#- --=========================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2001-2002 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#-------------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.6
#-
#- Release Information    : PrimeCell(TM)-PL172-r2p3-00rel0
#-
#-------------------------------------------------------------------------------
#-  Purpose  : 
#-             makefile for Verilog Integration Trickbox files
#-
#- --=========================================================================--

MODULES = Ahbif.v \
          AhbRegBlock.v \
          Ahbparam.v \
          AhbSlave.v
 
TEST_ENV = TICTALK

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

#- --=============================== END =====================================--
