#- --=================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- ---------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.5
#-
#- Release Information    : PrimeCell(TM)-PL190-REL1v1
#-
#- ---------------------------------------------------------------------
#- Purpose  :
#-            makefile for VHDL Trickbox files
#-
#- --=================================================================--

MODULES =  VicTrPackage.vhd \
           VicTrAhbif.vhd \
           VicTrIntReq.vhd \
           VicTrVectBank.vhd \
           VicTrProtChkr.vhd \
           VicTrick.vhd

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk 

################################# End ##################################
