library verilog;
use verilog.vl_types.all;
entity ARM7TDMI_timing is
    port(
        A               : out    vl_logic_vector(31 downto 0);
        ABE             : in     vl_logic;
        ABORT           : in     vl_logic;
        ALE             : in     vl_logic;
        APE             : in     vl_logic;
        BIGEND          : in     vl_logic;
        BL              : in     vl_logic_vector(3 downto 0);
        BREAKPT         : in     vl_logic;
        BUSDIS          : out    vl_logic;
        BUSEN           : in     vl_logic;
        COMMRX          : out    vl_logic;
        COMMTX          : out    vl_logic;
        CPA             : in     vl_logic;
        CPB             : in     vl_logic;
        D               : inout  vl_logic_vector(31 downto 0);
        DBE             : in     vl_logic;
        DBGACK          : out    vl_logic;
        DBGEN           : in     vl_logic;
        DBGRQ           : in     vl_logic;
        DBGRQI          : out    vl_logic;
        DIN             : in     vl_logic_vector(31 downto 0);
        DOUT            : out    vl_logic_vector(31 downto 0);
        DRIVEBS         : out    vl_logic;
        ECLK            : out    vl_logic;
        ECAPCLK         : out    vl_logic;
        ECAPCLKBS       : out    vl_logic;
        EXTERN0         : in     vl_logic;
        EXTERN1         : in     vl_logic;
        HIGHZ           : out    vl_logic;
        ICAPCLKBS       : out    vl_logic;
        IR              : out    vl_logic_vector(3 downto 0);
        ISYNC           : in     vl_logic;
        LOCK            : out    vl_logic;
        MAS             : out    vl_logic_vector(1 downto 0);
        MCLK            : in     vl_logic;
        nCPI            : out    vl_logic;
        nENIN           : in     vl_logic;
        nENOUT          : out    vl_logic;
        nENOUTI         : out    vl_logic;
        nEXEC           : out    vl_logic;
        nFIQ            : in     vl_logic;
        nHIGHZ          : out    vl_logic;
        nIRQ            : in     vl_logic;
        nM              : out    vl_logic_vector(4 downto 0);
        nMREQ           : out    vl_logic;
        nOPC            : out    vl_logic;
        nRESET          : in     vl_logic;
        nRW             : out    vl_logic;
        nTDOEN          : out    vl_logic;
        nTRANS          : out    vl_logic;
        nTRST           : in     vl_logic;
        nWAIT           : in     vl_logic;
        PCLKBS          : out    vl_logic;
        RANGEOUT0       : out    vl_logic;
        RANGEOUT1       : out    vl_logic;
        RSTCLKBS        : out    vl_logic;
        SCREG           : out    vl_logic_vector(3 downto 0);
        SDINBS          : out    vl_logic;
        SDOUTBS         : in     vl_logic;
        SEQ             : out    vl_logic;
        SHCLKBS         : out    vl_logic;
        SHCLK2BS        : out    vl_logic;
        TAPSM           : out    vl_logic_vector(3 downto 0);
        TBE             : in     vl_logic;
        TBIT            : out    vl_logic;
        TCK             : in     vl_logic;
        TCK1            : out    vl_logic;
        TCK2            : out    vl_logic;
        TDI             : in     vl_logic;
        TDO             : out    vl_logic;
        TMS             : in     vl_logic;
        r0              : out    vl_logic_vector(31 downto 0);
        r1              : out    vl_logic_vector(31 downto 0);
        r2              : out    vl_logic_vector(31 downto 0);
        r3              : out    vl_logic_vector(31 downto 0);
        r4              : out    vl_logic_vector(31 downto 0);
        r5              : out    vl_logic_vector(31 downto 0);
        r6              : out    vl_logic_vector(31 downto 0);
        r7              : out    vl_logic_vector(31 downto 0);
        r8              : out    vl_logic_vector(31 downto 0);
        r9              : out    vl_logic_vector(31 downto 0);
        r10             : out    vl_logic_vector(31 downto 0);
        r11             : out    vl_logic_vector(31 downto 0);
        r12             : out    vl_logic_vector(31 downto 0);
        r13             : out    vl_logic_vector(31 downto 0);
        r14             : out    vl_logic_vector(31 downto 0);
        r15             : out    vl_logic_vector(31 downto 0);
        r8fiq           : out    vl_logic_vector(31 downto 0);
        r9fiq           : out    vl_logic_vector(31 downto 0);
        r10fiq          : out    vl_logic_vector(31 downto 0);
        r11fiq          : out    vl_logic_vector(31 downto 0);
        r12fiq          : out    vl_logic_vector(31 downto 0);
        r13fiq          : out    vl_logic_vector(31 downto 0);
        r14fiq          : out    vl_logic_vector(31 downto 0);
        r13irq          : out    vl_logic_vector(31 downto 0);
        r14irq          : out    vl_logic_vector(31 downto 0);
        r13svc          : out    vl_logic_vector(31 downto 0);
        r14svc          : out    vl_logic_vector(31 downto 0);
        r13abt          : out    vl_logic_vector(31 downto 0);
        r14abt          : out    vl_logic_vector(31 downto 0);
        r13und          : out    vl_logic_vector(31 downto 0);
        r14und          : out    vl_logic_vector(31 downto 0);
        CPSR            : out    vl_logic_vector(31 downto 0);
        SPSRfiq         : out    vl_logic_vector(31 downto 0);
        SPSRirq         : out    vl_logic_vector(31 downto 0);
        SPSRsvc         : out    vl_logic_vector(31 downto 0);
        SPSRabt         : out    vl_logic_vector(31 downto 0);
        SPSRund         : out    vl_logic_vector(31 downto 0);
        icewp0addr      : out    vl_logic_vector(31 downto 0);
        icewp0amask     : out    vl_logic_vector(31 downto 0);
        icewp0data      : out    vl_logic_vector(31 downto 0);
        icewp0dmask     : out    vl_logic_vector(31 downto 0);
        icewp0ctl       : out    vl_logic_vector(8 downto 0);
        icewp0cmask     : out    vl_logic_vector(7 downto 0);
        icewp1addr      : out    vl_logic_vector(31 downto 0);
        icewp1amask     : out    vl_logic_vector(31 downto 0);
        icewp1data      : out    vl_logic_vector(31 downto 0);
        icewp1dmask     : out    vl_logic_vector(31 downto 0);
        icewp1ctl       : out    vl_logic_vector(8 downto 0);
        icewp1cmask     : out    vl_logic_vector(7 downto 0);
        icedbgctl       : out    vl_logic_vector(2 downto 0);
        icedbgstatus    : out    vl_logic_vector(3 downto 0)
    );
end ARM7TDMI_timing;
