set_dont_touch [list pARM_RESET ] 
set_dont_touch [list pARM_OSC   ]
set_dont_touch [list pARM_TRST  ]
set_dont_touch [list pARM_TMS   ]
set_dont_touch [list pARM_TCK   ]
set_dont_touch [list pARM_TDI   ]
set_dont_touch [list pARM_TDO   ]
set_dont_touch [list pTEST_MODE ]
set_dont_touch [list pBOOT_MODE ]
set_dont_touch [list pI2C0_SCL0 ]
set_dont_touch [list pI2C0_SCL1 ]
set_dont_touch [list pI2C0_SDA0 ]
set_dont_touch [list pI2C0_SDA1 ]
set_dont_touch [list pARM_CS    ]
set_dont_touch [list pV5_CS     ]
set_dont_touch [list pARM_OE    ]
set_dont_touch [list pARM_WE    ]
set_dont_touch [list pARM_ADR00 ]
set_dont_touch [list pARM_ADR01 ]
set_dont_touch [list pARM_ADR02 ]
set_dont_touch [list pARM_ADR03 ]
set_dont_touch [list pARM_ADR04 ]
set_dont_touch [list pARM_ADR05 ]
set_dont_touch [list pARM_ADR06 ]
set_dont_touch [list pARM_ADR07 ]
set_dont_touch [list pARM_ADR08 ]
set_dont_touch [list pARM_ADR09 ]
set_dont_touch [list pARM_ADR10 ]
set_dont_touch [list pARM_ADR11 ]
set_dont_touch [list pARM_ADR12 ]
set_dont_touch [list pARM_ADR13 ]
set_dont_touch [list pARM_ADR14 ]
set_dont_touch [list pARM_ADR15 ]
set_dont_touch [list pARM_ADR16 ]
set_dont_touch [list pARM_DAT00 ]
set_dont_touch [list pARM_DAT01 ]
set_dont_touch [list pARM_DAT02 ]
set_dont_touch [list pARM_DAT03 ]
set_dont_touch [list pARM_DAT04 ]
set_dont_touch [list pARM_DAT05 ]
set_dont_touch [list pARM_DAT06 ]
set_dont_touch [list pARM_DAT07 ]
set_dont_touch [list pARM_DAT08 ]
set_dont_touch [list pARM_DAT09 ]
set_dont_touch [list pARM_DAT10 ]
set_dont_touch [list pARM_DAT11 ]
set_dont_touch [list pARM_DAT12 ]
set_dont_touch [list pARM_DAT13 ]
set_dont_touch [list pARM_DAT14 ]
set_dont_touch [list pARM_DAT15 ]
set_dont_touch [list pGPIO00    ]
set_dont_touch [list pGPIO01    ]
set_dont_touch [list pGPIO02    ]
set_dont_touch [list pGPIO03    ]
set_dont_touch [list pGPIO04    ]
set_dont_touch [list pGPIO05    ]
set_dont_touch [list pGPIO06    ]
set_dont_touch [list pGPIO07    ]
set_dont_touch [list pGPIO10    ]
set_dont_touch [list pGPIO11    ]
set_dont_touch [list pGPIO12    ]
set_dont_touch [list pGPIO13    ]
set_dont_touch [list pGPIO14    ]
set_dont_touch [list pGPIO15    ]
set_dont_touch [list pGPIO16    ]
set_dont_touch [list pGPIO17    ]
set_dont_touch [list pGPIO20    ]
set_dont_touch [list pGPIO21    ]
set_dont_touch [list pGPIO22    ]
set_dont_touch [list pGPIO23    ]
set_dont_touch [list pGPIO24    ]
set_dont_touch [list pGPIO25    ]
set_dont_touch [list pGPIO26    ]
set_dont_touch [list pGPIO27    ]
set_dont_touch [list pGPIO30    ]
set_dont_touch [list pGPIO31    ]
set_dont_touch [list pGPIO32    ]
set_dont_touch [list pGPIO33    ]
set_dont_touch [list pGPIO34    ]
set_dont_touch [list pGPIO35    ]
set_dont_touch [list pGPIO36    ]
set_dont_touch [list pGPIO37    ]

set_dont_touch [list pFmTEN     ]
set_dont_touch [list pFmTTMR    ]

#/* CTS clock/reset */
set_dont_touch [list uDTSDI002Top/uAPB_PowerManager/SCKBUF]
set_dont_touch [list uDTSDI002Top/uAPB_PowerManager/UCKBUF]
set_dont_touch [list uDTSDI002Top/uAPB_PowerManager/ACKBUF]

set_dont_touch [list uDTSDI002Top/uResetCntl/SRSTBUF]
set_dont_touch [list uDTSDI002Top/uResetCntl/WRSTBUF]

# Dont touch Scan Enable for input pad mux(hook)
set_dont_touch [list gSCANEN]
