#- --=================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- ---------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.6
#-
#- Release Information    : PrimeCell(TM)-PL190-REL1v1
#-
#- ---------------------------------------------------------------------
#- Purpose :
#-           A makefile to initiate BusTalk simulations 
#-
#- --=================================================================--

#- List of directories to make. Order is important
DIRS = common bid reader buswatcher vr trickbox tbench

TEST_ENV = BUSTALK

include $(GLOBAL)/$(SIMULATOR)/DirSimMakefile.mk

################################ End ###################################
