#- --=========================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000-2004 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#-------------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.6
#-
#- Release Information    : PrimeCell(TM)-PL080-r1p3-00rel0
#-
#-------------------------------------------------------------------------------
#-  Purpose  : 
#-             Standard Verilog Library Makefile
#-
#- --=========================================================================--

MODULES = DmacRevAnd.v \
          DmacRqstSync.v \
          DmacRspRoute.v \
          DmacAhbSlaveIf.v \
          DmacLiteMaster.v \
          DmacArbiter.v \
          DmacMasterWrap.v \
          DmacAhbMaster.v \
          DmacChPckUnpck.v \
          DmacChRegFile.v \
          DmacChSrcXfer.v \
          DmacChReqMask.v \
          DmacChReqProc.v \
          DmacChRegBlock.v \
          DmacChDstXfer.v \
          DmacChLLILoad.v \
          DmacChannel.v \
          Dmac.v

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

#################################### End #######################################
