@TM:1162159818
@N: FX164 :"":0:0:0:-1|The option to pack flops in the IOB has not been specified 
@W: MO111 :"":0:0:0:-1|tristate driver uartenb_t on net uartenb has its enable tied to GND (module UART_TOP) 
@W: MO111 :"":0:0:0:-1|tristate driver swrstb_t on net swrstb has its enable tied to GND (module UART_TOP) 
@W: MO111 :"":0:0:0:-1|tristate driver stopbit_t on net stopbit has its enable tied to GND (module UART_TOP) 
@W: MO111 :"":0:0:0:-1|tristate driver statusrstb_t on net statusrstb has its enable tied to GND (module UART_TOP) 
@W: MO111 :"":0:0:0:-1|tristate driver parity_t[1] on net parity[1] has its enable tied to GND (module UART_TOP) 
@W: MO111 :"":0:0:0:-1|tristate driver parity_t[0] on net parity[0] has its enable tied to GND (module UART_TOP) 
@W: MO111 :"":0:0:0:-1|tristate driver fifordb_t on net fifordb has its enable tied to GND (module UART_TOP) 
@W: MO111 :"":0:0:0:-1|tristate driver fifodata_tx_t[7] on net fifodata_tx[7] has its enable tied to GND (module UART_TOP) 
@W: MO111 :"":0:0:0:-1|tristate driver fifodata_tx_t[6] on net fifodata_tx[6] has its enable tied to GND (module UART_TOP) 
@W: MO111 :"":0:0:0:-1|tristate driver fifodata_tx_t[5] on net fifodata_tx[5] has its enable tied to GND (module UART_TOP) 
@W: MO111 :"":0:0:0:-1|tristate driver fifodata_tx_t[4] on net fifodata_tx[4] has its enable tied to GND (module UART_TOP) 
@W: MO111 :"":0:0:0:-1|tristate driver fifodata_tx_t[3] on net fifodata_tx[3] has its enable tied to GND (module UART_TOP) 
@W: MO111 :"":0:0:0:-1|tristate driver fifodata_tx_t[2] on net fifodata_tx[2] has its enable tied to GND (module UART_TOP) 
@W: MO111 :"":0:0:0:-1|tristate driver fifodata_tx_t[1] on net fifodata_tx[1] has its enable tied to GND (module UART_TOP) 
@W: MO111 :"":0:0:0:-1|tristate driver fifodata_tx_t[0] on net fifodata_tx[0] has its enable tied to GND (module UART_TOP) 
@W: MO111 :"":0:0:0:-1|tristate driver databit_t on net databit has its enable tied to GND (module UART_TOP) 
@N: MT195 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT197 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@N: MT204 :"":0:0:0:-1|Autoconstrain Mode is ON
@TM:1162207989
@W:  :"c:\project\uart_lib\hdl\regblk.v":1:1:179:10|M
@TM:1162159818
@N:  :"c:\project\uart_lib\hdl\regblk.v":13:7:13:12|Synthesizing module RegBlk
@TM:1162161154
@W:  :"c:\project\uart_lib\hdl\regblk.v":57:14:57:19|M
@W:  :"c:\project\uart_lib\hdl\regblk.v":57:14:57:19|M
@W:  :"c:\project\uart_lib\hdl\regblk.v":57:14:57:19|M
@W:  :"c:\project\uart_lib\hdl\regblk.v":57:14:57:19|M
@W:  :"c:\project\uart_lib\hdl\regblk.v":57:14:57:19|M
@W:  :"c:\project\uart_lib\hdl\regblk.v":57:14:57:19|M
@W:  :"c:\project\uart_lib\hdl\regblk.v":57:14:57:19|M
@W:  :"c:\project\uart_lib\hdl\regblk.v":57:14:57:19|M
@W:  :"c:\project\uart_lib\hdl\regblk.v":57:14:57:19|M
@W:  :"c:\project\uart_lib\hdl\regblk.v":57:14:57:19|M
@W:  :"c:\project\uart_lib\hdl\regblk.v":57:14:57:19|M
@W:  :"c:\project\uart_lib\hdl\regblk.v":57:14:57:19|M
@W: CL159 :"c:\project\uart_lib\hdl\regblk.v":69:14:69:26|M
@W: CL159 :"c:\project\uart_lib\hdl\regblk.v":70:14:70:25|M
@W: CL159 :"c:\project\uart_lib\hdl\regblk.v":71:14:71:25|M
@W:  :"c:\project\uart_lib\hdl\regblk.v":75:14:75:20|M
@W: CL157 :"c:\project\uart_lib\hdl\regblk.v":75:14:75:20|M
@W: MO111 :"c:\project\uart_lib\hdl\regblk.v":75:14:75:20|M
@W:  :"c:\project\uart_lib\hdl\regblk.v":76:14:76:24|M
@W: CL157 :"c:\project\uart_lib\hdl\regblk.v":76:14:76:24|M
@W: MO111 :"c:\project\uart_lib\hdl\regblk.v":76:14:76:24|M
@TM:1162159818
@W:  :"c:\project\uart_lib\hdl\regblk.v":77:14:77:20|M
@W: CL157 :"c:\project\uart_lib\hdl\regblk.v":77:14:77:20|M
@W: MO111 :"c:\project\uart_lib\hdl\regblk.v":77:14:77:20|M
@TM:1162161154
@W:  :"c:\project\uart_lib\hdl\regblk.v":80:14:80:19|M
@W: CL157 :"c:\project\uart_lib\hdl\regblk.v":80:14:80:19|M
@W: MO111 :"c:\project\uart_lib\hdl\regblk.v":80:14:80:19|M
@W:  :"c:\project\uart_lib\hdl\regblk.v":82:14:82:23|M
@W: CL157 :"c:\project\uart_lib\hdl\regblk.v":82:14:82:23|M
@W: MO111 :"c:\project\uart_lib\hdl\regblk.v":82:14:82:23|M
@W:  :"c:\project\uart_lib\hdl\regblk.v":83:14:83:20|M
@W: CL157 :"c:\project\uart_lib\hdl\regblk.v":83:14:83:20|M
@W: MO111 :"c:\project\uart_lib\hdl\regblk.v":83:14:83:20|M
@W:  :"c:\project\uart_lib\hdl\regblk.v":84:14:84:19|M
@W: CL156 :"c:\project\uart_lib\hdl\regblk.v":84:14:84:19|M
@W: CL157 :"c:\project\uart_lib\hdl\regblk.v":84:14:84:19|M
@W: MO111 :"c:\project\uart_lib\hdl\regblk.v":84:14:84:19|M
@TM:1162159818
@W:  :"c:\project\uart_lib\hdl\regblk.v":86:14:86:20|M
@W: CL157 :"c:\project\uart_lib\hdl\regblk.v":86:14:86:20|M
@W: MO111 :"c:\project\uart_lib\hdl\regblk.v":86:14:86:20|M
@TM:1162161154
@W: CG133 :"c:\project\uart_lib\hdl\regblk.v":134:13:134:21|M
@TM:1162161777
@W: BN132 :"c:\project\uart_lib\hdl\regblk.v":168:1:168:4|M
@W: BN132 :"c:\project\uart_lib\hdl\regblk.v":168:1:168:4|M
@W: BN132 :"c:\project\uart_lib\hdl\regblk.v":168:1:168:4|M
@TM:1162161154
@W: CL118 :"c:\project\uart_lib\hdl\regblk.v":168:1:168:4|M
@TM:1162207980
@W: CL171 :"c:\project\uart_lib\hdl\regblk.v":168:1:168:4|M
@TM:1162161154
@W: MO127 :"c:\project\uart_lib\hdl\regblk.v":168:1:168:4|M
@W: CL190 :"c:\project\uart_lib\hdl\regblk.v":188:3:188:8|M
@W: BN116 :"c:\project\uart_lib\hdl\regblk.v":260:3:260:8|M
@TM:1162207717
@N:  :"c:\project\uart_lib\hdl\regblk.v":298:3:298:8|M
@N: MF179 :"c:\project\uart_lib\hdl\regblk.v":307:11:307:31|M
@TM:1162207980
@W: CL190 :"c:\project\uart_lib\hdl\regblk.v":337:3:337:8|M
@W: BN116 :"c:\project\uart_lib\hdl\regblk.v":347:3:347:8|M
@W: BN116 :"c:\project\uart_lib\hdl\regblk.v":358:3:358:8|M
@N: CG179 :"c:\project\uart_lib\hdl\regblk.v":367:22:367:35|M
@W: BN132 :"c:\project\uart_lib\hdl\regblk.v":370:3:370:8|M
@N: CG179 :"c:\project\uart_lib\hdl\regblk.v":379:22:379:36|M
@TM:1162207469
@W:  :"c:\project\uart_lib\hdl\rxblock.v":1:1:735:9|M
@TM:1162159818
@N:  :"c:\project\uart_lib\hdl\rxblock.v":13:7:13:13|Synthesizing module RxBlock
@TM:1162161154
@W: CL159 :"c:\project\uart_lib\hdl\rxblock.v":46:13:46:18|M
@W: CG133 :"c:\project\uart_lib\hdl\rxblock.v":139:13:139:13|M
@W: BN116 :"c:\project\uart_lib\hdl\rxblock.v":187:3:187:8|M
@N: CG179 :"c:\project\uart_lib\hdl\rxblock.v":196:24:196:40|M
@W: CL169 :"c:\project\uart_lib\hdl\rxblock.v":203:3:203:8|M
@W: CL169 :"c:\project\uart_lib\hdl\rxblock.v":212:3:212:8|M
@W: CL169 :"c:\project\uart_lib\hdl\rxblock.v":221:3:221:8|M
@TM:1162161777
@W: BN132 :"c:\project\uart_lib\hdl\rxblock.v":253:3:253:8|M
@W: BN132 :"c:\project\uart_lib\hdl\rxblock.v":270:3:270:8|M
@TM:1162161154
@N: CG179 :"c:\project\uart_lib\hdl\rxblock.v":280:25:280:40|M
@W: BN116 :"c:\project\uart_lib\hdl\rxblock.v":287:3:287:8|M
@W: BN116 :"c:\project\uart_lib\hdl\rxblock.v":337:3:337:8|M
@W: BN132 :"c:\project\uart_lib\hdl\rxblock.v":337:3:337:8|M
@W: CL169 :"c:\project\uart_lib\hdl\rxblock.v":337:3:337:8|M
@TM:1162161777
@N: FX235 :"c:\project\uart_lib\hdl\rxblock.v":592:3:592:8|M
@TM:1162207461
@W: CL118 :"c:\project\uart_lib\hdl\rxblock.v":607:1:607:4|M
@TM:1162159818
@N:  :"c:\project\uart_lib\hdl\txblock.v":14:7:14:13|Synthesizing module TxBlock
@TM:1162161154
@W: CL159 :"c:\project\uart_lib\hdl\txblock.v":44:13:44:18|M
@TM:1162161161
@W:  :"c:\project\uart_lib\hdl\txblock.v":163:1:163:4|M
@TM:1162161154
@W: CL118 :"c:\project\uart_lib\hdl\txblock.v":163:1:163:4|M
@N: CG179 :"c:\project\uart_lib\hdl\txblock.v":258:18:258:25|M
@W: CL169 :"c:\project\uart_lib\hdl\txblock.v":266:3:266:8|M
@TM:1162161161
@W:  :"c:\project\uart_lib\hdl\txblock.v":455:3:455:8|M
@TM:1162207628
@W: CG296 :"c:\project\uart_lib\hdl\txblock.v":464:14:466:3|M
@W: CL118 :"c:\project\uart_lib\hdl\txblock.v":470:1:470:4|M
@W: CG290 :"c:\project\uart_lib\hdl\txblock.v":472:29:472:38|M
@W: CG290 :"c:\project\uart_lib\hdl\txblock.v":519:3:519:11|M
@W: CG290 :"c:\project\uart_lib\hdl\txblock.v":524:3:524:11|M
@W: CG290 :"c:\project\uart_lib\hdl\txblock.v":527:6:527:7|M
@W: CG290 :"c:\project\uart_lib\hdl\txblock.v":534:3:534:15|M
@W: CG290 :"c:\project\uart_lib\hdl\txblock.v":539:3:539:11|M
@W: CG290 :"c:\project\uart_lib\hdl\txblock.v":542:6:542:7|M
@W: CG290 :"c:\project\uart_lib\hdl\txblock.v":553:3:553:11|M
@N: FX235 :"c:\project\uart_lib\hdl\txblock.v":582:3:582:8|M
@N: FX235 :"c:\project\uart_lib\hdl\txblock.v":582:3:582:8|M
@N: FX235 :"c:\project\uart_lib\hdl\txblock.v":590:3:590:8|M
@N: CL134 :"c:\project\uart_lib\hdl\txblock.v":601:4:601:9|M
@N: MF135 :"c:\project\uart_lib\hdl\txblock.v":601:4:601:9|M
@TM:1162159818
@N:  :"c:\project\uart_lib\hdl\uart_top_struct.v":13:7:13:14|Synthesizing module UART_TOP
