@TM:1165977471
@W: BN116 :"":0:0:0:-1|Removing sequential instance current_state[17] of view:PrimLib.dff(prim) because there are no references to its outputs 
@TM:1165976122
@N: BN191 :"":0:0:0:-1|Writing property annotation file D:\Projects\UART\FPGADV\UART_lib\syn\synplify\rev_1\uart_top_struct.tap.
@N: BN225 :"":0:0:0:-1|Writing default property annotation file D:\Projects\UART\FPGADV\UART_lib\syn\synplify\rev_1\uart_top_struct.map.
@N: FX164 :"":0:0:0:-1|The option to pack flops in the IOB has not been specified 
@TM:1169188369
@N: MF234 :"":0:0:0:-1|Hierarchical island-based critical path report is located in D:\Projects\UART\FPGADV\UART_lib\syn\synplify\rev_1\uart_top_struct.tah 
@TM:1165976122
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF258 :"":0:0:0:-1|Gated clock conversion disabled 
@N: MT195 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT197 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@N: MT206 :"":0:0:0:-1|Autoconstrain Mode is ON
@N: CG364 :"d:\projects\uart\fpgadv\uart_lib\hdl\regblk.v":13:7:13:12|Synthesizing module RegBlk
@W: CL209 :"d:\projects\uart\fpgadv\uart_lib\hdl\regblk.v":55:14:55:19|M
@W: CL234 :"d:\projects\uart\fpgadv\uart_lib\hdl\regblk.v":55:14:55:19|M
@TM:1169188368
@N: FX271 :"d:\projects\uart\fpgadv\uart_lib\hdl\regblk.v":194:3:194:8|M
@TM:1169188367
@N: FX271 :"d:\projects\uart\fpgadv\uart_lib\hdl\regblk.v":224:3:224:8|M
@TM:1165976924
@N:  :"d:\projects\uart\fpgadv\uart_lib\hdl\regblk.v":396:3:396:8|M
@N: CG179 :"d:\projects\uart\fpgadv\uart_lib\hdl\regblk.v":405:22:405:35|M
@N: MF179 :"d:\projects\uart\fpgadv\uart_lib\hdl\regblk.v":414:11:414:40|M
@N: CG179 :"d:\projects\uart\fpgadv\uart_lib\hdl\regblk.v":417:22:417:36|M
@TM:1165976122
@N: CG364 :"d:\projects\uart\fpgadv\uart_lib\hdl\rxblock.v":13:7:13:13|Synthesizing module RxBlock
@N: CG179 :"d:\projects\uart\fpgadv\uart_lib\hdl\rxblock.v":222:24:222:40|M
@N: CL134 :"d:\projects\uart\fpgadv\uart_lib\hdl\rxblock.v":247:3:247:8|M
@TM:1169188358
@W: CL132 :"d:\projects\uart\fpgadv\uart_lib\hdl\rxblock.v":257:24:257:42|M
@W: CL133 :"d:\projects\uart\fpgadv\uart_lib\hdl\rxblock.v":257:24:257:42|M
@TM:1165976122
@N: CG179 :"d:\projects\uart\fpgadv\uart_lib\hdl\rxblock.v":332:25:332:40|M
@TM:1165977470
@W: BN132 :"d:\projects\uart\fpgadv\uart_lib\hdl\rxblock.v":388:3:388:8|M
@TM:1165976814
@N: FX271 :"d:\projects\uart\fpgadv\uart_lib\hdl\rxblock.v":388:3:388:8|M
@TM:1165977471
@W: BN116 :"d:\projects\uart\fpgadv\uart_lib\hdl\rxblock.v":643:3:643:8|M
@TM:1165977468
@N: CL201 :"d:\projects\uart\fpgadv\uart_lib\hdl\rxblock.v":643:3:643:8|M
@TM:1165977465
@N: CG347 :"d:\projects\uart\fpgadv\uart_lib\hdl\rxblock.v":658:28:658:40|M
@N: CG346 :"d:\projects\uart\fpgadv\uart_lib\hdl\rxblock.v":658:42:658:50|M
@TM:1165976122
@N: CG364 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":14:7:14:13|Synthesizing module TxBlock
@N: CG347 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":163:33:163:45|M
@N: CG346 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":163:47:163:55|M
@N: CG179 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":257:18:257:25|M
@W: BN116 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":265:3:265:8|M
@TM:1169188367
@N: FX271 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":265:3:265:8|M
@N: FX271 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":280:6:280:9|M
@TM:1165976122
@N: CG347 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":280:31:280:43|M
@N: CG346 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":280:45:280:53|M
@TM:1165977598
@N: CL201 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":454:3:454:8|M
@TM:1165976122
@N: CG347 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":472:26:472:38|M
@N: CG346 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":472:40:472:48|M
@TM:1169188367
@N: FX271 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":600:3:600:8|M
@N: FX271 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":607:17:607:31|M
@TM:1169188358
@N: CL134 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":613:4:613:9|M
@W: CL169 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":613:4:613:9|M
@TM:1169188365
@N: MF135 :"d:\projects\uart\fpgadv\uart_lib\hdl\txblock.v":613:4:613:9|M
@TM:1165976122
@N: CG364 :"d:\projects\uart\fpgadv\uart_lib\hdl\uart_top_struct.v":13:7:13:14|Synthesizing module UART_TOP
@TM:1169188358
@W: CL234 :"d:\projects\uart\fpgadv\uart_lib\hdl\uart_top_struct.v":32:14:32:18|M
@W: CS149 :"d:\projects\uart\fpgadv\uart_lib\hdl\uart_top_struct.v":90:19:90:23|M
