#- --=========================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2002 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- -----------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.7
#-
#- Release Information    : PrimeCell(TM)-PL192-r0p0-00rel0
#-
#- -----------------------------------------------------------------------------
#- Purpose  :
#-            makefile for Verilog Trickbox files
#-
#- --=========================================================================--

MODULES = VicTrParams.v \
          VicTrAhbif.v \
          VicTrIntReqLog.v \
          VicTrFiqIntrLog.v \
          VicTrIrqIntrLog.v \
          VicTrIrqPriLog.v \
          VicMirTrickbox.v \
          VicTrProtChkr.v \
          VicTrick.v 

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk 

################################# End ##################################
