#####################################################

#  Created by Design Compiler write_sdc on Fri Jun 30 17:46:05 2006

#####################################################
set sdc_version 1.4

create_clock -period 7.5 -waveform {0 3.75} [get_ports {ACLK}]
create_clock -period 7.5 -waveform {0 3.75} [get_ports {FCLK}]
create_generated_clock -name "nACLK" -source [get_ports {ACLK}] -divide_by 1 -invert [get_pins {ACKBUF/Y}]
create_generated_clock -name "PCLK" -source [get_ports {ACLK}] -divide_by 2 [get_pins {PCKBUF/Y}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[0]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[0]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[1]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[1]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[2]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[2]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[3]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[3]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[4]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[4]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[5]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[5]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[6]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[6]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[7]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[7]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[8]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[8]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[9]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[9]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[10]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[10]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[11]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[11]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[12]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[12]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[13]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[13]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[14]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[14]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[15]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[15]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[16]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[16]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[17]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[17]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[18]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[18]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[19]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[19]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[20]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[20]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[21]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[21]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[22]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[22]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[23]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[23]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[24]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[24]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[25]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[25]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[26]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[26]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[27]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[27]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[28]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[28]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[29]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[29]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[30]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[30]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWDATA[31]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[31]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PWRITE}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWRITE}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PADDR[2]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PADDR[2]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PADDR[3]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PADDR[3]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PADDR[4]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PADDR[4]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PADDR[5]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PADDR[5]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PADDR[6]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PADDR[6]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PADDR[7]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PADDR[7]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PENABLE}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PENABLE}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PSEL}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PSEL}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PRESETB}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PRESETB}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[0]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[1]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[2]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[3]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[4]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[5]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[6]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[7]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[8]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[9]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[10]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[11]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[12]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[13]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[14]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[15]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[16]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[17]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[18]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[19]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[20]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[21]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[22]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[23]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[24]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[25]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[26]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[27]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[28]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[29]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[30]}]
set_input_delay 0 -clock "FCLK" [get_ports {SD_DQI[31]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {RReady}]
set_input_delay 0 -min -clock "ACLK" [get_ports {RReady}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARBurst[0]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARBurst[0]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARBurst[1]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARBurst[1]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARValid}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARValid}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARLen[0]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARLen[0]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARLen[1]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARLen[1]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARLen[2]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARLen[2]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARLen[3]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARLen[3]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARId[0]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARId[0]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARId[1]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARId[1]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARId[2]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARId[2]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARId[3]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARId[3]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[0]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[0]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[1]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[1]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[2]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[2]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[3]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[3]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[4]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[4]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[5]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[5]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[6]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[6]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[7]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[7]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[8]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[8]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[9]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[9]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[10]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[10]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[11]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[11]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[12]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[12]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[13]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[13]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[14]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[14]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[15]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[15]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[16]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[16]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[17]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[17]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[18]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[18]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[19]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[19]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[20]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[20]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARAddr[21]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARAddr[21]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {BReady}]
set_input_delay 0 -min -clock "ACLK" [get_ports {BReady}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WId[0]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WId[0]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WId[1]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WId[1]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WId[2]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WId[2]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WId[3]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WId[3]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WValid}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WValid}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[0]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[0]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[1]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[1]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[2]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[2]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[3]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[3]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[4]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[4]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[5]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[5]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[6]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[6]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[7]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[7]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[8]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[8]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[9]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[9]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[10]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[10]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[11]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[11]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[12]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[12]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[13]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[13]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[14]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[14]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[15]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[15]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[16]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[16]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[17]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[17]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[18]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[18]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[19]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[19]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[20]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[20]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[21]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[21]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[22]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[22]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[23]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[23]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[24]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[24]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[25]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[25]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[26]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[26]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[27]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[27]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[28]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[28]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[29]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[29]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[30]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[30]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WData[31]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WData[31]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WStrb[0]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WStrb[0]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WStrb[1]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WStrb[1]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WStrb[2]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WStrb[2]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WStrb[3]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WStrb[3]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {WLast}]
set_input_delay 0 -min -clock "ACLK" [get_ports {WLast}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWBurst[0]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWBurst[0]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWBurst[1]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWBurst[1]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWValid}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWValid}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWLen[0]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWLen[0]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWLen[1]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWLen[1]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWLen[2]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWLen[2]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWLen[3]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWLen[3]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWId[0]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWId[0]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWId[1]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWId[1]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWId[2]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWId[2]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWId[3]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWId[3]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[0]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[0]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[1]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[1]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[2]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[2]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[3]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[3]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[4]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[4]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[5]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[5]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[6]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[6]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[7]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[7]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[8]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[8]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[9]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[9]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[10]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[10]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[11]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[11]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[12]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[12]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[13]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[13]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[14]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[14]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[15]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[15]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[16]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[16]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[17]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[17]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[18]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[18]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[19]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[19]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[20]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[20]}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {AWAddr[21]}]
set_input_delay 0 -min -clock "ACLK" [get_ports {AWAddr[21]}]
set_input_delay 9 -max -clock "PCLK" [get_ports {PORESETB}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PORESETB}]
set_input_delay 5.25 -max -clock "ACLK" [get_ports {ARESETB}]
set_input_delay 0 -min -clock "ACLK" [get_ports {ARESETB}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[0]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[0]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[1]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[1]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[2]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[2]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[3]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[3]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[4]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[4]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[5]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[5]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[6]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[6]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[7]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[7]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[8]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[8]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[9]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[9]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[10]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[10]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[11]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[11]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[12]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[12]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[13]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[13]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[14]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[14]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[15]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[15]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[16]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[16]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[17]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[17]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[18]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[18]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[19]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[19]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[20]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[20]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[21]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[21]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[22]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[22]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[23]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[23]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[24]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[24]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[25]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[25]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[26]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[26]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[27]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[27]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[28]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[28]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[29]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[29]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[30]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[30]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[31]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[31]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQM[0]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQM[0]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQM[1]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQM[1]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQM[2]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQM[2]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQM[3]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQM[3]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[0]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[0]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[1]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[1]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[2]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[2]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[3]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[3]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[4]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[4]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[5]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[5]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[6]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[6]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[7]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[7]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[8]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[8]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[9]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[9]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[10]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[10]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[11]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[11]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[12]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[12]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[13]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[13]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[14]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[14]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[15]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[15]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[16]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[16]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[17]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[17]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[18]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[18]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[19]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[19]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[20]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[20]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[21]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[21]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[22]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[22]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[23]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[23]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[24]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[24]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[25]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[25]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[26]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[26]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[27]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[27]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[28]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[28]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[29]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[29]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[30]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[30]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQO[31]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQO[31]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_DQE}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_DQE}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_ADDR[0]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_ADDR[0]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_ADDR[1]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_ADDR[1]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_ADDR[2]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_ADDR[2]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_ADDR[3]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_ADDR[3]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_ADDR[4]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_ADDR[4]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_ADDR[5]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_ADDR[5]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_ADDR[6]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_ADDR[6]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_ADDR[7]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_ADDR[7]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_ADDR[8]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_ADDR[8]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_ADDR[9]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_ADDR[9]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_ADDR[10]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_ADDR[10]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_ADDR[11]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_ADDR[11]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_BADDR[0]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_BADDR[0]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_BADDR[1]}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_BADDR[1]}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_WEB}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_WEB}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_CASB}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_CASB}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_RASB}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_RASB}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_CSB}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_CSB}]
set_output_delay 2.25 -max -clock "ACLK" [get_ports {SD_CKE}]
set_output_delay 0 -min -clock "ACLK" [get_ports {SD_CKE}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RResp[0]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RResp[0]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RResp[1]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RResp[1]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RId[0]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RId[0]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RId[1]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RId[1]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RId[2]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RId[2]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RId[3]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RId[3]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RLast}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RLast}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RValid}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RValid}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[0]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[0]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[1]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[1]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[2]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[2]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[3]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[3]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[4]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[4]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[5]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[5]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[6]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[6]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[7]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[7]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[8]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[8]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[9]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[9]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[10]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[10]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[11]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[11]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[12]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[12]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[13]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[13]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[14]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[14]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[15]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[15]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[16]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[16]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[17]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[17]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[18]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[18]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[19]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[19]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[20]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[20]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[21]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[21]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[22]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[22]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[23]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[23]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[24]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[24]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[25]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[25]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[26]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[26]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[27]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[27]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[28]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[28]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[29]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[29]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[30]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[30]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {RData[31]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {RData[31]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {ARReady}]
set_output_delay -0 -min -clock "ACLK" [get_ports {ARReady}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {BId[0]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {BId[0]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {BId[1]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {BId[1]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {BId[2]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {BId[2]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {BId[3]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {BId[3]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {BValid}]
set_output_delay -0 -min -clock "ACLK" [get_ports {BValid}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {BResp[0]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {BResp[0]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {BResp[1]}]
set_output_delay -0 -min -clock "ACLK" [get_ports {BResp[1]}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {WReady}]
set_output_delay -0 -min -clock "ACLK" [get_ports {WReady}]
set_output_delay 4.5 -max -clock "ACLK" [get_ports {AWReady}]
set_output_delay -0 -min -clock "ACLK" [get_ports {AWReady}]
set_clock_transition -rise 0 [get_clocks {ACLK}]
set_clock_transition -fall 0 [get_clocks {ACLK}]
set_clock_transition -rise 0 [get_clocks {FCLK}]
set_clock_transition -fall 0 [get_clocks {FCLK}]
set_clock_uncertainty  0.675 -setup [get_ports {ACLK}]
set_clock_uncertainty  0.675 -setup [get_ports {FCLK}]
set_max_transition 2 [current_design]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {ARESETB}]
set_load -pin_load 0 [get_ports {ARESETB}]
set_disable_timing [get_ports {ARESETB}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {PORESETB}]
set_load -pin_load 0 [get_ports {PORESETB}]
set_disable_timing [get_ports {PORESETB}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {ACLK}]
set_load -pin_load 0 [get_ports {ACLK}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {FCLK}]
set_load -pin_load 0 [get_ports {FCLK}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[21]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[20]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[19]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[18]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[17]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[16]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[15]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[14]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[13]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[12]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[11]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[10]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[9]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[8]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[7]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[6]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[5]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[4]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[3]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[2]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[1]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWAddr[0]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {AWId[3]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {AWId[2]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {AWId[1]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {AWId[0]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {AWLen[3]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {AWLen[2]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {AWLen[1]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {AWLen[0]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {AWValid}]
set_load -pin_load 0.018316 [get_ports {AWReady}]
set_load -min -pin_load 0.018316 [get_ports {AWReady}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWBurst[1]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{AWBurst[0]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WLast}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WStrb[3]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WStrb[2]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WStrb[1]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WStrb[0]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[31]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[30]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[29]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[28]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[27]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[26]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[25]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[24]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[23]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[22]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[21]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[20]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[19]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[18]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[17]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[16]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[15]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[14]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[13]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[12]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[11]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{WData[10]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WData[9]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WData[8]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WData[7]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WData[6]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WData[5]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WData[4]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WData[3]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WData[2]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WData[1]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WData[0]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WValid}]
set_load -pin_load 0.018316 [get_ports {WReady}]
set_load -min -pin_load 0.018316 [get_ports {WReady}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WId[3]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WId[2]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WId[1]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {WId[0]}]
set_load -pin_load 0.018316 [get_ports {BResp[1]}]
set_load -min -pin_load 0.018316 [get_ports {BResp[1]}]
set_load -pin_load 0.018316 [get_ports {BResp[0]}]
set_load -min -pin_load 0.018316 [get_ports {BResp[0]}]
set_load -pin_load 0.018316 [get_ports {BValid}]
set_load -min -pin_load 0.018316 [get_ports {BValid}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {BReady}]
set_load -pin_load 0.018316 [get_ports {BId[3]}]
set_load -min -pin_load 0.018316 [get_ports {BId[3]}]
set_load -pin_load 0.018316 [get_ports {BId[2]}]
set_load -min -pin_load 0.018316 [get_ports {BId[2]}]
set_load -pin_load 0.018316 [get_ports {BId[1]}]
set_load -min -pin_load 0.018316 [get_ports {BId[1]}]
set_load -pin_load 0.018316 [get_ports {BId[0]}]
set_load -min -pin_load 0.018316 [get_ports {BId[0]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[21]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[20]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[19]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[18]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[17]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[16]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[15]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[14]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[13]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[12]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[11]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[10]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[9]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[8]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[7]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[6]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[5]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[4]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[3]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[2]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[1]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARAddr[0]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {ARId[3]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {ARId[2]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {ARId[1]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {ARId[0]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {ARLen[3]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {ARLen[2]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {ARLen[1]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {ARLen[0]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {ARValid}]
set_load -pin_load 0.018316 [get_ports {ARReady}]
set_load -min -pin_load 0.018316 [get_ports {ARReady}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARBurst[1]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{ARBurst[0]}]
set_load -pin_load 0.018316 [get_ports {RData[31]}]
set_load -min -pin_load 0.018316 [get_ports {RData[31]}]
set_load -pin_load 0.018316 [get_ports {RData[30]}]
set_load -min -pin_load 0.018316 [get_ports {RData[30]}]
set_load -pin_load 0.018316 [get_ports {RData[29]}]
set_load -min -pin_load 0.018316 [get_ports {RData[29]}]
set_load -pin_load 0.018316 [get_ports {RData[28]}]
set_load -min -pin_load 0.018316 [get_ports {RData[28]}]
set_load -pin_load 0.018316 [get_ports {RData[27]}]
set_load -min -pin_load 0.018316 [get_ports {RData[27]}]
set_load -pin_load 0.018316 [get_ports {RData[26]}]
set_load -min -pin_load 0.018316 [get_ports {RData[26]}]
set_load -pin_load 0.018316 [get_ports {RData[25]}]
set_load -min -pin_load 0.018316 [get_ports {RData[25]}]
set_load -pin_load 0.018316 [get_ports {RData[24]}]
set_load -min -pin_load 0.018316 [get_ports {RData[24]}]
set_load -pin_load 0.018316 [get_ports {RData[23]}]
set_load -min -pin_load 0.018316 [get_ports {RData[23]}]
set_load -pin_load 0.018316 [get_ports {RData[22]}]
set_load -min -pin_load 0.018316 [get_ports {RData[22]}]
set_load -pin_load 0.018316 [get_ports {RData[21]}]
set_load -min -pin_load 0.018316 [get_ports {RData[21]}]
set_load -pin_load 0.018316 [get_ports {RData[20]}]
set_load -min -pin_load 0.018316 [get_ports {RData[20]}]
set_load -pin_load 0.018316 [get_ports {RData[19]}]
set_load -min -pin_load 0.018316 [get_ports {RData[19]}]
set_load -pin_load 0.018316 [get_ports {RData[18]}]
set_load -min -pin_load 0.018316 [get_ports {RData[18]}]
set_load -pin_load 0.018316 [get_ports {RData[17]}]
set_load -min -pin_load 0.018316 [get_ports {RData[17]}]
set_load -pin_load 0.018316 [get_ports {RData[16]}]
set_load -min -pin_load 0.018316 [get_ports {RData[16]}]
set_load -pin_load 0.018316 [get_ports {RData[15]}]
set_load -min -pin_load 0.018316 [get_ports {RData[15]}]
set_load -pin_load 0.018316 [get_ports {RData[14]}]
set_load -min -pin_load 0.018316 [get_ports {RData[14]}]
set_load -pin_load 0.018316 [get_ports {RData[13]}]
set_load -min -pin_load 0.018316 [get_ports {RData[13]}]
set_load -pin_load 0.018316 [get_ports {RData[12]}]
set_load -min -pin_load 0.018316 [get_ports {RData[12]}]
set_load -pin_load 0.018316 [get_ports {RData[11]}]
set_load -min -pin_load 0.018316 [get_ports {RData[11]}]
set_load -pin_load 0.018316 [get_ports {RData[10]}]
set_load -min -pin_load 0.018316 [get_ports {RData[10]}]
set_load -pin_load 0.018316 [get_ports {RData[9]}]
set_load -min -pin_load 0.018316 [get_ports {RData[9]}]
set_load -pin_load 0.018316 [get_ports {RData[8]}]
set_load -min -pin_load 0.018316 [get_ports {RData[8]}]
set_load -pin_load 0.018316 [get_ports {RData[7]}]
set_load -min -pin_load 0.018316 [get_ports {RData[7]}]
set_load -pin_load 0.018316 [get_ports {RData[6]}]
set_load -min -pin_load 0.018316 [get_ports {RData[6]}]
set_load -pin_load 0.018316 [get_ports {RData[5]}]
set_load -min -pin_load 0.018316 [get_ports {RData[5]}]
set_load -pin_load 0.018316 [get_ports {RData[4]}]
set_load -min -pin_load 0.018316 [get_ports {RData[4]}]
set_load -pin_load 0.018316 [get_ports {RData[3]}]
set_load -min -pin_load 0.018316 [get_ports {RData[3]}]
set_load -pin_load 0.018316 [get_ports {RData[2]}]
set_load -min -pin_load 0.018316 [get_ports {RData[2]}]
set_load -pin_load 0.018316 [get_ports {RData[1]}]
set_load -min -pin_load 0.018316 [get_ports {RData[1]}]
set_load -pin_load 0.018316 [get_ports {RData[0]}]
set_load -min -pin_load 0.018316 [get_ports {RData[0]}]
set_load -pin_load 0.018316 [get_ports {RValid}]
set_load -min -pin_load 0.018316 [get_ports {RValid}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {RReady}]
set_load -pin_load 0.018316 [get_ports {RLast}]
set_load -min -pin_load 0.018316 [get_ports {RLast}]
set_load -pin_load 0.018316 [get_ports {RId[3]}]
set_load -min -pin_load 0.018316 [get_ports {RId[3]}]
set_load -pin_load 0.018316 [get_ports {RId[2]}]
set_load -min -pin_load 0.018316 [get_ports {RId[2]}]
set_load -pin_load 0.018316 [get_ports {RId[1]}]
set_load -min -pin_load 0.018316 [get_ports {RId[1]}]
set_load -pin_load 0.018316 [get_ports {RId[0]}]
set_load -min -pin_load 0.018316 [get_ports {RId[0]}]
set_load -pin_load 0.018316 [get_ports {RResp[1]}]
set_load -min -pin_load 0.018316 [get_ports {RResp[1]}]
set_load -pin_load 0.018316 [get_ports {RResp[0]}]
set_load -min -pin_load 0.018316 [get_ports {RResp[0]}]
set_load -pin_load 0.018316 [get_ports {SD_CKE}]
set_load -min -pin_load 0.018316 [get_ports {SD_CKE}]
set_load -pin_load 0.018316 [get_ports {SD_CSB}]
set_load -min -pin_load 0.018316 [get_ports {SD_CSB}]
set_load -pin_load 0.018316 [get_ports {SD_RASB}]
set_load -min -pin_load 0.018316 [get_ports {SD_RASB}]
set_load -pin_load 0.018316 [get_ports {SD_CASB}]
set_load -min -pin_load 0.018316 [get_ports {SD_CASB}]
set_load -pin_load 0.018316 [get_ports {SD_WEB}]
set_load -min -pin_load 0.018316 [get_ports {SD_WEB}]
set_load -pin_load 0.018316 [get_ports {SD_BADDR[1]}]
set_load -min -pin_load 0.018316 [get_ports {SD_BADDR[1]}]
set_load -pin_load 0.018316 [get_ports {SD_BADDR[0]}]
set_load -min -pin_load 0.018316 [get_ports {SD_BADDR[0]}]
set_load -pin_load 0.018316 [get_ports {SD_ADDR[11]}]
set_load -min -pin_load 0.018316 [get_ports {SD_ADDR[11]}]
set_load -pin_load 0.018316 [get_ports {SD_ADDR[10]}]
set_load -min -pin_load 0.018316 [get_ports {SD_ADDR[10]}]
set_load -pin_load 0.018316 [get_ports {SD_ADDR[9]}]
set_load -min -pin_load 0.018316 [get_ports {SD_ADDR[9]}]
set_load -pin_load 0.018316 [get_ports {SD_ADDR[8]}]
set_load -min -pin_load 0.018316 [get_ports {SD_ADDR[8]}]
set_load -pin_load 0.018316 [get_ports {SD_ADDR[7]}]
set_load -min -pin_load 0.018316 [get_ports {SD_ADDR[7]}]
set_load -pin_load 0.018316 [get_ports {SD_ADDR[6]}]
set_load -min -pin_load 0.018316 [get_ports {SD_ADDR[6]}]
set_load -pin_load 0.018316 [get_ports {SD_ADDR[5]}]
set_load -min -pin_load 0.018316 [get_ports {SD_ADDR[5]}]
set_load -pin_load 0.018316 [get_ports {SD_ADDR[4]}]
set_load -min -pin_load 0.018316 [get_ports {SD_ADDR[4]}]
set_load -pin_load 0.018316 [get_ports {SD_ADDR[3]}]
set_load -min -pin_load 0.018316 [get_ports {SD_ADDR[3]}]
set_load -pin_load 0.018316 [get_ports {SD_ADDR[2]}]
set_load -min -pin_load 0.018316 [get_ports {SD_ADDR[2]}]
set_load -pin_load 0.018316 [get_ports {SD_ADDR[1]}]
set_load -min -pin_load 0.018316 [get_ports {SD_ADDR[1]}]
set_load -pin_load 0.018316 [get_ports {SD_ADDR[0]}]
set_load -min -pin_load 0.018316 [get_ports {SD_ADDR[0]}]
set_load -pin_load 0.018316 [get_ports {SD_DQE}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQE}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[31]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[30]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[29]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[28]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[27]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[26]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[25]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[24]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[23]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[22]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[21]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[20]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[19]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[18]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[17]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[16]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[15]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[14]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[13]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[12]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[11]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[10]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[9]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[8]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[7]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[6]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[5]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[4]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[3]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[2]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[1]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{SD_DQI[0]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[31]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[31]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[30]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[30]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[29]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[29]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[28]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[28]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[27]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[27]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[26]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[26]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[25]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[25]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[24]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[24]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[23]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[23]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[22]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[22]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[21]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[21]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[20]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[20]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[19]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[19]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[18]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[18]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[17]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[17]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[16]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[16]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[15]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[15]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[14]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[14]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[13]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[13]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[12]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[12]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[11]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[11]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[10]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[10]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[9]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[9]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[8]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[8]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[7]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[7]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[6]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[6]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[5]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[5]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[4]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[4]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[3]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[3]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[2]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[2]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[1]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[1]}]
set_load -pin_load 0.018316 [get_ports {SD_DQO[0]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQO[0]}]
set_load -pin_load 0.018316 [get_ports {SD_DQM[3]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQM[3]}]
set_load -pin_load 0.018316 [get_ports {SD_DQM[2]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQM[2]}]
set_load -pin_load 0.018316 [get_ports {SD_DQM[1]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQM[1]}]
set_load -pin_load 0.018316 [get_ports {SD_DQM[0]}]
set_load -min -pin_load 0.018316 [get_ports {SD_DQM[0]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {PRESETB}]
set_load -pin_load 0 [get_ports {PRESETB}]
set_disable_timing [get_ports {PRESETB}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {PSEL}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {PENABLE}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {PADDR[7]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {PADDR[6]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {PADDR[5]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {PADDR[4]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {PADDR[3]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {PADDR[2]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports {PWRITE}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[31]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[30]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[29]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[28]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[27]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[26]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[25]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[24]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[23]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[22]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[21]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[20]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[19]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[18]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[17]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[16]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[15]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[14]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[13]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[12]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[11]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[10]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[9]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[8]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[7]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[6]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[5]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[4]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[3]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[2]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[1]}]
set_driving_cell -lib_cell SDFFHQX4 -library slow -pin Q [get_ports \
{PWDATA[0]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[31]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[31]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[30]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[30]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[29]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[29]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[28]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[28]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[27]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[27]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[26]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[26]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[25]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[25]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[24]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[24]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[23]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[23]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[22]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[22]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[21]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[21]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[20]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[20]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[19]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[19]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[18]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[18]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[17]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[17]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[16]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[16]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[15]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[15]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[14]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[14]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[13]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[13]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[12]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[12]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[11]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[11]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[10]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[10]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[9]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[9]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[8]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[8]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[7]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[7]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[6]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[6]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[5]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[5]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[4]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[4]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[3]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[3]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[2]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[2]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[1]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[1]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[0]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[0]}]
set_resistance 0 [get_nets {ACLK}]
set_resistance 0 [get_nets {ARESETB}]
set_resistance 0 [get_nets {PORESETB}]
set_resistance 0 [get_nets {FCLK}]
set_resistance 0 [get_nets {PRESETB}]
