#- --=========================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000-2001 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- -----------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.14
#-
#- Release Information    : PrimeCell(TM)-PL092-r1p3-01ltd0
#-
#- -----------------------------------------------------------------------------
#- Purpose  :
#-            makefile for Verilog Trickbox files
#-
#- --=========================================================================--

MODULES =  SmcTrParams.v \
           SmcTrMemAhbifReg.v \
           SmcTrMemRdWrCtl.v \
           SmcTrMemArray.v \
           SmcTrAhbifReg.v \
           SmcTrMCBusBlk.v \
           SmcTrProtChkr.v \
           SmcTrWaitCntl.v \
           SmcTrickMem.v \
           SmcTrick.v

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

#- --================================== END ==================================--
