library verilog;
use verilog.vl_types.all;
entity default_readchannelmi is
    generic(
        bus_wid         : integer := 32;
        addr_wid        : integer := 32;
        masterid_wid    : integer := 4;
        slaveid_wid     : integer := 7;
        awlen_wid       : integer := 4;
        awsize_wid      : integer := 3;
        awburst_wid     : integer := 2;
        awlock_wid      : integer := 2;
        awcache_wid     : integer := 4;
        awprot_wid      : integer := 3;
        wstrb_wid       : integer := 4;
        bresp_wid       : integer := 2;
        rresp_wid       : integer := 2;
        arlen_wid       : integer := 4;
        arburst_wid     : integer := 2;
        arlock_wid      : integer := 2;
        arcache_wid     : integer := 4;
        arprot_wid      : integer := 3;
        master_wid      : integer := 3;
        slave_wid       : integer := 3;
        slave_num       : integer := 6;
        master_num      : integer := 4;
        selmaster_wid   : integer := 3;
        wr_reqdepth_wid : integer := 4;
        rd_reqdepth_wid : integer := 4;
        wrpermit_slavecntwid: integer := 0;
        rdpermit_slavecntwid: integer := 0;
        arsize_wid      : integer := 3
    );
    port(
        aclk            : in     vl_logic;
        aresetn         : in     vl_logic;
        aridmi2s        : out    vl_logic_vector;
        araddrmi2s      : out    vl_logic_vector;
        arlenmi2s       : out    vl_logic_vector;
        arsizemi2s      : out    vl_logic_vector;
        arburstmi2s     : out    vl_logic_vector;
        arlockmi2s      : out    vl_logic_vector;
        arcachemi2s     : out    vl_logic_vector;
        arprotmi2s      : out    vl_logic_vector;
        arvalidmi2s     : out    vl_logic;
        arreadys2mi     : in     vl_logic;
        rids2mi         : in     vl_logic_vector;
        rresps2mi       : in     vl_logic_vector;
        rdatas2mi       : in     vl_logic_vector;
        rvalids2mi      : in     vl_logic;
        rlasts2mi       : in     vl_logic;
        rreadymi2s      : out    vl_logic;
        aridsi02mi      : in     vl_logic_vector;
        araddrsi02mi    : in     vl_logic_vector;
        arlensi02mi     : in     vl_logic_vector;
        arsizesi02mi    : in     vl_logic_vector;
        arburstsi02mi   : in     vl_logic_vector;
        arlocksi02mi    : in     vl_logic_vector;
        arcachesi02mi   : in     vl_logic_vector;
        arprotsi02mi    : in     vl_logic_vector;
        aridsi12mi      : in     vl_logic_vector;
        araddrsi12mi    : in     vl_logic_vector;
        arlensi12mi     : in     vl_logic_vector;
        arsizesi12mi    : in     vl_logic_vector;
        arburstsi12mi   : in     vl_logic_vector;
        arlocksi12mi    : in     vl_logic_vector;
        arcachesi12mi   : in     vl_logic_vector;
        arprotsi12mi    : in     vl_logic_vector;
        aridsi22mi      : in     vl_logic_vector;
        araddrsi22mi    : in     vl_logic_vector;
        arlensi22mi     : in     vl_logic_vector;
        arsizesi22mi    : in     vl_logic_vector;
        arburstsi22mi   : in     vl_logic_vector;
        arlocksi22mi    : in     vl_logic_vector;
        arcachesi22mi   : in     vl_logic_vector;
        arprotsi22mi    : in     vl_logic_vector;
        aridsi32mi      : in     vl_logic_vector;
        araddrsi32mi    : in     vl_logic_vector;
        arlensi32mi     : in     vl_logic_vector;
        arsizesi32mi    : in     vl_logic_vector;
        arburstsi32mi   : in     vl_logic_vector;
        arlocksi32mi    : in     vl_logic_vector;
        arcachesi32mi   : in     vl_logic_vector;
        arprotsi32mi    : in     vl_logic_vector;
        arvalidsi2mi    : in     vl_logic_vector;
        arreadymi2si    : out    vl_logic_vector;
        ridmi2si0       : out    vl_logic_vector;
        rrespmi2si0     : out    vl_logic_vector;
        rdatami2si0     : out    vl_logic_vector;
        ridmi2si1       : out    vl_logic_vector;
        rrespmi2si1     : out    vl_logic_vector;
        rdatami2si1     : out    vl_logic_vector;
        ridmi2si2       : out    vl_logic_vector;
        rrespmi2si2     : out    vl_logic_vector;
        rdatami2si2     : out    vl_logic_vector;
        ridmi2si3       : out    vl_logic_vector;
        rrespmi2si3     : out    vl_logic_vector;
        rdatami2si3     : out    vl_logic_vector;
        rvalidmi2si     : out    vl_logic_vector;
        rlastmi2si      : out    vl_logic_vector;
        rreadysi2mi     : in     vl_logic_vector;
        lock2rdmi       : in     vl_logic;
        unlock2rdmi     : in     vl_logic;
        lock2wrmi       : out    vl_logic;
        unlock2wrmi     : out    vl_logic;
        awvalid         : in     vl_logic;
        lockport        : in     vl_logic_vector;
        readintemptywrmi2rdmi: in     vl_logic;
        datacntemptyrdmi2wrmi: out    vl_logic;
        ctldataread2lock: out    vl_logic_vector
    );
end default_readchannelmi;
