library verilog;
use verilog.vl_types.all;
entity dmacarbiter is
    port(
        hclk            : in     vl_logic;
        hresetn         : in     vl_logic;
        arbstop         : in     vl_logic;
        ch0reqm         : in     vl_logic;
        ch1reqm         : in     vl_logic;
        ch2reqm         : in     vl_logic;
        ch3reqm         : in     vl_logic;
        ch4reqm         : in     vl_logic;
        ch5reqm         : in     vl_logic;
        ch6reqm         : in     vl_logic;
        ch7reqm         : in     vl_logic;
        ch0numofxfers   : in     vl_logic_vector(4 downto 0);
        ch1numofxfers   : in     vl_logic_vector(4 downto 0);
        ch2numofxfers   : in     vl_logic_vector(4 downto 0);
        ch3numofxfers   : in     vl_logic_vector(4 downto 0);
        ch4numofxfers   : in     vl_logic_vector(4 downto 0);
        ch5numofxfers   : in     vl_logic_vector(4 downto 0);
        ch6numofxfers   : in     vl_logic_vector(4 downto 0);
        ch7numofxfers   : in     vl_logic_vector(4 downto 0);
        ch0incrm        : in     vl_logic;
        ch1incrm        : in     vl_logic;
        ch2incrm        : in     vl_logic;
        ch3incrm        : in     vl_logic;
        ch4incrm        : in     vl_logic;
        ch5incrm        : in     vl_logic;
        ch6incrm        : in     vl_logic;
        ch7incrm        : in     vl_logic;
        ch0addrm        : in     vl_logic_vector(31 downto 0);
        ch1addrm        : in     vl_logic_vector(31 downto 0);
        ch2addrm        : in     vl_logic_vector(31 downto 0);
        ch3addrm        : in     vl_logic_vector(31 downto 0);
        ch4addrm        : in     vl_logic_vector(31 downto 0);
        ch5addrm        : in     vl_logic_vector(31 downto 0);
        ch6addrm        : in     vl_logic_vector(31 downto 0);
        ch7addrm        : in     vl_logic_vector(31 downto 0);
        ch0protm        : in     vl_logic_vector(2 downto 0);
        ch1protm        : in     vl_logic_vector(2 downto 0);
        ch2protm        : in     vl_logic_vector(2 downto 0);
        ch3protm        : in     vl_logic_vector(2 downto 0);
        ch4protm        : in     vl_logic_vector(2 downto 0);
        ch5protm        : in     vl_logic_vector(2 downto 0);
        ch6protm        : in     vl_logic_vector(2 downto 0);
        ch7protm        : in     vl_logic_vector(2 downto 0);
        ch0lockm        : in     vl_logic;
        ch1lockm        : in     vl_logic;
        ch2lockm        : in     vl_logic;
        ch3lockm        : in     vl_logic;
        ch4lockm        : in     vl_logic;
        ch5lockm        : in     vl_logic;
        ch6lockm        : in     vl_logic;
        ch7lockm        : in     vl_logic;
        ch0widthm       : in     vl_logic_vector(2 downto 0);
        ch1widthm       : in     vl_logic_vector(2 downto 0);
        ch2widthm       : in     vl_logic_vector(2 downto 0);
        ch3widthm       : in     vl_logic_vector(2 downto 0);
        ch4widthm       : in     vl_logic_vector(2 downto 0);
        ch5widthm       : in     vl_logic_vector(2 downto 0);
        ch6widthm       : in     vl_logic_vector(2 downto 0);
        ch7widthm       : in     vl_logic_vector(2 downto 0);
        ch0dirxnm       : in     vl_logic;
        ch1dirxnm       : in     vl_logic;
        ch2dirxnm       : in     vl_logic;
        ch3dirxnm       : in     vl_logic;
        ch4dirxnm       : in     vl_logic;
        ch5dirxnm       : in     vl_logic;
        ch6dirxnm       : in     vl_logic;
        ch7dirxnm       : in     vl_logic;
        ch0xferabort    : in     vl_logic;
        ch1xferabort    : in     vl_logic;
        ch2xferabort    : in     vl_logic;
        ch3xferabort    : in     vl_logic;
        ch4xferabort    : in     vl_logic;
        ch5xferabort    : in     vl_logic;
        ch6xferabort    : in     vl_logic;
        ch7xferabort    : in     vl_logic;
        arbxferreq      : out    vl_logic;
        arbnumofxfers   : out    vl_logic_vector(4 downto 0);
        arbincrxfer     : out    vl_logic;
        arbhprot        : out    vl_logic_vector(2 downto 0);
        arbhlock        : out    vl_logic;
        arbhsize        : out    vl_logic_vector(2 downto 0);
        arbpriority     : out    vl_logic;
        arbxferdir      : out    vl_logic;
        abortxfer       : out    vl_logic;
        arbhaddr        : out    vl_logic_vector(31 downto 0);
        ch0gntm         : out    vl_logic;
        ch1gntm         : out    vl_logic;
        ch2gntm         : out    vl_logic;
        ch3gntm         : out    vl_logic;
        ch4gntm         : out    vl_logic;
        ch5gntm         : out    vl_logic;
        ch6gntm         : out    vl_logic;
        ch7gntm         : out    vl_logic
    );
end dmacarbiter;
