#-====================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- ---------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.1
#-
#- Release Information    : PrimeCell(TM)-PL110-r1p2-00ltd0
#-
#- ---------------------------------------------------------------------
#- Purpose  : makefile for Verilog Trickbox files
#- -==================================================================--

MODULES = CLTrAHBIf.v \
          CLTrCLCDIf.v \
          CLTrDataCheck.v \
          CLTrProtCheck.v \
          CLTrRegBlock.v \
          CLTrick.v 

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk 

################################# End ##################################
