library verilog;
use verilog.vl_types.all;
entity epxa10_inout is
    port(
        clkref          : in     vl_logic;
        npor            : in     vl_logic;
        reserved        : in     vl_logic;
        debugen         : in     vl_logic;
        bootflash       : in     vl_logic;
        nconfig         : in     vl_logic;
        msel            : in     vl_logic_vector(1 downto 0);
        cen             : in     vl_logic;
        dclk            : in     vl_logic;
        cs              : in     vl_logic;
        csn             : in     vl_logic;
        rsn             : in     vl_logic;
        wsn             : in     vl_logic;
        datain          : in     vl_logic_vector(6 downto 0);
        exttck          : in     vl_logic;
        extntrst        : in     vl_logic;
        exttms          : in     vl_logic;
        ceon            : out    vl_logic;
        rdynbsy         : out    vl_logic;
        reset_in_n      : in     vl_logic;
        reset_out_n     : out    vl_logic;
        statusn_xmgxread: in     vl_logic;
        statusn         : out    vl_logic;
        condone_xmgxread: in     vl_logic;
        condone         : out    vl_logic;
        datain7_xmgxread: in     vl_logic;
        datain7         : out    vl_logic;
        exttdo_xmgxread : in     vl_logic;
        exttdo          : out    vl_logic;
        proctdi         : in     vl_logic;
        proctms         : in     vl_logic;
        proctck         : in     vl_logic;
        procntrst       : in     vl_logic;
        proctdo_xmgxread: in     vl_logic;
        proctdo         : out    vl_logic;
        jselect         : in     vl_logic;
        pldosc          : in     vl_logic;
        pldpor          : in     vl_logic;
        pldtdimux       : in     vl_logic;
        pldtdotap       : in     vl_logic;
        pldstatuson     : in     vl_logic;
        pldcondoneo     : in     vl_logic;
        pldceon         : in     vl_logic;
        pldcboscen      : in     vl_logic;
        pldrdynbsy      : in     vl_logic;
        pldcbendinit    : in     vl_logic;
        pldmsel         : out    vl_logic_vector(1 downto 0);
        pldconfign      : out    vl_logic;
        pldstatusin     : out    vl_logic;
        pldcondonei     : out    vl_logic;
        pldcen          : out    vl_logic;
        plddclk         : out    vl_logic;
        plddata         : out    vl_logic_vector(7 downto 0);
        pldoscen        : out    vl_logic;
        sdramdqin       : in     vl_logic_vector(31 downto 0);
        sdramdqsin      : in     vl_logic_vector(3 downto 0);
        sdramdqout      : out    vl_logic_vector(31 downto 0);
        sdramdqsout     : out    vl_logic_vector(3 downto 0);
        sdramdqm        : out    vl_logic_vector(3 downto 0);
        sdramaddr       : out    vl_logic_vector(14 downto 0);
        sdramclk        : out    vl_logic;
        sdramclkn       : out    vl_logic;
        sdramclke       : out    vl_logic;
        sdramwen        : out    vl_logic;
        sdramcasn       : out    vl_logic;
        sdramrasn       : out    vl_logic;
        sdramcsn        : out    vl_logic_vector(1 downto 0);
        sdramdqoe       : out    vl_logic_vector(3 downto 0);
        sdramdqsoe      : out    vl_logic_vector(3 downto 0);
        sdramioselect   : out    vl_logic;
        ebidqin         : in     vl_logic_vector(15 downto 0);
        ebiack          : in     vl_logic;
        ebidqout        : out    vl_logic_vector(15 downto 0);
        ebiaddr         : out    vl_logic_vector(24 downto 0);
        ebiwen          : out    vl_logic;
        ebioen          : out    vl_logic;
        ebibe           : out    vl_logic_vector(1 downto 0);
        ebics           : out    vl_logic_vector(3 downto 0);
        ebiclk          : out    vl_logic;
        ebidqoe         : out    vl_logic;
        ebiioselect     : out    vl_logic;
        intextn         : in     vl_logic;
        uartctsn        : in     vl_logic;
        uartdcdin       : in     vl_logic;
        uartdsrn        : in     vl_logic;
        uartrxd         : in     vl_logic;
        uartriin        : in     vl_logic;
        uarttxd         : out    vl_logic;
        uartrtsn        : out    vl_logic;
        uartdtrn        : out    vl_logic;
        uartrion        : out    vl_logic;
        uartdcdon       : out    vl_logic;
        uartdcdrioe     : out    vl_logic;
        uartioselect    : out    vl_logic;
        traceclk        : out    vl_logic;
        tracepipestat   : out    vl_logic_vector(2 downto 0);
        tracepkt        : out    vl_logic_vector(15 downto 0);
        tracesync       : out    vl_logic;
        traceioselect   : out    vl_logic;
        slavehclkpld    : in     vl_logic;
        slavehwrite     : in     vl_logic;
        slavehreadyi    : in     vl_logic;
        slavehselreg    : in     vl_logic;
        slavehsel       : in     vl_logic;
        slavehmastlock  : in     vl_logic;
        slavehtrans     : in     vl_logic_vector(1 downto 0);
        slavehsize      : in     vl_logic_vector(1 downto 0);
        slavehburst     : in     vl_logic_vector(2 downto 0);
        slavehaddr      : in     vl_logic_vector(31 downto 0);
        slavehwdata     : in     vl_logic_vector(31 downto 0);
        slavehreadyo    : out    vl_logic;
        slavehresp      : out    vl_logic_vector(1 downto 0);
        slavehrdata     : out    vl_logic_vector(31 downto 0);
        slavebuserrint  : out    vl_logic;
        masterhclkbridge: in     vl_logic;
        masterhready    : in     vl_logic;
        masterhgrant    : in     vl_logic;
        masterhresp     : in     vl_logic_vector(1 downto 0);
        masterhrdata    : in     vl_logic_vector(31 downto 0);
        masterhwrite    : out    vl_logic;
        masterhlock     : out    vl_logic;
        masterhbusreq   : out    vl_logic;
        masterhtrans    : out    vl_logic_vector(1 downto 0);
        masterhsize     : out    vl_logic_vector(1 downto 0);
        masterhburst    : out    vl_logic_vector(2 downto 0);
        masterhaddr     : out    vl_logic_vector(31 downto 0);
        masterhwdata    : out    vl_logic_vector(31 downto 0);
        clk0dp0         : in     vl_logic;
        clk1dp0         : in     vl_logic;
        clk0dp1         : in     vl_logic;
        clk1dp1         : in     vl_logic;
        r0a0            : in     vl_logic_vector(15 downto 0);
        r0a1            : in     vl_logic_vector(14 downto 0);
        r0ce0           : in     vl_logic;
        r0ce1           : in     vl_logic;
        r0rd            : in     vl_logic_vector(31 downto 0);
        r0rw0           : in     vl_logic;
        r0rw1           : in     vl_logic;
        r0rq            : out    vl_logic_vector(31 downto 0);
        lockreqdp0      : in     vl_logic;
        lockgrntdp0     : out    vl_logic;
        cramdp0         : in     vl_logic_vector(3 downto 0);
        r1a0            : in     vl_logic_vector(15 downto 0);
        r1a1            : in     vl_logic_vector(14 downto 0);
        r1ce0           : in     vl_logic;
        r1ce1           : in     vl_logic;
        r1rd            : in     vl_logic_vector(31 downto 0);
        r1rw0           : in     vl_logic;
        r1rw1           : in     vl_logic;
        r1rq            : out    vl_logic_vector(31 downto 0);
        lockreqdp1      : in     vl_logic;
        lockgrntdp1     : out    vl_logic;
        cramdp1         : in     vl_logic_vector(3 downto 0);
        highaddress     : in     vl_logic;
        dpcram          : in     vl_logic_vector(1 downto 0);
        intpld          : in     vl_logic_vector(5 downto 0);
        intuart         : out    vl_logic;
        inttimer0       : out    vl_logic;
        inttimer1       : out    vl_logic;
        intproc0        : out    vl_logic;
        intproc1        : out    vl_logic;
        debugrq         : in     vl_logic;
        debugext0       : in     vl_logic;
        debugext1       : in     vl_logic;
        debugiebrkpt    : in     vl_logic;
        debugdewpt      : in     vl_logic;
        debugextin      : in     vl_logic_vector(3 downto 0);
        debugack        : out    vl_logic;
        debugrng0       : out    vl_logic;
        debugrng1       : out    vl_logic;
        debugextout     : out    vl_logic_vector(3 downto 0);
        initialize      : in     vl_logic;
        shortreset      : in     vl_logic;
        clk_pll1        : in     vl_logic;
        clk_pll2        : in     vl_logic;
        pll_por         : out    vl_logic;
        pll_entest      : out    vl_logic;
        pll1_lock       : in     vl_logic;
        pll1_up         : in     vl_logic;
        pll1_down       : in     vl_logic;
        pll1_ctrl       : out    vl_logic_vector(14 downto 0);
        pll2_ctrl       : out    vl_logic_vector(14 downto 0);
        pll2_lock       : in     vl_logic;
        pll2_up         : in     vl_logic;
        pll2_down       : in     vl_logic;
        pll1_cnt        : out    vl_logic_vector(27 downto 0);
        pll2_cnt        : out    vl_logic_vector(27 downto 0);
        ahb1_clk        : out    vl_logic;
        ahb2_clk        : out    vl_logic;
        warm_reset_n    : out    vl_logic;
        ahb1_hlock      : out    vl_logic;
        ahb1_htrans     : out    vl_logic_vector(1 downto 0);
        ahb1_haddr      : out    vl_logic_vector(31 downto 0);
        ahb1_hwrite     : out    vl_logic;
        ahb1_hwdta      : out    vl_logic_vector(31 downto 0);
        ahb1_hburst     : out    vl_logic_vector(2 downto 0);
        ahb1_hsize      : out    vl_logic_vector(2 downto 0);
        ahb1_hrdata     : out    vl_logic_vector(31 downto 0);
        ahb1_hresp      : out    vl_logic_vector(1 downto 0);
        ahb1_hready     : out    vl_logic;
        ahb2_hbusreq_ahb12: out    vl_logic;
        ahb2_hbusreq_config: out    vl_logic;
        ahb2_hbusreq_pld: out    vl_logic;
        ahb2_hlock_ahb12: out    vl_logic;
        ahb2_hlock_pld  : out    vl_logic;
        ahb2_hgrant_ahb12: out    vl_logic;
        ahb2_hgrant_config: out    vl_logic;
        ahb2_hgrant_pld : out    vl_logic;
        ahb2_hmaster    : out    vl_logic_vector(1 downto 0);
        ahb2_hmastlock  : out    vl_logic;
        ahb2_hsplit     : out    vl_logic_vector(1 downto 0);
        ahb2_htrans     : out    vl_logic_vector(1 downto 0);
        ahb2_haddr      : out    vl_logic_vector(31 downto 0);
        ahb2_hwrite     : out    vl_logic;
        ahb2_hwdata     : out    vl_logic_vector(31 downto 0);
        ahb2_hburst     : out    vl_logic_vector(2 downto 0);
        ahb2_hsize      : out    vl_logic_vector(2 downto 0);
        ahb2_hrdata     : out    vl_logic_vector(31 downto 0);
        ahb2_hresp      : out    vl_logic_vector(1 downto 0);
        ahb2_hready     : out    vl_logic;
        int_sources     : out    vl_logic_vector(16 downto 0);
        irq_n           : out    vl_logic;
        fiq_n           : out    vl_logic;
        int_priority0   : out    vl_logic_vector(6 downto 0);
        int_priority1   : out    vl_logic_vector(6 downto 0);
        int_priority2   : out    vl_logic_vector(6 downto 0);
        int_priority3   : out    vl_logic_vector(6 downto 0);
        int_priority4   : out    vl_logic_vector(6 downto 0);
        int_priority5   : out    vl_logic_vector(6 downto 0);
        int_priority6   : out    vl_logic_vector(6 downto 0);
        int_priority7   : out    vl_logic_vector(6 downto 0);
        int_priority8   : out    vl_logic_vector(6 downto 0);
        int_priority9   : out    vl_logic_vector(6 downto 0);
        int_priority10  : out    vl_logic_vector(6 downto 0);
        int_priority11  : out    vl_logic_vector(6 downto 0);
        int_priority12  : out    vl_logic_vector(6 downto 0);
        int_priority13  : out    vl_logic_vector(6 downto 0);
        int_priority14  : out    vl_logic_vector(6 downto 0);
        int_priority15  : out    vl_logic_vector(6 downto 0);
        int_priority16  : out    vl_logic_vector(6 downto 0);
        int_mask        : out    vl_logic_vector(16 downto 0);
        int_source_status: out    vl_logic_vector(16 downto 0);
        int_request_status: out    vl_logic_vector(16 downto 0);
        int_id          : out    vl_logic_vector(5 downto 0);
        int_pld_priority: out    vl_logic_vector(5 downto 0);
        int_mode        : out    vl_logic_vector(1 downto 0);
        wdog_count      : out    vl_logic_vector(31 downto 0);
        wdog_ctrl       : out    vl_logic_vector(29 downto 0);
        boot_cr         : out    vl_logic_vector(2 downto 0);
        reset_sr        : out    vl_logic_vector(2 downto 0);
        idcode          : out    vl_logic_vector(31 downto 0);
        iocr_sdram      : out    vl_logic_vector(6 downto 0);
        iocr_ebi        : out    vl_logic_vector(6 downto 0);
        iocr_uart       : out    vl_logic_vector(6 downto 0);
        iocr_trace      : out    vl_logic_vector(6 downto 0);
        mmap_registers  : out    vl_logic_vector(31 downto 0);
        mmap_sram0      : out    vl_logic_vector(31 downto 0);
        mmap_sram1      : out    vl_logic_vector(31 downto 0);
        mmap_dpsram0    : out    vl_logic_vector(31 downto 0);
        mmap_dpsram1    : out    vl_logic_vector(31 downto 0);
        mmap_sdram0     : out    vl_logic_vector(31 downto 0);
        mmap_sdram1     : out    vl_logic_vector(31 downto 0);
        mmap_ebi0       : out    vl_logic_vector(31 downto 0);
        mmap_ebi1       : out    vl_logic_vector(31 downto 0);
        mmap_ebi2       : out    vl_logic_vector(31 downto 0);
        mmap_ebi3       : out    vl_logic_vector(31 downto 0);
        mmap_pld0       : out    vl_logic_vector(31 downto 0);
        mmap_pld1       : out    vl_logic_vector(31 downto 0);
        mmap_pld2       : out    vl_logic_vector(31 downto 0);
        mmap_pld3       : out    vl_logic_vector(31 downto 0);
        ahb12b_cr       : out    vl_logic_vector(2 downto 0);
        ahb12b_sr       : out    vl_logic_vector(8 downto 0);
        ahb12b_addrsr   : out    vl_logic_vector(31 downto 0);
        pldsb_cr        : out    vl_logic_vector(2 downto 0);
        pldsb_sr        : out    vl_logic_vector(8 downto 0);
        pldsb_addrsr    : out    vl_logic_vector(31 downto 0);
        pldmb_cr        : out    vl_logic_vector(2 downto 0);
        pldmb_sr        : out    vl_logic_vector(8 downto 0);
        pldmb_addrsr    : out    vl_logic_vector(31 downto 0);
        debug_com_base  : out    vl_logic_vector(31 downto 0);
        debug_com_int   : out    vl_logic_vector(1 downto 0);
        debug_com_hti   : out    vl_logic_vector(31 downto 0);
        debug_com_hto   : out    vl_logic_vector(31 downto 0);
        debug_com_thi   : out    vl_logic_vector(31 downto 0);
        debug_com_tho   : out    vl_logic_vector(31 downto 0);
        config_control  : out    vl_logic_vector(7 downto 0);
        config_clock    : out    vl_logic_vector(15 downto 0);
        config_data     : out    vl_logic_vector(31 downto 0);
        timer_control_a : out    vl_logic_vector(4 downto 0);
        timer_status_a  : out    vl_logic_vector(4 downto 0);
        timer_prescale_a: out    vl_logic_vector(31 downto 0);
        timer_prr_a     : out    vl_logic_vector(31 downto 0);
        timer_tlr_a     : out    vl_logic_vector(31 downto 0);
        timer_a         : out    vl_logic_vector(31 downto 0);
        timer_control_b : out    vl_logic_vector(4 downto 0);
        timer_status_b  : out    vl_logic_vector(4 downto 0);
        timer_prescale_b: out    vl_logic_vector(31 downto 0);
        timer_prr_b     : out    vl_logic_vector(31 downto 0);
        timer_tlr_b     : out    vl_logic_vector(31 downto 0);
        timer_b         : out    vl_logic_vector(31 downto 0);
        uart_rsr        : out    vl_logic_vector(7 downto 0);
        uart_rds        : out    vl_logic_vector(7 downto 0);
        uart_rd         : out    vl_logic_vector(7 downto 0);
        uart_tsr        : out    vl_logic_vector(7 downto 0);
        uart_fcr        : out    vl_logic_vector(7 downto 0);
        uart_ies        : out    vl_logic_vector(7 downto 0);
        uart_iec        : out    vl_logic_vector(7 downto 0);
        uart_isr        : out    vl_logic_vector(7 downto 0);
        uart_iid        : out    vl_logic_vector(7 downto 0);
        uart_mc         : out    vl_logic_vector(7 downto 0);
        uart_mcr        : out    vl_logic_vector(7 downto 0);
        uart_msr        : out    vl_logic_vector(7 downto 0);
        uart_dl_lo      : out    vl_logic_vector(7 downto 0);
        uart_dl_hi      : out    vl_logic_vector(7 downto 0);
        clk_pll1_ncnt   : out    vl_logic_vector(18 downto 0);
        clk_pll1_mcnt   : out    vl_logic_vector(18 downto 0);
        clk_pll1_kcnt   : out    vl_logic_vector(18 downto 0);
        clk_pll1_ctrl   : out    vl_logic_vector(15 downto 0);
        clk_pll2_ncnt   : out    vl_logic_vector(18 downto 0);
        clk_pll2_mcnt   : out    vl_logic_vector(18 downto 0);
        clk_pll2_kcnt   : out    vl_logic_vector(18 downto 0);
        clk_pll2_ctrl   : out    vl_logic_vector(15 downto 0);
        clk_derive      : out    vl_logic_vector(13 downto 0);
        clk_status      : out    vl_logic_vector(3 downto 0);
        clk_ahb1_count  : out    vl_logic_vector(31 downto 0);
        sdram_timing1   : out    vl_logic_vector(15 downto 0);
        sdram_timing2   : out    vl_logic_vector(15 downto 0);
        sdram_config    : out    vl_logic_vector(15 downto 0);
        sdram_refresh   : out    vl_logic_vector(15 downto 0);
        sdram_addr      : out    vl_logic_vector(15 downto 0);
        sdram_bus1      : out    vl_logic_vector(15 downto 0);
        sdram_bus2      : out    vl_logic_vector(15 downto 0);
        sdram_init      : out    vl_logic_vector(15 downto 0);
        sdram_mode0     : out    vl_logic_vector(11 downto 0);
        sdram_mode1     : out    vl_logic_vector(11 downto 0);
        ebi_sr          : out    vl_logic_vector(31 downto 0);
        ebi_block0      : out    vl_logic_vector(7 downto 0);
        ebi_block1      : out    vl_logic_vector(7 downto 0);
        ebi_block2      : out    vl_logic_vector(7 downto 0);
        ebi_block3      : out    vl_logic_vector(7 downto 0);
        ebi_int_sr      : out    vl_logic;
        ebi_int_addrsr  : out    vl_logic_vector(31 downto 0);
        r0              : out    vl_logic_vector(31 downto 0);
        r1              : out    vl_logic_vector(31 downto 0);
        r2              : out    vl_logic_vector(31 downto 0);
        r3              : out    vl_logic_vector(31 downto 0);
        r4              : out    vl_logic_vector(31 downto 0);
        r5              : out    vl_logic_vector(31 downto 0);
        r6              : out    vl_logic_vector(31 downto 0);
        r7              : out    vl_logic_vector(31 downto 0);
        r8              : out    vl_logic_vector(31 downto 0);
        r9              : out    vl_logic_vector(31 downto 0);
        r10             : out    vl_logic_vector(31 downto 0);
        r11             : out    vl_logic_vector(31 downto 0);
        r12             : out    vl_logic_vector(31 downto 0);
        r13             : out    vl_logic_vector(31 downto 0);
        r14             : out    vl_logic_vector(31 downto 0);
        r13irq          : out    vl_logic_vector(31 downto 0);
        r14irq          : out    vl_logic_vector(31 downto 0);
        r13svc          : out    vl_logic_vector(31 downto 0);
        r14svc          : out    vl_logic_vector(31 downto 0);
        r13abt          : out    vl_logic_vector(31 downto 0);
        r14abt          : out    vl_logic_vector(31 downto 0);
        r13und          : out    vl_logic_vector(31 downto 0);
        r14und          : out    vl_logic_vector(31 downto 0);
        r8fiq           : out    vl_logic_vector(31 downto 0);
        r9fiq           : out    vl_logic_vector(31 downto 0);
        r10fiq          : out    vl_logic_vector(31 downto 0);
        r11fiq          : out    vl_logic_vector(31 downto 0);
        r12fiq          : out    vl_logic_vector(31 downto 0);
        r13fiq          : out    vl_logic_vector(31 downto 0);
        r14fiq          : out    vl_logic_vector(31 downto 0);
        cpsr            : out    vl_logic_vector(10 downto 0);
        flags           : out    vl_logic_vector(3 downto 0);
        spsrfiq         : out    vl_logic_vector(10 downto 0);
        spsrirq         : out    vl_logic_vector(10 downto 0);
        spsrsvc         : out    vl_logic_vector(10 downto 0);
        spsrabt         : out    vl_logic_vector(10 downto 0);
        spsrund         : out    vl_logic_vector(10 downto 0);
        pc              : out    vl_logic_vector(31 downto 0);
        addrmask0       : out    vl_logic_vector(31 downto 0);
        addrval0        : out    vl_logic_vector(31 downto 0);
        datamask0       : out    vl_logic_vector(31 downto 0);
        dataval0        : out    vl_logic_vector(31 downto 0);
        ctlmask0        : out    vl_logic_vector(7 downto 0);
        ctlval0         : out    vl_logic_vector(8 downto 0);
        addrmask1       : out    vl_logic_vector(31 downto 0);
        addrval1        : out    vl_logic_vector(31 downto 0);
        datamask1       : out    vl_logic_vector(31 downto 0);
        dataval1        : out    vl_logic_vector(31 downto 0);
        ctlmask1        : out    vl_logic_vector(7 downto 0);
        ctlval1         : out    vl_logic_vector(8 downto 0);
        veccatch        : out    vl_logic_vector(6 downto 0);
        dbgctl          : out    vl_logic_vector(3 downto 0);
        dbgstatus       : out    vl_logic_vector(4 downto 0);
        commsctl        : out    vl_logic_vector(31 downto 0);
        commsdata       : out    vl_logic_vector(31 downto 0);
        processorid     : out    vl_logic_vector(31 downto 0);
        cacheid         : out    vl_logic_vector(31 downto 0);
        controlreg      : out    vl_logic_vector(31 downto 0);
        transtablebasereg: out    vl_logic_vector(31 downto 14);
        domainaccesscontrolreg: out    vl_logic_vector(31 downto 0);
        faultstatusreg  : out    vl_logic_vector(7 downto 0);
        faultaddrreg    : out    vl_logic_vector(31 downto 0);
        icachelockdown  : out    vl_logic_vector(31 downto 0);
        dcachelockdown  : out    vl_logic_vector(31 downto 0);
        itlblockdownbase: out    vl_logic_vector(5 downto 0);
        itlblockdowncurrentvictim: out    vl_logic_vector(5 downto 0);
        itlblockdownpreserve: out    vl_logic;
        dtlblockdownbase: out    vl_logic_vector(5 downto 0);
        dtlblockdowncurrentvictim: out    vl_logic_vector(5 downto 0);
        dtlblockdownpreserve: out    vl_logic;
        processid       : out    vl_logic_vector(31 downto 0);
        reset           : out    vl_logic;
        treset          : out    vl_logic;
        dread           : out    vl_logic;
        normal          : out    vl_logic;
        dwptread        : out    vl_logic;
        cpread          : out    vl_logic;
        cpdread         : out    vl_logic;
        iebkptread      : out    vl_logic;
        bscanin         : out    vl_logic;
        dbgoff          : out    vl_logic;
        tck2dbg         : out    vl_logic;
        tracking        : out    vl_logic;
        useb            : out    vl_logic;
        usef            : out    vl_logic;
        ambatestmode    : out    vl_logic;
        ambafunctestmode: out    vl_logic;
        ambafunctestmodejustchanged: out    vl_logic
    );
end epxa10_inout;
