library verilog;
use verilog.vl_types.all;
entity WriteChannelsi is
    generic(
        BUS_WID         : integer := 32;
        ADDR_WID        : integer := 32;
        ID_WID          : integer := 4;
        AWLEN_WID       : integer := 4;
        AWSIZE_WID      : integer := 3;
        AWBURST_WID     : integer := 2;
        AWLOCK_WID      : integer := 2;
        AWCACHE_WID     : integer := 4;
        AWPROT_WID      : integer := 3;
        WSTRB_WID       : integer := 4;
        BRESP_WID       : integer := 2;
        RRESP_WID       : integer := 2;
        ARLEN_WID       : integer := 4;
        ARSIZE_WID      : integer := 3;
        ARBURST_WID     : integer := 2;
        ARLOCK_WID      : integer := 2;
        ARCACHE_WID     : integer := 4;
        ARPROT_WID      : integer := 3;
        MASTER_WID      : integer := 4;
        SLAVE_WID       : integer := 3;
        SLAVE_NUM       : integer := 6;
        MASTER_NUM      : integer := 4;
        SLAVECNTWID     : integer := 5;
        REQDEPTH_WID    : integer := 2
    );
    port(
        ACLK            : in     vl_logic;
        ARESETn         : in     vl_logic;
        AWIDm2si        : in     vl_logic_vector;
        AWADDRm2si      : in     vl_logic_vector;
        AWLENm2si       : in     vl_logic_vector;
        AWSIZEm2si      : in     vl_logic_vector;
        AWBURSTm2si     : in     vl_logic_vector;
        AWLOCKm2si      : in     vl_logic_vector;
        AWCACHEm2si     : in     vl_logic_vector;
        AWPROTm2si      : in     vl_logic_vector;
        AWVALIDm2si     : in     vl_logic;
        AWREADYsi2m     : out    vl_logic;
        WIDm2si         : in     vl_logic_vector;
        WDATAm2si       : in     vl_logic_vector;
        WSTRBm2si       : in     vl_logic_vector;
        WLASTm2si       : in     vl_logic;
        WVALIDm2si      : in     vl_logic;
        WREADYsi2m      : out    vl_logic;
        BIDsi2m         : out    vl_logic_vector;
        BRESPsi2m       : out    vl_logic_vector;
        BVALIDsi2m      : out    vl_logic;
        BREADYm2si      : in     vl_logic;
        AWIDsi2mi       : out    vl_logic_vector;
        AWADDRsi2mi     : out    vl_logic_vector;
        AWLENsi2mi      : out    vl_logic_vector;
        AWSIZEsi2mi     : out    vl_logic_vector;
        AWBURSTsi2mi    : out    vl_logic_vector;
        AWLOCKsi2mi     : out    vl_logic_vector;
        AWCACHEsi2mi    : out    vl_logic_vector;
        AWPROTsi2mi     : out    vl_logic_vector;
        AWVALIDsi2mi    : out    vl_logic_vector;
        AWREADYmi2si    : in     vl_logic_vector;
        WIDsi2mi        : out    vl_logic_vector;
        WDATAsi2mi      : out    vl_logic_vector;
        WSTRBsi2mi      : out    vl_logic_vector;
        WLASTsi2mi      : out    vl_logic_vector;
        WVALIDsi2mi     : out    vl_logic_vector;
        WREADYmi2si     : in     vl_logic_vector;
        BIDmi02si       : in     vl_logic_vector;
        BRESPmi02si     : in     vl_logic_vector;
        BIDmi12si       : in     vl_logic_vector;
        BRESPmi12si     : in     vl_logic_vector;
        BIDmi22si       : in     vl_logic_vector;
        BRESPmi22si     : in     vl_logic_vector;
        BIDmi32si       : in     vl_logic_vector;
        BRESPmi32si     : in     vl_logic_vector;
        BIDmi42si       : in     vl_logic_vector;
        BRESPmi42si     : in     vl_logic_vector;
        BIDmi52si       : in     vl_logic_vector;
        BRESPmi52si     : in     vl_logic_vector;
        BVALIDmi2si     : in     vl_logic_vector;
        BREADYsi2mi     : out    vl_logic_vector
    );
end WriteChannelsi;
