library verilog;
use verilog.vl_types.all;
entity command_status is
    generic(
        ifield          : integer := 0;
        sfield          : integer := 1;
        tfield          : integer := 2;
        xfield          : integer := 3;
        afield          : integer := 4;
        cfield          : integer := 5;
        efield          : integer := 6;
        hfield          : integer := 7;
        rfield          : integer := 8;
        lfield          : integer := 9;
        dfield          : integer := 10;
        ufield          : integer := 11;
        bfield          : integer := 12;
        pfield          : integer := 13;
        gfield          : integer := 14
    );
    port(
        mresetn         : in     vl_logic;
        mclk            : in     vl_logic;
        mcselect        : in     vl_logic;
        mcommand        : in     vl_logic_vector(47 downto 0);
        mcommand_ok     : in     vl_logic;
        mdecode         : in     vl_logic_vector(11 downto 0);
        mcstate         : in     vl_logic_vector(4 downto 0);
        mspi_derr       : in     vl_logic;
        set_pwd         : in     vl_logic;
        lock_unlock_mode: in     vl_logic_vector(7 downto 0);
        pwd_match       : in     vl_logic;
        pwd_len_match   : in     vl_logic;
        pwd_stb         : in     vl_logic;
        clr_pwd         : in     vl_logic;
        card_is_locked  : out    vl_logic;
        index           : in     vl_logic_vector(7 downto 0);
        multi_write_block: in     vl_logic_vector(31 downto 0);
        multi_read_block: in     vl_logic_vector(31 downto 0);
        mext_csd        : in     vl_logic_vector(191 downto 0);
        switch_error_n  : out    vl_logic;
        wr_eol          : in     vl_logic;
        wr_field        : in     vl_logic_vector(3 downto 0);
        mrden           : in     vl_logic;
        block_len_error : out    vl_logic;
        mprot_up_data   : out    vl_logic_vector(31 downto 0);
        ismbw           : in     vl_logic;
        rd_eou          : in     vl_logic;
        wr_block_buffer_4word: in     vl_logic_vector(127 downto 0);
        wr_count        : in     vl_logic_vector(15 downto 0);
        cid_csd_overwrite: out    vl_logic;
        csd_update      : in     vl_logic_vector(127 downto 0);
        rd_field        : in     vl_logic_vector(3 downto 0);
        cmd_field       : in     vl_logic_vector(3 downto 0);
        cmd_eoe         : in     vl_logic;
        resp_eoe        : in     vl_logic;
        resp_eoe_d      : in     vl_logic;
        resp_eor        : in     vl_logic;
        rd_eol          : in     vl_logic;
        cmd_error       : in     vl_logic_vector(7 downto 0);
        mwstb           : in     vl_logic;
        mcsd            : in     vl_logic_vector(127 downto 0);
        mstatuscpu      : in     vl_logic_vector(31 downto 0);
        mstatuswr       : in     vl_logic;
        mstatuswren     : in     vl_logic_vector(31 downto 0);
        mblockmax       : in     vl_logic_vector(22 downto 0);
        mrblen          : in     vl_logic_vector(11 downto 0);
        mwblen          : in     vl_logic_vector(11 downto 0);
        meraseseq       : in     vl_logic_vector(8 downto 0);
        merasecmd       : in     vl_logic_vector(8 downto 0);
        mcardlock       : in     vl_logic;
        mcidfix         : in     vl_logic;
        mlocken         : in     vl_logic_vector(63 downto 0);
        cmd_eoe_d       : out    vl_logic;
        mstatus         : out    vl_logic_vector(31 downto 0)
    );
end command_status;
