#- --=========================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000-2001 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#-------------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile,v
#- File Revision          : 1.4
#-
#- Release Information    : ADK_REL1v1
#-
#-------------------------------------------------------------------------------
#-  Purpose  : 
#-             ADK makefile, compiles verilog rtl for $SIMULATOR
#-
#- --=========================================================================--

MODULES = MpmcAhbTop.v\
          MpmcAhbif.v\
          MpmcArbiter.v\
          MpmcBufCntrl.v\
          MpmcBufUnit.v\
          MpmcBuffer.v\
          MpmcClockOr.v\
          MpmcCore.v\
          MpmcDyAxsSM1.v\
          MpmcDyAxsSM2.v\
          MpmcDyFBtoH.v\
          MpmcDyFCntl.v\
          MpmcDyFIFO.v\
          MpmcDyIntRdGen.v\
          MpmcDyIntRegBlk.v\
          MpmcDyLatCntr.v\
          MpmcDyMemCntl.v\
          MpmcDyModSM.v\
          MpmcDyRefSM.v\
          MpmcDyRegBlk.v\
          MpmcDyRegFile.v\
          MpmcDySyFlash.v\
          MpmcEndian.v\
          MpmcMemBGnt.v\
          MpmcMemCntl.v\
          MpmcMemCntlIf.v\
          MpmcPadIf.v\
          MpmcRegIf.v\
          MpmcRevAnd.v\
          MpmcStExtIf.v\
          MpmcStIntIf.v\
          MpmcStMemCntl.v\
          MpmcStRegBlk.v\
          MpmcStTSM.v\
          MpmcStTimCntl.v\
          MpmcTIC.v\
          Mpmc.v 

PERIPH = mpmc_pl172

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

#################################### End #######################################
