onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {SLAVE1 WR}
add wave -noupdate -format Literal -radix hexadecimal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWIDmi2s
add wave -noupdate -color Magenta -format Literal -radix hexadecimal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWLOCKmi2s
add wave -noupdate -format Logic -radix hexadecimal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWREADYs2mi
add wave -noupdate -format Logic -radix hexadecimal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWVALIDmi2s
add wave -noupdate -color {Slate Blue} -format Literal -radix hexadecimal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WDATAmi2s
add wave -noupdate -color {Slate Blue} -format Literal -radix hexadecimal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WIDmi2s
add wave -noupdate -color {Slate Blue} -format Logic -radix hexadecimal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WLASTmi2s
add wave -noupdate -color {Slate Blue} -format Logic -radix hexadecimal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WREADYs2mi
add wave -noupdate -color {Slate Blue} -format Logic -radix hexadecimal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WVALIDmi2s
add wave -noupdate -format Literal -radix hexadecimal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/BIDmi2si
add wave -noupdate -format Literal -radix hexadecimal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/BIDs2mi
add wave -noupdate -format Logic -radix hexadecimal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/BREADYmi2s
add wave -noupdate -format Literal -radix hexadecimal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/BREADYsi2mi
add wave -noupdate -format Literal -radix hexadecimal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/BRESPs2mi
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/EnAREADYMUXn
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/EnAMUXn
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/LockArbiter
add wave -noupdate -color {Slate Blue} -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/StateLock
add wave -noupdate -divider {SLAVE1 RD}
add wave -noupdate -format Literal -radix hexadecimal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARADDRmi2s
add wave -noupdate -format Literal -radix hexadecimal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARIDmi2s
add wave -noupdate -color Aquamarine -format Literal -radix hexadecimal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWLOCKmi2s
add wave -noupdate -color Aquamarine -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWVALIDsi2mi
add wave -noupdate -expand -group VALID
add wave -noupdate -group VALID -format Logic -height 15 /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWVALIDmi2s
add wave -noupdate -group VALID -format Logic -height 15 /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARVALIDmi2s
add wave -noupdate -color Magenta -format Literal -radix hexadecimal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARLOCKmi2s
add wave -noupdate -format Logic -radix hexadecimal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARVALIDmi2s
add wave -noupdate -format Logic -radix hexadecimal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARREADYs2mi
add wave -noupdate -color {Slate Blue} -format Literal -radix hexadecimal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RDATAs2mi
add wave -noupdate -color {Slate Blue} -format Literal -radix hexadecimal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RIDs2mi
add wave -noupdate -color {Slate Blue} -format Logic -radix hexadecimal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RLASTs2mi
add wave -noupdate -color {Slate Blue} -format Logic -radix hexadecimal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RREADYmi2s
add wave -noupdate -color {Slate Blue} -format Logic -radix hexadecimal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RVALIDs2mi
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/EnAMUXn
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/EnAREADYMUXn
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/DataCntEmptyRdmi2Wrmi
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/Empty
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/LockPort
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/CtlData
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ArbiterMask
add wave -noupdate -color {Slate Blue} -format Literal -radix binary /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/StateLock
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/NxStateLock
add wave -noupdate -divider {New Divider}
add wave -noupdate -divider {TEST M1_WR}
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster1/AWID
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster1/AWLOCK
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster1/AWADDR
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster1/AWREADY
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster1/AWVALID
add wave -noupdate -divider {TEST M1_RD}
add wave -noupdate -format Literal /tb/TestMaster1/ARID
add wave -noupdate -format Literal /tb/TestMaster1/ARLOCK
add wave -noupdate -format Logic /tb/TestMaster1/ARVALID
add wave -noupdate -format Logic /tb/TestMaster1/ARREADY
add wave -noupdate -divider {New Divider}
add wave -noupdate -divider {TEST M3 WR}
add wave -noupdate -format Literal /tb/TestMaster3/AWID
add wave -noupdate -format Literal /tb/TestMaster3/AWLOCK
add wave -noupdate -format Logic /tb/TestMaster3/AWVALID
add wave -noupdate -format Logic /tb/TestMaster3/AWREADY
add wave -noupdate -divider {TEST M3 RD}
add wave -noupdate -format Literal /tb/TestMaster3/ARID
add wave -noupdate -format Literal /tb/TestMaster3/ARLOCK
add wave -noupdate -format Logic /tb/TestMaster3/ARVALID
add wave -noupdate -format Logic /tb/TestMaster3/ARREADY
add wave -noupdate -divider {New Divider}
add wave -noupdate -divider {New Divider}
add wave -noupdate -divider {New Divider}
add wave -noupdate -divider {New Divider}
add wave -noupdate -divider {New Divider}
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDm02si0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDm12si1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDm22si2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDm32si3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDmi02s0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDmi12s1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDmi22s2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDmi32s3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDmi42s4
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDmi52s5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi2mi0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi2mi1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi2mi2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi2mi3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi2mi4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi2mi5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi32mi
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic /tb/SBUS/AWVALIDm02si0
add wave -noupdate -format Logic /tb/SBUS/AWVALIDm12si1
add wave -noupdate -format Logic /tb/SBUS/AWVALIDm22si2
add wave -noupdate -format Logic /tb/SBUS/AWVALIDm32si3
add wave -noupdate -format Logic /tb/SBUS/AWVALIDmi02s0
add wave -noupdate -format Logic /tb/SBUS/AWVALIDmi12s1
add wave -noupdate -format Logic /tb/SBUS/AWVALIDmi22s2
add wave -noupdate -format Logic /tb/SBUS/AWVALIDmi32s3
add wave -noupdate -format Logic /tb/SBUS/AWVALIDmi42s4
add wave -noupdate -format Logic /tb/SBUS/AWVALIDmi52s5
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic /tb/SBUS/ACLK
add wave -noupdate -format Logic /tb/SBUS/ARESETn
add wave -noupdate -format Literal /tb/SBUS/AWIDm02si0
add wave -noupdate -format Literal /tb/SBUS/AWADDRm02si0
add wave -noupdate -format Literal /tb/SBUS/AWLENm02si0
add wave -noupdate -format Literal /tb/SBUS/AWSIZEm02si0
add wave -noupdate -format Literal /tb/SBUS/AWBURSTm02si0
add wave -noupdate -format Literal /tb/SBUS/AWLOCKm02si0
add wave -noupdate -format Literal /tb/SBUS/AWCACHEm02si0
add wave -noupdate -format Literal /tb/SBUS/AWPROTm02si0
add wave -noupdate -format Logic /tb/SBUS/AWVALIDm02si0
add wave -noupdate -format Logic /tb/SBUS/AWREADYsi02m0
add wave -noupdate -format Literal /tb/SBUS/WIDm02si0
add wave -noupdate -format Literal /tb/SBUS/WDATAm02si0
add wave -noupdate -format Literal /tb/SBUS/WSTRBm02si0
add wave -noupdate -format Logic /tb/SBUS/WLASTm02si0
add wave -noupdate -format Logic /tb/SBUS/WVALIDm02si0
add wave -noupdate -format Logic /tb/SBUS/WREADYsi02m0
add wave -noupdate -format Literal /tb/SBUS/BIDsi02m0
add wave -noupdate -format Literal /tb/SBUS/BRESPsi02m0
add wave -noupdate -format Logic /tb/SBUS/BVALIDsi02m0
add wave -noupdate -format Logic /tb/SBUS/BREADYm02si0
add wave -noupdate -format Literal /tb/SBUS/AWIDm12si1
add wave -noupdate -format Literal /tb/SBUS/AWADDRm12si1
add wave -noupdate -format Literal /tb/SBUS/AWLENm12si1
add wave -noupdate -format Literal /tb/SBUS/AWSIZEm12si1
add wave -noupdate -format Literal /tb/SBUS/AWBURSTm12si1
add wave -noupdate -format Literal /tb/SBUS/AWLOCKm12si1
add wave -noupdate -format Literal /tb/SBUS/AWCACHEm12si1
add wave -noupdate -format Literal /tb/SBUS/AWPROTm12si1
add wave -noupdate -format Logic /tb/SBUS/AWVALIDm12si1
add wave -noupdate -format Logic /tb/SBUS/AWREADYsi12m1
add wave -noupdate -format Literal /tb/SBUS/WIDm12si1
add wave -noupdate -format Literal /tb/SBUS/WDATAm12si1
add wave -noupdate -format Literal /tb/SBUS/WSTRBm12si1
add wave -noupdate -format Logic /tb/SBUS/WLASTm12si1
add wave -noupdate -format Logic /tb/SBUS/WVALIDm12si1
add wave -noupdate -format Logic /tb/SBUS/WREADYsi12m1
add wave -noupdate -format Literal /tb/SBUS/BIDsi12m1
add wave -noupdate -format Literal /tb/SBUS/BRESPsi12m1
add wave -noupdate -format Logic /tb/SBUS/BVALIDsi12m1
add wave -noupdate -format Logic /tb/SBUS/BREADYm12si1
add wave -noupdate -format Literal /tb/SBUS/AWIDm22si2
add wave -noupdate -format Literal /tb/SBUS/AWADDRm22si2
add wave -noupdate -format Literal /tb/SBUS/AWLENm22si2
add wave -noupdate -format Literal /tb/SBUS/AWSIZEm22si2
add wave -noupdate -format Literal /tb/SBUS/AWBURSTm22si2
add wave -noupdate -format Literal /tb/SBUS/AWLOCKm22si2
add wave -noupdate -format Literal /tb/SBUS/AWCACHEm22si2
add wave -noupdate -format Literal /tb/SBUS/AWPROTm22si2
add wave -noupdate -format Logic /tb/SBUS/AWVALIDm22si2
add wave -noupdate -format Logic /tb/SBUS/AWREADYsi22m2
add wave -noupdate -format Literal /tb/SBUS/WIDm22si2
add wave -noupdate -format Literal /tb/SBUS/WDATAm22si2
add wave -noupdate -format Literal /tb/SBUS/WSTRBm22si2
add wave -noupdate -format Logic /tb/SBUS/WLASTm22si2
add wave -noupdate -format Logic /tb/SBUS/WVALIDm22si2
add wave -noupdate -format Logic /tb/SBUS/WREADYsi22m2
add wave -noupdate -format Literal /tb/SBUS/BIDsi22m2
add wave -noupdate -format Literal /tb/SBUS/BRESPsi22m2
add wave -noupdate -format Logic /tb/SBUS/BVALIDsi22m2
add wave -noupdate -format Logic /tb/SBUS/BREADYm22si2
add wave -noupdate -format Literal /tb/SBUS/AWIDm32si3
add wave -noupdate -format Literal /tb/SBUS/AWADDRm32si3
add wave -noupdate -format Literal /tb/SBUS/AWLENm32si3
add wave -noupdate -format Literal /tb/SBUS/AWSIZEm32si3
add wave -noupdate -format Literal /tb/SBUS/AWBURSTm32si3
add wave -noupdate -format Literal /tb/SBUS/AWLOCKm32si3
add wave -noupdate -format Literal /tb/SBUS/AWCACHEm32si3
add wave -noupdate -format Literal /tb/SBUS/AWPROTm32si3
add wave -noupdate -format Logic /tb/SBUS/AWVALIDm32si3
add wave -noupdate -format Logic /tb/SBUS/AWREADYsi32m3
add wave -noupdate -format Literal /tb/SBUS/WIDm32si3
add wave -noupdate -format Literal /tb/SBUS/WDATAm32si3
add wave -noupdate -format Literal /tb/SBUS/WSTRBm32si3
add wave -noupdate -format Logic /tb/SBUS/WLASTm32si3
add wave -noupdate -format Logic /tb/SBUS/WVALIDm32si3
add wave -noupdate -format Logic /tb/SBUS/WREADYsi32m3
add wave -noupdate -format Literal /tb/SBUS/BIDsi32m3
add wave -noupdate -format Literal /tb/SBUS/BRESPsi32m3
add wave -noupdate -format Logic /tb/SBUS/BVALIDsi32m3
add wave -noupdate -format Logic /tb/SBUS/BREADYm32si3
add wave -noupdate -format Literal /tb/SBUS/AWIDmi02s0
add wave -noupdate -format Literal /tb/SBUS/AWADDRmi02s0
add wave -noupdate -format Literal /tb/SBUS/AWLENmi02s0
add wave -noupdate -format Literal /tb/SBUS/AWSIZEmi02s0
add wave -noupdate -format Literal /tb/SBUS/AWBURSTmi02s0
add wave -noupdate -format Literal /tb/SBUS/AWLOCKmi02s0
add wave -noupdate -format Literal /tb/SBUS/AWCACHEmi02s0
add wave -noupdate -format Literal /tb/SBUS/AWPROTmi02s0
add wave -noupdate -format Logic /tb/SBUS/AWVALIDmi02s0
add wave -noupdate -format Logic /tb/SBUS/AWREADYs02mi0
add wave -noupdate -format Literal /tb/SBUS/WIDmi02s0
add wave -noupdate -format Literal /tb/SBUS/WDATAmi02s0
add wave -noupdate -format Literal /tb/SBUS/WSTRBmi02s0
add wave -noupdate -format Logic /tb/SBUS/WLASTmi02s0
add wave -noupdate -format Logic /tb/SBUS/WVALIDmi02s0
add wave -noupdate -format Logic /tb/SBUS/WREADYs02mi0
add wave -noupdate -format Literal /tb/SBUS/BIDs02mi0
add wave -noupdate -format Literal /tb/SBUS/BRESPs02mi0
add wave -noupdate -format Logic /tb/SBUS/BVALIDs02mi0
add wave -noupdate -format Logic /tb/SBUS/BREADYmi02s0
add wave -noupdate -format Literal /tb/SBUS/AWIDmi12s1
add wave -noupdate -format Literal /tb/SBUS/AWADDRmi12s1
add wave -noupdate -format Literal /tb/SBUS/AWLENmi12s1
add wave -noupdate -format Literal /tb/SBUS/AWSIZEmi12s1
add wave -noupdate -format Literal /tb/SBUS/AWBURSTmi12s1
add wave -noupdate -format Literal /tb/SBUS/AWLOCKmi12s1
add wave -noupdate -format Literal /tb/SBUS/AWCACHEmi12s1
add wave -noupdate -format Literal /tb/SBUS/AWPROTmi12s1
add wave -noupdate -format Logic /tb/SBUS/AWVALIDmi12s1
add wave -noupdate -format Logic /tb/SBUS/AWREADYs12mi1
add wave -noupdate -format Literal /tb/SBUS/WIDmi12s1
add wave -noupdate -format Literal /tb/SBUS/WDATAmi12s1
add wave -noupdate -format Literal /tb/SBUS/WSTRBmi12s1
add wave -noupdate -format Logic /tb/SBUS/WLASTmi12s1
add wave -noupdate -format Logic /tb/SBUS/WVALIDmi12s1
add wave -noupdate -format Logic /tb/SBUS/WREADYs12mi1
add wave -noupdate -format Literal /tb/SBUS/BIDs12mi1
add wave -noupdate -format Literal /tb/SBUS/BRESPs12mi1
add wave -noupdate -format Logic /tb/SBUS/BVALIDs12mi1
add wave -noupdate -format Logic /tb/SBUS/BREADYmi12s1
add wave -noupdate -format Literal /tb/SBUS/AWIDmi22s2
add wave -noupdate -format Literal /tb/SBUS/AWADDRmi22s2
add wave -noupdate -format Literal /tb/SBUS/AWLENmi22s2
add wave -noupdate -format Literal /tb/SBUS/AWSIZEmi22s2
add wave -noupdate -format Literal /tb/SBUS/AWBURSTmi22s2
add wave -noupdate -format Literal /tb/SBUS/AWLOCKmi22s2
add wave -noupdate -format Literal /tb/SBUS/AWCACHEmi22s2
add wave -noupdate -format Literal /tb/SBUS/AWPROTmi22s2
add wave -noupdate -format Logic /tb/SBUS/AWVALIDmi22s2
add wave -noupdate -format Logic /tb/SBUS/AWREADYs22mi2
add wave -noupdate -format Literal /tb/SBUS/WIDmi22s2
add wave -noupdate -format Literal /tb/SBUS/WDATAmi22s2
add wave -noupdate -format Literal /tb/SBUS/WSTRBmi22s2
add wave -noupdate -format Logic /tb/SBUS/WLASTmi22s2
add wave -noupdate -format Logic /tb/SBUS/WVALIDmi22s2
add wave -noupdate -format Logic /tb/SBUS/WREADYs22mi2
add wave -noupdate -format Literal /tb/SBUS/BIDs22mi2
add wave -noupdate -format Literal /tb/SBUS/BRESPs22mi2
add wave -noupdate -format Logic /tb/SBUS/BVALIDs22mi2
add wave -noupdate -format Logic /tb/SBUS/BREADYmi22s2
add wave -noupdate -format Literal /tb/SBUS/AWIDmi32s3
add wave -noupdate -format Literal /tb/SBUS/AWADDRmi32s3
add wave -noupdate -format Literal /tb/SBUS/AWLENmi32s3
add wave -noupdate -format Literal /tb/SBUS/AWSIZEmi32s3
add wave -noupdate -format Literal /tb/SBUS/AWBURSTmi32s3
add wave -noupdate -format Literal /tb/SBUS/AWLOCKmi32s3
add wave -noupdate -format Literal /tb/SBUS/AWCACHEmi32s3
add wave -noupdate -format Literal /tb/SBUS/AWPROTmi32s3
add wave -noupdate -format Logic /tb/SBUS/AWVALIDmi32s3
add wave -noupdate -format Logic /tb/SBUS/AWREADYs32mi3
add wave -noupdate -format Literal /tb/SBUS/WIDmi32s3
add wave -noupdate -format Literal /tb/SBUS/WDATAmi32s3
add wave -noupdate -format Literal /tb/SBUS/WSTRBmi32s3
add wave -noupdate -format Logic /tb/SBUS/WLASTmi32s3
add wave -noupdate -format Logic /tb/SBUS/WVALIDmi32s3
add wave -noupdate -format Logic /tb/SBUS/WREADYs32mi3
add wave -noupdate -format Literal /tb/SBUS/BIDs32mi3
add wave -noupdate -format Literal /tb/SBUS/BRESPs32mi3
add wave -noupdate -format Logic /tb/SBUS/BVALIDs32mi3
add wave -noupdate -format Logic /tb/SBUS/BREADYmi32s3
add wave -noupdate -format Literal /tb/SBUS/AWIDmi42s4
add wave -noupdate -format Literal /tb/SBUS/AWADDRmi42s4
add wave -noupdate -format Literal /tb/SBUS/AWLENmi42s4
add wave -noupdate -format Literal /tb/SBUS/AWSIZEmi42s4
add wave -noupdate -format Literal /tb/SBUS/AWBURSTmi42s4
add wave -noupdate -format Literal /tb/SBUS/AWLOCKmi42s4
add wave -noupdate -format Literal /tb/SBUS/AWCACHEmi42s4
add wave -noupdate -format Literal /tb/SBUS/AWPROTmi42s4
add wave -noupdate -format Logic /tb/SBUS/AWVALIDmi42s4
add wave -noupdate -format Logic /tb/SBUS/AWREADYs42mi4
add wave -noupdate -format Literal /tb/SBUS/WIDmi42s4
add wave -noupdate -format Literal /tb/SBUS/WDATAmi42s4
add wave -noupdate -format Literal /tb/SBUS/WSTRBmi42s4
add wave -noupdate -format Logic /tb/SBUS/WLASTmi42s4
add wave -noupdate -format Logic /tb/SBUS/WVALIDmi42s4
add wave -noupdate -format Logic /tb/SBUS/WREADYs42mi4
add wave -noupdate -format Literal /tb/SBUS/BIDs42mi4
add wave -noupdate -format Literal /tb/SBUS/BRESPs42mi4
add wave -noupdate -format Logic /tb/SBUS/BVALIDs42mi4
add wave -noupdate -format Logic /tb/SBUS/BREADYmi42s4
add wave -noupdate -format Literal /tb/SBUS/AWIDmi52s5
add wave -noupdate -format Literal /tb/SBUS/AWADDRmi52s5
add wave -noupdate -format Literal /tb/SBUS/AWLENmi52s5
add wave -noupdate -format Literal /tb/SBUS/AWSIZEmi52s5
add wave -noupdate -format Literal /tb/SBUS/AWBURSTmi52s5
add wave -noupdate -format Literal /tb/SBUS/AWLOCKmi52s5
add wave -noupdate -format Literal /tb/SBUS/AWCACHEmi52s5
add wave -noupdate -format Literal /tb/SBUS/AWPROTmi52s5
add wave -noupdate -format Logic /tb/SBUS/AWVALIDmi52s5
add wave -noupdate -format Logic /tb/SBUS/AWREADYs52mi5
add wave -noupdate -format Literal /tb/SBUS/WIDmi52s5
add wave -noupdate -format Literal /tb/SBUS/WDATAmi52s5
add wave -noupdate -format Literal /tb/SBUS/WSTRBmi52s5
add wave -noupdate -format Logic /tb/SBUS/WLASTmi52s5
add wave -noupdate -format Logic /tb/SBUS/WVALIDmi52s5
add wave -noupdate -format Logic /tb/SBUS/WREADYs52mi5
add wave -noupdate -format Literal /tb/SBUS/BIDs52mi5
add wave -noupdate -format Literal /tb/SBUS/BRESPs52mi5
add wave -noupdate -format Logic /tb/SBUS/BVALIDs52mi5
add wave -noupdate -format Logic /tb/SBUS/BREADYmi52s5
add wave -noupdate -format Literal /tb/SBUS/ARIDm02si0
add wave -noupdate -format Literal /tb/SBUS/ARADDRm02si0
add wave -noupdate -format Literal /tb/SBUS/ARLENm02si0
add wave -noupdate -format Literal /tb/SBUS/ARSIZEm02si0
add wave -noupdate -format Literal /tb/SBUS/ARBURSTm02si0
add wave -noupdate -format Literal /tb/SBUS/ARLOCKm02si0
add wave -noupdate -format Literal /tb/SBUS/ARCACHEm02si0
add wave -noupdate -format Literal /tb/SBUS/ARPROTm02si0
add wave -noupdate -format Logic /tb/SBUS/ARVALIDm02si0
add wave -noupdate -format Logic /tb/SBUS/ARREADYsi02m0
add wave -noupdate -format Literal /tb/SBUS/RIDsi02m0
add wave -noupdate -format Literal /tb/SBUS/RRESPsi02m0
add wave -noupdate -format Literal /tb/SBUS/RDATAsi02m0
add wave -noupdate -format Logic /tb/SBUS/RLASTsi02m0
add wave -noupdate -format Logic /tb/SBUS/RVALIDsi02m0
add wave -noupdate -format Logic /tb/SBUS/RREADYm02si0
add wave -noupdate -format Literal /tb/SBUS/ARIDm12si1
add wave -noupdate -format Literal /tb/SBUS/ARADDRm12si1
add wave -noupdate -format Literal /tb/SBUS/ARLENm12si1
add wave -noupdate -format Literal /tb/SBUS/ARSIZEm12si1
add wave -noupdate -format Literal /tb/SBUS/ARBURSTm12si1
add wave -noupdate -format Literal /tb/SBUS/ARLOCKm12si1
add wave -noupdate -format Literal /tb/SBUS/ARCACHEm12si1
add wave -noupdate -format Literal /tb/SBUS/ARPROTm12si1
add wave -noupdate -format Logic /tb/SBUS/ARVALIDm12si1
add wave -noupdate -format Logic /tb/SBUS/ARREADYsi12m1
add wave -noupdate -format Literal /tb/SBUS/RIDsi12m1
add wave -noupdate -format Literal /tb/SBUS/RRESPsi12m1
add wave -noupdate -format Literal /tb/SBUS/RDATAsi12m1
add wave -noupdate -format Logic /tb/SBUS/RLASTsi12m1
add wave -noupdate -format Logic /tb/SBUS/RVALIDsi12m1
add wave -noupdate -format Logic /tb/SBUS/RREADYm12si1
add wave -noupdate -format Literal /tb/SBUS/ARIDm22si2
add wave -noupdate -format Literal /tb/SBUS/ARADDRm22si2
add wave -noupdate -format Literal /tb/SBUS/ARLENm22si2
add wave -noupdate -format Literal /tb/SBUS/ARSIZEm22si2
add wave -noupdate -format Literal /tb/SBUS/ARBURSTm22si2
add wave -noupdate -format Literal /tb/SBUS/ARLOCKm22si2
add wave -noupdate -format Literal /tb/SBUS/ARCACHEm22si2
add wave -noupdate -format Literal /tb/SBUS/ARPROTm22si2
add wave -noupdate -format Logic /tb/SBUS/ARVALIDm22si2
add wave -noupdate -format Logic /tb/SBUS/ARREADYsi22m2
add wave -noupdate -format Literal /tb/SBUS/RIDsi22m2
add wave -noupdate -format Literal /tb/SBUS/RRESPsi22m2
add wave -noupdate -format Literal /tb/SBUS/RDATAsi22m2
add wave -noupdate -format Logic /tb/SBUS/RLASTsi22m2
add wave -noupdate -format Logic /tb/SBUS/RVALIDsi22m2
add wave -noupdate -format Logic /tb/SBUS/RREADYm22si2
add wave -noupdate -format Literal /tb/SBUS/ARIDm32si3
add wave -noupdate -format Literal /tb/SBUS/ARADDRm32si3
add wave -noupdate -format Literal /tb/SBUS/ARLENm32si3
add wave -noupdate -format Literal /tb/SBUS/ARSIZEm32si3
add wave -noupdate -format Literal /tb/SBUS/ARBURSTm32si3
add wave -noupdate -format Literal /tb/SBUS/ARLOCKm32si3
add wave -noupdate -format Literal /tb/SBUS/ARCACHEm32si3
add wave -noupdate -format Literal /tb/SBUS/ARPROTm32si3
add wave -noupdate -format Logic /tb/SBUS/ARVALIDm32si3
add wave -noupdate -format Logic /tb/SBUS/ARREADYsi32m3
add wave -noupdate -format Literal /tb/SBUS/RIDsi32m3
add wave -noupdate -format Literal /tb/SBUS/RRESPsi32m3
add wave -noupdate -format Literal /tb/SBUS/RDATAsi32m3
add wave -noupdate -format Logic /tb/SBUS/RLASTsi32m3
add wave -noupdate -format Logic /tb/SBUS/RVALIDsi32m3
add wave -noupdate -format Logic /tb/SBUS/RREADYm32si3
add wave -noupdate -format Literal /tb/SBUS/ARIDmi02s0
add wave -noupdate -format Literal /tb/SBUS/ARADDRmi02s0
add wave -noupdate -format Literal /tb/SBUS/ARLENmi02s0
add wave -noupdate -format Literal /tb/SBUS/ARSIZEmi02s0
add wave -noupdate -format Literal /tb/SBUS/ARBURSTmi02s0
add wave -noupdate -format Literal /tb/SBUS/ARLOCKmi02s0
add wave -noupdate -format Literal /tb/SBUS/ARCACHEmi02s0
add wave -noupdate -format Literal /tb/SBUS/ARPROTmi02s0
add wave -noupdate -format Logic /tb/SBUS/ARVALIDmi02s0
add wave -noupdate -format Logic /tb/SBUS/ARREADYs02mi0
add wave -noupdate -format Literal /tb/SBUS/RIDs02mi0
add wave -noupdate -format Literal /tb/SBUS/RRESPs02mi0
add wave -noupdate -format Literal /tb/SBUS/RDATAs02mi0
add wave -noupdate -format Logic /tb/SBUS/RLASTs02mi0
add wave -noupdate -format Logic /tb/SBUS/RVALIDs02mi0
add wave -noupdate -format Logic /tb/SBUS/RREADYmi02s0
add wave -noupdate -format Literal /tb/SBUS/ARIDmi12s1
add wave -noupdate -format Literal /tb/SBUS/ARADDRmi12s1
add wave -noupdate -format Literal /tb/SBUS/ARLENmi12s1
add wave -noupdate -format Literal /tb/SBUS/ARSIZEmi12s1
add wave -noupdate -format Literal /tb/SBUS/ARBURSTmi12s1
add wave -noupdate -format Literal /tb/SBUS/ARLOCKmi12s1
add wave -noupdate -format Literal /tb/SBUS/ARCACHEmi12s1
add wave -noupdate -format Literal /tb/SBUS/ARPROTmi12s1
add wave -noupdate -format Logic /tb/SBUS/ARVALIDmi12s1
add wave -noupdate -format Logic /tb/SBUS/ARREADYs12mi1
add wave -noupdate -format Literal /tb/SBUS/RIDs12mi1
add wave -noupdate -format Literal /tb/SBUS/RRESPs12mi1
add wave -noupdate -format Literal /tb/SBUS/RDATAs12mi1
add wave -noupdate -format Logic /tb/SBUS/RLASTs12mi1
add wave -noupdate -format Logic /tb/SBUS/RVALIDs12mi1
add wave -noupdate -format Logic /tb/SBUS/RREADYmi12s1
add wave -noupdate -format Literal /tb/SBUS/ARIDmi22s2
add wave -noupdate -format Literal /tb/SBUS/ARADDRmi22s2
add wave -noupdate -format Literal /tb/SBUS/ARLENmi22s2
add wave -noupdate -format Literal /tb/SBUS/ARSIZEmi22s2
add wave -noupdate -format Literal /tb/SBUS/ARBURSTmi22s2
add wave -noupdate -format Literal /tb/SBUS/ARLOCKmi22s2
add wave -noupdate -format Literal /tb/SBUS/ARCACHEmi22s2
add wave -noupdate -format Literal /tb/SBUS/ARPROTmi22s2
add wave -noupdate -format Logic /tb/SBUS/ARVALIDmi22s2
add wave -noupdate -format Logic /tb/SBUS/ARREADYs22mi2
add wave -noupdate -format Literal /tb/SBUS/RIDs22mi2
add wave -noupdate -format Literal /tb/SBUS/RRESPs22mi2
add wave -noupdate -format Literal /tb/SBUS/RDATAs22mi2
add wave -noupdate -format Logic /tb/SBUS/RLASTs22mi2
add wave -noupdate -format Logic /tb/SBUS/RVALIDs22mi2
add wave -noupdate -format Logic /tb/SBUS/RREADYmi22s2
add wave -noupdate -format Literal /tb/SBUS/ARIDmi32s3
add wave -noupdate -format Literal /tb/SBUS/ARADDRmi32s3
add wave -noupdate -format Literal /tb/SBUS/ARLENmi32s3
add wave -noupdate -format Literal /tb/SBUS/ARSIZEmi32s3
add wave -noupdate -format Literal /tb/SBUS/ARBURSTmi32s3
add wave -noupdate -format Literal /tb/SBUS/ARLOCKmi32s3
add wave -noupdate -format Literal /tb/SBUS/ARCACHEmi32s3
add wave -noupdate -format Literal /tb/SBUS/ARPROTmi32s3
add wave -noupdate -format Logic /tb/SBUS/ARVALIDmi32s3
add wave -noupdate -format Logic /tb/SBUS/ARREADYs32mi3
add wave -noupdate -format Literal /tb/SBUS/RIDs32mi3
add wave -noupdate -format Literal /tb/SBUS/RRESPs32mi3
add wave -noupdate -format Literal /tb/SBUS/RDATAs32mi3
add wave -noupdate -format Logic /tb/SBUS/RLASTs32mi3
add wave -noupdate -format Logic /tb/SBUS/RVALIDs32mi3
add wave -noupdate -format Logic /tb/SBUS/RREADYmi32s3
add wave -noupdate -format Literal /tb/SBUS/ARIDmi42s4
add wave -noupdate -format Literal /tb/SBUS/ARADDRmi42s4
add wave -noupdate -format Literal /tb/SBUS/ARLENmi42s4
add wave -noupdate -format Literal /tb/SBUS/ARSIZEmi42s4
add wave -noupdate -format Literal /tb/SBUS/ARBURSTmi42s4
add wave -noupdate -format Literal /tb/SBUS/ARLOCKmi42s4
add wave -noupdate -format Literal /tb/SBUS/ARCACHEmi42s4
add wave -noupdate -format Literal /tb/SBUS/ARPROTmi42s4
add wave -noupdate -format Logic /tb/SBUS/ARVALIDmi42s4
add wave -noupdate -format Logic /tb/SBUS/ARREADYs42mi4
add wave -noupdate -format Literal /tb/SBUS/RIDs42mi4
add wave -noupdate -format Literal /tb/SBUS/RRESPs42mi4
add wave -noupdate -format Literal /tb/SBUS/RDATAs42mi4
add wave -noupdate -format Logic /tb/SBUS/RLASTs42mi4
add wave -noupdate -format Logic /tb/SBUS/RVALIDs42mi4
add wave -noupdate -format Logic /tb/SBUS/RREADYmi42s4
add wave -noupdate -format Literal /tb/SBUS/ARIDmi52s5
add wave -noupdate -format Literal /tb/SBUS/ARADDRmi52s5
add wave -noupdate -format Literal /tb/SBUS/ARLENmi52s5
add wave -noupdate -format Literal /tb/SBUS/ARSIZEmi52s5
add wave -noupdate -format Literal /tb/SBUS/ARBURSTmi52s5
add wave -noupdate -format Literal /tb/SBUS/ARLOCKmi52s5
add wave -noupdate -format Literal /tb/SBUS/ARCACHEmi52s5
add wave -noupdate -format Literal /tb/SBUS/ARPROTmi52s5
add wave -noupdate -format Logic /tb/SBUS/ARVALIDmi52s5
add wave -noupdate -format Logic /tb/SBUS/ARREADYs52mi5
add wave -noupdate -format Literal /tb/SBUS/RIDs52mi5
add wave -noupdate -format Literal /tb/SBUS/RRESPs52mi5
add wave -noupdate -format Literal /tb/SBUS/RDATAs52mi5
add wave -noupdate -format Logic /tb/SBUS/RLASTs52mi5
add wave -noupdate -format Logic /tb/SBUS/RVALIDs52mi5
add wave -noupdate -format Logic /tb/SBUS/RREADYmi52s5
add wave -noupdate -format Literal /tb/SBUS/CtlDataWrite2Lock0
add wave -noupdate -format Literal /tb/SBUS/CtlDataWrite2Lock1
add wave -noupdate -format Literal /tb/SBUS/CtlDataWrite2Lock2
add wave -noupdate -format Literal /tb/SBUS/CtlDataWrite2Lock3
add wave -noupdate -format Literal /tb/SBUS/CtlDataWrite2Lock4
add wave -noupdate -format Literal /tb/SBUS/CtlDataWrite2Lock5
add wave -noupdate -format Literal /tb/SBUS/CtlDataRead2Lock0
add wave -noupdate -format Literal /tb/SBUS/CtlDataRead2Lock1
add wave -noupdate -format Literal /tb/SBUS/CtlDataRead2Lock2
add wave -noupdate -format Literal /tb/SBUS/CtlDataRead2Lock3
add wave -noupdate -format Literal /tb/SBUS/CtlDataRead2Lock4
add wave -noupdate -format Literal /tb/SBUS/CtlDataRead2Lock5
add wave -noupdate -format Logic /tb/SBUS/Lock2wrmi0
add wave -noupdate -format Logic /tb/SBUS/Lock2wrmi1
add wave -noupdate -format Logic /tb/SBUS/Lock2wrmi2
add wave -noupdate -format Logic /tb/SBUS/Lock2wrmi3
add wave -noupdate -format Logic /tb/SBUS/Lock2wrmi4
add wave -noupdate -format Logic /tb/SBUS/Lock2wrmi5
add wave -noupdate -format Logic /tb/SBUS/UnLock2wrmi0
add wave -noupdate -format Logic /tb/SBUS/UnLock2wrmi1
add wave -noupdate -format Logic /tb/SBUS/UnLock2wrmi2
add wave -noupdate -format Logic /tb/SBUS/UnLock2wrmi3
add wave -noupdate -format Logic /tb/SBUS/UnLock2wrmi4
add wave -noupdate -format Logic /tb/SBUS/UnLock2wrmi5
add wave -noupdate -format Logic /tb/SBUS/Lock2rdmi0
add wave -noupdate -format Logic /tb/SBUS/Lock2rdmi1
add wave -noupdate -format Logic /tb/SBUS/Lock2rdmi2
add wave -noupdate -format Logic /tb/SBUS/Lock2rdmi3
add wave -noupdate -format Logic /tb/SBUS/Lock2rdmi4
add wave -noupdate -format Logic /tb/SBUS/Lock2rdmi5
add wave -noupdate -format Logic /tb/SBUS/UnLock2rdmi0
add wave -noupdate -format Logic /tb/SBUS/UnLock2rdmi1
add wave -noupdate -format Logic /tb/SBUS/UnLock2rdmi2
add wave -noupdate -format Logic /tb/SBUS/UnLock2rdmi3
add wave -noupdate -format Logic /tb/SBUS/UnLock2rdmi4
add wave -noupdate -format Logic /tb/SBUS/UnLock2rdmi5
add wave -noupdate -format Literal /tb/SBUS/LockPort2wrmi0
add wave -noupdate -format Literal /tb/SBUS/LockPort2wrmi1
add wave -noupdate -format Literal /tb/SBUS/LockPort2wrmi2
add wave -noupdate -format Literal /tb/SBUS/LockPort2wrmi3
add wave -noupdate -format Literal /tb/SBUS/LockPort2wrmi4
add wave -noupdate -format Literal /tb/SBUS/LockPort2wrmi5
add wave -noupdate -format Literal /tb/SBUS/LockPort2rdmi0
add wave -noupdate -format Literal /tb/SBUS/LockPort2rdmi1
add wave -noupdate -format Literal /tb/SBUS/LockPort2rdmi2
add wave -noupdate -format Literal /tb/SBUS/LockPort2rdmi3
add wave -noupdate -format Literal /tb/SBUS/LockPort2rdmi4
add wave -noupdate -format Literal /tb/SBUS/LockPort2rdmi5
add wave -noupdate -format Logic /tb/SBUS/ReadIntEmptyWrmi02Rdmi0
add wave -noupdate -format Logic /tb/SBUS/ReadIntEmptyWrmi12Rdmi1
add wave -noupdate -format Logic /tb/SBUS/ReadIntEmptyWrmi22Rdmi2
add wave -noupdate -format Logic /tb/SBUS/ReadIntEmptyWrmi32Rdmi3
add wave -noupdate -format Logic /tb/SBUS/ReadIntEmptyWrmi42Rdmi4
add wave -noupdate -format Logic /tb/SBUS/ReadIntEmptyWrmi52Rdmi5
add wave -noupdate -format Logic /tb/SBUS/DataCntEmptyRdmi02Wrmi0
add wave -noupdate -format Logic /tb/SBUS/DataCntEmptyRdmi12Wrmi1
add wave -noupdate -format Logic /tb/SBUS/DataCntEmptyRdmi22Wrmi2
add wave -noupdate -format Logic /tb/SBUS/DataCntEmptyRdmi32Wrmi3
add wave -noupdate -format Logic /tb/SBUS/DataCntEmptyRdmi42Wrmi4
add wave -noupdate -format Logic /tb/SBUS/DataCntEmptyRdmi52Wrmi5
add wave -noupdate -format Literal /tb/TestMaster3/MASTER_ID
add wave -noupdate -format Logic /tb/TestMaster3/ACLK
add wave -noupdate -format Logic /tb/TestMaster3/ARESETn
add wave -noupdate -format Literal /tb/TestMaster3/AWID
add wave -noupdate -format Literal /tb/TestMaster3/AWADDR
add wave -noupdate -format Literal /tb/TestMaster3/AWLEN
add wave -noupdate -format Literal /tb/TestMaster3/AWSIZE
add wave -noupdate -format Literal /tb/TestMaster3/AWBURST
add wave -noupdate -format Literal /tb/TestMaster3/AWLOCK
add wave -noupdate -format Literal /tb/TestMaster3/AWCACHE
add wave -noupdate -format Literal /tb/TestMaster3/AWPROT
add wave -noupdate -format Logic /tb/TestMaster3/AWVALID
add wave -noupdate -format Logic /tb/TestMaster3/AWREADY
add wave -noupdate -format Literal /tb/TestMaster3/WID
add wave -noupdate -format Literal /tb/TestMaster3/WDATA
add wave -noupdate -format Literal /tb/TestMaster3/WSTRB
add wave -noupdate -format Logic /tb/TestMaster3/WLAST
add wave -noupdate -format Logic /tb/TestMaster3/WVALID
add wave -noupdate -format Logic /tb/TestMaster3/WREADY
add wave -noupdate -format Literal /tb/TestMaster3/BID
add wave -noupdate -format Literal /tb/TestMaster3/BRESP
add wave -noupdate -format Logic /tb/TestMaster3/BVALID
add wave -noupdate -format Logic /tb/TestMaster3/BREADY
add wave -noupdate -format Literal /tb/TestMaster3/ARID
add wave -noupdate -format Literal /tb/TestMaster3/ARADDR
add wave -noupdate -format Literal /tb/TestMaster3/ARLEN
add wave -noupdate -format Literal /tb/TestMaster3/ARSIZE
add wave -noupdate -format Literal /tb/TestMaster3/ARBURST
add wave -noupdate -format Literal /tb/TestMaster3/ARLOCK
add wave -noupdate -format Literal /tb/TestMaster3/ARCACHE
add wave -noupdate -format Literal /tb/TestMaster3/ARPROT
add wave -noupdate -format Logic /tb/TestMaster3/ARVALID
add wave -noupdate -format Logic /tb/TestMaster3/ARREADY
add wave -noupdate -format Literal /tb/TestMaster3/RID
add wave -noupdate -format Literal /tb/TestMaster3/RDATA
add wave -noupdate -format Literal /tb/TestMaster3/RRESP
add wave -noupdate -format Logic /tb/TestMaster3/RLAST
add wave -noupdate -format Logic /tb/TestMaster3/RVALID
add wave -noupdate -format Logic /tb/TestMaster3/RREADY
add wave -noupdate -format Literal /tb/TestMaster3/AWQ_WINDEX
add wave -noupdate -format Literal /tb/TestMaster3/AWQ_RINDEX
add wave -noupdate -format Logic /tb/TestMaster3/AWQ_empty
add wave -noupdate -format Literal /tb/TestMaster3/WIDQ_WINDEX
add wave -noupdate -format Literal /tb/TestMaster3/WIDQ_RINDEX
add wave -noupdate -format Logic /tb/TestMaster3/WIDQ_full
add wave -noupdate -format Logic /tb/TestMaster3/WIDQ_empty
add wave -noupdate -format Literal /tb/TestMaster3/WDQ_RINDEX
add wave -noupdate -format Literal /tb/TestMaster3/WDQ_WINDEX
add wave -noupdate -format Logic /tb/TestMaster3/WDQ_empty
add wave -noupdate -format Literal /tb/TestMaster3/ARQ_WINDEX
add wave -noupdate -format Literal /tb/TestMaster3/ARQ_RINDEX
add wave -noupdate -format Logic /tb/TestMaster3/ARQ_empty
add wave -noupdate -format Literal /tb/TestMaster3/DecreaseWID
add wave -noupdate -format Logic /tb/TestMaster3/DecreaseWIDEnable
add wave -noupdate -format Literal /tb/TestMaster3/IncreaseWID
add wave -noupdate -format Logic /tb/TestMaster3/IncreaseWIDEnable
add wave -noupdate -format Literal /tb/TestMaster3/DecreaseRID
add wave -noupdate -format Logic /tb/TestMaster3/DecreaseRIDEnable
add wave -noupdate -format Literal /tb/TestMaster3/IncreaseRID
add wave -noupdate -format Logic /tb/TestMaster3/IncreaseRIDEnable
add wave -noupdate -format Literal /tb/TestMaster3/LOCK_ID
add wave -noupdate -format Literal /tb/TestMaster3/LOCK_ADDR
add wave -noupdate -format Literal /tb/TestMaster3/LOCK_BURSTLEN
add wave -noupdate -format Literal /tb/TestMaster3/LOCK_SLAVE
add wave -noupdate -format Logic /tb/TestMaster3/AW_idle
add wave -noupdate -format Logic /tb/TestMaster3/AW_RANDOM
add wave -noupdate -format Logic /tb/TestMaster3/WD_idle
add wave -noupdate -format Logic /tb/TestMaster3/WD_RANDOM
add wave -noupdate -format Logic /tb/TestMaster3/AR_idle
add wave -noupdate -format Logic /tb/TestMaster3/AR_RANDOM
add wave -noupdate -format Literal /tb/TestMaster3/i_rd
add wave -noupdate -format Literal /tb/TestMaster3/i_wid_temp
add wave -noupdate -format Literal /tb/TestMaster3/i_rid_temp
add wave -noupdate -format Logic /tb/TestMaster3/ResetIdleCnt
add wave -noupdate -format Literal /tb/TestMaster3/IdleCnt
add wave -noupdate -format Literal /tb/TestMaster3/situ
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/ACLK
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/ARESETn
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/ALOCK
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/AVALID
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/OVALID
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/ReqIntEmpty
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/DataCntEmptyRdmi2Wrmi
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/Lock
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/UnLock
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/LockPort
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/CtlData
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/ArbiterMask
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/EnAMUXn
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/EnAREADYMUXn
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/LockArbiter
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/StateLock
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/NxStateLock
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/LockAccess
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/UnLockAccess
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/U0LockCtlRdmi/Empty
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ACLK
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARESETn
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARIDmi2s
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARADDRmi2s
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARLENmi2s
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARSIZEmi2s
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARBURSTmi2s
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARLOCKmi2s
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARCACHEmi2s
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARPROTmi2s
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARVALIDmi2s
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARREADYs2mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RIDs2mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RRESPs2mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RDATAs2mi
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RLASTs2mi
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RVALIDs2mi
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RREADYmi2s
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARIDsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARADDRsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARLENsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARSIZEsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARBURSTsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARLOCKsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARCACHEsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARPROTsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARIDsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARADDRsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARLENsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARSIZEsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARBURSTsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARLOCKsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARCACHEsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARPROTsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARIDsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARADDRsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARLENsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARSIZEsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARBURSTsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARLOCKsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARCACHEsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARPROTsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARIDsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARADDRsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARLENsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARSIZEsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARBURSTsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARLOCKsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARCACHEsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARPROTsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARVALIDsi2mi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ARREADYmi2si
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RIDmi2si
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RRESPmi2si
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RDATAmi2si
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RVALIDmi2si
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RLASTmi2si
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/RREADYsi2mi
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/Lock
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/UnLock
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/AWVALID
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/LockPort
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ReadIntEmptyWrmi2Rdmi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/CtlDataRead2Lock
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/DataCntEmptyRdmi2Wrmi
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ArbiterMask
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/EnARMUXn
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/EnARREADYMUXn
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/LockArbiter
add wave -noupdate -format Literal /tb/SBUS/U0ReadChannel/U1ReadChannelmi/CtlData2RdchMux
add wave -noupdate -format Logic /tb/SBUS/U0ReadChannel/U1ReadChannelmi/ReqFull
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/ACLK
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/ARESETn
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/ALOCK
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/AVALID
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/OVALID
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/ReqIntEmpty
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/DataCntEmptyRdmi2Wrmi
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/Lock
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/UnLock
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/CtlData
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/EnAMUXn
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/EnAREADYMUXn
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/LockArbiter
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/StateLock
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/NxStateLock
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/LockAccess
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/UnLockAccess
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/U0LockCtlWrmi/Empty
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/ACLK
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/ARESETn
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWIDmi2s
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWADDRmi2s
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWLENmi2s
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWSIZEmi2s
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWBURSTmi2s
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWLOCKmi2s
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWCACHEmi2s
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWPROTmi2s
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWVALIDmi2s
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWREADYs2mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WIDmi2s
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WDATAmi2s
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WSTRBmi2s
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WLASTmi2s
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WVALIDmi2s
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WREADYs2mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/BIDs2mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/BRESPs2mi
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/BVALIDs2mi
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/BREADYmi2s
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWIDsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWADDRsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWLENsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWSIZEsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWBURSTsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWLOCKsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWCACHEsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWPROTsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWIDsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWADDRsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWLENsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWSIZEsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWBURSTsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWLOCKsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWCACHEsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWPROTsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWIDsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWADDRsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWLENsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWSIZEsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWBURSTsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWLOCKsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWCACHEsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWPROTsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWIDsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWADDRsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWLENsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWSIZEsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWBURSTsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWLOCKsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWCACHEsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWPROTsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWVALIDsi2mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/AWREADYmi2si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WIDsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WDATAsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WSTRBsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WIDsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WDATAsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WSTRBsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WIDsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WDATAsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WSTRBsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WIDsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WDATAsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WSTRBsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WLASTsi2mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WVALIDsi2mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/WREADYmi2si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/BIDmi2si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/BRESPmi2si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/BVALIDmi2si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/BREADYsi2mi
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/Lock
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/UnLock
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/ARVALID
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/DataCntEmptyRdmi2Wrmi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/LockPort
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/CtlDataWrite2Lock
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/ReadIntEmptyWrmi2Rdmi
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/ReqFull
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/EnAWMUXn
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/U1WriteChannelmi/EnAWREADYMUXn
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/LockArbiter
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/CtlData2WrchMux
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/U1WriteChannelmi/CtlData2DatachMux
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Literal /tb/TestMaster1/MASTER_ID
add wave -noupdate -format Logic /tb/TestMaster1/ACLK
add wave -noupdate -format Logic /tb/TestMaster1/ARESETn
add wave -noupdate -format Literal /tb/TestMaster1/AWID
add wave -noupdate -format Literal /tb/TestMaster1/AWADDR
add wave -noupdate -format Literal /tb/TestMaster1/AWLEN
add wave -noupdate -format Literal /tb/TestMaster1/AWSIZE
add wave -noupdate -format Literal /tb/TestMaster1/AWBURST
add wave -noupdate -format Literal /tb/TestMaster1/AWLOCK
add wave -noupdate -format Literal /tb/TestMaster1/AWCACHE
add wave -noupdate -format Literal /tb/TestMaster1/AWPROT
add wave -noupdate -format Logic /tb/TestMaster1/AWVALID
add wave -noupdate -format Logic /tb/TestMaster1/AWREADY
add wave -noupdate -format Literal /tb/TestMaster1/WID
add wave -noupdate -format Literal /tb/TestMaster1/WDATA
add wave -noupdate -format Literal /tb/TestMaster1/WSTRB
add wave -noupdate -format Logic /tb/TestMaster1/WLAST
add wave -noupdate -format Logic /tb/TestMaster1/WVALID
add wave -noupdate -format Logic /tb/TestMaster1/WREADY
add wave -noupdate -format Literal /tb/TestMaster1/BID
add wave -noupdate -format Literal /tb/TestMaster1/BRESP
add wave -noupdate -format Logic /tb/TestMaster1/BVALID
add wave -noupdate -format Logic /tb/TestMaster1/BREADY
add wave -noupdate -format Literal /tb/TestMaster1/ARID
add wave -noupdate -format Literal /tb/TestMaster1/ARADDR
add wave -noupdate -format Literal /tb/TestMaster1/ARLEN
add wave -noupdate -format Literal /tb/TestMaster1/ARSIZE
add wave -noupdate -format Literal /tb/TestMaster1/ARBURST
add wave -noupdate -format Literal /tb/TestMaster1/ARLOCK
add wave -noupdate -format Literal /tb/TestMaster1/ARCACHE
add wave -noupdate -format Literal /tb/TestMaster1/ARPROT
add wave -noupdate -format Logic /tb/TestMaster1/ARVALID
add wave -noupdate -format Logic /tb/TestMaster1/ARREADY
add wave -noupdate -format Literal /tb/TestMaster1/RID
add wave -noupdate -format Literal /tb/TestMaster1/RDATA
add wave -noupdate -format Literal /tb/TestMaster1/RRESP
add wave -noupdate -format Logic /tb/TestMaster1/RLAST
add wave -noupdate -format Logic /tb/TestMaster1/RVALID
add wave -noupdate -format Logic /tb/TestMaster1/RREADY
add wave -noupdate -format Literal /tb/TestMaster1/AWQ_WINDEX
add wave -noupdate -format Literal /tb/TestMaster1/AWQ_RINDEX
add wave -noupdate -format Logic /tb/TestMaster1/AWQ_empty
add wave -noupdate -format Literal /tb/TestMaster1/WIDQ_WINDEX
add wave -noupdate -format Literal /tb/TestMaster1/WIDQ_RINDEX
add wave -noupdate -format Logic /tb/TestMaster1/WIDQ_full
add wave -noupdate -format Logic /tb/TestMaster1/WIDQ_empty
add wave -noupdate -format Literal /tb/TestMaster1/WDQ_RINDEX
add wave -noupdate -format Literal /tb/TestMaster1/WDQ_WINDEX
add wave -noupdate -format Logic /tb/TestMaster1/WDQ_empty
add wave -noupdate -format Literal /tb/TestMaster1/ARQ_WINDEX
add wave -noupdate -format Literal /tb/TestMaster1/ARQ_RINDEX
add wave -noupdate -format Logic /tb/TestMaster1/ARQ_empty
add wave -noupdate -format Literal /tb/TestMaster1/DecreaseWID
add wave -noupdate -format Logic /tb/TestMaster1/DecreaseWIDEnable
add wave -noupdate -format Literal /tb/TestMaster1/IncreaseWID
add wave -noupdate -format Logic /tb/TestMaster1/IncreaseWIDEnable
add wave -noupdate -format Literal /tb/TestMaster1/DecreaseRID
add wave -noupdate -format Logic /tb/TestMaster1/DecreaseRIDEnable
add wave -noupdate -format Literal /tb/TestMaster1/IncreaseRID
add wave -noupdate -format Logic /tb/TestMaster1/IncreaseRIDEnable
add wave -noupdate -format Literal /tb/TestMaster1/LOCK_ID
add wave -noupdate -format Literal /tb/TestMaster1/LOCK_ADDR
add wave -noupdate -format Literal /tb/TestMaster1/LOCK_BURSTLEN
add wave -noupdate -format Literal /tb/TestMaster1/LOCK_SLAVE
add wave -noupdate -format Logic /tb/TestMaster1/AW_idle
add wave -noupdate -format Logic /tb/TestMaster1/AW_RANDOM
add wave -noupdate -format Logic /tb/TestMaster1/WD_idle
add wave -noupdate -format Logic /tb/TestMaster1/WD_RANDOM
add wave -noupdate -format Logic /tb/TestMaster1/AR_idle
add wave -noupdate -format Logic /tb/TestMaster1/AR_RANDOM
add wave -noupdate -format Literal /tb/TestMaster1/i_rd
add wave -noupdate -format Literal /tb/TestMaster1/i_wid_temp
add wave -noupdate -format Literal /tb/TestMaster1/i_rid_temp
add wave -noupdate -format Logic /tb/TestMaster1/ResetIdleCnt
add wave -noupdate -format Literal /tb/TestMaster1/IdleCnt
add wave -noupdate -format Literal /tb/TestMaster1/situ
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic /tb/IntSRAMController1/ACLK
add wave -noupdate -format Logic /tb/IntSRAMController1/ARESETn
add wave -noupdate -format Literal /tb/IntSRAMController1/AWID
add wave -noupdate -format Literal /tb/IntSRAMController1/AWADDR
add wave -noupdate -format Literal /tb/IntSRAMController1/AWLEN
add wave -noupdate -format Literal /tb/IntSRAMController1/AWSIZE
add wave -noupdate -format Literal /tb/IntSRAMController1/AWBURST
add wave -noupdate -format Logic /tb/IntSRAMController1/AWVALID
add wave -noupdate -format Logic /tb/IntSRAMController1/AWREADY
add wave -noupdate -format Literal /tb/IntSRAMController1/WID
add wave -noupdate -format Literal /tb/IntSRAMController1/WDATA
add wave -noupdate -format Literal /tb/IntSRAMController1/WSTRB
add wave -noupdate -format Logic /tb/IntSRAMController1/WLAST
add wave -noupdate -format Logic /tb/IntSRAMController1/WVALID
add wave -noupdate -format Logic /tb/IntSRAMController1/WREADY
add wave -noupdate -format Literal /tb/IntSRAMController1/BID
add wave -noupdate -format Literal /tb/IntSRAMController1/BRESP
add wave -noupdate -format Logic /tb/IntSRAMController1/BVALID
add wave -noupdate -format Logic /tb/IntSRAMController1/BREADY
add wave -noupdate -format Literal /tb/IntSRAMController1/ARID
add wave -noupdate -format Literal /tb/IntSRAMController1/ARADDR
add wave -noupdate -format Literal /tb/IntSRAMController1/ARLEN
add wave -noupdate -format Literal /tb/IntSRAMController1/ARSIZE
add wave -noupdate -format Literal /tb/IntSRAMController1/ARBURST
add wave -noupdate -format Logic /tb/IntSRAMController1/ARVALID
add wave -noupdate -format Logic /tb/IntSRAMController1/ARREADY
add wave -noupdate -format Literal /tb/IntSRAMController1/RID
add wave -noupdate -format Literal /tb/IntSRAMController1/RDATA
add wave -noupdate -format Literal /tb/IntSRAMController1/RRESP
add wave -noupdate -format Logic /tb/IntSRAMController1/RLAST
add wave -noupdate -format Logic /tb/IntSRAMController1/RVALID
add wave -noupdate -format Logic /tb/IntSRAMController1/RREADY
add wave -noupdate -format Literal /tb/IntSRAMController1/MEMADDR
add wave -noupdate -format Logic /tb/IntSRAMController1/MEMCEn
add wave -noupdate -format Literal /tb/IntSRAMController1/MEMWEn
add wave -noupdate -format Literal /tb/IntSRAMController1/MEMRDATA
add wave -noupdate -format Literal /tb/IntSRAMController1/MEMWDATA
add wave -noupdate -format Logic /tb/IntSRAMController1/ReadOrWrite
add wave -noupdate -format Literal /tb/IntSRAMController1/State
add wave -noupdate -format Literal /tb/IntSRAMController1/NextState
add wave -noupdate -format Logic /tb/IntSRAMController1/StateIsIDLE
add wave -noupdate -format Logic /tb/IntSRAMController1/StateIsREAD
add wave -noupdate -format Logic /tb/IntSRAMController1/StateIsWRITE
add wave -noupdate -format Logic /tb/IntSRAMController1/StateIsWRITE_RESP
add wave -noupdate -format Logic /tb/IntSRAMController1/FirstREADCycle
add wave -noupdate -format Literal /tb/IntSRAMController1/MuxedAddr
add wave -noupdate -format Literal /tb/IntSRAMController1/MuxedLen
add wave -noupdate -format Literal /tb/IntSRAMController1/MuxedSize
add wave -noupdate -format Literal /tb/IntSRAMController1/MuxedBurst
add wave -noupdate -format Logic /tb/IntSRAMController1/LatchCommandEn
add wave -noupdate -format Literal /tb/IntSRAMController1/Id
add wave -noupdate -format Literal /tb/IntSRAMController1/Addr
add wave -noupdate -format Literal /tb/IntSRAMController1/Len
add wave -noupdate -format Literal /tb/IntSRAMController1/BurstLen
add wave -noupdate -format Literal /tb/IntSRAMController1/Size
add wave -noupdate -format Literal /tb/IntSRAMController1/Burst
add wave -noupdate -format Logic /tb/IntSRAMController1/DecreaseLen
add wave -noupdate -format Logic /tb/IntSRAMController1/NextAddrCalcEn
add wave -noupdate -format Literal /tb/IntSRAMController1/IncreasedAddr
add wave -noupdate -format Literal /tb/IntSRAMController1/PrevAddr
add wave -noupdate -format Literal /tb/IntSRAMController1/WrapBoundary
add wave -noupdate -format Literal /tb/IntSRAMController1/IncrSize
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/Lock2wrmi0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/Lock2wrmi1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/Lock2wrmi2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/Lock2wrmi3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/Lock2wrmi4
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/Lock2wrmi5
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/UnLock2wrmi0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/UnLock2wrmi1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/UnLock2wrmi2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/UnLock2wrmi3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/UnLock2wrmi4
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/UnLock2wrmi5
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/ARVALIDmi02s0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/ARVALIDmi12s1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/ARVALIDmi22s2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/ARVALIDmi32s3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/ARVALIDmi42s4
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/ARVALIDmi52s5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/LockPort2wrmi0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/LockPort2wrmi1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/LockPort2wrmi2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/LockPort2wrmi3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/LockPort2wrmi4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/LockPort2wrmi5
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/ReadIntEmptyWrmi02Rdmi0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/ReadIntEmptyWrmi12Rdmi1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/ReadIntEmptyWrmi22Rdmi2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/ReadIntEmptyWrmi32Rdmi3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/ReadIntEmptyWrmi42Rdmi4
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/ReadIntEmptyWrmi52Rdmi5
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/DataCntEmptyRdmi02Wrmi0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/DataCntEmptyRdmi12Wrmi1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/DataCntEmptyRdmi22Wrmi2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/DataCntEmptyRdmi32Wrmi3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/DataCntEmptyRdmi42Wrmi4
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/DataCntEmptyRdmi52Wrmi5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/CtlDataWrite2Lock0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/CtlDataWrite2Lock1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/CtlDataWrite2Lock2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/CtlDataWrite2Lock3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/CtlDataWrite2Lock4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/CtlDataWrite2Lock5
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/ACLK
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/ARESETn
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWIDm02si0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWADDRm02si0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLENm02si0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWSIZEm02si0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWBURSTm02si0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLOCKm02si0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWCACHEm02si0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWPROTm02si0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDm02si0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWREADYsi02m0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WIDm02si0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WDATAm02si0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WSTRBm02si0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WLASTm02si0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WVALIDm02si0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WREADYsi02m0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BIDsi02m0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BRESPsi02m0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BVALIDsi02m0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BREADYm02si0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWIDm12si1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWADDRm12si1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLENm12si1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWSIZEm12si1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWBURSTm12si1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLOCKm12si1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWCACHEm12si1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWPROTm12si1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDm12si1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWREADYsi12m1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WIDm12si1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WDATAm12si1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WSTRBm12si1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WLASTm12si1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WVALIDm12si1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WREADYsi12m1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BIDsi12m1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BRESPsi12m1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BVALIDsi12m1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BREADYm12si1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWIDm22si2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWADDRm22si2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLENm22si2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWSIZEm22si2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWBURSTm22si2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLOCKm22si2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWCACHEm22si2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWPROTm22si2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDm22si2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWREADYsi22m2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WIDm22si2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WDATAm22si2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WSTRBm22si2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WLASTm22si2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WVALIDm22si2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WREADYsi22m2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BIDsi22m2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BRESPsi22m2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BVALIDsi22m2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BREADYm22si2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWIDm32si3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWADDRm32si3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLENm32si3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWSIZEm32si3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWBURSTm32si3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLOCKm32si3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWCACHEm32si3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWPROTm32si3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDm32si3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWREADYsi32m3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WIDm32si3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WDATAm32si3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WSTRBm32si3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WLASTm32si3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WVALIDm32si3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WREADYsi32m3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BIDsi32m3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BRESPsi32m3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BVALIDsi32m3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BREADYm32si3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWIDmi02s0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWADDRmi02s0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLENmi02s0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWSIZEmi02s0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWBURSTmi02s0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLOCKmi02s0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWCACHEmi02s0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWPROTmi02s0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDmi02s0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWREADYs02mi0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WIDmi02s0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WDATAmi02s0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WSTRBmi02s0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WLASTmi02s0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WVALIDmi02s0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WREADYs02mi0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BIDs02mi0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BRESPs02mi0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BVALIDs02mi0
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BREADYmi02s0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWIDmi12s1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWADDRmi12s1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLENmi12s1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWSIZEmi12s1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWBURSTmi12s1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLOCKmi12s1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWCACHEmi12s1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWPROTmi12s1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDmi12s1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWREADYs12mi1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WIDmi12s1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WDATAmi12s1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WSTRBmi12s1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WLASTmi12s1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WVALIDmi12s1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WREADYs12mi1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BIDs12mi1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BRESPs12mi1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BVALIDs12mi1
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BREADYmi12s1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWIDmi22s2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWADDRmi22s2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLENmi22s2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWSIZEmi22s2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWBURSTmi22s2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLOCKmi22s2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWCACHEmi22s2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWPROTmi22s2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDmi22s2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWREADYs22mi2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WIDmi22s2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WDATAmi22s2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WSTRBmi22s2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WLASTmi22s2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WVALIDmi22s2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WREADYs22mi2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BIDs22mi2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BRESPs22mi2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BVALIDs22mi2
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BREADYmi22s2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWIDmi32s3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWADDRmi32s3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLENmi32s3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWSIZEmi32s3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWBURSTmi32s3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLOCKmi32s3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWCACHEmi32s3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWPROTmi32s3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDmi32s3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWREADYs32mi3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WIDmi32s3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WDATAmi32s3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WSTRBmi32s3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WLASTmi32s3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WVALIDmi32s3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WREADYs32mi3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BIDs32mi3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BRESPs32mi3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BVALIDs32mi3
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BREADYmi32s3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWIDmi42s4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWADDRmi42s4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLENmi42s4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWSIZEmi42s4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWBURSTmi42s4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLOCKmi42s4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWCACHEmi42s4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWPROTmi42s4
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDmi42s4
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWREADYs42mi4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WIDmi42s4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WDATAmi42s4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WSTRBmi42s4
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WLASTmi42s4
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WVALIDmi42s4
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WREADYs42mi4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BIDs42mi4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BRESPs42mi4
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BVALIDs42mi4
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BREADYmi42s4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWIDmi52s5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWADDRmi52s5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLENmi52s5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWSIZEmi52s5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWBURSTmi52s5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLOCKmi52s5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWCACHEmi52s5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWPROTmi52s5
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWVALIDmi52s5
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/AWREADYs52mi5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WIDmi52s5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WDATAmi52s5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WSTRBmi52s5
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WLASTmi52s5
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WVALIDmi52s5
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/WREADYs52mi5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BIDs52mi5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BRESPs52mi5
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BVALIDs52mi5
add wave -noupdate -format Logic /tb/SBUS/U0WriteChannel/BREADYmi52s5
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWIDsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWADDRsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLENsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWSIZEsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWBURSTsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLOCKsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWCACHEsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWPROTsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WIDsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WDATAsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WSTRBsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BIDmi02si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BRESPmi02si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BIDmi12si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BRESPmi12si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BIDmi22si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BRESPmi22si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BIDmi32si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BRESPmi32si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BIDmi42si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BRESPmi42si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BIDmi52si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BRESPmi52si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWREADYmi2si0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WLASTsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WVALIDsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WREADYmi2si0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BVALIDmi2si0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BREADYsi02mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWIDsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWADDRsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLENsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWSIZEsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWBURSTsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLOCKsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWCACHEsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWPROTsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WIDsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WDATAsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WSTRBsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWREADYmi2si1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WLASTsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WVALIDsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WREADYmi2si1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BVALIDmi2si1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BREADYsi12mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWIDsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWADDRsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLENsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWSIZEsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWBURSTsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLOCKsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWCACHEsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWPROTsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WIDsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WDATAsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WSTRBsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWREADYmi2si2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WLASTsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WVALIDsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WREADYmi2si2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BVALIDmi2si2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BREADYsi22mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWIDsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWADDRsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLENsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWSIZEsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWBURSTsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWLOCKsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWCACHEsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWPROTsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WIDsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WDATAsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WSTRBsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWREADYmi2si3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WLASTsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WVALIDsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WREADYmi2si3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BVALIDmi2si3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BREADYsi32mi
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWREADYmi02si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WREADYmi02si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWREADYmi12si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WREADYmi12si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWREADYmi22si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WREADYmi22si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWREADYmi32si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WREADYmi32si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWREADYmi42si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WREADYmi42si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWREADYmi52si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/WREADYmi52si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BVALIDmi02si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BVALIDmi12si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BVALIDmi22si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BVALIDmi32si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BVALIDmi42si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/BVALIDmi52si
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi2mi0
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi2mi1
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi2mi2
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi2mi3
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi2mi4
add wave -noupdate -format Literal /tb/SBUS/U0WriteChannel/AWVALIDsi2mi5
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {120195000 ps} 0}
configure wave -namecolwidth 149
configure wave -valuecolwidth 99
configure wave -justifyvalue right
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
update
WaveRestoreZoom {119844320 ps} {120525680 ps}
