library verilog;
use verilog.vl_types.all;
entity mmc_serdes is
    generic(
        ifield          : integer := 0;
        sfield          : integer := 1;
        tfield          : integer := 2;
        xfield          : integer := 3;
        afield          : integer := 4;
        cfield          : integer := 5;
        efield          : integer := 6;
        hfield          : integer := 7;
        rfield          : integer := 8;
        lfield          : integer := 9;
        dfield          : integer := 10;
        ufield          : integer := 11;
        bfield          : integer := 12;
        pfield          : integer := 13;
        gfield          : integer := 14
    );
    port(
        mresetn         : in     vl_logic;
        hstandby        : in     vl_logic;
        msreset         : in     vl_logic;
        mclk            : in     vl_logic;
        mcs             : in     vl_logic;
        mcmdin          : in     vl_logic;
        mcmdout_dly     : out    vl_logic;
        mcmdouten_dly   : out    vl_logic;
        mdatin          : in     vl_logic_vector(7 downto 0);
        mdatout_dly     : out    vl_logic_vector(7 downto 0);
        mdatouten_dly   : out    vl_logic;
        mext_csd        : in     vl_logic_vector(191 downto 0);
        msfr_out        : in     vl_logic_vector(7 downto 0);
        msfr_read       : in     vl_logic_vector(31 downto 0);
        hbuswidth_cmd   : in     vl_logic_vector(31 downto 0);
        cmd_index       : out    vl_logic_vector(5 downto 0);
        resp_lost_n     : out    vl_logic;
        \MRSTB\         : out    vl_logic;
        mwstb           : out    vl_logic;
        mdout           : out    vl_logic_vector(7 downto 0);
        mdin            : in     vl_logic_vector(7 downto 0);
        \MRDEN\         : in     vl_logic;
        mtmbw           : out    vl_logic;
        mcselect        : out    vl_logic;
        mcommand        : out    vl_logic_vector(47 downto 0);
        margument       : in     vl_logic_vector(127 downto 0);
        mdecode         : in     vl_logic_vector(11 downto 0);
        mcstate         : in     vl_logic_vector(4 downto 0);
        mcommand_ok     : in     vl_logic;
        mcommand_ok_dly : in     vl_logic;
        mstatus         : in     vl_logic_vector(31 downto 0);
        mspi_derr       : in     vl_logic;
        mspi_r          : in     vl_logic_vector(15 downto 0);
        mbsyend         : in     vl_logic;
        mnid            : in     vl_logic_vector(7 downto 0);
        mncrmmc         : in     vl_logic_vector(7 downto 0);
        mncrspi         : in     vl_logic_vector(7 downto 0);
        mrblen          : in     vl_logic_vector(11 downto 0);
        mwblen          : in     vl_logic_vector(11 downto 0);
        mbsybwcmd       : in     vl_logic;
        mwakeupen       : in     vl_logic;
        mcrc7_on_off    : in     vl_logic;
        mcrc16_on_off   : in     vl_logic;
        mcmdirqen       : in     vl_logic_vector(15 downto 0);
        mrespirqen      : in     vl_logic_vector(15 downto 0);
        mwrirqen        : in     vl_logic_vector(15 downto 0);
        mrdirqen        : in     vl_logic_vector(15 downto 0);
        mwrforce        : in     vl_logic;
        mrdforce        : in     vl_logic;
        no_response     : in     vl_logic;
        mrca_match      : in     vl_logic;
        mcstatewr       : out    vl_logic_vector(2 downto 0);
        mcstatewr_manu  : out    vl_logic;
        resp_cmd_error  : out    vl_logic;
        houtdly         : in     vl_logic_vector(5 downto 0);
        cmd_eoe         : out    vl_logic;
        resp_eoe        : out    vl_logic;
        resp_eoe_d      : out    vl_logic;
        resp_eor        : out    vl_logic;
        rd_eol          : out    vl_logic;
        cmd_field       : out    vl_logic_vector(3 downto 0);
        resp_field      : out    vl_logic_vector(3 downto 0);
        wr_field        : out    vl_logic_vector(3 downto 0);
        rd_field        : out    vl_logic_vector(3 downto 0);
        crc7_ok         : out    vl_logic;
        crc16_ok_capture: out    vl_logic;
        mocr_update     : out    vl_logic;
        mrca_update     : out    vl_logic;
        mrca_up_data    : out    vl_logic_vector(15 downto 0);
        cstnormal       : out    vl_logic_vector(4 downto 0);
        fifo_clear      : out    vl_logic;
        mwstb_4word     : out    vl_logic;
        mwstb_16word    : out    vl_logic;
        mwstb_128word   : out    vl_logic;
        wr_word_count   : out    vl_logic_vector(7 downto 0);
        wr_4word_count  : out    vl_logic_vector(7 downto 0);
        wr_16word_count : out    vl_logic_vector(7 downto 0);
        wr_128word_count: out    vl_logic_vector(7 downto 0);
        single_write_command: out    vl_logic;
        multi_write_command: out    vl_logic;
        single_read_command: out    vl_logic;
        multi_read_command: out    vl_logic;
        rd_eou          : out    vl_logic;
        mrden           : out    vl_logic;
        start_block     : out    vl_logic_vector(22 downto 0);
        multi_write_block: out    vl_logic_vector(31 downto 0);
        multi_read_block: out    vl_logic_vector(31 downto 0);
        mrstb_4word     : out    vl_logic;
        mrstb_16word    : out    vl_logic;
        mrstb_128word   : out    vl_logic;
        rd_word_count   : out    vl_logic_vector(7 downto 0);
        rd_4word_count  : out    vl_logic_vector(7 downto 0);
        rd_16word_count : out    vl_logic_vector(7 downto 0);
        rd_128word_count: out    vl_logic_vector(7 downto 0);
        mrstb           : out    vl_logic;
        mrstb_3d        : out    vl_logic;
        mrstb_4d        : out    vl_logic;
        cststop         : out    vl_logic_vector(4 downto 0);
        busy_clear      : out    vl_logic;
        wr_count        : out    vl_logic_vector(15 downto 0);
        \Access\        : out    vl_logic_vector(1 downto 0);
        index           : out    vl_logic_vector(7 downto 0);
        value           : out    vl_logic_vector(7 downto 0);
        wr_eol          : out    vl_logic;
        resp_eox        : out    vl_logic;
        mprot_up_data   : in     vl_logic_vector(31 downto 0);
        ismbw           : out    vl_logic;
        bus1            : out    vl_logic;
        bus4            : out    vl_logic;
        bus8            : out    vl_logic;
        mcmdirqwr       : out    vl_logic_vector(14 downto 0);
        mrespirqwr      : out    vl_logic_vector(14 downto 0);
        mwrirqwr        : out    vl_logic_vector(14 downto 0);
        mrdirqwr        : out    vl_logic_vector(14 downto 0);
        mwakeup         : out    vl_logic;
        mirq            : out    vl_logic_vector(3 downto 0);
        mprefix         : out    vl_logic_vector(7 downto 0);
        mresp_end       : out    vl_logic;
        mcid            : in     vl_logic_vector(127 downto 0);
        mcsd            : in     vl_logic_vector(127 downto 0);
        mocr            : in     vl_logic_vector(31 downto 0)
    );
end mmc_serdes;
