library verilog;
use verilog.vl_types.all;
entity testmaster is
    generic(
        data_width      : integer := 32;
        wid_width       : integer := 4;
        rid_width       : integer := 4;
        randomize       : integer := 1;
        wrap_support    : integer := 1;
        word_only       : integer := 0;
        halfword_byte_single_only: integer := 0;
        maximum_idle_cnt: integer := 100000;
        awq_width       : integer := 4;
        wdq_width       : integer := 8;
        arq_width       : integer := 4;
        rdq_width       : integer := 8;
        cnt_width       : integer := 32;
        unitdelay       : integer := 1;
        sram_addr       : integer := 0;
        peri0_control_addr: integer := 536870912;
        peri1_control_addr: integer := 536871424;
        peri2_control_addr: integer := 536871936;
        peri3_control_addr: integer := 536872448;
        peri4_control_addr: integer := 536872960;
        peri5_control_addr: integer := 536873472;
        peri6_control_addr: integer := 536873984;
        peri7_control_addr: integer := 536874496;
        peri0_fifo_addr : integer := 536870916;
        peri1_fifo_addr : integer := 536871428;
        peri2_fifo_addr : integer := 536871940;
        peri3_fifo_addr : integer := 536872452;
        peri4_fifo_addr : integer := 536872964;
        peri5_fifo_addr : integer := 536873476;
        peri6_fifo_addr : integer := 536873988;
        peri7_fifo_addr : integer := 536874500;
        dmac_addr       : integer := 536875008;
        dmacintstatus   : integer := 0;
        dmacinttcstatus : integer := 4;
        dmacinttcclear  : integer := 8;
        dmacinterrorstatus: integer := 12;
        dmacinterrorclear: integer := 16;
        dmacrawinttcstatus: integer := 20;
        dmacrawinterrorstatus: integer := 24;
        dmacenbldchns   : integer := 28;
        dmacsoftbreq    : integer := 32;
        dmacsoftsreq    : integer := 36;
        dmacsoftlbreq   : integer := 40;
        dmacsoftlsreq   : integer := 44;
        dmacconfiguration: integer := 48;
        dmacsync        : integer := 52;
        dmacc0base      : integer := 256;
        dmacc1base      : integer := 288;
        dmacc2base      : integer := 320;
        dmacc3base      : integer := 352;
        dmacc4base      : integer := 384;
        dmacc5base      : integer := 416;
        dmacc6base      : integer := 448;
        dmacc7base      : integer := 480;
        chsrcaddr       : integer := 0;
        chdestaddr      : integer := 4;
        chlli           : integer := 8;
        chcontrol       : integer := 12;
        chconfiguration : integer := 16;
        taddr_width     : integer := 12
    );
    port(
        aclk            : in     vl_logic;
        aresetn         : in     vl_logic;
        awid            : out    vl_logic_vector;
        awaddr          : out    vl_logic_vector(31 downto 0);
        awlen           : out    vl_logic_vector(3 downto 0);
        awsize          : out    vl_logic_vector(2 downto 0);
        awburst         : out    vl_logic_vector(1 downto 0);
        awlock          : out    vl_logic_vector(1 downto 0);
        awcache         : out    vl_logic_vector(3 downto 0);
        awprot          : out    vl_logic_vector(2 downto 0);
        awvalid         : out    vl_logic;
        awready         : in     vl_logic;
        wid             : out    vl_logic_vector;
        wdata           : out    vl_logic_vector;
        wstrb           : out    vl_logic_vector;
        wlast           : out    vl_logic;
        wvalid          : out    vl_logic;
        wready          : in     vl_logic;
        bid             : in     vl_logic_vector;
        bresp           : in     vl_logic_vector(1 downto 0);
        bvalid          : in     vl_logic;
        bready          : out    vl_logic;
        arid            : out    vl_logic_vector;
        araddr          : out    vl_logic_vector(31 downto 0);
        arlen           : out    vl_logic_vector(3 downto 0);
        arsize          : out    vl_logic_vector(2 downto 0);
        arburst         : out    vl_logic_vector(1 downto 0);
        arlock          : out    vl_logic_vector(1 downto 0);
        arcache         : out    vl_logic_vector(3 downto 0);
        arprot          : out    vl_logic_vector(2 downto 0);
        arvalid         : out    vl_logic;
        arready         : in     vl_logic;
        rid             : in     vl_logic_vector;
        rdata           : in     vl_logic_vector;
        rresp           : in     vl_logic_vector(1 downto 0);
        rlast           : in     vl_logic;
        rvalid          : in     vl_logic;
        rready          : out    vl_logic
    );
end testmaster;
