#-------------------------------------------------------------------------------
#-  This confidential and proprietary software may be used only as
#-  authorised by a licensing agreement from ARM Limited
#-    (C) COPYRIGHT 1998-2000 ARM Limited
#-        ALL RIGHTS RESERVED
#-  The entire notice above must be reproduced on all authorised
#-  copies and copies may only be made to the extent permitted
#-  by a licensing agreement from ARM Limited.
#-------------------------------------------------------------------------------
#-
#-  Version and Release Control Information:
#-
#-  File Name              : makefile.rca
#-  File Revision          : 1.6
#-
#-  Release Information    : PrimeCell(TM)-PL011-REL1v3
#-
#-------------------------------------------------------------------------------
 
#-------------------------------------------------------------------------------
#-  Purpose : A makefile for the Gpio trickbox files. 
#-
#-------------------------------------------------------------------------------

MODULES = \
	 UartTrTXFCntl.vhd \
	 UartTrTXRegFile.vhd \
	 UartTrTXFIFO.vhd \
	 UartTrIrdaRX.vhd \
	 UartTrIrdaTX.vhd \
	 UartTrRXFCntl.vhd \
	 UartTrRXRegFile.vhd \
	 UartTrRXFIFO.vhd \
	 UartTrRX.vhd \
	 UartTrTX.vhd \
	 UartTrBaud.vhd \
	 UartTrClk.vhd \
	 UartTrRegBlock.vhd \
	 UartTrApbif.vhd \
	 UartTrDMA.vhd \
         UartTrick.vhd

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

############################## End of file #####################################
