#####################################################

#  Created by Design Compiler write_sdc on Fri Feb  9 10:31:00 2007

#####################################################
set sdc_version 1.4

create_clock -period 10 -waveform {0 5} [get_ports {M_PCLK}]
create_clock -period 20 -waveform {0 10} [get_ports {R_PCLK}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[0]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[0]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[1]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[1]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[2]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[2]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[3]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[3]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[4]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[4]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[5]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[5]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[6]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[6]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[7]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[7]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[8]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[8]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[9]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[9]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[10]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[10]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[11]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[11]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[12]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[12]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[13]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[13]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[14]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[14]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[15]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[15]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[16]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[16]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[17]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[17]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[18]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[18]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[19]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[19]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[20]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[20]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[21]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[21]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[22]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[22]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[23]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[23]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[24]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[24]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[25]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[25]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[26]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[26]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[27]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[27]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[28]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[28]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[29]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[29]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[30]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[30]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWDATA[31]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWDATA[31]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PADDR[0]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PADDR[0]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PADDR[1]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PADDR[1]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PADDR[2]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PADDR[2]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PADDR[3]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PADDR[3]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PADDR[4]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PADDR[4]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PADDR[5]}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PADDR[5]}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PWRITE}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PWRITE}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PENABLE}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PENABLE}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PSEL}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PSEL}]
set_input_delay 12 -max -clock "R_PCLK" [get_ports {R_PCLK}]
set_input_delay 0 -min -clock "R_PCLK" [get_ports {R_PCLK}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[0]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[0]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[1]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[1]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[2]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[2]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[3]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[3]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[4]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[4]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[5]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[5]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[6]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[6]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[7]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[7]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[8]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[8]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[9]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[9]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[10]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[10]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[11]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[11]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[12]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[12]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[13]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[13]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[14]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[14]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[15]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[15]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[16]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[16]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[17]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[17]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[18]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[18]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[19]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[19]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[20]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[20]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[21]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[21]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[22]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[22]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[23]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[23]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[24]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[24]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[25]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[25]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[26]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[26]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[27]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[27]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[28]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[28]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[29]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[29]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[30]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[30]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWDATA[31]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWDATA[31]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[0]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[0]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[1]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[1]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[2]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[2]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[3]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[3]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[4]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[4]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[5]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[5]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[6]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[6]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[7]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[7]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[8]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[8]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[9]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[9]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[10]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[10]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[11]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[11]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[12]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[12]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[13]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[13]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[14]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[14]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[15]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[15]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[16]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[16]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[17]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[17]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[18]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[18]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[19]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[19]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[20]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[20]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PADDR[21]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PADDR[21]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWRITE}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWRITE}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWSTRB[0]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWSTRB[0]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWSTRB[1]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWSTRB[1]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWSTRB[2]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWSTRB[2]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PWSTRB[3]}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PWSTRB[3]}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PENABLE}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PENABLE}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PSEL}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PSEL}]
set_input_delay 5 -max -rise -clock "M_PCLK" [get_ports {PRESETn}]
set_input_delay 0.5 -min -rise -clock "M_PCLK" [get_ports {PRESETn}]
set_input_delay 7 -max -clock "M_PCLK" [get_ports {M_PCLK}]
set_input_delay 0 -min -clock "M_PCLK" [get_ports {M_PCLK}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[0]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[0]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[1]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[1]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[2]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[2]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[3]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[3]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[4]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[4]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[5]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[5]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[6]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[6]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[7]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[7]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[8]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[8]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[9]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[9]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[10]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[10]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[11]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[11]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[12]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[12]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[13]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[13]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[14]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[14]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[15]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[15]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[16]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[16]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[17]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[17]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[18]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[18]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[19]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[19]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[20]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[20]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[21]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[21]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[22]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[22]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[23]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[23]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[24]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[24]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[25]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[25]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[26]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[26]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[27]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[27]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[28]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[28]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[29]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[29]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[30]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[30]}]
set_output_delay 16 -max -clock "R_PCLK" [get_ports {R_PRDATA[31]}]
set_output_delay -0 -min -clock "R_PCLK" [get_ports {R_PRDATA[31]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[0]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[0]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[1]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[1]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[2]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[2]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[3]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[3]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[4]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[4]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[5]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[5]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[6]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[6]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[7]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[7]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[8]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[8]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[9]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[9]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[10]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[10]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[11]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[11]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[12]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[12]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[13]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[13]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[14]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[14]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[15]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[15]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[16]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[16]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[17]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[17]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[18]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[18]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[19]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[19]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[20]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[20]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[21]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[21]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[22]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[22]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[23]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[23]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[24]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[24]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[25]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[25]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[26]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[26]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[27]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[27]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[28]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[28]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[29]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[29]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[30]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[30]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PRDATA[31]}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PRDATA[31]}]
set_output_delay 3 -max -clock "M_PCLK" [get_ports {M_PREADY}]
set_output_delay 0 -min -clock "M_PCLK" [get_ports {M_PREADY}]
set_clock_transition -rise 0 [get_clocks {M_PCLK}]
set_clock_transition -fall 0 [get_clocks {M_PCLK}]
set_clock_transition -rise 0 [get_clocks {R_PCLK}]
set_clock_transition -fall 0 [get_clocks {R_PCLK}]
set_clock_uncertainty  0.8 -setup [get_ports {M_PCLK}]
set_clock_uncertainty  0.8 -setup [get_ports {R_PCLK}]
set_max_transition 2 [current_design]
set_input_transition -max 1 [get_ports {M_PCLK}]
set_load -pin_load 0 [get_ports {M_PCLK}]
set_input_transition -max 1 [get_ports {PRESETn}]
set_load -pin_load 0 [get_ports {PRESETn}]
set_disable_timing [get_ports {PRESETn}]
set_input_transition -max 1 [get_ports {M_PSEL}]
set_input_transition -max 1 [get_ports {M_PENABLE}]
set_load -pin_load 0.018316 [get_ports {M_PREADY}]
set_load -min -pin_load 0.018316 [get_ports {M_PREADY}]
set_input_transition -max 1 [get_ports {M_PWSTRB[3]}]
set_input_transition -max 1 [get_ports {M_PWSTRB[2]}]
set_input_transition -max 1 [get_ports {M_PWSTRB[1]}]
set_input_transition -max 1 [get_ports {M_PWSTRB[0]}]
set_input_transition -max 1 [get_ports {M_PWRITE}]
set_input_transition -max 1 [get_ports {M_PADDR[21]}]
set_input_transition -max 1 [get_ports {M_PADDR[20]}]
set_input_transition -max 1 [get_ports {M_PADDR[19]}]
set_input_transition -max 1 [get_ports {M_PADDR[18]}]
set_input_transition -max 1 [get_ports {M_PADDR[17]}]
set_input_transition -max 1 [get_ports {M_PADDR[16]}]
set_input_transition -max 1 [get_ports {M_PADDR[15]}]
set_input_transition -max 1 [get_ports {M_PADDR[14]}]
set_input_transition -max 1 [get_ports {M_PADDR[13]}]
set_input_transition -max 1 [get_ports {M_PADDR[12]}]
set_input_transition -max 1 [get_ports {M_PADDR[11]}]
set_input_transition -max 1 [get_ports {M_PADDR[10]}]
set_input_transition -max 1 [get_ports {M_PADDR[9]}]
set_input_transition -max 1 [get_ports {M_PADDR[8]}]
set_input_transition -max 1 [get_ports {M_PADDR[7]}]
set_input_transition -max 1 [get_ports {M_PADDR[6]}]
set_input_transition -max 1 [get_ports {M_PADDR[5]}]
set_input_transition -max 1 [get_ports {M_PADDR[4]}]
set_input_transition -max 1 [get_ports {M_PADDR[3]}]
set_input_transition -max 1 [get_ports {M_PADDR[2]}]
set_input_transition -max 1 [get_ports {M_PADDR[1]}]
set_input_transition -max 1 [get_ports {M_PADDR[0]}]
set_input_transition -max 1 [get_ports {M_PWDATA[31]}]
set_input_transition -max 1 [get_ports {M_PWDATA[30]}]
set_input_transition -max 1 [get_ports {M_PWDATA[29]}]
set_input_transition -max 1 [get_ports {M_PWDATA[28]}]
set_input_transition -max 1 [get_ports {M_PWDATA[27]}]
set_input_transition -max 1 [get_ports {M_PWDATA[26]}]
set_input_transition -max 1 [get_ports {M_PWDATA[25]}]
set_input_transition -max 1 [get_ports {M_PWDATA[24]}]
set_input_transition -max 1 [get_ports {M_PWDATA[23]}]
set_input_transition -max 1 [get_ports {M_PWDATA[22]}]
set_input_transition -max 1 [get_ports {M_PWDATA[21]}]
set_input_transition -max 1 [get_ports {M_PWDATA[20]}]
set_input_transition -max 1 [get_ports {M_PWDATA[19]}]
set_input_transition -max 1 [get_ports {M_PWDATA[18]}]
set_input_transition -max 1 [get_ports {M_PWDATA[17]}]
set_input_transition -max 1 [get_ports {M_PWDATA[16]}]
set_input_transition -max 1 [get_ports {M_PWDATA[15]}]
set_input_transition -max 1 [get_ports {M_PWDATA[14]}]
set_input_transition -max 1 [get_ports {M_PWDATA[13]}]
set_input_transition -max 1 [get_ports {M_PWDATA[12]}]
set_input_transition -max 1 [get_ports {M_PWDATA[11]}]
set_input_transition -max 1 [get_ports {M_PWDATA[10]}]
set_input_transition -max 1 [get_ports {M_PWDATA[9]}]
set_input_transition -max 1 [get_ports {M_PWDATA[8]}]
set_input_transition -max 1 [get_ports {M_PWDATA[7]}]
set_input_transition -max 1 [get_ports {M_PWDATA[6]}]
set_input_transition -max 1 [get_ports {M_PWDATA[5]}]
set_input_transition -max 1 [get_ports {M_PWDATA[4]}]
set_input_transition -max 1 [get_ports {M_PWDATA[3]}]
set_input_transition -max 1 [get_ports {M_PWDATA[2]}]
set_input_transition -max 1 [get_ports {M_PWDATA[1]}]
set_input_transition -max 1 [get_ports {M_PWDATA[0]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[31]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[31]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[30]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[30]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[29]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[29]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[28]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[28]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[27]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[27]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[26]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[26]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[25]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[25]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[24]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[24]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[23]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[23]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[22]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[22]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[21]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[21]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[20]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[20]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[19]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[19]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[18]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[18]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[17]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[17]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[16]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[16]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[15]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[15]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[14]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[14]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[13]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[13]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[12]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[12]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[11]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[11]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[10]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[10]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[9]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[9]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[8]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[8]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[7]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[7]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[6]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[6]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[5]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[5]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[4]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[4]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[3]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[3]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[2]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[2]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[1]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[1]}]
set_load -pin_load 0.018316 [get_ports {M_PRDATA[0]}]
set_load -min -pin_load 0.018316 [get_ports {M_PRDATA[0]}]
set_input_transition -max 1 [get_ports {R_PCLK}]
set_load -pin_load 0 [get_ports {R_PCLK}]
set_input_transition -max 1 [get_ports {R_PSEL}]
set_input_transition -max 1 [get_ports {R_PENABLE}]
set_input_transition -max 1 [get_ports {R_PWRITE}]
set_input_transition -max 1 [get_ports {R_PADDR[5]}]
set_input_transition -max 1 [get_ports {R_PADDR[4]}]
set_input_transition -max 1 [get_ports {R_PADDR[3]}]
set_input_transition -max 1 [get_ports {R_PADDR[2]}]
set_input_transition -max 1 [get_ports {R_PADDR[1]}]
set_input_transition -max 1 [get_ports {R_PADDR[0]}]
set_input_transition -max 1 [get_ports {R_PWDATA[31]}]
set_input_transition -max 1 [get_ports {R_PWDATA[30]}]
set_input_transition -max 1 [get_ports {R_PWDATA[29]}]
set_input_transition -max 1 [get_ports {R_PWDATA[28]}]
set_input_transition -max 1 [get_ports {R_PWDATA[27]}]
set_input_transition -max 1 [get_ports {R_PWDATA[26]}]
set_input_transition -max 1 [get_ports {R_PWDATA[25]}]
set_input_transition -max 1 [get_ports {R_PWDATA[24]}]
set_input_transition -max 1 [get_ports {R_PWDATA[23]}]
set_input_transition -max 1 [get_ports {R_PWDATA[22]}]
set_input_transition -max 1 [get_ports {R_PWDATA[21]}]
set_input_transition -max 1 [get_ports {R_PWDATA[20]}]
set_input_transition -max 1 [get_ports {R_PWDATA[19]}]
set_input_transition -max 1 [get_ports {R_PWDATA[18]}]
set_input_transition -max 1 [get_ports {R_PWDATA[17]}]
set_input_transition -max 1 [get_ports {R_PWDATA[16]}]
set_input_transition -max 1 [get_ports {R_PWDATA[15]}]
set_input_transition -max 1 [get_ports {R_PWDATA[14]}]
set_input_transition -max 1 [get_ports {R_PWDATA[13]}]
set_input_transition -max 1 [get_ports {R_PWDATA[12]}]
set_input_transition -max 1 [get_ports {R_PWDATA[11]}]
set_input_transition -max 1 [get_ports {R_PWDATA[10]}]
set_input_transition -max 1 [get_ports {R_PWDATA[9]}]
set_input_transition -max 1 [get_ports {R_PWDATA[8]}]
set_input_transition -max 1 [get_ports {R_PWDATA[7]}]
set_input_transition -max 1 [get_ports {R_PWDATA[6]}]
set_input_transition -max 1 [get_ports {R_PWDATA[5]}]
set_input_transition -max 1 [get_ports {R_PWDATA[4]}]
set_input_transition -max 1 [get_ports {R_PWDATA[3]}]
set_input_transition -max 1 [get_ports {R_PWDATA[2]}]
set_input_transition -max 1 [get_ports {R_PWDATA[1]}]
set_input_transition -max 1 [get_ports {R_PWDATA[0]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[31]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[31]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[30]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[30]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[29]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[29]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[28]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[28]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[27]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[27]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[26]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[26]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[25]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[25]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[24]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[24]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[23]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[23]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[22]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[22]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[21]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[21]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[20]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[20]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[19]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[19]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[18]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[18]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[17]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[17]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[16]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[16]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[15]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[15]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[14]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[14]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[13]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[13]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[12]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[12]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[11]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[11]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[10]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[10]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[9]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[9]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[8]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[8]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[7]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[7]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[6]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[6]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[5]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[5]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[4]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[4]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[3]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[3]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[2]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[2]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[1]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[1]}]
set_load -pin_load 0.018316 [get_ports {R_PRDATA[0]}]
set_load -min -pin_load 0.018316 [get_ports {R_PRDATA[0]}]
set_load -pin_load 0.018316 [get_ports {CSb}]
set_load -min -pin_load 0.018316 [get_ports {CSb}]
set_load -pin_load 0.018316 [get_ports {ZZb}]
set_load -min -pin_load 0.018316 [get_ports {ZZb}]
set_load -pin_load 0.018316 [get_ports {OEb}]
set_load -min -pin_load 0.018316 [get_ports {OEb}]
set_load -pin_load 0.018316 [get_ports {WEb}]
set_load -min -pin_load 0.018316 [get_ports {WEb}]
set_load -pin_load 0.018316 [get_ports {UBb}]
set_load -min -pin_load 0.018316 [get_ports {UBb}]
set_load -pin_load 0.018316 [get_ports {LBb}]
set_load -min -pin_load 0.018316 [get_ports {LBb}]
set_load -pin_load 0.018316 [get_ports {ADDR[21]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[21]}]
set_load -pin_load 0.018316 [get_ports {ADDR[20]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[20]}]
set_load -pin_load 0.018316 [get_ports {ADDR[19]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[19]}]
set_load -pin_load 0.018316 [get_ports {ADDR[18]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[18]}]
set_load -pin_load 0.018316 [get_ports {ADDR[17]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[17]}]
set_load -pin_load 0.018316 [get_ports {ADDR[16]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[16]}]
set_load -pin_load 0.018316 [get_ports {ADDR[15]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[15]}]
set_load -pin_load 0.018316 [get_ports {ADDR[14]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[14]}]
set_load -pin_load 0.018316 [get_ports {ADDR[13]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[13]}]
set_load -pin_load 0.018316 [get_ports {ADDR[12]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[12]}]
set_load -pin_load 0.018316 [get_ports {ADDR[11]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[11]}]
set_load -pin_load 0.018316 [get_ports {ADDR[10]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[10]}]
set_load -pin_load 0.018316 [get_ports {ADDR[9]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[9]}]
set_load -pin_load 0.018316 [get_ports {ADDR[8]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[8]}]
set_load -pin_load 0.018316 [get_ports {ADDR[7]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[7]}]
set_load -pin_load 0.018316 [get_ports {ADDR[6]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[6]}]
set_load -pin_load 0.018316 [get_ports {ADDR[5]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[5]}]
set_load -pin_load 0.018316 [get_ports {ADDR[4]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[4]}]
set_load -pin_load 0.018316 [get_ports {ADDR[3]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[3]}]
set_load -pin_load 0.018316 [get_ports {ADDR[2]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[2]}]
set_load -pin_load 0.018316 [get_ports {ADDR[1]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[1]}]
set_load -pin_load 0.018316 [get_ports {ADDR[0]}]
set_load -min -pin_load 0.018316 [get_ports {ADDR[0]}]
set_input_transition -max 1 [get_ports {DATAIN[15]}]
set_input_transition -max 1 [get_ports {DATAIN[14]}]
set_input_transition -max 1 [get_ports {DATAIN[13]}]
set_input_transition -max 1 [get_ports {DATAIN[12]}]
set_input_transition -max 1 [get_ports {DATAIN[11]}]
set_input_transition -max 1 [get_ports {DATAIN[10]}]
set_input_transition -max 1 [get_ports {DATAIN[9]}]
set_input_transition -max 1 [get_ports {DATAIN[8]}]
set_input_transition -max 1 [get_ports {DATAIN[7]}]
set_input_transition -max 1 [get_ports {DATAIN[6]}]
set_input_transition -max 1 [get_ports {DATAIN[5]}]
set_input_transition -max 1 [get_ports {DATAIN[4]}]
set_input_transition -max 1 [get_ports {DATAIN[3]}]
set_input_transition -max 1 [get_ports {DATAIN[2]}]
set_input_transition -max 1 [get_ports {DATAIN[1]}]
set_input_transition -max 1 [get_ports {DATAIN[0]}]
set_load -pin_load 0.018316 [get_ports {nDATAEN}]
set_load -min -pin_load 0.018316 [get_ports {nDATAEN}]
set_load -pin_load 0.018316 [get_ports {DATAOUT[15]}]
set_load -min -pin_load 0.018316 [get_ports {DATAOUT[15]}]
set_load -pin_load 0.018316 [get_ports {DATAOUT[14]}]
set_load -min -pin_load 0.018316 [get_ports {DATAOUT[14]}]
set_load -pin_load 0.018316 [get_ports {DATAOUT[13]}]
set_load -min -pin_load 0.018316 [get_ports {DATAOUT[13]}]
set_load -pin_load 0.018316 [get_ports {DATAOUT[12]}]
set_load -min -pin_load 0.018316 [get_ports {DATAOUT[12]}]
set_load -pin_load 0.018316 [get_ports {DATAOUT[11]}]
set_load -min -pin_load 0.018316 [get_ports {DATAOUT[11]}]
set_load -pin_load 0.018316 [get_ports {DATAOUT[10]}]
set_load -min -pin_load 0.018316 [get_ports {DATAOUT[10]}]
set_load -pin_load 0.018316 [get_ports {DATAOUT[9]}]
set_load -min -pin_load 0.018316 [get_ports {DATAOUT[9]}]
set_load -pin_load 0.018316 [get_ports {DATAOUT[8]}]
set_load -min -pin_load 0.018316 [get_ports {DATAOUT[8]}]
set_load -pin_load 0.018316 [get_ports {DATAOUT[7]}]
set_load -min -pin_load 0.018316 [get_ports {DATAOUT[7]}]
set_load -pin_load 0.018316 [get_ports {DATAOUT[6]}]
set_load -min -pin_load 0.018316 [get_ports {DATAOUT[6]}]
set_load -pin_load 0.018316 [get_ports {DATAOUT[5]}]
set_load -min -pin_load 0.018316 [get_ports {DATAOUT[5]}]
set_load -pin_load 0.018316 [get_ports {DATAOUT[4]}]
set_load -min -pin_load 0.018316 [get_ports {DATAOUT[4]}]
set_load -pin_load 0.018316 [get_ports {DATAOUT[3]}]
set_load -min -pin_load 0.018316 [get_ports {DATAOUT[3]}]
set_load -pin_load 0.018316 [get_ports {DATAOUT[2]}]
set_load -min -pin_load 0.018316 [get_ports {DATAOUT[2]}]
set_load -pin_load 0.018316 [get_ports {DATAOUT[1]}]
set_load -min -pin_load 0.018316 [get_ports {DATAOUT[1]}]
set_load -pin_load 0.018316 [get_ports {DATAOUT[0]}]
set_load -min -pin_load 0.018316 [get_ports {DATAOUT[0]}]
set_resistance 0 [get_nets {R_PCLK}]
set_resistance 0 [get_nets {PRESETn}]
set_resistance 0 [get_nets {M_PCLK}]
