library verilog;
use verilog.vl_types.all;
entity writechannelsi_rs is
    generic(
        bus_wid         : integer := 32;
        addr_wid        : integer := 32;
        id_wid          : integer := 4;
        awlen_wid       : integer := 4;
        awsize_wid      : integer := 3;
        awburst_wid     : integer := 2;
        awlock_wid      : integer := 2;
        awcache_wid     : integer := 4;
        awprot_wid      : integer := 3;
        wstrb_wid       : integer := 4;
        bresp_wid       : integer := 2;
        rresp_wid       : integer := 2;
        arlen_wid       : integer := 4;
        arsize_wid      : integer := 3;
        arburst_wid     : integer := 2;
        arlock_wid      : integer := 2;
        arcache_wid     : integer := 4;
        arprot_wid      : integer := 3;
        master_wid      : integer := 4;
        slave_wid       : integer := 3;
        slave_num       : integer := 6;
        master_num      : integer := 4;
        slavecntwid     : integer := 5;
        reqdepth_wid    : integer := 2
    );
    port(
        aclk            : in     vl_logic;
        aresetn         : in     vl_logic;
        awidm2si        : in     vl_logic_vector;
        awaddrm2si      : in     vl_logic_vector;
        awlenm2si       : in     vl_logic_vector;
        awsizem2si      : in     vl_logic_vector;
        awburstm2si     : in     vl_logic_vector;
        awlockm2si      : in     vl_logic_vector;
        awcachem2si     : in     vl_logic_vector;
        awprotm2si      : in     vl_logic_vector;
        awvalidm2si     : in     vl_logic;
        awreadysi2m     : out    vl_logic;
        widm2si         : in     vl_logic_vector;
        wdatam2si       : in     vl_logic_vector;
        wstrbm2si       : in     vl_logic_vector;
        wlastm2si       : in     vl_logic;
        wvalidm2si      : in     vl_logic;
        wreadysi2m      : out    vl_logic;
        bidsi2m         : out    vl_logic_vector;
        brespsi2m       : out    vl_logic_vector;
        bvalidsi2m      : out    vl_logic;
        breadym2si      : in     vl_logic;
        awidsi2mi       : out    vl_logic_vector;
        awaddrsi2mi     : out    vl_logic_vector;
        awlensi2mi      : out    vl_logic_vector;
        awsizesi2mi     : out    vl_logic_vector;
        awburstsi2mi    : out    vl_logic_vector;
        awlocksi2mi     : out    vl_logic_vector;
        awcachesi2mi    : out    vl_logic_vector;
        awprotsi2mi     : out    vl_logic_vector;
        awvalidsi2mi    : out    vl_logic_vector;
        awreadymi2si    : in     vl_logic_vector;
        widsi2mi        : out    vl_logic_vector;
        wdatasi2mi      : out    vl_logic_vector;
        wstrbsi2mi      : out    vl_logic_vector;
        wlastsi2mi      : out    vl_logic_vector;
        wvalidsi2mi     : out    vl_logic_vector;
        wreadymi2si     : in     vl_logic_vector;
        bidmi02si       : in     vl_logic_vector;
        brespmi02si     : in     vl_logic_vector;
        bidmi12si       : in     vl_logic_vector;
        brespmi12si     : in     vl_logic_vector;
        bidmi22si       : in     vl_logic_vector;
        brespmi22si     : in     vl_logic_vector;
        bidmi32si       : in     vl_logic_vector;
        brespmi32si     : in     vl_logic_vector;
        bidmi42si       : in     vl_logic_vector;
        brespmi42si     : in     vl_logic_vector;
        bidmi52si       : in     vl_logic_vector;
        brespmi52si     : in     vl_logic_vector;
        bvalidmi2si     : in     vl_logic_vector;
        breadysi2mi     : out    vl_logic_vector
    );
end writechannelsi_rs;
