#-------------------------------------------------------------------------------
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from ARM Limited
#   (C) COPYRIGHT 2001 ARM Limited
#       ALL RIGHTS RESERVED
# The entire notice above must be reproduced on all authorised
# copies and copies may only be made to the extent permitted
# by a licensing agreement from ARM Limited.
#-------------------------------------------------------------------------------
# 
# Version and Release Control Information:
# 
# File Name              : makefile.rca
# File Revision          : 1.7
# 
# Release Information    : PrimeCell(TM)-PL031-REL1v0
# 
#-------------------------------------------------------------------------------
#-  Purpose  :
#-             Verilog Library Makefile
#-
#- --=========================================================================--

all: 
	@cp -f $(GLOBAL)/bustalk_apb/verilog/buswatcher/*.v .

clean:  
	@rm -rf *.v


############################## End of file #####################################
