vlib work
vlog ../src/ahdlprim.v
vlog ../src/eu_dpramx1.v
vlog ../src/eu_dpramx2.v
vlog ../src/BUF.v
vlog ../src/ab_masb.v
vlog ../src/ab_slvb.v
vlog ../src/mbackpci.v
vlog ../src/pciif.v
vlog ../src/tbackpci.v
vlog ../src/pciarb.v
vlog ../src/ep454g6.v
vlog ../src/top454.v
vlog pcimodel.v
vlog monitor_pci.v
vlog ahb_arb.v
vlog boundchk.v
vlog monitor_bus.v
vlog ab_mas_m.v
vlog std_tback.v
vlog std_mback.v
vlog pcimdevice.v
vlog pcitdevice.v
vlog ahbmdevice.v
vlog ahbslave.v
vlog tb454.v
