library verilog;
use verilog.vl_types.all;
entity SDRRas is
    generic(
        AW              : integer := 24;
        DW              : integer := 31;
        BW              : integer := 3;
        BL              : integer := 1;
        ID              : integer := 3;
        BBL             : integer := 3;
        WQCD            : integer := 4;
        WQD             : integer := 31;
        RQCD            : integer := 4;
        RQD             : integer := 31;
        WBLQCD          : integer := 2;
        WBLQD           : integer := 7;
        RBLQCD          : integer := 2;
        RBLQD           : integer := 7;
        ARBLQCD         : integer := 2;
        ARBLQD          : integer := 7;
        MDW             : integer := 15;
        DMW             : integer := 1;
        BAW             : integer := 1;
        RAW             : integer := 12;
        CAW             : integer := 10;
        RWW             : integer := 1;
        CD              : integer := 4;
        erc_powerup     : integer := 1;
        erc_epc         : integer := 2;
        erc_ar          : integer := 4;
        erc_mrs         : integer := 8;
        erc_idle        : integer := 16;
        erc_normal      : integer := 32;
        bc_null         : integer := 0;
        bc_mcas         : integer := 1;
        bc_mras         : integer := 2;
        bc_pc           : integer := 4;
        bc_sras         : integer := 8;
        bc_scas         : integer := 16;
        bc_epc          : integer := 32;
        ebc_null        : integer := 0;
        ebc_mcas        : integer := 1;
        ebc_mras        : integer := 2;
        ebc_pc          : integer := 4;
        ebc_sras        : integer := 8;
        ebc_scas        : integer := 16;
        ebc_epc         : integer := 32;
        ebc_bstop       : integer := 64
    );
    port(
        ARESETB         : in     vl_logic;
        ACLK            : in     vl_logic;
        BA_BA           : in     vl_logic_vector;
        BA_RA           : in     vl_logic_vector;
        BA_TT           : in     vl_logic_vector;
        BA_REQ          : in     vl_logic;
        CMD             : in     vl_logic_vector(5 downto 0);
        CLOSING         : in     vl_logic;
        B0_LAST_RA      : out    vl_logic_vector;
        B1_LAST_RA      : out    vl_logic_vector;
        B2_LAST_RA      : out    vl_logic_vector;
        B3_LAST_RA      : out    vl_logic_vector;
        RAS_0_BA        : out    vl_logic_vector;
        RAS_0_RA        : out    vl_logic_vector;
        RAS_0_TT        : out    vl_logic_vector;
        RAS_EMPTY       : out    vl_logic;
        RAS_HEMPTY      : out    vl_logic;
        RAS_FULL        : out    vl_logic
    );
end SDRRas;
