#-------------------------------------------------------------------------------
#-  This confidential and proprietary software may be used only as
#-  authorised by a licensing agreement from ARM Limited
#-    (C) COPYRIGHT 1998 ARM Limited
#-        ALL RIGHTS RESERVED
#-  The entire notice above must be reproduced on all authorised
#-  copies and copies may only be made to the extent permitted
#-  by a licensing agreement from ARM Limited.
#-------------------------------------------------------------------------------
#-
#-  Version and Release Control Information:
#-
#-  File Name              : makefile.rca
#-  File Revision          : 1.1
#-
#-  Release Information    : PrimeCell(TM)-PL022-REL1v2
#-
#-------------------------------------------------------------------------------
 
#-------------------------------------------------------------------------------
#-  Purpose  : Standard Verilog Library Makefile
#-------------------------------------------------------------------------------

MODULES = SspDefs.v \
          SspApbif.v \
          SspIntGen.v \
          SspRegCore.v \
          SspScaleCntr.v \
          SspTxRegFile.v \
          SspTxFCntl.v \
          SspTxLJustify.v \
          SspTxFIFO.v \
          SspRxRegFile.v \
          SspRxFCntl.v \
          SspRxFIFO.v \
          SspSynctoPCLK.v \
          SspSynctoSSPCLK.v \
          SspTest.v \
          SspSTxRxCntl.v \
          SspMTxRxCntl.v \
          SspDataStp.v \
          SspDMA.v \
          SspRevAnd.v \
          Ssp.v

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

############################# End of file ######################################

