#- --=========================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- -----------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.5
#-
#- Release Information    : PrimeCell(TM)-PL081-REL1v0
#-
#- -----------------------------------------------------------------------------
#- Purpose  :
#-            makefile for Verilog Trickbox files
#-
#- --=========================================================================--

MODULES =  DmacTrIntArb.v \
           DmacTrAhbSlaveIf.v \
           DmacTrMasWrap.v \
           DmacTrAhbLite.v \
           DmacTrAhbMaster.v \
           DmacTrRouter.v \
           DmacTrChLogic.v \
           DmacTrBehaviour.v \
           DmacTrProChkr.v \
           DmacTrMem.v \
           DmacTrPeriph.v \
           DmacTrCounter.v \
           DmacTrGntGen.v \
           DmacTrick.v

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk 

##################################### End ######################################
