library verilog;
use verilog.vl_types.all;
entity APBif_DTS is
    port(
        HCLK            : in     vl_logic;
        HRESETn         : in     vl_logic;
        HADDR           : in     vl_logic_vector(31 downto 0);
        HTRANS          : in     vl_logic_vector(1 downto 0);
        HWRITE          : in     vl_logic;
        HWDATA          : in     vl_logic_vector(31 downto 0);
        HSEL            : in     vl_logic;
        HREADY          : in     vl_logic;
        HRDATA          : out    vl_logic_vector(31 downto 0);
        HREADYOUT       : out    vl_logic;
        HRESP           : out    vl_logic_vector(1 downto 0);
        PRDATA          : in     vl_logic_vector(31 downto 0);
        PWDATA          : out    vl_logic_vector(31 downto 0);
        PENABLE         : out    vl_logic;
        PSELS0          : out    vl_logic;
        PSELS1          : out    vl_logic;
        PSELS2          : out    vl_logic;
        PSELS3          : out    vl_logic;
        PSELS4X0        : out    vl_logic;
        PSELS4X1        : out    vl_logic;
        PSELS4X2        : out    vl_logic;
        PSELS4X3        : out    vl_logic;
        PSELS4X4        : out    vl_logic;
        PSELS4X5        : out    vl_logic;
        PSELS4X6        : out    vl_logic;
        PSELS4X7        : out    vl_logic;
        PSELS5X0        : out    vl_logic;
        PSELS5X1        : out    vl_logic;
        PSELS5X2        : out    vl_logic;
        PSELS5X3        : out    vl_logic;
        PSELS5X4        : out    vl_logic;
        PSELS5X5        : out    vl_logic;
        PSELS5X6        : out    vl_logic;
        PSELS5X7        : out    vl_logic;
        PSELS6X0        : out    vl_logic;
        PSELS6X1        : out    vl_logic;
        PSELS6X2        : out    vl_logic;
        PSELS6X3        : out    vl_logic;
        PSELS6X4        : out    vl_logic;
        PSELS6X5        : out    vl_logic;
        PSELS6X6        : out    vl_logic;
        PSELS6X7        : out    vl_logic;
        PSELS7X0        : out    vl_logic;
        PSELS7X1        : out    vl_logic;
        PSELS7X2        : out    vl_logic;
        PSELS7X3        : out    vl_logic;
        PSELS7X4        : out    vl_logic;
        PSELS7X5        : out    vl_logic;
        PSELS7X6        : out    vl_logic;
        PSELS7X7        : out    vl_logic;
        PSELS8X0        : out    vl_logic;
        PSELS8X1        : out    vl_logic;
        PSELS8X2        : out    vl_logic;
        PSELS8X3        : out    vl_logic;
        PSELS8X4        : out    vl_logic;
        PSELS8X5        : out    vl_logic;
        PSELS8X6        : out    vl_logic;
        PSELS8X7        : out    vl_logic;
        PSELS9          : out    vl_logic;
        PSELS10         : out    vl_logic;
        PSELS11         : out    vl_logic;
        PSELS12         : out    vl_logic;
        PSELS13         : out    vl_logic;
        PADDR           : out    vl_logic_vector(11 downto 0);
        PWRITE          : out    vl_logic;
        SCANENABLE      : in     vl_logic;
        SCANINHCLK      : in     vl_logic;
        SCANOUTHCLK     : out    vl_logic
    );
end APBif_DTS;
