library verilog;
use verilog.vl_types.all;
entity dmacahbslaveif is
    port(
        hclk            : in     vl_logic;
        hresetn         : in     vl_logic;
        hseldmac        : in     vl_logic;
        hwrite          : in     vl_logic;
        htrans          : in     vl_logic;
        hwdata          : in     vl_logic_vector(15 downto 0);
        haddr           : in     vl_logic_vector(11 downto 2);
        hsize           : in     vl_logic_vector(2 downto 0);
        hreadyin        : in     vl_logic;
        revision        : in     vl_logic_vector(3 downto 0);
        ch0hrdata       : in     vl_logic_vector(31 downto 0);
        ch1hrdata       : in     vl_logic_vector(31 downto 0);
        ch2hrdata       : in     vl_logic_vector(31 downto 0);
        ch3hrdata       : in     vl_logic_vector(31 downto 0);
        ch4hrdata       : in     vl_logic_vector(31 downto 0);
        ch5hrdata       : in     vl_logic_vector(31 downto 0);
        ch6hrdata       : in     vl_logic_vector(31 downto 0);
        ch7hrdata       : in     vl_logic_vector(31 downto 0);
        dmacbreq        : in     vl_logic_vector(15 downto 0);
        dmaclbreq       : in     vl_logic_vector(15 downto 0);
        dmacsreq        : in     vl_logic_vector(15 downto 0);
        dmaclsreq       : in     vl_logic_vector(15 downto 0);
        dmacsreqsync    : in     vl_logic_vector(15 downto 0);
        dmacbreqsync    : in     vl_logic_vector(15 downto 0);
        dmaclsreqsync   : in     vl_logic_vector(15 downto 0);
        dmaclbreqsync   : in     vl_logic_vector(15 downto 0);
        dmacclr         : in     vl_logic_vector(15 downto 0);
        dmactc          : in     vl_logic_vector(15 downto 0);
        dmacinterr      : in     vl_logic;
        dmacinttc       : in     vl_logic;
        channelen0      : in     vl_logic;
        channelen1      : in     vl_logic;
        channelen2      : in     vl_logic;
        channelen3      : in     vl_logic;
        channelen4      : in     vl_logic;
        channelen5      : in     vl_logic;
        channelen6      : in     vl_logic;
        channelen7      : in     vl_logic;
        interrch0       : in     vl_logic;
        interrch1       : in     vl_logic;
        interrch2       : in     vl_logic;
        interrch3       : in     vl_logic;
        interrch4       : in     vl_logic;
        interrch5       : in     vl_logic;
        interrch6       : in     vl_logic;
        interrch7       : in     vl_logic;
        inttcch0        : in     vl_logic;
        inttcch1        : in     vl_logic;
        inttcch2        : in     vl_logic;
        inttcch3        : in     vl_logic;
        inttcch4        : in     vl_logic;
        inttcch5        : in     vl_logic;
        inttcch6        : in     vl_logic;
        inttcch7        : in     vl_logic;
        rawinterrch0    : in     vl_logic;
        rawinterrch1    : in     vl_logic;
        rawinterrch2    : in     vl_logic;
        rawinterrch3    : in     vl_logic;
        rawinterrch4    : in     vl_logic;
        rawinterrch5    : in     vl_logic;
        rawinterrch6    : in     vl_logic;
        rawinterrch7    : in     vl_logic;
        rawinttcch0     : in     vl_logic;
        rawinttcch1     : in     vl_logic;
        rawinttcch2     : in     vl_logic;
        rawinttcch3     : in     vl_logic;
        rawinttcch4     : in     vl_logic;
        rawinttcch5     : in     vl_logic;
        rawinttcch6     : in     vl_logic;
        rawinttcch7     : in     vl_logic;
        clearreq        : in     vl_logic_vector(15 downto 0);
        errclrreq0      : in     vl_logic_vector(15 downto 0);
        errclrreq1      : in     vl_logic_vector(15 downto 0);
        errclrreq2      : in     vl_logic_vector(15 downto 0);
        errclrreq3      : in     vl_logic_vector(15 downto 0);
        errclrreq4      : in     vl_logic_vector(15 downto 0);
        errclrreq5      : in     vl_logic_vector(15 downto 0);
        errclrreq6      : in     vl_logic_vector(15 downto 0);
        errclrreq7      : in     vl_logic_vector(15 downto 0);
        hreadyout       : out    vl_logic;
        hresp           : out    vl_logic_vector(1 downto 0);
        hrdata          : out    vl_logic_vector(31 downto 0);
        reghwrite       : out    vl_logic;
        regaddress      : out    vl_logic_vector(4 downto 2);
        dmacchannelsel0 : out    vl_logic;
        dmacchannelsel1 : out    vl_logic;
        dmacchannelsel2 : out    vl_logic;
        dmacchannelsel3 : out    vl_logic;
        dmacchannelsel4 : out    vl_logic;
        dmacchannelsel5 : out    vl_logic;
        dmacchannelsel6 : out    vl_logic;
        dmacchannelsel7 : out    vl_logic;
        mskddmacsreq    : out    vl_logic_vector(15 downto 0);
        mskddmacbreq    : out    vl_logic_vector(15 downto 0);
        mskddmaclsreq   : out    vl_logic_vector(15 downto 0);
        mskddmaclbreq   : out    vl_logic_vector(15 downto 0);
        clrinttc0       : out    vl_logic;
        clrinttc1       : out    vl_logic;
        clrinttc2       : out    vl_logic;
        clrinttc3       : out    vl_logic;
        clrinttc4       : out    vl_logic;
        clrinttc5       : out    vl_logic;
        clrinttc6       : out    vl_logic;
        clrinttc7       : out    vl_logic;
        clrinterr0      : out    vl_logic;
        clrinterr1      : out    vl_logic;
        clrinterr2      : out    vl_logic;
        clrinterr3      : out    vl_logic;
        clrinterr4      : out    vl_logic;
        clrinterr5      : out    vl_logic;
        clrinterr6      : out    vl_logic;
        clrinterr7      : out    vl_logic;
        dmacbreqch      : out    vl_logic_vector(15 downto 0);
        dmaclbreqch     : out    vl_logic_vector(15 downto 0);
        dmacsreqch      : out    vl_logic_vector(15 downto 0);
        dmaclsreqch     : out    vl_logic_vector(15 downto 0);
        iten            : out    vl_logic;
        dmacitop1       : out    vl_logic_vector(15 downto 0);
        dmacitop2       : out    vl_logic_vector(15 downto 0);
        dmacitop3       : out    vl_logic_vector(1 downto 0);
        dmacen          : out    vl_logic;
        bigendianm1     : out    vl_logic;
        bigendianm2     : out    vl_logic
    );
end dmacahbslaveif;
