library verilog;
use verilog.vl_types.all;
entity DDRTop is
    generic(
        AW              : integer := 24;
        DW              : integer := 31;
        BW              : integer := 3;
        BL              : integer := 1;
        ID              : integer := 4;
        BBL             : integer := 3;
        WQCD            : integer := 4;
        WQD             : integer := 31;
        RQCD            : integer := 5;
        RQD             : integer := 63;
        WBLQCD          : integer := 2;
        WBLQD           : integer := 7;
        BBLQCD          : integer := 1;
        BBLQD           : integer := 3;
        RBLQCD          : integer := 3;
        RBLQD           : integer := 15;
        MDW             : integer := 15;
        DMW             : integer := 1;
        BAW             : integer := 1;
        RAW             : integer := 12;
        CAW             : integer := 10;
        RWW             : integer := 1;
        CD              : integer := 4;
        erc_powerup     : integer := 1;
        erc_epc         : integer := 2;
        erc_ar          : integer := 4;
        erc_mrs         : integer := 8;
        erc_idle        : integer := 16;
        erc_normal      : integer := 32;
        bc_null         : integer := 0;
        bc_mcas         : integer := 1;
        bc_mras         : integer := 2;
        bc_pc           : integer := 4;
        bc_sras         : integer := 8;
        bc_scas         : integer := 16;
        bc_epc          : integer := 32;
        ebc_null        : integer := 0;
        ebc_mcas        : integer := 1;
        ebc_mras        : integer := 2;
        ebc_pc          : integer := 4;
        ebc_sras        : integer := 8;
        ebc_scas        : integer := 16;
        ebc_epc         : integer := 32;
        ebc_bstop       : integer := 64
    );
    port(
        ARESETB         : in     vl_logic;
        nPOR            : in     vl_logic;
        MCLK            : in     vl_logic;
        nMCLK           : in     vl_logic;
        ACLK            : in     vl_logic;
        nACLK           : in     vl_logic;
        AWAddr          : in     vl_logic_vector(31 downto 0);
        AWId            : in     vl_logic_vector;
        AWLen           : in     vl_logic_vector;
        AWValid         : in     vl_logic;
        AWReady         : out    vl_logic;
        AWBurst         : in     vl_logic_vector(1 downto 0);
        WLast           : in     vl_logic;
        WStrb           : in     vl_logic_vector;
        WData           : in     vl_logic_vector;
        WValid          : in     vl_logic;
        WReady          : out    vl_logic;
        WId             : in     vl_logic_vector;
        BResp           : out    vl_logic_vector(1 downto 0);
        BValid          : out    vl_logic;
        BReady          : in     vl_logic;
        BId             : out    vl_logic_vector;
        ARAddr          : in     vl_logic_vector(31 downto 0);
        ARId            : in     vl_logic_vector;
        ARLen           : in     vl_logic_vector;
        ARValid         : in     vl_logic;
        ARReady         : out    vl_logic;
        ARBurst         : in     vl_logic_vector(1 downto 0);
        RData           : out    vl_logic_vector;
        RValid          : out    vl_logic;
        RReady          : in     vl_logic;
        RLast           : out    vl_logic;
        RId             : out    vl_logic_vector;
        RResp           : out    vl_logic_vector(1 downto 0);
        SD_CKE          : out    vl_logic;
        SD_CSB          : out    vl_logic;
        SD_RASB         : out    vl_logic;
        SD_CASB         : out    vl_logic;
        SD_WEB          : out    vl_logic;
        SD_BADDR        : out    vl_logic_vector;
        SD_ADDR         : out    vl_logic_vector;
        SD_DQE          : out    vl_logic;
        SD_DQI          : in     vl_logic_vector;
        SD_DQO          : out    vl_logic_vector;
        SD_DQM          : out    vl_logic_vector;
        SD_DQSE         : out    vl_logic;
        SD_DQSO         : out    vl_logic_vector;
        SD_DQSI         : in     vl_logic_vector;
        nSD_DQSI        : in     vl_logic_vector;
        PCLK            : in     vl_logic;
        PRESETB         : in     vl_logic;
        PSEL            : in     vl_logic;
        PENABLE         : in     vl_logic;
        PADDR           : in     vl_logic_vector(7 downto 2);
        PWRITE          : in     vl_logic;
        PWDATA          : in     vl_logic_vector(31 downto 0);
        PRDATA          : out    vl_logic_vector(31 downto 0)
    );
end DDRTop;
