library verilog;
use verilog.vl_types.all;
entity ReadChannelsi_RS is
    generic(
        BUS_WID         : integer := 32;
        ADDR_WID        : integer := 32;
        ID_WID          : integer := 4;
        AWLEN_WID       : integer := 4;
        AWSIZE_WID      : integer := 3;
        AWBURST_WID     : integer := 2;
        AWLOCK_WID      : integer := 2;
        AWCACHE_WID     : integer := 4;
        AWPROT_WID      : integer := 3;
        WSTRB_WID       : integer := 4;
        BRESP_WID       : integer := 2;
        RRESP_WID       : integer := 2;
        ARLEN_WID       : integer := 4;
        ARSIZE_WID      : integer := 3;
        ARBURST_WID     : integer := 2;
        ARLOCK_WID      : integer := 2;
        ARCACHE_WID     : integer := 4;
        ARPROT_WID      : integer := 3;
        MASTER_WID      : integer := 4;
        SLAVE_WID       : integer := 3;
        SLAVE_NUM       : integer := 6;
        MASTER_NUM      : integer := 4;
        SLAVECNTWID     : integer := 5;
        REQDEPTH_WID    : integer := 2
    );
    port(
        ACLK            : in     vl_logic;
        ARESETn         : in     vl_logic;
        ARIDm2si        : in     vl_logic_vector;
        ARADDRm2si      : in     vl_logic_vector;
        ARLENm2si       : in     vl_logic_vector;
        ARSIZEm2si      : in     vl_logic_vector;
        ARBURSTm2si     : in     vl_logic_vector;
        ARLOCKm2si      : in     vl_logic_vector;
        ARCACHEm2si     : in     vl_logic_vector;
        ARPROTm2si      : in     vl_logic_vector;
        ARVALIDm2si     : in     vl_logic;
        ARREADYsi2m     : out    vl_logic;
        RIDsi2m         : out    vl_logic_vector;
        RRESPsi2m       : out    vl_logic_vector;
        RVALIDsi2m      : out    vl_logic;
        RDATAsi2m       : out    vl_logic_vector;
        RREADYm2si      : in     vl_logic;
        RLASTsi2m       : out    vl_logic;
        ARIDsi2mi       : out    vl_logic_vector;
        ARADDRsi2mi     : out    vl_logic_vector;
        ARLENsi2mi      : out    vl_logic_vector;
        ARSIZEsi2mi     : out    vl_logic_vector;
        ARBURSTsi2mi    : out    vl_logic_vector;
        ARLOCKsi2mi     : out    vl_logic_vector;
        ARCACHEsi2mi    : out    vl_logic_vector;
        ARPROTsi2mi     : out    vl_logic_vector;
        ARVALIDsi2mi    : out    vl_logic_vector;
        ARREADYmi2si    : in     vl_logic_vector;
        RIDmi02si       : in     vl_logic_vector;
        RRESPmi02si     : in     vl_logic_vector;
        RDATAmi02si     : in     vl_logic_vector;
        RIDmi12si       : in     vl_logic_vector;
        RRESPmi12si     : in     vl_logic_vector;
        RDATAmi12si     : in     vl_logic_vector;
        RIDmi22si       : in     vl_logic_vector;
        RRESPmi22si     : in     vl_logic_vector;
        RDATAmi22si     : in     vl_logic_vector;
        RIDmi32si       : in     vl_logic_vector;
        RRESPmi32si     : in     vl_logic_vector;
        RDATAmi32si     : in     vl_logic_vector;
        RIDmi42si       : in     vl_logic_vector;
        RRESPmi42si     : in     vl_logic_vector;
        RDATAmi42si     : in     vl_logic_vector;
        RIDmi52si       : in     vl_logic_vector;
        RRESPmi52si     : in     vl_logic_vector;
        RDATAmi52si     : in     vl_logic_vector;
        RVALIDmi2si     : in     vl_logic_vector;
        RREADYsi2mi     : out    vl_logic_vector;
        RLASTmi2si      : in     vl_logic_vector
    );
end ReadChannelsi_RS;
