#-====================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2001 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- ---------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.1
#-
#- Release Information    : PrimeCell(TM)-PL131-REL1v0
#-
#- ---------------------------------------------------------------------
#- Purpose  : makefile for Verilog Trickbox files
#- -==================================================================--


MODULES = \
           SciTrApbif.v       \
           SciTrMux.v         \
           SciTrRegBlk.v      \
           SciTrRegBlkUpd.v   \
           SciTrTxFCntl.v     \
           SciTrTxRegFile.v   \
           SciTrTxFIFO.v      \
           SciTrRxRegFile.v   \
           SciTrRxFCntl.v     \
           SciTrRxFIFO.v      \
           SciTrSynctoPCLK.v  \
           SciTrSynctoRFCLK.v \
           SciTrTXCntl.v      \
           SciTrRXCntl.v      \
           SciTrREFCLKGen.v   \
           SciTrTimCheck.v    \
           SciTrDMA.v         \
           SciTrick.v

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk 

################################# End ##################################

