library verilog;
use verilog.vl_types.all;
entity DmacAXIArbiter is
    port(
        ACLK            : in     vl_logic;
        ARESETn         : in     vl_logic;
        ARVALID0        : in     vl_logic;
        ARREADY0        : out    vl_logic;
        ARADDR0         : in     vl_logic_vector(31 downto 0);
        ARLEN0          : in     vl_logic_vector(3 downto 0);
        ARSIZE0         : in     vl_logic_vector(2 downto 0);
        ARBURST0        : in     vl_logic_vector(1 downto 0);
        RDATA0          : out    vl_logic_vector(31 downto 0);
        RRESP0          : out    vl_logic_vector(1 downto 0);
        RLAST0          : out    vl_logic;
        RVALID0         : out    vl_logic;
        RREADY0         : in     vl_logic;
        AWVALID0        : in     vl_logic;
        AWREADY0        : out    vl_logic;
        AWADDR0         : in     vl_logic_vector(31 downto 0);
        AWLEN0          : in     vl_logic_vector(3 downto 0);
        AWSIZE0         : in     vl_logic_vector(2 downto 0);
        AWBURST0        : in     vl_logic_vector(1 downto 0);
        WDATA0          : in     vl_logic_vector(31 downto 0);
        WSTRB0          : in     vl_logic_vector(3 downto 0);
        WLAST0          : in     vl_logic;
        WVALID0         : in     vl_logic;
        WREADY0         : out    vl_logic;
        BRESP0          : out    vl_logic_vector(1 downto 0);
        BVALID0         : out    vl_logic;
        BREADY0         : in     vl_logic;
        ARVALID1        : in     vl_logic;
        ARREADY1        : out    vl_logic;
        ARADDR1         : in     vl_logic_vector(31 downto 0);
        ARLEN1          : in     vl_logic_vector(3 downto 0);
        ARSIZE1         : in     vl_logic_vector(2 downto 0);
        ARBURST1        : in     vl_logic_vector(1 downto 0);
        RDATA1          : out    vl_logic_vector(31 downto 0);
        RRESP1          : out    vl_logic_vector(1 downto 0);
        RLAST1          : out    vl_logic;
        RVALID1         : out    vl_logic;
        RREADY1         : in     vl_logic;
        AWVALID1        : in     vl_logic;
        AWREADY1        : out    vl_logic;
        AWADDR1         : in     vl_logic_vector(31 downto 0);
        AWLEN1          : in     vl_logic_vector(3 downto 0);
        AWSIZE1         : in     vl_logic_vector(2 downto 0);
        AWBURST1        : in     vl_logic_vector(1 downto 0);
        WDATA1          : in     vl_logic_vector(31 downto 0);
        WSTRB1          : in     vl_logic_vector(3 downto 0);
        WLAST1          : in     vl_logic;
        WVALID1         : in     vl_logic;
        WREADY1         : out    vl_logic;
        BRESP1          : out    vl_logic_vector(1 downto 0);
        BVALID1         : out    vl_logic;
        BREADY1         : in     vl_logic;
        ARID            : out    vl_logic;
        ARVALID         : out    vl_logic;
        ARREADY         : in     vl_logic;
        ARADDR          : out    vl_logic_vector(31 downto 0);
        ARLEN           : out    vl_logic_vector(3 downto 0);
        ARSIZE          : out    vl_logic_vector(2 downto 0);
        ARBURST         : out    vl_logic_vector(1 downto 0);
        RID             : in     vl_logic;
        RDATA           : in     vl_logic_vector(31 downto 0);
        RRESP           : in     vl_logic_vector(1 downto 0);
        RLAST           : in     vl_logic;
        RVALID          : in     vl_logic;
        RREADY          : out    vl_logic;
        AWID            : out    vl_logic;
        AWVALID         : out    vl_logic;
        AWREADY         : in     vl_logic;
        AWADDR          : out    vl_logic_vector(31 downto 0);
        AWLEN           : out    vl_logic_vector(3 downto 0);
        AWSIZE          : out    vl_logic_vector(2 downto 0);
        AWBURST         : out    vl_logic_vector(1 downto 0);
        WID             : out    vl_logic;
        WDATA           : out    vl_logic_vector(31 downto 0);
        WSTRB           : out    vl_logic_vector(3 downto 0);
        WLAST           : out    vl_logic;
        WVALID          : out    vl_logic;
        WREADY          : in     vl_logic;
        BID             : in     vl_logic;
        BRESP           : in     vl_logic_vector(1 downto 0);
        BVALID          : in     vl_logic;
        BREADY          : out    vl_logic
    );
end DmacAXIArbiter;
