library verilog;
use verilog.vl_types.all;
entity dmacengine is
    port(
        aclk            : in     vl_logic;
        aresetn         : in     vl_logic;
        start           : in     vl_logic;
        ready           : out    vl_logic;
        chcontrol       : in     vl_logic_vector(31 downto 0);
        chsrcaddr       : in     vl_logic_vector(31 downto 0);
        chdestaddr      : in     vl_logic_vector(31 downto 0);
        chdescriptor    : in     vl_logic_vector(31 downto 0);
        chcontrolwe     : out    vl_logic;
        chsrcaddrwe     : out    vl_logic;
        chdestaddrwe    : out    vl_logic;
        chdescriptorwe  : out    vl_logic;
        chcontrolwdata  : out    vl_logic_vector(31 downto 0);
        chsrcaddrwdata  : out    vl_logic_vector(31 downto 0);
        chdestaddrwdata : out    vl_logic_vector(31 downto 0);
        chdescriptorwdata: out    vl_logic_vector(31 downto 0);
        arvalid         : out    vl_logic;
        arready         : in     vl_logic;
        araddr          : out    vl_logic_vector(31 downto 0);
        arlen           : out    vl_logic_vector(3 downto 0);
        arsize          : out    vl_logic_vector(2 downto 0);
        arburst         : out    vl_logic_vector(1 downto 0);
        rdata           : in     vl_logic_vector(31 downto 0);
        rresp           : in     vl_logic_vector(1 downto 0);
        rlast           : in     vl_logic;
        rvalid          : in     vl_logic;
        rready          : out    vl_logic;
        awvalid         : out    vl_logic;
        awready         : in     vl_logic;
        awaddr          : out    vl_logic_vector(31 downto 0);
        awlen           : out    vl_logic_vector(3 downto 0);
        awsize          : out    vl_logic_vector(2 downto 0);
        awburst         : out    vl_logic_vector(1 downto 0);
        wdata           : out    vl_logic_vector(31 downto 0);
        wstrb           : out    vl_logic_vector(3 downto 0);
        wlast           : out    vl_logic;
        wvalid          : out    vl_logic;
        wready          : in     vl_logic;
        bresp           : in     vl_logic_vector(1 downto 0);
        bvalid          : in     vl_logic;
        bready          : out    vl_logic;
        startinterrupt  : out    vl_logic;
        endinterrupt    : out    vl_logic;
        errorinterrupt  : out    vl_logic;
        stopinterrupt   : out    vl_logic
    );
end dmacengine;
