#- --=========================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2003 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- -----------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.7
#-
#- Release Information    : PrimeCell(TM)-PL093-r0p3-00rel0
#-
#- -----------------------------------------------------------------------------
#- Purpose :
#-           Standard VHDL Library Makefile
#-
#- --=========================================================================--

MODULES = SsmcPackage.vhd \
          SsmcAhbSlvRegIf.vhd \
          SsmcAhbSlvMemIf.vhd \
          SsmcSynchroniser.vhd \
          SsmcMemTSM.vhd \
          SsmcPadMux.vhd \
          SsmcPadIf.vhd \
          SsmcDerivedClk.vhd \
          SsmcCore.vhd \
          SsmcTIC.vhd \
          SsmcDBI.vhd \
          SsmcClockOr.vhd \
          SsmcRevAnd.vhd \
          Ssmc.vhd


include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

#- --================================= End ===================================--
