@TM:1141092916
@N: FX164 :"":0:0:0:-1|The option to pack flops in the IOB has not been specified 
@TM:1141092919
@N: MT195 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT197 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@TM:1141092916
@N: MT204 :"":0:0:0:-1|Autoconstrain Mode is ON
@TM:1141092915
@N:  :"d:\data\adc_ltr9200\rtl\adc_control.v":21:7:21:17|Synthesizing module adc_control
@TM:1141100164
@W: CL159 :"d:\data\adc_ltr9200\rtl\adc_control.v":68:6:68:15|M
@W: CL159 :"d:\data\adc_ltr9200\rtl\adc_control.v":69:6:69:15|M
@W: CL159 :"d:\data\adc_ltr9200\rtl\adc_control.v":70:6:70:16|M
@TM:1141110386
@N: FX235 :"d:\data\adc_ltr9200\rtl\adc_control.v":126:0:126:5|M
@N:  :"d:\data\adc_ltr9200\rtl\adc_control.v":174:15:174:27|M
@N: CL201 :"d:\data\adc_ltr9200\rtl\adc_control.v":231:0:231:5|M
@N: FX235 :"d:\data\adc_ltr9200\rtl\adc_control.v":266:0:266:5|M
@TM:1141285350
@N:  :"d:\data\adc_ltr9200\rtl\adc_control.v":306:13:306:25|M
