library verilog;
use verilog.vl_types.all;
entity VideoTimingGen is
    generic(
        HSYNC_LOW_NTSC  : integer := 16;
        HSYNC_LOW_PAL   : integer := 16;
        YSCALE_NTSC     : integer := 605;
        USCALE_NTSC     : integer := 516;
        VSCALE_NTSC     : integer := 718;
        YSCALE_NTSCJ    : integer := 654;
        USCALE_NTSCJ    : integer := 558;
        VSCALE_NTSCJ    : integer := 787;
        YSCALE_PAL      : integer := 640;
        USCALE_PAL      : integer := 546;
        VSCALE_PAL      : integer := 770;
        BLANK_VALUE_NTSC: integer := 240;
        BLANK_VALUE_PAL : integer := 252;
        BLANK_VALUE_C   : integer := 512;
        BLACK_VALUE_NTSC: integer := 282;
        BLACK_VALUE_PAL : integer := 252;
        TOTAL_PIXEL_NTSC: integer := 1716;
        TOTAL_PIXEL_PAL : integer := 1728;
        TOTAL_PIXEL_SQ_NTSC: integer := 1560;
        TOTAL_PIXEL_SQ_PAL: integer := 1888;
        TOTAL_PIXEL_NTSCM1: integer := 1715;
        TOTAL_PIXEL_PALM1: integer := 1727;
        TOTAL_PIXEL_SQ_NTSCM1: integer := 1559;
        TOTAL_PIXEL_SQ_PALM1: integer := 1887;
        TOTAL_LINE_NTSC : integer := 525;
        TOTAL_LINE_PAL  : integer := 625;
        TOTAL_DISPLAY_LINE_NTSC: integer := 480;
        TOTAL_DISPLAY_LINE_PAL: integer := 576;
        TOTAL_LINE_NTSC_NOINTER: integer := 262;
        TOTAL_LINE_PAL_NOINTER: integer := 312;
        TOTAL_DISPLAY_LINE_NTSC_NOINTER: integer := 240;
        TOTAL_DISPLAY_LINE_PAL_NOINTER: integer := 288;
        CHANGE_FIELDS0_NTSC: integer := 525;
        CHANGE_FIELDS1_NTSC: integer := 263;
        CHANGE_FIELDS0_NTSC_NOINTER: integer := 252;
        CHANGE_FIELDS0_PAL: integer := 625;
        CHANGE_FIELDS1_PAL: integer := 313;
        CHANGE_FIELDS0_PAL_NOINTER: integer := 312;
        ACTIVE_TOTAL_PIXEL_NTSC_RGB: integer := 2160;
        ACTIVE_TOTAL_PIXEL_PAL_RGB: integer := 2160;
        ACTIVE_TOTAL_PIXEL_SQ_NTSC_RGB: integer := 1920;
        ACTIVE_TOTAL_PIXEL_SQ_PAL_RGB: integer := 2304;
        BURST_MAX_NTSC  : integer := 112;
        BURST_MAX_PAL   : integer := 117;
        HSYNC_START_NTSC: integer := 32;
        BURST_START_NTSC: integer := 170;
        COLOR_START_NTSC: integer := 276;
        HSYNC_SLOPE_NTSC: integer := 4;
        BURST_SLOPE_NTSC: integer := 8;
        HSYNC_START_SQ_NTSC: integer := 44;
        BURST_START_SQ_NTSC: integer := 168;
        COLOR_START_SQ_NTSC: integer := 280;
        HSYNC_SLOPE_SQ_NTSC: integer := 4;
        BLANK_VALUE_7_5 : integer := 42;
        HSYNC_START_PAL : integer := 24;
        BURST_START_PAL : integer := 170;
        COLOR_START_PAL : integer := 288;
        HSYNC_SLOPE_PAL : integer := 7;
        BURST_SLOPE_PAL : integer := 8;
        HSYNC_START_SQ_PAL: integer := 42;
        BURST_START_SQ_PAL: integer := 202;
        COLOR_START_SQ_PAL: integer := 352;
        HSYNC_SLOPE_SQ_PAL: integer := 7;
        BURST_SLOPE_SQ_PAL: integer := 8;
        BLANK_VALUE_0   : integer := 0;
        EQUALIZING_AREA0_START_NTSC: integer := 523;
        EQUALIZING_AREA0_END_NTSC: integer := 525;
        EQUALIZING_AREA1_START_NTSC: integer := 4;
        EQUALIZING_AREA1_END_NTSC: integer := 6;
        EQUALIZING_AREA2_START_NTSC: integer := 261;
        EQUALIZING_AREA2_END_NTSC: integer := 262;
        EQUALIZING_AREA3_START_NTSC: integer := 267;
        EQUALIZING_AREA3_END_NTSC: integer := 268;
        EQUALIZING_AREA0_START_NTSC_NOINTER: integer := 260;
        EQUALIZING_AREA0_END_NTSC_NOINTER: integer := 262;
        EQUALIZING_AREA1_START_NTSC_NOINTER: integer := 4;
        EQUALIZING_AREA1_END_NTSC_NOINTER: integer := 6;
        EQUALIZING_AREA0_START_PAL: integer := 624;
        EQUALIZING_AREA0_END_PAL: integer := 625;
        EQUALIZING_AREA1_START_PAL: integer := 4;
        EQUALIZING_AREA1_END_PAL: integer := 5;
        EQUALIZING_AREA2_START_PAL: integer := 311;
        EQUALIZING_AREA2_END_PAL: integer := 312;
        EQUALIZING_AREA3_START_PAL: integer := 316;
        EQUALIZING_AREA3_END_PAL: integer := 317;
        EQUALIZING_AREA0_START_PAL_NOINTER: integer := 311;
        EQUALIZING_AREA0_END_PAL_NOINTER: integer := 312;
        EQUALIZING_AREA1_START_PAL_NOINTER: integer := 4;
        EQUALIZING_AREA1_END_PAL_NOINTER: integer := 5;
        EQUALIZING_AREA0_START_MPAL: integer := 523;
        EQUALIZING_AREA0_END_MPAL: integer := 525;
        EQUALIZING_AREA1_START_MPAL: integer := 4;
        EQUALIZING_AREA1_END_MPAL: integer := 6;
        EQUALIZING_AREA2_START_MPAL: integer := 261;
        EQUALIZING_AREA2_END_MPAL: integer := 262;
        EQUALIZING_AREA3_START_MPAL: integer := 267;
        EQUALIZING_AREA3_END_MPAL: integer := 268;
        SERRATION_AREA0_START_NTSC: integer := 1;
        SERRATION_AREA0_END_NTSC: integer := 3;
        SERRATION_AREA1_START_NTSC: integer := 264;
        SERRATION_AREA1_END_NTSC: integer := 265;
        SERRATION_AREA0_START_NTSC_NOINTER: integer := 1;
        SERRATION_AREA0_END_NTSC_NOINTER: integer := 3;
        SERRATION_AREA0_START_PAL: integer := 1;
        SERRATION_AREA0_END_PAL: integer := 2;
        SERRATION_AREA1_START_PAL: integer := 314;
        SERRATION_AREA1_END_PAL: integer := 315;
        SERRATION_AREA0_START_PAL_NOINTER: integer := 1;
        SERRATION_AREA0_END_PAL_NOINTER: integer := 2;
        SERRATION_AREA0_START_MPAL: integer := 1;
        SERRATION_AREA0_END_MPAL: integer := 3;
        SERRATION_AREA1_START_MPAL: integer := 264;
        SERRATION_AREA1_END_MPAL: integer := 265;
        SERREQ_AREA0_NTSC: integer := 260;
        SERREQ_AREA0_PAL: integer := 623;
        SERREQ_AREA0_MPAL: integer := 260;
        SERREQ_AREA1_NTSC: integer := 266;
        SERREQ_AREA1_PAL: integer := 3;
        SERREQ_AREA1_PAL_NOINTER: integer := 3;
        SERREQ_AREA1_MPAL: integer := 266;
        EQSERR_AREA0_NTSC: integer := 263;
        EQSERR_AREA0_PAL: integer := 313;
        EQSERR_AREA0_MPAL: integer := 263;
        EQBLANK_AREA0_NTSC: integer := 269;
        EQBLANK_AREA0_PAL: integer := 318;
        EQBLANK_AREA0_MPAL: integer := 269;
        BURST_AREA1_START_NTSC: integer := 1;
        BURST_AREA1_END_NTSC: integer := 6;
        BURST_AREA2_START_NTSC: integer := 261;
        BURST_AREA2_END_NTSC: integer := 269;
        BURST_AREA3_START_NTSC: integer := 523;
        BURST_AREA3_END_NTSC: integer := 525;
        BURST_AREA1_START_NTSC_NOINTER: integer := 1;
        BURST_AREA1_END_NTSC_NOINTER: integer := 6;
        BURST_AREA2_START_NTSC_NOINTER: integer := 260;
        BURST_AREA2_END_NTSC_NOINTER: integer := 262;
        BURST_AREA1_START_PAL0: integer := 1;
        BURST_AREA1_END_PAL0: integer := 6;
        BURST_AREA2_START_PAL0: integer := 310;
        BURST_AREA2_END_PAL0: integer := 318;
        BURST_AREA3_START_PAL0: integer := 623;
        BURST_AREA3_END_PAL0: integer := 625;
        BURST_AREA1_START_PAL1: integer := 1;
        BURST_AREA1_END_PAL1: integer := 5;
        BURST_AREA2_START_PAL1: integer := 311;
        BURST_AREA2_END_PAL1: integer := 319;
        BURST_AREA3_START_PAL1: integer := 622;
        BURST_AREA3_END_PAL1: integer := 625;
        BURST_AREA1_START_PAL0_NOINTER: integer := 1;
        BURST_AREA1_END_PAL0_NOINTER: integer := 6;
        BURST_AREA2_START_PAL0_NOINTER: integer := 311;
        BURST_AREA2_END_PAL0_NOINTER: integer := 312;
        BURST_AREA1_START_MPAL0: integer := 1;
        BURST_AREA1_END_MPAL0: integer := 8;
        BURST_AREA2_START_MPAL0: integer := 260;
        BURST_AREA2_END_MPAL0: integer := 270;
        BURST_AREA3_START_MPAL0: integer := 523;
        BURST_AREA3_END_MPAL0: integer := 525;
        BURST_AREA1_START_MPAL1: integer := 1;
        BURST_AREA1_END_MPAL1: integer := 7;
        BURST_AREA2_START_MPAL1: integer := 259;
        BURST_AREA2_END_MPAL1: integer := 269;
        BURST_AREA3_START_MPAL1: integer := 522;
        BURST_AREA3_END_MPAL1: integer := 525;
        BURST_AREA1_START_MPAL_NOINTER: integer := 1;
        BURST_AREA1_END_MPAL_NOINTER: integer := 6;
        BURST_AREA2_START_MPAL_NOINTER: integer := 260;
        BURST_AREA2_END_MPAL_NOINTER: integer := 262;
        ACTIVE_FIELD1_START_NTSC: integer := 20;
        ACTIVE_FIELD1_END_NTSC: integer := 259;
        ACTIVE_FIELD2_START_NTSC: integer := 283;
        ACTIVE_FIELD2_END_NTSC: integer := 522;
        ACTIVE_FIELD1_START_NTSC_NOINTER: integer := 23;
        ACTIVE_FIELD1_END_NTSC_NOINTER: integer := 259;
        ACTIVE_FIELD1_START_PAL: integer := 23;
        ACTIVE_FIELD1_END_PAL: integer := 310;
        ACTIVE_FIELD2_START_PAL: integer := 336;
        ACTIVE_FIELD2_END_PAL: integer := 623;
        ACTIVE_FIELD1_START_PAL_NOINTER: integer := 23;
        ACTIVE_FIELD1_END_PAL_NOINTER: integer := 310;
        NTSCM           : integer := 0;
        NTSCJ           : integer := 1;
        NTSC4           : integer := 2;
        PALM            : integer := 3;
        PAL             : integer := 4;
        PALNc           : integer := 5;
        PALN            : integer := 6
    );
    port(
        CLK             : in     vl_logic;
        RESETn          : in     vl_logic;
        HSYNCn          : in     vl_logic;
        VSYNCn          : in     vl_logic;
        BLANKn          : in     vl_logic;
        ENABLE          : in     vl_logic;
        EN_SQPIXEL      : in     vl_logic;
        EN_NONINTERLACE : in     vl_logic;
        EN_RESET_SCH    : in     vl_logic;
        EN_INTERNAL_PATTERN: in     vl_logic;
        OUT_MODE        : in     vl_logic_vector(2 downto 0);
        BURST_WID       : in     vl_logic_vector(1 downto 0);
        HSYNC_WID       : in     vl_logic_vector(2 downto 0);
        MASTER_SLAVE_SEL: in     vl_logic;
        INTERMODE_SEL   : in     vl_logic_vector(1 downto 0);
        LUMA_FILTER_SEL : in     vl_logic_vector(1 downto 0);
        CHRO_FILTER_SEL : in     vl_logic_vector(1 downto 0);
        ACT_DISPLAY_SYN : out    vl_logic;
        ACT_DISPLAY_ADDR: out    vl_logic;
        ACT_DISPLAY_INTER: out    vl_logic;
        F_COUNTER_INTER : out    vl_logic_vector(4 downto 0);
        H_COUNTER_INTER : out    vl_logic_vector(10 downto 0);
        V_COUNTER_INTER : out    vl_logic_vector(9 downto 0);
        HSYNC_ENABLE    : out    vl_logic;
        BURST_ENABLE    : out    vl_logic;
        BURST_ENABLE_ADDR: out    vl_logic;
        RESET_ADDR      : out    vl_logic;
        BURST_ID        : out    vl_logic;
        NTSC_PAL        : out    vl_logic;
        BURST_NTSC_PAL  : out    vl_logic
    );
end VideoTimingGen;
