library verilog;
use verilog.vl_types.all;
entity NFCtrl is
    generic(
        ST_IDLE         : integer := 1;
        ST_LOAD         : integer := 2;
        ST_CMD          : integer := 4;
        ST_ADDR         : integer := 8;
        ST_RNBCHECK     : integer := 16;
        ST_WAIT2CLK     : integer := 32;
        ST_WDATA        : integer := 64;
        ST_RDATA        : integer := 128;
        TST_IDLE        : integer := 1;
        TST_TADLTWB     : integer := 2;
        TST_TCALS       : integer := 4;
        TST_TRWLP       : integer := 8;
        TST_TRWHP       : integer := 16
    );
    port(
        Clk             : in     vl_logic;
        nRst            : in     vl_logic;
        DMAReqOut       : out    vl_logic;
        NFCtrlBusyOut   : out    vl_logic;
        NFStatValidOut  : out    vl_logic;
        NFStatusOut     : out    vl_logic_vector(15 downto 0);
        WrEndOut        : out    vl_logic;
        RdEndOut        : out    vl_logic;
        WrFIFOReadyOut  : out    vl_logic;
        RdFIFOReadyOut  : out    vl_logic;
        FIFOFlushOut    : out    vl_logic;
        FIFORdDataIn    : in     vl_logic_vector(31 downto 0);
        FIFORdDataEnOut : out    vl_logic;
        FIFOWrDataOut   : out    vl_logic_vector(31 downto 0);
        FIFOWrDataEnOut : out    vl_logic;
        BeforeFullIn    : in     vl_logic;
        FIFORdReadyIn   : in     vl_logic;
        FIFOFullIn      : in     vl_logic;
        FIFOHalfFullIn  : in     vl_logic;
        FIFOEmpty1In    : in     vl_logic;
        FIFOEmpty0In    : in     vl_logic;
        WrRdyIn         : in     vl_logic;
        RdRdyIn         : in     vl_logic;
        NFOpRdEnOut     : out    vl_logic;
        NFOpIn          : in     vl_logic_vector(31 downto 0);
        QLevelIn        : in     vl_logic_vector(3 downto 0);
        NFCTRL0In       : in     vl_logic_vector(7 downto 0);
        NFCTRL1In       : in     vl_logic_vector(7 downto 0);
        NFCONF0In       : in     vl_logic_vector(7 downto 0);
        NFCONF1In       : in     vl_logic_vector(7 downto 0);
        NFCONF2In       : in     vl_logic_vector(7 downto 0);
        EccIn           : in     vl_logic_vector(15 downto 0);
        AutoEccWrEnIn   : in     vl_logic;
        BoundaryIn      : in     vl_logic;
        NST_RdataOut    : out    vl_logic;
        CST_RdataOut    : out    vl_logic;
        CST_WdataOut    : out    vl_logic;
        EccDataOut      : out    vl_logic_vector(15 downto 0);
        EccDataEnOut    : out    vl_logic;
        AddrValidOut    : out    vl_logic;
        ColumnAddrOut   : out    vl_logic_vector(11 downto 0);
        NFDataIn        : in     vl_logic_vector(15 downto 0);
        NFDataOut       : out    vl_logic_vector(15 downto 0);
        NFDataOutEnOut  : out    vl_logic;
        CLEOut          : out    vl_logic;
        ALEOut          : out    vl_logic;
        nNFCE3Out       : out    vl_logic;
        nNFCE2Out       : out    vl_logic;
        nNFCE1Out       : out    vl_logic;
        nNFCE0Out       : out    vl_logic;
        nNFREOut        : out    vl_logic;
        nNFWEOut        : out    vl_logic;
        FiltRnB3In      : in     vl_logic;
        FiltRnB2In      : in     vl_logic;
        FiltRnB1In      : in     vl_logic;
        FiltRnB0In      : in     vl_logic;
        TransSize       : out    vl_logic
    );
end NFCtrl;
