// ARM7TDMICRFTESTER.v
//
// Verilog implementation of ARM7TDMICRFTESTER, generated by simwrap

// Elements of the code in this file are
// Copyright 1993-99, 2000-02 ARM Ltd,
// All rights reserved.

`timescale 1 ps / 1 ps

// Inout shell

module ARM7TDMICRFTESTER_inout (A,
  ABE,
  ABORT,
  ALE,
  APE,
  BIGEND,
  BL,
  BREAKPT,
  BUSDIS,
  BUSEN,
  COMMRX,
  COMMTX,
  CPA,
  CPB,
  D_xmgxread,
  D,
  DBE,
  DBGACK,
  DBGEN,
  DBGRQ,
  DBGRQI,
  DIN,
  DOUT,
  DRIVEBS,
  ECAPCLK,
  ECAPCLKBS,
  ECLK,
  EXTERN0,
  EXTERN1,
  HIGHZ,
  ICAPCLKBS,
  IR,
  ISYNC,
  LOCK,
  MAS,
  MCLK,
  nCPI,
  nENIN,
  nENOUT,
  nENOUTI,
  nEXEC,
  nFIQ,
  nHIGHZ,
  nIRQ,
  nM,
  nMREQ,
  nOPC,
  nRESET,
  nRW,
  nTDOEN,
  nTRANS,
  nTRST,
  nWAIT,
  PCLKBS,
  RANGEOUT0,
  RANGEOUT1,
  RSTCLKBS,
  SCREG,
  SDINBS,
  SDOUTBS,
  SEQ,
  SHCLK2BS,
  SHCLKBS,
  TAPSM,
  TBE,
  TBIT,
  TCK,
  TCK1,
  TCK2,
  TDI,
  TDO,
  TMS,
  CRFA,
  CRFABE,
  CRFABORT,
  CRFALE,
  CRFAPE,
  CRFBIGEND,
  CRFBL,
  CRFBREAKPT,
  CRFBUSDIS,
  CRFBUSEN,
  CRFCOMMRX,
  CRFCOMMTX,
  CRFCPA,
  CRFCPB,
  CRFD,
  CRFDBE,
  CRFDBGACK,
  CRFDBGEN,
  CRFDBGRQ,
  CRFDBGRQI,
  CRFDIN,
  CRFDOUT,
  CRFDRIVEBS,
  CRFECAPCLK,
  CRFECAPCLKBS,
  CRFECLK,
  CRFEXTERN0,
  CRFEXTERN1,
  CRFHIGHZ,
  CRFICAPCLKBS,
  CRFIR,
  CRFISYNC,
  CRFLOCK,
  CRFMAS,
  CRFMCLK,
  CRFnCPI,
  CRFnENIN,
  CRFnENOUT,
  CRFnENOUTI,
  CRFnEXEC,
  CRFnFIQ,
  CRFnHIGHZ,
  CRFnIRQ,
  CRFnM,
  CRFnMREQ,
  CRFnOPC,
  CRFnRESET,
  CRFnRW,
  CRFnTDOEN,
  CRFnTRANS,
  CRFnTRST,
  CRFnWAIT,
  CRFPCLKBS,
  CRFRANGEOUT0,
  CRFRANGEOUT1,
  CRFRSTCLKBS,
  CRFSCREG,
  CRFSDINBS,
  CRFSDOUTBS,
  CRFSEQ,
  CRFSHCLK2BS,
  CRFSHCLKBS,
  CRFTAPSM,
  CRFTBE,
  CRFTBIT,
  CRFTCK,
  CRFTCK1,
  CRFTCK2,
  CRFTDI,
  CRFTDO,
  CRFTMS,
  CRFstrobe);

input [31:0] A;
output ABE;
output ABORT;
output ALE;
output APE;
output BIGEND;
output [3:0] BL;
output BREAKPT;
input BUSDIS;
output BUSEN;
input COMMRX;
input COMMTX;
output CPA;
output CPB;
input [31:0] D_xmgxread;
output [31:0] D;
output DBE;
input DBGACK;
output DBGEN;
output DBGRQ;
input DBGRQI;
output [31:0] DIN;
input [31:0] DOUT;
input DRIVEBS;
input ECAPCLK;
input ECAPCLKBS;
input ECLK;
output EXTERN0;
output EXTERN1;
input HIGHZ;
input ICAPCLKBS;
input [3:0] IR;
output ISYNC;
input LOCK;
input [1:0] MAS;
output MCLK;
input nCPI;
output nENIN;
input nENOUT;
input nENOUTI;
input nEXEC;
output nFIQ;
input nHIGHZ;
output nIRQ;
input [4:0] nM;
input nMREQ;
input nOPC;
output nRESET;
input nRW;
input nTDOEN;
input nTRANS;
output nTRST;
output nWAIT;
input PCLKBS;
input RANGEOUT0;
input RANGEOUT1;
input RSTCLKBS;
input [3:0] SCREG;
input SDINBS;
output SDOUTBS;
input SEQ;
input SHCLK2BS;
input SHCLKBS;
input [3:0] TAPSM;
output TBE;
input TBIT;
output TCK;
input TCK1;
input TCK2;
output TDI;
input TDO;
output TMS;
output CRFA;
output CRFABE;
output CRFABORT;
output CRFALE;
output CRFAPE;
output CRFBIGEND;
output CRFBL;
output CRFBREAKPT;
output CRFBUSDIS;
output CRFBUSEN;
output CRFCOMMRX;
output CRFCOMMTX;
output CRFCPA;
output CRFCPB;
output CRFD;
output CRFDBE;
output CRFDBGACK;
output CRFDBGEN;
output CRFDBGRQ;
output CRFDBGRQI;
output CRFDIN;
output CRFDOUT;
output CRFDRIVEBS;
output CRFECAPCLK;
output CRFECAPCLKBS;
output CRFECLK;
output CRFEXTERN0;
output CRFEXTERN1;
output CRFHIGHZ;
output CRFICAPCLKBS;
output CRFIR;
output CRFISYNC;
output CRFLOCK;
output CRFMAS;
output CRFMCLK;
output CRFnCPI;
output CRFnENIN;
output CRFnENOUT;
output CRFnENOUTI;
output CRFnEXEC;
output CRFnFIQ;
output CRFnHIGHZ;
output CRFnIRQ;
output CRFnM;
output CRFnMREQ;
output CRFnOPC;
output CRFnRESET;
output CRFnRW;
output CRFnTDOEN;
output CRFnTRANS;
output CRFnTRST;
output CRFnWAIT;
output CRFPCLKBS;
output CRFRANGEOUT0;
output CRFRANGEOUT1;
output CRFRSTCLKBS;
output CRFSCREG;
output CRFSDINBS;
output CRFSDOUTBS;
output CRFSEQ;
output CRFSHCLK2BS;
output CRFSHCLKBS;
output CRFTAPSM;
output CRFTBE;
output CRFTBIT;
output CRFTCK;
output CRFTCK1;
output CRFTCK2;
output CRFTDI;
output CRFTDO;
output CRFTMS;
output CRFstrobe;

reg CRFA;
reg ABE;
reg CRFABE;
reg ABORT;
reg CRFABORT;
reg ALE;
reg CRFALE;
reg APE;
reg CRFAPE;
reg BIGEND;
reg CRFBIGEND;
reg [3:0] BL;
reg CRFBL;
reg BREAKPT;
reg CRFBREAKPT;
reg CRFBUSDIS;
reg BUSEN;
reg CRFBUSEN;
reg CRFCOMMRX;
reg CRFCOMMTX;
reg CPA;
reg CRFCPA;
reg CPB;
reg CRFCPB;
reg [31:0] D;
reg CRFD;
reg DBE;
reg CRFDBE;
reg CRFDBGACK;
reg DBGEN;
reg CRFDBGEN;
reg DBGRQ;
reg CRFDBGRQ;
reg CRFDBGRQI;
reg [31:0] DIN;
reg CRFDIN;
reg CRFDOUT;
reg CRFDRIVEBS;
reg CRFECAPCLK;
reg CRFECAPCLKBS;
reg CRFECLK;
reg EXTERN0;
reg CRFEXTERN0;
reg EXTERN1;
reg CRFEXTERN1;
reg CRFHIGHZ;
reg CRFICAPCLKBS;
reg CRFIR;
reg ISYNC;
reg CRFISYNC;
reg CRFLOCK;
reg CRFMAS;
reg MCLK;
reg CRFMCLK;
reg CRFnCPI;
reg nENIN;
reg CRFnENIN;
reg CRFnENOUT;
reg CRFnENOUTI;
reg CRFnEXEC;
reg nFIQ;
reg CRFnFIQ;
reg CRFnHIGHZ;
reg nIRQ;
reg CRFnIRQ;
reg CRFnM;
reg CRFnMREQ;
reg CRFnOPC;
reg nRESET;
reg CRFnRESET;
reg CRFnRW;
reg CRFnTDOEN;
reg CRFnTRANS;
reg nTRST;
reg CRFnTRST;
reg nWAIT;
reg CRFnWAIT;
reg CRFPCLKBS;
reg CRFRANGEOUT0;
reg CRFRANGEOUT1;
reg CRFRSTCLKBS;
reg CRFSCREG;
reg CRFSDINBS;
reg SDOUTBS;
reg CRFSDOUTBS;
reg CRFSEQ;
reg CRFSHCLK2BS;
reg CRFSHCLKBS;
reg CRFTAPSM;
reg TBE;
reg CRFTBE;
reg CRFTBIT;
reg TCK;
reg CRFTCK;
reg CRFTCK1;
reg CRFTCK2;
reg TDI;
reg CRFTDI;
reg CRFTDO;
reg TMS;
reg CRFTMS;
reg CRFstrobe;
parameter
  MG_LOGFILE_NAME = "",
  MG_FORCED_DELAY = 0,
  MG_OBJECT = "$DIR_ARM7TDMICRFTESTER",
  MG_OMI_PATH = "",
  MG_MSG_TIME = 0,
  MG_MSG_INSTANCE = 0,
  MG_MSG_SEVERITY = "",
  MG_MSG_SUPPRESS = "",
  MG_MSG_V4_FORMAT = 0;

initial
  begin
    $mm("ARM7TDMICRFTESTER?locator=MG_OBJECT",A,
    ABE,
    ABORT,
    ALE,
    APE,
    BIGEND,
    BL,
    BREAKPT,
    BUSDIS,
    BUSEN,
    COMMRX,
    COMMTX,
    CPA,
    CPB,
    D_xmgxread,
    D,
    DBE,
    DBGACK,
    DBGEN,
    DBGRQ,
    DBGRQI,
    DIN,
    DOUT,
    DRIVEBS,
    ECAPCLK,
    ECAPCLKBS,
    ECLK,
    EXTERN0,
    EXTERN1,
    HIGHZ,
    ICAPCLKBS,
    IR,
    ISYNC,
    LOCK,
    MAS,
    MCLK,
    nCPI,
    nENIN,
    nENOUT,
    nENOUTI,
    nEXEC,
    nFIQ,
    nHIGHZ,
    nIRQ,
    nM,
    nMREQ,
    nOPC,
    nRESET,
    nRW,
    nTDOEN,
    nTRANS,
    nTRST,
    nWAIT,
    PCLKBS,
    RANGEOUT0,
    RANGEOUT1,
    RSTCLKBS,
    SCREG,
    SDINBS,
    SDOUTBS,
    SEQ,
    SHCLK2BS,
    SHCLKBS,
    TAPSM,
    TBE,
    TBIT,
    TCK,
    TCK1,
    TCK2,
    TDI,
    TDO,
    TMS,
    CRFA, CRFA,
    CRFABE, CRFABE,
    CRFABORT, CRFABORT,
    CRFALE, CRFALE,
    CRFAPE, CRFAPE,
    CRFBIGEND, CRFBIGEND,
    CRFBL, CRFBL,
    CRFBREAKPT, CRFBREAKPT,
    CRFBUSDIS, CRFBUSDIS,
    CRFBUSEN, CRFBUSEN,
    CRFCOMMRX, CRFCOMMRX,
    CRFCOMMTX, CRFCOMMTX,
    CRFCPA, CRFCPA,
    CRFCPB, CRFCPB,
    CRFD, CRFD,
    CRFDBE, CRFDBE,
    CRFDBGACK, CRFDBGACK,
    CRFDBGEN, CRFDBGEN,
    CRFDBGRQ, CRFDBGRQ,
    CRFDBGRQI, CRFDBGRQI,
    CRFDIN, CRFDIN,
    CRFDOUT, CRFDOUT,
    CRFDRIVEBS, CRFDRIVEBS,
    CRFECAPCLK, CRFECAPCLK,
    CRFECAPCLKBS, CRFECAPCLKBS,
    CRFECLK, CRFECLK,
    CRFEXTERN0, CRFEXTERN0,
    CRFEXTERN1, CRFEXTERN1,
    CRFHIGHZ, CRFHIGHZ,
    CRFICAPCLKBS, CRFICAPCLKBS,
    CRFIR, CRFIR,
    CRFISYNC, CRFISYNC,
    CRFLOCK, CRFLOCK,
    CRFMAS, CRFMAS,
    CRFMCLK, CRFMCLK,
    CRFnCPI, CRFnCPI,
    CRFnENIN, CRFnENIN,
    CRFnENOUT, CRFnENOUT,
    CRFnENOUTI, CRFnENOUTI,
    CRFnEXEC, CRFnEXEC,
    CRFnFIQ, CRFnFIQ,
    CRFnHIGHZ, CRFnHIGHZ,
    CRFnIRQ, CRFnIRQ,
    CRFnM, CRFnM,
    CRFnMREQ, CRFnMREQ,
    CRFnOPC, CRFnOPC,
    CRFnRESET, CRFnRESET,
    CRFnRW, CRFnRW,
    CRFnTDOEN, CRFnTDOEN,
    CRFnTRANS, CRFnTRANS,
    CRFnTRST, CRFnTRST,
    CRFnWAIT, CRFnWAIT,
    CRFPCLKBS, CRFPCLKBS,
    CRFRANGEOUT0, CRFRANGEOUT0,
    CRFRANGEOUT1, CRFRANGEOUT1,
    CRFRSTCLKBS, CRFRSTCLKBS,
    CRFSCREG, CRFSCREG,
    CRFSDINBS, CRFSDINBS,
    CRFSDOUTBS, CRFSDOUTBS,
    CRFSEQ, CRFSEQ,
    CRFSHCLK2BS, CRFSHCLK2BS,
    CRFSHCLKBS, CRFSHCLKBS,
    CRFTAPSM, CRFTAPSM,
    CRFTBE, CRFTBE,
    CRFTBIT, CRFTBIT,
    CRFTCK, CRFTCK,
    CRFTCK1, CRFTCK1,
    CRFTCK2, CRFTCK2,
    CRFTDI, CRFTDI,
    CRFTDO, CRFTDO,
    CRFTMS, CRFTMS,
    CRFstrobe, CRFstrobe);
  end

endmodule

// Device shell

module ARM7TDMICRFTESTER (A,
  ABE,
  ABORT,
  ALE,
  APE,
  BIGEND,
  BL,
  BREAKPT,
  BUSDIS,
  BUSEN,
  COMMRX,
  COMMTX,
  CPA,
  CPB,
  D,
  DBE,
  DBGACK,
  DBGEN,
  DBGRQ,
  DBGRQI,
  DIN,
  DOUT,
  DRIVEBS,
  ECAPCLK,
  ECAPCLKBS,
  ECLK,
  EXTERN0,
  EXTERN1,
  HIGHZ,
  ICAPCLKBS,
  IR,
  ISYNC,
  LOCK,
  MAS,
  MCLK,
  nCPI,
  nENIN,
  nENOUT,
  nENOUTI,
  nEXEC,
  nFIQ,
  nHIGHZ,
  nIRQ,
  nM,
  nMREQ,
  nOPC,
  nRESET,
  nRW,
  nTDOEN,
  nTRANS,
  nTRST,
  nWAIT,
  PCLKBS,
  RANGEOUT0,
  RANGEOUT1,
  RSTCLKBS,
  SCREG,
  SDINBS,
  SDOUTBS,
  SEQ,
  SHCLK2BS,
  SHCLKBS,
  TAPSM,
  TBE,
  TBIT,
  TCK,
  TCK1,
  TCK2,
  TDI,
  TDO,
  TMS);

input [31:0] A;
output ABE;
output ABORT;
output ALE;
output APE;
output BIGEND;
output [3:0] BL;
output BREAKPT;
input BUSDIS;
output BUSEN;
input COMMRX;
input COMMTX;
output CPA;
output CPB;
inout [31:0] D;
output DBE;
input DBGACK;
output DBGEN;
output DBGRQ;
input DBGRQI;
output [31:0] DIN;
input [31:0] DOUT;
input DRIVEBS;
input ECAPCLK;
input ECAPCLKBS;
input ECLK;
output EXTERN0;
output EXTERN1;
input HIGHZ;
input ICAPCLKBS;
input [3:0] IR;
output ISYNC;
input LOCK;
input [1:0] MAS;
output MCLK;
input nCPI;
output nENIN;
input nENOUT;
input nENOUTI;
input nEXEC;
output nFIQ;
input nHIGHZ;
output nIRQ;
input [4:0] nM;
input nMREQ;
input nOPC;
output nRESET;
input nRW;
input nTDOEN;
input nTRANS;
output nTRST;
output nWAIT;
input PCLKBS;
input RANGEOUT0;
input RANGEOUT1;
input RSTCLKBS;
input [3:0] SCREG;
input SDINBS;
output SDOUTBS;
input SEQ;
input SHCLK2BS;
input SHCLKBS;
input [3:0] TAPSM;
output TBE;
input TBIT;
output TCK;
input TCK1;
input TCK2;
output TDI;
input TDO;
output TMS;

wire CRFA;
wire CRFABE;
wire CRFABORT;
wire CRFALE;
wire CRFAPE;
wire CRFBIGEND;
wire CRFBL;
wire CRFBREAKPT;
wire CRFBUSDIS;
wire CRFBUSEN;
wire CRFCOMMRX;
wire CRFCOMMTX;
wire CRFCPA;
wire CRFCPB;
wire CRFD;
wire CRFDBE;
wire CRFDBGACK;
wire CRFDBGEN;
wire CRFDBGRQ;
wire CRFDBGRQI;
wire CRFDIN;
wire CRFDOUT;
wire CRFDRIVEBS;
wire CRFECAPCLK;
wire CRFECAPCLKBS;
wire CRFECLK;
wire CRFEXTERN0;
wire CRFEXTERN1;
wire CRFHIGHZ;
wire CRFICAPCLKBS;
wire CRFIR;
wire CRFISYNC;
wire CRFLOCK;
wire CRFMAS;
wire CRFMCLK;
wire CRFnCPI;
wire CRFnENIN;
wire CRFnENOUT;
wire CRFnENOUTI;
wire CRFnEXEC;
wire CRFnFIQ;
wire CRFnHIGHZ;
wire CRFnIRQ;
wire CRFnM;
wire CRFnMREQ;
wire CRFnOPC;
wire CRFnRESET;
wire CRFnRW;
wire CRFnTDOEN;
wire CRFnTRANS;
wire CRFnTRST;
wire CRFnWAIT;
wire CRFPCLKBS;
wire CRFRANGEOUT0;
wire CRFRANGEOUT1;
wire CRFRSTCLKBS;
wire CRFSCREG;
wire CRFSDINBS;
wire CRFSDOUTBS;
wire CRFSEQ;
wire CRFSHCLK2BS;
wire CRFSHCLKBS;
wire CRFTAPSM;
wire CRFTBE;
wire CRFTBIT;
wire CRFTCK;
wire CRFTCK1;
wire CRFTCK2;
wire CRFTDI;
wire CRFTDO;
wire CRFTMS;
wire CRFstrobe;

parameter
  MG_LOGFILE_NAME = "",
  MG_FORCED_DELAY = 0,
  MG_OBJECT = "$DIR_ARM7TDMICRFTESTER",
  MG_OMI_PATH = "",
  MG_MSG_TIME = 0,
  MG_MSG_INSTANCE = 0,
  MG_MSG_SEVERITY = "",
  MG_MSG_SUPPRESS = "",
  MG_MSG_V4_FORMAT = 0;

ARM7TDMICRFTESTER_inout theinout (A,
    ABE,
    ABORT,
    ALE,
    APE,
    BIGEND,
    BL,
    BREAKPT,
    BUSDIS,
    BUSEN,
    COMMRX,
    COMMTX,
    CPA,
    CPB,
    D,
    D,
    DBE,
    DBGACK,
    DBGEN,
    DBGRQ,
    DBGRQI,
    DIN,
    DOUT,
    DRIVEBS,
    ECAPCLK,
    ECAPCLKBS,
    ECLK,
    EXTERN0,
    EXTERN1,
    HIGHZ,
    ICAPCLKBS,
    IR,
    ISYNC,
    LOCK,
    MAS,
    MCLK,
    nCPI,
    nENIN,
    nENOUT,
    nENOUTI,
    nEXEC,
    nFIQ,
    nHIGHZ,
    nIRQ,
    nM,
    nMREQ,
    nOPC,
    nRESET,
    nRW,
    nTDOEN,
    nTRANS,
    nTRST,
    nWAIT,
    PCLKBS,
    RANGEOUT0,
    RANGEOUT1,
    RSTCLKBS,
    SCREG,
    SDINBS,
    SDOUTBS,
    SEQ,
    SHCLK2BS,
    SHCLKBS,
    TAPSM,
    TBE,
    TBIT,
    TCK,
    TCK1,
    TCK2,
    TDI,
    TDO,
    TMS,
    CRFA,
    CRFABE,
    CRFABORT,
    CRFALE,
    CRFAPE,
    CRFBIGEND,
    CRFBL,
    CRFBREAKPT,
    CRFBUSDIS,
    CRFBUSEN,
    CRFCOMMRX,
    CRFCOMMTX,
    CRFCPA,
    CRFCPB,
    CRFD,
    CRFDBE,
    CRFDBGACK,
    CRFDBGEN,
    CRFDBGRQ,
    CRFDBGRQI,
    CRFDIN,
    CRFDOUT,
    CRFDRIVEBS,
    CRFECAPCLK,
    CRFECAPCLKBS,
    CRFECLK,
    CRFEXTERN0,
    CRFEXTERN1,
    CRFHIGHZ,
    CRFICAPCLKBS,
    CRFIR,
    CRFISYNC,
    CRFLOCK,
    CRFMAS,
    CRFMCLK,
    CRFnCPI,
    CRFnENIN,
    CRFnENOUT,
    CRFnENOUTI,
    CRFnEXEC,
    CRFnFIQ,
    CRFnHIGHZ,
    CRFnIRQ,
    CRFnM,
    CRFnMREQ,
    CRFnOPC,
    CRFnRESET,
    CRFnRW,
    CRFnTDOEN,
    CRFnTRANS,
    CRFnTRST,
    CRFnWAIT,
    CRFPCLKBS,
    CRFRANGEOUT0,
    CRFRANGEOUT1,
    CRFRSTCLKBS,
    CRFSCREG,
    CRFSDINBS,
    CRFSDOUTBS,
    CRFSEQ,
    CRFSHCLK2BS,
    CRFSHCLKBS,
    CRFTAPSM,
    CRFTBE,
    CRFTBIT,
    CRFTCK,
    CRFTCK1,
    CRFTCK2,
    CRFTDI,
    CRFTDO,
    CRFTMS,
    CRFstrobe);

defparam
  theinout.MG_LOGFILE_NAME = MG_LOGFILE_NAME,
  theinout.MG_FORCED_DELAY = MG_FORCED_DELAY,
  theinout.MG_OBJECT = MG_OBJECT,
  theinout.MG_OMI_PATH = MG_OMI_PATH,
  theinout.MG_MSG_TIME = MG_MSG_TIME,
  theinout.MG_MSG_INSTANCE = MG_MSG_INSTANCE,
  theinout.MG_MSG_SEVERITY = MG_MSG_SEVERITY,
  theinout.MG_MSG_SUPPRESS = MG_MSG_SUPPRESS,
  theinout.MG_MSG_V4_FORMAT = MG_MSG_V4_FORMAT;

endmodule

// Model with socket

module ARM7TDMICRFTESTERTOP ();

wire [31:0] A;
wire ABE;
wire ABORT;
wire ALE;
wire APE;
wire BIGEND;
wire [3:0] BL;
wire BREAKPT;
wire BUSDIS;
wire BUSEN;
wire COMMRX;
wire COMMTX;
wire CPA;
wire CPB;
wire [31:0] D;
wire DBE;
wire DBGACK;
wire DBGEN;
wire DBGRQ;
wire DBGRQI;
wire [31:0] DIN;
wire [31:0] DOUT;
wire DRIVEBS;
wire ECAPCLK;
wire ECAPCLKBS;
wire ECLK;
wire EXTERN0;
wire EXTERN1;
wire HIGHZ;
wire ICAPCLKBS;
wire [3:0] IR;
wire ISYNC;
wire LOCK;
wire [1:0] MAS;
wire MCLK;
wire PCLKBS;
wire RANGEOUT0;
wire RANGEOUT1;
wire RSTCLKBS;
wire [3:0] SCREG;
wire SDINBS;
wire SDOUTBS;
wire SEQ;
wire SHCLK2BS;
wire SHCLKBS;
wire [3:0] TAPSM;
wire TBE;
wire TBIT;
wire TCK;
wire TCK1;
wire TCK2;
wire TDI;
wire TDO;
wire TMS;
wire nCPI;
wire nENIN;
wire nENOUT;
wire nENOUTI;
wire nEXEC;
wire nFIQ;
wire nHIGHZ;
wire nIRQ;
wire [4:0] nM;
wire nMREQ;
wire nOPC;
wire nRESET;
wire nRW;
wire nTDOEN;
wire nTRANS;
wire nTRST;
wire nWAIT;

  ARM7TDMICRFTESTER theARM7TDMICRFTESTER (A,
    ABE,
    ABORT,
    ALE,
    APE,
    BIGEND,
    BL,
    BREAKPT,
    BUSDIS,
    BUSEN,
    COMMRX,
    COMMTX,
    CPA,
    CPB,
    D,
    DBE,
    DBGACK,
    DBGEN,
    DBGRQ,
    DBGRQI,
    DIN,
    DOUT,
    DRIVEBS,
    ECAPCLK,
    ECAPCLKBS,
    ECLK,
    EXTERN0,
    EXTERN1,
    HIGHZ,
    ICAPCLKBS,
    IR,
    ISYNC,
    LOCK,
    MAS,
    MCLK,
    nCPI,
    nENIN,
    nENOUT,
    nENOUTI,
    nEXEC,
    nFIQ,
    nHIGHZ,
    nIRQ,
    nM,
    nMREQ,
    nOPC,
    nRESET,
    nRW,
    nTDOEN,
    nTRANS,
    nTRST,
    nWAIT,
    PCLKBS,
    RANGEOUT0,
    RANGEOUT1,
    RSTCLKBS,
    SCREG,
    SDINBS,
    SDOUTBS,
    SEQ,
    SHCLK2BS,
    SHCLKBS,
    TAPSM,
    TBE,
    TBIT,
    TCK,
    TCK1,
    TCK2,
    TDI,
    TDO,
    TMS);

  ARM7TDMI theARM7TDMI (A,
    ABE,
    ABORT,
    ALE,
    APE,
    BIGEND,
    BL,
    BREAKPT,
    BUSDIS,
    BUSEN,
    COMMRX,
    COMMTX,
    CPA,
    CPB,
    D,
    DBE,
    DBGACK,
    DBGEN,
    DBGRQ,
    DBGRQI,
    DIN,
    DOUT,
    DRIVEBS,
    ECAPCLK,
    ECAPCLKBS,
    ECLK,
    EXTERN0,
    EXTERN1,
    HIGHZ,
    ICAPCLKBS,
    IR,
    ISYNC,
    LOCK,
    MAS,
    MCLK,
    nCPI,
    nENIN,
    nENOUT,
    nENOUTI,
    nEXEC,
    nFIQ,
    nHIGHZ,
    nIRQ,
    nM,
    nMREQ,
    nOPC,
    nRESET,
    nRW,
    nTDOEN,
    nTRANS,
    nTRST,
    nWAIT,
    PCLKBS,
    RANGEOUT0,
    RANGEOUT1,
    RSTCLKBS,
    SCREG,
    SDINBS,
    SDOUTBS,
    SEQ,
    SHCLK2BS,
    SHCLKBS,
    TAPSM,
    TBE,
    TBIT,
    TCK,
    TCK1,
    TCK2,
    TDI,
    TDO,
    TMS);

endmodule
