library verilog;
use verilog.vl_types.all;
entity WMASQ is
    port(
        CHTEST          : in     vl_logic;
        ENP             : in     vl_logic;
        LDIRC           : in     vl_logic;
        MCK             : in     vl_logic;
        TI              : in     vl_logic;
        TE              : in     vl_logic;
        XRST            : in     vl_logic;
        SCHON           : in     vl_logic;
        FSYNC           : in     vl_logic;
        START           : in     vl_logic;
        WR1SE           : in     vl_logic;
        WIMEA           : out    vl_logic_vector(8 downto 0);
        CHS             : out    vl_logic_vector(5 downto 0);
        \TO\            : out    vl_logic;
        CHONLE          : out    vl_logic;
        WPWEN           : out    vl_logic;
        WEMLE           : out    vl_logic;
        TSYNC           : out    vl_logic;
        WSCST           : out    vl_logic;
        WR6LE           : out    vl_logic;
        PITLEN          : out    vl_logic;
        WR7LE           : out    vl_logic;
        WMDILE          : out    vl_logic;
        PLCCLE          : out    vl_logic;
        WNLE            : out    vl_logic;
        WAPCEN          : out    vl_logic;
        PITALE          : out    vl_logic;
        W3ICE           : out    vl_logic;
        W2ICE           : out    vl_logic;
        W1ICE           : out    vl_logic;
        PITBLE          : out    vl_logic;
        WADBLE          : out    vl_logic;
        W0ICE           : out    vl_logic;
        WRPEN           : out    vl_logic;
        WRLEN           : out    vl_logic;
        WR0EN           : out    vl_logic;
        WR1EN           : out    vl_logic;
        RPDSEN          : out    vl_logic;
        WSOEN           : out    vl_logic;
        WIMOEN          : out    vl_logic;
        PLCCEN          : out    vl_logic;
        WMADS           : out    vl_logic;
        WAIVEN          : out    vl_logic;
        WCRLE           : out    vl_logic;
        WR5LE           : out    vl_logic;
        WR4LE           : out    vl_logic;
        WR3LE           : out    vl_logic;
        WR2LE           : out    vl_logic;
        WR1LE           : out    vl_logic;
        WR0LE           : out    vl_logic;
        WDRCLE          : out    vl_logic;
        W3LE            : out    vl_logic;
        W2LE            : out    vl_logic;
        W1LE            : out    vl_logic;
        W0LE            : out    vl_logic;
        NSTLE           : out    vl_logic;
        WIMWE           : out    vl_logic;
        WABLE           : out    vl_logic
    );
end WMASQ;
