LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY ADC0 IS
	PORT ( CLK, nRST : IN STD_LOGIC;
	         ADC_D   : BUFFER STD_LOGIC_VECTOR( 11 DOWNTO 0 );
	         nCS     : OUT STD_LOGIC;
	         nRD     : OUT STD_LOGIC;
	         nCONVST : OUT STD_LOGIC;
	         BUSY    : IN STD_LOGIC;
	         ADC_CLK : OUT STD_LOGIC;
	         ADC_WnB : OUT STD_LOGIC;
	         ADC_nWR : OUT STD_LOGIC;
	         
	         LED : OUT STD_LOGIC_VECTOR( 3 DOWNTO 0 );
	          
	          
	          SEG_DAT : OUT STD_LOGIC_VECTOR( 7 DOWNTO 0 );
	          SEG_COM : OUT STD_LOGIC_VECTOR( 3 DOWNTO 0 ));
END ADC0;

ARCHITECTURE RTL OF ADC0 IS 

	CONSTANT SEG_0 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="11111100";
	CONSTANT SEG_1 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="01100000";
	CONSTANT SEG_2 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="11011010";
	CONSTANT SEG_3 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="11110010";
	CONSTANT SEG_4 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="01100110";
	CONSTANT SEG_5 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="10110110";
	CONSTANT SEG_6 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="00111110";
	CONSTANT SEG_7 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="11100000";
	CONSTANT SEG_8 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="11111110";
	CONSTANT SEG_9 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="11100110";
	CONSTANT SEG_A : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="11101110";
	CONSTANT SEG_B : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="00111110";
	CONSTANT SEG_C : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="10011100";
	CONSTANT SEG_D : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="01111010";
	CONSTANT SEG_E : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="10011110";
	CONSTANT SEG_F : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="10001110";
	
	CONSTANT SCAN_0 : STD_LOGIC_VECTOR( 3 DOWNTO 0 ):="1110";
	CONSTANT SCAN_1 : STD_LOGIC_VECTOR( 3 DOWNTO 0 ):="1101";
	CONSTANT SCAN_2 : STD_LOGIC_VECTOR( 3 DOWNTO 0 ):="1011";
	CONSTANT SCAN_3 : STD_LOGIC_VECTOR( 3 DOWNTO 0 ):="0111";

	SIGNAL COUNT : INTEGER RANGE 0 TO 31;
	SIGNAL SMP_CLK : STD_LOGIC;
	SIGNAL DAT_BUF : STD_LOGIC_VECTOR( 11 DOWNTO 0 );
	--SIGNAL CONV_CLK : STD_LOGIC;
	SIGNAL BUSY_EN : STD_LOGIC;
	
	SIGNAL LED_CLK : STD_LOGIC;
	
	
	SIGNAL SEG_BUF : STD_LOGIC_VECTOR( 3 DOWNTO 0 );
	SIGNAL SEG_COM_B : STD_LOGIC_VECTOR( 3 DOWNTO 0 );
	SIGNAL SEG_CLK : STD_LOGIC;
BEGIN
	PROCESS( SMP_CLK ) 
	BEGIN
		IF RISING_EDGE(SMP_CLK) THEN
			SEG_CLK <= NOT SEG_CLK;
		END IF;
	END PROCESS;
	
	PROCESS( SEG_CLK )
	BEGIN
		IF RISING_EDGE(SEG_CLK) THEN
			CASE SEG_COM_B IS
				WHEN SCAN_0 => SEG_COM_B <= SCAN_1;
					       SEG_BUF <= DAT_BUF( 7 DOWNTO 4 );
				WHEN SCAN_1 => SEG_COM_B <= SCAN_2;
					        SEG_BUF <= DAT_BUF( 11 DOWNTO 8 );
				WHEN SCAN_2 => SEG_COM_B <= SCAN_3;
					        SEG_BUF <= ( OTHERS => '0' );
				WHEN OTHERS => SEG_COM_B <= SCAN_0;
									SEG_BUF <= DAT_BUF( 3 DOWNTO 0 );
			END CASE;
		END IF;
	END PROCESS;
	
	SEG_COM <=	SEG_COM_B;

	WITH SEG_BUF SELECT
	SEG_DAT <= SEG_0 WHEN "0000",
		   SEG_1 WHEN "0001",
		   SEG_2 WHEN "0010",
		   SEG_3 WHEN "0011",
		   SEG_4 WHEN "0100",
		   SEG_5 WHEN "0101",
		   SEG_6 WHEN "0110",
		   SEG_7 WHEN "0111",
		   SEG_8 WHEN "1000",
		   SEG_9 WHEN "1001",
		   SEG_A WHEN "1010",
		   SEG_B WHEN "1011",
		   SEG_C WHEN "1100",
		   SEG_D WHEN "1101",
		   SEG_E WHEN "1110",
		   SEG_F WHEN OTHERS;

	PROCESS( SMP_CLK, nRST )
		VARIABLE CNT : INTEGER RANGE 0 TO 125;
	BEGIN
		IF nRST='0' THEN
			CNT := 0;
			LED_CLK <= '0';
		ELSIF RISING_EDGE(SMP_CLK) THEN
			IF CNT=125 THEN
				CNT := 0;
				LED_CLK <= NOT LED_CLK;
			ELSE
				CNT := CNT + 1;
			END IF;
		END IF;
	END PROCESS;
	
	PROCESS( LED_CLK, nRST )
		VARIABLE LED_B : STD_LOGIC_VECTOR( 3 DOWNTO 0 );
	BEGIN
		IF nRST='0' THEN
			LED_B := (OTHERS => '1');
		ELSIF RISING_EDGE(LED_CLK) THEN
			IF LED_B="1111" THEN
				LED_B := "1110";
			ELSE
				IF (BUSY='0') THEN
					LED_B := LED_B( 2 DOWNTO 0 ) & LED_B(3);
				END IF;
			END IF;
			LED <= LED_B;
		END IF;
	END PROCESS;


	ADC_CLK <= SMP_CLK WHEN (BUSY_EN='1') ELSE '1';
	
	PROCESS( CLK, nRST )
		VARIABLE CNT : INTEGER RANGE 0 TO 1251;--1KHZ
	BEGIN
		IF nRST='0' THEN
			CNT := 0;
			SMP_CLK <= '0';
		ELSIF RISING_EDGE(CLK) THEN
			IF CNT< 1250 THEN
				CNT := CNT + 1;
			ELSE
				CNT := 0;
				SMP_CLK <= NOT SMP_CLK;
			END IF;
		END IF;
	END PROCESS;
	
	PROCESS(SMP_CLK, nRST )
	BEGIN
		IF nRST='0' THEN
			COUNT <= 0;
		ELSIF RISING_EDGE(SMP_CLK) THEN
			IF COUNT < 30 THEN
				COUNT <= COUNT + 1;
			ELSE
				COUNT <= 0;
			END IF;
		END IF;
	END PROCESS;
			
	PROCESS( SMP_CLK, nRST )
		VARIABLE EN : STD_LOGIC;
	BEGIN
		IF nRST='0' THEN
			--COUNT <= 0;
			nCONVST <= '1';
			BUSY_EN <= '0';
			nCS <= '1';
			nRD <= '1';
			DAT_BUF <= ( OTHERS => '0' );
			EN := '0';
			ADC_nWR <= '1';
			ADC_WnB <= '1';
		ELSIF RISING_EDGE(SMP_CLK) THEN
			IF EN='0' THEN
				ADC_WnB <= '1';
				CASE COUNT IS
					WHEN 3 => nCS <= '0'; 
					WHEN 4 => ADC_nWR <= '0';
					WHEN 5 => ADC_D <= "000000000001";
					WHEN 6 => ADC_nWR <= '1';
					WHEN 7 => nCS <= '1';
					WHEN 9 => nCS <= '0';
					WHEN 10 => ADC_nWR <= '0';
					WHEN 11 => ADC_D <= "000000000001";
					WHEN 12 => ADC_nWR <= '1';
					WHEN 13 => nCS <= '1'; 
					WHEN 29 => EN := '1';
					WHEN OTHERS => NULL;
				END CASE;
			ELSE
						ADC_WnB <= '1';
			CASE COUNT IS
			--stan-by
				WHEN 0 => --COUNT <= COUNT + 1;
				          nCONVST <= '1';
					  BUSY_EN <= '0';
					  nCS <= '1';
					  nRD <= '1';
			--ADC Data Convert
				WHEN 1 => --COUNT <= COUNT + 1;
				          nCONVST <= '0';
					  BUSY_EN <= '1';
					  nCS <= '1';
					  nRD <= '1';
			--CONVERTTING					  
				WHEN 14 =>  nCONVST <= '1';
								BUSY_EN <= '0';
				WHEN 15 => nCS <= '0';
				WHEN 16 => nRD <= '0';
				WHEN 17 => DAT_BUF <= ADC_D;
				WHEN 18 => nRD <= '1';
				WHEN 19 => nCS <= '1';
				WHEN OTHERS => NULL;
			END CASE;
		END IF;
		END IF;
	END PROCESS;
END RTL;