LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY ADC0 IS
	PORT ( CLK, nRST : IN STD_LOGIC;
	         ADC_D   : INOUT STD_LOGIC_VECTOR( 11 DOWNTO 0 );
	         nCS     : OUT STD_LOGIC;
	         nRD     : OUT STD_LOGIC;
	         nCONVST : OUT STD_LOGIC;
	         BUSY    : IN STD_LOGIC;
	         ADC_CLK : OUT STD_LOGIC;
	         ADC_WnB : OUT STD_LOGIC;
	         ADC_nWR : OUT STD_LOGIC;
	         
	         LED : OUT STD_LOGIC_VECTOR( 3 DOWNTO 0 );
	          
	          
	          SEG_DAT : OUT STD_LOGIC_VECTOR( 7 DOWNTO 0 );
	          SEG_COM : OUT STD_LOGIC_VECTOR( 3 DOWNTO 0 ));
END ADC0;

ARCHITECTURE RTL OF ADC0 IS 

	CONSTANT SEG_0 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="11111100";
	CONSTANT SEG_1 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="01100000";
	CONSTANT SEG_2 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="11011010";
	CONSTANT SEG_3 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="11110010";
	CONSTANT SEG_4 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="01100110";
	CONSTANT SEG_5 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="10110110";
	CONSTANT SEG_6 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="00111110";
	CONSTANT SEG_7 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="11100000";
	CONSTANT SEG_8 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="11111110";
	CONSTANT SEG_9 : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="11100110";
	CONSTANT SEG_A : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="11101110";
	CONSTANT SEG_B : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="00111110";
	CONSTANT SEG_C : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="10011100";
	CONSTANT SEG_D : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="01111010";
	CONSTANT SEG_E : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="10011110";
	CONSTANT SEG_F : STD_LOGIC_VECTOR( 7 DOWNTO 0 ):="10001110";
	
	CONSTANT SCAN_0 : STD_LOGIC_VECTOR( 3 DOWNTO 0 ):="1110";
	CONSTANT SCAN_1 : STD_LOGIC_VECTOR( 3 DOWNTO 0 ):="1101";
	CONSTANT SCAN_2 : STD_LOGIC_VECTOR( 3 DOWNTO 0 ):="1011";
	CONSTANT SCAN_3 : STD_LOGIC_VECTOR( 3 DOWNTO 0 ):="0111";

	SIGNAL COUNT : INTEGER RANGE 0 TO 60;--56
	SIGNAL SMP_CLK : STD_LOGIC;
	SIGNAL DAT_BUF : STD_LOGIC_VECTOR( 11 DOWNTO 0 );
	--SIGNAL CONV_CLK : STD_LOGIC;
	--SIGNAL BUSY_EN : STD_LOGIC;
	
	SIGNAL LED_CLK : STD_LOGIC;
	
	
	SIGNAL SEG_BUF : STD_LOGIC_VECTOR( 3 DOWNTO 0 );
	SIGNAL SEG_COM_B : STD_LOGIC_VECTOR( 3 DOWNTO 0 );
	SIGNAL SEG_CLK : STD_LOGIC;
	
	SIGNAL DIR_SIG : STD_LOGIC;
	SIGNAL D_IN, D_OUT : STD_LOGIC_VECTOR( 11 DOWNTO 0 );
	SIGNAL SEG1, SEG2, SEG3 : STD_LOGIC_VECTOR( 3 DOWNTO 0 );
	SIGNAL LATCH_EN : STD_LOGIC;
BEGIN
	PROCESS( SMP_CLK ) 
	BEGIN
		IF RISING_EDGE(SMP_CLK) THEN
			SEG_CLK <= NOT SEG_CLK;
		END IF;
	END PROCESS;
	
	PROCESS( SEG_CLK )
	BEGIN
		IF RISING_EDGE(SEG_CLK) THEN
			CASE SEG_COM_B IS
				WHEN SCAN_0 => SEG_COM_B <= SCAN_1;
					       SEG_BUF <= SEG1;
				WHEN SCAN_1 => SEG_COM_B <= SCAN_2;
					        SEG_BUF <= SEG2;
				WHEN SCAN_2 => SEG_COM_B <= SCAN_3;
					        SEG_BUF <= ( OTHERS => '0' );
				WHEN OTHERS => SEG_COM_B <= SCAN_0;
									SEG_BUF <= SEG3;
			END CASE;
		END IF;
	END PROCESS;
	SEG1 <= DAT_BUF( 7 DOWNTO 4 );
	SEG2 <= DAT_BUF( 11 DOWNTO 8 );
	SEG3 <= DAT_BUF( 3 DOWNTO 0 );
	SEG_COM <=	SEG_COM_B;

	WITH SEG_BUF SELECT
	SEG_DAT <= SEG_0 WHEN "0000",
		   SEG_1 WHEN "0001",
		   SEG_2 WHEN "0010",
		   SEG_3 WHEN "0011",
		   SEG_4 WHEN "0100",
		   SEG_5 WHEN "0101",
		   SEG_6 WHEN "0110",
		   SEG_7 WHEN "0111",
		   SEG_8 WHEN "1000",
		   SEG_9 WHEN "1001",
		   SEG_A WHEN "1010",
		   SEG_B WHEN "1011",
		   SEG_C WHEN "1100",
		   SEG_D WHEN "1101",
		   SEG_E WHEN "1110",
		   SEG_F WHEN OTHERS;

	PROCESS( SMP_CLK, nRST )
		VARIABLE CNT : INTEGER RANGE 0 TO 125;
	BEGIN
		IF nRST='0' THEN
			CNT := 0;
			LED_CLK <= '0';
		ELSIF RISING_EDGE(SMP_CLK) THEN
			IF CNT=125 THEN
				CNT := 0;
				LED_CLK <= NOT LED_CLK;
			ELSE
				CNT := CNT + 1;
			END IF;
		END IF;
	END PROCESS;
	
	PROCESS( LED_CLK, nRST, BUSY )
		VARIABLE LED_B : STD_LOGIC_VECTOR( 3 DOWNTO 0 );
		VARIABLE CNT : INTEGER RANGE 0 TO 1562500;
	BEGIN
		IF nRST='0' THEN
			LED_B := (OTHERS => '1');
			CNT := 0;
		ELSIF RISING_EDGE(LED_CLK) THEN
			IF LED_B="1111" THEN
				LED_B := "1110";
			ELSE
				IF CNT=1562500 THEN
					LED_B := LED_B( 2 DOWNTO 0 ) & '0';
					CNT := 0;
				ELSE
					CNT := CNT + 1;
				END IF;				
			END IF;
			LED <= LED_B;
		END IF;
	END PROCESS;


	--ADC_CLK <= SMP_CLK WHEN (BUSY_EN='1') ELSE '1';
	
	PROCESS( CLK, nRST )
		VARIABLE CNT : INTEGER RANGE 0 TO 626;--10KHZ
	BEGIN
		IF nRST='0' THEN
			CNT := 0;
			SMP_CLK <= '0';
		ELSIF RISING_EDGE(CLK) THEN
			IF CNT< 625 THEN
				CNT := CNT + 1;
			ELSE
				CNT := 0;
				SMP_CLK <= NOT SMP_CLK;
			END IF;
		END IF;
	END PROCESS;
	
	PROCESS(SMP_CLK, nRST )
	BEGIN
		IF nRST='0' THEN
			COUNT <= 0;
		ELSIF RISING_EDGE(SMP_CLK) THEN
			IF COUNT < 59 THEN
				COUNT <= COUNT + 1;
			ELSE
				COUNT <= 0;
			END IF;
		END IF;
	END PROCESS;
			
	ADC_WnB <= '1'; --WORD(12BIT) MODE
---  BUS CONTROLL -------------------------------------------
--ADC OUTPUT-MODE	
	ADC_D <= D_OUT WHEN ( DIR_SIG= '1' ) ELSE ( OTHERS => 'Z' );
--ADC INPUT-MODE	
	PROCESS( LATCH_EN )
	BEGIN
		IF LATCH_EN= '1' THEN
			IF DIR_SIG = '0' THEN 
				D_IN <= ADC_D;
			END IF;
		END IF;
	END PROCESS; 
-------------------------------------------------------------
	
	PROCESS( CLK, nRST )
		VARIABLE EN : STD_LOGIC;
	BEGIN
		IF nRST='0' THEN
			nCONVST <= '1';
			nCS <= '1';
			nRD <= '1'; 
			ADC_CLK <= '1';
			ADC_nWR <= '1';
			EN := '0';
	 ELSIF RISING_EDGE(CLK) THEN
		IF EN = '0' THEN
			CASE COUNT IS
				WHEN 2 => nCS <= '0';
				WHEN 4 => ADC_nWR <= '0';
						    DIR_SIG <= '1';
				WHEN 6 => D_OUT <=   "00" 	&	 '0'		& '0' & "011" & "00" & "00" & '0';
				WHEN 7 => ADC_nWR <= '1';
				WHEN 8 => DIR_SIG <= '0';
				WHEN 10 => nCS <= '1';
				WHEN 55 => EN := '1';
				WHEN OTHERS => NULL;
			END CASE;
		ELSE
			CASE COUNT IS
			----- SAMPLLING
				WHEN 1 => nCONVST <= '0';
				WHEN 2 => ADC_CLK <= '0';
				WHEN 3 => ADC_CLK <= '1'; --1CLK
				WHEN 4 => ADC_CLK <= '0';
				WHEN 5 => ADC_CLK <= '1'; --2CLK
				WHEN 6 => ADC_CLK <= '0';
				WHEN 7 => ADC_CLK <= '1'; --3CLK
				WHEN 8 => ADC_CLK <= '0';
				WHEN 9 => ADC_CLK <= '1'; --4CLK
				WHEN 10 => ADC_CLK <= '0';
				WHEN 11 => ADC_CLK <= '1'; --5CLK
				WHEN 12 => ADC_CLK <= '0';
				WHEN 13 => ADC_CLK <= '1'; --6CLK
				WHEN 14 => ADC_CLK <= '0';
				WHEN 15 => ADC_CLK <= '1'; --7CLK
				WHEN 16 => ADC_CLK <= '0';
				WHEN 17 => ADC_CLK <= '1'; --8CLK
				WHEN 18 => ADC_CLK <= '0';
				WHEN 19 => ADC_CLK <= '1'; --9CLK
				WHEN 20 => ADC_CLK <= '0';
				WHEN 21 => ADC_CLK <= '1'; --10CLK
				WHEN 22 => ADC_CLK <= '0';
				WHEN 23 => ADC_CLK <= '1'; --11CLK
				WHEN 24 => ADC_CLK <= '0';
				WHEN 25 => ADC_CLK <= '1'; --12CLK
				WHEN 26 => ADC_CLK <= '0';
				WHEN 27 => ADC_CLK <= '1'; --13CLK
				WHEN 28 => ADC_CLK <= '0';
				WHEN 29 => ADC_CLK <= '1'; --14CLK
						     nCONVST <= '1';
				-------- DATA CAPTURE
				WHEN 40 => nCS <= '0';
				WHEN 42 => nRD <= '0'; 
				WHEN 43 => LATCH_EN <= '1';
				WHEN 44 => LATCH_EN <= '0';
				WHEN 45 => DAT_BUF <= D_IN;
				WHEN 46 => nRD <= '1';
				WHEN 48 => nCS <= '1';
--				WHEN 50 => 
--				WHEN 52 => 
--				WHEN 54 => 
				WHEN OTHERS => NULL;
			END CASE;
		END IF;
	END IF;
END PROCESS;	
		
			
			
		
		



END RTL;