library verilog;
use verilog.vl_types.all;
entity mmc_apbregisterif is
    port(
        pclk            : in     vl_logic;
        presetn         : in     vl_logic;
        psel            : in     vl_logic;
        penable         : in     vl_logic;
        pwrite          : in     vl_logic;
        paddr           : in     vl_logic_vector(6 downto 2);
        pwdata          : in     vl_logic_vector(31 downto 0);
        prdata          : out    vl_logic_vector(31 downto 0);
        sdreset         : out    vl_logic;
        enclk           : out    vl_logic;
        psaveon         : out    vl_logic;
        isdipre         : out    vl_logic_vector(7 downto 0);
        cmdarg          : out    vl_logic_vector(31 downto 0);
        isdicmdcon      : out    vl_logic_vector(12 downto 0);
        cmst            : out    vl_logic;
        cmstclr         : in     vl_logic;
        rspcrcset       : in     vl_logic;
        cmdsentset      : in     vl_logic;
        cmdtoutset      : in     vl_logic;
        rspfinset       : in     vl_logic;
        cmdon           : in     vl_logic;
        rspindex        : in     vl_logic_vector(7 downto 0);
        response0       : in     vl_logic_vector(31 downto 0);
        response1       : in     vl_logic_vector(31 downto 0);
        response2       : in     vl_logic_vector(31 downto 0);
        response3       : in     vl_logic_vector(31 downto 0);
        idatatimer      : out    vl_logic_vector(22 downto 0);
        iblksize        : out    vl_logic_vector(15 downto 0);
        isdidatcon      : out    vl_logic_vector(30 downto 0);
        dtst            : out    vl_logic;
        dtstclr         : in     vl_logic;
        blknumcnt       : in     vl_logic_vector(15 downto 0);
        blkcnt          : in     vl_logic_vector(15 downto 0);
        nobusyset       : in     vl_logic;
        crcstaset       : in     vl_logic;
        datcrcset       : in     vl_logic;
        dattoutset      : in     vl_logic;
        datfinset       : in     vl_logic;
        busyfinset      : in     vl_logic;
        txdaton         : in     vl_logic;
        rxdaton         : in     vl_logic;
        frst            : out    vl_logic;
        fffailset       : in     vl_logic;
        tfdet           : in     vl_logic;
        rfdet           : in     vl_logic;
        tfhalf          : in     vl_logic;
        tfempty         : in     vl_logic;
        rffull          : in     vl_logic;
        rfhalf          : in     vl_logic;
        ffcnt           : in     vl_logic_vector(4 downto 0);
        txwriteen       : out    vl_logic;
        rxrdptrinc      : out    vl_logic;
        fifodata        : in     vl_logic_vector(31 downto 0);
        delaysel        : out    vl_logic_vector(2 downto 0);
        invsel          : out    vl_logic;
        rcmdstart       : out    vl_logic;
        rcmdstartclr    : in     vl_logic;
        iautoreadcon    : out    vl_logic_vector(1 downto 0);
        errorstate      : in     vl_logic_vector(1 downto 0);
        responsecmd18   : in     vl_logic_vector(31 downto 0);
        autoreadcomplete: in     vl_logic;
        mmc_int         : out    vl_logic
    );
end mmc_apbregisterif;
