library verilog;
use verilog.vl_types.all;
entity dma64ahb is
    port(
        rstpci          : in     vl_logic;
        clkpci          : in     vl_logic;
        t_width64       : in     vl_logic;
        t_hit           : in     vl_logic;
        t_we            : in     vl_logic;
        irdynid         : in     vl_logic;
        trdynid         : in     vl_logic;
        m_nextd         : in     vl_logic;
        m_rejd          : in     vl_logic;
        m_aack          : in     vl_logic;
        m_aack64        : in     vl_logic;
        m_tretry        : in     vl_logic;
        m_tabort        : in     vl_logic;
        m_abort         : in     vl_logic;
        m_otcmd         : in     vl_logic;
        m_otdata        : in     vl_logic;
        adi             : in     vl_logic_vector(63 downto 0);
        t_addr          : in     vl_logic_vector(15 downto 0);
        t_ben           : in     vl_logic_vector(7 downto 0);
        ahbaddr         : in     vl_logic_vector(5 downto 0);
        dout_ahb        : out    vl_logic_vector(31 downto 0);
        din_dmaregs     : in     vl_logic_vector(63 downto 0);
        dout_dmaregs    : out    vl_logic_vector(63 downto 0);
        t_drdy          : out    vl_logic;
        m_lastd         : out    vl_logic;
        m_drdy          : out    vl_logic;
        m_areq          : out    vl_logic;
        m_areq64        : out    vl_logic;
        m_crw           : out    vl_logic;
        ado             : out    vl_logic_vector(63 downto 0);
        m_cbe           : out    vl_logic_vector(7 downto 0);
        hclk            : in     vl_logic;
        hresetn         : in     vl_logic;
        iaddr           : out    vl_logic_vector(31 downto 0);
        iben            : out    vl_logic_vector(3 downto 0);
        itxinit         : out    vl_logic;
        iwr             : out    vl_logic;
        iburst          : out    vl_logic;
        iprefetch       : out    vl_logic_vector(3 downto 0);
        idrdy           : in     vl_logic;
        itxerr          : in     vl_logic;
        itxidle         : in     vl_logic;
        wbae            : out    vl_logic;
        wbte            : out    vl_logic;
        wbrd            : in     vl_logic;
        rbaf            : out    vl_logic;
        rbtf            : out    vl_logic;
        rbwr            : in     vl_logic;
        rbdin           : in     vl_logic_vector(31 downto 0);
        wbdout          : out    vl_logic_vector(31 downto 0);
        dma_txdone      : out    vl_logic;
        dma_pcierr      : out    vl_logic;
        dma_ahberr      : out    vl_logic
    );
end dma64ahb;
