library verilog;
use verilog.vl_types.all;
entity pcim64ahbw is
    port(
        clk_p           : in     vl_logic;
        rstn_p          : in     vl_logic;
        idsel_p         : in     vl_logic;
        gntn_p          : in     vl_logic;
        reqn_p          : out    vl_logic;
        intan_p         : out    vl_logic;
        serrn_p         : out    vl_logic;
        par_p           : inout  vl_logic;
        par64_p         : inout  vl_logic;
        framen_p        : inout  vl_logic;
        req64n_p        : inout  vl_logic;
        irdyn_p         : inout  vl_logic;
        trdyn_p         : inout  vl_logic;
        devseln_p       : inout  vl_logic;
        ack64n_p        : inout  vl_logic;
        stopn_p         : inout  vl_logic;
        perrn_p         : inout  vl_logic;
        ad_p            : inout  vl_logic_vector(63 downto 0);
        cbe_p           : inout  vl_logic_vector(7 downto 0);
        hclk            : in     vl_logic;
        hresetn         : in     vl_logic;
        mhaddr          : out    vl_logic_vector(31 downto 0);
        mhbusreq        : out    vl_logic;
        mhlock          : out    vl_logic;
        mhgrant         : in     vl_logic;
        mhwrite         : out    vl_logic;
        mhtrans         : out    vl_logic_vector(1 downto 0);
        mhsize          : out    vl_logic_vector(2 downto 0);
        mhprot          : out    vl_logic_vector(3 downto 0);
        mhburst         : out    vl_logic_vector(2 downto 0);
        mhready         : in     vl_logic;
        mhresp          : in     vl_logic_vector(1 downto 0);
        mhrdata         : in     vl_logic_vector(31 downto 0);
        mhwdata         : out    vl_logic_vector(31 downto 0);
        shsel           : in     vl_logic;
        shwrite         : in     vl_logic;
        shtrans         : in     vl_logic_vector(1 downto 0);
        shsize          : in     vl_logic_vector(2 downto 0);
        shburst         : in     vl_logic_vector(2 downto 0);
        shaddr          : in     vl_logic_vector(31 downto 0);
        shready         : out    vl_logic;
        shresp          : out    vl_logic_vector(1 downto 0);
        shrdata         : out    vl_logic_vector(31 downto 0);
        shwdata         : in     vl_logic_vector(31 downto 0);
        hint            : out    vl_logic
    );
end pcim64ahbw;
