onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/PCLK
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/PRESETn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/PADDR
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/PSEL
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/PENABLE
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/PWRITE
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/PRDATA
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFBootPinIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/IOWidthPinIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NandWidthPinIn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/BootCfgPinIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/OutDtmnPinIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/IntReqOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFCtrlBusyIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFStatValidIn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFStatusIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/WrEndIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/RdEndIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/RdFIFOReadyIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/WrFIFOReadyIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/FiltRnB1In
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/FiltRnB0In
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/FIFOFlushIn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/FIFORdDataOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/FIFORdDataEnIn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/FIFOWrDataIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/FIFOWrDataEnIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/BeforeFullOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/FIFORdReadyOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/FIFOFullOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/FIFOHalfFullOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/FIFOEmpty0Out
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/FIFOEmpty1Out
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/WrRdyOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/RdRdyOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFOpRdEnIn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFOpOut
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/QLevelOut
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/ControlOut0
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/ControlOut1
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/ConfigOut0
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/ConfigOut1
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/ConfigOut2
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PCLK
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PRESETn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PADDR
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PSEL
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PENABLE
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PWRITE
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PRDATA
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFBootPinIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/IOWidthPinIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NandWidthPinIn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/BootCfgPinIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/OutDtmnPinIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/IntReqOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFCtrlBusyIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFStatValidIn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFStatusIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/WrEndIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/RdEndIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/RdFIFOReadyIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/WrFIFOReadyIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FiltRnB1In
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FiltRnB0In
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFOFlushIn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFORdDataOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFORdDataEnIn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFOWrDataIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFOWrDataEnIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/BeforeFullOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFORdReadyOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFOFullOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFOHalfFullOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFOEmpty0Out
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFOEmpty1Out
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/WrRdyOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/RdRdyOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFOpRdEnIn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFOpOut
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/QLevelOut
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/ControlOut0
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/ControlOut1
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/ConfigOut0
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/ConfigOut1
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/ConfigOut2
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFOPER0
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFOPER1
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFOPER2
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFOPER3
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFCONF0
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFCONF1
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFCONF2
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFCTRL0
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFCTRL1
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFSTAT0
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFSTAT1
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFSTAT2
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFSTAT3
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFFIFOSTAT0
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFFIFOSTAT1
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/QLevel
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/Timing0
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/Timing1
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/Ctrl0
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/Ctrl1
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFStatValid
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/WrEnd
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/RdEnd
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/RnBDetect1
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/RnBDetect0
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/RnB1
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/RnB0
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFOLevel
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFOWrEn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFORdEn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFOWrData
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFORdData
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/QWrData
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFOWrCnt
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFORdCnt
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFOWrCollect
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFOData
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/DivRdEn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/NFCtrlRst
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/APBWriteEn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/APBReadEn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/QWrEn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFORst
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFOCnt1
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/FIFOCnt0
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/WrEnd_Dly
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/RdEnd_Dly
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/WrFIFOReady_Dly
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/RdFIFOReady_Dly
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/RnB1_Dly
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/RnB0_Dly
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/Timing_conf0
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/Timing_conf1
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/Control0
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/Control1
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PCLK
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PRESETn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PADDR
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PSEL
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PENABLE
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PWRITE
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PRDATA
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/QWrCnt
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFCmdQ/Clk
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFCmdQ/nRst
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFCmdQ/NFCtrlRstIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFCmdQ/QWrEnIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFCmdQ/QRdEnIn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFCmdQ/QWrDataIn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFCmdQ/QRdDataOut
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFCmdQ/QLevelOut
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFCmdQ/WrPtr
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFCmdQ/RdPtr
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFCmdQ/QCnt
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFCmdQ/QFull
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFCmdQ/QEmpty
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PCLK
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PRESETn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PADDR
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PSEL
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PENABLE
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PWRITE
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/PRDATA
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/Clk
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/nRst
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFOFlushIn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFOLevelIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFOWrEnIn
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFORdEnIn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFOWrDataIn
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFORdDataOut
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFOCnt1
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFOCnt0
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/WrRdyOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/RdRdyOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/BeforeFullOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFOFullOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFOHalfFullOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFORdReadyOut
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFOEmpty1Out
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFOEmpty0Out
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/WrPtr0
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/WrPtr1
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/RdPtr0
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/RdPtr1
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/Level
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFOSelRd
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFOSelWr
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFOFull0
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFOFull1
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFOEmpty0
add wave -noupdate -format Logic -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/FIFOEmpty1
add wave -noupdate -format Literal -radix hexadecimal /Tb_NFAPBIF/NFAPBIF/uNFDFIFO/i
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {80000 ps} 0}
configure wave -namecolwidth 337
configure wave -valuecolwidth 55
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
update
WaveRestoreZoom {0 ps} {635462 ps}
