onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/ARESETB
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/nPOR
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/MCLK
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/nMCLK
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/ACLK
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/nACLK
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/AWAddr
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/AWId
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/AWLen
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/AWBurst
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/AWValid
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/AWReady
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WLast
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WStrb
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WId
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WData
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WValid
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WReady
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/BId
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/BResp
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/BReady
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/BValid
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/ARAddr
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/ARId
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/ARLen
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/ARBurst
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/ARValid
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/ARReady
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RReady
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RLast
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RValid
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RData
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RId
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RResp
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RQFull
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WQFull
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/BA_STS
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/BA_REQ
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/BA_AA
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/BA_TT
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/BA_ID
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/BA_RW
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/BA_PM
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/SD_DQE
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/SD_DQI
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/SD_DQO
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/SD_DQM
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/SD_DQSE
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/SD_DQSO
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/SD_DQSI
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RdDataMem
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/iDelayReadFlag
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RdDataRdy
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/iDelayReadLast
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RdLastMem
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/iDelayReadId
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RdIdMem
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/DiValid
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/DoValid
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/QueEmp
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/QueFul
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/QueErr
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RdLast
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RdId
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/DqsoValid
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/ColAddrSiz
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RdDataInSel
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RdDataPol
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WriteLatA0
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WriteLatAA
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WriteLatTT
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WriteLatID
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WriteLatBB
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/ReadLatA0
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/ReadLatAA
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/ReadLatTT
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/ReadLatID
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/ReadLatBB
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/AckMem
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WQWrite
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WQRead
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/iWQRead
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WQHFull
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WQEmpty
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WQWrData
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WQRdData
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WBLQWrite
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WBLQRead
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/iWBLQRead
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WBLQFull
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WBLQHFull
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WBLQEmpty
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WBLQWrData
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WBLQRdData
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RQWrite
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RQRead
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/iRQRead
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RQHFull
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RQEmpty
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RQWrData
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RQRdData
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RBLQWrite
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RBLQRead
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/iRBLQRead
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RBLQFull
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RBLQHFull
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RBLQEmpty
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RBLQWrData
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RBLQRdData
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/tWIdle
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/tWWDat
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/tWWAck
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/tWWReq
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/tWWSpi
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/tRIdle
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/tRRReq
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/tRRSpi
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/CurStRD
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/NxtStRD
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/tRDIdle
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/tRDReq
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/nRDIdle
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/nRDReq
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WriteAck
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/ReadAck
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/PageEnd
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WSpilitCon
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WIncMisCon
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WIncMisCal
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WPageMisCon
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WPageMisCal
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WSpi2Addr
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WSpi2Len
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WSpi1Addr
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WSpi1Len
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RSpilitCon
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RIncMisCon
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RIncMisCal
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RPageMisCon
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RPageMisCal
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RSpi2Addr
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RSpi2Len
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RSpi1Addr
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RSpi1Len
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WriteReqAA
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WriteReqTT
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WriteReqID
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WriteReqRW
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WriteRequest
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/ReadReqAA
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/ReadReqTT
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/ReadReqID
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/ReadReqRW
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/ReadRequest
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/iARReady
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/iAWReady
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/iWReady
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/iWValid
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/iARValid
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/iAWValid
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WDatAck
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RespAck
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WrWrapAALow
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WBurstCnt
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/LatchedWBL
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WrWrapCnt
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WrWrapAddrSt
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WQIncAddr
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/NxtWrDt
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/NxtDQSEnOut
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/NxtDQSOut
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/NxtDqsSel
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/NxtDQM
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/DQMACLKQ
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/WrDtACLKQ
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/DataEnOutQ
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/DataEnOutQ2
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/DataEnOutACLKQ
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/PosedgeSyncACLK
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/UHalfWrdFtch
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/NxtUHalfWrdFtch
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/FtchdHWQ
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/FtchdHWQ2
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/NxtFtchdHW
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/HWMaskQ
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/HWMaskQ2
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/NxtHWMask
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/DqsSel
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/DQSOut
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/DQSOutGen
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/DqsCnt
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WQDataValid
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RdWrapAALow
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/SD_DQSI0
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/SD_DQSI1
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/nSD_DQSI0
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/nSD_DQSI1
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RData1stStgLo
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RData1stStgHi
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RDatanACLK
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RData2ndStg
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/R16Data
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/NxtR16Data
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RData1stStg
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/NxtRData2ndStg
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RBurstCnt
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RBLCnt
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/LatchedRBL
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RdWrapCnt
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RdWrapAddrSt
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RdWrapEn
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/RdWrapArround
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RdLastCnt
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/SDRTop/SDRAi/RQIncAddr
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/ReadCntEnd
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/ReadDatEn
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/IncRdLastCnt
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/DecRdLastCnt
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/WriteReq
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/SDRTop/SDRAi/ReadReq
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/sdram16bit/Addr
add wave -noupdate -format Literal -radix unsigned /TbLCD/sdram16bit/Ba
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/sdram16bit/Cke
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/sdram16bit/Clk
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/sdram16bit/Cs_n
add wave -noupdate -format Logic /TbLCD/sdram16bit/Ras_n
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/sdram16bit/Cas_n
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/sdram16bit/Dm
add wave -noupdate -format Logic -height 15 -radix hexadecimal {/TbLCD/sdram16bit/Dqs[0]}
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/sdram16bit/Dq
add wave -noupdate -format Logic /TbLCD/SDdate
add wave -noupdate -format Logic /TbLCD/SDdqse
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/sdram16bit/Dqs
add wave -noupdate -format Logic /TbLCD/sdram16bit/Write_enable
add wave -noupdate -format Logic /TbLCD/sdram16bit/wdqs_valid
add wave -noupdate -format Logic /TbLCD/sdram16bit/Read_enable
add wave -noupdate -format Logic /TbLCD/sdram16bit/Prech_enable
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/AW
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/AWBURST
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/AWID
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/AWSIZE
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/AWREADY
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/AWVALID
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/WID
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/WLAST
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/WREADY
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/WVALID
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/WDATA
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/BRESP
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/BREADY
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/BVALID
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/ARBURST
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/ARESETB
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/ARESETn
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/ARID
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/ARLEN
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/ARSIZE
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/ARVALID
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/RID
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/RRESP
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/RREADY
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/RVALID
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/RLAST
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/RDATA
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PCLK
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PRESETB
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/PADDR
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PSEL
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PWRITE
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PENABLE
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/PRDATA
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/DmReg/GPalMemRdAddr
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/DmReg/GPalMemRead
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/DmReg/GPalMemWrAddr
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/DmReg/GPalMemWrData
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/DmReg/GPalMemWrite
add wave -noupdate -format Literal -radix unsigned /TbLCD/PalMemData
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmReg/PalMemWrAddr
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmReg/PalMemWrData
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/DmReg/PalMemWrite
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/GraphicPlane/PalMemAddr
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/GraphicPlane/PalMemRdAddrInt
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/GraphicPlane/PalMemRdData
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/GraphicPlane/PalMemRead
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/GraphicPlane/PalMemReadAll
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/GraphicPlane/PalMemReadInt
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/GraphicPlane/PalMemWrAddr
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/GraphicPlane/PalMemWrData
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/GraphicPlane/PalMemWrite
add wave -noupdate -format Logic /TbLCD/DmTop/GraphicPlane/PaletteMem/clk
add wave -noupdate -format Logic /TbLCD/DmTop/GraphicPlane/PaletteMem/rst
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/GraphicPlane/PaletteMem/addr
add wave -noupdate -format Logic /TbLCD/DmTop/GraphicPlane/PaletteMem/ce
add wave -noupdate -format Logic /TbLCD/DmTop/GraphicPlane/PaletteMem/we
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicPlane/PaletteMem/di
add wave -noupdate -format Logic /TbLCD/DmTop/GraphicPlane/PaletteMem/oe
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicPlane/PaletteMem/do
add wave -noupdate -format Logic /TbLCD/DmTop/DmReg/CDMAOverRun
add wave -noupdate -format Logic /TbLCD/DmTop/DmReg/CDMAOverRunD
add wave -noupdate -format Logic /TbLCD/DmTop/DmReg/CDMAOverRunPCLK
add wave -noupdate -format Logic /TbLCD/DmTop/DmReg/CDMAOverRunSts
add wave -noupdate -format Logic /TbLCD/DmTop/DmErrInt
add wave -noupdate -format Logic /TbLCD/DmTop/LCDCLK
add wave -noupdate -format Logic /TbLCD/DmTop/LCDVSync
add wave -noupdate -format Logic /TbLCD/DmTop/LCDHSync
add wave -noupdate -format Logic /TbLCD/DmTop/LCDDataEn
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/LCDData
add wave -noupdate -format Logic /TbLCD/DmTop/DmARIf/ACLK
add wave -noupdate -format Logic /TbLCD/DmTop/DmARIf/ARESETn
add wave -noupdate -format Literal /TbLCD/DmTop/DmARIf/ARID
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/ARADDR
add wave -noupdate -format Literal /TbLCD/DmTop/DmARIf/ARLEN
add wave -noupdate -format Literal /TbLCD/DmTop/DmARIf/ARSIZE
add wave -noupdate -format Literal /TbLCD/DmTop/DmARIf/ARBURST
add wave -noupdate -format Literal /TbLCD/DmTop/DmARIf/ARLOCK
add wave -noupdate -format Literal /TbLCD/DmTop/DmARIf/ARCACHE
add wave -noupdate -format Literal /TbLCD/DmTop/DmARIf/ARPROT
add wave -noupdate -format Logic /TbLCD/DmTop/DmARIf/ARVALID
add wave -noupdate -format Logic /TbLCD/DmTop/DmARIf/ARREADY
add wave -noupdate -format Literal /TbLCD/DmTop/DmARIf/RID
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/RDATA
add wave -noupdate -format Literal /TbLCD/DmTop/DmARIf/RRESP
add wave -noupdate -format Logic /TbLCD/DmTop/DmARIf/RLAST
add wave -noupdate -format Logic /TbLCD/DmTop/DmARIf/RVALID
add wave -noupdate -format Logic /TbLCD/DmTop/DmARIf/RREADY
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/DmARIf/grd
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/grid
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/graddr
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/grsize
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/grbe
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/grdata
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/DmARIf/grvalid
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/DmARIf/grbusy
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/grdid
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/DmARIf/grlast
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/DmARIf/sm_ddata
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/DmARIf/sm_didle
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/addr_dly
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/rest_len
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/rest_lenm1
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/need_wd
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/send_byte
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/now_len
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/burst_len
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/cmp_4k
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/burst_4k
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/cmp_len_4k
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/DmARIf/acs
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/DmARIf/ans
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/DmARIf/dcs
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/ns
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/cs
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/DmARIf/sm_idle
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/DmARIf/sm_calc_len
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/DmARIf/sm_rd_cmd
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/DmARIf/sm_rd_data
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/DmARIf/sm_await
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/DmARIf/sm_aidle
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/ARID0
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/rest_addr
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/now_byte
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/next_byte
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/rd_size
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/pre_be
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/DmARIf/part_be
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/Clk
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/nRST
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/FIFOClear
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GPlaneEn
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/FrameStart
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/GPlaneStartAddr
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/GraphicDma/GPlaneXSize
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/GraphicDma/GPlaneYSize
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/GPlanePixFormat
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/GraphicDma/GPlaneXRef
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/GraphicDma/GPlaneXStart
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/GraphicDma/GPlaneYStart
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GDMARCmd
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GDMARCmdAck
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/GDMARAddr
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/GDMARBurstLen
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GDMARDataValid
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GDMARLast
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/GDMARData
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GDMADataRequest
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GDMADataValid
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/GDMADataIn
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GDMAOverRun
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GDMAUnderRun
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/tGIdle
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/tGDCal
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/tGDReq
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/tGDEnd
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GraphicDmaEn
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/GraphicDma/YDmaReqCnt
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/GraphicDma/XDmaReqCnt
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/GraphicDma/BurstSiz
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GBLQWrite
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GBLQRead
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/iGBLQRead
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/GraphicDma/GDMAGBLQ/DatCnt
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GBLQQFull
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GBLQHFull
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GBLQFull
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GBLQEmpty
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/GBLQWrData
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/GBLQRdData
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/BurstCnt
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/BurstEnd
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GDMARDataValidD
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GraFIFOWrite
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/GraFIFOWrData
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GraFIFORead
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/GraFIFORdData
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GraFIFOAlmostEmpty
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GraFIFOEmpty
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GraFIFOFull
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GraFIFOHalfFull
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/ReqMask
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GDMAEn
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GoDMARequest
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/XDmaReqEnd
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/GPlaneXStartRef
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/GPlaneXRefM4
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/GPlaneXRefRef
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/GDMAStartAddr
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/GraphicDma/GDMAEnd
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/BLQWrCount
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/BLQRdCount
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/GraphicDma/ReadExceedWrite
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/Clk
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/nRST
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/FIFOClear
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CPlaneEn
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/FrameStart
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/CPlaneStartAddr
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/CPlaneXSize
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/CPlaneYSize
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/CPlaneXStart
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/CPlaneYStart
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/CPlaneXStartRef
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/CPlaneXRef
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/CPlaneXRefRef
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CPlanePixFormat
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CPlaneAddrSwEn
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/CPlaneAddrSwVal
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CDMARCmd
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CDMARCmdAck
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/CDMARBurstLen
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CDMARDataValid
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/CursorDma/CDMARData
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CDMARLast
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/CDMARAddr
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CDMADataRequest
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CDMADataValid
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/CursorDma/CDMADataIn
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CDMAOverRun
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CDMAUnderRun
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/YDmaReqCnt
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/XDmaReqEnd
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/XDmaReqCnt
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CursorDmaEn
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CDMAEn
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/ReqMask
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/GoDMARequest
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/tCIdle
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/tCDCal
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/tCDReq
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/tCDEnd
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/CBFrameCnt
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CBFrameCntInc
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CBFrameCntEnd
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CDMARAddrSel
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/BurstSiz
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/CPlaneXYSize
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CBLQWrite
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CBLQRead
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/iCBLQRead
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CBLQHFull
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CBLQQFull
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CBLQFull
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CBLQEmpty
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/CBLQWrData
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/CBLQRdData
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/BurstCnt
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/BurstEnd
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CDMARDataValidD
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CurFIFOWrite
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/CursorDma/CurFIFOWrData
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CurFIFORead
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/CursorDma/CurFIFORdData
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CurFIFOAlmostEmpty
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CurFIFOEmpty
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CurFIFOFull
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorDma/CurFIFOHalfFull
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorDma/CPlaneXRefM4
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/Clk
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/nRST
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/FIFOClear
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CPlaneEn
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/FrameStart
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CDMADataRequest
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CDMADataValid
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorPlane/CDMADataIn
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CPlanePixFormat
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorPlane/CPlaneAlphaMode
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorPlane/CPlaneAlphaValue
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorPlane/CPlaneXSize
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorPlane/CPlaneYSize
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorPlane/CPlaneXSizeRef
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CPlaneDataRequest
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CPlaneDataValid
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorPlane/CPlaneDataIn
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CurFIFOOverRun
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CurFIFOUnderRun
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/tCIdle
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/tCDReq
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/tCWD00
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/tCWD01
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/tCWD10
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/tCWD11
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CursorEn
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CursorEnDis
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CursorEnEna
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CDMARequestX
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CDMARequestY
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorPlane/LatchCDMAData
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CurXCountEnd
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CurYCountEnd
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CurXCountInc
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorPlane/CurXCount
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorPlane/CurYCount
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CurFIFOWrite
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorPlane/CurFIFOWrData
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CurFIFORead
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/CursorPlane/CurFIFORdData
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CurFIFOEmpty
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CurFIFOFull
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/CurFIFOHalfFull
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/CursorPlane/GoDMARequest
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/Clk
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/nRST
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/FIFOClear
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VPlaneEn
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VPlaneInterlaceEn
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/FrameStart
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/VideoDma/VPlaneStartAddr
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/VideoDma/VPlaneStartAddr2
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/VideoDma/VPlaneXSize
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/VideoDma/VPlaneYSize
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VDMARDataValid
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VDMARLast
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/VideoDma/VDMARData
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VDMARCmd
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VDMARCmdAck
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/VideoDma/VDMARAddr
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/VideoDma/VDMARBurstLen
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VDMADataRequest
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VDMADataValid
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/VideoDma/VDMADataIn
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VDMAOverRun
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VDMAUnderRun
add wave -noupdate -format Logic /TbLCD/DmTop/VideoDma/LineSel
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoDma/VDMARAddr1
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoDma/VDMARAddr2
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/tVIdle
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/tVDCal
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/tVDReq
add wave -noupdate -format Logic /TbLCD/DmTop/VideoDma/tVDEnd
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VideoDmaEn
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/VideoDma/BurstSiz
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VBLQWrite
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VBLQRead
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/iVBLQRead
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VBLQHFull
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VBLQQFull
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VBLQFull
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VBLQEmpty
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/VideoDma/VBLQWrData
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/VideoDma/VBLQRdData
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/VideoDma/BurstCnt
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/BurstEnd
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VDMARDataValidD
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VidFIFOWrite
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/VideoDma/VidFIFOWrData
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VidFIFORead
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/VideoDma/VidFIFORdData
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VidFIFOAlmostEmpty
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VidFIFOEmpty
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VidFIFOFull
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/VidFIFOHalfFull
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/VideoDma/GoDMARequest
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/Clk
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/nRST
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/FIFOClear
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneEn
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/FrameStart
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VDMADataRequest
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VDMADataValid
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VDMADataIn
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneCSCEn
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGammaEn
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlanePixFormat
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneAlphaMode
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneAlphaValue
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneXSize
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneYSize
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneXSizeRef
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma10
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma0F
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma0E
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma0D
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma0C
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma0B
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma0A
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma09
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma08
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma07
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma06
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma05
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma04
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma03
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma02
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma01
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGamma00
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneDataRequest
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneDataValid
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneDataIn
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneDataHold
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidFIFOOverRun
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidFIFOUnderRun
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/tVIdle
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/tVDReq
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/tVWD00
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/tVWD01
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/tVWait
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VideoEn
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VideoEnDis
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VideoEnEna
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VWaitEnd
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VWaitCount
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VDMARequestX
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VDMARequestY
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/LatchVDMAData
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidXCountEnd
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidYCountEnd
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidXCountInc
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidXCount
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidYCount
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/FSMIn
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/FSMValidIn
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidFCIn
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidFCOut
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidFCValidIn
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidFCValidOut
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidCSCIn
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidCSCOut
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidCSCValidIn
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidCSCValidOut
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGammaValidIn
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGammaValidOut
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGammaIn
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGammaOut
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VPlaneGammaAlpha
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidFIFOWrite
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidFIFOWrData
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidFIFORead
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidFIFORdData
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidFIFOEmpty
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidFIFOFull
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidFIFOHalfFull
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/VidFIFOAlmostEmpty
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/VideoPlane/GoDMARequest
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PlaneMixer/Clk
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/PlaneMixer/MixXCount
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/PlaneMixer/MixYCount
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PlaneMixer/MixXCountEnd
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PlaneMixer/MixYCountEnd
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PlaneMixer/MixXCountInc
add wave -noupdate -format Logic /TbLCD/DmTop/PlaneMixer/BPlaneDataRequest
add wave -noupdate -format Logic /TbLCD/DmTop/PlaneMixer/BPlaneDataValid
add wave -noupdate -format Logic /TbLCD/DmTop/PlaneMixer/BPlaneRequestX
add wave -noupdate -format Logic /TbLCD/DmTop/PlaneMixer/BPlaneRequestY
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/PlaneMixer/LcdXSize
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PlaneMixer/P1DataSel
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PlaneMixer/P2DataSel
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PlaneMixer/P3DataSel
add wave -noupdate -format Logic /TbLCD/DmTop/PlaneMixer/P1AlphaBLendValid
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/PlaneMixer/P1AlphaBLendData
add wave -noupdate -format Logic /TbLCD/DmTop/PlaneMixer/P2AlphaBLendValid
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/PlaneMixer/P2AlphaBLendData
add wave -noupdate -format Logic /TbLCD/DmTop/PlaneMixer/P3AlphaBLendValid
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/PlaneMixer/P3AlphaBLendData
add wave -noupdate -format Literal /TbLCD/DmTop/PlaneMixer/MixerCount
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PlaneMixer/MixFIFOWrite
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/PlaneMixer/MixFIFOWrData
add wave -noupdate -format Literal /TbLCD/DmTop/PlaneMixer/MixerRdCount
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PlaneMixer/MixFIFORead
add wave -noupdate -format Literal -radix hexadecimal /TbLCD/DmTop/PlaneMixer/MixFIFORdData
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PlaneMixer/MixFIFOEmpty
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PlaneMixer/MixFIFOFull
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PlaneMixer/MixFIFOHalfFull
add wave -noupdate -format Logic -radix hexadecimal /TbLCD/DmTop/PlaneMixer/PlaneHold
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LCDCLK
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/nLCDRST
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LcdPwrEn
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/HFP
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/HBP
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/HSW
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/CPL
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/VSW
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/VFP
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/VBP
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/LPS
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/IVS
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/IHS
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/IEO
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/BCD
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LEEn
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/LEDel
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LcdEn
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/LcdVComp
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/FrRstAckSyncLcdClk
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/VCompAckSyncLcdClk
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/BusMBESyncLcdClk
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/NextRising
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/EndFrame
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/PCEn
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/FifoEn
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/VState
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/HState
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LCDFPint
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LCDLPint
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LCDDEint
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LCDLEint
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LCDPWRint
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/StartRow
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/FrameStart
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/FrameRst
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/VCompStat
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/UnpackEn
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/TFTPDEn
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/IntLCDLP1
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/IntLcdPwr
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/HEq0
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/VEq0
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/NextFrameRst
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/NextIntFrameSt
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/NextVComp
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/VEq1
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/VFPEq0
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/VBPEq0
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/HEq1
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/IntLCDDE
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/IntLCDDE1
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/NextUnpackEn
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/IntLCDFP1
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/NextLCDFP
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/IntLCDFP2
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/NextLCDFP1
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/IntLCDLP2
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/SOL
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LoadHSW
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LoadHFP
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LoadHBP
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LoadCPL
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LoadVSW
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LoadVFP
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LoadVBP
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LoadLPS
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/EndOfLine
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/NextVState
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/NextHState
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/NextLCDLP
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/FrameStartSet
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/IntFrameStart
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/FrameRstSet
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/VCompSet
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/DelNextRising
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/Dech
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/DecV
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/NextOE
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/NextSOL
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/EnFP
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LoadFirstSW
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/NextLoadFirstSW
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LEStartSet
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/NextLECount
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/LECount
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LoadLEV
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/LEVal
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/NextLEWait
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LEWait
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/NextLCDLEint
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/NextHCount
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/NextVCount
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/EnLowFlag
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/NextEnLowFlag
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/LcdEnEdgedet
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/NextLcdEnEdgedet
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/DelLcdEn
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/DelFrameRstSet
add wave -noupdate -format Logic -radix unsigned /TbLCD/DmTop/LcdTG/NextFrameStart
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/HCount
add wave -noupdate -format Literal -radix unsigned /TbLCD/DmTop/LcdTG/VCount
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {11051562036 ps} 0} {{Cursor 2} {4272740 ps} 0} {{Cursor 3} {6556052918 ps} 0} {{Cursor 4} {152755640 ps} 0} {{Cursor 5} {2922040960 ps} 0}
configure wave -namecolwidth 226
configure wave -valuecolwidth 71
configure wave -justifyvalue left
configure wave -signalnamewidth 2
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
update
WaveRestoreZoom {11051498714 ps} {11051725313 ps}
