library verilog;
use verilog.vl_types.all;
entity TSPSQ is
    port(
        PLACA           : in     vl_logic_vector(6 downto 0);
        FMODE           : in     vl_logic_vector(1 downto 0);
        CHTEST          : in     vl_logic;
        MCK             : in     vl_logic;
        TI              : in     vl_logic;
        TE              : in     vl_logic;
        ENP             : in     vl_logic;
        XRST            : in     vl_logic;
        WSCST           : in     vl_logic;
        TSYNC           : in     vl_logic;
        CHOSLD          : in     vl_logic;
        PITB            : in     vl_logic_vector(3 downto 0);
        TIMEA           : out    vl_logic_vector(8 downto 0);
        TACCL           : out    vl_logic;
        TPWEN           : out    vl_logic;
        TSCST           : out    vl_logic;
        ESYNC           : out    vl_logic;
        \TO\            : out    vl_logic;
        TIMLLLE         : out    vl_logic;
        TTLE            : out    vl_logic;
        TC2LE           : out    vl_logic;
        TC1LE           : out    vl_logic;
        DYACLE          : out    vl_logic;
        CHACLE          : out    vl_logic;
        RVACLE          : out    vl_logic;
        DLACLE          : out    vl_logic;
        DRACLE          : out    vl_logic;
        TIMLWE          : out    vl_logic;
        TIMHWE          : out    vl_logic;
        WEABLE          : out    vl_logic;
        TBLE            : out    vl_logic;
        TALE            : out    vl_logic;
        TYLE            : out    vl_logic;
        TXLE            : out    vl_logic;
        PLACB           : out    vl_logic_vector(8 downto 0);
        TIMEXEN         : out    vl_logic;
        CHLVEN          : out    vl_logic;
        TBS2EN          : out    vl_logic;
        TROMEN          : out    vl_logic;
        WESAEN          : out    vl_logic;
        TIMLIS          : out    vl_logic;
        DYACEN          : out    vl_logic;
        CHACEN          : out    vl_logic;
        RVACEN          : out    vl_logic;
        DLACEN          : out    vl_logic;
        DRACEN          : out    vl_logic;
        TCSEL           : out    vl_logic;
        WST0            : out    vl_logic;
        TACEN           : out    vl_logic;
        TCBEN           : out    vl_logic;
        WST1            : out    vl_logic;
        TSOEN           : out    vl_logic;
        TPYEN           : out    vl_logic;
        TBCL            : out    vl_logic;
        ITPEN           : out    vl_logic;
        WEOEN           : out    vl_logic;
        TSBEN           : out    vl_logic;
        TTSEN           : out    vl_logic;
        TSYEN           : out    vl_logic;
        TXEXEN          : out    vl_logic;
        TIMLLEN         : out    vl_logic;
        TIMLEN          : out    vl_logic;
        TIMHLEN         : out    vl_logic;
        TAIVEN          : out    vl_logic;
        TPAEN           : out    vl_logic
    );
end TSPSQ;
