library verilog;
use verilog.vl_types.all;
entity SDRSpi is
    generic(
        AW              : integer := 24;
        DW              : integer := 31;
        BW              : integer := 3;
        BL              : integer := 1;
        ID              : integer := 3;
        BBL             : integer := 3;
        WQCD            : integer := 4;
        WQD             : integer := 31;
        RQCD            : integer := 4;
        RQD             : integer := 31;
        WBLQCD          : integer := 2;
        WBLQD           : integer := 7;
        RBLQCD          : integer := 2;
        RBLQD           : integer := 7;
        ARBLQCD         : integer := 2;
        ARBLQD          : integer := 7;
        MDW             : integer := 15;
        DMW             : integer := 1;
        BAW             : integer := 1;
        RAW             : integer := 12;
        CAW             : integer := 10;
        RWW             : integer := 1;
        CD              : integer := 4;
        erc_powerup     : integer := 1;
        erc_epc         : integer := 2;
        erc_ar          : integer := 4;
        erc_mrs         : integer := 8;
        erc_idle        : integer := 16;
        erc_normal      : integer := 32;
        bc_null         : integer := 0;
        bc_mcas         : integer := 1;
        bc_mras         : integer := 2;
        bc_pc           : integer := 4;
        bc_sras         : integer := 8;
        bc_scas         : integer := 16;
        bc_epc          : integer := 32;
        ebc_null        : integer := 0;
        ebc_mcas        : integer := 1;
        ebc_mras        : integer := 2;
        ebc_pc          : integer := 4;
        ebc_sras        : integer := 8;
        ebc_scas        : integer := 16;
        ebc_epc         : integer := 32;
        ebc_bstop       : integer := 64;
        W_IDLE          : integer := 1;
        W_WREQ          : integer := 2;
        W_WDAT          : integer := 4;
        W_WRES          : integer := 8;
        W_WRES2         : integer := 16;
        W_WEND          : integer := 32;
        R_IDLE          : integer := 1;
        R_RREQ          : integer := 2;
        R_REND          : integer := 4;
        R_DIDLE         : integer := 1;
        R_DREQ          : integer := 2
    );
    port(
        ARESETB         : in     vl_logic;
        ACLK            : in     vl_logic;
        AWAddrS         : in     vl_logic_vector;
        AWIdS           : in     vl_logic_vector;
        AWLenS          : in     vl_logic_vector;
        AWValidS        : in     vl_logic;
        AWReadyS        : out    vl_logic;
        AWBurstS        : in     vl_logic_vector(1 downto 0);
        WLastS          : in     vl_logic;
        WStrbS          : in     vl_logic_vector;
        WDataS          : in     vl_logic_vector;
        WValidS         : in     vl_logic;
        WReadyS         : out    vl_logic;
        WIdS            : in     vl_logic_vector;
        BRespS          : out    vl_logic_vector(1 downto 0);
        BValidS         : out    vl_logic;
        BReadyS         : in     vl_logic;
        BIdS            : out    vl_logic_vector;
        ARAddrS         : in     vl_logic_vector;
        ARIdS           : in     vl_logic_vector;
        ARLenS          : in     vl_logic_vector;
        ARValidS        : in     vl_logic;
        ARReadyS        : out    vl_logic;
        ARBurstS        : in     vl_logic_vector(1 downto 0);
        RDataS          : out    vl_logic_vector;
        RValidS         : out    vl_logic;
        RReadyS         : in     vl_logic;
        RLastS          : out    vl_logic;
        RIdS            : out    vl_logic_vector;
        RRespS          : out    vl_logic_vector(1 downto 0);
        AWAddrM         : out    vl_logic_vector;
        AWIdM           : out    vl_logic_vector;
        AWLenM          : out    vl_logic_vector;
        AWValidM        : out    vl_logic;
        AWReadyM        : in     vl_logic;
        AWBurstM        : out    vl_logic_vector(1 downto 0);
        WLastM          : out    vl_logic;
        WStrbM          : out    vl_logic_vector;
        WDataM          : out    vl_logic_vector;
        WValidM         : out    vl_logic;
        WReadyM         : in     vl_logic;
        WIdM            : out    vl_logic_vector;
        BRespM          : in     vl_logic_vector(1 downto 0);
        BValidM         : in     vl_logic;
        BReadyM         : out    vl_logic;
        BIdM            : in     vl_logic_vector;
        ARAddrM         : out    vl_logic_vector;
        ARIdM           : out    vl_logic_vector;
        ARLenM          : out    vl_logic_vector;
        ARValidM        : out    vl_logic;
        ARReadyM        : in     vl_logic;
        ARBurstM        : out    vl_logic_vector(1 downto 0);
        RDataM          : in     vl_logic_vector;
        RValidM         : in     vl_logic;
        RReadyM         : out    vl_logic;
        RLastM          : in     vl_logic;
        RIdM            : in     vl_logic_vector;
        RRespM          : in     vl_logic_vector(1 downto 0)
    );
end SDRSpi;
