@TM:1164280258
@N: FA174 :"":0:0:0:-1|The following device usage report estimates place and route data. Please look at the place and route report for final resource usage..
@N: MT195 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT197 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@TM:1164280256
@N: MT204 :"":0:0:0:-1|Autoconstrain Mode is ON
@N:  :"d:\data\ntsc_pal\testrtl_master\rtl_test\videoencodertester.v":21:7:21:24|Synthesizing module VideoEncoderTester
@W: CL159 :"d:\data\ntsc_pal\testrtl_master\rtl_test\videoencodertester.v":123:23:123:27|M
@TM:1164332178
@W: CL159 :"d:\data\ntsc_pal\testrtl_master\rtl_test\videoencodertester.v":124:23:124:27|M
@TM:1164332164
@N:  :"d:\data\ntsc_pal\testrtl_master\rtl_test\videoencodertester.v":233:15:233:27|M
@N:  :"d:\data\ntsc_pal\testrtl_master\rtl_test\videoencodertester.v":267:24:267:36|M
@N:  :"d:\data\ntsc_pal\testrtl_master\rtl_test\videoencodertester.v":267:38:267:46|M
@N:  :"d:\data\ntsc_pal\testrtl_master\rtl_test\videoencodertester.v":293:24:293:36|M
@N:  :"d:\data\ntsc_pal\testrtl_master\rtl_test\videoencodertester.v":293:38:293:46|M
@TM:1164342422
@N:  :"d:\data\ntsc_pal\testrtl_master\rtl_test\videoencodertester.v":446:0:446:5|M
@N:  :"d:\data\ntsc_pal\testrtl_master\rtl_test\videoencodertester.v":534:0:534:5|M
@N:  :"d:\data\ntsc_pal\testrtl_master\rtl_test\videoencodertester.v":552:0:552:5|M
