#- --=========================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2001 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- -----------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.2
#-
#- Release Information    : PrimeCell(TM)-PL220-r0p0-00ltd0
#-
#- -----------------------------------------------------------------------------
#- Purpose  :
#-            makefile for Verilog Trickbox files
#-
#- --=========================================================================--

MODULES =  EbiTrParams.v \
           EbiTrRegBlk.v \
           EbiTrAhbif.v \
           EbiTrClkResGen.v \
           EbiTrArbtCtl.v \
           EbiTrMultBlk.v \
           EbiTrMirEbi.v \
           EbiTrReqIndctr.v \
           EbiTrComparator.v \
           EbiTrProChkr.v \
           EbiTrick.v

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk 

##################################### End ######################################
