library verilog;
use verilog.vl_types.all;
entity mmc_reg is
    port(
        mresetn         : in     vl_logic;
        msreset         : in     vl_logic;
        hsreset         : in     vl_logic;
        mclk            : in     vl_logic;
        hsel            : in     vl_logic;
        haddr           : in     vl_logic_vector(31 downto 0);
        htrans          : in     vl_logic_vector(1 downto 0);
        hsize           : in     vl_logic_vector(2 downto 0);
        hwrite          : in     vl_logic;
        hready          : in     vl_logic;
        hwdata          : in     vl_logic_vector(31 downto 0);
        hrdata          : out    vl_logic_vector(31 downto 0);
        hresp           : out    vl_logic_vector(1 downto 0);
        hreadyout       : out    vl_logic;
        hcommand        : in     vl_logic_vector(47 downto 0);
        hcommand_ok     : in     vl_logic;
        hcommand_ok2    : in     vl_logic;
        hcommand_ok3wr  : in     vl_logic;
        hstatus         : in     vl_logic_vector(31 downto 0);
        hcrc7_ok        : in     vl_logic;
        hcrc16_ok       : in     vl_logic;
        hcmdirqwr       : in     vl_logic_vector(14 downto 0);
        hrespirqwr      : in     vl_logic_vector(14 downto 0);
        hwrirqwr        : in     vl_logic_vector(14 downto 0);
        hrdirqwr        : in     vl_logic_vector(14 downto 0);
        hprefix         : in     vl_logic_vector(7 downto 0);
        hresp_end       : in     vl_logic;
        hrespfield      : in     vl_logic_vector(3 downto 0);
        hcselect        : in     vl_logic;
        hcid            : out    vl_logic_vector(127 downto 0);
        hrca            : out    vl_logic_vector(15 downto 0);
        hdsr            : out    vl_logic_vector(15 downto 0);
        hcsd            : out    vl_logic_vector(127 downto 0);
        mocr_update     : in     vl_logic;
        mrca_update     : in     vl_logic;
        mrca_up_data    : in     vl_logic_vector(15 downto 0);
        mcmdindex       : in     vl_logic_vector(5 downto 0);
        mcommand_ok     : in     vl_logic;
        \Access\        : in     vl_logic_vector(1 downto 0);
        index           : in     vl_logic_vector(7 downto 0);
        value           : in     vl_logic_vector(7 downto 0);
        switch_error    : in     vl_logic;
        wr_block_buffer_4word: in     vl_logic_vector(127 downto 0);
        mcmdfield       : in     vl_logic_vector(3 downto 0);
        resp_eox        : in     vl_logic;
        resp_eor        : in     vl_logic;
        block_len_error : in     vl_logic;
        mwrfield        : in     vl_logic_vector(3 downto 0);
        wr_count        : in     vl_logic_vector(15 downto 0);
        cid_csd_overwrite: in     vl_logic;
        csd_update      : in     vl_logic_vector(127 downto 0);
        hext_csd        : out    vl_logic_vector(191 downto 0);
        hocr            : out    vl_logic_vector(31 downto 0);
        hdecode60       : out    vl_logic_vector(15 downto 0);
        hdecode61       : out    vl_logic_vector(15 downto 0);
        hdecode62       : out    vl_logic_vector(15 downto 0);
        hdecode63       : out    vl_logic_vector(15 downto 0);
        hcmddef         : out    vl_logic_vector(63 downto 0);
        hblockmax       : out    vl_logic_vector(22 downto 0);
        hwblen          : out    vl_logic_vector(11 downto 0);
        hrblen          : out    vl_logic_vector(11 downto 0);
        hcardlock       : out    vl_logic;
        hcidfix         : out    vl_logic;
        heraseseq       : out    vl_logic_vector(8 downto 0);
        herasecmd       : out    vl_logic_vector(8 downto 0);
        hstatuscpu      : out    vl_logic_vector(31 downto 0);
        hstatuswren     : out    vl_logic_vector(31 downto 0);
        hstatuswr       : out    vl_logic;
        hcstnorm        : out    vl_logic_vector(4 downto 0);
        hcststop        : out    vl_logic_vector(4 downto 0);
        hcstmanu        : out    vl_logic_vector(4 downto 0);
        hcstwr          : out    vl_logic;
        hnid            : out    vl_logic_vector(7 downto 0);
        hncrmmc         : out    vl_logic_vector(7 downto 0);
        hncrspi         : out    vl_logic_vector(7 downto 0);
        hbsyend         : out    vl_logic;
        hbsybwcmd       : out    vl_logic;
        hgo_irq_state   : out    vl_logic;
        hwakeupen       : out    vl_logic;
        hcrc7_on_off    : out    vl_logic;
        hcrc16_on_off   : out    vl_logic;
        hcmdirqen       : out    vl_logic_vector(15 downto 0);
        hrespirqen      : out    vl_logic_vector(15 downto 0);
        hwrirqen        : out    vl_logic_vector(15 downto 0);
        hrdirqen        : out    vl_logic_vector(15 downto 0);
        hwrforce        : out    vl_logic;
        hrdforce        : out    vl_logic;
        hdis2rcv        : out    vl_logic;
        hstby_cmd2      : out    vl_logic;
        hstby_cmd3      : out    vl_logic;
        hbusy_cmd12     : out    vl_logic;
        hbusy_cmd12_resp: out    vl_logic_vector(2 downto 0);
        hrden           : out    vl_logic;
        hlocken         : out    vl_logic_vector(63 downto 0);
        hsfr_out        : out    vl_logic_vector(7 downto 0);
        hsfr_read       : out    vl_logic_vector(31 downto 0);
        hbuswidth_cmd   : out    vl_logic_vector(31 downto 0);
        hdma1locken     : out    vl_logic_vector(7 downto 0);
        htmbw           : in     vl_logic;
        houtdly         : out    vl_logic_vector(5 downto 0)
    );
end mmc_reg;
