#- --=========================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- -----------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.19
#-
#- Release Information    : PrimeCell(TM)-PL092-r1p3-01ltd0
#-
#- -----------------------------------------------------------------------------
#- Purpose :
#-           Standard VHDL Library Makefile
#-
#- --=========================================================================--

MODULES = SmcPackage.vhd \
          SmcRevAnd.vhd \
          SmcAhbif.vhd \
          SmcSynchroniser.vhd \
          SmcTSM.vhd \
          SmcEIB.vhd \
          SmcTimerWaitCont.vhd \
          SmcWrEnGen.vhd \
	  SmcCore.vhd \
          TIC.vhd \
          DBI.vhd \
          Smc.vhd

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

#- --================================= End ===================================--
