library verilog;
use verilog.vl_types.all;
entity dmacchregblock is
    port(
        hclk            : in     vl_logic;
        hresetn         : in     vl_logic;
        hwdata          : in     vl_logic_vector(31 downto 0);
        masteraddressm1 : in     vl_logic_vector(31 downto 0);
        masteraddressm2 : in     vl_logic_vector(31 downto 0);
        chwrdatam1      : in     vl_logic_vector(31 downto 0);
        chwrdatam2      : in     vl_logic_vector(31 downto 0);
        dmacchannelsel  : in     vl_logic;
        reghwrite       : in     vl_logic;
        regaddress      : in     vl_logic_vector(4 downto 2);
        srcdmacstate    : in     vl_logic_vector(4 downto 0);
        srcerr          : in     vl_logic;
        srcdisable      : in     vl_logic;
        srcaddrupdate   : in     vl_logic;
        dectrfsizesrc   : in     vl_logic;
        dectrfsizedst   : in     vl_logic;
        dstdmacstate    : in     vl_logic_vector(4 downto 0);
        dsterr          : in     vl_logic;
        dstdisable      : in     vl_logic;
        dstaddrupdate   : in     vl_logic;
        finishedlli     : in     vl_logic;
        llierr          : in     vl_logic;
        disabledlli     : in     vl_logic;
        llisrcwr        : in     vl_logic;
        llidstwr        : in     vl_logic;
        llilliregwr     : in     vl_logic;
        llicntlwr       : in     vl_logic;
        fifononempty    : in     vl_logic;
        chdstbreq       : in     vl_logic;
        chdstlbreq      : in     vl_logic;
        ldsrcindstflow  : in     vl_logic;
        chhrdata        : out    vl_logic_vector(31 downto 0);
        fifoptrreset    : out    vl_logic;
        setinterr       : out    vl_logic;
        dmacchsrcaddr   : out    vl_logic_vector(31 downto 0);
        dmacchdstaddr   : out    vl_logic_vector(31 downto 0);
        unseterrmsk     : out    vl_logic;
        trfsizedst      : out    vl_logic_vector(13 downto 0);
        disableddst     : out    vl_logic;
        srcerred        : out    vl_logic;
        disabledsrc     : out    vl_logic;
        inttcenable     : out    vl_logic;
        dsterred        : out    vl_logic;
        swidth          : out    vl_logic_vector(2 downto 0);
        dwidth          : out    vl_logic_vector(2 downto 0);
        srcselect       : out    vl_logic;
        dstselect       : out    vl_logic;
        trfsizesrc      : out    vl_logic_vector(11 downto 0);
        sbsize          : out    vl_logic_vector(2 downto 0);
        dbsize          : out    vl_logic_vector(2 downto 0);
        srcincr         : out    vl_logic;
        destincr        : out    vl_logic;
        protstat        : out    vl_logic_vector(2 downto 0);
        tcintmask       : out    vl_logic;
        channelen       : out    vl_logic;
        srcperiph       : out    vl_logic_vector(3 downto 0);
        dstperiph       : out    vl_logic_vector(3 downto 0);
        flowcntl        : out    vl_logic_vector(2 downto 0);
        errintmask      : out    vl_logic;
        chlock          : out    vl_logic;
        halt            : out    vl_logic;
        channelenlow    : out    vl_logic;
        sourceen        : out    vl_logic;
        desten          : out    vl_logic;
        lliselforpkt    : out    vl_logic;
        lliaddressub    : out    vl_logic_vector(31 downto 2)
    );
end dmacchregblock;
