library verilog;
use verilog.vl_types.all;
entity converter64to32 is
    port(
        aclk            : in     vl_logic;
        aresetn         : in     vl_logic;
        awaddr64        : in     vl_logic_vector(31 downto 0);
        awlen64         : in     vl_logic_vector(3 downto 0);
        awsize64        : in     vl_logic_vector(2 downto 0);
        awburst64       : in     vl_logic_vector(1 downto 0);
        awvalid64       : in     vl_logic;
        awready64       : out    vl_logic;
        wdata64         : in     vl_logic_vector(63 downto 0);
        wstrb64         : in     vl_logic_vector(7 downto 0);
        wlast64         : in     vl_logic;
        wvalid64        : in     vl_logic;
        wready64        : out    vl_logic;
        bresp64         : out    vl_logic_vector(1 downto 0);
        bvalid64        : out    vl_logic;
        bready64        : in     vl_logic;
        araddr64        : in     vl_logic_vector(31 downto 0);
        arlen64         : in     vl_logic_vector(3 downto 0);
        arsize64        : in     vl_logic_vector(2 downto 0);
        arburst64       : in     vl_logic_vector(1 downto 0);
        arvalid64       : in     vl_logic;
        arready64       : out    vl_logic;
        rdata64         : out    vl_logic_vector(63 downto 0);
        rresp64         : out    vl_logic_vector(1 downto 0);
        rlast64         : out    vl_logic;
        rvalid64        : out    vl_logic;
        rready64        : in     vl_logic;
        awaddr32        : out    vl_logic_vector(31 downto 0);
        awlen32         : out    vl_logic_vector(3 downto 0);
        awsize32        : out    vl_logic_vector(2 downto 0);
        awburst32       : out    vl_logic_vector(1 downto 0);
        awvalid32       : out    vl_logic;
        awready32       : in     vl_logic;
        wdata32         : out    vl_logic_vector(31 downto 0);
        wstrb32         : out    vl_logic_vector(3 downto 0);
        wlast32         : out    vl_logic;
        wvalid32        : out    vl_logic;
        wready32        : in     vl_logic;
        bresp32         : in     vl_logic_vector(1 downto 0);
        bvalid32        : in     vl_logic;
        bready32        : out    vl_logic;
        araddr32        : out    vl_logic_vector(31 downto 0);
        arlen32         : out    vl_logic_vector(3 downto 0);
        arsize32        : out    vl_logic_vector(2 downto 0);
        arburst32       : out    vl_logic_vector(1 downto 0);
        arvalid32       : out    vl_logic;
        arready32       : in     vl_logic;
        rdata32         : in     vl_logic_vector(31 downto 0);
        rresp32         : in     vl_logic_vector(1 downto 0);
        rlast32         : in     vl_logic;
        rvalid32        : in     vl_logic;
        rready32        : out    vl_logic
    );
end converter64to32;
