library verilog;
use verilog.vl_types.all;
entity AHB1_WriteChannelmi is
    generic(
        BUS_WID         : integer := 32;
        ADDR_WID        : integer := 32;
        MASTERID_WID    : integer := 1;
        SLAVEID_WID     : integer := 2;
        AWLEN_WID       : integer := 4;
        AWSIZE_WID      : integer := 3;
        AWBURST_WID     : integer := 2;
        AWLOCK_WID      : integer := 2;
        AWCACHE_WID     : integer := 4;
        AWPROT_WID      : integer := 3;
        WSTRB_WID       : integer := 4;
        BRESP_WID       : integer := 2;
        RRESP_WID       : integer := 2;
        ARLEN_WID       : integer := 4;
        ARBURST_WID     : integer := 2;
        ARLOCK_WID      : integer := 2;
        ARCACHE_WID     : integer := 4;
        ARPROT_WID      : integer := 3;
        MASTER_WID      : integer := 3;
        SLAVE_WID       : integer := 4;
        SLAVE_NUM       : integer := 8;
        MASTER_NUM      : integer := 5;
        SELMASTER_WID   : integer := 1;
        Wr_REQDEPTH_WID : integer := 1;
        Rd_REQDEPTH_WID : integer := 1;
        WrPermit_SLAVECNTWID: integer := 1;
        RdPermit_SLAVECNTWID: integer := 1;
        ARSIZE_WID      : integer := 3
    );
    port(
        ACLK            : in     vl_logic;
        ARESETn         : in     vl_logic;
        AWIDmi2s        : out    vl_logic_vector;
        AWADDRmi2s      : out    vl_logic_vector;
        AWLENmi2s       : out    vl_logic_vector;
        AWSIZEmi2s      : out    vl_logic_vector;
        AWBURSTmi2s     : out    vl_logic_vector;
        AWLOCKmi2s      : out    vl_logic_vector;
        AWCACHEmi2s     : out    vl_logic_vector;
        AWPROTmi2s      : out    vl_logic_vector;
        AWVALIDmi2s     : out    vl_logic;
        AWREADYs2mi     : in     vl_logic;
        WIDmi2s         : out    vl_logic_vector;
        WDATAmi2s       : out    vl_logic_vector;
        WSTRBmi2s       : out    vl_logic_vector;
        WLASTmi2s       : out    vl_logic;
        WVALIDmi2s      : out    vl_logic;
        WREADYs2mi      : in     vl_logic;
        BIDs2mi         : in     vl_logic_vector;
        BRESPs2mi       : in     vl_logic_vector;
        BVALIDs2mi      : in     vl_logic;
        BREADYmi2s      : out    vl_logic;
        AWIDsi02mi      : in     vl_logic_vector;
        AWADDRsi02mi    : in     vl_logic_vector;
        AWLENsi02mi     : in     vl_logic_vector;
        AWSIZEsi02mi    : in     vl_logic_vector;
        AWBURSTsi02mi   : in     vl_logic_vector;
        AWLOCKsi02mi    : in     vl_logic_vector;
        AWCACHEsi02mi   : in     vl_logic_vector;
        AWPROTsi02mi    : in     vl_logic_vector;
        WIDsi02mi       : in     vl_logic_vector;
        WDATAsi02mi     : in     vl_logic_vector;
        WSTRBsi02mi     : in     vl_logic_vector;
        AWIDsi12mi      : in     vl_logic_vector;
        AWADDRsi12mi    : in     vl_logic_vector;
        AWLENsi12mi     : in     vl_logic_vector;
        AWSIZEsi12mi    : in     vl_logic_vector;
        AWBURSTsi12mi   : in     vl_logic_vector;
        AWLOCKsi12mi    : in     vl_logic_vector;
        AWCACHEsi12mi   : in     vl_logic_vector;
        AWPROTsi12mi    : in     vl_logic_vector;
        WIDsi12mi       : in     vl_logic_vector;
        WDATAsi12mi     : in     vl_logic_vector;
        WSTRBsi12mi     : in     vl_logic_vector;
        BIDmi2si0       : out    vl_logic_vector;
        BRESPmi2si0     : out    vl_logic_vector;
        BIDmi2si1       : out    vl_logic_vector;
        BRESPmi2si1     : out    vl_logic_vector;
        BVALIDmi2si     : out    vl_logic_vector;
        BREADYsi2mi     : in     vl_logic_vector;
        Lock2Wrmi       : in     vl_logic;
        UnLock2Wrmi     : in     vl_logic;
        Lock2Rdmi       : out    vl_logic;
        UnLock2Rdmi     : out    vl_logic;
        ARVALID         : in     vl_logic;
        LockPort        : in     vl_logic_vector;
        ReadIntEmptyWrmi2Rdmi: out    vl_logic;
        DataCntEmptyRdmi2Wrmi: in     vl_logic;
        CtlDataWrite2Lock: out    vl_logic_vector;
        AWVALIDsi2mi    : in     vl_logic_vector;
        AWREADYmi2si    : out    vl_logic_vector;
        WLASTsi2mi      : in     vl_logic_vector;
        WVALIDsi2mi     : in     vl_logic_vector;
        WREADYmi2si     : out    vl_logic_vector
    );
end AHB1_WriteChannelmi;
