#-====================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- ---------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.1
#-
#- Release Information    : PrimeCell(TM)-PL022-REL1v2
#-
#- ---------------------------------------------------------------------
#- Purpose  : makefile for Verilog Trickbox files
#- -==================================================================--

MODULES = SspTrApbif.v \
          SspTrRegCore.v \
          SspTrScaleCntr.v \
          SspTrTxRegFile.v \
          SspTrTxFCntl.v \
          SspTrTxLJustify.v \
          SspTrTxFIFO.v \
          SspTrRxRegFile.v \
          SspTrRxFCntl.v \
          SspTrRxFIFO.v \
          SspTrSynctoPCLK.v \
          SspTrSynctoSSPCLK.v \
          SspTrMTxRxCntl.v \
          SspTrSTxRxCntl.v \
          SspTrChecker.v \
          SspTrCkRsCntlr.v \
          SspTrDMA.v \
          SspTrick.v 

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk 

################################# End ##################################
