library verilog;
use verilog.vl_types.all;
entity NFAPBIF is
    generic(
        QSIZE           : integer := 8
    );
    port(
        PCLK            : in     vl_logic;
        PRESETn         : in     vl_logic;
        PADDR           : in     vl_logic_vector(6 downto 2);
        PSEL            : in     vl_logic;
        PENABLE         : in     vl_logic;
        PWRITE          : in     vl_logic;
        PWDATA          : in     vl_logic_vector(31 downto 0);
        PRDATA          : out    vl_logic_vector(31 downto 0);
        NFBootPinIn     : in     vl_logic;
        IOWidthPinIn    : in     vl_logic;
        NandWidthPinIn  : in     vl_logic;
        BootCfgPinIn    : in     vl_logic_vector(1 downto 0);
        OutDtmnPinIn    : in     vl_logic;
        IntReqOut       : out    vl_logic;
        ECCSECTOR0      : in     vl_logic_vector(23 downto 0);
        ECCSECTOR1      : in     vl_logic_vector(23 downto 0);
        ECCSECTOR2      : in     vl_logic_vector(23 downto 0);
        ECCSECTOR3      : in     vl_logic_vector(23 downto 0);
        ECCSECTOR4      : in     vl_logic_vector(23 downto 0);
        ECCSECTOR5      : in     vl_logic_vector(23 downto 0);
        ECCSECTOR6      : in     vl_logic_vector(23 downto 0);
        ECCSECTOR7      : in     vl_logic_vector(23 downto 0);
        ECCSECTOR8      : in     vl_logic_vector(23 downto 0);
        ECCSECTOR9      : in     vl_logic_vector(23 downto 0);
        ECCSECTOR10     : in     vl_logic_vector(23 downto 0);
        ECCSECTOR11     : in     vl_logic_vector(23 downto 0);
        ECCSECTOR12     : in     vl_logic_vector(23 downto 0);
        ECCSECTOR13     : in     vl_logic_vector(23 downto 0);
        ECCSECTOR14     : in     vl_logic_vector(23 downto 0);
        ECCSECTOR15     : in     vl_logic_vector(23 downto 0);
        SECCSECTOR0     : in     vl_logic_vector(15 downto 0);
        SECCSECTOR1     : in     vl_logic_vector(15 downto 0);
        SECCSECTOR2     : in     vl_logic_vector(15 downto 0);
        SECCSECTOR3     : in     vl_logic_vector(15 downto 0);
        SECCSECTOR4     : in     vl_logic_vector(15 downto 0);
        SECCSECTOR5     : in     vl_logic_vector(15 downto 0);
        SECCSECTOR6     : in     vl_logic_vector(15 downto 0);
        SECCSECTOR7     : in     vl_logic_vector(15 downto 0);
        NFCtrlBusyIn    : in     vl_logic;
        NFStatValidIn   : in     vl_logic;
        NFStatusIn      : in     vl_logic_vector(15 downto 0);
        WrEndIn         : in     vl_logic;
        RdEndIn         : in     vl_logic;
        RdFIFOReadyIn   : in     vl_logic;
        WrFIFOReadyIn   : in     vl_logic;
        FiltRnB1In      : in     vl_logic;
        FiltRnB0In      : in     vl_logic;
        FIFOFlushIn     : in     vl_logic;
        FIFORdDataOut   : out    vl_logic_vector(31 downto 0);
        FIFORdDataEnIn  : in     vl_logic;
        FIFOWrDataIn    : in     vl_logic_vector(31 downto 0);
        FIFOWrDataEnIn  : in     vl_logic;
        BeforeFullOut   : out    vl_logic;
        FIFORdReadyOut  : out    vl_logic;
        FIFOFullOut     : out    vl_logic;
        FIFOHalfFullOut : out    vl_logic;
        FIFOEmpty1Out   : out    vl_logic;
        FIFOEmpty0Out   : out    vl_logic;
        WrRdyOut        : out    vl_logic;
        RdRdyOut        : out    vl_logic;
        NFOpRdEnIn      : in     vl_logic;
        NFOpOut         : out    vl_logic_vector(31 downto 0);
        QLevelOut       : out    vl_logic_vector(3 downto 0);
        ControlOut      : out    vl_logic_vector(13 downto 0);
        ConfigOut       : out    vl_logic_vector(18 downto 0)
    );
end NFAPBIF;
