#####################################################

#  Created by Design Compiler write_sdc on Wed May  9 09:40:33 2007

#####################################################
set sdc_version 1.4

create_clock -period 10 -waveform {0 5} [get_ports {PCLK}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[0]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[0]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[1]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[1]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[2]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[2]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[3]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[3]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[4]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[4]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[5]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[5]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[6]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[6]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[7]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[7]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[8]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[8]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[9]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[9]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[10]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[10]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[11]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[11]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[12]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[12]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[13]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[13]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[14]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[14]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[15]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[15]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[16]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[16]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[17]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[17]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[18]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[18]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[19]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[19]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[20]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[20]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[21]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[21]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[22]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[22]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[23]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[23]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[24]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[24]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[25]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[25]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[26]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[26]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[27]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[27]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[28]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[28]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[29]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[29]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[30]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[30]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWDATA[31]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[31]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PADDR[2]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PADDR[2]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PADDR[3]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PADDR[3]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PADDR[4]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PADDR[4]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PADDR[5]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PADDR[5]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PADDR[6]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PADDR[6]}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PWRITE}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWRITE}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PENABLE}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PENABLE}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PSEL}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PSEL}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PRESETn}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PRESETn}]
set_input_delay 7 -max -clock "PCLK" [get_ports {PCLK}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PCLK}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[0]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[0]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[1]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[1]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[2]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[2]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[3]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[3]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[4]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[4]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[5]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[5]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[6]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[6]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[7]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[7]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[8]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[8]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[9]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[9]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[10]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[10]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[11]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[11]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[12]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[12]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[13]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[13]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[14]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[14]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[15]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[15]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[16]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[16]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[17]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[17]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[18]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[18]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[19]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[19]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[20]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[20]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[21]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[21]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[22]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[22]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[23]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[23]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[24]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[24]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[25]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[25]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[26]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[26]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[27]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[27]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[28]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[28]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[29]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[29]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[30]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[30]}]
set_output_delay 6 -max -clock "PCLK" [get_ports {PRDATA[31]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[31]}]
set_clock_transition -rise 0 [get_clocks {PCLK}]
set_clock_transition -fall 0 [get_clocks {PCLK}]
set_clock_uncertainty  0.8 -setup [get_ports {PCLK}]
set_max_transition 2 [current_design]
set_input_transition -max 1 [get_ports {PCLK}]
set_load -pin_load 0 [get_ports {PCLK}]
set_input_transition -max 1 [get_ports {PRESETn}]
set_load -pin_load 0 [get_ports {PRESETn}]
set_disable_timing [get_ports {PRESETn}]
set_input_transition -max 1 [get_ports {PSEL}]
set_input_transition -max 1 [get_ports {PENABLE}]
set_input_transition -max 1 [get_ports {PWRITE}]
set_input_transition -max 1 [get_ports {PADDR[6]}]
set_input_transition -max 1 [get_ports {PADDR[5]}]
set_input_transition -max 1 [get_ports {PADDR[4]}]
set_input_transition -max 1 [get_ports {PADDR[3]}]
set_input_transition -max 1 [get_ports {PADDR[2]}]
set_input_transition -max 1 [get_ports {PWDATA[31]}]
set_input_transition -max 1 [get_ports {PWDATA[30]}]
set_input_transition -max 1 [get_ports {PWDATA[29]}]
set_input_transition -max 1 [get_ports {PWDATA[28]}]
set_input_transition -max 1 [get_ports {PWDATA[27]}]
set_input_transition -max 1 [get_ports {PWDATA[26]}]
set_input_transition -max 1 [get_ports {PWDATA[25]}]
set_input_transition -max 1 [get_ports {PWDATA[24]}]
set_input_transition -max 1 [get_ports {PWDATA[23]}]
set_input_transition -max 1 [get_ports {PWDATA[22]}]
set_input_transition -max 1 [get_ports {PWDATA[21]}]
set_input_transition -max 1 [get_ports {PWDATA[20]}]
set_input_transition -max 1 [get_ports {PWDATA[19]}]
set_input_transition -max 1 [get_ports {PWDATA[18]}]
set_input_transition -max 1 [get_ports {PWDATA[17]}]
set_input_transition -max 1 [get_ports {PWDATA[16]}]
set_input_transition -max 1 [get_ports {PWDATA[15]}]
set_input_transition -max 1 [get_ports {PWDATA[14]}]
set_input_transition -max 1 [get_ports {PWDATA[13]}]
set_input_transition -max 1 [get_ports {PWDATA[12]}]
set_input_transition -max 1 [get_ports {PWDATA[11]}]
set_input_transition -max 1 [get_ports {PWDATA[10]}]
set_input_transition -max 1 [get_ports {PWDATA[9]}]
set_input_transition -max 1 [get_ports {PWDATA[8]}]
set_input_transition -max 1 [get_ports {PWDATA[7]}]
set_input_transition -max 1 [get_ports {PWDATA[6]}]
set_input_transition -max 1 [get_ports {PWDATA[5]}]
set_input_transition -max 1 [get_ports {PWDATA[4]}]
set_input_transition -max 1 [get_ports {PWDATA[3]}]
set_input_transition -max 1 [get_ports {PWDATA[2]}]
set_input_transition -max 1 [get_ports {PWDATA[1]}]
set_input_transition -max 1 [get_ports {PWDATA[0]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[31]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[31]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[30]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[30]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[29]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[29]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[28]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[28]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[27]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[27]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[26]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[26]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[25]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[25]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[24]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[24]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[23]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[23]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[22]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[22]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[21]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[21]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[20]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[20]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[19]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[19]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[18]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[18]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[17]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[17]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[16]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[16]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[15]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[15]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[14]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[14]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[13]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[13]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[12]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[12]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[11]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[11]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[10]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[10]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[9]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[9]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[8]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[8]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[7]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[7]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[6]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[6]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[5]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[5]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[4]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[4]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[3]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[3]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[2]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[2]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[1]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[1]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[0]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[0]}]
set_input_transition -max 1 [get_ports {MMC_FBCLK}]
set_input_transition -max 1 [get_ports {MMC_CMDIN}]
set_input_transition -max 1 [get_ports {MMC_DATIN[7]}]
set_input_transition -max 1 [get_ports {MMC_DATIN[6]}]
set_input_transition -max 1 [get_ports {MMC_DATIN[5]}]
set_input_transition -max 1 [get_ports {MMC_DATIN[4]}]
set_input_transition -max 1 [get_ports {MMC_DATIN[3]}]
set_input_transition -max 1 [get_ports {MMC_DATIN[2]}]
set_input_transition -max 1 [get_ports {MMC_DATIN[1]}]
set_input_transition -max 1 [get_ports {MMC_DATIN[0]}]
set_input_transition -max 1 [get_ports {TESTMODE}]
set_load -pin_load 0.018316 [get_ports {MMC_INT}]
set_load -min -pin_load 0.018316 [get_ports {MMC_INT}]
set_load -pin_load 0.018316 [get_ports {MMC_DMAREQ}]
set_load -min -pin_load 0.018316 [get_ports {MMC_DMAREQ}]
set_load -pin_load 0.018316 [get_ports {MMC_CLKOUT}]
set_load -min -pin_load 0.018316 [get_ports {MMC_CLKOUT}]
set_load -pin_load 0.018316 [get_ports {MMC_CMDOUT}]
set_load -min -pin_load 0.018316 [get_ports {MMC_CMDOUT}]
set_load -pin_load 0.018316 [get_ports {MMC_DATOUT[7]}]
set_load -min -pin_load 0.018316 [get_ports {MMC_DATOUT[7]}]
set_load -pin_load 0.018316 [get_ports {MMC_DATOUT[6]}]
set_load -min -pin_load 0.018316 [get_ports {MMC_DATOUT[6]}]
set_load -pin_load 0.018316 [get_ports {MMC_DATOUT[5]}]
set_load -min -pin_load 0.018316 [get_ports {MMC_DATOUT[5]}]
set_load -pin_load 0.018316 [get_ports {MMC_DATOUT[4]}]
set_load -min -pin_load 0.018316 [get_ports {MMC_DATOUT[4]}]
set_load -pin_load 0.018316 [get_ports {MMC_DATOUT[3]}]
set_load -min -pin_load 0.018316 [get_ports {MMC_DATOUT[3]}]
set_load -pin_load 0.018316 [get_ports {MMC_DATOUT[2]}]
set_load -min -pin_load 0.018316 [get_ports {MMC_DATOUT[2]}]
set_load -pin_load 0.018316 [get_ports {MMC_DATOUT[1]}]
set_load -min -pin_load 0.018316 [get_ports {MMC_DATOUT[1]}]
set_load -pin_load 0.018316 [get_ports {MMC_DATOUT[0]}]
set_load -min -pin_load 0.018316 [get_ports {MMC_DATOUT[0]}]
set_load -pin_load 0.018316 [get_ports {MMC_nCMDEN}]
set_load -min -pin_load 0.018316 [get_ports {MMC_nCMDEN}]
set_load -pin_load 0.018316 [get_ports {MMC_nDATEN}]
set_load -min -pin_load 0.018316 [get_ports {MMC_nDATEN}]
set_resistance 0 [get_nets {PCLK}]
set_resistance 0 [get_nets {PRESETn}]
