library verilog;
use verilog.vl_types.all;
entity ETRI_UWBCore is
    port(
        nRESET          : in     vl_logic;
        ARMnRESET       : in     vl_logic;
        CLK200M         : in     vl_logic;
        CLK100M         : in     vl_logic;
        CLK50M          : in     vl_logic;
        CLK27M          : in     vl_logic;
        BOOT_WIDTH      : in     vl_logic_vector(1 downto 0);
        SMC_ADDR        : out    vl_logic_vector(26 downto 0);
        SMC_WDATA       : out    vl_logic_vector(15 downto 0);
        SMC_RDATA       : in     vl_logic_vector(15 downto 0);
        SMC_nCS         : out    vl_logic_vector(8 downto 0);
        SMC_nOE         : out    vl_logic;
        SMC_nWE         : out    vl_logic;
        SMC_nBE         : out    vl_logic_vector(3 downto 0);
        SMC_nWBE        : out    vl_logic_vector(3 downto 0);
        SMC_BIDEN       : out    vl_logic;
        DDR_CLK         : out    vl_logic;
        DDR_nCLK        : out    vl_logic;
        DDR_CKE         : out    vl_logic;
        DDR_CSB         : out    vl_logic;
        DDR_RASB        : out    vl_logic;
        DDR_CASB        : out    vl_logic;
        DDR_WEB         : out    vl_logic;
        DDR_BADDR       : out    vl_logic_vector(1 downto 0);
        DDR_ADDR        : out    vl_logic_vector(12 downto 0);
        DDR_DQE         : out    vl_logic;
        DDR_DQI         : in     vl_logic_vector(15 downto 0);
        DDR_DQO         : out    vl_logic_vector(15 downto 0);
        DDR_DQM         : out    vl_logic_vector(1 downto 0);
        DDR_DQSE        : out    vl_logic;
        DDR_DQSO        : out    vl_logic_vector(1 downto 0);
        DDR_DQSI        : in     vl_logic_vector(1 downto 0);
        DDR_nDQSI       : in     vl_logic_vector(1 downto 0);
        UART_TXD        : out    vl_logic_vector(3 downto 0);
        UART_RXD        : in     vl_logic_vector(3 downto 0);
        I2C_SCLi        : in     vl_logic;
        I2C_SDAi        : in     vl_logic;
        I2C_SCLo        : out    vl_logic;
        I2C_SDAo        : out    vl_logic;
        I2C_nSDAEn      : out    vl_logic;
        I2C_nSCLEn      : out    vl_logic;
        I2S_MCLK        : out    vl_logic;
        I2S_MCLK_OE     : out    vl_logic;
        I2S_BCLK_O      : out    vl_logic;
        I2S_BCLK_I      : in     vl_logic;
        I2S_BCLK_OE     : out    vl_logic;
        I2S_LRCLK_O     : out    vl_logic;
        I2S_LRCLK_I     : in     vl_logic;
        I2S_LRCLK_OE    : out    vl_logic;
        I2S_SDIN        : in     vl_logic;
        I2S_SDOUT       : out    vl_logic;
        NF_Boot         : in     vl_logic;
        NF_IOWidth      : in     vl_logic;
        NF_Width        : in     vl_logic;
        NF_BootCfg      : in     vl_logic_vector(1 downto 0);
        NF_OutDtmn      : in     vl_logic;
        NF_DMADone      : out    vl_logic;
        NF_DI           : in     vl_logic_vector(15 downto 0);
        NF_DO           : out    vl_logic_vector(15 downto 0);
        NF_DOE          : out    vl_logic;
        NF_CLE          : out    vl_logic;
        NF_ALE          : out    vl_logic;
        NF_nCE1         : out    vl_logic;
        NF_nCE0         : out    vl_logic;
        NF_nRE          : out    vl_logic;
        NF_nWE          : out    vl_logic;
        NF_RnB1         : in     vl_logic;
        NF_RnB0         : in     vl_logic;
        GPIO0_IN        : in     vl_logic_vector(31 downto 0);
        GPIO0_OE        : out    vl_logic_vector(31 downto 0);
        GPIO0_OUT       : out    vl_logic_vector(31 downto 0);
        GPIO1_IN        : in     vl_logic_vector(31 downto 0);
        GPIO1_OE        : out    vl_logic_vector(31 downto 0);
        GPIO1_OUT       : out    vl_logic_vector(31 downto 0);
        SPIRxd          : in     vl_logic;
        SPInSSIn        : in     vl_logic;
        SPIClkIn        : in     vl_logic;
        SPInSSOut       : out    vl_logic;
        SPIClkOut       : out    vl_logic;
        SPITxd          : out    vl_logic;
        SPInOE          : out    vl_logic;
        SPInCTLOE       : out    vl_logic;
        ARMICE_nTRST    : in     vl_logic;
        ARMICE_TCK      : in     vl_logic;
        ARMICE_RTCK     : out    vl_logic;
        ARMICE_TMS      : in     vl_logic;
        ARMICE_TDI      : in     vl_logic;
        ARMICE_TDO      : out    vl_logic
    );
end ETRI_UWBCore;
