onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {New Divider}
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ARESETn
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/Start
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/Ready
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/FifoReset
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/NumByte
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/SrcWidth
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/DataIn
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/WriteEn
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/SrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/DstWidth
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/DataOut
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/DataMask
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ReadEn
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/DstAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ChControl
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ChSrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ChDestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ChDescriptor
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ChControlWE
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ChSrcAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ChDestAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ChDescriptorWE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ChControlWData
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ChSrcAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ChDestAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ChDescriptorWData
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ARBURST
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/RREADY
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/AWBURST
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/BREADY
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/StartInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/EndInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ErrorInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/StopInterrupt
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/DestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/SourceAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/DescriptorAddr
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/DescriptorEnd
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/Length
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/Size
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/DestWidth
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/DestIncr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/SourceWidth
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/SrcIncr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/State
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/NextState
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/LengthIsZero
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/AllDescriptorLoad
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/LAST
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/BusError
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/WriteError
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/NewLength
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ByteSize
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/DescReadCount
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ChRegWE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/NewSrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/NewDestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/NewControl
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/Add32bitOut
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/Add32bitOperand
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/Read
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/Write
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/Addr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/Width
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/Burst
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/LowerAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/AXISIZE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/IncrAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/NextIncrAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/TestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/MaxLenWithout4KBCross
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/SizeInByte
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/TotalTransferLen
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/RealLen
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/NextRemainedTransferLen
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/AlignedAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/AlignedRealLen
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/AXILEN
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/AXILENPlusOne
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/RemainedTransferLen
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/AXIBURST
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/RealLenMinusOne
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/TransferCount
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/CurrentAWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/AWLEN_FIFO_0
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/AWLEN_FIFO_1
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/NumOfWriteReq
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/NumOfWriteProc
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/NumOfWriteProcPlusOne
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Engine/Control/ReadError
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/PCLK
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/PRESETn
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/PENABLE
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/PSEL
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/PWRITE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/PADDR
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/PRDATA
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/Active
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/Enabled
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/Memory2Memory
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/ControlWE
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/SrcAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/DestAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/DescriptorWE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/ControlWData
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/SrcAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/DestAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/DescriptorWData
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/StartInterruptIn
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/EndInterruptIn
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/ErrorInterruptIn
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/StopInterruptIn
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/Interrupt
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/Descriptor
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/SrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/DestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/Control
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/Status
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/PSELInternal
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/PRDATA0
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/PRDATA1
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/PRDATA2
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/PRDATA3
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/Control0
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/SrcAddr0
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/DestAddr0
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/Descriptor0
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/Control1
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/SrcAddr1
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/DestAddr1
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/Descriptor1
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/Control2
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/SrcAddr2
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/DestAddr2
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/Descriptor2
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/Control3
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/SrcAddr3
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/DestAddr3
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RegFile/Descriptor3
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/Channel0
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/ControlWE0
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/SrcAddrWE0
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/DestAddrWE0
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/DescriptorWE0
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/StartInterrupt0
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/EndInterrupt0
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/StopInterrupt0
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/ErrorInterrupt0
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/Channel1
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/ControlWE1
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/SrcAddrWE1
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/DestAddrWE1
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/DescriptorWE1
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/StartInterrupt1
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/EndInterrupt1
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/StopInterrupt1
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/ErrorInterrupt1
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/Channel2
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/ControlWE2
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/SrcAddrWE2
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/DestAddrWE2
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/DescriptorWE2
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/StartInterrupt2
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/EndInterrupt2
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/StopInterrupt2
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/ErrorInterrupt2
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/Channel3
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/ControlWE3
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/SrcAddrWE3
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/DestAddrWE3
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/DescriptorWE3
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/StartInterrupt3
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/EndInterrupt3
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/StopInterrupt3
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/ErrorInterrupt3
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RegFile/ARESETn
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/ARESETn
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/DMAReq
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/DMAAck
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Interrupt
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/PENABLE
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/PSEL
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/PWRITE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/PADDR
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/PRDATA
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/ARBURST
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/RREADY
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/AWBURST
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/BREADY
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Start
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/Ready
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/ChControl
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/ChSrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/ChDestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/ChDescriptor
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/ChControlWE
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/ChSrcAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/ChDestAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/ChDescriptorWE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/ChControlWData
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/ChSrcAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/ChDestAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/ChDescriptorWData
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/StartInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/EndInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/ErrorInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/Dmac4/StopInterrupt
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Active
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Memory2Memory
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/Dmac4/Enabled
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/SRAM/CLK
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/SRAM/ADDR
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/SRAM/CEn
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/SRAM/WEn
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/SRAM/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/SRAM/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/SRAM/i
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/ARESETn
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/AWID
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/AWBURST
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/WID
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/BID
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/BREADY
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/ARID
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/ARBURST
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/RID
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/RREADY
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/MEMADDR
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/MEMCEn
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/MEMWEn
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/MEMRDATA
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/MEMWDATA
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/nReadOrWrite
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/nReadOrWrite_P
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/Addr_P
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/Len_P
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/Size_P
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/Burst_P
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/ID_P
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/VALID_P
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/StartNewRequest
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/MuxedAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/MuxedLen
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/MuxedSize
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/MuxedBurst
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/MuxedId
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/RealnReadOrWrite
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/CanAcceptMoreRequest
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/StateIsIDLE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/State
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/NextState
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/StateIsREAD
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/StateIsWRITE
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/StateIsWAIT_RESP
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/SuccessiveRead
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/NextFirstREADCycle
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/Id
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/Addr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/Len
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/BurstLen
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/Size
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/Burst
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/FirstREADCycle
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/SuccessiveReadCondition
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/DecreaseLen
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/IntSRAMController/NextAddrCalcEn
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/IncreasedAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/PrevAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/WrapMask
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/IntSRAMController/IncrSize
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/ARESETn
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWID
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWBURST
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWLOCK
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWCACHE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWPROT
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/WID
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/BID
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/BREADY
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARID
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARBURST
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARLOCK
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARCACHE
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARPROT
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/RID
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/RREADY
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWID_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWADDR_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWLEN_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWSIZE_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWBURST_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWLOCK_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWCACHE_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWPROT_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/WID_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/WDATA_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/WSTRB_r
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/WLAST_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARID_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARADDR_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARLEN_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARSIZE_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARBURST_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARLOCK_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARCACHE_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARPROT_r
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWQ_WINDEX
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/AWQ_RINDEX
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/AWQ_empty
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/WIDQ_WINDEX
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/WIDQ_RINDEX
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/WIDQ_full
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/WIDQ_empty
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/WDQ_RINDEX
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/WDQ_WINDEX
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/WDQ_empty
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARQ_WINDEX
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/ARQ_RINDEX
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/ARQ_empty
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/DecreaseWID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/DecreaseWIDEnable
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/IncreaseWID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/IncreaseWIDEnable
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/DecreaseRID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/DecreaseRIDEnable
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/IncreaseRID
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/IncreaseRIDEnable
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/AW_idle
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/AW_RANDOM
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/WD_idle
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/WD_RANDOM
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/AR_idle
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/AR_RANDOM
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/LAST_READ_DATA
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/i_rd
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/i_wid_temp
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/i_rid_temp
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/ResetIdleCnt
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/IdleCnt
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/src_addr_index
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/dst_addr_index
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/length_index
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/dst_width_index
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/src_width_index
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/size_index
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/small_or_large
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/SrcWidth
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/DstWidth
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/SrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/DstAddr
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/Size
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/Length
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/LengthTemp
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/MaxLength
add wave -noupdate -format Logic -radix hexadecimal /tb4Ch/TestMaster/TestNum
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/offset0
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/offset1
add wave -noupdate -format Literal -radix hexadecimal /tb4Ch/TestMaster/index
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
WaveRestoreZoom {0 ps} {310016 ps}
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
