onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {New Divider}
add wave -noupdate -divider {New Divider}
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/ARESETn
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/Start
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/Ready
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/FifoReset
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/NumByte
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/SrcWidth
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/DataIn
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/WriteEn
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/SrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/DstWidth
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/DataOut
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/DataMask
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/ReadEn
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/DstAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/ChControl
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/ChSrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/ChDestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/ChDescriptor
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/ChControlWE
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/ChSrcAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/ChDestAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/ChDescriptorWE
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/ChControlWData
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/ChSrcAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/ChDestAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/ChDescriptorWData
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/ARBURST
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/RREADY
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/AWBURST
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/BREADY
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/StartInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/EndInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/ErrorInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/StopInterrupt
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/DestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/SourceAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/DescriptorAddr
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/DescriptorEnd
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/Length
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/Size
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/DestWidth
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/DestIncr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/SourceWidth
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/SrcIncr
add wave -noupdate -format Literal /tb/Dmac1/Engine/Control/LowerAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/SizeInByte
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/State
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/NextState
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/LengthIsZero
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/AllDescriptorLoad
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/LAST
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/BusError
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/NewLength
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/ByteSize
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/DescReadCount
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/ChRegWE
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/NewSrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/NewDestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/NewControl
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/Add32bitOut
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/Add32bitOperand
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/Read
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/Write
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/Addr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/Width
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/Burst
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/AXISIZE
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/IncrAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/TestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/MaxLenWithout4KBCross
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/TotalTransferLen
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/RealLen
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/NextRemainedTransferLen
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/AlignedAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/NextIncrAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/AlignedRealLen
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/AXILEN
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/RemainedTransferLen
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/AXIADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/AXIBURST
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/RealLenMinusOne
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/TransferCount
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/CurrentAWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/AWLEN_FIFO_0
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/AWLEN_FIFO_1
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/NumOfWriteReq
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/NumOfWriteProc
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/Engine/Control/NumOfWriteProcPlusOne
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Engine/Control/ReadError
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/PCLK
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/PRESETn
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/PENABLE
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/PSEL
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/PWRITE
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/PADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/PRDATA
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/Active
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/Enabled
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/Memory2Memory
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/ControlWE
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/SrcAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/DestAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/DescriptorWE
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/ControlWData
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/SrcAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/DestAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/DescriptorWData
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/StartInterruptIn
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/EndInterruptIn
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/ErrorInterruptIn
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/StopInterruptIn
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/Interrupt
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/Descriptor
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/SrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/DestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/Control
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/Status
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/DescriptorAddr
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/DescriptorEnd
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/StartIntEn
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/EndIntEn
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/MtoM
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/SrcIncr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/SrcWidth
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/DstIncr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/DstWidth
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/Size
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RegFile/Length
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/StopIntEn
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/StopInt
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/StartInt
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/EndInt
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/ErrInt
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/APB_WriteEnable
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/APB_ReadEnable
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/StartIntEnable
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/EndIntEnable
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RegFile/StopIntEnable
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/ARESETn
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/DMAReq
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/DMAAck
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Interrupt
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/PENABLE
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/PSEL
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/PWRITE
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/PADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/PRDATA
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/ARBURST
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/RREADY
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/AWBURST
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/BREADY
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Start
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Ready
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/ChControl
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/ChSrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/ChDestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/ChDescriptor
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/ChControlWE
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/ChSrcAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/ChDestAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/ChDescriptorWE
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/ChControlWData
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/ChSrcAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/ChDestAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb/Dmac1/ChDescriptorWData
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/StartInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/EndInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/ErrorInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/StopInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Active
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Memory2Memory
add wave -noupdate -format Logic -radix hexadecimal /tb/Dmac1/Enabled
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb/SRAM/CLK
add wave -noupdate -format Literal -radix hexadecimal /tb/SRAM/ADDR
add wave -noupdate -format Logic -radix hexadecimal /tb/SRAM/CEn
add wave -noupdate -format Literal -radix hexadecimal /tb/SRAM/WEn
add wave -noupdate -format Literal -radix hexadecimal /tb/SRAM/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/SRAM/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/SRAM/i
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/ARESETn
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/AWID
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/AWBURST
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/WID
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/BID
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/BREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/ARID
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/ARBURST
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/RID
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/RREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/MEMADDR
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/MEMCEn
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/MEMWEn
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/MEMRDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/MEMWDATA
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/nReadOrWrite
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/nReadOrWrite_P
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/Addr_P
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/Len_P
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/Size_P
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/Burst_P
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/ID_P
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/VALID_P
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/StartNewRequest
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/MuxedAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/MuxedLen
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/MuxedSize
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/MuxedBurst
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/MuxedId
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/RealnReadOrWrite
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/CanAcceptMoreRequest
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/StateIsIDLE
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/State
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/NextState
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/StateIsREAD
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/StateIsWRITE
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/StateIsWAIT_RESP
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/SuccessiveRead
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/NextFirstREADCycle
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/Id
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/Addr
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/Len
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/BurstLen
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/Size
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/Burst
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/FirstREADCycle
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/SuccessiveReadCondition
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/DecreaseLen
add wave -noupdate -format Logic -radix hexadecimal /tb/IntSRAMController/NextAddrCalcEn
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/IncreasedAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/PrevAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/WrapMask
add wave -noupdate -format Literal -radix hexadecimal /tb/IntSRAMController/IncrSize
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/ARESETn
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWID
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWBURST
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWLOCK
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWCACHE
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWPROT
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/WID
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/BID
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/BREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARID
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARBURST
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARLOCK
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARCACHE
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARPROT
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/RID
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/RREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWID_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWADDR_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWLEN_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWSIZE_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWBURST_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWLOCK_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWCACHE_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWPROT_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/WID_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/WDATA_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/WSTRB_r
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/WLAST_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARID_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARADDR_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARLEN_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARSIZE_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARBURST_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARLOCK_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARCACHE_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARPROT_r
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWQ_WINDEX
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/AWQ_RINDEX
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/AWQ_empty
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/WIDQ_WINDEX
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/WIDQ_RINDEX
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/WIDQ_full
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/WIDQ_empty
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/WDQ_RINDEX
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/WDQ_WINDEX
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/WDQ_empty
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARQ_WINDEX
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/ARQ_RINDEX
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/ARQ_empty
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/DecreaseWID
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/DecreaseWIDEnable
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/IncreaseWID
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/IncreaseWIDEnable
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/DecreaseRID
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/DecreaseRIDEnable
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/IncreaseRID
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/IncreaseRIDEnable
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/AW_idle
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/AW_RANDOM
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/WD_idle
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/WD_RANDOM
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/AR_idle
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/AR_RANDOM
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/LAST_READ_DATA
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/i_rd
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/i_wid_temp
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/i_rid_temp
add wave -noupdate -format Logic -radix hexadecimal /tb/TestMaster/ResetIdleCnt
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/IdleCnt
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/src_addr_index
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/dst_addr_index
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/length_index
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/dst_width_index
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/src_width_index
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/size_index
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/SrcWidth
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/DstWidth
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/SrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/DstAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/Size
add wave -noupdate -format Literal -radix hexadecimal /tb/TestMaster/Length
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {33979005000 ps} 0}
WaveRestoreZoom {33978780856 ps} {33979156480 ps}
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
