onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ARESETn
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/Start
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/Ready
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/FifoReset
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/NumByte
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/SrcWidth
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/DataIn
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/WriteEn
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/SrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/DstWidth
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/DataOut
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/DataMask
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ReadEn
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/DstAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ChControl
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ChSrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ChDestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ChDescriptor
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ChControlWE
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ChSrcAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ChDestAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ChDescriptorWE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ChControlWData
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ChSrcAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ChDestAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ChDescriptorWData
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ARBURST
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/RREADY
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/AWBURST
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/BREADY
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/StartInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/EndInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ErrorInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/StopInterrupt
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/DestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/SourceAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/DescriptorAddr
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/DescriptorEnd
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/Length
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/Size
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/DestWidth
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/DestIncr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/SourceWidth
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/SrcIncr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/State
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/NextState
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/LengthIsZero
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/AllDescriptorLoad
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/LAST
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/BusError
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/WriteError
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/NewLength
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ByteSize
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/DescReadCount
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ChRegWE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/NewSrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/NewDestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/NewControl
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/Add32bitOut
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/Add32bitOperand
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/Read
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/Write
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/Addr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/Width
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/Burst
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/LowerAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/AXISIZE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/IncrAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/NextIncrAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/TestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/MaxLenWithout4KBCross
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/SizeInByte
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/TotalTransferLen
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/RealLen
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/NextRemainedTransferLen
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/AlignedAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/AlignedRealLen
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/AXILEN
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/AXILENPlusOne
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/RemainedTransferLen
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/AXIBURST
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/RealLenMinusOne
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/TransferCount
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/CurrentAWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/AWLEN_FIFO_0
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/AWLEN_FIFO_1
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/NumOfWriteReq
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/NumOfWriteProc
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/NumOfWriteProcPlusOne
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Engine/Control/ReadError
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/PCLK
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/PRESETn
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/PENABLE
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/PSEL
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/PWRITE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/PADDR
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/PRDATA
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/Active
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/Enabled
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/Memory2Memory
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/ControlWE
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/SrcAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/DestAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/DescriptorWE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/ControlWData
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/SrcAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/DestAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/DescriptorWData
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/StartInterruptIn
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/EndInterruptIn
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/ErrorInterruptIn
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/StopInterruptIn
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/Interrupt
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/Descriptor
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/SrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/DestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/Control
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/Status
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/DescriptorAddr
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/DescriptorEnd
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/StartIntEn
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/EndIntEn
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/MtoM
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/SrcIncr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/SrcWidth
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/DstIncr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/DstWidth
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/Size
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/Length
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/Enable
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/StopIntEn
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/StopInt
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/StartInt
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/EndInt
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/ErrInt
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/APB_WriteEnable
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/APB_ReadEnable
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/StartIntEnable
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/EndIntEnable
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RegFile/Channel0Reg/StopIntEnable
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/ARESETn
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/DMAReq
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/DMAAck
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Interrupt
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/PENABLE
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/PSEL
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/PWRITE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/PADDR
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/PRDATA
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/ARBURST
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/RREADY
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/AWBURST
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/BREADY
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Start
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Ready
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/ChControl
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/ChSrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/ChDestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/ChDescriptor
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/ChControlWE
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/ChSrcAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/ChDestAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/ChDescriptorWE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/ChControlWData
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/ChSrcAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/ChDestAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/Dmac1/ChDescriptorWData
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/StartInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/EndInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/ErrorInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/StopInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Active
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Memory2Memory
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/Dmac1/Enabled
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/SRAM/CLK
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/SRAM/ADDR
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/SRAM/CEn
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/SRAM/WEn
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/SRAM/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/SRAM/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/SRAM/i
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/ARESETn
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/AWID
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/AWBURST
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/WID
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/BID
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/BREADY
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/ARID
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/ARBURST
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/RID
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/RREADY
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/MEMADDR
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/MEMCEn
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/MEMWEn
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/MEMRDATA
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/MEMWDATA
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/nReadOrWrite
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/nReadOrWrite_P
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/Addr_P
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/Len_P
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/Size_P
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/Burst_P
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/ID_P
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/VALID_P
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/StartNewRequest
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/MuxedAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/MuxedLen
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/MuxedSize
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/MuxedBurst
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/MuxedId
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/RealnReadOrWrite
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/CanAcceptMoreRequest
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/StateIsIDLE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/State
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/NextState
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/StateIsREAD
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/StateIsWRITE
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/StateIsWAIT_RESP
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/SuccessiveRead
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/NextFirstREADCycle
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/Id
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/Addr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/Len
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/BurstLen
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/Size
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/Burst
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/FirstREADCycle
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/SuccessiveReadCondition
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/DecreaseLen
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/IntSRAMController/NextAddrCalcEn
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/IncreasedAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/PrevAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/WrapMask
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/IntSRAMController/IncrSize
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/ARESETn
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWID
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWBURST
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWLOCK
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWCACHE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWPROT
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/WID
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/BID
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/BREADY
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARID
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARBURST
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARLOCK
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARCACHE
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARPROT
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/RID
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/RREADY
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWID_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWADDR_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWLEN_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWSIZE_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWBURST_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWLOCK_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWCACHE_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWPROT_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/WID_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/WDATA_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/WSTRB_r
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/WLAST_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARID_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARADDR_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARLEN_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARSIZE_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARBURST_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARLOCK_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARCACHE_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARPROT_r
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWQ_WINDEX
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/AWQ_RINDEX
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/AWQ_empty
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/WIDQ_WINDEX
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/WIDQ_RINDEX
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/WIDQ_full
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/WIDQ_empty
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/WDQ_RINDEX
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/WDQ_WINDEX
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/WDQ_empty
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARQ_WINDEX
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/ARQ_RINDEX
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/ARQ_empty
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/DecreaseWID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/DecreaseWIDEnable
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/IncreaseWID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/IncreaseWIDEnable
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/DecreaseRID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/DecreaseRIDEnable
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/IncreaseRID
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/IncreaseRIDEnable
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/AW_idle
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/AW_RANDOM
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/WD_idle
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/WD_RANDOM
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/AR_idle
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/AR_RANDOM
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/LAST_READ_DATA
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/i_rd
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/i_wid_temp
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/i_rid_temp
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/ResetIdleCnt
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/IdleCnt
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/src_addr_index
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/dst_addr_index
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/length_index
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/dst_width_index
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/src_width_index
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/size_index
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/small_or_large
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/SrcWidth
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/DstWidth
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/SrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/DstAddr
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/Size
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/Length
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/LengthTemp
add wave -noupdate -format Literal -radix hexadecimal /tb1Ch/TestMaster/MaxLength
add wave -noupdate -format Logic -radix hexadecimal /tb1Ch/TestMaster/TestNum
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
WaveRestoreZoom {0 ps} {155008 ps}
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
