onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {New Divider}
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ARESETn
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/Start
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/Ready
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/FifoReset
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/NumByte
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/SrcWidth
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/DataIn
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/WriteEn
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/SrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/DstWidth
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/DataOut
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/DataMask
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ReadEn
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/DstAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ChControl
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ChSrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ChDestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ChDescriptor
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ChControlWE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ChSrcAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ChDestAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ChDescriptorWE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ChControlWData
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ChSrcAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ChDestAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ChDescriptorWData
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ARBURST
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/RREADY
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/AWBURST
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/BREADY
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/StartInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/EndInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ErrorInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/StopInterrupt
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/DestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/SourceAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/DescriptorAddr
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/DescriptorEnd
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/Length
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/Size
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/DestWidth
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/DestIncr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/SourceWidth
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/SrcIncr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/State
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/NextState
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/LengthIsZero
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/AllDescriptorLoad
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/LAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/BusError
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/WriteError
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/NewLength
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ByteSize
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/DescReadCount
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ChRegWE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/NewSrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/NewDestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/NewControl
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/Add32bitOut
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/Add32bitOperand
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/Read
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/Write
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/Addr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/Width
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/Burst
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/LowerAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/AXISIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/IncrAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/NextIncrAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/TestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/MaxLenWithout4KBCross
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/SizeInByte
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/TotalTransferLen
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/RealLen
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/NextRemainedTransferLen
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/AlignedAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/AlignedRealLen
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/AXILEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/AXILENPlusOne
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/RemainedTransferLen
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/AXIBURST
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/RealLenMinusOne
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/TransferCount
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/CurrentAWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/AWLEN_FIFO_0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/AWLEN_FIFO_1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/NumOfWriteReq
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/NumOfWriteProc
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/NumOfWriteProcPlusOne
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Engine/Control/ReadError
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ARESETn
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/DMAReq
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/DMAAck
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Interrupt
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/PENABLE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/PSEL
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/PWRITE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/PADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/PRDATA
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ARBURST
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/RREADY
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/AWBURST
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/BREADY
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Start
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Ready
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ChControl
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ChSrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ChDestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ChDescriptor
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ChControlWE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ChSrcAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ChDestAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ChDescriptorWE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ChControlWData
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ChSrcAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ChDestAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ChDescriptorWData
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/StartInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/EndInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/ErrorInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/StopInterrupt
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Active
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Memory2Memory
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_1/Enabled
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ARESETn
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/Start
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/Ready
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/FifoReset
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/NumByte
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/SrcWidth
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/DataIn
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/WriteEn
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/SrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/DstWidth
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/DataOut
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/DataMask
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ReadEn
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/DstAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ChControl
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ChSrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ChDestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ChDescriptor
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ChControlWE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ChSrcAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ChDestAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ChDescriptorWE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ChControlWData
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ChSrcAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ChDestAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ChDescriptorWData
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ARBURST
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/RREADY
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/AWBURST
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/BREADY
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/StartInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/EndInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ErrorInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/StopInterrupt
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/DestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/SourceAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/DescriptorAddr
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/DescriptorEnd
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/Length
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/Size
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/DestWidth
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/DestIncr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/SourceWidth
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/SrcIncr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/State
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/NextState
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/LengthIsZero
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/AllDescriptorLoad
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/LAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/BusError
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/WriteError
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/NewLength
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ByteSize
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/DescReadCount
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ChRegWE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/NewSrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/NewDestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/NewControl
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/Add32bitOut
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/Add32bitOperand
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/Read
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/Write
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/Addr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/Width
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/Burst
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/LowerAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/AXISIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/IncrAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/NextIncrAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/TestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/MaxLenWithout4KBCross
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/SizeInByte
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/TotalTransferLen
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/RealLen
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/NextRemainedTransferLen
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/AlignedAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/AlignedRealLen
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/AXILEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/AXILENPlusOne
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/RemainedTransferLen
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/AXIBURST
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/RealLenMinusOne
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/TransferCount
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/CurrentAWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/AWLEN_FIFO_0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/AWLEN_FIFO_1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/NumOfWriteReq
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/NumOfWriteProc
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/NumOfWriteProcPlusOne
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Engine/Control/ReadError
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ARESETn
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/DMAReq
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/DMAAck
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Interrupt
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/PENABLE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/PSEL
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/PWRITE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/PADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/PRDATA
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ARBURST
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/RREADY
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/AWBURST
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/BREADY
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Start
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Ready
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ChControl
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ChSrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ChDestAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ChDescriptor
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ChControlWE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ChSrcAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ChDestAddrWE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ChDescriptorWE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ChControlWData
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ChSrcAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ChDestAddrWData
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ChDescriptorWData
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/StartInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/EndInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/ErrorInterrupt
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/StopInterrupt
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Active
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Memory2Memory
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Dmac2_0/Enabled
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARESETn
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARVALID0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARREADY0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARADDR0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARLEN0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARSIZE0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARBURST0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/RDATA0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/RRESP0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/RLAST0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/RVALID0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/RREADY0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWVALID0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWREADY0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWADDR0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWLEN0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWSIZE0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWBURST0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WDATA0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WSTRB0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WLAST0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WVALID0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WREADY0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/BRESP0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/BVALID0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/BREADY0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARVALID1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARREADY1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARADDR1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARLEN1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARSIZE1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARBURST1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/RDATA1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/RRESP1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/RLAST1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/RVALID1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/RREADY1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWVALID1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWREADY1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWADDR1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWLEN1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWSIZE1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWBURST1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WDATA1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WSTRB1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WLAST1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WVALID1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WREADY1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/BRESP1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/BVALID1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/BREADY1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARBURST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/RID
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/RREADY
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWBURST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WID
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WREADY
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/BID
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/BREADY
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARidle
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARSel_reg
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARSel
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/ARSelected0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWidle
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWSel_reg
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWSel
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWSelected0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWIDQueFull
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWTrans
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/WLastTrans
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWIDQue
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWIDQueReadIndex
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWIDQueWriteIndex
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/AWIDQueEmpty
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/NextAWIDQueWriteIndex
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AXI2x1Arbiter/NextAWIDQueReadIndex
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PCLK
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PRESETn
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PENABLE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PSEL
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PWRITE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PRDATA
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PCLK0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PRESETn0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PENABLE0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PSEL0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PWRITE0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PADDR0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PWDATA0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PRDATA0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PCLK1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PRESETn1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PENABLE1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PSEL1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PWRITE1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PADDR1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PWDATA1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/APBMux/PRDATA1
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/ARESETn
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/DMAReq
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/DMAAck
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/Interrupt
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/PENABLE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/PSEL
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/PWRITE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/PADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/PRDATA
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/ARID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/ARBURST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/RID
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/RREADY
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AWID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AWBURST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/WID
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/WREADY
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/BID
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/BREADY
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/PCLK0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/PRESETn0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/PENABLE0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/PSEL0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/PWRITE0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/PADDR0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/PWDATA0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/PRDATA0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/PCLK1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/PRESETn1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/PENABLE1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/PSEL1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/PWRITE1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/PADDR1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/PWDATA1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/PRDATA1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/ARVALID0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/ARREADY0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/ARADDR0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/ARLEN0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/ARSIZE0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/ARBURST0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/RDATA0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/RRESP0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/RLAST0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/RVALID0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/RREADY0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AWVALID0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AWREADY0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AWADDR0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AWLEN0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AWSIZE0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AWBURST0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/WDATA0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/WSTRB0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/WLAST0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/WVALID0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/WREADY0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/BRESP0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/BVALID0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/BREADY0
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/ARVALID1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/ARREADY1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/ARADDR1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/ARLEN1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/ARSIZE1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/ARBURST1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/RDATA1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/RRESP1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/RLAST1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/RVALID1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/RREADY1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AWVALID1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/AWREADY1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AWADDR1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AWLEN1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AWSIZE1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/AWBURST1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/WDATA1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/WSTRB1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/WLAST1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/WVALID1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/WREADY1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/Dmac2x2/BRESP1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/BVALID1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/BREADY1
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/PCLK
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/Dmac2x2/PRESETn
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/SRAM/CLK
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/SRAM/ADDR
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/SRAM/CEn
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/SRAM/WEn
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/SRAM/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/SRAM/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/SRAM/i
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/ARESETn
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/AWID
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/AWBURST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/WID
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/BID
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/BREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/ARID
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/ARBURST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/RID
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/RREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/MEMADDR
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/MEMCEn
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/MEMWEn
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/MEMRDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/MEMWDATA
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/nReadOrWrite
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/nReadOrWrite_P
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/Addr_P
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/Len_P
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/Size_P
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/Burst_P
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/ID_P
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/VALID_P
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/StartNewRequest
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/MuxedAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/MuxedLen
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/MuxedSize
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/MuxedBurst
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/MuxedId
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/RealnReadOrWrite
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/CanAcceptMoreRequest
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/StateIsIDLE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/State
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/NextState
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/StateIsREAD
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/StateIsWRITE
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/StateIsWAIT_RESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/SuccessiveRead
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/NextFirstREADCycle
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/Id
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/Addr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/Len
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/BurstLen
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/Size
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/Burst
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/FirstREADCycle
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/SuccessiveReadCondition
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/DecreaseLen
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/IntSRAMController/NextAddrCalcEn
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/IncreasedAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/PrevAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/WrapMask
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/IntSRAMController/IncrSize
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/ARESETn
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWID
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWBURST
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWLOCK
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWCACHE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWPROT
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/WID
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/BID
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/BREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARID
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARBURST
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARLOCK
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARCACHE
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARPROT
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/RID
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/RREADY
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWID_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWADDR_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWLEN_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWSIZE_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWBURST_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWLOCK_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWCACHE_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWPROT_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/WID_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/WDATA_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/WSTRB_r
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/WLAST_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARID_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARADDR_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARLEN_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARSIZE_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARBURST_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARLOCK_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARCACHE_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARPROT_r
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWQ_WINDEX
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/AWQ_RINDEX
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/AWQ_empty
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/WIDQ_WINDEX
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/WIDQ_RINDEX
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/WIDQ_full
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/WIDQ_empty
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/WDQ_RINDEX
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/WDQ_WINDEX
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/WDQ_empty
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARQ_WINDEX
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/ARQ_RINDEX
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/ARQ_empty
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/DecreaseWID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/DecreaseWIDEnable
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/IncreaseWID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/IncreaseWIDEnable
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/DecreaseRID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/DecreaseRIDEnable
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/IncreaseRID
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/IncreaseRIDEnable
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/AW_idle
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/AW_RANDOM
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/WD_idle
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/WD_RANDOM
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/AR_idle
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/AR_RANDOM
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/LAST_READ_DATA
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/i_rd
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/i_wid_temp
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/i_rid_temp
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/ResetIdleCnt
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/IdleCnt
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/src_addr_index
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/dst_addr_index
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/length_index
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/dst_width_index
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/src_width_index
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/size_index
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/small_or_large
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/SrcWidth
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/DstWidth
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/SrcAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/DstAddr
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/Size
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/Length
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/LengthTemp
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/MaxLength
add wave -noupdate -format Logic -radix hexadecimal /tb2x2Ch/TestMaster/TestNum
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/offset0
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/offset1
add wave -noupdate -format Literal -radix hexadecimal /tb2x2Ch/TestMaster/index
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
WaveRestoreZoom {0 ps} {310016 ps}
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
