#-------------------------------------------------------------------------------
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#-------------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.1
#-
#- Release Information    : PrimeCell(TM)-PL181-REL1v0
#-
#-------------------------------------------------------------------------------
#-  Purpose  :
#-             Standard Verilog Library Makefile
#-------------------------------------------------------------------------------

MODULES = MmciParams.v \
        MmciApbifReg.v \
        MmciSynctoMCLK.v \
        MmciSynctoPCLK.v \
        MmciRegUpd.v \
        MmciPwrClkCtr.v \
        MmciCPSM.v \
        MmciDPSM.v \
        MmciFIFOReg.v \
        MmciFifoDmaCtr.v \
        MmciIntGen.v \
        MmciOPReSync.v \
        MmciRevAnd.v \
        MmciClockAnd.v \
        MmciClockMux.v \
        Mmci.v

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

############################## End of file #####################################
