library verilog;
use verilog.vl_types.all;
entity mmc_decoder is
    port(
        mresetn         : in     vl_logic;
        mclk            : in     vl_logic;
        mcselect        : in     vl_logic;
        mcommand        : in     vl_logic_vector(47 downto 0);
        mcstate         : in     vl_logic_vector(4 downto 0);
        crc7_ok         : in     vl_logic;
        mspi_derr       : in     vl_logic;
        set_pwd         : in     vl_logic;
        lock_unlock_mode: in     vl_logic_vector(7 downto 0);
        pwd_match       : in     vl_logic;
        pwd_len_match   : in     vl_logic;
        pwd_stb         : in     vl_logic;
        clr_pwd         : in     vl_logic;
        card_is_locked  : out    vl_logic;
        index           : in     vl_logic_vector(7 downto 0);
        multi_write_block: in     vl_logic_vector(31 downto 0);
        multi_read_block: in     vl_logic_vector(31 downto 0);
        mext_csd        : in     vl_logic_vector(191 downto 0);
        switch_error    : out    vl_logic;
        wr_eol          : in     vl_logic;
        wr_field        : in     vl_logic_vector(3 downto 0);
        mrden           : in     vl_logic;
        block_len_error : out    vl_logic;
        mprot_up_data   : out    vl_logic_vector(31 downto 0);
        ismbw           : in     vl_logic;
        rd_eou          : in     vl_logic;
        wr_block_buffer_4word: in     vl_logic_vector(127 downto 0);
        wr_count        : in     vl_logic_vector(15 downto 0);
        cid_csd_overwrite: out    vl_logic;
        csd_update      : in     vl_logic_vector(127 downto 0);
        rd_field        : in     vl_logic_vector(3 downto 0);
        cmd_field       : in     vl_logic_vector(3 downto 0);
        cmd_eoe         : in     vl_logic;
        resp_eoe        : in     vl_logic;
        resp_eoe_d      : in     vl_logic;
        resp_eor        : in     vl_logic;
        rd_eol          : in     vl_logic;
        mgo_irq_state   : in     vl_logic;
        mwstb           : in     vl_logic;
        hbuswidth_cmd   : in     vl_logic_vector(31 downto 0);
        resp_cmd_error  : in     vl_logic;
        mcsd            : in     vl_logic_vector(127 downto 0);
        mdecode60       : in     vl_logic_vector(15 downto 0);
        mdecode61       : in     vl_logic_vector(15 downto 0);
        mdecode62       : in     vl_logic_vector(15 downto 0);
        mdecode63       : in     vl_logic_vector(15 downto 0);
        mcmddef         : in     vl_logic_vector(63 downto 0);
        mstatuscpu      : in     vl_logic_vector(31 downto 0);
        mstatuswr       : in     vl_logic;
        mstatuswren     : in     vl_logic_vector(31 downto 0);
        mblockmax       : in     vl_logic_vector(22 downto 0);
        mrblen          : in     vl_logic_vector(11 downto 0);
        mwblen          : in     vl_logic_vector(11 downto 0);
        meraseseq       : in     vl_logic_vector(8 downto 0);
        merasecmd       : in     vl_logic_vector(8 downto 0);
        mcardlock       : in     vl_logic;
        mcidfix         : in     vl_logic;
        mrca            : in     vl_logic_vector(15 downto 0);
        mlocken         : in     vl_logic_vector(63 downto 0);
        mstby_cmd2      : in     vl_logic;
        mstby_cmd3      : in     vl_logic;
        mbusy_cmd12     : in     vl_logic;
        mdecode         : out    vl_logic_vector(11 downto 0);
        mstatus         : out    vl_logic_vector(31 downto 0);
        mcommand_ok     : out    vl_logic;
        mcommand_ok_dly : out    vl_logic;
        mcommand_ok2    : out    vl_logic;
        mcommand_ok3wr  : out    vl_logic;
        no_response     : out    vl_logic;
        mrca_match      : out    vl_logic
    );
end mmc_decoder;
