library verilog;
use verilog.vl_types.all;
entity dmacchdstxfer is
    port(
        hclk            : in     vl_logic;
        hresetn         : in     vl_logic;
        dmacen          : in     vl_logic;
        busavlblm1      : in     vl_logic;
        busavlblm2      : in     vl_logic;
        dataerrorm1     : in     vl_logic;
        dataerrorm2     : in     vl_logic;
        xferabortedm1   : in     vl_logic;
        xferabortedm2   : in     vl_logic;
        setsrctcdone    : in     vl_logic;
        flowcntl        : in     vl_logic_vector(2 downto 0);
        trfsizedst      : in     vl_logic_vector(13 downto 0);
        dbsize          : in     vl_logic_vector(2 downto 0);
        dwidth2lsb      : in     vl_logic_vector(1 downto 0);
        srcselect       : in     vl_logic;
        dstselect       : in     vl_logic;
        desten          : in     vl_logic;
        lliaddressub    : in     vl_logic_vector(31 downto 2);
        channelen       : in     vl_logic;
        srcerred        : in     vl_logic;
        disabledsrc     : in     vl_logic;
        inttcenable     : in     vl_logic;
        fifofilllevel   : in     vl_logic_vector(4 downto 0);
        chdstbreq       : in     vl_logic;
        chdstlbreq      : in     vl_logic;
        chdstsreq       : in     vl_logic;
        chdstlsreq      : in     vl_logic;
        dststart        : in     vl_logic;
        dstdisable      : out    vl_logic;
        dsterr          : out    vl_logic;
        dectrfsizedst   : out    vl_logic;
        dstaddrupdate   : out    vl_logic;
        setdstaxsonmsk  : out    vl_logic;
        unsetdstaxsonmsk: out    vl_logic;
        setlliloadmsk   : out    vl_logic;
        seterrmskdst    : out    vl_logic;
        errcycmaskdst   : out    vl_logic;
        dmacclrdst      : out    vl_logic;
        dmactcdst       : out    vl_logic;
        setllireq       : out    vl_logic;
        abortreqdstm1   : out    vl_logic;
        abortreqdstm2   : out    vl_logic;
        setinttc        : out    vl_logic;
        dstnumofxfers   : out    vl_logic_vector(4 downto 0);
        dstburston      : out    vl_logic;
        dstfactor       : out    vl_logic_vector(2 downto 0);
        dstdmacstate    : out    vl_logic_vector(4 downto 0);
        axscntdst       : out    vl_logic_vector(4 downto 0);
        rdptrinc        : out    vl_logic
    );
end dmacchdstxfer;
