library verilog;
use verilog.vl_types.all;
entity DDRAi is
    generic(
        AW              : integer := 24;
        DW              : integer := 31;
        BW              : integer := 3;
        BL              : integer := 1;
        ID              : integer := 4;
        BBL             : integer := 3;
        WQCD            : integer := 4;
        WQD             : integer := 31;
        RQCD            : integer := 5;
        RQD             : integer := 63;
        WBLQCD          : integer := 2;
        WBLQD           : integer := 7;
        BBLQCD          : integer := 1;
        BBLQD           : integer := 3;
        RBLQCD          : integer := 3;
        RBLQD           : integer := 15;
        MDW             : integer := 15;
        DMW             : integer := 1;
        BAW             : integer := 1;
        RAW             : integer := 12;
        CAW             : integer := 10;
        RWW             : integer := 1;
        CD              : integer := 4;
        erc_powerup     : integer := 1;
        erc_epc         : integer := 2;
        erc_ar          : integer := 4;
        erc_mrs         : integer := 8;
        erc_idle        : integer := 16;
        erc_normal      : integer := 32;
        bc_null         : integer := 0;
        bc_mcas         : integer := 1;
        bc_mras         : integer := 2;
        bc_pc           : integer := 4;
        bc_sras         : integer := 8;
        bc_scas         : integer := 16;
        bc_epc          : integer := 32;
        ebc_null        : integer := 0;
        ebc_mcas        : integer := 1;
        ebc_mras        : integer := 2;
        ebc_pc          : integer := 4;
        ebc_sras        : integer := 8;
        ebc_scas        : integer := 16;
        ebc_epc         : integer := 32;
        ebc_bstop       : integer := 64;
        W_IDLE          : integer := 1;
        W_WDAT          : integer := 2;
        W_WREQ          : integer := 4;
        W_WSPI          : integer := 8;
        R_IDLE          : integer := 1;
        R_RREQ          : integer := 2;
        R_RSPI          : integer := 4;
        R_DIDLE         : integer := 1;
        R_DREQ          : integer := 2
    );
    port(
        ARESETB         : in     vl_logic;
        nPOR            : in     vl_logic;
        MCLK            : in     vl_logic;
        nMCLK           : in     vl_logic;
        ACLK            : in     vl_logic;
        nACLK           : in     vl_logic;
        AWAddr          : in     vl_logic_vector;
        AWId            : in     vl_logic_vector;
        AWLen           : in     vl_logic_vector;
        AWValid         : in     vl_logic;
        AWReady         : out    vl_logic;
        AWBurst         : in     vl_logic_vector(1 downto 0);
        WLast           : in     vl_logic;
        WStrb           : in     vl_logic_vector;
        WData           : in     vl_logic_vector;
        WValid          : in     vl_logic;
        WReady          : out    vl_logic;
        WId             : in     vl_logic_vector;
        BResp           : out    vl_logic_vector(1 downto 0);
        BValid          : out    vl_logic;
        BReady          : in     vl_logic;
        BId             : out    vl_logic_vector;
        ARAddr          : in     vl_logic_vector;
        ARId            : in     vl_logic_vector;
        ARLen           : in     vl_logic_vector;
        ARValid         : in     vl_logic;
        ARReady         : out    vl_logic;
        ARBurst         : in     vl_logic_vector(1 downto 0);
        RData           : out    vl_logic_vector;
        RValid          : out    vl_logic;
        RReady          : in     vl_logic;
        RLast           : out    vl_logic;
        RId             : out    vl_logic_vector;
        RResp           : out    vl_logic_vector(1 downto 0);
        RQFull          : out    vl_logic;
        WQFull          : out    vl_logic;
        BA_AA           : out    vl_logic_vector;
        BA_REQ          : out    vl_logic;
        BA_TT           : out    vl_logic_vector;
        BA_RW           : out    vl_logic;
        BA_ID           : out    vl_logic_vector;
        BA_PM           : out    vl_logic;
        DiValid         : in     vl_logic;
        DoValid         : in     vl_logic;
        QueEmp          : in     vl_logic;
        QueFul          : in     vl_logic;
        QueErr          : in     vl_logic;
        RdLast          : in     vl_logic;
        RdId            : in     vl_logic_vector;
        DqsoValid       : in     vl_logic;
        ColAddrSiz      : in     vl_logic_vector(1 downto 0);
        RdDataInSel     : in     vl_logic;
        RdDataPol       : in     vl_logic;
        SD_DQE          : out    vl_logic;
        SD_DQI          : in     vl_logic_vector;
        SD_DQO          : out    vl_logic_vector;
        SD_DQM          : out    vl_logic_vector;
        SD_DQSE         : out    vl_logic;
        SD_DQSO         : out    vl_logic_vector;
        SD_DQSI0        : in     vl_logic;
        SD_DQSI1        : in     vl_logic;
        nSD_DQSI0       : in     vl_logic;
        nSD_DQSI1       : in     vl_logic
    );
end DDRAi;
