#! /bin/sh
action()
{
  $* || exit 1
}

RTL_PATH=../rtl

action vlog $RTL_PATH/AXIBUS/ReadChannel/AHB0_ReqCnt.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/AHB1_ReqCnt.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/DDR_ReqCnt.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/APB0_ReqCnt.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/APB1_ReqCnt.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/SMC_ReqCnt.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/SSRAM_ReqCnt.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/default_ReqCnt.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/AHB0_LockCtlRdmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/AHB1_LockCtlRdmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/DDR_LockCtlRdmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/APB0_LockCtlRdmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/APB1_LockCtlRdmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/SMC_LockCtlRdmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/SSRAM_LockCtlRdmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/default_LockCtlRdmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/AHB0_ReadChannelmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/AHB1_ReadChannelmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/DDR_ReadChannelmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/APB0_ReadChannelmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/APB1_ReadChannelmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/SMC_ReadChannelmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/SSRAM_ReadChannelmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/default_ReadChannelmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/ARMD_ReadChannelsi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RDCH_ARMD_PermitCtl.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/ARMI_ReadChannelsi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RDCH_ARMI_PermitCtl.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/DMAC_ReadChannelsi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RDCH_DMAC_PermitCtl.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/MAC_ReadChannelsi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RDCH_MAC_PermitCtl.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/PCI_ReadChannelsi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RDCH_PCI_PermitCtl.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/TOP/ReadChannel.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/AHB0_ReqInter.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/AHB1_ReqInter.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/DDR_ReqInter.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/APB0_ReqInter.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/APB1_ReqInter.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/SMC_ReqInter.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/SSRAM_ReqInter.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/default_ReqInter.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/AHB0_LockCtlWrmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/AHB1_LockCtlWrmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/DDR_LockCtlWrmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/APB0_LockCtlWrmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/APB1_LockCtlWrmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/SMC_LockCtlWrmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/SSRAM_LockCtlWrmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/default_LockCtlWrmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/AHB0_WriteChannelmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/AHB1_WriteChannelmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/DDR_WriteChannelmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/APB0_WriteChannelmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/APB1_WriteChannelmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/SMC_WriteChannelmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/SSRAM_WriteChannelmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/default_WriteChannelmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/ARMD_WriteChannelsi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/WRCH_ARMD_PermitCtl.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/DMAC_WriteChannelsi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/WRCH_DMAC_PermitCtl.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/MAC_WriteChannelsi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/WRCH_MAC_PermitCtl.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/PCI_WriteChannelsi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/WRCH_PCI_PermitCtl.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/TOP/WriteChannel.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/ARMD_RS_WriteChannelsi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/ARMD_AWSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/ARMD_WDSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/ARMD_WRSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/ARMD_AWSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/ARMD_WDSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/ARMD_WRSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/ARMD_RS_ReadChannelsi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/ARMD_ARSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/ARMD_RDSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/ARMD_ARSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/ARMD_RDSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/ARMI_RS_ReadChannelsi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/ARMI_ARSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/ARMI_RDSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/ARMI_ARSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/ARMI_RDSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/DMAC_RS_WriteChannelsi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/DMAC_AWSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/DMAC_WDSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/DMAC_WRSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/DMAC_RS_ReadChannelsi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/DMAC_ARSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/DMAC_RDSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/MAC_RS_WriteChannelsi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/MAC_AWSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/MAC_WDSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/MAC_WRSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/MAC_AWSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/MAC_WDSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/MAC_WRSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/MAC_RS_ReadChannelsi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/MAC_ARSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/MAC_RDSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/MAC_ARSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/MAC_RDSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/PCI_RS_WriteChannelsi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/PCI_AWSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/PCI_WDSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/PCI_WRSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/PCI_AWSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/PCI_WDSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/PCI_WRSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/PCI_RS_ReadChannelsi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/PCI_ARSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/PCI_RDSIm2si_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/PCI_ARSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/PCI_RDSIsi2mi_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/AHB0_RS_WriteChannelmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/AHB0_RS_ReadChannelmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/AHB0_AWMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/AHB0_WDMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/AHB0_WRMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/AHB0_ARMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/AHB0_RDMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/AHB1_RS_WriteChannelmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/AHB1_RS_ReadChannelmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/AHB1_AWMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/AHB1_WDMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/AHB1_WRMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/AHB1_ARMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/AHB1_RDMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/DDR_RS_WriteChannelmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/DDR_RS_ReadChannelmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/DDR_AWMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/DDR_WDMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/DDR_WRMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/DDR_ARMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/DDR_RDMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/APB0_RS_WriteChannelmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/APB0_RS_ReadChannelmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/APB0_AWMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/APB0_WDMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/APB0_WRMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/APB0_ARMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/APB0_RDMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/APB1_RS_WriteChannelmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/APB1_RS_ReadChannelmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/APB1_AWMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/APB1_WDMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/APB1_WRMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/APB1_ARMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/APB1_RDMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/SMC_RS_WriteChannelmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/SMC_RS_ReadChannelmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/SMC_AWMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/SMC_WDMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/SMC_WRMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/SMC_ARMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/SMC_RDMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/SSRAM_RS_WriteChannelmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/SSRAM_RS_ReadChannelmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/SSRAM_AWMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/SSRAM_WDMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/SSRAM_WRMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/SSRAM_ARMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/SSRAM_RDMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/default_RS_WriteChannelmi.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/default_RS_ReadChannelmi.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/default_AWMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/default_WDMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/WriteChannel/RegisterSlice/default_WRMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/default_ARMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/ReadChannel/RegisterSlice/default_RDMImi2s_registered.v
action vlog $RTL_PATH/AXIBUS/TOP/SBUS.v


