library verilog;
use verilog.vl_types.all;
entity serdes_field is
    generic(
        ifield          : integer := 0;
        sfield          : integer := 1;
        tfield          : integer := 2;
        xfield          : integer := 3;
        afield          : integer := 4;
        cfield          : integer := 5;
        efield          : integer := 6;
        hfield          : integer := 7;
        rfield          : integer := 8;
        lfield          : integer := 9;
        dfield          : integer := 10;
        ufield          : integer := 11;
        bfield          : integer := 12;
        pfield          : integer := 13;
        gfield          : integer := 14;
        ssbw            : integer := 254;
        smbw            : integer := 252;
        tmbw            : integer := 253
    );
    port(
        mresetn         : in     vl_logic;
        hstandby        : in     vl_logic;
        msreset         : in     vl_logic;
        mcs             : in     vl_logic;
        mclk            : in     vl_logic;
        mcmdin          : in     vl_logic;
        mdatin          : in     vl_logic;
        mcselect        : in     vl_logic;
        busy_clear      : in     vl_logic;
        mrden           : in     vl_logic;
        mwstb_4word     : out    vl_logic;
        mwstb_16word    : out    vl_logic;
        mwstb_128word   : out    vl_logic;
        wr_word_count   : out    vl_logic_vector(7 downto 0);
        wr_4word_count  : out    vl_logic_vector(7 downto 0);
        wr_16word_count : out    vl_logic_vector(7 downto 0);
        wr_128word_count: out    vl_logic_vector(7 downto 0);
        single_write_command: out    vl_logic;
        multi_write_command: out    vl_logic;
        single_read_command: out    vl_logic;
        multi_read_command: out    vl_logic;
        mcstatewr       : in     vl_logic_vector(2 downto 0);
        start_block     : out    vl_logic_vector(22 downto 0);
        multi_write_block: out    vl_logic_vector(31 downto 0);
        multi_read_block: out    vl_logic_vector(31 downto 0);
        mrstb_4word     : out    vl_logic;
        mrstb_16word    : out    vl_logic;
        mrstb_128word   : out    vl_logic;
        rd_word_count   : out    vl_logic_vector(7 downto 0);
        rd_4word_count  : out    vl_logic_vector(7 downto 0);
        rd_16word_count : out    vl_logic_vector(7 downto 0);
        rd_128word_count: out    vl_logic_vector(7 downto 0);
        mrstb           : out    vl_logic;
        mrstb_3d        : out    vl_logic;
        mrstb_4d        : out    vl_logic;
        wr_count        : out    vl_logic_vector(15 downto 0);
        \Access\        : out    vl_logic_vector(1 downto 0);
        index           : out    vl_logic_vector(7 downto 0);
        value           : out    vl_logic_vector(7 downto 0);
        last_block      : out    vl_logic;
        wr_eol          : out    vl_logic;
        resp_eox        : out    vl_logic;
        cmd_eoe_d       : out    vl_logic;
        mcstate         : in     vl_logic_vector(4 downto 0);
        mdecode         : in     vl_logic_vector(11 downto 0);
        mspi_derr       : in     vl_logic;
        mcommand        : in     vl_logic_vector(47 downto 0);
        mcommand_ok     : in     vl_logic;
        mstatus         : in     vl_logic_vector(31 downto 0);
        mtmbw           : out    vl_logic;
        \MRSTB\         : out    vl_logic;
        mwstb           : out    vl_logic;
        \MRDEN\         : in     vl_logic;
        mnid            : in     vl_logic_vector(7 downto 0);
        mncrmmc         : in     vl_logic_vector(7 downto 0);
        mncrspi         : in     vl_logic_vector(7 downto 0);
        mbsyend         : in     vl_logic;
        mwblen          : in     vl_logic_vector(11 downto 0);
        mrblen          : in     vl_logic_vector(11 downto 0);
        mbsybwcmd       : in     vl_logic;
        mwakeupen       : in     vl_logic;
        mcmdirqen       : in     vl_logic_vector(15 downto 0);
        mrespirqen      : in     vl_logic_vector(15 downto 0);
        mwrirqen        : in     vl_logic_vector(15 downto 0);
        mrdirqen        : in     vl_logic_vector(15 downto 0);
        mwrforce        : in     vl_logic;
        mrdforce        : in     vl_logic;
        no_response     : in     vl_logic;
        crc16_ok        : in     vl_logic;
        mdatain_buf     : in     vl_logic_vector(7 downto 0);
        cmd_field       : out    vl_logic_vector(3 downto 0);
        resp_field      : out    vl_logic_vector(3 downto 0);
        resp_field_n    : out    vl_logic_vector(3 downto 0);
        wr_field        : out    vl_logic_vector(3 downto 0);
        rd_field        : out    vl_logic_vector(3 downto 0);
        rd_field_n      : out    vl_logic_vector(3 downto 0);
        resp_idxup      : out    vl_logic;
        resp_argup      : out    vl_logic_vector(3 downto 0);
        rd_stop         : out    vl_logic;
        rd_uup          : out    vl_logic;
        rd_uup_status   : out    vl_logic;
        rd_lup          : out    vl_logic;
        wr_eobyte       : out    vl_logic;
        resp_r1up       : out    vl_logic;
        resp_r2up       : out    vl_logic;
        resp_r3up       : out    vl_logic;
        cmd_soh         : out    vl_logic;
        cmd_eox_n       : out    vl_logic;
        cmd_eoe         : out    vl_logic;
        cmd_eoe_n       : out    vl_logic;
        resp_eoe        : out    vl_logic;
        resp_eoe_n      : out    vl_logic;
        resp_eoe_d      : out    vl_logic;
        resp_eor        : out    vl_logic;
        resp_eor_n      : out    vl_logic;
        resp_eor_d      : out    vl_logic;
        wr_eoc          : out    vl_logic;
        rd_csupdate     : out    vl_logic;
        rd_eol          : out    vl_logic;
        rd_eou          : out    vl_logic;
        rd_eob          : out    vl_logic;
        rd_eoc          : out    vl_logic;
        rd_eobusy       : out    vl_logic;
        cmd_start       : out    vl_logic;
        resp_start      : out    vl_logic;
        wr_start        : out    vl_logic;
        rd_start        : out    vl_logic;
        issbw           : out    vl_logic;
        ismbw           : out    vl_logic;
        itmbw           : out    vl_logic;
        mcmdirqwr       : out    vl_logic_vector(14 downto 0);
        mrespirqwr      : out    vl_logic_vector(14 downto 0);
        mwrirqwr        : out    vl_logic_vector(14 downto 0);
        mrdirqwr        : out    vl_logic_vector(14 downto 0);
        mwakeup         : out    vl_logic;
        mirq            : out    vl_logic_vector(3 downto 0);
        mprefix         : out    vl_logic_vector(7 downto 0);
        mresp_end       : out    vl_logic;
        resp_cmd_error  : in     vl_logic;
        bus8            : in     vl_logic;
        bus4            : in     vl_logic;
        bus1            : in     vl_logic;
        rd_count        : out    vl_logic_vector(15 downto 0);
        rd_count_n      : out    vl_logic_vector(15 downto 0)
    );
end serdes_field;
