# Generated by vmake version 2.0

# Define path to each library
LIB_WORK = work

# Define path to each design unit
WORK-Lite2AHB = $(LIB_WORK)/@lite2@a@h@b/_primary.dat
WORK-FileReader = $(LIB_WORK)/@file@reader/_primary.dat
WORK-FileReadCore = $(LIB_WORK)/@file@read@core/_primary.dat
VCOM = vcom
VLOG = vlog

whole_library :     $(WORK-Lite2AHB) \
    $(WORK-FileReader) \
    $(WORK-FileReadCore)

$(WORK-FileReadCore) : FileReadCore.v
	$(VLOG) -compat FileReadCore.v

$(WORK-FileReader) : FileReader.v
	$(VLOG) -compat FileReader.v

$(WORK-Lite2AHB) : /user/ysjoo/ip/ADK/BP010-BU-01001-1.01/ARM_ADK_REL1v1/design/global_ADK/verilog/Lite2AHB.v
	$(VLOG) -compat /user/ysjoo/ip/ADK/BP010-BU-01001-1.01/ARM_ADK_REL1v1/design/global_ADK/verilog/Lite2AHB.v
