#! /bin/sh

action()
{
  $* || exit 1
}

if [ -e work ]; then
    rm -fr work
fi
action vlib work

action vlog ../rtl/BUS/ReadChannel/DDRCtrl_ReqCnt.v
action vlog ../rtl/BUS/ReadChannel/APB0_ReqCnt.v
action vlog ../rtl/BUS/ReadChannel/APB1_ReqCnt.v
action vlog ../rtl/BUS/ReadChannel/SMC_ReqCnt.v
action vlog ../rtl/BUS/ReadChannel/IntSRAM_ReqCnt.v
action vlog ../rtl/BUS/ReadChannel/default_ReqCnt.v
action vlog ../rtl/BUS/ReadChannel/DDRCtrl_LockCtlRdmi.v
action vlog ../rtl/BUS/ReadChannel/APB0_LockCtlRdmi.v
action vlog ../rtl/BUS/ReadChannel/APB1_LockCtlRdmi.v
action vlog ../rtl/BUS/ReadChannel/SMC_LockCtlRdmi.v
action vlog ../rtl/BUS/ReadChannel/IntSRAM_LockCtlRdmi.v
action vlog ../rtl/BUS/ReadChannel/default_LockCtlRdmi.v
action vlog ../rtl/BUS/ReadChannel/DDRCtrl_ReadChannelmi.v
action vlog ../rtl/BUS/ReadChannel/APB0_ReadChannelmi.v
action vlog ../rtl/BUS/ReadChannel/APB1_ReadChannelmi.v
action vlog ../rtl/BUS/ReadChannel/SMC_ReadChannelmi.v
action vlog ../rtl/BUS/ReadChannel/IntSRAM_ReadChannelmi.v
action vlog ../rtl/BUS/ReadChannel/default_ReadChannelmi.v
action vlog ../rtl/BUS/ReadChannel/ARM_ReadChannelsi.v
action vlog ../rtl/BUS/ReadChannel/RDCH_ARM_PermitCtl.v
action vlog ../rtl/BUS/ReadChannel/DisplayCtrl_ReadChannelsi.v
action vlog ../rtl/BUS/ReadChannel/RDCH_DisplayCtrl_PermitCtl.v
action vlog ../rtl/BUS/ReadChannel/DMACtrl_ReadChannelsi.v
action vlog ../rtl/BUS/ReadChannel/RDCH_DMACtrl_PermitCtl.v
action vlog ../rtl/BUS/ReadChannel/TOP/ReadChannel.v
action vlog ../rtl/BUS/WriteChannel/DDRCtrl_ReqInter.v
action vlog ../rtl/BUS/WriteChannel/APB0_ReqInter.v
action vlog ../rtl/BUS/WriteChannel/APB1_ReqInter.v
action vlog ../rtl/BUS/WriteChannel/SMC_ReqInter.v
action vlog ../rtl/BUS/WriteChannel/IntSRAM_ReqInter.v
action vlog ../rtl/BUS/WriteChannel/default_ReqInter.v
action vlog ../rtl/BUS/WriteChannel/DDRCtrl_LockCtlWrmi.v
action vlog ../rtl/BUS/WriteChannel/APB0_LockCtlWrmi.v
action vlog ../rtl/BUS/WriteChannel/APB1_LockCtlWrmi.v
action vlog ../rtl/BUS/WriteChannel/SMC_LockCtlWrmi.v
action vlog ../rtl/BUS/WriteChannel/IntSRAM_LockCtlWrmi.v
action vlog ../rtl/BUS/WriteChannel/default_LockCtlWrmi.v
action vlog ../rtl/BUS/WriteChannel/DDRCtrl_WriteChannelmi.v
action vlog ../rtl/BUS/WriteChannel/APB0_WriteChannelmi.v
action vlog ../rtl/BUS/WriteChannel/APB1_WriteChannelmi.v
action vlog ../rtl/BUS/WriteChannel/SMC_WriteChannelmi.v
action vlog ../rtl/BUS/WriteChannel/IntSRAM_WriteChannelmi.v
action vlog ../rtl/BUS/WriteChannel/default_WriteChannelmi.v
action vlog ../rtl/BUS/WriteChannel/ARM_WriteChannelsi.v
action vlog ../rtl/BUS/WriteChannel/WRCH_ARM_PermitCtl.v
action vlog ../rtl/BUS/WriteChannel/DMACtrl_WriteChannelsi.v
action vlog ../rtl/BUS/WriteChannel/WRCH_DMACtrl_PermitCtl.v
action vlog ../rtl/BUS/WriteChannel/VideoIn_WriteChannelsi.v
action vlog ../rtl/BUS/WriteChannel/WRCH_VideoIn_PermitCtl.v
action vlog ../rtl/BUS/WriteChannel/TOP/WriteChannel.v
action vlog ../rtl/BUS/WriteChannel/ARM_RS_WriteChannelsi.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/ARM_AWSIm2si_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/ARM_WDSIm2si_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/ARM_WRSIm2si_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/ARM_AWSIsi2mi_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/ARM_WDSIsi2mi_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/ARM_WRSIsi2mi_registered.v
action vlog ../rtl/BUS/ReadChannel/ARM_RS_ReadChannelsi.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/ARM_ARSIm2si_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/ARM_RDSIm2si_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/ARM_ARSIsi2mi_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/ARM_RDSIsi2mi_registered.v
action vlog ../rtl/BUS/ReadChannel/DisplayCtrl_RS_ReadChannelsi.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/DisplayCtrl_ARSIm2si_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/DisplayCtrl_RDSIm2si_registered.v
action vlog ../rtl/BUS/WriteChannel/DMACtrl_RS_WriteChannelsi.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/DMACtrl_AWSIm2si_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/DMACtrl_WDSIm2si_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/DMACtrl_WRSIm2si_registered.v
action vlog ../rtl/BUS/ReadChannel/DMACtrl_RS_ReadChannelsi.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/DMACtrl_ARSIm2si_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/DMACtrl_RDSIm2si_registered.v
action vlog ../rtl/BUS/WriteChannel/VideoIn_RS_WriteChannelsi.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/VideoIn_AWSIm2si_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/VideoIn_WDSIm2si_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/VideoIn_WRSIm2si_registered.v
action vlog ../rtl/BUS/WriteChannel/DDRCtrl_RS_WriteChannelmi.v
action vlog ../rtl/BUS/ReadChannel/DDRCtrl_RS_ReadChannelmi.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/DDRCtrl_AWMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/DDRCtrl_WDMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/DDRCtrl_WRMImi2s_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/DDRCtrl_ARMImi2s_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/DDRCtrl_RDMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/APB0_RS_WriteChannelmi.v
action vlog ../rtl/BUS/ReadChannel/APB0_RS_ReadChannelmi.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/APB0_AWMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/APB0_WDMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/APB0_WRMImi2s_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/APB0_ARMImi2s_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/APB0_RDMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/APB1_RS_WriteChannelmi.v
action vlog ../rtl/BUS/ReadChannel/APB1_RS_ReadChannelmi.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/APB1_AWMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/APB1_WDMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/APB1_WRMImi2s_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/APB1_ARMImi2s_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/APB1_RDMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/SMC_RS_WriteChannelmi.v
action vlog ../rtl/BUS/ReadChannel/SMC_RS_ReadChannelmi.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/SMC_AWMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/SMC_WDMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/SMC_WRMImi2s_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/SMC_ARMImi2s_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/SMC_RDMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/IntSRAM_RS_WriteChannelmi.v
action vlog ../rtl/BUS/ReadChannel/IntSRAM_RS_ReadChannelmi.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/IntSRAM_AWMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/IntSRAM_WDMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/IntSRAM_WRMImi2s_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/IntSRAM_ARMImi2s_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/IntSRAM_RDMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/default_RS_WriteChannelmi.v
action vlog ../rtl/BUS/ReadChannel/default_RS_ReadChannelmi.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/default_AWMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/default_WDMImi2s_registered.v
action vlog ../rtl/BUS/WriteChannel/RegisterSlice/default_WRMImi2s_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/default_ARMImi2s_registered.v
action vlog ../rtl/BUS/ReadChannel/RegisterSlice/default_RDMImi2s_registered.v
action vlog ../rtl/BUS/TOP/SBUS.v
action vlog ../bench/tb.v
action vlog ../bench/ARM_TestMaster_bus.v
action vlog ../bench/DisplayCtrl_TestMaster_bus.v
action vlog ../bench/DMACtrl_TestMaster_bus.v
action vlog ../bench/VideoIn_TestMaster_bus.v
action vlog ../bench/DDRCtrl_IntSRAMController.v
action vlog ../bench/APB0_IntSRAMController.v
action vlog ../bench/APB1_IntSRAMController.v
action vlog ../bench/SMC_IntSRAMController.v
action vlog ../bench/IntSRAM_IntSRAMController.v
action vlog ../bench/DDRCtrl_SSRAM32bit.v
action vlog ../bench/APB0_SSRAM32bit.v
action vlog ../bench/APB1_SSRAM32bit.v
action vlog ../bench/SMC_SSRAM32bit.v
action vlog ../bench/IntSRAM_SSRAM32bit.v
action vlog ../bench/DefaultSlave.v
action vlog ../bench/SSRAM32bit.v
action vlog ../rtl/BUS/protocol_checker/AxiPC.v
action vlog ../rtl/BUS/std_ovl/assert_implication.vlib
action vlog ../rtl/BUS/std_ovl/assert_next.vlib
action vlog ../rtl/BUS/std_ovl/assert_win_unchange.vlib
action vlog ../rtl/BUS/std_ovl/assert_frame.vlib
action vlog ../rtl/BUS/std_ovl/assert_never.vlib
action vlog ../rtl/BUS/std_ovl/assert_always.vlib
action vlog ../rtl/BUS/std_ovl/assert_frame.vlib
action vlog ../rtl/BUS/std_ovl/assert_quiescent_state.vlib
action vlog ../rtl/BUS/std_ovl/assert_proposition.vlib
vsim -c tb -do "run -all"
