#! /bin/sh
#-------------------------------------------------------------------------------
#-  This confidential and proprietary software may be used only as
#-  authorised by a licensing agreement from ARM Limited
#-    (C) COPYRIGHT 1999 ARM Limited
#-        ALL RIGHTS RESERVED
#-  The entire notice above must be reproduced on all authorised
#-  copies and copies may only be made to the extent permitted
#-  by a licensing agreement from ARM Limited.
#-------------------------------------------------------------------------------
#-
#-  Version and Release Control Information:
#-
#-  File Name              : cpy_vect,v
#-  File Revision          : 1.3
#-
#-  Release Information    : PrimeCell(TM)-PL170-REL2v2
#-
#-------------------------------------------------------------------------------
 
#-------------------------------------------------------------------------------
# Purpose : Script to generate .bif or .tif file
#-------------------------------------------------------------------------------

echo "Env variable VECT_TYPE currently set to \" $VECT_TYPE \" "

if [ "$VECT_TYPE" = TIF ]
then
    echo "Creating $1/$2.tif" 
    cp $1/$2.tmp $1/$2.tif
else
    echo "Creating $1/$2.bif" 
    cp $1/$2.tmp $1/$2.bif
fi
 
