----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date:    23:44:31 12/02/2006 
-- Design Name: 
-- Module Name:    UART_TEST - Behavioral 
-- Project Name: 
-- Target Devices: 
-- Tool versions: 
-- Description: 
--
-- Dependencies: 
--
-- Revision: 
-- Revision 0.01 - File Created
-- Additional Comments: 
--
----------------------------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY UART_TEST IS
	PORT ( CLK, nRST : IN STD_LOGIC;
		TXD     : OUT STD_LOGIC;
		TXD1    : OUT STD_LOGIC;
		RXD1    : IN STD_LOGIC;
		SEG_DATA : OUT STD_LOGIC_VECTOR( 0 TO 7 );
		SEG_COM  : OUT STD_LOGIC_VECTOR( 0 TO 3 )
	     );
END UART_TEST;

ARCHITECTURE RTL OF UART_TEST IS
--================ USER SETTING ==================
	CONSTANT CLK_IN : INTEGER := 25000000;  --  INPUT CLOCK
	CONSTANT TXCLK : INTEGER := 4800;	--  TXD-9600 [bit/sec]	
---------------------------------------------------
	TYPE STATUS IS ( IDLE, START, BIT0, BIT1, BIT2, BIT3, BIT4, BIT5, BIT6, BIT7, STOP );
	SIGNAL STATE : STATUS;

	SIGNAL COUNT : INTEGER RANGE 0 TO 63;	
	SIGNAL TX_CLK : STD_LOGIC;
	SIGNAL FONT : STD_LOGIC_VECTOR( 7 DOWNTO 0 );
	
	CONSTANT SEG_0 : STD_LOGIC_VECTOR( 0 TO 7 ):="11111100";
	CONSTANT SEG_1 : STD_LOGIC_VECTOR( 0 TO 7 ):="01100000";
	CONSTANT SEG_2 : STD_LOGIC_VECTOR( 0 TO 7 ):="11011010";
	CONSTANT SEG_3 : STD_LOGIC_VECTOR( 0 TO 7 ):="11110010";
	CONSTANT SEG_4 : STD_LOGIC_VECTOR( 0 TO 7 ):="01100110";
	CONSTANT SEG_5 : STD_LOGIC_VECTOR( 0 TO 7 ):="10110110";
	CONSTANT SEG_6 : STD_LOGIC_VECTOR( 0 TO 7 ):="00111110";
	CONSTANT SEG_7 : STD_LOGIC_VECTOR( 0 TO 7 ):="11100000";
	CONSTANT SEG_8 : STD_LOGIC_VECTOR( 0 TO 7 ):="11111110";
	CONSTANT SEG_9 : STD_LOGIC_VECTOR( 0 TO 7 ):="11100110";
	CONSTANT SEG_A : STD_LOGIC_VECTOR( 0 TO 7 ):="11101110";
	CONSTANT SEG_B : STD_LOGIC_VECTOR( 0 TO 7 ):="00111110";
	CONSTANT SEG_C : STD_LOGIC_VECTOR( 0 TO 7 ):="10011100";
	CONSTANT SEG_D : STD_LOGIC_VECTOR( 0 TO 7 ):="01111010";
	CONSTANT SEG_E : STD_LOGIC_VECTOR( 0 TO 7 ):="10011110";
	CONSTANT SEG_F : STD_LOGIC_VECTOR( 0 TO 7 ):="10001110";
	
	CONSTANT SCAN_0 : STD_LOGIC_VECTOR( 3 DOWNTO 0 ):="1110";
	CONSTANT SCAN_1 : STD_LOGIC_VECTOR( 3 DOWNTO 0 ):="1101";
	CONSTANT SCAN_2 : STD_LOGIC_VECTOR( 3 DOWNTO 0 ):="1011";
	CONSTANT SCAN_3 : STD_LOGIC_VECTOR( 3 DOWNTO 0 ):="0111";

	CONSTANT ASCII_0 : STD_LOGIC_VECTOR(7 DOWNTO 0) := "00110000";
	CONSTANT ASCII_1 : STD_LOGIC_VECTOR(7 DOWNTO 0) := "00110001";
	CONSTANT ASCII_2 : STD_LOGIC_VECTOR(7 DOWNTO 0) := "00110010";
	CONSTANT ASCII_3 : STD_LOGIC_VECTOR(7 DOWNTO 0) := "00110011";
	CONSTANT ASCII_4 : STD_LOGIC_VECTOR(7 DOWNTO 0) := "00110100";
	CONSTANT ASCII_5 : STD_LOGIC_VECTOR(7 DOWNTO 0) := "00110101";
	CONSTANT ASCII_6 : STD_LOGIC_VECTOR(7 DOWNTO 0) := "00110110";
	CONSTANT ASCII_7 : STD_LOGIC_VECTOR(7 DOWNTO 0) := "00110111";
	CONSTANT ASCII_8 : STD_LOGIC_VECTOR(7 DOWNTO 0) := "00111000";
	CONSTANT ASCII_9 : STD_LOGIC_VECTOR(7 DOWNTO 0) := "00111001";

	CONSTANT ASCII_LA : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01000001";
	CONSTANT ASCII_LB : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01000010";
	CONSTANT ASCII_LC : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01000011";
	CONSTANT ASCII_LD : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01000100";
	CONSTANT ASCII_LE : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01000101";
	CONSTANT ASCII_LF : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01000110";
	CONSTANT ASCII_LG : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01000111";
	CONSTANT ASCII_LH : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01001000";
	CONSTANT ASCII_LI : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01001001";
	CONSTANT ASCII_LJ : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01001010";
	CONSTANT ASCII_LK : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01001011";
	CONSTANT ASCII_LL : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01001100";
	CONSTANT ASCII_LM : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01001101";
	CONSTANT ASCII_LN : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01001110";
	CONSTANT ASCII_LO : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01001111";
	CONSTANT ASCII_LP : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01010000";
	CONSTANT ASCII_LQ : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01010001";
	CONSTANT ASCII_LR : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01010010";
	CONSTANT ASCII_LS : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01010011";
	CONSTANT ASCII_LT : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01010100";
	CONSTANT ASCII_LU : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01010101";
	CONSTANT ASCII_LV : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01010110";
	CONSTANT ASCII_LW : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01010111";
	CONSTANT ASCII_LX : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01011000";
	CONSTANT ASCII_LY : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01011001";
	CONSTANT ASCII_LZ : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01011010";
	
	CONSTANT ASCII_SA : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01100001";
	CONSTANT ASCII_SB : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01100010";
	CONSTANT ASCII_SC : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01100011";
	CONSTANT ASCII_SD : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01100100";
	CONSTANT ASCII_SE : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01100101";
	CONSTANT ASCII_SF : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01100110";
	CONSTANT ASCII_SG : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01100111";
	CONSTANT ASCII_SH : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01101000";
	CONSTANT ASCII_SI : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01101001";
	CONSTANT ASCII_SJ : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01101010";
	CONSTANT ASCII_SK : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01101011";
	CONSTANT ASCII_SL : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01101100";
	CONSTANT ASCII_SM : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01101101";
	CONSTANT ASCII_SN : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01101110";
	CONSTANT ASCII_SO : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01101111";
	CONSTANT ASCII_SP : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01110000";
	CONSTANT ASCII_SQ : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01110001";
	CONSTANT ASCII_SR : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01110010";
	CONSTANT ASCII_SS : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01110011";
	CONSTANT ASCII_ST : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01110100";
	CONSTANT ASCII_SU : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01110101";
	CONSTANT ASCII_SV : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01110110";
	CONSTANT ASCII_SW : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01110111";
	CONSTANT ASCII_SX : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01111000";
	CONSTANT ASCII_SY : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01111001";
	CONSTANT ASCII_SZ : STD_LOGIC_VECTOR(7 DOWNTO 0) := "01111010";
	
	CONSTANT CR : STD_LOGIC_VECTOR( 7 DOWNTO 0 ) := "00001101";
	CONSTANT LF : STD_LOGIC_VECTOR( 7 DOWNTO 0 ) := "00001010";
	CONSTANT UN : STD_LOGIC_VECTOR( 7 DOWNTO 0 ) := "01011111";
	CONSTANT BL : STD_LOGIC_VECTOR( 7 DOWNTO 0 ) := "00100000";
	CONSTANT CO : STD_LOGIC_VECTOR( 7 DOWNTO 0 ) := "00111010";
	CONSTANT DA : STD_LOGIC_VECTOR( 7 DOWNTO 0 ) := "00101101";

	TYPE RX_STATUS IS ( RX_IDLE, RX_START, RX_BIT0, RX_BIT1, RX_BIT2, RX_BIT3, RX_BIT4, RX_BIT5, RX_BIT6, RX_BIT7, RX_STOP );
	SIGNAL RX_STATE : RX_STATUS;
	
	SIGNAL RXD_DATA_BUF : STD_LOGIC_VECTOR( 7 DOWNTO 0 );
	SIGNAL RXD_DATA : STD_LOGIC_VECTOR( 7 DOWNTO 0 );
	
	SIGNAL SEG_RXD0, SEG_RXD1, SEG_TXD0, SEG_TXD1 : STD_LOGIC_VECTOR( 3 DOWNTO 0 );
	SIGNAL SEG_CLK : STD_LOGIC;
	SIGNAL SEG_SCAN_SIG : STD_LOGIC_VECTOR( 3 DOWNTO 0 );
	SIGNAL SEG_DAT : STD_LOGIC_VECTOR( 3 DOWNTO 0 );
	
	SIGNAL DELAY : INTEGER RANGE 0 TO 9600;
	SIGNAL EN : STD_LOGIC;
	
BEGIN

	PROCESS( CLK, nRST )
		VARIABLE CNT : INTEGER RANGE 0 TO CLK_IN;
	BEGIN
		IF nRST='0' THEN
			CNT := 0;
			TX_CLK <= '0';
		ELSIF RISING_EDGE(CLK) THEN
			IF ( CNT < 1302) THEN
					CNT := CNT + 1;
				ELSE
					CNT := 0;
					TX_CLK <= NOT TX_CLK;
			END IF;
		END IF;
	END PROCESS;

	PROCESS( TX_CLK, nRST )
	BEGIN
		IF nRST='0' THEN
			RXD_DATA_BUF <= ( OTHERS => '0' );
			RX_STATE <= RX_IDLE;
			RXD_DATA <= ( OTHERS => '0' );
		ELSIF RISING_EDGE(TX_CLK) THEN
			CASE RX_STATE IS
				WHEN RX_IDLE => IF RXD1='0' THEN
									RX_STATE <= RX_START;
								 ELSE
									RX_STATE <= RX_IDLE;
								 END IF;
				WHEN RX_START => RX_STATE <= RX_BIT0;
									RXD_DATA_BUF(0) <= RXD1;
				WHEN RX_BIT0 => RX_STATE <= RX_BIT1;
									 RXD_DATA_BUF(1) <= RXD1;
				WHEN RX_BIT1 => RX_STATE <= RX_BIT2;
									 RXD_DATA_BUF(2) <= RXD1;
				WHEN RX_BIT2 => RX_STATE <= RX_BIT3;
									 RXD_DATA_BUF(3) <= RXD1;
				WHEN RX_BIT3 => RX_STATE <= RX_BIT4;
									 RXD_DATA_BUF(4) <= RXD1;
				WHEN RX_BIT4 => RX_STATE <= RX_BIT5;
									 RXD_DATA_BUF(5) <= RXD1;
				WHEN RX_BIT5 => RX_STATE <= RX_BIT6;
									 RXD_DATA_BUF(6) <= RXD1;
				WHEN RX_BIT6 => RX_STATE <= RX_BIT7;
									 RXD_DATA_BUF(7) <= RXD1;
				WHEN RX_BIT7 => RX_STATE <= RX_STOP;
									 RXD_DATA <= RXD_DATA_BUF;
				WHEN OTHERS =>  RX_STATE <=  RX_IDLE;
			END CASE;
		END IF;
	END PROCESS;
	
		
	
	PROCESS( CLK, nRST )
		VARIABLE CNT : INTEGER RANGE 0 TO 78125;
	BEGIN
		IF nRST='0' THEN
			CNT := 0;
			SEG_CLK <= '0';
		ELSIF RISING_EDGE(CLK) THEN
			IF (CNT=78125) THEN
				CNT := 0;
				SEG_CLK <= NOT SEG_CLK;
			ELSE
				CNT := CNT + 1;
			END IF;
		END IF;
	END PROCESS;
	
	PROCESS( SEG_CLK )
	BEGIN
		IF RISING_EDGE(SEG_CLK) THEN
			CASE SEG_SCAN_SIG IS
				WHEN SCAN_0 => SEG_SCAN_SIG <= SCAN_1;
									SEG_DAT <= SEG_TXD0;
				WHEN SCAN_1 => SEG_SCAN_SIG <= SCAN_2;
									SEG_DAT <= SEG_RXD1;
				WHEN SCAN_2 => SEG_SCAN_SIG <= SCAN_3;  --SEG [ 8 x x x ]
									SEG_DAT <= SEG_RXD0;     
				WHEN SCAN_3 => SEG_SCAN_SIG <= SCAN_0;
									SEG_DAT <= SEG_TXD1;
				WHEN OTHERS => SEG_SCAN_SIG <= SCAN_0;
									SEG_DAT <= SEG_TXD1;
			END CASE;
		END IF;
	END PROCESS;
		
	SEG_RXD0 <= RXD_DATA ( 7 DOWNTO 4 );
	SEG_RXD1 <= RXD_DATA ( 3 DOWNTO 0 );
	
	SEG_TXD0 <= FONT( 7 DOWNTO 4 );
	SEG_TXD1 <= FONT( 3 DOWNTO 0 );
	
	SEG_COM <= SEG_SCAN_SIG;
	
	SEG_DATA <=	SEG_0 WHEN (SEG_DAT="0000") ELSE
					SEG_1 WHEN (SEG_DAT="0001") ELSE
					SEG_2 WHEN (SEG_DAT="0010") ELSE
					SEG_3 WHEN (SEG_DAT="0011") ELSE
					SEG_4 WHEN (SEG_DAT="0100") ELSE
					SEG_5 WHEN (SEG_DAT="0101") ELSE
					SEG_6 WHEN (SEG_DAT="0110") ELSE
					SEG_7 WHEN (SEG_DAT="0111") ELSE
					SEG_8 WHEN (SEG_DAT="1000") ELSE
					SEG_9 WHEN (SEG_DAT="1001") ELSE
					SEG_A WHEN (SEG_DAT="1010") ELSE
					SEG_B WHEN (SEG_DAT="1011") ELSE
					SEG_C WHEN (SEG_DAT="1100") ELSE
					SEG_D WHEN (SEG_DAT="1101") ELSE
					SEG_E WHEN (SEG_DAT="1110") ELSE
					SEG_F WHEN (SEG_DAT="1111") ELSE
					( OTHERS => '0' );
			
	PROCESS( TX_CLK, nRST )
	BEGIN
		IF nRST='0' THEN
			STATE <= IDLE;
			COUNT <= 0;
			DELAY <= 0;
			TXD <= '1';
			TXD1 <= '1';
			EN <= '0';
		ELSIF RISING_EDGE(TX_CLK) THEN
			IF EN='0' THEN
				CASE STATE IS
					WHEN IDLE => STATE <= START;
									 TXD <= '0';
									 TXD1 <= '0';
					WHEN START => STATE <= BIT0;
							TXD <= FONT(0);
							TXD1<= FONT(0);
					WHEN BIT0 => STATE <= BIT1;
							TXD <= FONT(1);
							TXD1<= FONT(1);
					WHEN BIT1 => STATE <= BIT2;
							TXD <= FONT(2);
							TXD1<= FONT(2);
					WHEN BIT2 => STATE <= BIT3;
							TXD <= FONT(3);
							TXD1<= FONT(3);
					WHEN BIT3 => STATE <= BIT4;
							TXD <= FONT(4);
							TXD1 <= FONT(4);
					WHEN BIT4 => STATE <= BIT5;
							TXD <= FONT(5);
							TXD1 <= FONT(5);
					WHEN BIT5 => STATE <= BIT6;
							TXD <= FONT(6);
							TXD1 <= FONT(6);
					WHEN  BIT6 => STATE <= BIT7;
							TXD <= FONT(7);
							TXD1 <= FONT(7);
					WHEN BIT7 => STATE <= STOP;
							TXD <= '1';
							TXD1 <= '1';
					WHEN STOP => IF (COUNT < 36) THEN
											STATE <= IDLE;
											COUNT <= COUNT + 1;
									 ELSE
											STATE <= IDLE;
											COUNT <= 0;
											EN <= '1';
									END IF;
					WHEN OTHERS => STATE <= IDLE;
				END CASE;
			ELSE
				CASE STATE IS
					WHEN IDLE =>IF (DELAY=9600) THEN
										STATE <= START;
										DELAY <= 0;
										TXD <= '0';
										TXD1 <= '0';
									ELSE
										DELAY <= DELAY + 1;
										STATE <= IDLE;
										TXD <= '1';
										TXD1 <= '1';
									END IF;
					WHEN START => STATE <= BIT0;
							TXD <= FONT(0);
							TXD1<= FONT(0);
					WHEN BIT0 => STATE <= BIT1;
							TXD <= FONT(1);
							TXD1<= FONT(1);
					WHEN BIT1 => STATE <= BIT2;
							TXD <= FONT(2);
							TXD1<= FONT(2);
					WHEN BIT2 => STATE <= BIT3;
							TXD <= FONT(3);
							TXD1<= FONT(3);
					WHEN BIT3 => STATE <= BIT4;
							TXD <= FONT(4);
							TXD1 <= FONT(4);
					WHEN BIT4 => STATE <= BIT5;
							TXD <= FONT(5);
							TXD1 <= FONT(5);
					WHEN BIT5 => STATE <= BIT6;
							TXD <= FONT(6);
							TXD1 <= FONT(6);
					WHEN  BIT6 => STATE <= BIT7;
							TXD <= FONT(7);
							TXD1 <= FONT(7);
					WHEN BIT7 => STATE <= STOP;
							TXD <= '1';
							TXD1 <= '1';
					WHEN STOP => IF (COUNT < 37) THEN
										STATE <= IDLE;
										COUNT <= COUNT + 1;
									 ELSE
										STATE <= STOP;
									 END IF;
					WHEN OTHERS => STATE <= IDLE;
				END CASE;
			END IF;
		END IF;
	END PROCESS;
---------------------------------------------------
		--  Display FONT --
-- 	    You-Will Inc  Tel : 031)203-1161
---------------------------------------------------
	PROCESS(COUNT)
	BEGIN
		CASE COUNT IS
		
		   WHEN 0 =>  FONT <= CR;
			WHEN 1 =>  FONT <= LF;
			WHEN 2 =>  FONT <= ASCII_LY;
			WHEN 3 =>  FONT <= ASCII_SO;
			WHEN 4 =>  FONT <= ASCII_SU;
			WHEN 5 =>  FONT <= UN;
			WHEN 6 =>  FONT <= ASCII_LW;
			WHEN 7 =>  FONT <= ASCII_SI;
			WHEN 8 =>  FONT <= ASCII_SL;
			WHEN 9 =>  FONT <= ASCII_SL;
			WHEN 10 =>  FONT <= BL;
			WHEN 11 =>  FONT <= ASCII_LI;
			WHEN 12 => FONT <= ASCII_SN;
			WHEN 13 => FONT <= ASCII_SC;
			WHEN 14 => FONT <= CR;
			WHEN 15 => FONT <= LF;
			WHEN 16 => FONT <= ASCII_LT;
			WHEN 17 => FONT <= ASCII_SE;
			WHEN 18 => FONT <= ASCII_SL;
			WHEN 19 => FONT <= BL;
			WHEN 20 => FONT <= CO;
			WHEN 21 => FONT <= BL;
			WHEN 22 => FONT <= ASCII_0;
			WHEN 23 => FONT <= ASCII_3;
			WHEN 24 => FONT <= ASCII_1;
			WHEN 25 => FONT <= DA;
			WHEN 26 => FONT <= ASCII_2;
			WHEN 27 => FONT <= ASCII_0;
			WHEN 28 => FONT <= ASCII_3;
			WHEN 29 => FONT <= DA;
			WHEN 30 => FONT <= ASCII_1;
			WHEN 31 => FONT <= ASCII_1;
			WHEN 32 => FONT <= ASCII_6;
			WHEN 33 => FONT <= ASCII_1;
			WHEN 34 => FONT <= BL;
			WHEN 35 => FONT <= CR;
			WHEN 36 => FONT <= LF;
			WHEN OTHERS => FONT <= ( OTHERS => '1');
		END CASE;
	END PROCESS;
END RTL;