#------------------------------------------------------------------------------
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from ARM Limited
#   (C) COPYRIGHT 1999 ARM Limited
#       ALL RIGHTS RESERVED
# The entire notice above must be reproduced on all authorised
# copies and copies may only be made to the extent permitted
# by a licensing agreement from ARM Limited.
#-------------------------------------------------------------------------------
# 
# Version and Release Control Information:
# 
# File Name              : makefile,v
# File Revision          : 1.3
# 
# Release Information    : PL050-REL1v1
# 
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Purpose : Standard VHDL Library Makefile  
#-------------------------------------------------------------------------------


MODULES =  KmiTrApbif.vhd \
           KmiTrBitCounter.vhd \
           KmiTrKCLKGen.vhd \
           KmiTrController.vhd \
           KmiTrDataWidth.vhd \
           KmiTrOutDrive.vhd \
           KmiTrRXFIFO.vhd \
           KmiTrPulseGen.vhd \
           KmiTrTXFIFO.vhd \
           KmiTrRegFile.vhd \
           KmiTrTimer.vhd \
           KmiTrick.vhd
 
include ../modeltech/StdMakefile.mk

############################## End of file #####################################
