#- --=========================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000-2001 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#-------------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile,v
#- File Revision          : 1.3
#-
#- Release Information    : ADK_REL1v1
#-
#-------------------------------------------------------------------------------
#-  Purpose  : 
#-             ADK makefile, compiles vhdl rtl for $SIMULATOR
#-
#- --=========================================================================--

MODULES = SmiCore.vhd \
          SmiDBI.vhd \
          TIC.vhd \
          SMI.vhd 

PERIPH =  SMI

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

#################################### End #######################################
