library verilog;
use verilog.vl_types.all;
entity mmc_core is
    port(
        mresetn         : in     vl_logic;
        hstandby        : in     vl_logic;
        msreset         : out    vl_logic;
        mclk            : in     vl_logic;
        mcs             : in     vl_logic;
        mcmdin          : in     vl_logic;
        mcmdout         : out    vl_logic;
        mcmdouten       : out    vl_logic;
        mdatin          : in     vl_logic_vector(7 downto 0);
        mdatout         : out    vl_logic_vector(7 downto 0);
        mdatouten       : out    vl_logic;
        mext_csd        : in     vl_logic_vector(191 downto 0);
        msfr_out        : in     vl_logic_vector(7 downto 0);
        msfr_read       : in     vl_logic_vector(31 downto 0);
        hbuswidth_cmd   : in     vl_logic_vector(31 downto 0);
        houtdly         : in     vl_logic_vector(5 downto 0);
        mcmdindex       : out    vl_logic_vector(5 downto 0);
        mocr_update     : out    vl_logic;
        mrca_update     : out    vl_logic;
        mrca_up_data    : out    vl_logic_vector(15 downto 0);
        fifo_clear      : out    vl_logic;
        mwstb_4word     : out    vl_logic;
        mwstb_16word    : out    vl_logic;
        mwstb_128word   : out    vl_logic;
        wr_word_count   : out    vl_logic_vector(7 downto 0);
        wr_4word_count  : out    vl_logic_vector(7 downto 0);
        wr_16word_count : out    vl_logic_vector(7 downto 0);
        wr_128word_count: out    vl_logic_vector(7 downto 0);
        single_write_command: out    vl_logic;
        multi_write_command: out    vl_logic;
        single_read_command: out    vl_logic;
        multi_read_command: out    vl_logic;
        rd_eou          : out    vl_logic;
        mrden           : out    vl_logic;
        start_block     : out    vl_logic_vector(22 downto 0);
        multi_write_block: out    vl_logic_vector(31 downto 0);
        multi_read_block: out    vl_logic_vector(31 downto 0);
        mrstb_4word     : out    vl_logic;
        mrstb_16word    : out    vl_logic;
        mrstb_128word   : out    vl_logic;
        rd_word_count   : out    vl_logic_vector(7 downto 0);
        rd_4word_count  : out    vl_logic_vector(7 downto 0);
        rd_16word_count : out    vl_logic_vector(7 downto 0);
        rd_128word_count: out    vl_logic_vector(7 downto 0);
        mrstb           : out    vl_logic;
        mrstb_3d        : out    vl_logic;
        mrstb_4d        : out    vl_logic;
        busy_clear      : out    vl_logic;
        wr_count        : out    vl_logic_vector(15 downto 0);
        set_pwd         : in     vl_logic;
        lock_unlock_mode: in     vl_logic_vector(7 downto 0);
        pwd_match       : in     vl_logic;
        pwd_len_match   : in     vl_logic;
        pwd_stb         : in     vl_logic;
        clr_pwd         : in     vl_logic;
        card_is_locked  : out    vl_logic;
        \Access\        : out    vl_logic_vector(1 downto 0);
        index           : out    vl_logic_vector(7 downto 0);
        value           : out    vl_logic_vector(7 downto 0);
        switch_error    : out    vl_logic;
        resp_eox        : out    vl_logic;
        resp_eor        : out    vl_logic;
        block_len_error : out    vl_logic;
        wr_block_buffer_4word: in     vl_logic_vector(127 downto 0);
        cid_csd_overwrite: out    vl_logic;
        csd_update      : in     vl_logic_vector(127 downto 0);
        bus1            : out    vl_logic;
        bus4            : out    vl_logic;
        bus8            : out    vl_logic;
        mcid            : in     vl_logic_vector(127 downto 0);
        mrca            : in     vl_logic_vector(15 downto 0);
        mcsd            : in     vl_logic_vector(127 downto 0);
        mocr            : in     vl_logic_vector(31 downto 0);
        mbsyend         : in     vl_logic;
        mwblen          : in     vl_logic_vector(11 downto 0);
        mrblen          : in     vl_logic_vector(11 downto 0);
        mbsybwcmd       : in     vl_logic;
        mcstwr          : in     vl_logic;
        mstatuscpu      : in     vl_logic_vector(31 downto 0);
        mstatuswr       : in     vl_logic;
        mstatuswren     : in     vl_logic_vector(31 downto 0);
        mdecode60       : in     vl_logic_vector(15 downto 0);
        mdecode61       : in     vl_logic_vector(15 downto 0);
        mdecode62       : in     vl_logic_vector(15 downto 0);
        mdecode63       : in     vl_logic_vector(15 downto 0);
        mnid            : in     vl_logic_vector(7 downto 0);
        mncrmmc         : in     vl_logic_vector(7 downto 0);
        mncrspi         : in     vl_logic_vector(7 downto 0);
        mcstnorm        : in     vl_logic_vector(4 downto 0);
        mcststop        : in     vl_logic_vector(4 downto 0);
        mcstmanu        : in     vl_logic_vector(4 downto 0);
        mcmddef         : in     vl_logic_vector(63 downto 0);
        mblockmax       : in     vl_logic_vector(22 downto 0);
        meraseseq       : in     vl_logic_vector(8 downto 0);
        merasecmd       : in     vl_logic_vector(8 downto 0);
        mcardlock       : in     vl_logic;
        mcidfix         : in     vl_logic;
        mgo_irq_state   : in     vl_logic;
        mwakeupen       : in     vl_logic;
        mcrc7_on_off    : in     vl_logic;
        mcrc16_on_off   : in     vl_logic;
        mcmdirqen       : in     vl_logic_vector(15 downto 0);
        mrespirqen      : in     vl_logic_vector(15 downto 0);
        mwrirqen        : in     vl_logic_vector(15 downto 0);
        mrdirqen        : in     vl_logic_vector(15 downto 0);
        mwrforce        : in     vl_logic;
        mrdforce        : in     vl_logic;
        mdis2rcv        : in     vl_logic;
        mstby_cmd2      : in     vl_logic;
        mstby_cmd3      : in     vl_logic;
        mbusy_cmd12     : in     vl_logic;
        mbusy_cmd12_resp: in     vl_logic_vector(2 downto 0);
        \MRDEN\         : in     vl_logic;
        mlocken         : in     vl_logic_vector(63 downto 0);
        \MRSTB\         : out    vl_logic;
        mwstb           : out    vl_logic;
        mdout           : out    vl_logic_vector(7 downto 0);
        mdin            : in     vl_logic_vector(7 downto 0);
        mtmbw           : out    vl_logic;
        mcommand        : out    vl_logic_vector(47 downto 0);
        mcommand_ok     : out    vl_logic;
        mcommand_ok2    : out    vl_logic;
        mcommand_ok3wr  : out    vl_logic;
        mstatus         : out    vl_logic_vector(31 downto 0);
        mdecode         : out    vl_logic_vector(11 downto 0);
        mcrc7_ok        : out    vl_logic;
        mcrc16_ok       : out    vl_logic;
        mcmdfield       : out    vl_logic_vector(3 downto 0);
        mrespfield      : out    vl_logic_vector(3 downto 0);
        mwrfield        : out    vl_logic_vector(3 downto 0);
        mrdfield        : out    vl_logic_vector(3 downto 0);
        mcstate         : out    vl_logic_vector(4 downto 0);
        mcmdirqwr       : out    vl_logic_vector(14 downto 0);
        mrespirqwr      : out    vl_logic_vector(14 downto 0);
        mwrirqwr        : out    vl_logic_vector(14 downto 0);
        mrdirqwr        : out    vl_logic_vector(14 downto 0);
        mwakeup         : out    vl_logic;
        mirq            : out    vl_logic_vector(3 downto 0);
        mprefix         : out    vl_logic_vector(7 downto 0);
        mresp_end       : out    vl_logic;
        mcselect        : out    vl_logic
    );
end mmc_core;
