library verilog;
use verilog.vl_types.all;
entity dmac is
    port(
        hclk            : in     vl_logic;
        hresetn         : in     vl_logic;
        hseldmac        : in     vl_logic;
        hwrite          : in     vl_logic;
        htrans          : in     vl_logic;
        haddr           : in     vl_logic_vector(11 downto 2);
        hsize           : in     vl_logic_vector(2 downto 0);
        hreadyin        : in     vl_logic;
        hwdata          : in     vl_logic_vector(31 downto 0);
        hgrantdmacm1    : in     vl_logic;
        hgrantdmacm2    : in     vl_logic;
        hreadyinm1      : in     vl_logic;
        hreadyinm2      : in     vl_logic;
        hrespm1         : in     vl_logic_vector(1 downto 0);
        hrespm2         : in     vl_logic_vector(1 downto 0);
        hrdatam1        : in     vl_logic_vector(31 downto 0);
        hrdatam2        : in     vl_logic_vector(31 downto 0);
        dmacbreq        : in     vl_logic_vector(15 downto 0);
        dmaclbreq       : in     vl_logic_vector(15 downto 0);
        dmacsreq        : in     vl_logic_vector(15 downto 0);
        dmaclsreq       : in     vl_logic_vector(15 downto 0);
        scaninhclk      : in     vl_logic;
        scanenable      : in     vl_logic;
        hreadyout       : out    vl_logic;
        hresp           : out    vl_logic_vector(1 downto 0);
        hrdata          : out    vl_logic_vector(31 downto 0);
        hbusreqdmacm1   : out    vl_logic;
        hbusreqdmacm2   : out    vl_logic;
        hlockdmacm1     : out    vl_logic;
        hlockdmacm2     : out    vl_logic;
        htransm1        : out    vl_logic_vector(1 downto 0);
        htransm2        : out    vl_logic_vector(1 downto 0);
        haddrm1         : out    vl_logic_vector(31 downto 0);
        haddrm2         : out    vl_logic_vector(31 downto 0);
        hsizem1         : out    vl_logic_vector(2 downto 0);
        hsizem2         : out    vl_logic_vector(2 downto 0);
        hburstm1        : out    vl_logic_vector(2 downto 0);
        hburstm2        : out    vl_logic_vector(2 downto 0);
        hprotm1         : out    vl_logic_vector(3 downto 0);
        hprotm2         : out    vl_logic_vector(3 downto 0);
        hwritem1        : out    vl_logic;
        hwritem2        : out    vl_logic;
        hwdatam1        : out    vl_logic_vector(31 downto 0);
        hwdatam2        : out    vl_logic_vector(31 downto 0);
        dmacclr         : out    vl_logic_vector(15 downto 0);
        dmactc          : out    vl_logic_vector(15 downto 0);
        dmacinterr      : out    vl_logic;
        dmacinttc       : out    vl_logic;
        dmacintr        : out    vl_logic;
        scanouthclk     : out    vl_logic
    );
end dmac;
