onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -format Logic /tb/ACLK
add wave -noupdate -format Logic /tb/ARESETn
add wave -noupdate -format Literal /tb/AWIDm02si0
add wave -noupdate -format Literal /tb/AWADDRm02si0
add wave -noupdate -format Literal /tb/AWLENm02si0
add wave -noupdate -format Literal /tb/AWSIZEm02si0
add wave -noupdate -format Literal /tb/AWBURSTm02si0
add wave -noupdate -format Literal /tb/AWLOCKm02si0
add wave -noupdate -format Literal /tb/AWCACHEm02si0
add wave -noupdate -format Literal /tb/AWPROTm02si0
add wave -noupdate -format Logic /tb/AWVALIDm02si0
add wave -noupdate -format Logic /tb/AWREADYsi02m0
add wave -noupdate -format Literal /tb/WIDm02si0
add wave -noupdate -format Literal /tb/WDATAm02si0
add wave -noupdate -format Literal /tb/WSTRBm02si0
add wave -noupdate -format Logic /tb/WLASTm02si0
add wave -noupdate -format Logic /tb/WVALIDm02si0
add wave -noupdate -format Logic /tb/WREADYsi02m0
add wave -noupdate -format Literal /tb/BIDsi02m0
add wave -noupdate -format Literal /tb/BRESPsi02m0
add wave -noupdate -format Logic /tb/BVALIDsi02m0
add wave -noupdate -format Logic /tb/BREADYm02si0
add wave -noupdate -format Literal /tb/AWIDm12si1
add wave -noupdate -format Literal /tb/AWADDRm12si1
add wave -noupdate -format Literal /tb/AWLENm12si1
add wave -noupdate -format Literal /tb/AWSIZEm12si1
add wave -noupdate -format Literal /tb/AWBURSTm12si1
add wave -noupdate -format Literal /tb/AWLOCKm12si1
add wave -noupdate -format Literal /tb/AWCACHEm12si1
add wave -noupdate -format Literal /tb/AWPROTm12si1
add wave -noupdate -format Logic /tb/AWVALIDm12si1
add wave -noupdate -format Logic /tb/AWREADYsi12m1
add wave -noupdate -format Literal /tb/WIDm12si1
add wave -noupdate -format Literal /tb/WDATAm12si1
add wave -noupdate -format Literal /tb/WSTRBm12si1
add wave -noupdate -format Logic /tb/WLASTm12si1
add wave -noupdate -format Logic /tb/WVALIDm12si1
add wave -noupdate -format Logic /tb/WREADYsi12m1
add wave -noupdate -format Literal /tb/BIDsi12m1
add wave -noupdate -format Literal /tb/BRESPsi12m1
add wave -noupdate -format Logic /tb/BVALIDsi12m1
add wave -noupdate -format Logic /tb/BREADYm12si1
add wave -noupdate -format Literal /tb/AWIDm22si2
add wave -noupdate -format Literal /tb/AWADDRm22si2
add wave -noupdate -format Literal /tb/AWLENm22si2
add wave -noupdate -format Literal /tb/AWSIZEm22si2
add wave -noupdate -format Literal /tb/AWBURSTm22si2
add wave -noupdate -format Literal /tb/AWLOCKm22si2
add wave -noupdate -format Literal /tb/AWCACHEm22si2
add wave -noupdate -format Literal /tb/AWPROTm22si2
add wave -noupdate -format Logic /tb/AWVALIDm22si2
add wave -noupdate -format Logic /tb/AWREADYsi22m2
add wave -noupdate -format Literal /tb/WIDm22si2
add wave -noupdate -format Literal /tb/WDATAm22si2
add wave -noupdate -format Literal /tb/WSTRBm22si2
add wave -noupdate -format Logic /tb/WLASTm22si2
add wave -noupdate -format Logic /tb/WVALIDm22si2
add wave -noupdate -format Logic /tb/WREADYsi22m2
add wave -noupdate -format Literal /tb/BIDsi22m2
add wave -noupdate -format Literal /tb/BRESPsi22m2
add wave -noupdate -format Logic /tb/BVALIDsi22m2
add wave -noupdate -format Logic /tb/BREADYm22si2
add wave -noupdate -format Literal /tb/AWIDm32si3
add wave -noupdate -format Literal /tb/AWADDRm32si3
add wave -noupdate -format Literal /tb/AWLENm32si3
add wave -noupdate -format Literal /tb/AWSIZEm32si3
add wave -noupdate -format Literal /tb/AWBURSTm32si3
add wave -noupdate -format Literal /tb/AWLOCKm32si3
add wave -noupdate -format Literal /tb/AWCACHEm32si3
add wave -noupdate -format Literal /tb/AWPROTm32si3
add wave -noupdate -format Logic /tb/AWVALIDm32si3
add wave -noupdate -format Logic /tb/AWREADYsi32m3
add wave -noupdate -format Literal /tb/WIDm32si3
add wave -noupdate -format Literal /tb/WDATAm32si3
add wave -noupdate -format Literal /tb/WSTRBm32si3
add wave -noupdate -format Logic /tb/WLASTm32si3
add wave -noupdate -format Logic /tb/WVALIDm32si3
add wave -noupdate -format Logic /tb/WREADYsi32m3
add wave -noupdate -format Literal /tb/BIDsi32m3
add wave -noupdate -format Literal /tb/BRESPsi32m3
add wave -noupdate -format Logic /tb/BVALIDsi32m3
add wave -noupdate -format Logic /tb/BREADYm32si3
add wave -noupdate -format Literal /tb/AWIDmi02s0
add wave -noupdate -format Literal /tb/AWADDRmi02s0
add wave -noupdate -format Literal /tb/AWLENmi02s0
add wave -noupdate -format Literal /tb/AWSIZEmi02s0
add wave -noupdate -format Literal /tb/AWBURSTmi02s0
add wave -noupdate -format Literal /tb/AWLOCKmi02s0
add wave -noupdate -format Literal /tb/AWCACHEmi02s0
add wave -noupdate -format Literal /tb/AWPROTmi02s0
add wave -noupdate -format Logic /tb/AWVALIDmi02s0
add wave -noupdate -format Logic /tb/AWREADYs02mi0
add wave -noupdate -format Literal /tb/WIDmi02s0
add wave -noupdate -format Literal /tb/WDATAmi02s0
add wave -noupdate -format Literal /tb/WSTRBmi02s0
add wave -noupdate -format Logic /tb/WLASTmi02s0
add wave -noupdate -format Logic /tb/WVALIDmi02s0
add wave -noupdate -format Logic /tb/WREADYs02mi0
add wave -noupdate -format Literal /tb/BIDs02mi0
add wave -noupdate -format Literal /tb/BRESPs02mi0
add wave -noupdate -format Logic /tb/BVALIDs02mi0
add wave -noupdate -format Logic /tb/BREADYmi02s0
add wave -noupdate -format Literal /tb/AWIDmi12s1
add wave -noupdate -format Literal /tb/AWADDRmi12s1
add wave -noupdate -format Literal /tb/AWLENmi12s1
add wave -noupdate -format Literal /tb/AWSIZEmi12s1
add wave -noupdate -format Literal /tb/AWBURSTmi12s1
add wave -noupdate -format Literal /tb/AWLOCKmi12s1
add wave -noupdate -format Literal /tb/AWCACHEmi12s1
add wave -noupdate -format Literal /tb/AWPROTmi12s1
add wave -noupdate -format Logic /tb/AWVALIDmi12s1
add wave -noupdate -format Logic /tb/AWREADYs12mi1
add wave -noupdate -format Literal /tb/WIDmi12s1
add wave -noupdate -format Literal /tb/WDATAmi12s1
add wave -noupdate -format Literal /tb/WSTRBmi12s1
add wave -noupdate -format Logic /tb/WLASTmi12s1
add wave -noupdate -format Logic /tb/WVALIDmi12s1
add wave -noupdate -format Logic /tb/WREADYs12mi1
add wave -noupdate -format Literal /tb/BIDs12mi1
add wave -noupdate -format Literal /tb/BRESPs12mi1
add wave -noupdate -format Logic /tb/BVALIDs12mi1
add wave -noupdate -format Logic /tb/BREADYmi12s1
add wave -noupdate -format Literal /tb/AWIDmi22s2
add wave -noupdate -format Literal /tb/AWADDRmi22s2
add wave -noupdate -format Literal /tb/AWLENmi22s2
add wave -noupdate -format Literal /tb/AWSIZEmi22s2
add wave -noupdate -format Literal /tb/AWBURSTmi22s2
add wave -noupdate -format Literal /tb/AWLOCKmi22s2
add wave -noupdate -format Literal /tb/AWCACHEmi22s2
add wave -noupdate -format Literal /tb/AWPROTmi22s2
add wave -noupdate -format Logic /tb/AWVALIDmi22s2
add wave -noupdate -format Logic /tb/AWREADYs22mi2
add wave -noupdate -format Literal /tb/WIDmi22s2
add wave -noupdate -format Literal /tb/WDATAmi22s2
add wave -noupdate -format Literal /tb/WSTRBmi22s2
add wave -noupdate -format Logic /tb/WLASTmi22s2
add wave -noupdate -format Logic /tb/WVALIDmi22s2
add wave -noupdate -format Logic /tb/WREADYs22mi2
add wave -noupdate -format Literal /tb/BIDs22mi2
add wave -noupdate -format Literal /tb/BRESPs22mi2
add wave -noupdate -format Logic /tb/BVALIDs22mi2
add wave -noupdate -format Logic /tb/BREADYmi22s2
add wave -noupdate -format Literal /tb/AWIDmi32s3
add wave -noupdate -format Literal /tb/AWADDRmi32s3
add wave -noupdate -format Literal /tb/AWLENmi32s3
add wave -noupdate -format Literal /tb/AWSIZEmi32s3
add wave -noupdate -format Literal /tb/AWBURSTmi32s3
add wave -noupdate -format Literal /tb/AWLOCKmi32s3
add wave -noupdate -format Literal /tb/AWCACHEmi32s3
add wave -noupdate -format Literal /tb/AWPROTmi32s3
add wave -noupdate -format Logic /tb/AWVALIDmi32s3
add wave -noupdate -format Logic /tb/AWREADYs32mi3
add wave -noupdate -format Literal /tb/WIDmi32s3
add wave -noupdate -format Literal /tb/WDATAmi32s3
add wave -noupdate -format Literal /tb/WSTRBmi32s3
add wave -noupdate -format Logic /tb/WLASTmi32s3
add wave -noupdate -format Logic /tb/WVALIDmi32s3
add wave -noupdate -format Logic /tb/WREADYs32mi3
add wave -noupdate -format Literal /tb/BIDs32mi3
add wave -noupdate -format Literal /tb/BRESPs32mi3
add wave -noupdate -format Logic /tb/BVALIDs32mi3
add wave -noupdate -format Logic /tb/BREADYmi32s3
add wave -noupdate -format Literal /tb/AWIDmi42s4
add wave -noupdate -format Literal /tb/AWADDRmi42s4
add wave -noupdate -format Literal /tb/AWLENmi42s4
add wave -noupdate -format Literal /tb/AWSIZEmi42s4
add wave -noupdate -format Literal /tb/AWBURSTmi42s4
add wave -noupdate -format Literal /tb/AWLOCKmi42s4
add wave -noupdate -format Literal /tb/AWCACHEmi42s4
add wave -noupdate -format Literal /tb/AWPROTmi42s4
add wave -noupdate -format Logic /tb/AWVALIDmi42s4
add wave -noupdate -format Logic /tb/AWREADYs42mi4
add wave -noupdate -format Literal /tb/WIDmi42s4
add wave -noupdate -format Literal /tb/WDATAmi42s4
add wave -noupdate -format Literal /tb/WSTRBmi42s4
add wave -noupdate -format Logic /tb/WLASTmi42s4
add wave -noupdate -format Logic /tb/WVALIDmi42s4
add wave -noupdate -format Logic /tb/WREADYs42mi4
add wave -noupdate -format Literal /tb/BIDs42mi4
add wave -noupdate -format Literal /tb/BRESPs42mi4
add wave -noupdate -format Logic /tb/BVALIDs42mi4
add wave -noupdate -format Logic /tb/BREADYmi42s4
add wave -noupdate -format Literal /tb/AWIDmi52s5
add wave -noupdate -format Literal /tb/AWADDRmi52s5
add wave -noupdate -format Literal /tb/AWLENmi52s5
add wave -noupdate -format Literal /tb/AWSIZEmi52s5
add wave -noupdate -format Literal /tb/AWBURSTmi52s5
add wave -noupdate -format Literal /tb/AWLOCKmi52s5
add wave -noupdate -format Literal /tb/AWCACHEmi52s5
add wave -noupdate -format Literal /tb/AWPROTmi52s5
add wave -noupdate -format Logic /tb/AWVALIDmi52s5
add wave -noupdate -format Logic /tb/AWREADYs52mi5
add wave -noupdate -format Literal /tb/WIDmi52s5
add wave -noupdate -format Literal /tb/WDATAmi52s5
add wave -noupdate -format Literal /tb/WSTRBmi52s5
add wave -noupdate -format Logic /tb/WLASTmi52s5
add wave -noupdate -format Logic /tb/WVALIDmi52s5
add wave -noupdate -format Logic /tb/WREADYs52mi5
add wave -noupdate -format Literal /tb/BIDs52mi5
add wave -noupdate -format Literal /tb/BRESPs52mi5
add wave -noupdate -format Logic /tb/BVALIDs52mi5
add wave -noupdate -format Logic /tb/BREADYmi52s5
add wave -noupdate -format Literal /tb/ARIDm02si0
add wave -noupdate -format Literal /tb/ARADDRm02si0
add wave -noupdate -format Literal /tb/ARLENm02si0
add wave -noupdate -format Literal /tb/ARSIZEm02si0
add wave -noupdate -format Literal /tb/ARBURSTm02si0
add wave -noupdate -format Literal /tb/ARLOCKm02si0
add wave -noupdate -format Literal /tb/ARCACHEm02si0
add wave -noupdate -format Literal /tb/ARPROTm02si0
add wave -noupdate -format Logic /tb/ARVALIDm02si0
add wave -noupdate -format Logic /tb/ARREADYsi02m0
add wave -noupdate -format Literal /tb/RIDsi02m0
add wave -noupdate -format Literal /tb/RRESPsi02m0
add wave -noupdate -format Literal /tb/RDATAsi02m0
add wave -noupdate -format Logic /tb/RLASTsi02m0
add wave -noupdate -format Logic /tb/RVALIDsi02m0
add wave -noupdate -format Logic /tb/RREADYm02si0
add wave -noupdate -format Literal /tb/ARIDm12si1
add wave -noupdate -format Literal /tb/ARADDRm12si1
add wave -noupdate -format Literal /tb/ARLENm12si1
add wave -noupdate -format Literal /tb/ARSIZEm12si1
add wave -noupdate -format Literal /tb/ARBURSTm12si1
add wave -noupdate -format Literal /tb/ARLOCKm12si1
add wave -noupdate -format Literal /tb/ARCACHEm12si1
add wave -noupdate -format Literal /tb/ARPROTm12si1
add wave -noupdate -format Logic /tb/ARVALIDm12si1
add wave -noupdate -format Logic /tb/ARREADYsi12m1
add wave -noupdate -format Literal /tb/RIDsi12m1
add wave -noupdate -format Literal /tb/RRESPsi12m1
add wave -noupdate -format Literal /tb/RDATAsi12m1
add wave -noupdate -format Logic /tb/RLASTsi12m1
add wave -noupdate -format Logic /tb/RVALIDsi12m1
add wave -noupdate -format Logic /tb/RREADYm12si1
add wave -noupdate -format Literal /tb/ARIDm22si2
add wave -noupdate -format Literal /tb/ARADDRm22si2
add wave -noupdate -format Literal /tb/ARLENm22si2
add wave -noupdate -format Literal /tb/ARSIZEm22si2
add wave -noupdate -format Literal /tb/ARBURSTm22si2
add wave -noupdate -format Literal /tb/ARLOCKm22si2
add wave -noupdate -format Literal /tb/ARCACHEm22si2
add wave -noupdate -format Literal /tb/ARPROTm22si2
add wave -noupdate -format Logic /tb/ARVALIDm22si2
add wave -noupdate -format Logic /tb/ARREADYsi22m2
add wave -noupdate -format Literal /tb/RIDsi22m2
add wave -noupdate -format Literal /tb/RRESPsi22m2
add wave -noupdate -format Literal /tb/RDATAsi22m2
add wave -noupdate -format Logic /tb/RLASTsi22m2
add wave -noupdate -format Logic /tb/RVALIDsi22m2
add wave -noupdate -format Logic /tb/RREADYm22si2
add wave -noupdate -format Literal /tb/ARIDm32si3
add wave -noupdate -format Literal /tb/ARADDRm32si3
add wave -noupdate -format Literal /tb/ARLENm32si3
add wave -noupdate -format Literal /tb/ARSIZEm32si3
add wave -noupdate -format Literal /tb/ARBURSTm32si3
add wave -noupdate -format Literal /tb/ARLOCKm32si3
add wave -noupdate -format Literal /tb/ARCACHEm32si3
add wave -noupdate -format Literal /tb/ARPROTm32si3
add wave -noupdate -format Logic /tb/ARVALIDm32si3
add wave -noupdate -format Logic /tb/ARREADYsi32m3
add wave -noupdate -format Literal /tb/RIDsi32m3
add wave -noupdate -format Literal /tb/RRESPsi32m3
add wave -noupdate -format Literal /tb/RDATAsi32m3
add wave -noupdate -format Logic /tb/RLASTsi32m3
add wave -noupdate -format Logic /tb/RVALIDsi32m3
add wave -noupdate -format Logic /tb/RREADYm32si3
add wave -noupdate -format Literal /tb/ARIDmi02s0
add wave -noupdate -format Literal /tb/ARADDRmi02s0
add wave -noupdate -format Literal /tb/ARLENmi02s0
add wave -noupdate -format Literal /tb/ARSIZEmi02s0
add wave -noupdate -format Literal /tb/ARBURSTmi02s0
add wave -noupdate -format Literal /tb/ARLOCKmi02s0
add wave -noupdate -format Literal /tb/ARCACHEmi02s0
add wave -noupdate -format Literal /tb/ARPROTmi02s0
add wave -noupdate -format Logic /tb/ARVALIDmi02s0
add wave -noupdate -format Logic /tb/ARREADYs02mi0
add wave -noupdate -format Literal /tb/RIDs02mi0
add wave -noupdate -format Literal /tb/RRESPs02mi0
add wave -noupdate -format Literal /tb/RDATAs02mi0
add wave -noupdate -format Logic /tb/RLASTs02mi0
add wave -noupdate -format Logic /tb/RVALIDs02mi0
add wave -noupdate -format Logic /tb/RREADYmi02s0
add wave -noupdate -format Literal /tb/ARIDmi12s1
add wave -noupdate -format Literal /tb/ARADDRmi12s1
add wave -noupdate -format Literal /tb/ARLENmi12s1
add wave -noupdate -format Literal /tb/ARSIZEmi12s1
add wave -noupdate -format Literal /tb/ARBURSTmi12s1
add wave -noupdate -format Literal /tb/ARLOCKmi12s1
add wave -noupdate -format Literal /tb/ARCACHEmi12s1
add wave -noupdate -format Literal /tb/ARPROTmi12s1
add wave -noupdate -format Logic /tb/ARVALIDmi12s1
add wave -noupdate -format Logic /tb/ARREADYs12mi1
add wave -noupdate -format Literal /tb/RIDs12mi1
add wave -noupdate -format Literal /tb/RRESPs12mi1
add wave -noupdate -format Literal /tb/RDATAs12mi1
add wave -noupdate -format Logic /tb/RLASTs12mi1
add wave -noupdate -format Logic /tb/RVALIDs12mi1
add wave -noupdate -format Logic /tb/RREADYmi12s1
add wave -noupdate -format Literal /tb/ARIDmi22s2
add wave -noupdate -format Literal /tb/ARADDRmi22s2
add wave -noupdate -format Literal /tb/ARLENmi22s2
add wave -noupdate -format Literal /tb/ARSIZEmi22s2
add wave -noupdate -format Literal /tb/ARBURSTmi22s2
add wave -noupdate -format Literal /tb/ARLOCKmi22s2
add wave -noupdate -format Literal /tb/ARCACHEmi22s2
add wave -noupdate -format Literal /tb/ARPROTmi22s2
add wave -noupdate -format Logic /tb/ARVALIDmi22s2
add wave -noupdate -format Logic /tb/ARREADYs22mi2
add wave -noupdate -format Literal /tb/RIDs22mi2
add wave -noupdate -format Literal /tb/RRESPs22mi2
add wave -noupdate -format Literal /tb/RDATAs22mi2
add wave -noupdate -format Logic /tb/RLASTs22mi2
add wave -noupdate -format Logic /tb/RVALIDs22mi2
add wave -noupdate -format Logic /tb/RREADYmi22s2
add wave -noupdate -format Literal /tb/ARIDmi32s3
add wave -noupdate -format Literal /tb/ARADDRmi32s3
add wave -noupdate -format Literal /tb/ARLENmi32s3
add wave -noupdate -format Literal /tb/ARSIZEmi32s3
add wave -noupdate -format Literal /tb/ARBURSTmi32s3
add wave -noupdate -format Literal /tb/ARLOCKmi32s3
add wave -noupdate -format Literal /tb/ARCACHEmi32s3
add wave -noupdate -format Literal /tb/ARPROTmi32s3
add wave -noupdate -format Logic /tb/ARVALIDmi32s3
add wave -noupdate -format Logic /tb/ARREADYs32mi3
add wave -noupdate -format Literal /tb/RIDs32mi3
add wave -noupdate -format Literal /tb/RRESPs32mi3
add wave -noupdate -format Literal /tb/RDATAs32mi3
add wave -noupdate -format Logic /tb/RLASTs32mi3
add wave -noupdate -format Logic /tb/RVALIDs32mi3
add wave -noupdate -format Logic /tb/RREADYmi32s3
add wave -noupdate -format Literal /tb/ARIDmi42s4
add wave -noupdate -format Literal /tb/ARADDRmi42s4
add wave -noupdate -format Literal /tb/ARLENmi42s4
add wave -noupdate -format Literal /tb/ARSIZEmi42s4
add wave -noupdate -format Literal /tb/ARBURSTmi42s4
add wave -noupdate -format Literal /tb/ARLOCKmi42s4
add wave -noupdate -format Literal /tb/ARCACHEmi42s4
add wave -noupdate -format Literal /tb/ARPROTmi42s4
add wave -noupdate -format Logic /tb/ARVALIDmi42s4
add wave -noupdate -format Logic /tb/ARREADYs42mi4
add wave -noupdate -format Literal /tb/RIDs42mi4
add wave -noupdate -format Literal /tb/RRESPs42mi4
add wave -noupdate -format Literal /tb/RDATAs42mi4
add wave -noupdate -format Logic /tb/RLASTs42mi4
add wave -noupdate -format Logic /tb/RVALIDs42mi4
add wave -noupdate -format Logic /tb/RREADYmi42s4
add wave -noupdate -format Literal /tb/ARIDmi52s5
add wave -noupdate -format Literal /tb/ARADDRmi52s5
add wave -noupdate -format Literal /tb/ARLENmi52s5
add wave -noupdate -format Literal /tb/ARSIZEmi52s5
add wave -noupdate -format Literal /tb/ARBURSTmi52s5
add wave -noupdate -format Literal /tb/ARLOCKmi52s5
add wave -noupdate -format Literal /tb/ARCACHEmi52s5
add wave -noupdate -format Literal /tb/ARPROTmi52s5
add wave -noupdate -format Logic /tb/ARVALIDmi52s5
add wave -noupdate -format Logic /tb/ARREADYs52mi5
add wave -noupdate -format Literal /tb/RIDs52mi5
add wave -noupdate -format Literal /tb/RRESPs52mi5
add wave -noupdate -format Literal /tb/RDATAs52mi5
add wave -noupdate -format Logic /tb/RLASTs52mi5
add wave -noupdate -format Logic /tb/RVALIDs52mi5
add wave -noupdate -format Logic /tb/RREADYmi52s5
add wave -noupdate -format Literal /tb/MEMADDR0
add wave -noupdate -format Literal /tb/MEMRDATA0
add wave -noupdate -format Literal /tb/MEMWDATA0
add wave -noupdate -format Logic /tb/MEMCEn0
add wave -noupdate -format Literal /tb/MEMWEn0
add wave -noupdate -format Literal /tb/MEMADDR1
add wave -noupdate -format Literal /tb/MEMRDATA1
add wave -noupdate -format Literal /tb/MEMWDATA1
add wave -noupdate -format Logic /tb/MEMCEn1
add wave -noupdate -format Literal /tb/MEMWEn1
add wave -noupdate -format Literal /tb/MEMADDR2
add wave -noupdate -format Literal /tb/MEMRDATA2
add wave -noupdate -format Literal /tb/MEMWDATA2
add wave -noupdate -format Logic /tb/MEMCEn2
add wave -noupdate -format Literal /tb/MEMWEn2
add wave -noupdate -format Literal /tb/MEMADDR3
add wave -noupdate -format Literal /tb/MEMRDATA3
add wave -noupdate -format Literal /tb/MEMWDATA3
add wave -noupdate -format Logic /tb/MEMCEn3
add wave -noupdate -format Literal /tb/MEMWEn3
add wave -noupdate -format Literal /tb/MEMADDR4
add wave -noupdate -format Literal /tb/MEMRDATA4
add wave -noupdate -format Literal /tb/MEMWDATA4
add wave -noupdate -format Logic /tb/MEMCEn4
add wave -noupdate -format Literal /tb/MEMWEn4
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue right
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
update
WaveRestoreZoom {0 ps} {1 ns}
