////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 1995-2003 Xilinx, Inc.
// All Right Reserved.
////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 7.1.04i
//  \   \         Application : 
//  /   /         Filename : mypll2x.v
// /___/   /\     Timestamp : 01/11/2007 20:31:07
// \   \  /  \ 
//  \___\/\___\ 
//
//Command: 
//Design Name: mypll2x
//
// Module mypll2x
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: Synplify
`timescale 1ns / 1ps

module mypll2x(CLKIN_IN, 
               CLKDV_OUT, 
               CLKIN_IBUFG_OUT, 
               CLK0_OUT, 
               CLK2X_OUT, 
               LOCKED_OUT);

    input CLKIN_IN;
   output CLKDV_OUT;
   output CLKIN_IBUFG_OUT;
   output CLK0_OUT;
   output CLK2X_OUT;
   output LOCKED_OUT;
   
   wire CLKDV_BUF;
   wire CLKFB_IN;
   wire CLKIN_IBUFG;
   wire CLK0_BUF;
   wire CLK2X_BUF;
   wire [6:0] GND;
   wire [15:0] GND1;
   wire GND2;
   
   assign GND = 7'b0000000;
   assign GND1 = 16'b0000000000000000;
   assign GND2 = 0;
   assign CLKIN_IBUFG_OUT = CLKIN_IBUFG;
   assign CLK0_OUT = CLKFB_IN;
   BUFG CLKDV_BUFG_INST (.I(CLKDV_BUF), 
                         .O(CLKDV_OUT));
   IBUFG CLKIN_IBUFG_INST (.I(CLKIN_IN), 
                           .O(CLKIN_IBUFG));
   BUFG CLK0_BUFG_INST (.I(CLK0_BUF), 
                        .O(CLKFB_IN));
   BUFG CLK2X_BUFG_INST (.I(CLK2X_BUF), 
                         .O(CLK2X_OUT));
   // Period Jitter (Peak-to-Peak) for block DCM_ADV_INST = 0.72 ns
   DCM_ADV DCM_ADV_INST (.CLKFB(CLKFB_IN), 
                         .CLKIN(CLKIN_IBUFG), 
                         .DADDR(GND[6:0]), 
                         .DCLK(GND2), 
                         .DEN(GND2), 
                         .DI(GND1[15:0]), 
                         .DWE(GND2), 
                         .PSCLK(GND2), 
                         .PSEN(GND2), 
                         .PSINCDEC(GND2), 
                         .RST(GND2), 
                         .CLKDV(CLKDV_BUF), 
                         .CLKFX(), 
                         .CLKFX180(), 
                         .CLK0(CLK0_BUF), 
                         .CLK2X(CLK2X_BUF), 
                         .CLK2X180(), 
                         .CLK90(), 
                         .CLK180(), 
                         .CLK270(), 
                         .DO(), 
                         .DRDY(), 
                         .LOCKED(LOCKED_OUT), 
                         .PSDONE())/* synthesis xc_props="CLK_FEEDBACK=1X, \
                         CLKDV_DIVIDE=2.000000, \
                         CLKFX_DIVIDE=1, \
                         CLKFX_MULTIPLY=4, \
                         CLKIN_DIVIDE_BY_2=FALSE, \
                         CLKIN_PERIOD=20.000000, \
                         CLKOUT_PHASE_SHIFT=NONE, \
                         DCM_AUTOCALIBRATION=TRUE, \
                         DCM_PERFORMANCE_MODE=MAX_SPEED, \
                         DESKEW_ADJUST=SYSTEM_SYNCHRONOUS, \
                         DFS_FREQUENCY_MODE=LOW, \
                         DLL_FREQUENCY_MODE=LOW, \
                         DUTY_CYCLE_CORRECTION=FALSE, \
                         PHASE_SHIFT=0, \
                         STARTUP_WAIT=FALSE, \
                         FACTORY_JF=F0F0" */;
   // synopsys translate_off
   defparam DCM_ADV_INST.CLK_FEEDBACK = "1X";
   defparam DCM_ADV_INST.CLKDV_DIVIDE = 2.000000;
   defparam DCM_ADV_INST.CLKFX_DIVIDE = 1;
   defparam DCM_ADV_INST.CLKFX_MULTIPLY = 4;
   defparam DCM_ADV_INST.CLKIN_DIVIDE_BY_2 = "FALSE";
   defparam DCM_ADV_INST.CLKIN_PERIOD = 20.000000;
   defparam DCM_ADV_INST.CLKOUT_PHASE_SHIFT = "NONE";
   defparam DCM_ADV_INST.DCM_AUTOCALIBRATION = "TRUE";
   defparam DCM_ADV_INST.DCM_PERFORMANCE_MODE = "MAX_SPEED";
   defparam DCM_ADV_INST.DESKEW_ADJUST = "SYSTEM_SYNCHRONOUS";
   defparam DCM_ADV_INST.DFS_FREQUENCY_MODE = "LOW";
   defparam DCM_ADV_INST.DLL_FREQUENCY_MODE = "LOW";
   defparam DCM_ADV_INST.DUTY_CYCLE_CORRECTION = "FALSE";
   defparam DCM_ADV_INST.PHASE_SHIFT = 0;
   defparam DCM_ADV_INST.STARTUP_WAIT = "FALSE";
   defparam DCM_ADV_INST.FACTORY_JF = 16'hF0F0;
   // synopsys translate_on
endmodule
