LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY I2S_TEST IS
	PORT ( CLK, nRST : IN STD_LOGIC;
	        PORESET  : IN STD_LOGIC;
	        
	        CDCLK    : OUT STD_LOGIC; --BCLK*256 => 12.288[MHz]
	        BCLK     : OUT STD_LOGIC; --BIT-CLK  => 48[kHz]
	        WS       : OUT STD_LOGIC; --LEFT-RIGHR SIGNAL
	       DATA_I    : IN STD_LOGIC;
	       DATA_O    : OUT STD_LOGIC;
	       
	       L3MODE    : OUT STD_LOGIC;
	       L3CLOCK   : OUT STD_LOGIC; --20[kHz] I2S-CLOCK
	       L3DATA    : INOUT STD_LOGIC); 
END I2S_TEST;

ARCHITECTURE RTL OF I2S_TEST IS
	SIGNAL RESET : STD_LOGIC;
--////////////////////////////////////////////
	CONSTANT SYS_CLOCK_SPEED : INTEGER := 25000000;
--////////////////////////////////////////////
	CONSTANT L3_CLOCK_SPEED : INTEGER := 10000;
	SIGNAL  L3_DIV_CLK : STD_LOGIC;
	SIGNAL L3_DIV_CNT : INTEGER RANGE 0 TO 25000000;
	SIGNAL L3_STEP_CNT : INTEGER RANGE 0 TO 10;
--////////////////////////////////////////////	
	TYPE STATE IS ( ADDR_MODE, DATA_MODE );
	SIGNAL STATUS : STATE;
	
	SIGNAL L3EN : STD_LOGIC;
	SIGNAL LUT_INDEX : INTEGER RANGE 0 TO 20;
	CONSTANT LUT_SIZE : INTEGER := 19;
	SIGNAL LUT_DATA : STD_LOGIC_VECTOR( 15 DOWNTO 0 );
	SIGNAL SYSCLK : STD_LOGIC;
	
	CONSTANT BIT_DIV : INTEGER := 130;
	SIGNAL BIT_CLK_CNT : INTEGER RANGE 0 TO 130;
	SIGNAL BITCLK : STD_LOGIC;
	
	CONSTANT WS_DIV : INTEGER := 16;
	SIGNAL WS_CLK_CNT : INTEGER RANGE 0 TO 16;
	SIGNAL WS_CLK : STD_LOGIC;
	
	SIGNAL DATA_BUF : STD_LOGIC_VECTOR( 7 DOWNTO 0 );
BEGIN

	CDCLK <= SYSCLK;
	RESET <= nRST AND PORESET;
	
	L3MODE <= '0' WHEN ((STATUS=ADDR_MODE) AND ((L3_STEP_CNT >= 1) AND (L3_STEP_CNT <= 9))) ELSE
		  '1';
		  
	DATA_O <= DATA_BUF(7);
	WS <= '1';
	BCLK <= BITCLK;

	PROCESS( L3_STEP_CNT, L3_DIV_CLK )
	BEGIN
		IF ((L3_STEP_CNT >= 1) AND (L3_STEP_CNT <= 8)) THEN
			L3CLOCK <= L3_DIV_CLK;
		ELSE
			L3CLOCK <= '1';
		END IF;
	END PROCESS; 
	
	PROCESS( CLK, nRST )
	BEGIN
		IF nRST='0' THEN
			SYSCLK <= '0';
		ELSIF RISING_EDGE(CLK) THEN
			SYSCLK <= NOT SYSCLK;
		END IF;
	END PROCESS;
	
	PROCESS( SYSCLK, nRST )
	BEGIN
		IF nRST='0' THEN
			BITCLK <= '0';
			BIT_CLK_CNT <= 0;
		ELSIF RISING_EDGE(SYSCLK) THEN
			IF (BIT_CLK_CNT = BIT_DIV ) THEN
				BITCLK <= NOT BITCLK;
				BIT_CLK_CNT <= 0;
			ELSE
				BIT_CLK_CNT <= BIT_CLK_CNT + 1;
			END IF;
		END IF;
	END PROCESS;
	
	PROCESS( SYSCLK, nRST )
	BEGIN
		IF (nRST='0') THEN
			WS_CLK <= '0';
			WS_CLK_CNT <= 0;
		ELSIF RISING_EDGE(SYSCLK) THEN
			IF ( WS_CLK_CNT = WS_DIV ) THEN
				WS_CLK_CNT <= 0;
				WS_CLK <= NOT WS_CLK;
			ELSE
				WS_CLK_CNT <= WS_CLK_CNT + 1;
			END IF;
		END IF;
	END PROCESS;
	
	PROCESS( BITCLK )
	BEGIN
		IF FALLING_EDGE(BITCLK) THEN
			DATA_BUF <= DATA_BUF( 6 DOWNTO 0 ) & DATA_I;
		END IF;
	END PROCESS;
			
			
			

	PROCESS( CLK,  RESET )
	BEGIN
		IF (RESET='0') THEN
			L3_DIV_CNT <= 0;
			L3_DIV_CLK <= '0';
		ELSIF RISING_EDGE(CLK) THEN
			IF (L3_DIV_CNT < (SYS_CLOCK_SPEED/L3_CLOCK_SPEED)) THEN
				L3_DIV_CNT <= L3_DIV_CNT + 1;
			ELSE
				L3_DIV_CNT <= 0;
				L3_DIV_CLK <= NOT L3_DIV_CLK;
			END IF;
		END IF;
	END PROCESS;

	PROCESS( L3_DIV_CLK, RESET )
	BEGIN
		IF RESET='0' THEN
			L3_STEP_CNT <= 0;
			STATUS <= ADDR_MODE;
		ELSIF RISING_EDGE(L3_DIV_CLK) THEN
			IF ( L3_STEP_CNT < 10 ) THEN
				L3_STEP_CNT <= L3_STEP_CNT + 1;
			ELSE
				L3_STEP_CNT <= 0;
				IF (STATUS=ADDR_MODE) THEN
					STATUS <= DATA_MODE;
				ELSE
					STATUS <= ADDR_MODE;
				END IF;
			END IF;
		END IF;
	END PROCESS;
		
	PROCESS( L3_STEP_CNT, RESET )
	BEGIN
		IF RESET='0' THEN
			LUT_INDEX <= 0;
			L3DATA <= 'Z';
		ELSIF (LUT_INDEX < LUT_SIZE ) THEN
			IF (STATUS=ADDR_MODE) THEN
				CASE L3_STEP_CNT IS
					WHEN 1 => L3DATA <= LUT_DATA(8);
					WHEN 2 => L3DATA <= LUT_DATA(9);
					WHEN 3 => L3DATA <= LUT_DATA(10);
					WHEN 4 => L3DATA <= LUT_DATA(11);
					WHEN 5 => L3DATA <= LUT_DATA(12);
					WHEN 6 => L3DATA <= LUT_DATA(13);
					WHEN 7 => L3DATA <= LUT_DATA(14);
					WHEN 8 => L3DATA <= LUT_DATA(15);
					WHEN 9 => L3DATA <= 'Z';
					WHEN OTHERS => NULL;
				END CASE;
			ELSE
				CASE L3_STEP_CNT IS
					WHEN 1 => L3DATA <= LUT_DATA(0);
					WHEN 2 => L3DATA <= LUT_DATA(1);
					WHEN 3 => L3DATA <= LUT_DATA(2);
					WHEN 4 => L3DATA <= LUT_DATA(3);
					WHEN 5 => L3DATA <= LUT_DATA(4);
					WHEN 6 => L3DATA <= LUT_DATA(5);
					WHEN 7 => L3DATA <= LUT_DATA(6);
					WHEN 8 => L3DATA <= LUT_DATA(7);
					WHEN 9 => LUT_INDEX <= LUT_INDEX + 1;
						  L3DATA <= 'Z';
					WHEN OTHERS => NULL;
				END CASE;				
			END IF;
		END IF;
	END PROCESS;
	
	PROCESS( LUT_INDEX )
	BEGIN
		CASE LUT_INDEX IS
			WHEN 0 => LUT_DATA <= X"1640";
			WHEN 1 => LUT_DATA <= X"1620";
			WHEN 2 => LUT_DATA <= X"1683";
			WHEN 3 => LUT_DATA <= X"1400";
			WHEN 4 => LUT_DATA <= X"1440";
			WHEN 5 => LUT_DATA <= X"14A0";
			WHEN 6 => LUT_DATA <= X"14C0";
			WHEN 7 => LUT_DATA <= X"14E4";
			WHEN 8 => LUT_DATA <= X"14C1";
			WHEN 9 => LUT_DATA <= X"14E4";
			WHEN 10 => LUT_DATA <= X"14C2";
			WHEN 11 => LUT_DATA <= X"14E1";
			WHEN 12 => LUT_DATA <= X"14C4";
			WHEN 13 => LUT_DATA <= X"14E2";
			WHEN 14 => LUT_DATA <= X"14C5";
			WHEN 15 => LUT_DATA <= X"14E6";
			WHEN 16 => LUT_DATA <= X"14C6";
			WHEN 17 => LUT_DATA <= X"14E0";
			WHEN 18 => LUT_DATA <= X"15FF";
			WHEN OTHERS => LUT_DATA <= ( OTHERS => '1' );
		END CASE;
	END PROCESS;
			
END RTL;
	

	
	
	
	
	
	
	
















				
			
		