library verilog;
use verilog.vl_types.all;
entity alt_exc_stripe is
    generic(
        processor       : string  := "ARM";
        device_size     : integer := 1000;
        sdram_width     : integer := 32;
        sdramdqm_width  : integer := 4;
        gpio_width      : integer := 4;
        boot_from_flash : string  := "FALSE";
        debug_extensions: string  := "TRUE";
        ebi0_width      : integer := 16;
        use_short_reset : string  := "FALSE";
        use_initialisation_files: string  := "FALSE";
        dp0_mode        : string  := "UNUSED";
        dp1_mode        : string  := "UNUSED";
        dp0_width       : integer := 2;
        dp1_width       : integer := 2;
        dp0_widthad     : integer := 2;
        dp1_widthad     : integer := 2;
        dp0_output_mode : string  := "UNREG";
        dp1_output_mode : string  := "UNREG";
        source          : string  := "";
        dp0_file        : string  := "";
        dp1_file        : string  := "";
        dp2_file        : string  := "";
        dp3_file        : string  := ""
    );
    port(
        clk_ref         : in     vl_logic;
        nreset          : inout  vl_logic;
        npor            : in     vl_logic;
        proc_tdi        : in     vl_logic;
        proc_tdo        : inout  vl_logic;
        proc_tms        : in     vl_logic;
        proc_tck        : in     vl_logic;
        proc_ntrst      : in     vl_logic;
        masterhclk      : in     vl_logic;
        masterhready    : in     vl_logic;
        masterhgrant    : in     vl_logic;
        masterhaddr     : out    vl_logic_vector(31 downto 0);
        masterhwdata    : out    vl_logic_vector(31 downto 0);
        masterhburst    : out    vl_logic_vector(2 downto 0);
        masterhtrans    : out    vl_logic_vector(1 downto 0);
        masterhsize     : out    vl_logic_vector(1 downto 0);
        masterhlock     : out    vl_logic;
        masterhwrite    : out    vl_logic;
        masterhbusreq   : out    vl_logic;
        masterhrdata    : in     vl_logic_vector(31 downto 0);
        masterhresp     : in     vl_logic_vector(1 downto 0);
        slavehclk       : in     vl_logic;
        slavehwrite     : in     vl_logic;
        slavehreadyi    : in     vl_logic;
        slavehselreg    : in     vl_logic;
        slavehsel       : in     vl_logic;
        slavehmastlock  : in     vl_logic;
        slavehrdata     : out    vl_logic_vector(31 downto 0);
        slavehresp      : out    vl_logic_vector(1 downto 0);
        slavehaddr      : in     vl_logic_vector(31 downto 0);
        slavehwdata     : in     vl_logic_vector(31 downto 0);
        slavehtrans     : in     vl_logic_vector(1 downto 0);
        slavehsize      : in     vl_logic_vector(1 downto 0);
        slavehburst     : in     vl_logic_vector(2 downto 0);
        slavehreadyo    : out    vl_logic;
        slavebuserrint  : out    vl_logic;
        debugrq         : in     vl_logic;
        debugext0       : in     vl_logic;
        debugext1       : in     vl_logic;
        debugiebrkpt    : in     vl_logic;
        debugdewpt      : in     vl_logic;
        debugextin      : in     vl_logic_vector(3 downto 0);
        intpld          : in     vl_logic_vector(5 downto 0);
        intuart         : out    vl_logic;
        inttimer0       : out    vl_logic;
        inttimer1       : out    vl_logic;
        intcommtx       : out    vl_logic;
        intcommrx       : out    vl_logic;
        intextpin       : in     vl_logic;
        debugack        : out    vl_logic;
        debugrng0       : out    vl_logic;
        debugrng1       : out    vl_logic;
        debugextout     : out    vl_logic_vector(3 downto 0);
        ebiack          : in     vl_logic;
        ebiwen          : out    vl_logic;
        ebioen          : out    vl_logic;
        ebiclk          : out    vl_logic;
        ebiaddr         : out    vl_logic_vector(24 downto 0);
        ebicsn          : out    vl_logic_vector(3 downto 0);
        ebibe           : out    vl_logic_vector(1 downto 0);
        ebidq           : inout  vl_logic_vector(15 downto 0);
        uartctsn        : in     vl_logic;
        uartdsrn        : in     vl_logic;
        uartrxd         : in     vl_logic;
        uarttxd         : out    vl_logic;
        uartrtsn        : out    vl_logic;
        uartdtrn        : out    vl_logic;
        uartdcdn        : inout  vl_logic;
        uartrin         : inout  vl_logic;
        sdramclk        : out    vl_logic;
        sdramclkn       : out    vl_logic;
        sdramclke       : out    vl_logic;
        sdramwen        : out    vl_logic;
        sdramcasn       : out    vl_logic;
        sdramrasn       : out    vl_logic;
        sdramdqm        : out    vl_logic_vector(3 downto 0);
        sdramcsn        : out    vl_logic_vector(1 downto 0);
        sdramaddr       : out    vl_logic_vector(14 downto 0);
        sdramdq         : inout  vl_logic_vector(31 downto 0);
        sdramdqs        : inout  vl_logic_vector(3 downto 0);
        traceclk        : out    vl_logic;
        tracesync       : out    vl_logic;
        tracepipestat   : out    vl_logic_vector(2 downto 0);
        tracepkt        : out    vl_logic_vector(15 downto 0);
        gpi             : in     vl_logic_vector;
        gpo             : out    vl_logic_vector;
        lockreqdp0      : in     vl_logic;
        lockreqdp1      : in     vl_logic;
        lockgrantdp0    : out    vl_logic;
        lockgrantdp1    : out    vl_logic;
        dp0_2_portaclk  : in     vl_logic;
        dp0_portaena    : in     vl_logic;
        dp0_portawe     : in     vl_logic;
        dp0_portadatain : in     vl_logic_vector;
        dp0_portaaddr   : in     vl_logic_vector;
        dp0_portadataout: out    vl_logic_vector;
        dp0_portbclk    : in     vl_logic;
        dp0_portbena    : in     vl_logic;
        dp0_portbwe     : in     vl_logic;
        dp0_portbdatain : in     vl_logic_vector;
        dp0_portbaddr   : in     vl_logic_vector;
        dp0_portbdataout: out    vl_logic_vector;
        dp1_3_portaclk  : in     vl_logic;
        dp1_portaena    : in     vl_logic;
        dp1_portawe     : in     vl_logic;
        dp1_portadatain : in     vl_logic_vector;
        dp1_portaaddr   : in     vl_logic_vector;
        dp1_portadataout: out    vl_logic_vector;
        dp1_portbclk    : in     vl_logic;
        dp1_portbena    : in     vl_logic;
        dp1_portbwe     : in     vl_logic;
        dp1_portbdatain : in     vl_logic_vector;
        dp1_portbaddr   : in     vl_logic_vector;
        dp1_portbdataout: out    vl_logic_vector;
        dp2_portaena    : in     vl_logic;
        dp2_portawe     : in     vl_logic;
        dp2_portadatain : in     vl_logic_vector;
        dp2_portaaddr   : in     vl_logic_vector;
        dp2_portadataout: out    vl_logic_vector;
        dp3_portaena    : in     vl_logic;
        dp3_portawe     : in     vl_logic;
        dp3_portadatain : in     vl_logic_vector;
        dp3_portaaddr   : in     vl_logic_vector;
        dp3_portadataout: out    vl_logic_vector
    );
end alt_exc_stripe;
