#- --=========================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- -----------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.18
#-
#- Release Information    : PrimeCell(TM)-PL092-r1p3-01ltd0
#-
#- -----------------------------------------------------------------------------
#- Purpose :
#-           Standard Verilog Library Makefile
#-
#- --=========================================================================--

MODULES = SmcParams.v \
          SmcRevAnd.v \
          SmcAhbif.v \
          SmcSynchroniser.v \
          SmcTSM.v \
          SmcEIB.v \
          SmcTimerWaitCont.v \
          SmcWrEnGen.v \
          SmcCore.v \
          TIC.v \
          DBI.v \
          Smc.v

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

#- --================================= End ===================================--
