#!/bin/sh
date > run2.list
OLD=bhchoi/tmp
NEW=bhchoi/Twin_ARM
SRC_DIR=./


	for FILE in `find $SRC_DIR -name "*.v" -print`
	do
		sed -e "s!$OLD!$NEW!g" $FILE > $FILE.new
		echo $FILE >> run2.list
		mv $FILE $FILE.old
		mv $FILE.new $FILE
	done


