#- --=================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- ---------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.5
#-
#- Release Information    : PrimeCell(TM)-PL041-REL1v0
#-
#- ---------------------------------------------------------------------
#- Purpose :
#-           A makefile to initiate TicTalk simulations 
#- --=================================================================--

# list of directories to make. Order is important
DIRS = common sys chip trickbox ticbox tbench

TEST_ENV = TICTALK

include $(GLOBAL)/$(SIMULATOR)/DirSimMakefile.mk

################################ End ###################################
