#-------------------------------------------------------------------------------
#-  This confidential and proprietary software may be used only as
#-  authorised by a licensing agreement from ARM Limited
#-    (C) COPYRIGHT 2000 ARM Limited
#-        ALL RIGHTS RESERVED
#-  The entire notice above must be reproduced on all authorised
#-  copies and copies may only be made to the extent permitted
#-  by a licensing agreement from ARM Limited.
#-------------------------------------------------------------------------------
#-
#-  Version and Release Control Information:
#-
#-  File Name              : makefile.rca
#-  File Revision          : 1.4
#-
#-  Release Information    : PrimeCell(TM)-PL011-REL1v3
#-
#-------------------------------------------------------------------------------
 
#-------------------------------------------------------------------------------
#-  Purpose :
#-            makefile for Verilog Trickbox files
#-
#-------------------------------------------------------------------------------

MODULES = \
         UartTrTXFCntl.v \
         UartTrTXRegFile.v \
         UartTrTXFIFO.v \
         UartTrIrdaRX.v \
         UartTrIrdaTX.v \
         UartTrRXFCntl.v \
         UartTrRXRegFile.v \
         UartTrRXFIFO.v \
         UartTrRX.v \
         UartTrTX.v \
         UartTrBaud.v \
         UartTrClk.v \
         UartTrRegBlock.v \
         UartTrApbif.v \
         UartTrDMA.v \
         UartTrIntLB.v \
         UartTrick.v
 
include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

############################## End of file #####################################
