library verilog;
use verilog.vl_types.all;
entity mmc_regsfr is
    port(
        mresetn         : in     vl_logic;
        mclk            : in     vl_logic;
        mcmdindex       : in     vl_logic_vector(5 downto 0);
        mcommand_ok     : in     vl_logic;
        mcmdfield       : in     vl_logic_vector(3 downto 0);
        resp_eox        : in     vl_logic;
        resp_eor        : in     vl_logic;
        block_len_error : in     vl_logic;
        hsfrxwr         : in     vl_logic_vector(18 downto 0);
        hwdata          : in     vl_logic_vector(31 downto 0);
        hcmdirqwr       : in     vl_logic_vector(14 downto 0);
        hrespirqwr      : in     vl_logic_vector(14 downto 0);
        hwrirqwr        : in     vl_logic_vector(14 downto 0);
        hrdirqwr        : in     vl_logic_vector(14 downto 0);
        hrespfield      : in     vl_logic_vector(3 downto 0);
        hcommand        : in     vl_logic_vector(47 downto 0);
        hcrc7_spi_off   : in     vl_logic;
        hcommand_ok     : in     vl_logic;
        hdecode60       : out    vl_logic_vector(15 downto 0);
        hdecode61       : out    vl_logic_vector(15 downto 0);
        hdecode62       : out    vl_logic_vector(15 downto 0);
        hdecode63       : out    vl_logic_vector(15 downto 0);
        hcmddef         : out    vl_logic_vector(63 downto 0);
        hblockmax       : out    vl_logic_vector(22 downto 0);
        hwblen          : out    vl_logic_vector(11 downto 0);
        hrblen          : out    vl_logic_vector(11 downto 0);
        hcardlock       : out    vl_logic;
        hcidfix         : out    vl_logic;
        hcsdfix         : out    vl_logic;
        heccdis         : out    vl_logic;
        heraseseq       : out    vl_logic_vector(8 downto 0);
        herasecmd       : out    vl_logic_vector(8 downto 0);
        hstatuscpu      : out    vl_logic_vector(31 downto 0);
        hstatuswren     : out    vl_logic_vector(31 downto 0);
        hstatuswr       : out    vl_logic;
        hcstnorm        : out    vl_logic_vector(4 downto 0);
        hcststop        : out    vl_logic_vector(4 downto 0);
        hcstmanu        : out    vl_logic_vector(4 downto 0);
        hcstwr          : out    vl_logic;
        hnid            : out    vl_logic_vector(7 downto 0);
        hncrmmc         : out    vl_logic_vector(7 downto 0);
        hncrspi         : out    vl_logic_vector(7 downto 0);
        hbsyend         : out    vl_logic;
        hbsybwcmd       : out    vl_logic;
        hgo_irq_state   : out    vl_logic;
        hwakeupen       : out    vl_logic;
        hcrc7_on_off    : out    vl_logic;
        hcrc16_on_off   : out    vl_logic;
        hcmdirqen       : out    vl_logic_vector(15 downto 0);
        hrespirqen      : out    vl_logic_vector(15 downto 0);
        hwrirqen        : out    vl_logic_vector(15 downto 0);
        hrdirqen        : out    vl_logic_vector(15 downto 0);
        hwrforce        : out    vl_logic;
        hrdforce        : out    vl_logic;
        hdis2rcv        : out    vl_logic;
        hstby_cmd2      : out    vl_logic;
        hstby_cmd3      : out    vl_logic;
        hbusy_cmd12     : out    vl_logic;
        hbusy_cmd12_resp: out    vl_logic_vector(2 downto 0);
        hrden           : out    vl_logic;
        hcmdirq         : out    vl_logic_vector(14 downto 0);
        hrespirq        : out    vl_logic_vector(14 downto 0);
        hwrirq          : out    vl_logic_vector(14 downto 0);
        hrdirq          : out    vl_logic_vector(14 downto 0);
        hlocken         : out    vl_logic_vector(63 downto 0);
        hdma1locken     : out    vl_logic_vector(7 downto 0);
        houtdly         : out    vl_logic_vector(5 downto 0)
    );
end mmc_regsfr;
