library verilog;
use verilog.vl_types.all;
entity ARMI_RS_ReadChannelsi is
    generic(
        BUS_WID         : integer := 32;
        ADDR_WID        : integer := 32;
        MASTERID_WID    : integer := 1;
        SLAVEID_WID     : integer := 2;
        AWLEN_WID       : integer := 4;
        AWSIZE_WID      : integer := 3;
        AWBURST_WID     : integer := 2;
        AWLOCK_WID      : integer := 2;
        AWCACHE_WID     : integer := 4;
        AWPROT_WID      : integer := 3;
        WSTRB_WID       : integer := 4;
        BRESP_WID       : integer := 2;
        RRESP_WID       : integer := 2;
        ARLEN_WID       : integer := 4;
        ARBURST_WID     : integer := 2;
        ARLOCK_WID      : integer := 2;
        ARCACHE_WID     : integer := 4;
        ARPROT_WID      : integer := 3;
        MASTER_WID      : integer := 3;
        SLAVE_WID       : integer := 4;
        SLAVE_NUM       : integer := 8;
        MASTER_NUM      : integer := 5;
        SELMASTER_WID   : integer := 2;
        Wr_REQDEPTH_WID : integer := 1;
        Rd_REQDEPTH_WID : integer := 1;
        WrPermit_SLAVECNTWID: integer := 1;
        RdPermit_SLAVECNTWID: integer := 1;
        ARSIZE_WID      : integer := 3
    );
    port(
        SelMAP1         : in     vl_logic;
        ACLK            : in     vl_logic;
        ARESETn         : in     vl_logic;
        ARADDRm2si      : in     vl_logic_vector;
        ARLENm2si       : in     vl_logic_vector;
        ARSIZEm2si      : in     vl_logic_vector;
        ARBURSTm2si     : in     vl_logic_vector;
        ARLOCKm2si      : in     vl_logic_vector;
        ARVALIDm2si     : in     vl_logic;
        ARREADYsi2m     : out    vl_logic;
        RRESPsi2m       : out    vl_logic_vector;
        RVALIDsi2m      : out    vl_logic;
        RDATAsi2m       : out    vl_logic_vector;
        RREADYm2si      : in     vl_logic;
        RLASTsi2m       : out    vl_logic;
        ARIDsi2mi2      : out    vl_logic_vector;
        ARADDRsi2mi2    : out    vl_logic_vector;
        ARLENsi2mi2     : out    vl_logic_vector;
        ARSIZEsi2mi2    : out    vl_logic_vector;
        ARBURSTsi2mi2   : out    vl_logic_vector;
        ARLOCKsi2mi2    : out    vl_logic_vector;
        ARCACHEsi2mi2   : out    vl_logic_vector;
        ARPROTsi2mi2    : out    vl_logic_vector;
        ARIDsi2mi5      : out    vl_logic_vector;
        ARADDRsi2mi5    : out    vl_logic_vector;
        ARLENsi2mi5     : out    vl_logic_vector;
        ARSIZEsi2mi5    : out    vl_logic_vector;
        ARBURSTsi2mi5   : out    vl_logic_vector;
        ARLOCKsi2mi5    : out    vl_logic_vector;
        ARCACHEsi2mi5   : out    vl_logic_vector;
        ARPROTsi2mi5    : out    vl_logic_vector;
        ARIDsi2mi6      : out    vl_logic_vector;
        ARADDRsi2mi6    : out    vl_logic_vector;
        ARLENsi2mi6     : out    vl_logic_vector;
        ARSIZEsi2mi6    : out    vl_logic_vector;
        ARBURSTsi2mi6   : out    vl_logic_vector;
        ARLOCKsi2mi6    : out    vl_logic_vector;
        ARCACHEsi2mi6   : out    vl_logic_vector;
        ARPROTsi2mi6    : out    vl_logic_vector;
        ARIDsi2mi7      : out    vl_logic_vector;
        ARADDRsi2mi7    : out    vl_logic_vector;
        ARLENsi2mi7     : out    vl_logic_vector;
        ARSIZEsi2mi7    : out    vl_logic_vector;
        ARBURSTsi2mi7   : out    vl_logic_vector;
        ARLOCKsi2mi7    : out    vl_logic_vector;
        ARCACHEsi2mi7   : out    vl_logic_vector;
        ARPROTsi2mi7    : out    vl_logic_vector;
        ARVALIDsi2mi    : out    vl_logic_vector;
        ARREADYmi2si    : in     vl_logic_vector;
        RIDmi22si       : in     vl_logic_vector;
        RRESPmi22si     : in     vl_logic_vector;
        RDATAmi22si     : in     vl_logic_vector;
        RIDmi52si       : in     vl_logic_vector;
        RRESPmi52si     : in     vl_logic_vector;
        RDATAmi52si     : in     vl_logic_vector;
        RIDmi62si       : in     vl_logic_vector;
        RRESPmi62si     : in     vl_logic_vector;
        RDATAmi62si     : in     vl_logic_vector;
        RIDmi72si       : in     vl_logic_vector;
        RRESPmi72si     : in     vl_logic_vector;
        RDATAmi72si     : in     vl_logic_vector;
        RVALIDmi2si     : in     vl_logic_vector;
        RREADYsi2mi     : out    vl_logic_vector;
        RLASTmi2si      : in     vl_logic_vector
    );
end ARMI_RS_ReadChannelsi;
