#-------------------------------------------------------------------------------
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from ARM Limited
#   (C) COPYRIGHT 1999 ARM Limited
#       ALL RIGHTS RESERVED
# The entire notice above must be reproduced on all authorised
# copies and copies may only be made to the extent permitted
# by a licensing agreement from ARM Limited.
#-------------------------------------------------------------------------------
# 
# Version and Release Control Information:
# 
# File Name              : makefile.rca
# File Revision          : 1.6
# 
# Release Information    : PrimeCell(TM)-PL011-REL1v3
# 
#-------------------------------------------------------------------------------

all: 
	@cp -f $(GLOBAL)/tictalk_ahb/verilog/sys/*.v .

clean:  
	@rm -rf *.v


############################## End of file #####################################
