#-====================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- ---------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.1
#-
#- Release Information    : PrimeCell(TM)-PL022-REL1v2
#-
#- ---------------------------------------------------------------------
#- Purpose  : makefile for VHDL Trickbox files
#- -==================================================================--

MODULES = SspTrApbif.vhd \
          SspTrRegCore.vhd \
          SspTrTxRegFile.vhd \
          SspTrTxFCntl.vhd \
          SspTrTxLJustify.vhd \
          SspTrTxFIFO.vhd \
          SspTrCkRsCntlr.vhd \
          SspTrRxRegFile.vhd \
          SspTrRxFCntl.vhd \
          SspTrRxFIFO.vhd \
          SspTrSynctoPCLK.vhd \
          SspTrSynctoSSPCLK.vhd \
          SspTrMTxRxCntl.vhd \
          SspTrSTxRxCntl.vhd \
          SspTrChecker.vhd \
          SspTrScaleCntr.vhd \
          SspTrDMA.vhd \
          SspTrick.vhd

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk 

################################# End ##################################
