#####################################################

#  Created by Design Compiler write_sdc on Fri Jul  1 12:48:01 2005

#####################################################
set sdc_version 1.4

create_clock -period 20 -waveform {0 10} [get_ports {clk}]
set_input_delay 1 -clock "clk" [get_ports {BistMode}]
set_input_delay 1 -clock "clk" [get_ports {p1_io[0]}]
set_input_delay 1 -clock "clk" [get_ports {p1_io[1]}]
set_input_delay 1 -clock "clk" [get_ports {p1_io[2]}]
set_input_delay 1 -clock "clk" [get_ports {p1_io[3]}]
set_input_delay 1 -clock "clk" [get_ports {p1_io[4]}]
set_input_delay 1 -clock "clk" [get_ports {p1_io[5]}]
set_input_delay 1 -clock "clk" [get_ports {p1_io[6]}]
set_input_delay 1 -clock "clk" [get_ports {p1_io[7]}]
set_input_delay 1 -clock "clk" [get_ports {in_xdat_a[0]}]
set_input_delay 1 -clock "clk" [get_ports {in_xdat_a[1]}]
set_input_delay 1 -clock "clk" [get_ports {in_xdat_a[2]}]
set_input_delay 1 -clock "clk" [get_ports {in_xdat_a[3]}]
set_input_delay 1 -clock "clk" [get_ports {in_xdat_a[4]}]
set_input_delay 1 -clock "clk" [get_ports {in_xdat_a[5]}]
set_input_delay 1 -clock "clk" [get_ports {in_xdat_a[6]}]
set_input_delay 1 -clock "clk" [get_ports {in_xdat_a[7]}]
set_input_delay 10 -clock "clk" [get_ports {rom_data_i[0]}]
set_input_delay 10 -clock "clk" [get_ports {rom_data_i[1]}]
set_input_delay 10 -clock "clk" [get_ports {rom_data_i[2]}]
set_input_delay 10 -clock "clk" [get_ports {rom_data_i[3]}]
set_input_delay 10 -clock "clk" [get_ports {rom_data_i[4]}]
set_input_delay 10 -clock "clk" [get_ports {rom_data_i[5]}]
set_input_delay 10 -clock "clk" [get_ports {rom_data_i[6]}]
set_input_delay 10 -clock "clk" [get_ports {rom_data_i[7]}]
set_input_delay 1 -clock "clk" [get_ports {all_rxd_i}]
set_input_delay 1 -clock "clk" [get_ports {all_t1_i}]
set_input_delay 1 -clock "clk" [get_ports {all_t0_i}]
set_input_delay 1 -clock "clk" [get_ports {int1_i}]
set_input_delay 1 -clock "clk" [get_ports {int0_i}]
set_input_delay 1 -clock "clk" [get_ports {rst_p}]
set_input_delay 1 -clock "clk" [get_ports {clk}]
set_output_delay 1 -clock "clk" [get_ports {ErrMap}]
set_output_delay 1 -clock "clk" [get_ports {Finish}]
set_output_delay 1 -clock "clk" [get_ports {BistFail}]
set_output_delay 1 -clock "clk" [get_ports {p1_io[0]}]
set_output_delay 1 -clock "clk" [get_ports {p1_io[1]}]
set_output_delay 1 -clock "clk" [get_ports {p1_io[2]}]
set_output_delay 1 -clock "clk" [get_ports {p1_io[3]}]
set_output_delay 1 -clock "clk" [get_ports {p1_io[4]}]
set_output_delay 1 -clock "clk" [get_ports {p1_io[5]}]
set_output_delay 1 -clock "clk" [get_ports {p1_io[6]}]
set_output_delay 1 -clock "clk" [get_ports {p1_io[7]}]
set_output_delay 1 -clock "clk" [get_ports {rd_xdat}]
set_output_delay 1 -clock "clk" [get_ports {wr_xdat_d1}]
set_output_delay 1 -clock "clk" [get_ports {en_xdat}]
set_output_delay 1 -clock "clk" [get_ports {out_xdat[0]}]
set_output_delay 1 -clock "clk" [get_ports {out_xdat[1]}]
set_output_delay 1 -clock "clk" [get_ports {out_xdat[2]}]
set_output_delay 1 -clock "clk" [get_ports {out_xdat[3]}]
set_output_delay 1 -clock "clk" [get_ports {out_xdat[4]}]
set_output_delay 1 -clock "clk" [get_ports {out_xdat[5]}]
set_output_delay 1 -clock "clk" [get_ports {out_xdat[6]}]
set_output_delay 1 -clock "clk" [get_ports {out_xdat[7]}]
set_output_delay 1 -clock "clk" [get_ports {addr_xdat[0]}]
set_output_delay 1 -clock "clk" [get_ports {addr_xdat[1]}]
set_output_delay 1 -clock "clk" [get_ports {addr_xdat[2]}]
set_output_delay 1 -clock "clk" [get_ports {addr_xdat[3]}]
set_output_delay 1 -clock "clk" [get_ports {addr_xdat[4]}]
set_output_delay 1 -clock "clk" [get_ports {addr_xdat[5]}]
set_output_delay 1 -clock "clk" [get_ports {addr_xdat[6]}]
set_output_delay 1 -clock "clk" [get_ports {addr_xdat[7]}]
set_output_delay 1 -clock "clk" [get_ports {addr_xdat[8]}]
set_output_delay 1 -clock "clk" [get_ports {addr_xdat[9]}]
set_output_delay 1 -clock "clk" [get_ports {addr_xdat[10]}]
set_output_delay 1 -clock "clk" [get_ports {addr_xdat[11]}]
set_output_delay 1 -clock "clk" [get_ports {addr_xdat[12]}]
set_output_delay 1 -clock "clk" [get_ports {addr_xdat[13]}]
set_output_delay 1 -clock "clk" [get_ports {addr_xdat[14]}]
set_output_delay 1 -clock "clk" [get_ports {addr_xdat[15]}]
set_output_delay 1 -clock "clk" [get_ports {rom_adr_o[0]}]
set_output_delay 1 -clock "clk" [get_ports {rom_adr_o[1]}]
set_output_delay 1 -clock "clk" [get_ports {rom_adr_o[2]}]
set_output_delay 1 -clock "clk" [get_ports {rom_adr_o[3]}]
set_output_delay 1 -clock "clk" [get_ports {rom_adr_o[4]}]
set_output_delay 1 -clock "clk" [get_ports {rom_adr_o[5]}]
set_output_delay 1 -clock "clk" [get_ports {rom_adr_o[6]}]
set_output_delay 1 -clock "clk" [get_ports {rom_adr_o[7]}]
set_output_delay 1 -clock "clk" [get_ports {rom_adr_o[8]}]
set_output_delay 1 -clock "clk" [get_ports {rom_adr_o[9]}]
set_output_delay 1 -clock "clk" [get_ports {rom_adr_o[10]}]
set_output_delay 1 -clock "clk" [get_ports {rom_adr_o[11]}]
set_output_delay 1 -clock "clk" [get_ports {rom_adr_o[12]}]
set_output_delay 1 -clock "clk" [get_ports {rom_adr_o[13]}]
set_output_delay 1 -clock "clk" [get_ports {rom_adr_o[14]}]
set_output_delay 1 -clock "clk" [get_ports {rom_adr_o[15]}]
set_output_delay 1 -clock "clk" [get_ports {clkb}]
set_output_delay 1 -clock "clk" [get_ports {all_txd_o}]
set_clock_transition -rise 0.5 [get_clocks {clk}]
set_clock_transition -fall 0.5 [get_clocks {clk}]
set_clock_uncertainty  0.3 [get_clocks {clk}]
set_clock_latency  1.5 [get_clocks {clk}]
set_max_transition 1 [current_design]
set_operating_conditions -max "slow" -max_library "slow" -min "fast" \
-min_library "fast"
set_wire_load_mode "enclosed" 
