library verilog;
use verilog.vl_types.all;
entity mmc_datacontrol is
    port(
        nrst            : in     vl_logic;
        sdreset         : in     vl_logic;
        pclk            : in     vl_logic;
        neg_ckpulse     : in     vl_logic;
        ckpulse         : in     vl_logic;
        byteorder       : in     vl_logic;
        sdidtimer       : in     vl_logic_vector(22 downto 0);
        sdibsize        : in     vl_logic_vector(15 downto 0);
        tarsp           : in     vl_logic;
        racmd           : in     vl_logic;
        blkmode         : in     vl_logic;
        widebus         : in     vl_logic;
        mmcplus         : in     vl_logic;
        dtst            : in     vl_logic;
        datmode         : in     vl_logic_vector(1 downto 0);
        blknum          : in     vl_logic_vector(15 downto 0);
        busyrsp         : in     vl_logic;
        abortcmd        : in     vl_logic;
        blknumcnt       : out    vl_logic_vector(15 downto 0);
        blkdatcnt       : out    vl_logic_vector(15 downto 0);
        nobusyset       : out    vl_logic;
        crcstaset       : out    vl_logic;
        datcrcset       : out    vl_logic;
        dattoutset      : out    vl_logic;
        datfinset       : out    vl_logic;
        busyfinset      : out    vl_logic;
        txdaton         : out    vl_logic;
        rxdaton         : out    vl_logic;
        dtstclr         : out    vl_logic;
        rspfinset       : in     vl_logic;
        cmdsentset      : in     vl_logic;
        txactive        : out    vl_logic;
        txrdptrinc      : out    vl_logic;
        rxactive        : out    vl_logic;
        rxwriteen       : out    vl_logic;
        fifowritedata   : out    vl_logic_vector(31 downto 0);
        tfrempty        : in     vl_logic;
        rffull          : in     vl_logic;
        fiforeaddata    : in     vl_logic_vector(31 downto 0);
        enclk2          : out    vl_logic;
        ndaten          : out    vl_logic;
        inv_ndaten      : out    vl_logic;
        datout          : out    vl_logic_vector(7 downto 0);
        inv_datout      : out    vl_logic_vector(7 downto 0);
        datin           : in     vl_logic_vector(7 downto 0);
        busychkidle     : out    vl_logic;
        datctrlidle     : out    vl_logic
    );
end mmc_datacontrol;
