library verilog;
use verilog.vl_types.all;
entity epxa10top is
    generic(
        dp0crambits     : integer := 0;
        dp1crambits     : integer := 0;
        globaldpcrambits: integer := 0
    );
    port(
        clkref          : in     vl_logic;
        npor            : in     vl_logic;
        reserved        : in     vl_logic;
        debugen         : in     vl_logic;
        bootflash       : in     vl_logic;
        msel            : in     vl_logic_vector(1 downto 0);
        reset_in_n      : in     vl_logic;
        reset_out_n     : out    vl_logic;
        proctdi         : in     vl_logic;
        proctdo         : inout  vl_logic;
        proctms         : in     vl_logic;
        proctck         : in     vl_logic;
        procntrst       : in     vl_logic;
        jselect         : in     vl_logic;
        sdramdqin       : in     vl_logic_vector(31 downto 0);
        sdramdqsin      : in     vl_logic_vector(3 downto 0);
        sdramdqout      : out    vl_logic_vector(31 downto 0);
        sdramdqsout     : out    vl_logic_vector(3 downto 0);
        sdramdqm        : out    vl_logic_vector(3 downto 0);
        sdramaddr       : out    vl_logic_vector(14 downto 0);
        sdramclk        : out    vl_logic;
        sdramclkn       : out    vl_logic;
        sdramclke       : out    vl_logic;
        sdramwen        : out    vl_logic;
        sdramcasn       : out    vl_logic;
        sdramrasn       : out    vl_logic;
        sdramcsn        : out    vl_logic_vector(1 downto 0);
        sdramdqoe       : out    vl_logic_vector(3 downto 0);
        sdramdqsoe      : out    vl_logic_vector(3 downto 0);
        sdramioselect   : out    vl_logic;
        ebiack          : in     vl_logic;
        ebidqin         : in     vl_logic_vector(15 downto 0);
        ebidqout        : out    vl_logic_vector(15 downto 0);
        ebiaddr         : out    vl_logic_vector(24 downto 0);
        ebiwen          : out    vl_logic;
        ebioen          : out    vl_logic;
        ebibe           : out    vl_logic_vector(1 downto 0);
        ebics           : out    vl_logic_vector(3 downto 0);
        ebiclk          : out    vl_logic;
        ebidqoe         : out    vl_logic;
        ebiioselect     : out    vl_logic;
        intextn         : in     vl_logic;
        uartctsn        : in     vl_logic;
        uartdcdin       : in     vl_logic;
        uartdsrn        : in     vl_logic;
        uartrxd         : in     vl_logic;
        uartriin        : in     vl_logic;
        uarttxd         : out    vl_logic;
        uartrtsn        : out    vl_logic;
        uartdtrn        : out    vl_logic;
        uartrion        : out    vl_logic;
        uartdcdon       : out    vl_logic;
        uartdcdrioe     : out    vl_logic;
        uartioselect    : out    vl_logic;
        traceclk        : out    vl_logic;
        tracepipestat   : out    vl_logic_vector(2 downto 0);
        tracepkt        : out    vl_logic_vector(15 downto 0);
        tracesync       : out    vl_logic;
        traceioselect   : out    vl_logic;
        slavehclkpld    : in     vl_logic;
        slavehwrite     : in     vl_logic;
        slavehreadyi    : in     vl_logic;
        slavehselreg    : in     vl_logic;
        slavehsel       : in     vl_logic;
        slavehmastlock  : in     vl_logic;
        slavehaddr      : in     vl_logic_vector(31 downto 0);
        slavehwdata     : in     vl_logic_vector(31 downto 0);
        slavehtrans     : in     vl_logic_vector(1 downto 0);
        slavehsize      : in     vl_logic_vector(1 downto 0);
        slavehburst     : in     vl_logic_vector(2 downto 0);
        slavehreadyo    : out    vl_logic;
        slavebuserrint  : out    vl_logic;
        slavehrdata     : out    vl_logic_vector(31 downto 0);
        slavehresp      : out    vl_logic_vector(1 downto 0);
        masterhclkbridge: in     vl_logic;
        masterhready    : in     vl_logic;
        masterhgrant    : in     vl_logic;
        masterhresp     : in     vl_logic_vector(1 downto 0);
        masterhrdata    : in     vl_logic_vector(31 downto 0);
        masterhwrite    : out    vl_logic;
        masterhlock     : out    vl_logic;
        masterhbusreq   : out    vl_logic;
        masterhtrans    : out    vl_logic_vector(1 downto 0);
        masterhsize     : out    vl_logic_vector(1 downto 0);
        masterhburst    : out    vl_logic_vector(2 downto 0);
        masterhaddr     : out    vl_logic_vector(31 downto 0);
        masterhwdata    : out    vl_logic_vector(31 downto 0);
        clk0dp0         : in     vl_logic;
        clk1dp0         : in     vl_logic;
        clk0dp1         : in     vl_logic;
        clk1dp1         : in     vl_logic;
        r0a0            : in     vl_logic_vector(15 downto 0);
        r0a1            : in     vl_logic_vector(14 downto 0);
        r0ce0           : in     vl_logic;
        r0ce1           : in     vl_logic;
        r0rd            : in     vl_logic_vector(31 downto 0);
        r0rw0           : in     vl_logic;
        r0rw1           : in     vl_logic;
        r0rq            : out    vl_logic_vector(31 downto 0);
        lockreqdp0      : in     vl_logic;
        lockgrntdp0     : out    vl_logic;
        r1a0            : in     vl_logic_vector(15 downto 0);
        r1a1            : in     vl_logic_vector(14 downto 0);
        r1ce0           : in     vl_logic;
        r1ce1           : in     vl_logic;
        r1rd            : in     vl_logic_vector(31 downto 0);
        r1rw0           : in     vl_logic;
        r1rw1           : in     vl_logic;
        r1rq            : out    vl_logic_vector(31 downto 0);
        lockreqdp1      : in     vl_logic;
        lockgrntdp1     : out    vl_logic;
        highaddress     : in     vl_logic;
        intuart         : out    vl_logic;
        inttimer0       : out    vl_logic;
        inttimer1       : out    vl_logic;
        intcommtx       : out    vl_logic;
        intcommrx       : out    vl_logic;
        intpld          : in     vl_logic_vector(5 downto 0);
        debugack        : out    vl_logic;
        debugrng1       : out    vl_logic;
        debugrng0       : out    vl_logic;
        debugrq         : in     vl_logic;
        debugext1       : in     vl_logic;
        debugext0       : in     vl_logic;
        debugiebrkpt    : in     vl_logic;
        debugdewpt      : in     vl_logic;
        debugextin      : in     vl_logic_vector(3 downto 0);
        debugextout     : out    vl_logic_vector(3 downto 0);
        initialize      : in     vl_logic;
        shortreset      : in     vl_logic
    );
end epxa10top;
