#-====================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2001 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- ---------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.1
#-
#- Release Information    : PrimeCell(TM)-PL131-REL1v0
#-
#- ---------------------------------------------------------------------
#- Purpose  : makefile for VHDL Trickbox files
#- -==================================================================--

MODULES = SciTrApbif.vhd       \
          SciTrTXCntl.vhd      \
          SciTrRXCntl.vhd      \
          SciTrTxFCntl.vhd     \
          SciTrTxRegFile.vhd   \
          SciTrTxFIFO.vhd      \
          SciTrRxFCntl.vhd     \
          SciTrRxRegFile.vhd   \
          SciTrRxFIFO.vhd      \
          SciTrRegBlk.vhd      \
          SciTrRegBlkUpd.vhd   \
          SciTrSynctoPCLK.vhd  \
          SciTrSynctoRFCLK.vhd \
          SciTrMux.vhd         \
          SciTrREFCLKGen.vhd   \
          SciTrTimCheck.vhd    \
          SciTrDMA.vhd         \
          SciTrick.vhd

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk 

################################# End ##################################
