library verilog;
use verilog.vl_types.all;
entity SDRCtl is
    generic(
        AW              : integer := 25;
        DW              : integer := 31;
        BW              : integer := 3;
        BL              : integer := 3;
        ID              : integer := 3;
        WQCD            : integer := 5;
        WQD             : integer := 63;
        RQCD            : integer := 5;
        RQD             : integer := 63;
        WBLQCD          : integer := 1;
        WBLQD           : integer := 3;
        RBLQCD          : integer := 1;
        RBLQD           : integer := 3;
        MDW             : integer := 31;
        DMW             : integer := 3;
        BAW             : integer := 1;
        RAW             : integer := 12;
        CAW             : integer := 10;
        TL              : integer := 4;
        RWW             : integer := 1;
        CD              : integer := 3;
        erc_powerup     : integer := 1;
        erc_epc         : integer := 2;
        erc_ar          : integer := 4;
        erc_mrs         : integer := 8;
        erc_idle        : integer := 16;
        erc_normal      : integer := 32;
        bc_null         : integer := 0;
        bc_mcas         : integer := 1;
        bc_mras         : integer := 2;
        bc_pc           : integer := 4;
        bc_sras         : integer := 8;
        bc_scas         : integer := 16;
        bc_epc          : integer := 32;
        ebc_null        : integer := 0;
        ebc_mcas        : integer := 1;
        ebc_mras        : integer := 2;
        ebc_pc          : integer := 4;
        ebc_sras        : integer := 8;
        ebc_scas        : integer := 16;
        ebc_epc         : integer := 32;
        ebc_bstop       : integer := 64
    );
    port(
        PORESETB        : in     vl_logic;
        ARESETB         : in     vl_logic;
        ACLK            : in     vl_logic;
        BA_AA           : in     vl_logic_vector;
        BA_TT           : in     vl_logic_vector;
        BA_RW           : in     vl_logic;
        BA_REQ          : in     vl_logic;
        BA_ID           : in     vl_logic_vector;
        BA_PM           : in     vl_logic;
        BA_STS          : out    vl_logic_vector(16 downto 0);
        RQFull          : in     vl_logic;
        WQFull          : in     vl_logic;
        SD_CKE          : out    vl_logic;
        SD_CSB          : out    vl_logic;
        SD_RASB         : out    vl_logic;
        SD_CASB         : out    vl_logic;
        SD_WEB          : out    vl_logic;
        SD_BADDR        : out    vl_logic_vector;
        SD_ADDR         : out    vl_logic_vector;
        PCLK            : in     vl_logic;
        PRESETB         : in     vl_logic;
        PSEL            : in     vl_logic;
        PENABLE         : in     vl_logic;
        PADDR           : in     vl_logic_vector(7 downto 2);
        PWRITE          : in     vl_logic;
        PWDATA          : in     vl_logic_vector(31 downto 0);
        PRDATA          : out    vl_logic_vector(31 downto 0)
    );
end SDRCtl;
