@TM:1158126658
@N: BN197 :"":0:0:0:-1|Writing property annotation file D:\projects\FPGABoard_Test\Test_7Segment\synplify\rev_1\FPGATop.smp.
@N: FX164 :"":0:0:0:-1|The option to pack flops in the IOB has not been specified 
@N: MT195 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT197 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@N: MT204 :"":0:0:0:-1|Autoconstrain Mode is ON
@TM:1158126656
@N: CG364 :"d:\projects\fpgaboard_test\test_7segment\rtl\fpgatop.v":16:7:16:13|Synthesizing module FPGATop
@W: CL170 :"d:\projects\fpgaboard_test\test_7segment\rtl\fpgatop.v":42:0:42:5|M
@TM:1158126658
@N:  :"d:\projects\fpgaboard_test\test_7segment\rtl\fpgatop.v":52:0:52:5|M
@TM:1158126656
@N: CG364 :"d:\projects\fpgaboard_test\test_7segment\rtl\sevensegment.v":16:7:16:18|Synthesizing module SevenSegment
@W: CL170 :"d:\projects\fpgaboard_test\test_7segment\rtl\sevensegment.v":54:0:54:5|M
@TM:1158126722
@W: MO127 :"d:\projects\fpgaboard_test\test_7segment\rtl\sevensegment.v":54:0:54:5|M
@TM:1158126656
@W: CL170 :"d:\projects\fpgaboard_test\test_7segment\rtl\sevensegment.v":57:0:57:5|M
@TM:1158126722
@W: MO127 :"d:\projects\fpgaboard_test\test_7segment\rtl\sevensegment.v":57:0:57:5|M
@TM:1158126656
@N: CL201 :"d:\projects\fpgaboard_test\test_7segment\rtl\sevensegment.v":62:0:62:5|M
@N: CG347 :"d:\projects\fpgaboard_test\test_7segment\rtl\sevensegment.v":71:25:71:37|M
@N: CG346 :"d:\projects\fpgaboard_test\test_7segment\rtl\sevensegment.v":71:39:71:47|M
@N: CG364 :"d:\projects\fpgaboard_test\test_7segment\rtl\sevensegment.v":97:7:97:22|Synthesizing module SevenSegmentCode
@TM:1158126722
@N: MF138 :"d:\projects\fpgaboard_test\test_7segment\rtl\sevensegment.v":108:1:108:4|M
@N: MO106 :"d:\projects\fpgaboard_test\test_7segment\rtl\sevensegment.v":108:1:108:4|M
