<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:dmp1_rel_mx="urn:dmp:idp1:mpeg21:2003:01-REL-MX-NS:2005:04" xmlns:dmp1_rel_r="urn:dmp:idp1:mpeg21:2003:01-REL-R-NS:2005:04" targetNamespace="urn:dmp:idp1:mpeg21:2003:01-REL-MX-NS:2005:04" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<import namespace="urn:dmp:idp1:mpeg21:2003:01-REL-R-NS:2005:04" schemaLocation="dmp1-rel-r-2005-04.xsd"/>
	<!-- Rights -->
	<element name="play" type="dmp1_rel_mx:Play" substitutionGroup="dmp1_rel_r:right"/>
	<element name="print" type="dmp1_rel_mx:Print" substitutionGroup="dmp1_rel_r:right"/>
	<element name="move" type="dmp1_rel_mx:Move" substitutionGroup="dmp1_rel_r:right"/>
	<!--Complex Types-->
	<complexType name="Play">
		<complexContent>
			<extension base="dmp1_rel_r:Right"/>
		</complexContent>
	</complexType>
	<complexType name="Print">
		<complexContent>
			<extension base="dmp1_rel_r:Right"/>
		</complexContent>
	</complexType>
	<complexType name="Move">
		<complexContent>
			<extension base="dmp1_rel_r:Right"/>
		</complexContent>
	</complexType>
</schema>
