<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:dmp2rk="urn:dmp:idp2:Represent:Key:2006:02" xmlns:dsig="http://www.w3.org/2000/09/xmldsig#" targetNamespace="urn:dmp:idp2:Represent:Key:2006:02" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="http://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd"/>
	<element name="Key">
		<complexType>
			<sequence>
				<element ref="dsig:KeyInfo"/>
				<element name="startDTS" type="unsignedLong" minOccurs="0"/>
				<element name="startPacketID" type="unsignedInt" minOccurs="0"/>
				<element name="expireDTS" type="unsignedLong" minOccurs="0"/>
				<element name="expirePacketID" type="unsignedInt" minOccurs="0"/>
			</sequence>
		</complexType>
	</element>
</schema>
