<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:dmp2_ipmpdidl="urn:dmp:idp2:mpeg21:2004:01-IPMPDIDL-NS:2006:02" xmlns:dmp2rc="urn:dmp:idp2:Represent:Content:2006:02" xmlns:dsig="http://www.w3.org/2000/09/xmldsig#" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:dmp:idp2:Represent:Content:2006:02" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="http://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd"/>
	<import namespace="urn:dmp:idp2:mpeg21:2004:01-IPMPDIDL-NS:2006:02" schemaLocation="dmp2ipmpdidl-2006-02.xsd"/>
	<element name="DMPInformation">
		<complexType>
			<sequence>
				<element ref="dmp2rc:Metadata"/>
				<sequence minOccurs="0">
					<element ref="dsig:Signature"/>
				</sequence>
			</sequence>
		</complexType>
	</element>
	<element name="Metadata" type="dmp2rc:MetadataType"/>
	<complexType name="MetadataType">
		<sequence>
			<choice>
				<group ref="dmp2_ipmpdidl:IPMPDIDLChildGroup" minOccurs="0"/>
				<element ref="dmp2rc:StructuredData" maxOccurs="unbounded"/>
			</choice>
		</sequence>
		<attribute name="id" type="anyURI" use="optional"/> 
	</complexType>
	<element name="StructuredData" type="dmp2rc:StructuredDataType">
		<annotation>
			<documentation>IDP-2 Metadata are of type dmp2rm:TVAMain and are denoted by the attribute 'ref ' value of "urn:dmp:idp2:Represent:Metadata:2006:02" which refers to the DMP IDP-2 TVA metadata profile</documentation>
		</annotation>
	</element>
	<complexType name="StructuredDataType">
		<sequence>
			<any namespace="##any" processContents="lax" minOccurs="0"/>
		</sequence>
		<attribute name="ref" type="anyURI" default="urn:dmp:idp2:Represent:Metadata:2006:02"/>
	</complexType>
	<element name="DCISignature" type="dmp2rc:DCISignatureType"/>
	<complexType name="DCISignatureType">
		<sequence maxOccurs="unbounded">
			<element name="IssuerID" type="anyURI" minOccurs="0"/>
			<element ref="dsig:Signature"/>
		</sequence>
	</complexType>
	<element name="DCIHash" type="dmp2rc:DCIHashType"/>
	<complexType name="DCIHashType">
		<sequence maxOccurs="unbounded">
			<element ref="dsig:CanonicalizationMethod"/>
			<element ref="dsig:Reference"/>
		</sequence>
	</complexType>
</schema>
