<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:mx="urn:mpeg:mpeg21:2003:01-REL-MX-NS" xmlns:r="urn:mpeg:mpeg21:2003:01-REL-R-NS" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:mpeg:mpeg21:2003:01-REL-MX-NS" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:import namespace="urn:mpeg:mpeg21:2003:01-REL-R-NS" schemaLocation="rel-r-bpx-v1.xsd"/>
	<xsd:import namespace="http://www.w3.org/2001/04/xmlenc#" schemaLocation="http://www.w3.org/TR/2002/REC-xmlenc-core-20021210/xenc-schema.xsd"/>
	<!-- Rights -->
	<xsd:element name="enhance" type="mx:Enhance" substitutionGroup="r:right"/>
	<xsd:element name="execute" type="mx:Execute" substitutionGroup="r:right"/>
	<xsd:element name="play" type="mx:Play" substitutionGroup="r:right"/>
	<xsd:element name="print" type="mx:Print" substitutionGroup="r:right"/>
	<!--Complex Types-->
	<xsd:complexType name="Enhance">
		<xsd:complexContent>
			<xsd:extension base="r:Right"/>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="Execute">
		<xsd:complexContent>
			<xsd:extension base="r:Right"/>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="Play">
		<xsd:complexContent>
			<xsd:extension base="r:Right"/>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="Print">
		<xsd:complexContent>
			<xsd:extension base="r:Right"/>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:schema>
