@TM:1186107621
@N: BN191 :"":0:0:0:-1|Writing property annotation file D:\ETRI_UWB\ADK_PCI_BOARD\synplify\rev_2_identify\PCI_FPGA.tap.
@N: BN225 :"":0:0:0:-1|Writing default property annotation file D:\ETRI_UWB\ADK_PCI_BOARD\synplify\rev_2_identify\PCI_FPGA.map.
@N: FX164 :"":0:0:0:-1|The option to pack flops in the IOB has not been specified 
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF258 :"":0:0:0:-1|Gated clock conversion disabled 
@N: MT195 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT197 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@TM:1186107557
@N: CG364 :"c:\program files\synplicity\fpga_862\lib\xilinx\unisim.v":141:7:141:19|Synthesizing module BSCAN_VIRTEX4
@N: CG364 :"c:\program files\synplicity\fpga_862\lib\xilinx\unisim.v":166:7:166:10|Synthesizing module BUFG
@TM:1186391206
@N: CG364 :"c:\program files\synplicity\fpga_862\lib\xilinx\unisim.v":17289:7:17289:18|Synthesizing module RAMB16_S9_S9
@N: CG364 :"c:\program files\synplicity\fpga_862\lib\xilinx\unisim.v":19202:7:19202:13|Synthesizing module SRLC16E
@TM:1186107557
@N:  :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\identify.log":0:0:0:0|M
@TM:1186391206
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\pci_fpga.v":16:7:16:14|Synthesizing module PCI_FPGA
@W: CL159 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\pci_fpga.v":118:14:118:22|M
@TM:1186399875
@W: CG360 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\pci_fpga.v":197:5:197:14|M
@TM:1186398925
@W: CG360 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\pci_fpga.v":203:5:203:15|M
@W: CG360 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\pci_fpga.v":204:5:204:15|M
@W: CG360 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\pci_fpga.v":205:5:205:15|M
@W: CG360 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\pci_fpga.v":206:5:206:15|M
@W: CG360 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\pci_fpga.v":207:5:207:15|M
@TM:1186405592
@W: CL168 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\pci_fpga.v":216:5:216:10|M
@W: CL168 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\pci_fpga.v":220:5:220:10|M
@W: CL168 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\pci_fpga.v":224:5:224:10|M
@W: CL168 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\pci_fpga.v":228:5:228:10|M
@TM:1186405597
@N:  :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\pci_fpga.v":287:0:287:5|M
@TM:1186391206
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":16:7:16:18|Synthesizing module SevenSegment
@TM:1186391210
@W: BN115 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":35:17:35:22|M
@W: BN115 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":40:17:40:22|M
@W: BN115 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":45:17:45:23|M
@W: BN115 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":50:17:50:24|M
@W: BN116 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":56:0:56:5|M
@W: BN132 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":56:0:56:5|M
@TM:1186391206
@W: CL170 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":56:0:56:5|M
@TM:1186391210
@W: BN116 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":59:0:59:5|M
@W: BN132 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":59:0:59:5|M
@TM:1186391206
@W: CL170 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":59:0:59:5|M
@TM:1186391210
@W: BN132 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":64:0:64:5|M
@TM:1186391206
@N: CL201 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":64:0:64:5|M
@TM:1186391210
@W: MO129 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":64:0:64:5|M
@TM:1186391203
@N: CG347 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":73:25:73:37|M
@N: CG346 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":73:39:73:47|M
@TM:1186391206
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\sevensegment.v":111:7:111:22|Synthesizing module SevenSegmentCode
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":1:7:1:18|Synthesizing module b9_ORbIwXaEF
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":31:7:31:20|Synthesizing module jtag_interface
@TM:1186391252
@W: MT246 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":86:16:86:25|M
@TM:1186391206
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":100:7:100:26|Synthesizing module b16_Rcmi_qlx9_yHpm7y
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":151:7:151:16|Synthesizing module comm_block
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":216:7:216:16|Synthesizing module b7_V71OJqz
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":263:7:263:20|Synthesizing module b10_nYWNT9NwbL
@TM:1186391210
@N: MF179 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":297:22:297:46|M
@N:  :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":301:2:301:7|M
@TM:1186391206
@W: CL189 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":307:2:307:7|M
@N: CL201 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":307:2:307:7|M
@TM:1186391203
@N: CG347 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":381:33:381:45|M
@TM:1186391206
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":393:7:393:18|Synthesizing module b9_O2yyf_fG2
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":400:7:400:25|Synthesizing module b15_CRGcTCua_eH4_lv
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":484:7:484:21|Synthesizing module b11_PSyil9s1fkT
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":1431:7:1431:16|Synthesizing module b7_PfFzrNY
@W: CL209 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":1447:16:1447:27|M
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":1491:7:1491:16|Synthesizing module b7_OCByLXC
@TM:1186391203
@N: CG334 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":1562:14:1562:26|M
@N: CG333 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":1565:14:1565:25|M
@TM:1186391210
@W: MO129 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":1570:2:1570:7|M
@N:  :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":1579:2:1579:7|M
@TM:1186391206
@N: CL201 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":1587:2:1587:7|M
@TM:1186391203
@N: CG347 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":1603:42:1603:54|M
@N: CG347 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":1620:39:1620:51|M
@TM:1186391206
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":1735:7:1735:22|Synthesizing module b12_OFWNT9_wMeEd
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":1789:7:1789:25|Synthesizing module GenericRAMram_block
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":1825:7:1825:23|Synthesizing module ramSliceram_block
@TM:1186391203
@N: CG347 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":1914:37:1914:49|M
@TM:1186391206
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":1927:7:1927:15|Synthesizing module ram_block
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2065:7:2065:16|Synthesizing module b7_OFWNT9s
@TM:1186391203
@N: CG334 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2105:14:2105:26|M
@N: CG333 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2108:14:2108:25|M
@TM:1186391213
@W: BN132 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2110:2:2110:7|M
@TM:1186391206
@N: CL135 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2110:2:2110:7|M
@W: CL169 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2110:2:2110:7|M
@TM:1186391210
@N:  :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2152:2:2152:7|M
@N:  :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2167:2:2167:7|M
@TM:1186391206
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2255:7:2255:22|Synthesizing module b12_nvmFL_la1xyH
@TM:1186391203
@N: CG347 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2306:44:2306:56|M
@TM:1186391206
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2320:7:2320:16|Synthesizing module b7_PLF_6lN
@TM:1186391203
@N: CG347 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2360:42:2360:54|M
@TM:1186391206
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2374:7:2374:12|Synthesizing module b3_uKr
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2459:7:2459:17|Synthesizing module b8_nR_ymqrG
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2555:7:2555:12|Synthesizing module b3_12m
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2667:7:2667:13|Synthesizing module ldic1_0
@N: CG364 :"d:\etri_uwb\adk_pci_board\synplify\rev_2_identify\instr_sources\syn_dics.v":2806:7:2806:12|Synthesizing module iice_0
