library verilog;
use verilog.vl_types.all;
entity dmacchreqproc is
    port(
        hclk            : in     vl_logic;
        hresetn         : in     vl_logic;
        dmacbreqch      : in     vl_logic_vector(15 downto 0);
        dmaclbreqch     : in     vl_logic_vector(15 downto 0);
        dmacsreqch      : in     vl_logic_vector(15 downto 0);
        dmaclsreqch     : in     vl_logic_vector(15 downto 0);
        clrinterr       : in     vl_logic;
        clrinttc        : in     vl_logic;
        srcperiph       : in     vl_logic_vector(3 downto 0);
        dstperiph       : in     vl_logic_vector(3 downto 0);
        flowcntl        : in     vl_logic_vector(2 downto 0);
        setinterr       : in     vl_logic;
        errintmask      : in     vl_logic;
        tcintmask       : in     vl_logic;
        srcselect       : in     vl_logic;
        dstselect       : in     vl_logic;
        lliselforpkt    : in     vl_logic;
        dmacchsrcaddr   : in     vl_logic_vector(31 downto 0);
        dmacchdstaddr   : in     vl_logic_vector(31 downto 0);
        protstat        : in     vl_logic_vector(2 downto 0);
        swidth          : in     vl_logic_vector(2 downto 0);
        dwidth          : in     vl_logic_vector(2 downto 0);
        sbsize          : in     vl_logic_vector(2 downto 0);
        lliaddressub    : in     vl_logic_vector(31 downto 2);
        srcincr         : in     vl_logic;
        destincr        : in     vl_logic;
        channelen       : in     vl_logic;
        trfsizesrc      : in     vl_logic_vector(11 downto 0);
        abortreqsrcm1   : in     vl_logic;
        abortreqsrcm2   : in     vl_logic;
        dmacclrsrc      : in     vl_logic;
        dmactcsrc       : in     vl_logic;
        srcnumofxfers   : in     vl_logic_vector(4 downto 0);
        abortreqdstm1   : in     vl_logic;
        abortreqdstm2   : in     vl_logic;
        dmacclrdst      : in     vl_logic;
        dmactcdst       : in     vl_logic;
        setinttc        : in     vl_logic;
        setllireq       : in     vl_logic;
        dstnumofxfers   : in     vl_logic_vector(4 downto 0);
        dstdmacstate    : in     vl_logic_vector(4 downto 0);
        unsetllireq     : in     vl_logic;
        finishedlli     : in     vl_logic;
        sourcemask      : in     vl_logic;
        destmask        : in     vl_logic;
        chgntm1         : in     vl_logic;
        chgntm2         : in     vl_logic;
        dstburston      : in     vl_logic;
        fifononempty    : in     vl_logic;
        chsrcbreq       : out    vl_logic;
        chsrclbreq      : out    vl_logic;
        chsrcsreq       : out    vl_logic;
        chsrclsreq      : out    vl_logic;
        srcstart        : out    vl_logic;
        chdstbreq       : out    vl_logic;
        chdstlbreq      : out    vl_logic;
        chdstsreq       : out    vl_logic;
        chdstlsreq      : out    vl_logic;
        dststart        : out    vl_logic;
        llistart        : out    vl_logic;
        chxferabortm1   : out    vl_logic;
        chxferabortm2   : out    vl_logic;
        chreqm1         : out    vl_logic;
        chreqm2         : out    vl_logic;
        chnumofxfersm1  : out    vl_logic_vector(4 downto 0);
        chnumofxfersm2  : out    vl_logic_vector(4 downto 0);
        chincrm1        : out    vl_logic;
        chincrm2        : out    vl_logic;
        chaddrm1        : out    vl_logic_vector(31 downto 0);
        chaddrm2        : out    vl_logic_vector(31 downto 0);
        chprotm1        : out    vl_logic_vector(2 downto 0);
        chprotm2        : out    vl_logic_vector(2 downto 0);
        chwidthm1       : out    vl_logic_vector(2 downto 0);
        chwidthm2       : out    vl_logic_vector(2 downto 0);
        chdirxnm1       : out    vl_logic;
        chdirxnm2       : out    vl_logic;
        ldsrcindstflow  : out    vl_logic;
        clearreq        : out    vl_logic_vector(15 downto 0);
        rawinterrch     : out    vl_logic;
        rawinttcch      : out    vl_logic;
        errclrreq       : out    vl_logic_vector(15 downto 0);
        interrch        : out    vl_logic;
        inttcch         : out    vl_logic;
        sigtc           : out    vl_logic_vector(15 downto 0)
    );
end dmacchreqproc;
