library verilog;
use verilog.vl_types.all;
entity SBUS is
    generic(
        BUS_WID         : integer := 32;
        ADDR_WID        : integer := 32;
        MASTERID_WID    : integer := 1;
        SLAVEID_WID     : integer := 4;
        AWLEN_WID       : integer := 4;
        AWSIZE_WID      : integer := 3;
        AWBURST_WID     : integer := 2;
        AWLOCK_WID      : integer := 2;
        AWCACHE_WID     : integer := 4;
        AWPROT_WID      : integer := 3;
        WSTRB_WID       : integer := 4;
        BRESP_WID       : integer := 2;
        RRESP_WID       : integer := 2;
        ARLEN_WID       : integer := 4;
        ARBURST_WID     : integer := 2;
        ARLOCK_WID      : integer := 2;
        ARCACHE_WID     : integer := 4;
        ARPROT_WID      : integer := 3;
        MASTER_WID      : integer := 3;
        SLAVE_WID       : integer := 4;
        SLAVE_NUM       : integer := 8;
        MASTER_NUM      : integer := 5;
        SELMASTER_WID   : integer := 3;
        Wr_REQDEPTH_WID : integer := 4;
        Rd_REQDEPTH_WID : integer := 4;
        WrPermit_SLAVECNTWID: integer := 1;
        RdPermit_SLAVECNTWID: integer := 1;
        ARSIZE_WID      : integer := 3;
        WRITECHID0_WID  : integer := 1;
        WRITECHID1_WID  : integer := 1;
        WRITECHID2_WID  : integer := 1;
        WRITECHID3_WID  : integer := 1;
        WRITECHID4_WID  : integer := 1;
        READCHID0_WID   : integer := 1;
        READCHID1_WID   : integer := 1;
        READCHID2_WID   : integer := 1;
        READCHID3_WID   : integer := 1;
        READCHID4_WID   : integer := 1;
        WR_SLAVEID0_WID : integer := 2;
        WR_SLAVEID1_WID : integer := 2;
        WR_SLAVEID2_WID : integer := 3;
        WR_SLAVEID3_WID : integer := 2;
        WR_SLAVEID4_WID : integer := 2;
        WR_SLAVEID5_WID : integer := 3;
        WR_SLAVEID6_WID : integer := 3;
        WR_SLAVEID7_WID : integer := 3;
        RD_SLAVEID0_WID : integer := 2;
        RD_SLAVEID1_WID : integer := 2;
        RD_SLAVEID2_WID : integer := 4;
        RD_SLAVEID3_WID : integer := 2;
        RD_SLAVEID4_WID : integer := 2;
        RD_SLAVEID5_WID : integer := 4;
        RD_SLAVEID6_WID : integer := 4;
        RD_SLAVEID7_WID : integer := 4;
        SELMASTER0_WID  : integer := 1;
        SELMASTER1_WID  : integer := 1;
        SELMASTER2_WID  : integer := 3;
        SELMASTER3_WID  : integer := 1;
        SELMASTER4_WID  : integer := 1;
        SELMASTER5_WID  : integer := 3;
        SELMASTER6_WID  : integer := 3;
        SELMASTER7_WID  : integer := 3;
        SELWRITE0_WID   : integer := 1;
        SELREAD0_WID    : integer := 1;
        SELWRITE1_WID   : integer := 1;
        SELREAD1_WID    : integer := 1;
        SELWRITE2_WID   : integer := 2;
        SELREAD2_WID    : integer := 3;
        SELWRITE3_WID   : integer := 1;
        SELREAD3_WID    : integer := 1;
        SELWRITE4_WID   : integer := 1;
        SELREAD4_WID    : integer := 1;
        SELWRITE5_WID   : integer := 2;
        SELREAD5_WID    : integer := 3;
        SELWRITE6_WID   : integer := 2;
        SELREAD6_WID    : integer := 3;
        SELWRITE7_WID   : integer := 2;
        SELREAD7_WID    : integer := 3;
        SLAVE_WRITEID0_WID: integer := 1;
        SLAVE_WRITEID1_WID: integer := 1;
        SLAVE_WRITEID2_WID: integer := 1;
        SLAVE_WRITEID3_WID: integer := 1;
        SLAVE_WRITEID4_WID: integer := 1;
        SLAVE_WRITEID5_WID: integer := 1;
        SLAVE_WRITEID6_WID: integer := 1;
        SLAVE_WRITEID7_WID: integer := 1;
        SLAVE_READID0_WID: integer := 1;
        SLAVE_READID1_WID: integer := 1;
        SLAVE_READID2_WID: integer := 1;
        SLAVE_READID3_WID: integer := 1;
        SLAVE_READID4_WID: integer := 1;
        SLAVE_READID5_WID: integer := 1;
        SLAVE_READID6_WID: integer := 1;
        SLAVE_READID7_WID: integer := 1
    );
    port(
        AWADDR_ARMD     : in     vl_logic_vector;
        AWLEN_ARMD      : in     vl_logic_vector;
        AWSIZE_ARMD     : in     vl_logic_vector;
        AWBURST_ARMD    : in     vl_logic_vector;
        AWLOCK_ARMD     : in     vl_logic_vector;
        AWVALID_ARMD    : in     vl_logic;
        AWREADY_2_ARMD  : out    vl_logic;
        WDATA_ARMD      : in     vl_logic_vector;
        WSTRB_ARMD      : in     vl_logic_vector;
        WLAST_ARMD      : in     vl_logic;
        WVALID_ARMD     : in     vl_logic;
        WREADY_2_ARMD   : out    vl_logic;
        BRESP_2_ARMD    : out    vl_logic_vector;
        BVALID_2_ARMD   : out    vl_logic;
        BREADY_ARMD     : in     vl_logic;
        AWID_DMAC       : in     vl_logic_vector;
        AWADDR_DMAC     : in     vl_logic_vector;
        AWLEN_DMAC      : in     vl_logic_vector;
        AWSIZE_DMAC     : in     vl_logic_vector;
        AWBURST_DMAC    : in     vl_logic_vector;
        AWVALID_DMAC    : in     vl_logic;
        AWREADY_2_DMAC  : out    vl_logic;
        WID_DMAC        : in     vl_logic_vector;
        WDATA_DMAC      : in     vl_logic_vector;
        WSTRB_DMAC      : in     vl_logic_vector;
        WLAST_DMAC      : in     vl_logic;
        WVALID_DMAC     : in     vl_logic;
        WREADY_2_DMAC   : out    vl_logic;
        BID_2_DMAC      : out    vl_logic_vector;
        BRESP_2_DMAC    : out    vl_logic_vector;
        BVALID_2_DMAC   : out    vl_logic;
        BREADY_DMAC     : in     vl_logic;
        AWADDR_MAC      : in     vl_logic_vector;
        AWLEN_MAC       : in     vl_logic_vector;
        AWSIZE_MAC      : in     vl_logic_vector;
        AWBURST_MAC     : in     vl_logic_vector;
        AWVALID_MAC     : in     vl_logic;
        AWREADY_2_MAC   : out    vl_logic;
        WDATA_MAC       : in     vl_logic_vector;
        WSTRB_MAC       : in     vl_logic_vector;
        WLAST_MAC       : in     vl_logic;
        WVALID_MAC      : in     vl_logic;
        WREADY_2_MAC    : out    vl_logic;
        BRESP_2_MAC     : out    vl_logic_vector;
        BVALID_2_MAC    : out    vl_logic;
        BREADY_MAC      : in     vl_logic;
        AWADDR_PCI      : in     vl_logic_vector;
        AWLEN_PCI       : in     vl_logic_vector;
        AWSIZE_PCI      : in     vl_logic_vector;
        AWBURST_PCI     : in     vl_logic_vector;
        AWVALID_PCI     : in     vl_logic;
        AWREADY_2_PCI   : out    vl_logic;
        WDATA_PCI       : in     vl_logic_vector;
        WSTRB_PCI       : in     vl_logic_vector;
        WLAST_PCI       : in     vl_logic;
        WVALID_PCI      : in     vl_logic;
        WREADY_2_PCI    : out    vl_logic;
        BRESP_2_PCI     : out    vl_logic_vector;
        BVALID_2_PCI    : out    vl_logic;
        BREADY_PCI      : in     vl_logic;
        AWID_2_AHB0     : out    vl_logic_vector;
        AWADDR_2_AHB0   : out    vl_logic_vector;
        AWLEN_2_AHB0    : out    vl_logic_vector;
        AWSIZE_2_AHB0   : out    vl_logic_vector;
        AWBURST_2_AHB0  : out    vl_logic_vector;
        AWVALID_2_AHB0  : out    vl_logic;
        AWREADY_AHB0    : in     vl_logic;
        WID_2_AHB0      : out    vl_logic_vector;
        WDATA_2_AHB0    : out    vl_logic_vector;
        WLAST_2_AHB0    : out    vl_logic;
        WVALID_2_AHB0   : out    vl_logic;
        WREADY_AHB0     : in     vl_logic;
        BID_AHB0        : in     vl_logic_vector;
        BRESP_AHB0      : in     vl_logic_vector;
        BVALID_AHB0     : in     vl_logic;
        BREADY_2_AHB0   : out    vl_logic;
        AWID_2_AHB1     : out    vl_logic_vector;
        AWADDR_2_AHB1   : out    vl_logic_vector;
        AWLEN_2_AHB1    : out    vl_logic_vector;
        AWSIZE_2_AHB1   : out    vl_logic_vector;
        AWBURST_2_AHB1  : out    vl_logic_vector;
        AWVALID_2_AHB1  : out    vl_logic;
        AWREADY_AHB1    : in     vl_logic;
        WID_2_AHB1      : out    vl_logic_vector;
        WDATA_2_AHB1    : out    vl_logic_vector;
        WLAST_2_AHB1    : out    vl_logic;
        WVALID_2_AHB1   : out    vl_logic;
        WREADY_AHB1     : in     vl_logic;
        BID_AHB1        : in     vl_logic_vector;
        BRESP_AHB1      : in     vl_logic_vector;
        BVALID_AHB1     : in     vl_logic;
        BREADY_2_AHB1   : out    vl_logic;
        AWID_2_DDR      : out    vl_logic_vector;
        AWADDR_2_DDR    : out    vl_logic_vector;
        AWLEN_2_DDR     : out    vl_logic_vector;
        AWSIZE_2_DDR    : out    vl_logic_vector;
        AWBURST_2_DDR   : out    vl_logic_vector;
        AWVALID_2_DDR   : out    vl_logic;
        AWREADY_DDR     : in     vl_logic;
        WID_2_DDR       : out    vl_logic_vector;
        WDATA_2_DDR     : out    vl_logic_vector;
        WSTRB_2_DDR     : out    vl_logic_vector;
        WLAST_2_DDR     : out    vl_logic;
        WVALID_2_DDR    : out    vl_logic;
        WREADY_DDR      : in     vl_logic;
        BID_DDR         : in     vl_logic_vector;
        BRESP_DDR       : in     vl_logic_vector;
        BVALID_DDR      : in     vl_logic;
        BREADY_2_DDR    : out    vl_logic;
        AWID_2_APB0     : out    vl_logic_vector;
        AWADDR_2_APB0   : out    vl_logic_vector;
        AWLEN_2_APB0    : out    vl_logic_vector;
        AWSIZE_2_APB0   : out    vl_logic_vector;
        AWBURST_2_APB0  : out    vl_logic_vector;
        AWVALID_2_APB0  : out    vl_logic;
        AWREADY_APB0    : in     vl_logic;
        WID_2_APB0      : out    vl_logic_vector;
        WDATA_2_APB0    : out    vl_logic_vector;
        WLAST_2_APB0    : out    vl_logic;
        WVALID_2_APB0   : out    vl_logic;
        WREADY_APB0     : in     vl_logic;
        BID_APB0        : in     vl_logic_vector;
        BRESP_APB0      : in     vl_logic_vector;
        BVALID_APB0     : in     vl_logic;
        BREADY_2_APB0   : out    vl_logic;
        AWID_2_APB1     : out    vl_logic_vector;
        AWADDR_2_APB1   : out    vl_logic_vector;
        AWLEN_2_APB1    : out    vl_logic_vector;
        AWSIZE_2_APB1   : out    vl_logic_vector;
        AWBURST_2_APB1  : out    vl_logic_vector;
        AWVALID_2_APB1  : out    vl_logic;
        AWREADY_APB1    : in     vl_logic;
        WID_2_APB1      : out    vl_logic_vector;
        WDATA_2_APB1    : out    vl_logic_vector;
        WLAST_2_APB1    : out    vl_logic;
        WVALID_2_APB1   : out    vl_logic;
        WREADY_APB1     : in     vl_logic;
        BID_APB1        : in     vl_logic_vector;
        BRESP_APB1      : in     vl_logic_vector;
        BVALID_APB1     : in     vl_logic;
        BREADY_2_APB1   : out    vl_logic;
        AWID_2_SMC      : out    vl_logic_vector;
        AWADDR_2_SMC    : out    vl_logic_vector;
        AWLEN_2_SMC     : out    vl_logic_vector;
        AWSIZE_2_SMC    : out    vl_logic_vector;
        AWBURST_2_SMC   : out    vl_logic_vector;
        AWVALID_2_SMC   : out    vl_logic;
        AWREADY_SMC     : in     vl_logic;
        WID_2_SMC       : out    vl_logic_vector;
        WDATA_2_SMC     : out    vl_logic_vector;
        WSTRB_2_SMC     : out    vl_logic_vector;
        WLAST_2_SMC     : out    vl_logic;
        WVALID_2_SMC    : out    vl_logic;
        WREADY_SMC      : in     vl_logic;
        BID_SMC         : in     vl_logic_vector;
        BRESP_SMC       : in     vl_logic_vector;
        BVALID_SMC      : in     vl_logic;
        BREADY_2_SMC    : out    vl_logic;
        AWID_2_SSRAM    : out    vl_logic_vector;
        AWADDR_2_SSRAM  : out    vl_logic_vector;
        AWLEN_2_SSRAM   : out    vl_logic_vector;
        AWSIZE_2_SSRAM  : out    vl_logic_vector;
        AWBURST_2_SSRAM : out    vl_logic_vector;
        AWVALID_2_SSRAM : out    vl_logic;
        AWREADY_SSRAM   : in     vl_logic;
        WID_2_SSRAM     : out    vl_logic_vector;
        WDATA_2_SSRAM   : out    vl_logic_vector;
        WSTRB_2_SSRAM   : out    vl_logic_vector;
        WLAST_2_SSRAM   : out    vl_logic;
        WVALID_2_SSRAM  : out    vl_logic;
        WREADY_SSRAM    : in     vl_logic;
        BID_SSRAM       : in     vl_logic_vector;
        BRESP_SSRAM     : in     vl_logic_vector;
        BVALID_SSRAM    : in     vl_logic;
        BREADY_2_SSRAM  : out    vl_logic;
        ARADDR_ARMD     : in     vl_logic_vector;
        ARLEN_ARMD      : in     vl_logic_vector;
        ARSIZE_ARMD     : in     vl_logic_vector;
        ARBURST_ARMD    : in     vl_logic_vector;
        ARLOCK_ARMD     : in     vl_logic_vector;
        ARVALID_ARMD    : in     vl_logic;
        ARREADY_2_ARMD  : out    vl_logic;
        RRESP_2_ARMD    : out    vl_logic_vector;
        RDATA_2_ARMD    : out    vl_logic_vector;
        RLAST_2_ARMD    : out    vl_logic;
        RVALID_2_ARMD   : out    vl_logic;
        RREADY_ARMD     : in     vl_logic;
        ARADDR_ARMI     : in     vl_logic_vector;
        ARLEN_ARMI      : in     vl_logic_vector;
        ARSIZE_ARMI     : in     vl_logic_vector;
        ARBURST_ARMI    : in     vl_logic_vector;
        ARLOCK_ARMI     : in     vl_logic_vector;
        ARVALID_ARMI    : in     vl_logic;
        ARREADY_2_ARMI  : out    vl_logic;
        RRESP_2_ARMI    : out    vl_logic_vector;
        RDATA_2_ARMI    : out    vl_logic_vector;
        RLAST_2_ARMI    : out    vl_logic;
        RVALID_2_ARMI   : out    vl_logic;
        RREADY_ARMI     : in     vl_logic;
        ARID_DMAC       : in     vl_logic_vector;
        ARADDR_DMAC     : in     vl_logic_vector;
        ARLEN_DMAC      : in     vl_logic_vector;
        ARSIZE_DMAC     : in     vl_logic_vector;
        ARBURST_DMAC    : in     vl_logic_vector;
        ARVALID_DMAC    : in     vl_logic;
        ARREADY_2_DMAC  : out    vl_logic;
        RID_2_DMAC      : out    vl_logic_vector;
        RRESP_2_DMAC    : out    vl_logic_vector;
        RDATA_2_DMAC    : out    vl_logic_vector;
        RLAST_2_DMAC    : out    vl_logic;
        RVALID_2_DMAC   : out    vl_logic;
        RREADY_DMAC     : in     vl_logic;
        ARADDR_MAC      : in     vl_logic_vector;
        ARLEN_MAC       : in     vl_logic_vector;
        ARSIZE_MAC      : in     vl_logic_vector;
        ARBURST_MAC     : in     vl_logic_vector;
        ARVALID_MAC     : in     vl_logic;
        ARREADY_2_MAC   : out    vl_logic;
        RRESP_2_MAC     : out    vl_logic_vector;
        RDATA_2_MAC     : out    vl_logic_vector;
        RLAST_2_MAC     : out    vl_logic;
        RVALID_2_MAC    : out    vl_logic;
        RREADY_MAC      : in     vl_logic;
        ARADDR_PCI      : in     vl_logic_vector;
        ARLEN_PCI       : in     vl_logic_vector;
        ARSIZE_PCI      : in     vl_logic_vector;
        ARBURST_PCI     : in     vl_logic_vector;
        ARVALID_PCI     : in     vl_logic;
        ARREADY_2_PCI   : out    vl_logic;
        RRESP_2_PCI     : out    vl_logic_vector;
        RDATA_2_PCI     : out    vl_logic_vector;
        RLAST_2_PCI     : out    vl_logic;
        RVALID_2_PCI    : out    vl_logic;
        RREADY_PCI      : in     vl_logic;
        ARID_2_AHB0     : out    vl_logic_vector;
        ARADDR_2_AHB0   : out    vl_logic_vector;
        ARLEN_2_AHB0    : out    vl_logic_vector;
        ARSIZE_2_AHB0   : out    vl_logic_vector;
        ARBURST_2_AHB0  : out    vl_logic_vector;
        ARVALID_2_AHB0  : out    vl_logic;
        ARREADY_AHB0    : in     vl_logic;
        RID_AHB0        : in     vl_logic_vector;
        RRESP_AHB0      : in     vl_logic_vector;
        RDATA_AHB0      : in     vl_logic_vector;
        RLAST_AHB0      : in     vl_logic;
        RVALID_AHB0     : in     vl_logic;
        RREADY_2_AHB0   : out    vl_logic;
        ARID_2_AHB1     : out    vl_logic_vector;
        ARADDR_2_AHB1   : out    vl_logic_vector;
        ARLEN_2_AHB1    : out    vl_logic_vector;
        ARSIZE_2_AHB1   : out    vl_logic_vector;
        ARBURST_2_AHB1  : out    vl_logic_vector;
        ARVALID_2_AHB1  : out    vl_logic;
        ARREADY_AHB1    : in     vl_logic;
        RID_AHB1        : in     vl_logic_vector;
        RRESP_AHB1      : in     vl_logic_vector;
        RDATA_AHB1      : in     vl_logic_vector;
        RLAST_AHB1      : in     vl_logic;
        RVALID_AHB1     : in     vl_logic;
        RREADY_2_AHB1   : out    vl_logic;
        ARID_2_DDR      : out    vl_logic_vector;
        ARADDR_2_DDR    : out    vl_logic_vector;
        ARLEN_2_DDR     : out    vl_logic_vector;
        ARSIZE_2_DDR    : out    vl_logic_vector;
        ARBURST_2_DDR   : out    vl_logic_vector;
        ARVALID_2_DDR   : out    vl_logic;
        ARREADY_DDR     : in     vl_logic;
        RID_DDR         : in     vl_logic_vector;
        RRESP_DDR       : in     vl_logic_vector;
        RDATA_DDR       : in     vl_logic_vector;
        RLAST_DDR       : in     vl_logic;
        RVALID_DDR      : in     vl_logic;
        RREADY_2_DDR    : out    vl_logic;
        ARID_2_APB0     : out    vl_logic_vector;
        ARADDR_2_APB0   : out    vl_logic_vector;
        ARLEN_2_APB0    : out    vl_logic_vector;
        ARSIZE_2_APB0   : out    vl_logic_vector;
        ARBURST_2_APB0  : out    vl_logic_vector;
        ARVALID_2_APB0  : out    vl_logic;
        ARREADY_APB0    : in     vl_logic;
        RID_APB0        : in     vl_logic_vector;
        RRESP_APB0      : in     vl_logic_vector;
        RDATA_APB0      : in     vl_logic_vector;
        RLAST_APB0      : in     vl_logic;
        RVALID_APB0     : in     vl_logic;
        RREADY_2_APB0   : out    vl_logic;
        ARID_2_APB1     : out    vl_logic_vector;
        ARADDR_2_APB1   : out    vl_logic_vector;
        ARLEN_2_APB1    : out    vl_logic_vector;
        ARSIZE_2_APB1   : out    vl_logic_vector;
        ARBURST_2_APB1  : out    vl_logic_vector;
        ARVALID_2_APB1  : out    vl_logic;
        ARREADY_APB1    : in     vl_logic;
        RID_APB1        : in     vl_logic_vector;
        RRESP_APB1      : in     vl_logic_vector;
        RDATA_APB1      : in     vl_logic_vector;
        RLAST_APB1      : in     vl_logic;
        RVALID_APB1     : in     vl_logic;
        RREADY_2_APB1   : out    vl_logic;
        ARID_2_SMC      : out    vl_logic_vector;
        ARADDR_2_SMC    : out    vl_logic_vector;
        ARLEN_2_SMC     : out    vl_logic_vector;
        ARSIZE_2_SMC    : out    vl_logic_vector;
        ARBURST_2_SMC   : out    vl_logic_vector;
        ARVALID_2_SMC   : out    vl_logic;
        ARREADY_SMC     : in     vl_logic;
        RID_SMC         : in     vl_logic_vector;
        RRESP_SMC       : in     vl_logic_vector;
        RDATA_SMC       : in     vl_logic_vector;
        RLAST_SMC       : in     vl_logic;
        RVALID_SMC      : in     vl_logic;
        RREADY_2_SMC    : out    vl_logic;
        ARID_2_SSRAM    : out    vl_logic_vector;
        ARADDR_2_SSRAM  : out    vl_logic_vector;
        ARLEN_2_SSRAM   : out    vl_logic_vector;
        ARSIZE_2_SSRAM  : out    vl_logic_vector;
        ARBURST_2_SSRAM : out    vl_logic_vector;
        ARVALID_2_SSRAM : out    vl_logic;
        ARREADY_SSRAM   : in     vl_logic;
        RID_SSRAM       : in     vl_logic_vector;
        RRESP_SSRAM     : in     vl_logic_vector;
        RDATA_SSRAM     : in     vl_logic_vector;
        RLAST_SSRAM     : in     vl_logic;
        RVALID_SSRAM    : in     vl_logic;
        RREADY_2_SSRAM  : out    vl_logic;
        ACLK            : in     vl_logic;
        ARESETn         : in     vl_logic;
        SelMAP1         : in     vl_logic
    );
end SBUS;
