#-----------------------------------------------------------------------
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2002 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#-----------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.1
#-
#- Release Information    : PrimeCell(TM)-PL110-r1p2-00ltd0
#-
#-----------------------------------------------------------------------
#-  Purpose  : 
#-             Standard Verilog Library Makefile
#-----------------------------------------------------------------------

MODULES = \
           ClcdDefine.v \
           ClcdConfig.v \
           ClcdFifoReg.v \
           dpram128x32.v \
            pram128x32.v \
           tpram64x32.v \
           ClcdDmaFRegWrap.v \
           ClcdDmaFRamWrap.v \
           ClcdFifoCntl.v \
           ClcdDMAFifo.v \
           ClcdAhbSlaveIf.v \
           ClcdAhbMasterIf.v \
           ClcdAhbIf.v \
           ClcdSyncCLCDCLK.v \
           ClcdSyncHCLK.v \
           ClcdUnpack.v \
           ClcdPalette.v \
           ClcdSerialiser.v \
           ClcdCPGen.v \
           ClcdFormat.v \
           ClcdGS.v \
           ClcdTiming.v \
           ClcdMain.v \
           ClcdOutMux.v \
           ClcdTest.v \
           ClcdCntl.v \
           ClcdRevAnd.v \
           Clcd.v

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

################################ End ###################################
