library verilog;
use verilog.vl_types.all;
entity VideoEncoderTester is
    generic(
        DATA_WIDTH      : integer := 32;
        WID_WIDTH       : integer := 4;
        RID_WIDTH       : integer := 4;
        ADDR_WIDTH      : integer := 32;
        START_ADDR_ALL  : integer := 0;
        IDLE            : integer := 0;
        ARREQ           : integer := 1;
        RECEIVE         : integer := 1
    );
    port(
        ACLK            : in     vl_logic;
        CLK_27MHZ       : in     vl_logic;
        ARESETn         : in     vl_logic;
        ARADDR          : out    vl_logic_vector;
        ARLEN           : out    vl_logic_vector(3 downto 0);
        ARSIZE          : out    vl_logic_vector(2 downto 0);
        ARBURST         : out    vl_logic_vector(1 downto 0);
        ARVALID         : out    vl_logic;
        ARREADY         : in     vl_logic;
        RDATA           : in     vl_logic_vector;
        RRESP           : in     vl_logic_vector(1 downto 0);
        RLAST           : in     vl_logic;
        RVALID          : in     vl_logic;
        RREADY          : out    vl_logic;
        DMA_REQ         : out    vl_logic;
        PENABLE         : in     vl_logic;
        PSEL            : in     vl_logic;
        PWRITE          : in     vl_logic;
        PADDR           : in     vl_logic_vector(3 downto 2);
        PWDATA          : in     vl_logic_vector(31 downto 0);
        PRDATA          : out    vl_logic_vector(31 downto 0);
        MEMADDR00       : out    vl_logic_vector(4 downto 0);
        MEMADDR01       : out    vl_logic_vector(4 downto 0);
        MEMWEn00        : out    vl_logic;
        MEMWEn01        : out    vl_logic;
        MEMRDATA00      : in     vl_logic_vector(31 downto 0);
        MEMRDATA01      : in     vl_logic_vector(31 downto 0);
        MEMWDATA00      : out    vl_logic_vector(31 downto 0);
        MEMWDATA01      : out    vl_logic_vector(31 downto 0);
        MEMADDR10       : out    vl_logic_vector(4 downto 0);
        MEMADDR11       : out    vl_logic_vector(4 downto 0);
        MEMWEn10        : out    vl_logic;
        MEMWEn11        : out    vl_logic;
        MEMRDATA10      : in     vl_logic_vector(31 downto 0);
        MEMRDATA11      : in     vl_logic_vector(31 downto 0);
        MEMWDATA10      : out    vl_logic_vector(31 downto 0);
        MEMWDATA11      : out    vl_logic_vector(31 downto 0);
        MEMADDR20       : out    vl_logic_vector(4 downto 0);
        MEMADDR21       : out    vl_logic_vector(4 downto 0);
        MEMWEn20        : out    vl_logic;
        MEMWEn21        : out    vl_logic;
        MEMRDATA20      : in     vl_logic_vector(31 downto 0);
        MEMRDATA21      : in     vl_logic_vector(31 downto 0);
        MEMWDATA20      : out    vl_logic_vector(31 downto 0);
        MEMWDATA21      : out    vl_logic_vector(31 downto 0);
        MEMADDR30       : out    vl_logic_vector(4 downto 0);
        MEMADDR31       : out    vl_logic_vector(4 downto 0);
        MEMWEn30        : out    vl_logic;
        MEMWEn31        : out    vl_logic;
        MEMRDATA30      : in     vl_logic_vector(31 downto 0);
        MEMRDATA31      : in     vl_logic_vector(31 downto 0);
        MEMWDATA30      : out    vl_logic_vector(31 downto 0);
        MEMWDATA31      : out    vl_logic_vector(31 downto 0);
        ADC_OUT         : out    vl_logic_vector(7 downto 0);
        SYNC            : out    vl_logic;
        BLANK           : out    vl_logic
    );
end VideoEncoderTester;
