;- --=================================================================--
;- This confidential and proprietary software may be used only as
;- authorised by a licensing agreement from ARM Limited
;-   (C) COPYRIGHT 2003 ARM Limited
;-       ALL RIGHTS RESERVED
;- The entire notice above must be reproduced on all authorised
;- copies and copies may only be made to the extent permitted
;- by a licensing agreement from ARM Limited.
;-
;- ---------------------------------------------------------------------
;- Version and Release Control Information:
;-
;- File Name              : modelsim_bustalk.ini.rca
;- File Revision          : 1.2
;-
;- Release Information    : PrimeCell(TM)-PL093-r0p3-00rel0
;-
;- ---------------------------------------------------------------------
;- Purpose : 
;-           Modelsim setup file for BusTalk directories
;- --=================================================================--

[Library]

; testbench
tbench     = ../tbench/work
common     = ../tbench/work
reader     = ../tbench/work
buswatcher = ../tbench/work
bid        = ../tbench/work
vr         = ../tbench/work
uut        = ../uut/work
trickbox   = ../trickbox/work

others = $GLOBAL/modelsim/libmap

[vsim]
; Load Denali
Veriuser = $DENALI/mtipli.so

; Default run length
RunLength = 100

; Iterations that can be run without advancing simulation time
IterationLimit = 5000

; Simulator resolution
Resolution = ps

; Stop the simulator after an assertion message
; 0 = Note  1 = Warning  2 = Error  3 = Failure  4 = Fatal
BreakOnAssertion = 3

; Default radix for all windows and commands...
; 0 = symbolic, 2 = binary, 8 = octal, 10 = decimal, 16 = hex
DefaultRadix = 16

; List Translation
; Map an enumerated value to 0, 1, or Z.  Default is 'X';
List0 = '0' FALSE 'L'
List1 = '1' TRUE 'H'
ListZ = 'Z'

; Force Translation
; Map 1s and 0s to the enumerated value
Force0 = '0' FALSE
Force1 = '1' TRUE

; VSIM Startup command
; Startup = do startup.do

; Save the command window contents to this file
TranscriptFile = transcript

; Disable assertion messages
; ignoreNote = 1
; ignoreWarning = 1
; ignoreError = 1
; ignoreFailure = 1

; window positions
main_window_pos = 1 1 528 264
structure_window_pos = 265 1 257 434
signal_window_pos = 265 258 272 327
process_window_pos = 699 1 257 198
variable_window_pos = 592 258 272 305
source_window_pos = 1 529 622 305
list_window_pos = 673 529 622 224
wave_window_pos = 306 529 622 367

; List of object libraries to search for C interface
ForeignLibs = /usr/lib/libc.a

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; End ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
