library verilog;
use verilog.vl_types.all;
entity mmc_fifo is
    port(
        mresetn         : in     vl_logic;
        hclk            : in     vl_logic;
        mclk            : in     vl_logic;
        hsel            : in     vl_logic;
        haddr           : in     vl_logic_vector(31 downto 0);
        htrans          : in     vl_logic_vector(1 downto 0);
        hsize           : in     vl_logic_vector(2 downto 0);
        hwrite          : in     vl_logic;
        hready          : in     vl_logic;
        hwdata          : in     vl_logic_vector(31 downto 0);
        hrdata          : out    vl_logic_vector(31 downto 0);
        hresp           : out    vl_logic_vector(1 downto 0);
        hreadyout       : out    vl_logic;
        hrstb1          : in     vl_logic;
        hwstb1          : in     vl_logic;
        hdin1           : in     vl_logic_vector(7 downto 0);
        hdout1          : out    vl_logic_vector(7 downto 0);
        hrstb2          : in     vl_logic;
        hwstb2          : in     vl_logic;
        hssize2         : in     vl_logic_vector(2 downto 0);
        hdin2           : in     vl_logic_vector(31 downto 0);
        hdout2          : out    vl_logic_vector(31 downto 0);
        hstore_write    : out    vl_logic_vector(5 downto 0);
        hstore_read     : out    vl_logic_vector(5 downto 0);
        fifo_clear      : in     vl_logic;
        mfifo_clear     : in     vl_logic;
        mwstb_4word     : in     vl_logic;
        mwstb_16word    : in     vl_logic;
        mwstb_128word   : in     vl_logic;
        wr_word_count   : in     vl_logic_vector(7 downto 0);
        wr_4word_count  : in     vl_logic_vector(7 downto 0);
        wr_16word_count : in     vl_logic_vector(7 downto 0);
        wr_128word_count: in     vl_logic_vector(7 downto 0);
        mstatus         : in     vl_logic_vector(31 downto 0);
        mcrc16_ok       : in     vl_logic;
        single_write_command: in     vl_logic;
        multi_write_command: in     vl_logic;
        single_read_command: in     vl_logic;
        multi_read_command: in     vl_logic;
        rd_eou          : in     vl_logic;
        mrden           : in     vl_logic;
        start_block     : in     vl_logic_vector(22 downto 0);
        multi_write_block: in     vl_logic_vector(31 downto 0);
        multi_read_block: in     vl_logic_vector(31 downto 0);
        mrstb_4word     : in     vl_logic;
        mrstb_16word    : in     vl_logic;
        mrstb_128word   : in     vl_logic;
        rd_word_count   : in     vl_logic_vector(7 downto 0);
        rd_4word_count  : in     vl_logic_vector(7 downto 0);
        rd_16word_count : in     vl_logic_vector(7 downto 0);
        rd_128word_count: in     vl_logic_vector(7 downto 0);
        mrstb           : in     vl_logic;
        mrstb_3d        : in     vl_logic;
        mrstb_4d        : in     vl_logic;
        mwrfield        : in     vl_logic_vector(3 downto 0);
        mcmdindex       : in     vl_logic_vector(5 downto 0);
        busy_clear      : in     vl_logic;
        wr_count        : in     vl_logic_vector(15 downto 0);
        mcmdfield       : in     vl_logic_vector(3 downto 0);
        set_pwd         : out    vl_logic;
        lock_unlock_mode: out    vl_logic_vector(7 downto 0);
        pwd_match       : out    vl_logic;
        pwd_len_match   : out    vl_logic;
        pwd_stb         : out    vl_logic;
        clr_pwd         : out    vl_logic;
        card_is_locked  : in     vl_logic;
        wr_block_buffer_4word: out    vl_logic_vector(127 downto 0);
        mcsd            : in     vl_logic_vector(127 downto 0);
        csd_update      : out    vl_logic_vector(127 downto 0);
        mext_csd        : in     vl_logic_vector(191 downto 0);
        bus1            : in     vl_logic;
        bus4            : in     vl_logic;
        bus8            : in     vl_logic;
        hstore_write_edge: in     vl_logic_vector(5 downto 0);
        hstore_read_edge: in     vl_logic_vector(5 downto 0);
        hirq            : out    vl_logic
    );
end mmc_fifo;
