library verilog;
use verilog.vl_types.all;
entity readchannelsi_rs is
    generic(
        bus_wid         : integer := 32;
        addr_wid        : integer := 32;
        id_wid          : integer := 4;
        awlen_wid       : integer := 4;
        awsize_wid      : integer := 3;
        awburst_wid     : integer := 2;
        awlock_wid      : integer := 2;
        awcache_wid     : integer := 4;
        awprot_wid      : integer := 3;
        wstrb_wid       : integer := 4;
        bresp_wid       : integer := 2;
        rresp_wid       : integer := 2;
        arlen_wid       : integer := 4;
        arsize_wid      : integer := 3;
        arburst_wid     : integer := 2;
        arlock_wid      : integer := 2;
        arcache_wid     : integer := 4;
        arprot_wid      : integer := 3;
        master_wid      : integer := 4;
        slave_wid       : integer := 3;
        slave_num       : integer := 6;
        master_num      : integer := 4;
        slavecntwid     : integer := 5;
        reqdepth_wid    : integer := 2
    );
    port(
        aclk            : in     vl_logic;
        aresetn         : in     vl_logic;
        aridm2si        : in     vl_logic_vector;
        araddrm2si      : in     vl_logic_vector;
        arlenm2si       : in     vl_logic_vector;
        arsizem2si      : in     vl_logic_vector;
        arburstm2si     : in     vl_logic_vector;
        arlockm2si      : in     vl_logic_vector;
        arcachem2si     : in     vl_logic_vector;
        arprotm2si      : in     vl_logic_vector;
        arvalidm2si     : in     vl_logic;
        arreadysi2m     : out    vl_logic;
        ridsi2m         : out    vl_logic_vector;
        rrespsi2m       : out    vl_logic_vector;
        rvalidsi2m      : out    vl_logic;
        rdatasi2m       : out    vl_logic_vector;
        rreadym2si      : in     vl_logic;
        rlastsi2m       : out    vl_logic;
        aridsi2mi       : out    vl_logic_vector;
        araddrsi2mi     : out    vl_logic_vector;
        arlensi2mi      : out    vl_logic_vector;
        arsizesi2mi     : out    vl_logic_vector;
        arburstsi2mi    : out    vl_logic_vector;
        arlocksi2mi     : out    vl_logic_vector;
        arcachesi2mi    : out    vl_logic_vector;
        arprotsi2mi     : out    vl_logic_vector;
        arvalidsi2mi    : out    vl_logic_vector;
        arreadymi2si    : in     vl_logic_vector;
        ridmi02si       : in     vl_logic_vector;
        rrespmi02si     : in     vl_logic_vector;
        rdatami02si     : in     vl_logic_vector;
        ridmi12si       : in     vl_logic_vector;
        rrespmi12si     : in     vl_logic_vector;
        rdatami12si     : in     vl_logic_vector;
        ridmi22si       : in     vl_logic_vector;
        rrespmi22si     : in     vl_logic_vector;
        rdatami22si     : in     vl_logic_vector;
        ridmi32si       : in     vl_logic_vector;
        rrespmi32si     : in     vl_logic_vector;
        rdatami32si     : in     vl_logic_vector;
        ridmi42si       : in     vl_logic_vector;
        rrespmi42si     : in     vl_logic_vector;
        rdatami42si     : in     vl_logic_vector;
        ridmi52si       : in     vl_logic_vector;
        rrespmi52si     : in     vl_logic_vector;
        rdatami52si     : in     vl_logic_vector;
        rvalidmi2si     : in     vl_logic_vector;
        rreadysi2mi     : out    vl_logic_vector;
        rlastmi2si      : in     vl_logic_vector
    );
end readchannelsi_rs;
