library verilog;
use verilog.vl_types.all;
entity s3_writechannelmi is
    generic(
        bus_wid         : integer := 32;
        addr_wid        : integer := 32;
        masterid_wid    : integer := 4;
        slaveid_wid     : integer := 6;
        awlen_wid       : integer := 4;
        awsize_wid      : integer := 3;
        awburst_wid     : integer := 2;
        awlock_wid      : integer := 2;
        awcache_wid     : integer := 4;
        awprot_wid      : integer := 3;
        wstrb_wid       : integer := 4;
        bresp_wid       : integer := 2;
        rresp_wid       : integer := 2;
        arlen_wid       : integer := 4;
        arburst_wid     : integer := 2;
        arlock_wid      : integer := 2;
        arcache_wid     : integer := 4;
        arprot_wid      : integer := 3;
        master_wid      : integer := 3;
        slave_wid       : integer := 3;
        slave_num       : integer := 6;
        master_num      : integer := 4;
        selmaster_wid   : integer := 2;
        wr_reqdepth_wid : integer := 4;
        rd_reqdepth_wid : integer := 4;
        wrpermit_slavecntwid: integer := 3;
        rdpermit_slavecntwid: integer := 3;
        arsize_wid      : integer := 3
    );
    port(
        aclk            : in     vl_logic;
        aresetn         : in     vl_logic;
        awidmi2s        : out    vl_logic_vector;
        awaddrmi2s      : out    vl_logic_vector;
        awlenmi2s       : out    vl_logic_vector;
        awsizemi2s      : out    vl_logic_vector;
        awburstmi2s     : out    vl_logic_vector;
        awlockmi2s      : out    vl_logic_vector;
        awcachemi2s     : out    vl_logic_vector;
        awprotmi2s      : out    vl_logic_vector;
        awvalidmi2s     : out    vl_logic;
        awreadys2mi     : in     vl_logic;
        widmi2s         : out    vl_logic_vector;
        wdatami2s       : out    vl_logic_vector;
        wstrbmi2s       : out    vl_logic_vector;
        wlastmi2s       : out    vl_logic;
        wvalidmi2s      : out    vl_logic;
        wreadys2mi      : in     vl_logic;
        bids2mi         : in     vl_logic_vector;
        bresps2mi       : in     vl_logic_vector;
        bvalids2mi      : in     vl_logic;
        breadymi2s      : out    vl_logic;
        awidsi02mi      : in     vl_logic_vector;
        awaddrsi02mi    : in     vl_logic_vector;
        awlensi02mi     : in     vl_logic_vector;
        awsizesi02mi    : in     vl_logic_vector;
        awburstsi02mi   : in     vl_logic_vector;
        awlocksi02mi    : in     vl_logic_vector;
        awcachesi02mi   : in     vl_logic_vector;
        awprotsi02mi    : in     vl_logic_vector;
        widsi02mi       : in     vl_logic_vector;
        wdatasi02mi     : in     vl_logic_vector;
        wstrbsi02mi     : in     vl_logic_vector;
        awidsi12mi      : in     vl_logic_vector;
        awaddrsi12mi    : in     vl_logic_vector;
        awlensi12mi     : in     vl_logic_vector;
        awsizesi12mi    : in     vl_logic_vector;
        awburstsi12mi   : in     vl_logic_vector;
        awlocksi12mi    : in     vl_logic_vector;
        awcachesi12mi   : in     vl_logic_vector;
        awprotsi12mi    : in     vl_logic_vector;
        widsi12mi       : in     vl_logic_vector;
        wdatasi12mi     : in     vl_logic_vector;
        wstrbsi12mi     : in     vl_logic_vector;
        awidsi22mi      : in     vl_logic_vector;
        awaddrsi22mi    : in     vl_logic_vector;
        awlensi22mi     : in     vl_logic_vector;
        awsizesi22mi    : in     vl_logic_vector;
        awburstsi22mi   : in     vl_logic_vector;
        awlocksi22mi    : in     vl_logic_vector;
        awcachesi22mi   : in     vl_logic_vector;
        awprotsi22mi    : in     vl_logic_vector;
        widsi22mi       : in     vl_logic_vector;
        wdatasi22mi     : in     vl_logic_vector;
        wstrbsi22mi     : in     vl_logic_vector;
        awidsi32mi      : in     vl_logic_vector;
        awaddrsi32mi    : in     vl_logic_vector;
        awlensi32mi     : in     vl_logic_vector;
        awsizesi32mi    : in     vl_logic_vector;
        awburstsi32mi   : in     vl_logic_vector;
        awlocksi32mi    : in     vl_logic_vector;
        awcachesi32mi   : in     vl_logic_vector;
        awprotsi32mi    : in     vl_logic_vector;
        widsi32mi       : in     vl_logic_vector;
        wdatasi32mi     : in     vl_logic_vector;
        wstrbsi32mi     : in     vl_logic_vector;
        bidmi2si0       : out    vl_logic_vector;
        brespmi2si0     : out    vl_logic_vector;
        bidmi2si1       : out    vl_logic_vector;
        brespmi2si1     : out    vl_logic_vector;
        bidmi2si2       : out    vl_logic_vector;
        brespmi2si2     : out    vl_logic_vector;
        bidmi2si3       : out    vl_logic_vector;
        brespmi2si3     : out    vl_logic_vector;
        bvalidmi2si     : out    vl_logic_vector;
        breadysi2mi     : in     vl_logic_vector;
        lock2wrmi       : in     vl_logic;
        unlock2wrmi     : in     vl_logic;
        lock2rdmi       : out    vl_logic;
        unlock2rdmi     : out    vl_logic;
        arvalid         : in     vl_logic;
        lockport        : in     vl_logic_vector;
        readintemptywrmi2rdmi: out    vl_logic;
        datacntemptyrdmi2wrmi: in     vl_logic;
        ctldatawrite2lock: out    vl_logic_vector;
        awvalidsi2mi    : in     vl_logic_vector;
        awreadymi2si    : out    vl_logic_vector;
        wlastsi2mi      : in     vl_logic_vector;
        wvalidsi2mi     : in     vl_logic_vector;
        wreadymi2si     : out    vl_logic_vector
    );
end s3_writechannelmi;
