library verilog;
use verilog.vl_types.all;
entity pci_mtfsm64 is
    generic(
        oe_active       : integer := 0;
        vendor_id       : integer := 43981;
        device_id       : integer := 25702;
        class_id        : integer := 425984;
        rev_id          : integer := 16;
        bar0_present    : integer := 1;
        bar0_dwidth     : integer := 22;
        bar1_present    : integer := 1;
        bar1_dwidth     : integer := 8;
        bar2_present    : integer := 0;
        bar2_map        : integer := 0;
        bar2_dwidth     : integer := 28;
        bar3_present    : integer := 0;
        bar3_map        : integer := 0;
        bar3_dwidth     : integer := 28;
        bar4_present    : integer := 0;
        bar4_map        : integer := 0;
        bar4_dwidth     : integer := 28;
        bar5_present    : integer := 0;
        bar5_map        : integer := 0;
        bar5_dwidth     : integer := 28;
        ebar_present    : integer := 0;
        ebar_map        : integer := 0;
        ebar_dwidth     : integer := 17;
        subvendor_id    : integer := 4334;
        subdevice_id    : integer := 256;
        cis_ptr         : integer := 0;
        cap_ptr         : integer := 0;
        max_lat         : integer := 32;
        min_gnt         : integer := 4;
        int_pin         : integer := 1;
        int_line        : integer := 0;
        command_init    : integer := 0;
        status_init     : integer := 544;
        clsize_init     : integer := 0;
        lattimer_init   : integer := 0;
        intline_init    : integer := 0;
        iack_code       : integer := 0;
        scyc_code       : integer := 1;
        iord_code       : integer := 2;
        iowr_code       : integer := 3;
        res4_code       : integer := 4;
        res5_code       : integer := 5;
        mrd_code        : integer := 6;
        mwr_code        : integer := 7;
        res8_code       : integer := 8;
        res9_code       : integer := 9;
        cfgrd_code      : integer := 10;
        cfgwr_code      : integer := 11;
        mrm_code        : integer := 12;
        dual_code       : integer := 13;
        mrl_code        : integer := 14;
        mwi_code        : integer := 15;
        m_park          : integer := 0;
        m_idle          : integer := 1;
        m_busreq        : integer := 2;
        m_cmd           : integer := 3;
        m_trdata        : integer := 4;
        m_turnar        : integer := 5;
        t_idle          : integer := 0;
        t_adrdec        : integer := 1;
        t_sdata         : integer := 2;
        t_turnar        : integer := 3
    );
    port(
        clk             : in     vl_logic;
        reset           : in     vl_logic;
        idselid         : in     vl_logic;
        frameni         : in     vl_logic;
        framenid        : in     vl_logic;
        irdyni          : in     vl_logic;
        irdynid         : in     vl_logic;
        devselni        : in     vl_logic;
        devselnid       : in     vl_logic;
        trdyni          : in     vl_logic;
        trdynid         : in     vl_logic;
        stopni          : in     vl_logic;
        stopnid         : in     vl_logic;
        gntni           : in     vl_logic;
        gntnid          : in     vl_logic;
        req64nid        : in     vl_logic;
        ack64ni         : in     vl_logic;
        target_act      : in     vl_logic;
        adi             : in     vl_logic_vector(63 downto 0);
        cbenid          : in     vl_logic_vector(7 downto 0);
        lat_timer       : in     vl_logic_vector(7 downto 0);
        cfg_ioen        : in     vl_logic;
        cfg_memen       : in     vl_logic;
        master_en       : in     vl_logic;
        hit             : in     vl_logic;
        cfg_drdy        : in     vl_logic;
        b_limit         : in     vl_logic;
        t_drdy          : in     vl_logic_vector(6 downto 0);
        t_term          : in     vl_logic;
        t_abort         : in     vl_logic;
        m_areq          : in     vl_logic;
        m_areq64        : in     vl_logic;
        m_crw           : in     vl_logic;
        m_drdy          : in     vl_logic;
        m_lastd         : in     vl_logic;
        reqno_nxt       : out    vl_logic;
        frameno_nxt     : out    vl_logic;
        ce_frame        : out    vl_logic;
        req64no_nxt     : out    vl_logic;
        ce_req64        : out    vl_logic;
        irdyno_nxt      : out    vl_logic;
        devselno_nxt    : out    vl_logic;
        ack64no_nxt     : out    vl_logic;
        trdyno_nxt      : out    vl_logic;
        stopno_nxt      : out    vl_logic;
        ot_frame_nxt    : out    vl_logic;
        ot_req64_nxt    : out    vl_logic;
        ot_irdy_nxt     : out    vl_logic;
        ot_devsel_nxt   : out    vl_logic;
        ot_ack64_nxt    : out    vl_logic;
        ot_trdy_nxt     : out    vl_logic;
        ot_stop_nxt     : out    vl_logic;
        acc_end         : out    vl_logic;
        ot_cbe_nxt      : out    vl_logic;
        new_ot_ad       : out    vl_logic_vector(4 downto 0);
        new_ot_ad64     : out    vl_logic_vector(3 downto 0);
        clr_adtff       : out    vl_logic;
        t_ce_adordyn    : out    vl_logic;
        m_ce_adordyn    : out    vl_logic;
        ce_adodir       : out    vl_logic;
        first_cyc       : out    vl_logic;
        acc_cfg         : out    vl_logic;
        acc_io          : out    vl_logic;
        acc_mem         : out    vl_logic;
        acc_wr          : out    vl_logic;
        acc_rd          : out    vl_logic;
        adr             : out    vl_logic_vector(31 downto 0);
        badr            : out    vl_logic_vector(31 downto 0);
        command         : out    vl_logic_vector(3 downto 0);
        cmd_cfgrd       : out    vl_logic;
        cmd_cfgwr       : out    vl_logic;
        adr_valid       : out    vl_logic;
        width64         : out    vl_logic;
        t_nextd         : out    vl_logic;
        t_we            : out    vl_logic;
        t_wr            : out    vl_logic;
        t_rd            : out    vl_logic;
        m_otcmd         : out    vl_logic;
        m_otdata        : out    vl_logic;
        m_wrejd         : out    vl_logic;
        m_nextd         : out    vl_logic;
        m_aack          : out    vl_logic;
        m_aack64        : out    vl_logic;
        mabort_sig      : out    vl_logic;
        tabort_det      : out    vl_logic;
        tretry_det      : out    vl_logic;
        tdisc_det       : out    vl_logic;
        master_act      : out    vl_logic
    );
end pci_mtfsm64;
