onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/ARESETn
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/AWID
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/AWBURST
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/WID
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/BID
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/BREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/ARID
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/ARBURST
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/RID
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/RREADY
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/SMC_READY
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/SMC_RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/SMC_ADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/SMC_WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/SMC_WBEB
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/SMC_WRITE
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/SMC_READ
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/SMC_BANK_SEL
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/SMC_SRAM_START
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/SMC_TRANS_SIZE
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/ReadOrWrite
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/State
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/NextState
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/StateIsIDLE
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/StateIsREAD
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/StateIsWRITE
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/StateIsWRITE_RESP
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/IsWritePending
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/MuxedAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/MuxedLen
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/MuxedSize
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/MuxedBurst
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/LatchCommandEn
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/Id
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/GeneratedAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/Len
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/BurstLen
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/Size
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/Burst
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/DecreaseLen
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/NextAddrCalcEn
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/IncreasedAddr
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/WrapBoundary
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/WaitingRREADY
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/ReadEnable
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/LatchedRDATA
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/WDATAAvailable
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/WriteEnable
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/LatchedWDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uAXI_interface/LatchedWBEB
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/CLK
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/RSTb
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/ADDR
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/WRITE
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/READ
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/WBEB
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/TRANS_SIZE
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/BANK_SEL
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/SRAM_START
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/ADDR_SETUP
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/ADDR_HOLD
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/CS_SETUP
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/CS_HOLD
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/ACC_CYCLE
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/BUS_WIDTH
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/ADDR_SHIFT
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/READY
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/EXT_ADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/EXT_WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/EXT_RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/EXT_CSb
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/EXT_WEb
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/EXT_OEb
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/EXT_BEb
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/EXT_WBEb
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/EXT_BIDEN
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/i_addr
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/i_wdata
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/ns
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/cs
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/timing_cnt
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/repeat_cnt
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/repeat_cnt_val
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/beb
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/pre_beb
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/r_beb
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/go_tas
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/go_tcss
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/go_tacc
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/go_tcsh
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/go_tah
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/go_cont
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/go_idle
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/go_next
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/cont_tas
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/cont_tcss
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/cont_tacc
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/timing_cnt_en
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/repeat_end
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/size8
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/size16
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/size32
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/width8
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/width16
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/width32
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/inc01
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/inc02
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/csb
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/uSRAM_CTRL/web
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/ARESETn
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/AWID
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/AWBURST
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/WID
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/BID
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/BREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/ARID
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/ARBURST
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/RID
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/RREADY
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/PCLK
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/PRESETn
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/PADDR
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/PSEL
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/PENABLE
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/PWRITE
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/PRDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/EXT_ADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/EXT_WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/EXT_RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/EXT_CSb
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/EXT_OEb
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/EXT_WEb
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/EXT_BEb
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/EXT_WBEb
add wave -noupdate -format Logic -radix hexadecimal /tb/uSMC_TOP/EXT_BIDEN
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/ADDR_SETUP
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/ADDR_HOLD
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/CS_SETUP
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/CS_HOLD
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/ACC_CYCLE
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/BUS_WIDTH
add wave -noupdate -format Literal -radix hexadecimal /tb/uSMC_TOP/ADDR_SHIFT
add wave -noupdate -divider {New Divider}
add wave -noupdate -format Logic -radix hexadecimal /tb/ACLK
add wave -noupdate -format Logic -radix hexadecimal /tb/ARESETn
add wave -noupdate -format Literal -radix hexadecimal /tb/AWID
add wave -noupdate -format Literal -radix hexadecimal /tb/AWADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/AWLEN
add wave -noupdate -format Literal -radix hexadecimal /tb/AWSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb/AWBURST
add wave -noupdate -format Logic -radix hexadecimal /tb/AWVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/AWREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/WID
add wave -noupdate -format Literal -radix hexadecimal /tb/WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/WSTRB
add wave -noupdate -format Logic -radix hexadecimal /tb/WLAST
add wave -noupdate -format Logic -radix hexadecimal /tb/WVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/WREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/BID
add wave -noupdate -format Literal -radix hexadecimal /tb/BRESP
add wave -noupdate -format Logic -radix hexadecimal /tb/BVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/BREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/ARID
add wave -noupdate -format Literal -radix hexadecimal /tb/ARADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/ARLEN
add wave -noupdate -format Literal -radix hexadecimal /tb/ARSIZE
add wave -noupdate -format Literal -radix hexadecimal /tb/ARBURST
add wave -noupdate -format Logic -radix hexadecimal /tb/ARVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/ARREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/RID
add wave -noupdate -format Literal -radix hexadecimal /tb/RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/RRESP
add wave -noupdate -format Logic -radix hexadecimal /tb/RLAST
add wave -noupdate -format Logic -radix hexadecimal /tb/RVALID
add wave -noupdate -format Logic -radix hexadecimal /tb/RREADY
add wave -noupdate -format Literal -radix hexadecimal /tb/PADDR
add wave -noupdate -format Logic -radix hexadecimal /tb/PSEL
add wave -noupdate -format Logic -radix hexadecimal /tb/PENABLE
add wave -noupdate -format Logic -radix hexadecimal /tb/PWRITE
add wave -noupdate -format Literal -radix hexadecimal /tb/PWDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/PRDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/EXT_ADDR
add wave -noupdate -format Literal -radix hexadecimal /tb/EXT_WDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/EXT_RDATA
add wave -noupdate -format Literal -radix hexadecimal /tb/EXT_CSb
add wave -noupdate -format Logic -radix hexadecimal /tb/EXT_OEb
add wave -noupdate -format Logic -radix hexadecimal /tb/EXT_WEb
add wave -noupdate -format Literal -radix hexadecimal /tb/EXT_BEb
add wave -noupdate -format Literal -radix hexadecimal /tb/EXT_WBEb
add wave -noupdate -format Logic -radix hexadecimal /tb/EXT_BIDEN
add wave -noupdate -format Literal -radix hexadecimal /tb/sram_data_0
add wave -noupdate -format Literal -radix hexadecimal /tb/sram_data_1
add wave -noupdate -format Literal -radix hexadecimal /tb/sram_data_2
add wave -noupdate -format Literal -radix hexadecimal /tb/sram_data_3
add wave -noupdate -format Literal -radix hexadecimal /tb/sram_data_32
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1494830 ps} 0}
WaveRestoreZoom {14940850108 ps} {14942344938 ps}
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
