library verilog;
use verilog.vl_types.all;
entity ReadChannel is
    generic(
        BUS_WID         : integer := 32;
        ADDR_WID        : integer := 32;
        MASTERID_WID    : integer := 1;
        SLAVEID_WID     : integer := 2;
        AWLEN_WID       : integer := 4;
        AWSIZE_WID      : integer := 3;
        AWBURST_WID     : integer := 2;
        AWLOCK_WID      : integer := 2;
        AWCACHE_WID     : integer := 4;
        AWPROT_WID      : integer := 3;
        WSTRB_WID       : integer := 4;
        BRESP_WID       : integer := 2;
        RRESP_WID       : integer := 2;
        ARLEN_WID       : integer := 4;
        ARBURST_WID     : integer := 2;
        ARLOCK_WID      : integer := 2;
        ARCACHE_WID     : integer := 4;
        ARPROT_WID      : integer := 3;
        MASTER_WID      : integer := 3;
        SLAVE_WID       : integer := 4;
        SLAVE_NUM       : integer := 8;
        MASTER_NUM      : integer := 5;
        SELMASTER_WID   : integer := 3;
        Wr_REQDEPTH_WID : integer := 1;
        Rd_REQDEPTH_WID : integer := 1;
        WrPermit_SLAVECNTWID: integer := 1;
        RdPermit_SLAVECNTWID: integer := 1;
        ARSIZE_WID      : integer := 3;
        MASTERID0_WID   : integer := 1;
        MASTERID1_WID   : integer := 1;
        MASTERID2_WID   : integer := 1;
        MASTERID3_WID   : integer := 1;
        MASTERID4_WID   : integer := 1;
        MAXMASTERID_WID : integer := 1;
        BLANKMASTERID0_WID: integer := 0;
        BLANKMASTERID1_WID: integer := 0;
        BLANKMASTERID2_WID: integer := 0;
        BLANKMASTERID3_WID: integer := 0;
        BLANKMASTERID4_WID: integer := 0;
        SLAVEID0_WID    : integer := 2;
        SLAVEID1_WID    : integer := 2;
        SLAVEID2_WID    : integer := 4;
        SLAVEID3_WID    : integer := 2;
        SLAVEID4_WID    : integer := 2;
        SLAVEID5_WID    : integer := 4;
        SLAVEID6_WID    : integer := 4;
        SLAVEID7_WID    : integer := 4;
        SELMASTER0_WID  : integer := 1;
        SELMASTER1_WID  : integer := 1;
        SELMASTER2_WID  : integer := 3;
        SELMASTER3_WID  : integer := 1;
        SELMASTER4_WID  : integer := 1;
        SELMASTER5_WID  : integer := 3;
        SELMASTER6_WID  : integer := 3;
        SELMASTER7_WID  : integer := 3;
        SLAVE_MASTERID0_WID: integer := 1;
        SLAVE_MASTERID1_WID: integer := 1;
        SLAVE_MASTERID2_WID: integer := 1;
        SLAVE_MASTERID3_WID: integer := 1;
        SLAVE_MASTERID4_WID: integer := 1;
        SLAVE_MASTERID5_WID: integer := 1;
        SLAVE_MASTERID6_WID: integer := 1;
        SLAVE_MASTERID7_WID: integer := 1
    );
    port(
        SelMAP1         : in     vl_logic;
        ARADDRm02si0    : in     vl_logic_vector;
        ARLENm02si0     : in     vl_logic_vector;
        ARSIZEm02si0    : in     vl_logic_vector;
        ARBURSTm02si0   : in     vl_logic_vector;
        ARLOCKm02si0    : in     vl_logic_vector;
        ARVALIDm02si0   : in     vl_logic;
        ARREADYsi02m0   : out    vl_logic;
        RRESPsi02m0     : out    vl_logic_vector;
        RDATAsi02m0     : out    vl_logic_vector;
        RLASTsi02m0     : out    vl_logic;
        RVALIDsi02m0    : out    vl_logic;
        RREADYm02si0    : in     vl_logic;
        ARADDRm12si1    : in     vl_logic_vector;
        ARLENm12si1     : in     vl_logic_vector;
        ARSIZEm12si1    : in     vl_logic_vector;
        ARBURSTm12si1   : in     vl_logic_vector;
        ARLOCKm12si1    : in     vl_logic_vector;
        ARVALIDm12si1   : in     vl_logic;
        ARREADYsi12m1   : out    vl_logic;
        RRESPsi12m1     : out    vl_logic_vector;
        RDATAsi12m1     : out    vl_logic_vector;
        RLASTsi12m1     : out    vl_logic;
        RVALIDsi12m1    : out    vl_logic;
        RREADYm12si1    : in     vl_logic;
        ARIDm22si2      : in     vl_logic_vector;
        ARADDRm22si2    : in     vl_logic_vector;
        ARLENm22si2     : in     vl_logic_vector;
        ARSIZEm22si2    : in     vl_logic_vector;
        ARBURSTm22si2   : in     vl_logic_vector;
        ARVALIDm22si2   : in     vl_logic;
        ARREADYsi22m2   : out    vl_logic;
        RIDsi22m2       : out    vl_logic_vector;
        RRESPsi22m2     : out    vl_logic_vector;
        RDATAsi22m2     : out    vl_logic_vector;
        RLASTsi22m2     : out    vl_logic;
        RVALIDsi22m2    : out    vl_logic;
        RREADYm22si2    : in     vl_logic;
        ARADDRm32si3    : in     vl_logic_vector;
        ARLENm32si3     : in     vl_logic_vector;
        ARSIZEm32si3    : in     vl_logic_vector;
        ARBURSTm32si3   : in     vl_logic_vector;
        ARVALIDm32si3   : in     vl_logic;
        ARREADYsi32m3   : out    vl_logic;
        RRESPsi32m3     : out    vl_logic_vector;
        RDATAsi32m3     : out    vl_logic_vector;
        RLASTsi32m3     : out    vl_logic;
        RVALIDsi32m3    : out    vl_logic;
        RREADYm32si3    : in     vl_logic;
        ARADDRm42si4    : in     vl_logic_vector;
        ARLENm42si4     : in     vl_logic_vector;
        ARSIZEm42si4    : in     vl_logic_vector;
        ARBURSTm42si4   : in     vl_logic_vector;
        ARVALIDm42si4   : in     vl_logic;
        ARREADYsi42m4   : out    vl_logic;
        RRESPsi42m4     : out    vl_logic_vector;
        RDATAsi42m4     : out    vl_logic_vector;
        RLASTsi42m4     : out    vl_logic;
        RVALIDsi42m4    : out    vl_logic;
        RREADYm42si4    : in     vl_logic;
        ARIDmi02s0      : out    vl_logic_vector;
        ARADDRmi02s0    : out    vl_logic_vector;
        ARLENmi02s0     : out    vl_logic_vector;
        ARSIZEmi02s0    : out    vl_logic_vector;
        ARBURSTmi02s0   : out    vl_logic_vector;
        ARVALIDmi02s0   : out    vl_logic;
        ARREADYs02mi0   : in     vl_logic;
        RIDs02mi0       : in     vl_logic_vector;
        RRESPs02mi0     : in     vl_logic_vector;
        RDATAs02mi0     : in     vl_logic_vector;
        RLASTs02mi0     : in     vl_logic;
        RVALIDs02mi0    : in     vl_logic;
        RREADYmi02s0    : out    vl_logic;
        ARIDmi12s1      : out    vl_logic_vector;
        ARADDRmi12s1    : out    vl_logic_vector;
        ARLENmi12s1     : out    vl_logic_vector;
        ARSIZEmi12s1    : out    vl_logic_vector;
        ARBURSTmi12s1   : out    vl_logic_vector;
        ARVALIDmi12s1   : out    vl_logic;
        ARREADYs12mi1   : in     vl_logic;
        RIDs12mi1       : in     vl_logic_vector;
        RRESPs12mi1     : in     vl_logic_vector;
        RDATAs12mi1     : in     vl_logic_vector;
        RLASTs12mi1     : in     vl_logic;
        RVALIDs12mi1    : in     vl_logic;
        RREADYmi12s1    : out    vl_logic;
        ARIDmi22s2      : out    vl_logic_vector;
        ARADDRmi22s2    : out    vl_logic_vector;
        ARLENmi22s2     : out    vl_logic_vector;
        ARSIZEmi22s2    : out    vl_logic_vector;
        ARBURSTmi22s2   : out    vl_logic_vector;
        ARVALIDmi22s2   : out    vl_logic;
        ARREADYs22mi2   : in     vl_logic;
        RIDs22mi2       : in     vl_logic_vector;
        RRESPs22mi2     : in     vl_logic_vector;
        RDATAs22mi2     : in     vl_logic_vector;
        RLASTs22mi2     : in     vl_logic;
        RVALIDs22mi2    : in     vl_logic;
        RREADYmi22s2    : out    vl_logic;
        ARIDmi32s3      : out    vl_logic_vector;
        ARADDRmi32s3    : out    vl_logic_vector;
        ARLENmi32s3     : out    vl_logic_vector;
        ARSIZEmi32s3    : out    vl_logic_vector;
        ARBURSTmi32s3   : out    vl_logic_vector;
        ARVALIDmi32s3   : out    vl_logic;
        ARREADYs32mi3   : in     vl_logic;
        RIDs32mi3       : in     vl_logic_vector;
        RRESPs32mi3     : in     vl_logic_vector;
        RDATAs32mi3     : in     vl_logic_vector;
        RLASTs32mi3     : in     vl_logic;
        RVALIDs32mi3    : in     vl_logic;
        RREADYmi32s3    : out    vl_logic;
        ARIDmi42s4      : out    vl_logic_vector;
        ARADDRmi42s4    : out    vl_logic_vector;
        ARLENmi42s4     : out    vl_logic_vector;
        ARSIZEmi42s4    : out    vl_logic_vector;
        ARBURSTmi42s4   : out    vl_logic_vector;
        ARVALIDmi42s4   : out    vl_logic;
        ARREADYs42mi4   : in     vl_logic;
        RIDs42mi4       : in     vl_logic_vector;
        RRESPs42mi4     : in     vl_logic_vector;
        RDATAs42mi4     : in     vl_logic_vector;
        RLASTs42mi4     : in     vl_logic;
        RVALIDs42mi4    : in     vl_logic;
        RREADYmi42s4    : out    vl_logic;
        ARIDmi52s5      : out    vl_logic_vector;
        ARADDRmi52s5    : out    vl_logic_vector;
        ARLENmi52s5     : out    vl_logic_vector;
        ARSIZEmi52s5    : out    vl_logic_vector;
        ARBURSTmi52s5   : out    vl_logic_vector;
        ARVALIDmi52s5   : out    vl_logic;
        ARREADYs52mi5   : in     vl_logic;
        RIDs52mi5       : in     vl_logic_vector;
        RRESPs52mi5     : in     vl_logic_vector;
        RDATAs52mi5     : in     vl_logic_vector;
        RLASTs52mi5     : in     vl_logic;
        RVALIDs52mi5    : in     vl_logic;
        RREADYmi52s5    : out    vl_logic;
        ARIDmi62s6      : out    vl_logic_vector;
        ARADDRmi62s6    : out    vl_logic_vector;
        ARLENmi62s6     : out    vl_logic_vector;
        ARSIZEmi62s6    : out    vl_logic_vector;
        ARBURSTmi62s6   : out    vl_logic_vector;
        ARVALIDmi62s6   : out    vl_logic;
        ARREADYs62mi6   : in     vl_logic;
        RIDs62mi6       : in     vl_logic_vector;
        RRESPs62mi6     : in     vl_logic_vector;
        RDATAs62mi6     : in     vl_logic_vector;
        RLASTs62mi6     : in     vl_logic;
        RVALIDs62mi6    : in     vl_logic;
        RREADYmi62s6    : out    vl_logic;
        ARIDmi72s7      : out    vl_logic_vector;
        ARADDRmi72s7    : out    vl_logic_vector;
        ARLENmi72s7     : out    vl_logic_vector;
        ARSIZEmi72s7    : out    vl_logic_vector;
        ARBURSTmi72s7   : out    vl_logic_vector;
        ARVALIDmi72s7   : out    vl_logic;
        ARREADYs72mi7   : in     vl_logic;
        RIDs72mi7       : in     vl_logic_vector;
        RRESPs72mi7     : in     vl_logic_vector;
        RDATAs72mi7     : in     vl_logic_vector;
        RLASTs72mi7     : in     vl_logic;
        RVALIDs72mi7    : in     vl_logic;
        RREADYmi72s7    : out    vl_logic;
        Lock2rdmi0      : in     vl_logic;
        Lock2rdmi1      : in     vl_logic;
        Lock2rdmi2      : in     vl_logic;
        Lock2rdmi3      : in     vl_logic;
        Lock2rdmi4      : in     vl_logic;
        Lock2rdmi5      : in     vl_logic;
        Lock2rdmi6      : in     vl_logic;
        Lock2rdmi7      : in     vl_logic;
        Lock2wrmi0      : in     vl_logic;
        Lock2wrmi1      : in     vl_logic;
        Lock2wrmi2      : in     vl_logic;
        Lock2wrmi3      : in     vl_logic;
        Lock2wrmi4      : in     vl_logic;
        Lock2wrmi5      : in     vl_logic;
        Lock2wrmi6      : in     vl_logic;
        Lock2wrmi7      : in     vl_logic;
        UnLock2rdmi0    : in     vl_logic;
        UnLock2rdmi1    : in     vl_logic;
        UnLock2rdmi2    : in     vl_logic;
        UnLock2rdmi3    : in     vl_logic;
        UnLock2rdmi4    : in     vl_logic;
        UnLock2rdmi5    : in     vl_logic;
        UnLock2rdmi6    : in     vl_logic;
        UnLock2rdmi7    : in     vl_logic;
        UnLock2wrmi0    : out    vl_logic;
        UnLock2wrmi1    : out    vl_logic;
        UnLock2wrmi2    : out    vl_logic;
        UnLock2wrmi3    : out    vl_logic;
        UnLock2wrmi4    : out    vl_logic;
        UnLock2wrmi5    : out    vl_logic;
        UnLock2wrmi6    : out    vl_logic;
        UnLock2wrmi7    : out    vl_logic;
        AWVALIDmi02s0   : in     vl_logic;
        AWVALIDmi12s1   : in     vl_logic;
        AWVALIDmi22s2   : in     vl_logic;
        AWVALIDmi32s3   : in     vl_logic;
        AWVALIDmi42s4   : in     vl_logic;
        AWVALIDmi52s5   : in     vl_logic;
        AWVALIDmi62s6   : in     vl_logic;
        AWVALIDmi72s7   : in     vl_logic;
        LockPort2rdmi0  : in     vl_logic_vector;
        LockPort2rdmi1  : in     vl_logic_vector;
        LockPort2rdmi2  : in     vl_logic_vector;
        LockPort2rdmi3  : in     vl_logic_vector;
        LockPort2rdmi4  : in     vl_logic_vector;
        LockPort2rdmi5  : in     vl_logic_vector;
        LockPort2rdmi6  : in     vl_logic_vector;
        LockPort2rdmi7  : in     vl_logic_vector;
        ReadIntEmptyWrmi02Rdmi0: in     vl_logic;
        ReadIntEmptyWrmi12Rdmi1: in     vl_logic;
        ReadIntEmptyWrmi22Rdmi2: in     vl_logic;
        ReadIntEmptyWrmi32Rdmi3: in     vl_logic;
        ReadIntEmptyWrmi42Rdmi4: in     vl_logic;
        ReadIntEmptyWrmi52Rdmi5: in     vl_logic;
        ReadIntEmptyWrmi62Rdmi6: in     vl_logic;
        ReadIntEmptyWrmi72Rdmi7: in     vl_logic;
        DataCntEmptyRdmi02Wrmi0: out    vl_logic;
        DataCntEmptyRdmi12Wrmi1: out    vl_logic;
        DataCntEmptyRdmi22Wrmi2: out    vl_logic;
        DataCntEmptyRdmi32Wrmi3: out    vl_logic;
        DataCntEmptyRdmi42Wrmi4: out    vl_logic;
        DataCntEmptyRdmi52Wrmi5: out    vl_logic;
        DataCntEmptyRdmi62Wrmi6: out    vl_logic;
        DataCntEmptyRdmi72Wrmi7: out    vl_logic;
        CtlDataRead2Lock0: out    vl_logic_vector;
        CtlDataRead2Lock1: out    vl_logic_vector;
        CtlDataRead2Lock2: out    vl_logic_vector;
        CtlDataRead2Lock3: out    vl_logic_vector;
        CtlDataRead2Lock4: out    vl_logic_vector;
        CtlDataRead2Lock5: out    vl_logic_vector;
        CtlDataRead2Lock6: out    vl_logic_vector;
        CtlDataRead2Lock7: out    vl_logic_vector;
        ACLK            : in     vl_logic;
        ARESETn         : in     vl_logic
    );
end ReadChannel;
