library verilog;
use verilog.vl_types.all;
entity WriteChannel is
    generic(
        BUS_WID         : integer := 32;
        ADDR_WID        : integer := 32;
        MASTERID_WID    : integer := 1;
        SLAVEID_WID     : integer := 2;
        AWLEN_WID       : integer := 4;
        AWSIZE_WID      : integer := 3;
        AWBURST_WID     : integer := 2;
        AWLOCK_WID      : integer := 2;
        AWCACHE_WID     : integer := 4;
        AWPROT_WID      : integer := 3;
        WSTRB_WID       : integer := 4;
        BRESP_WID       : integer := 2;
        RRESP_WID       : integer := 2;
        ARLEN_WID       : integer := 4;
        ARBURST_WID     : integer := 2;
        ARLOCK_WID      : integer := 2;
        ARCACHE_WID     : integer := 4;
        ARPROT_WID      : integer := 3;
        MASTER_WID      : integer := 3;
        SLAVE_WID       : integer := 4;
        SLAVE_NUM       : integer := 8;
        MASTER_NUM      : integer := 5;
        SELMASTER_WID   : integer := 2;
        Wr_REQDEPTH_WID : integer := 1;
        Rd_REQDEPTH_WID : integer := 1;
        WrPermit_SLAVECNTWID: integer := 1;
        RdPermit_SLAVECNTWID: integer := 1;
        ARSIZE_WID      : integer := 3;
        MASTERID0_WID   : integer := 1;
        MASTERID1_WID   : integer := 1;
        MASTERID2_WID   : integer := 1;
        MASTERID3_WID   : integer := 1;
        MASTERID4_WID   : integer := 1;
        MAXMASTERID_WID : integer := 1;
        BLANKMASTERID0_WID: integer := 0;
        BLANKMASTERID1_WID: integer := 0;
        BLANKMASTERID2_WID: integer := 0;
        BLANKMASTERID3_WID: integer := 0;
        BLANKMASTERID4_WID: integer := 0;
        SLAVEID0_WID    : integer := 2;
        SLAVEID1_WID    : integer := 2;
        SLAVEID2_WID    : integer := 3;
        SLAVEID3_WID    : integer := 2;
        SLAVEID4_WID    : integer := 2;
        SLAVEID5_WID    : integer := 3;
        SLAVEID6_WID    : integer := 3;
        SLAVEID7_WID    : integer := 3;
        SELMASTER0_WID  : integer := 1;
        SELMASTER1_WID  : integer := 1;
        SELMASTER2_WID  : integer := 2;
        SELMASTER3_WID  : integer := 1;
        SELMASTER4_WID  : integer := 1;
        SELMASTER5_WID  : integer := 2;
        SELMASTER6_WID  : integer := 2;
        SELMASTER7_WID  : integer := 2;
        SLAVE_MASTERID0_WID: integer := 1;
        SLAVE_MASTERID1_WID: integer := 1;
        SLAVE_MASTERID2_WID: integer := 1;
        SLAVE_MASTERID3_WID: integer := 1;
        SLAVE_MASTERID4_WID: integer := 1;
        SLAVE_MASTERID5_WID: integer := 1;
        SLAVE_MASTERID6_WID: integer := 1;
        SLAVE_MASTERID7_WID: integer := 1
    );
    port(
        SelMAP1         : in     vl_logic;
        AWADDRm02si0    : in     vl_logic_vector;
        AWLENm02si0     : in     vl_logic_vector;
        AWSIZEm02si0    : in     vl_logic_vector;
        AWBURSTm02si0   : in     vl_logic_vector;
        AWLOCKm02si0    : in     vl_logic_vector;
        AWVALIDm02si0   : in     vl_logic;
        AWREADYsi02m0   : out    vl_logic;
        WDATAm02si0     : in     vl_logic_vector;
        WSTRBm02si0     : in     vl_logic_vector;
        WLASTm02si0     : in     vl_logic;
        WVALIDm02si0    : in     vl_logic;
        WREADYsi02m0    : out    vl_logic;
        BRESPsi02m0     : out    vl_logic_vector;
        BVALIDsi02m0    : out    vl_logic;
        BREADYm02si0    : in     vl_logic;
        AWIDm22si2      : in     vl_logic_vector;
        AWADDRm22si2    : in     vl_logic_vector;
        AWLENm22si2     : in     vl_logic_vector;
        AWSIZEm22si2    : in     vl_logic_vector;
        AWBURSTm22si2   : in     vl_logic_vector;
        AWVALIDm22si2   : in     vl_logic;
        AWREADYsi22m2   : out    vl_logic;
        WIDm22si2       : in     vl_logic_vector;
        WDATAm22si2     : in     vl_logic_vector;
        WSTRBm22si2     : in     vl_logic_vector;
        WLASTm22si2     : in     vl_logic;
        WVALIDm22si2    : in     vl_logic;
        WREADYsi22m2    : out    vl_logic;
        BIDsi22m2       : out    vl_logic_vector;
        BRESPsi22m2     : out    vl_logic_vector;
        BVALIDsi22m2    : out    vl_logic;
        BREADYm22si2    : in     vl_logic;
        AWADDRm32si3    : in     vl_logic_vector;
        AWLENm32si3     : in     vl_logic_vector;
        AWSIZEm32si3    : in     vl_logic_vector;
        AWBURSTm32si3   : in     vl_logic_vector;
        AWVALIDm32si3   : in     vl_logic;
        AWREADYsi32m3   : out    vl_logic;
        WDATAm32si3     : in     vl_logic_vector;
        WSTRBm32si3     : in     vl_logic_vector;
        WLASTm32si3     : in     vl_logic;
        WVALIDm32si3    : in     vl_logic;
        WREADYsi32m3    : out    vl_logic;
        BRESPsi32m3     : out    vl_logic_vector;
        BVALIDsi32m3    : out    vl_logic;
        BREADYm32si3    : in     vl_logic;
        AWADDRm42si4    : in     vl_logic_vector;
        AWLENm42si4     : in     vl_logic_vector;
        AWSIZEm42si4    : in     vl_logic_vector;
        AWBURSTm42si4   : in     vl_logic_vector;
        AWVALIDm42si4   : in     vl_logic;
        AWREADYsi42m4   : out    vl_logic;
        WDATAm42si4     : in     vl_logic_vector;
        WSTRBm42si4     : in     vl_logic_vector;
        WLASTm42si4     : in     vl_logic;
        WVALIDm42si4    : in     vl_logic;
        WREADYsi42m4    : out    vl_logic;
        BRESPsi42m4     : out    vl_logic_vector;
        BVALIDsi42m4    : out    vl_logic;
        BREADYm42si4    : in     vl_logic;
        AWIDmi02s0      : out    vl_logic_vector;
        AWADDRmi02s0    : out    vl_logic_vector;
        AWLENmi02s0     : out    vl_logic_vector;
        AWSIZEmi02s0    : out    vl_logic_vector;
        AWBURSTmi02s0   : out    vl_logic_vector;
        AWVALIDmi02s0   : out    vl_logic;
        AWREADYs02mi0   : in     vl_logic;
        WIDmi02s0       : out    vl_logic_vector;
        WDATAmi02s0     : out    vl_logic_vector;
        WLASTmi02s0     : out    vl_logic;
        WVALIDmi02s0    : out    vl_logic;
        WREADYs02mi0    : in     vl_logic;
        BIDs02mi0       : in     vl_logic_vector;
        BRESPs02mi0     : in     vl_logic_vector;
        BVALIDs02mi0    : in     vl_logic;
        BREADYmi02s0    : out    vl_logic;
        AWIDmi12s1      : out    vl_logic_vector;
        AWADDRmi12s1    : out    vl_logic_vector;
        AWLENmi12s1     : out    vl_logic_vector;
        AWSIZEmi12s1    : out    vl_logic_vector;
        AWBURSTmi12s1   : out    vl_logic_vector;
        AWVALIDmi12s1   : out    vl_logic;
        AWREADYs12mi1   : in     vl_logic;
        WIDmi12s1       : out    vl_logic_vector;
        WDATAmi12s1     : out    vl_logic_vector;
        WLASTmi12s1     : out    vl_logic;
        WVALIDmi12s1    : out    vl_logic;
        WREADYs12mi1    : in     vl_logic;
        BIDs12mi1       : in     vl_logic_vector;
        BRESPs12mi1     : in     vl_logic_vector;
        BVALIDs12mi1    : in     vl_logic;
        BREADYmi12s1    : out    vl_logic;
        AWIDmi22s2      : out    vl_logic_vector;
        AWADDRmi22s2    : out    vl_logic_vector;
        AWLENmi22s2     : out    vl_logic_vector;
        AWSIZEmi22s2    : out    vl_logic_vector;
        AWBURSTmi22s2   : out    vl_logic_vector;
        AWVALIDmi22s2   : out    vl_logic;
        AWREADYs22mi2   : in     vl_logic;
        WIDmi22s2       : out    vl_logic_vector;
        WDATAmi22s2     : out    vl_logic_vector;
        WSTRBmi22s2     : out    vl_logic_vector;
        WLASTmi22s2     : out    vl_logic;
        WVALIDmi22s2    : out    vl_logic;
        WREADYs22mi2    : in     vl_logic;
        BIDs22mi2       : in     vl_logic_vector;
        BRESPs22mi2     : in     vl_logic_vector;
        BVALIDs22mi2    : in     vl_logic;
        BREADYmi22s2    : out    vl_logic;
        AWIDmi32s3      : out    vl_logic_vector;
        AWADDRmi32s3    : out    vl_logic_vector;
        AWLENmi32s3     : out    vl_logic_vector;
        AWSIZEmi32s3    : out    vl_logic_vector;
        AWBURSTmi32s3   : out    vl_logic_vector;
        AWVALIDmi32s3   : out    vl_logic;
        AWREADYs32mi3   : in     vl_logic;
        WIDmi32s3       : out    vl_logic_vector;
        WDATAmi32s3     : out    vl_logic_vector;
        WLASTmi32s3     : out    vl_logic;
        WVALIDmi32s3    : out    vl_logic;
        WREADYs32mi3    : in     vl_logic;
        BIDs32mi3       : in     vl_logic_vector;
        BRESPs32mi3     : in     vl_logic_vector;
        BVALIDs32mi3    : in     vl_logic;
        BREADYmi32s3    : out    vl_logic;
        AWIDmi42s4      : out    vl_logic_vector;
        AWADDRmi42s4    : out    vl_logic_vector;
        AWLENmi42s4     : out    vl_logic_vector;
        AWSIZEmi42s4    : out    vl_logic_vector;
        AWBURSTmi42s4   : out    vl_logic_vector;
        AWVALIDmi42s4   : out    vl_logic;
        AWREADYs42mi4   : in     vl_logic;
        WIDmi42s4       : out    vl_logic_vector;
        WDATAmi42s4     : out    vl_logic_vector;
        WLASTmi42s4     : out    vl_logic;
        WVALIDmi42s4    : out    vl_logic;
        WREADYs42mi4    : in     vl_logic;
        BIDs42mi4       : in     vl_logic_vector;
        BRESPs42mi4     : in     vl_logic_vector;
        BVALIDs42mi4    : in     vl_logic;
        BREADYmi42s4    : out    vl_logic;
        AWIDmi52s5      : out    vl_logic_vector;
        AWADDRmi52s5    : out    vl_logic_vector;
        AWLENmi52s5     : out    vl_logic_vector;
        AWSIZEmi52s5    : out    vl_logic_vector;
        AWBURSTmi52s5   : out    vl_logic_vector;
        AWVALIDmi52s5   : out    vl_logic;
        AWREADYs52mi5   : in     vl_logic;
        WIDmi52s5       : out    vl_logic_vector;
        WDATAmi52s5     : out    vl_logic_vector;
        WSTRBmi52s5     : out    vl_logic_vector;
        WLASTmi52s5     : out    vl_logic;
        WVALIDmi52s5    : out    vl_logic;
        WREADYs52mi5    : in     vl_logic;
        BIDs52mi5       : in     vl_logic_vector;
        BRESPs52mi5     : in     vl_logic_vector;
        BVALIDs52mi5    : in     vl_logic;
        BREADYmi52s5    : out    vl_logic;
        AWIDmi62s6      : out    vl_logic_vector;
        AWADDRmi62s6    : out    vl_logic_vector;
        AWLENmi62s6     : out    vl_logic_vector;
        AWSIZEmi62s6    : out    vl_logic_vector;
        AWBURSTmi62s6   : out    vl_logic_vector;
        AWVALIDmi62s6   : out    vl_logic;
        AWREADYs62mi6   : in     vl_logic;
        WIDmi62s6       : out    vl_logic_vector;
        WDATAmi62s6     : out    vl_logic_vector;
        WSTRBmi62s6     : out    vl_logic_vector;
        WLASTmi62s6     : out    vl_logic;
        WVALIDmi62s6    : out    vl_logic;
        WREADYs62mi6    : in     vl_logic;
        BIDs62mi6       : in     vl_logic_vector;
        BRESPs62mi6     : in     vl_logic_vector;
        BVALIDs62mi6    : in     vl_logic;
        BREADYmi62s6    : out    vl_logic;
        AWIDmi72s7      : out    vl_logic_vector;
        AWADDRmi72s7    : out    vl_logic_vector;
        AWLENmi72s7     : out    vl_logic_vector;
        AWSIZEmi72s7    : out    vl_logic_vector;
        AWBURSTmi72s7   : out    vl_logic_vector;
        AWVALIDmi72s7   : out    vl_logic;
        AWREADYs72mi7   : in     vl_logic;
        WIDmi72s7       : out    vl_logic_vector;
        WDATAmi72s7     : out    vl_logic_vector;
        WSTRBmi72s7     : out    vl_logic_vector;
        WLASTmi72s7     : out    vl_logic;
        WVALIDmi72s7    : out    vl_logic;
        WREADYs72mi7    : in     vl_logic;
        BIDs72mi7       : in     vl_logic_vector;
        BRESPs72mi7     : in     vl_logic_vector;
        BVALIDs72mi7    : in     vl_logic;
        BREADYmi72s7    : out    vl_logic;
        Lock2wrmi0      : in     vl_logic;
        Lock2wrmi1      : in     vl_logic;
        Lock2wrmi2      : in     vl_logic;
        Lock2wrmi3      : in     vl_logic;
        Lock2wrmi4      : in     vl_logic;
        Lock2wrmi5      : in     vl_logic;
        Lock2wrmi6      : in     vl_logic;
        Lock2wrmi7      : in     vl_logic;
        Lock2rdmi0      : out    vl_logic;
        Lock2rdmi1      : out    vl_logic;
        Lock2rdmi2      : out    vl_logic;
        Lock2rdmi3      : out    vl_logic;
        Lock2rdmi4      : out    vl_logic;
        Lock2rdmi5      : out    vl_logic;
        Lock2rdmi6      : out    vl_logic;
        Lock2rdmi7      : out    vl_logic;
        UnLock2wrmi0    : in     vl_logic;
        UnLock2wrmi1    : in     vl_logic;
        UnLock2wrmi2    : in     vl_logic;
        UnLock2wrmi3    : in     vl_logic;
        UnLock2wrmi4    : in     vl_logic;
        UnLock2wrmi5    : in     vl_logic;
        UnLock2wrmi6    : in     vl_logic;
        UnLock2wrmi7    : in     vl_logic;
        UnLock2rdmi0    : out    vl_logic;
        UnLock2rdmi1    : out    vl_logic;
        UnLock2rdmi2    : out    vl_logic;
        UnLock2rdmi3    : out    vl_logic;
        UnLock2rdmi4    : out    vl_logic;
        UnLock2rdmi5    : out    vl_logic;
        UnLock2rdmi6    : out    vl_logic;
        UnLock2rdmi7    : out    vl_logic;
        ARVALIDmi02s0   : in     vl_logic;
        ARVALIDmi12s1   : in     vl_logic;
        ARVALIDmi22s2   : in     vl_logic;
        ARVALIDmi32s3   : in     vl_logic;
        ARVALIDmi42s4   : in     vl_logic;
        ARVALIDmi52s5   : in     vl_logic;
        ARVALIDmi62s6   : in     vl_logic;
        ARVALIDmi72s7   : in     vl_logic;
        LockPort2wrmi0  : in     vl_logic_vector;
        LockPort2wrmi1  : in     vl_logic_vector;
        LockPort2wrmi2  : in     vl_logic_vector;
        LockPort2wrmi3  : in     vl_logic_vector;
        LockPort2wrmi4  : in     vl_logic_vector;
        LockPort2wrmi5  : in     vl_logic_vector;
        LockPort2wrmi6  : in     vl_logic_vector;
        LockPort2wrmi7  : in     vl_logic_vector;
        ReadIntEmptyWrmi02Rdmi0: out    vl_logic;
        ReadIntEmptyWrmi12Rdmi1: out    vl_logic;
        ReadIntEmptyWrmi22Rdmi2: out    vl_logic;
        ReadIntEmptyWrmi32Rdmi3: out    vl_logic;
        ReadIntEmptyWrmi42Rdmi4: out    vl_logic;
        ReadIntEmptyWrmi52Rdmi5: out    vl_logic;
        ReadIntEmptyWrmi62Rdmi6: out    vl_logic;
        ReadIntEmptyWrmi72Rdmi7: out    vl_logic;
        DataCntEmptyRdmi02Wrmi0: in     vl_logic;
        DataCntEmptyRdmi12Wrmi1: in     vl_logic;
        DataCntEmptyRdmi22Wrmi2: in     vl_logic;
        DataCntEmptyRdmi32Wrmi3: in     vl_logic;
        DataCntEmptyRdmi42Wrmi4: in     vl_logic;
        DataCntEmptyRdmi52Wrmi5: in     vl_logic;
        DataCntEmptyRdmi62Wrmi6: in     vl_logic;
        DataCntEmptyRdmi72Wrmi7: in     vl_logic;
        CtlDataWrite2Lock0: out    vl_logic_vector;
        CtlDataWrite2Lock1: out    vl_logic_vector;
        CtlDataWrite2Lock2: out    vl_logic_vector;
        CtlDataWrite2Lock3: out    vl_logic_vector;
        CtlDataWrite2Lock4: out    vl_logic_vector;
        CtlDataWrite2Lock5: out    vl_logic_vector;
        CtlDataWrite2Lock6: out    vl_logic_vector;
        CtlDataWrite2Lock7: out    vl_logic_vector;
        ACLK            : in     vl_logic;
        ARESETn         : in     vl_logic
    );
end WriteChannel;
