library verilog;
use verilog.vl_types.all;
entity pci_cfgspace is
    generic(
        oe_active       : integer := 0;
        vendor_id       : integer := 43981;
        device_id       : integer := 25702;
        class_id        : integer := 425984;
        rev_id          : integer := 16;
        bar0_present    : integer := 1;
        bar0_dwidth     : integer := 22;
        bar1_present    : integer := 1;
        bar1_dwidth     : integer := 8;
        bar2_present    : integer := 0;
        bar2_map        : integer := 0;
        bar2_dwidth     : integer := 28;
        bar3_present    : integer := 0;
        bar3_map        : integer := 0;
        bar3_dwidth     : integer := 28;
        bar4_present    : integer := 0;
        bar4_map        : integer := 0;
        bar4_dwidth     : integer := 28;
        bar5_present    : integer := 0;
        bar5_map        : integer := 0;
        bar5_dwidth     : integer := 28;
        ebar_present    : integer := 0;
        ebar_map        : integer := 0;
        ebar_dwidth     : integer := 17;
        subvendor_id    : integer := 4334;
        subdevice_id    : integer := 256;
        cis_ptr         : integer := 0;
        cap_ptr         : integer := 0;
        max_lat         : integer := 32;
        min_gnt         : integer := 4;
        int_pin         : integer := 1;
        int_line        : integer := 0;
        command_init    : integer := 0;
        status_init     : integer := 544;
        clsize_init     : integer := 0;
        lattimer_init   : integer := 0;
        intline_init    : integer := 0;
        iack_code       : integer := 0;
        scyc_code       : integer := 1;
        iord_code       : integer := 2;
        iowr_code       : integer := 3;
        res4_code       : integer := 4;
        res5_code       : integer := 5;
        mrd_code        : integer := 6;
        mwr_code        : integer := 7;
        res8_code       : integer := 8;
        res9_code       : integer := 9;
        cfgrd_code      : integer := 10;
        cfgwr_code      : integer := 11;
        mrm_code        : integer := 12;
        dual_code       : integer := 13;
        mrl_code        : integer := 14;
        mwi_code        : integer := 15;
        idle            : integer := 0;
        decode          : integer := 1;
        data            : integer := 2
    );
    port(
        reset           : in     vl_logic;
        clk             : in     vl_logic;
        din             : in     vl_logic_vector(31 downto 0);
        dout            : out    vl_logic_vector(31 downto 0);
        adr             : in     vl_logic_vector(7 downto 2);
        busadr          : in     vl_logic_vector(31 downto 0);
        ben             : in     vl_logic_vector(3 downto 0);
        cmd_cfgrd       : in     vl_logic;
        cmd_cfgwr       : in     vl_logic;
        acc_end         : in     vl_logic;
        first_cyc       : in     vl_logic;
        acc_cfg         : in     vl_logic;
        acc_io          : in     vl_logic;
        acc_mem         : in     vl_logic;
        adr_valid       : in     vl_logic;
        we              : in     vl_logic;
        set_mdperr      : in     vl_logic;
        sig_tabort      : in     vl_logic;
        rcv_tabort      : in     vl_logic;
        rcv_mabort      : in     vl_logic;
        sig_serr        : in     vl_logic;
        det_perr        : in     vl_logic;
        drdy            : out    vl_logic;
        b_limit         : out    vl_logic;
        card_hit        : out    vl_logic;
        target_act      : out    vl_logic;
        cfg_hit         : out    vl_logic;
        bar_hit         : out    vl_logic_vector(5 downto 0);
        rom_hit         : out    vl_logic;
        pcr_cmd         : out    vl_logic_vector(15 downto 0);
        pcr_stat        : out    vl_logic_vector(15 downto 0);
        io_en           : out    vl_logic;
        mem_en          : out    vl_logic;
        master_en       : out    vl_logic;
        spec_cyc        : out    vl_logic;
        mwi_en          : out    vl_logic;
        perr_en         : out    vl_logic;
        stepping_en     : out    vl_logic;
        serr_en         : out    vl_logic;
        lat_timer       : out    vl_logic_vector(7 downto 0);
        cache_size      : out    vl_logic_vector(7 downto 0)
    );
end pci_cfgspace;
