library verilog;
use verilog.vl_types.all;
entity pci_genpar64 is
    generic(
        oe_active       : integer := 0;
        vendor_id       : integer := 43981;
        device_id       : integer := 25702;
        class_id        : integer := 425984;
        rev_id          : integer := 16;
        bar0_present    : integer := 1;
        bar0_dwidth     : integer := 22;
        bar1_present    : integer := 1;
        bar1_dwidth     : integer := 8;
        bar2_present    : integer := 0;
        bar2_map        : integer := 0;
        bar2_dwidth     : integer := 28;
        bar3_present    : integer := 0;
        bar3_map        : integer := 0;
        bar3_dwidth     : integer := 28;
        bar4_present    : integer := 0;
        bar4_map        : integer := 0;
        bar4_dwidth     : integer := 28;
        bar5_present    : integer := 0;
        bar5_map        : integer := 0;
        bar5_dwidth     : integer := 28;
        ebar_present    : integer := 0;
        ebar_map        : integer := 0;
        ebar_dwidth     : integer := 17;
        subvendor_id    : integer := 4334;
        subdevice_id    : integer := 256;
        cis_ptr         : integer := 0;
        cap_ptr         : integer := 0;
        max_lat         : integer := 32;
        min_gnt         : integer := 4;
        int_pin         : integer := 1;
        int_line        : integer := 0;
        command_init    : integer := 0;
        status_init     : integer := 544;
        clsize_init     : integer := 0;
        lattimer_init   : integer := 0;
        intline_init    : integer := 0;
        iack_code       : integer := 0;
        scyc_code       : integer := 1;
        iord_code       : integer := 2;
        iowr_code       : integer := 3;
        res4_code       : integer := 4;
        res5_code       : integer := 5;
        mrd_code        : integer := 6;
        mwr_code        : integer := 7;
        res8_code       : integer := 8;
        res9_code       : integer := 9;
        cfgrd_code      : integer := 10;
        cfgwr_code      : integer := 11;
        mrm_code        : integer := 12;
        dual_code       : integer := 13;
        mrl_code        : integer := 14;
        mwi_code        : integer := 15
    );
    port(
        rstpci          : in     vl_logic;
        clkpci          : in     vl_logic;
        clr_adtff       : in     vl_logic;
        ce_ado          : in     vl_logic;
        ot_ado_nxt      : in     vl_logic;
        ado             : in     vl_logic_vector(63 downto 0);
        cbei            : in     vl_logic_vector(7 downto 0);
        ot_par_nxt      : out    vl_logic;
        paro_nxt        : out    vl_logic;
        ot_par64_nxt    : out    vl_logic;
        par64o_nxt      : out    vl_logic
    );
end pci_genpar64;
