library verilog;
use verilog.vl_types.all;
entity testmaster2x2ch is
    generic(
        data_width      : integer := 32;
        wid_width       : integer := 4;
        rid_width       : integer := 4;
        randomize       : integer := 1;
        wrap_support    : integer := 1;
        word_only       : integer := 0;
        halfword_byte_single_only: integer := 0;
        maximum_idle_cnt: integer := 100000;
        awq_width       : integer := 4;
        wdq_width       : integer := 8;
        arq_width       : integer := 4;
        rdq_width       : integer := 8;
        cnt_width       : integer := 32;
        unitdelay       : integer := 1;
        sram_addr       : integer := 0;
        peri0_control_addr: integer := 536870912;
        peri1_control_addr: integer := 536871424;
        peri2_control_addr: integer := 536871936;
        peri3_control_addr: integer := 536872448;
        peri4_control_addr: integer := 536872960;
        peri5_control_addr: integer := 536873472;
        peri6_control_addr: integer := 536873984;
        peri7_control_addr: integer := 536874496;
        peri0_fifo_addr : integer := 536870916;
        peri1_fifo_addr : integer := 536871428;
        peri2_fifo_addr : integer := 536871940;
        peri3_fifo_addr : integer := 536872452;
        peri4_fifo_addr : integer := 536872964;
        peri5_fifo_addr : integer := 536873476;
        peri6_fifo_addr : integer := 536873988;
        peri7_fifo_addr : integer := 536874500;
        dmac_addr       : integer := 536875008;
        src_addr        : integer := 0;
        dst0_addr       : integer := 11264;
        dst1_addr       : integer := 19456;
        dst2_addr       : integer := 27648;
        dst3_addr       : integer := 35840;
        length          : integer := 2048;
        half_length     : integer := 768;
        desc00_addr     : integer := 16324;
        desc01_addr     : integer := 16364;
        desc10_addr     : integer := 24516;
        desc11_addr     : integer := 24556;
        desc20_addr     : integer := 32708;
        desc21_addr     : integer := 32748;
        desc30_addr     : integer := 40900;
        desc31_addr     : integer := 40940
    );
    port(
        aclk            : in     vl_logic;
        aresetn         : in     vl_logic;
        awid            : out    vl_logic_vector;
        awaddr          : out    vl_logic_vector(31 downto 0);
        awlen           : out    vl_logic_vector(3 downto 0);
        awsize          : out    vl_logic_vector(2 downto 0);
        awburst         : out    vl_logic_vector(1 downto 0);
        awlock          : out    vl_logic_vector(1 downto 0);
        awcache         : out    vl_logic_vector(3 downto 0);
        awprot          : out    vl_logic_vector(2 downto 0);
        awvalid         : out    vl_logic;
        awready         : in     vl_logic;
        wid             : out    vl_logic_vector;
        wdata           : out    vl_logic_vector;
        wstrb           : out    vl_logic_vector;
        wlast           : out    vl_logic;
        wvalid          : out    vl_logic;
        wready          : in     vl_logic;
        bid             : in     vl_logic_vector;
        bresp           : in     vl_logic_vector(1 downto 0);
        bvalid          : in     vl_logic;
        bready          : out    vl_logic;
        arid            : out    vl_logic_vector;
        araddr          : out    vl_logic_vector(31 downto 0);
        arlen           : out    vl_logic_vector(3 downto 0);
        arsize          : out    vl_logic_vector(2 downto 0);
        arburst         : out    vl_logic_vector(1 downto 0);
        arlock          : out    vl_logic_vector(1 downto 0);
        arcache         : out    vl_logic_vector(3 downto 0);
        arprot          : out    vl_logic_vector(2 downto 0);
        arvalid         : out    vl_logic;
        arready         : in     vl_logic;
        rid             : in     vl_logic_vector;
        rdata           : in     vl_logic_vector;
        rresp           : in     vl_logic_vector(1 downto 0);
        rlast           : in     vl_logic;
        rvalid          : in     vl_logic;
        rready          : out    vl_logic
    );
end testmaster2x2ch;
