#- --=========================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2001 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#-------------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.3
#-
#- Release Information    : PrimeCell(TM)-PL220-r0p0-00ltd0
#-
#-------------------------------------------------------------------------------
#-  Purpose  : 
#-             Standard Verilog Library Makefile
#-
#- --=========================================================================--
MODULES = EbiParams.v \
          EbiArbCntl.v \
          EbiMux.v \
          Ebi.v

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

#################################### End #######################################
