library verilog;
use verilog.vl_types.all;
entity ESP is
    port(
        EEMDO           : in     vl_logic_vector(15 downto 0);
        PMD             : in     vl_logic_vector(15 downto 0);
        PMA             : in     vl_logic_vector(7 downto 0);
        SOBWS           : in     vl_logic_vector(1 downto 0);
        RXD             : in     vl_logic_vector(31 downto 0);
        EIMO            : in     vl_logic_vector(15 downto 0);
        ESSD            : in     vl_logic_vector(19 downto 0);
        EDBRS           : in     vl_logic_vector(1 downto 0);
        SDI2            : in     vl_logic;
        TI1             : in     vl_logic;
        EMCL            : in     vl_logic;
        RXESEN          : in     vl_logic;
        ENP             : in     vl_logic;
        TE              : in     vl_logic;
        MCK             : in     vl_logic;
        TI0             : in     vl_logic;
        XRST            : in     vl_logic;
        TXRDY           : in     vl_logic;
        TXEN            : in     vl_logic;
        RXEN            : in     vl_logic;
        RXWE            : in     vl_logic;
        SDI1            : in     vl_logic;
        TSCST           : in     vl_logic;
        SURDEN          : in     vl_logic;
        PCEBEN          : in     vl_logic;
        ESYNC           : in     vl_logic;
        EWREQ           : in     vl_logic;
        EIMA            : out    vl_logic_vector(7 downto 0);
        EIMDI           : out    vl_logic_vector(15 downto 0);
        EEMDI           : out    vl_logic_vector(15 downto 0);
        EEMA            : out    vl_logic_vector(15 downto 0);
        TXD             : out    vl_logic_vector(31 downto 0);
        EROMA           : out    vl_logic_vector(8 downto 0);
        TO1             : out    vl_logic;
        EROMAS          : out    vl_logic;
        TO0             : out    vl_logic;
        RXSYNC          : out    vl_logic;
        RXRDY           : out    vl_logic;
        TXSYNC          : out    vl_logic;
        TXRD            : out    vl_logic;
        LRCKO           : out    vl_logic;
        SCKO            : out    vl_logic;
        SD2O            : out    vl_logic;
        SD1O            : out    vl_logic;
        EWRDY           : out    vl_logic;
        XEIMWE          : out    vl_logic;
        XEEMWE          : out    vl_logic;
        ESSCL           : out    vl_logic;
        ESSCE           : out    vl_logic;
        MLRCK           : out    vl_logic;
        MSCK            : out    vl_logic
    );
end ESP;
