library verilog;
use verilog.vl_types.all;
entity SDRBsm is
    generic(
        AW              : integer := 25;
        DW              : integer := 31;
        BW              : integer := 3;
        BL              : integer := 3;
        ID              : integer := 3;
        WQCD            : integer := 5;
        WQD             : integer := 63;
        RQCD            : integer := 5;
        RQD             : integer := 63;
        WBLQCD          : integer := 1;
        WBLQD           : integer := 3;
        RBLQCD          : integer := 1;
        RBLQD           : integer := 3;
        MDW             : integer := 31;
        DMW             : integer := 3;
        BAW             : integer := 1;
        RAW             : integer := 12;
        CAW             : integer := 10;
        TL              : integer := 4;
        RWW             : integer := 1;
        CD              : integer := 3;
        erc_powerup     : integer := 1;
        erc_epc         : integer := 2;
        erc_ar          : integer := 4;
        erc_mrs         : integer := 8;
        erc_idle        : integer := 16;
        erc_normal      : integer := 32;
        bc_null         : integer := 0;
        bc_mcas         : integer := 1;
        bc_mras         : integer := 2;
        bc_pc           : integer := 4;
        bc_sras         : integer := 8;
        bc_scas         : integer := 16;
        bc_epc          : integer := 32;
        ebc_null        : integer := 0;
        ebc_mcas        : integer := 1;
        ebc_mras        : integer := 2;
        ebc_pc          : integer := 4;
        ebc_sras        : integer := 8;
        ebc_scas        : integer := 16;
        ebc_epc         : integer := 32;
        ebc_bstop       : integer := 64;
        bs_idle         : integer := 1;
        bs_pcing        : integer := 2;
        bs_rowopen      : integer := 4;
        bs_rasing       : integer := 8;
        bs_casing       : integer := 16
    );
    port(
        ARESETB         : in     vl_logic;
        ACLK            : in     vl_logic;
        TRP             : in     vl_logic_vector(1 downto 0);
        TRRD            : in     vl_logic_vector(1 downto 0);
        TRCD            : in     vl_logic_vector(1 downto 0);
        TRASMIN         : in     vl_logic_vector(3 downto 0);
        BA_BA           : in     vl_logic_vector;
        BA_RA           : in     vl_logic_vector;
        BA_TT           : in     vl_logic_vector;
        BA_REQ          : in     vl_logic;
        CAS_0_BA        : in     vl_logic_vector;
        CAS_0_RA        : in     vl_logic_vector;
        CAS_0_TT        : in     vl_logic_vector;
        CAS_0_FINAL     : in     vl_logic;
        CAS_0_NEWROW    : in     vl_logic;
        CAS_EMPTY       : in     vl_logic;
        LAST_RA         : in     vl_logic_vector;
        RAS_0_BA        : in     vl_logic_vector;
        RAS_0_RA        : in     vl_logic_vector;
        RAS_0_TT        : in     vl_logic_vector;
        RAS_EMPTY       : in     vl_logic;
        BF_NO           : in     vl_logic_vector;
        BF_CASBUSY      : out    vl_logic;
        BF_TCASBUSY     : in     vl_logic;
        BF_RASBUSY      : out    vl_logic;
        BF_TRASBUSY     : in     vl_logic;
        BF_READY        : out    vl_logic;
        BF_TREADY       : in     vl_logic;
        BF_IDLE         : out    vl_logic;
        BF_LAST         : out    vl_logic;
        BF_REQCMD       : out    vl_logic_vector(5 downto 0);
        BF_CMD          : in     vl_logic_vector(5 downto 0);
        ERCMD           : in     vl_logic_vector(5 downto 0);
        ECMD            : in     vl_logic_vector(6 downto 0)
    );
end SDRBsm;
