#-------------------------------------------------------------------------------
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2002 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#-------------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.9
#-
#- Release Information    : PrimeCell(TM)-PL192-r0p0-00rel0
#-
#-------------------------------------------------------------------------------
#-  Purpose  :
#-             Standard Verilog Library Makefile
#-------------------------------------------------------------------------------

MODULES = VicPriority.v \
          VicIntResolver.v \
          VicRevAnd.v \
          VicAhbif.v \
          VicCpuif.v \
          VicInterrupt.v \
          Vic.v

PERIPH = Vic
include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

############################### End of file ######################################
