#-----------------------------------------------------------------------
#-  This confidential and proprietary software may be used only as
#-  authorised by a licensing agreement from ARM Limited
#-    (C) COPYRIGHT 1999, 2000 ARM Limited
#-        ALL RIGHTS RESERVED
#-  The entire notice above must be reproduced on all authorised
#-  copies and copies may only be made to the extent permitted
#-  by a licensing agreement from ARM Limited.
#-----------------------------------------------------------------------
#-
#-  Version and Release Control Information:
#-
#-  File Name              : makefile,v
#-  File Revision          : 1.13
#-
#-  Release Information    : PrimeCell(TM)-PL170-REL2v2
#-
#-----------------------------------------------------------------------
 
#-----------------------------------------------------------------------
#-  Purpose  : Standard Verilog Library Makefile
#-----------------------------------------------------------------------

MODULES = SdramDefs.v \
          SdramBigEndian.v \
          SdramAhbif.v \
          SdramAhbRegBlk.v \
          SdramAhbWrBuf0.v \
          SdramAhbWrBuf1.v \
          SdramAhbRdBuf0.v \
          SdramArbFSM.v \
          SdramArbiter.v \
          SdramDramFSM.v \
          SdramTimCntl.v \
          SdramDramCntl.v \
          SdramCmdSeq.v \
          SdramEngine.v \
          SdramPins.v \
          Sdram.v

include ../modeltech/StdMakefile.mk

########################## End of file #################################
