library verilog;
use verilog.vl_types.all;
entity MuxS2M is
    port(
        HCLK            : in     vl_logic;
        HRESETn         : in     vl_logic;
        HSELS0          : in     vl_logic;
        HSELS1          : in     vl_logic;
        HSELS2          : in     vl_logic;
        HSELS3          : in     vl_logic;
        HSELS4          : in     vl_logic;
        HSELS5          : in     vl_logic;
        HSELS6          : in     vl_logic;
        HSELS7          : in     vl_logic;
        HSELDefault     : in     vl_logic;
        HRDATAS0        : in     vl_logic_vector(31 downto 0);
        HREADYS0        : in     vl_logic;
        HRESPS0         : in     vl_logic_vector(1 downto 0);
        HRDATAS1        : in     vl_logic_vector(31 downto 0);
        HREADYS1        : in     vl_logic;
        HRESPS1         : in     vl_logic_vector(1 downto 0);
        HRDATAS2        : in     vl_logic_vector(31 downto 0);
        HREADYS2        : in     vl_logic;
        HRESPS2         : in     vl_logic_vector(1 downto 0);
        HRDATAS3        : in     vl_logic_vector(31 downto 0);
        HREADYS3        : in     vl_logic;
        HRESPS3         : in     vl_logic_vector(1 downto 0);
        HRDATAS4        : in     vl_logic_vector(31 downto 0);
        HREADYS4        : in     vl_logic;
        HRESPS4         : in     vl_logic_vector(1 downto 0);
        HRDATAS5        : in     vl_logic_vector(31 downto 0);
        HREADYS5        : in     vl_logic;
        HRESPS5         : in     vl_logic_vector(1 downto 0);
        HRDATAS6        : in     vl_logic_vector(31 downto 0);
        HREADYS6        : in     vl_logic;
        HRESPS6         : in     vl_logic_vector(1 downto 0);
        HRDATAS7        : in     vl_logic_vector(31 downto 0);
        HREADYS7        : in     vl_logic;
        HRESPS7         : in     vl_logic_vector(1 downto 0);
        HREADYDefault   : in     vl_logic;
        HRESPDefault    : in     vl_logic_vector(1 downto 0);
        HRDATA          : out    vl_logic_vector(31 downto 0);
        HREADY          : out    vl_logic;
        HRESP           : out    vl_logic_vector(1 downto 0);
        SCANENABLE      : in     vl_logic;
        SCANINHCLK      : in     vl_logic;
        SCANOUTHCLK     : out    vl_logic
    );
end MuxS2M;
