#- --=================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#-----------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.1
#-
#- Release Information    : PrimeCell(TM)-PL022-REL1v2
#-
#-----------------------------------------------------------------------
#-  Purpose  : 
#-             VHDL Library Makefile
#-
#- --=================================================================--

all: 
	@cp -f $(GLOBAL)/tictalk_ahb/vhdl/sys/*.vhd .

clean:  
	@rm -rf *.vhd

################################ End ###################################
