/********************************
	typedef 定義
*********************************/

#ifndef _TYPEDEF_
#define _TYPEDEF_

#ifdef IDE1
	/* x86系CPU MS-DOS(16ビット)環境 */
	typedef unsigned long		UDWORD;
	typedef unsigned int		UWORD;
	typedef unsigned char		UBYTE;
#endif
#ifdef IDE2
	/* x86系CPU MS-DOS(16ビット)環境 */
	typedef unsigned long		UDWORD;
	typedef unsigned int		UWORD;
	typedef unsigned char		UBYTE;
#endif
#ifdef PCI
	/* x86系CPU MS-DOS(16ビット)環境 */
	typedef unsigned long		UDWORD;
	typedef unsigned int		UWORD;
	typedef unsigned char		UBYTE;
#endif

#endif
