library verilog;
use verilog.vl_types.all;
entity dma64txctrl is
    generic(
        idle            : integer := 1;
        request         : integer := 2;
        data            : integer := 4;
        retry           : integer := 8;
        idle_bit        : integer := 0;
        request_bit     : integer := 1;
        data_bit        : integer := 2;
        retry_bit       : integer := 3;
        retry_time      : integer := 4;
        dma_read        : integer := 1;
        dma_write       : integer := 0
    );
    port(
        rstpci          : in     vl_logic;
        clkpci          : in     vl_logic;
        irdynid         : in     vl_logic;
        trdynid         : in     vl_logic;
        m_nextd         : in     vl_logic;
        m_rejd          : in     vl_logic;
        m_aack          : in     vl_logic;
        m_aack64        : in     vl_logic;
        m_tretry        : in     vl_logic;
        m_tabort        : in     vl_logic;
        m_abort         : in     vl_logic;
        m_otcmd         : in     vl_logic;
        m_drdy          : out    vl_logic;
        m_areq          : out    vl_logic;
        m_areq64        : out    vl_logic;
        m_otdata        : in     vl_logic;
        m_crw           : out    vl_logic;
        m_lastd         : out    vl_logic;
        wf_read         : out    vl_logic;
        wf_undo         : out    vl_logic;
        wf_dwordsel     : out    vl_logic;
        rf_wrl          : out    vl_logic;
        rf_wrh          : out    vl_logic;
        rf_dwordsel     : out    vl_logic;
        rf_tf           : in     vl_logic;
        rf_af           : in     vl_logic;
        rf_te           : in     vl_logic;
        rf_mid          : in     vl_logic;
        wf_tf           : in     vl_logic;
        wf_te           : in     vl_logic;
        wf_ae           : in     vl_logic;
        wf_mid          : in     vl_logic;
        txsucc32        : out    vl_logic;
        txsucc64        : out    vl_logic;
        inc_ahbaddr     : out    vl_logic;
        tx_pcierrset    : out    vl_logic;
        tx_ahberrset    : out    vl_logic;
        tx_doneset      : out    vl_logic;
        tx_64fset       : out    vl_logic;
        txcnt_0         : in     vl_logic;
        hclk            : in     vl_logic;
        hresetn         : in     vl_logic;
        itxinit         : out    vl_logic;
        iwr             : out    vl_logic;
        iburst          : out    vl_logic;
        iprefetch       : out    vl_logic_vector(3 downto 0);
        idrdy           : in     vl_logic;
        itxerr          : in     vl_logic;
        itxidle         : in     vl_logic;
        wbae            : in     vl_logic;
        wbte            : in     vl_logic;
        wbrd            : in     vl_logic;
        rbaf            : in     vl_logic;
        rbtf            : in     vl_logic;
        rbwr            : in     vl_logic;
        rbmid           : in     vl_logic;
        wbmid           : in     vl_logic;
        dma_txena       : in     vl_logic;
        dma_tx64        : in     vl_logic;
        dma_txdone      : in     vl_logic;
        dma_pcierr      : in     vl_logic;
        dma_ahberr      : in     vl_logic;
        dma_tx64fail    : in     vl_logic;
        dma_cmderror    : out    vl_logic;
        dma_txcnt       : in     vl_logic_vector(23 downto 0);
        dma_pcicmd      : in     vl_logic_vector(3 downto 0);
        dma_ahbaddr     : in     vl_logic_vector(31 downto 0)
    );
end dma64txctrl;
