@TM:1165022600
@W: BN116 :"":0:0:0:-1|Removing sequential instance que_lencst[0:0] of view:PrimLib.dffr(prim) because there are no references to its outputs 
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF258 :"":0:0:0:-1|Gated clock conversion disabled 
@W: MO111 :"":0:0:0:-1|tristate driver ARCACHEsi02mi5_t[0] on net ARCACHEsi02mi5[0] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARCACHEsi02mi5_t[1] on net ARCACHEsi02mi5[1] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARCACHEsi02mi5_t[2] on net ARCACHEsi02mi5[2] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARCACHEsi02mi5_t[3] on net ARCACHEsi02mi5[3] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARCACHEsi12mi5_t[0] on net ARCACHEsi12mi5[0] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARCACHEsi12mi5_t[1] on net ARCACHEsi12mi5[1] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARCACHEsi12mi5_t[2] on net ARCACHEsi12mi5[2] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARCACHEsi12mi5_t[3] on net ARCACHEsi12mi5[3] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARLOCKsi12mi5_t[0] on net ARLOCKsi12mi5[0] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARLOCKsi12mi5_t[1] on net ARLOCKsi12mi5[1] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARPROTsi02mi5_t[0] on net ARPROTsi02mi5[0] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARPROTsi02mi5_t[1] on net ARPROTsi02mi5[1] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARPROTsi02mi5_t[2] on net ARPROTsi02mi5[2] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARPROTsi12mi5_t[0] on net ARPROTsi12mi5[0] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARPROTsi12mi5_t[1] on net ARPROTsi12mi5[1] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARPROTsi12mi5_t[2] on net ARPROTsi12mi5[2] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARREADYmi12si_t[1] on net ARREADYmi12si[1] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARREADYmi22si_t[1] on net ARREADYmi22si[1] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARREADYmi2si_t[1] on net ARREADYmi2si[1] has its enable tied to GND (module APB0_RS_ReadChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver ARREADYmi2si_t[1] on net ARREADYmi2si[1] has its enable tied to GND (module APB1_RS_ReadChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver ARVALIDsi12mi_t[1] on net ARVALIDsi12mi[1] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARVALIDsi12mi_t[2] on net ARVALIDsi12mi[2] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver ARVALIDsi2mi_t[1] on net ARVALIDsi2mi[1] has its enable tied to GND (module VideoEnC_RS_ReadChannelsi) 
@W: MO111 :"":0:0:0:-1|tristate driver ARVALIDsi2mi_t[2] on net ARVALIDsi2mi[2] has its enable tied to GND (module VideoEnC_RS_ReadChannelsi) 
@W: MO111 :"":0:0:0:-1|tristate driver AWCACHEsi02mi5_t[0] on net AWCACHEsi02mi5[0] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver AWCACHEsi02mi5_t[1] on net AWCACHEsi02mi5[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver AWCACHEsi02mi5_t[2] on net AWCACHEsi02mi5[2] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver AWCACHEsi02mi5_t[3] on net AWCACHEsi02mi5[3] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver AWPROTsi02mi5_t[0] on net AWPROTsi02mi5[0] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver AWPROTsi02mi5_t[1] on net AWPROTsi02mi5[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver AWPROTsi02mi5_t[2] on net AWPROTsi02mi5[2] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver AWREADYmi02si_t[1] on net AWREADYmi02si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver AWREADYmi12si_t[1] on net AWREADYmi12si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver AWREADYmi22si_t[1] on net AWREADYmi22si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver AWREADYmi2si_t[1] on net AWREADYmi2si[1] has its enable tied to GND (module APB0_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver AWREADYmi2si_t[1] on net AWREADYmi2si[1] has its enable tied to GND (module APB1_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver AWREADYmi2si_t[1] on net AWREADYmi2si[1] has its enable tied to GND (module DDRCtrl_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver AWREADYmi2si_t[1] on net AWREADYmi2si[1] has its enable tied to GND (module IntSRAM_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver AWREADYmi2si_t[1] on net AWREADYmi2si[1] has its enable tied to GND (module SMC_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver AWREADYmi2si_t[1] on net AWREADYmi2si[1] has its enable tied to GND (module default_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver AWREADYmi32si_t[1] on net AWREADYmi32si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver AWREADYmi42si_t[1] on net AWREADYmi42si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver AWREADYmi52si_t[1] on net AWREADYmi52si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver BVALIDmi02si_t[1] on net BVALIDmi02si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver BVALIDmi12si_t[1] on net BVALIDmi12si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver BVALIDmi22si_t[1] on net BVALIDmi22si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver BVALIDmi2si_t[1] on net BVALIDmi2si[1] has its enable tied to GND (module APB0_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver BVALIDmi2si_t[1] on net BVALIDmi2si[1] has its enable tied to GND (module APB1_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver BVALIDmi2si_t[1] on net BVALIDmi2si[1] has its enable tied to GND (module DDRCtrl_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver BVALIDmi2si_t[1] on net BVALIDmi2si[1] has its enable tied to GND (module IntSRAM_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver BVALIDmi2si_t[1] on net BVALIDmi2si[1] has its enable tied to GND (module SMC_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver BVALIDmi2si_t[1] on net BVALIDmi2si[1] has its enable tied to GND (module default_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver BVALIDmi32si_t[1] on net BVALIDmi32si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver BVALIDmi42si_t[1] on net BVALIDmi42si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver BVALIDmi52si_t[1] on net BVALIDmi52si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver RLASTmi12si_t[1] on net RLASTmi12si[1] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver RLASTmi22si_t[1] on net RLASTmi22si[1] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver RLASTmi2si_t[1] on net RLASTmi2si[1] has its enable tied to GND (module APB0_RS_ReadChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver RLASTmi2si_t[1] on net RLASTmi2si[1] has its enable tied to GND (module APB1_RS_ReadChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver RREADYsi12mi_t[1] on net RREADYsi12mi[1] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver RREADYsi12mi_t[2] on net RREADYsi12mi[2] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver RREADYsi2mi_t[1] on net RREADYsi2mi[1] has its enable tied to GND (module VideoEnC_RS_ReadChannelsi) 
@W: MO111 :"":0:0:0:-1|tristate driver RREADYsi2mi_t[2] on net RREADYsi2mi[2] has its enable tied to GND (module VideoEnC_RS_ReadChannelsi) 
@W: MO111 :"":0:0:0:-1|tristate driver RVALIDmi12si_t[1] on net RVALIDmi12si[1] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver RVALIDmi22si_t[1] on net RVALIDmi22si[1] has its enable tied to GND (module ReadChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver RVALIDmi2si_t[1] on net RVALIDmi2si[1] has its enable tied to GND (module APB0_RS_ReadChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver RVALIDmi2si_t[1] on net RVALIDmi2si[1] has its enable tied to GND (module APB1_RS_ReadChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver WREADYmi02si_t[1] on net WREADYmi02si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver WREADYmi12si_t[1] on net WREADYmi12si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver WREADYmi22si_t[1] on net WREADYmi22si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver WREADYmi2si_t[1] on net WREADYmi2si[1] has its enable tied to GND (module APB0_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver WREADYmi2si_t[1] on net WREADYmi2si[1] has its enable tied to GND (module APB1_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver WREADYmi2si_t[1] on net WREADYmi2si[1] has its enable tied to GND (module DDRCtrl_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver WREADYmi2si_t[1] on net WREADYmi2si[1] has its enable tied to GND (module IntSRAM_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver WREADYmi2si_t[1] on net WREADYmi2si[1] has its enable tied to GND (module SMC_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver WREADYmi2si_t[1] on net WREADYmi2si[1] has its enable tied to GND (module default_RS_WriteChannelmi) 
@W: MO111 :"":0:0:0:-1|tristate driver WREADYmi32si_t[1] on net WREADYmi32si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver WREADYmi42si_t[1] on net WREADYmi42si[1] has its enable tied to GND (module WriteChannel) 
@W: MO111 :"":0:0:0:-1|tristate driver WREADYmi52si_t[1] on net WREADYmi52si[1] has its enable tied to GND (module WriteChannel) 
@N: MT207 :"":0:0:0:-1|Found clock with name Clock. Because one or more clocks are defined in SDC file, Autoconstrain mode is TURNED OFF
@N: CD720 :"c:\program files\synplicity\fpga_862\lib\vhd\std.vhd":123:18:123:21|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\model\ssram32bit.v":17:7:17:16|Synthesizing module SSRAM32bit
@N: CG364 :"d:\data\ntsc_pal\testplatform3\model\ssram8bit.v":17:7:17:15|Synthesizing module SSRAM8bit
@N: CL134 :"d:\data\ntsc_pal\testplatform3\model\ssram8bit.v":44:0:44:5|M
@N: MF174 :"d:\data\ntsc_pal\testplatform3\model\ssram8bit.v":44:0:44:5|M
@W: MF186 :"d:\data\ntsc_pal\testplatform3\model\ssram8bit.v":44:0:44:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_lockctlrdmi.v":17:8:17:23|Synthesizing module APB0_LockCtlRdmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_lockctlrdmi.v":86:34:86:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":20:8:20:25|Synthesizing module APB0_ReadChannelmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":173:32:173:43|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":185:32:185:42|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":228:4:228:7|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":229:19:229:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":229:33:229:41|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":268:24:268:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":268:38:268:46|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":289:31:289:42|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":299:3:299:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":300:14:300:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":300:28:300:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":318:8:318:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":319:24:319:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":319:38:319:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":332:8:332:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":333:24:333:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":333:38:333:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":346:8:346:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":347:24:347:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":347:38:347:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":360:8:360:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":361:24:361:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":361:38:361:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":374:8:374:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":375:24:375:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":375:38:375:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":388:8:388:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":389:24:389:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":389:38:389:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":402:8:402:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":403:24:403:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":403:38:403:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":416:8:416:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":417:24:417:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":417:38:417:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":435:8:435:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":436:24:436:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":436:38:436:46|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":450:28:450:38|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":451:28:451:37|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":469:8:469:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":470:24:470:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":470:38:470:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":482:3:482:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":483:14:483:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":483:28:483:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":501:3:501:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":502:14:502:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":502:28:502:36|M
@W: CL157 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":546:0:546:12|M
@W: MO111 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_readchannelmi.v":546:0:546:12|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_reqcnt.v":17:8:17:18|Synthesizing module APB0_ReqCnt
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_reqcnt.v":91:23:91:25|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_rs_readchannelmi.v":19:8:19:28|Synthesizing module APB0_RS_ReadChannelmi
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_rs_readchannelmi.v":151:31:151:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_rs_readchannelmi.v":152:31:152:43|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_rs_readchannelmi.v":153:31:153:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_rs_readchannelmi.v":191:12:191:19|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_rs_readchannelmi.v":192:12:192:24|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_rs_readchannelmi.v":193:20:193:30|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_rs_readchannelmi.v":210:30:210:41|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_rs_readchannelmi.v":212:30:212:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb0_rs_readchannelmi.v":214:30:214:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_lockctlrdmi.v":17:8:17:23|Synthesizing module APB1_LockCtlRdmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_lockctlrdmi.v":86:34:86:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":20:8:20:25|Synthesizing module APB1_ReadChannelmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":173:32:173:43|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":185:32:185:42|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":228:4:228:7|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":229:19:229:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":229:33:229:41|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":268:24:268:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":268:38:268:46|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":289:31:289:42|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":299:3:299:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":300:14:300:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":300:28:300:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":318:8:318:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":319:24:319:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":319:38:319:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":332:8:332:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":333:24:333:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":333:38:333:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":346:8:346:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":347:24:347:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":347:38:347:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":360:8:360:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":361:24:361:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":361:38:361:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":374:8:374:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":375:24:375:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":375:38:375:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":388:8:388:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":389:24:389:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":389:38:389:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":402:8:402:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":403:24:403:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":403:38:403:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":416:8:416:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":417:24:417:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":417:38:417:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":435:8:435:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":436:24:436:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":436:38:436:46|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":450:28:450:38|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":451:28:451:37|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":469:8:469:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":470:24:470:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":470:38:470:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":482:3:482:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":483:14:483:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":483:28:483:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":501:3:501:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":502:14:502:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":502:28:502:36|M
@W: CL157 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":546:0:546:12|M
@W: MO111 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_readchannelmi.v":546:0:546:12|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_reqcnt.v":17:8:17:18|Synthesizing module APB1_ReqCnt
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_reqcnt.v":91:23:91:25|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_rs_readchannelmi.v":19:8:19:28|Synthesizing module APB1_RS_ReadChannelmi
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_rs_readchannelmi.v":151:31:151:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_rs_readchannelmi.v":152:31:152:43|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_rs_readchannelmi.v":153:31:153:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_rs_readchannelmi.v":191:12:191:19|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_rs_readchannelmi.v":192:12:192:24|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_rs_readchannelmi.v":193:20:193:30|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_rs_readchannelmi.v":210:30:210:41|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_rs_readchannelmi.v":212:30:212:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\apb1_rs_readchannelmi.v":214:30:214:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":17:8:17:24|Synthesizing module ARM_ReadChannelsi
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":456:8:456:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":457:19:457:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":457:33:457:41|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":533:8:533:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":534:20:534:32|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":534:34:534:42|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":633:4:633:7|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":634:19:634:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":634:33:634:41|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":669:3:669:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":670:14:670:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":670:28:670:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":739:8:739:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":740:24:740:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":740:38:740:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":762:8:762:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":763:24:763:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":763:38:763:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":785:8:785:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":786:24:786:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":786:38:786:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":803:8:803:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":804:24:804:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":804:38:804:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":821:8:821:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":822:24:822:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_readchannelsi.v":822:38:822:46|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_rs_readchannelsi.v":17:8:17:27|Synthesizing module ARM_RS_ReadChannelsi
@W: CL157 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_rs_readchannelsi.v":306:30:306:42|M
@W: MO111 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_rs_readchannelsi.v":306:30:306:42|M
@W: CL157 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_rs_readchannelsi.v":308:29:308:40|M
@W: MO111 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_rs_readchannelsi.v":308:29:308:40|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_rs_readchannelsi.v":376:30:376:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\arm_rs_readchannelsi.v":377:30:377:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_lockctlrdmi.v":17:8:17:26|Synthesizing module DDRCtrl_LockCtlRdmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_lockctlrdmi.v":86:34:86:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":20:8:20:28|Synthesizing module DDRCtrl_ReadChannelmi
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":259:4:259:7|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":260:19:260:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":260:33:260:41|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":302:24:302:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":302:38:302:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":338:3:338:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":339:14:339:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":339:28:339:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":364:8:364:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":365:24:365:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":365:38:365:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":380:8:380:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":381:24:381:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":381:38:381:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":396:8:396:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":397:24:397:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":397:38:397:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":412:8:412:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":413:24:413:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":413:38:413:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":428:8:428:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":429:24:429:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":429:38:429:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":444:8:444:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":445:24:445:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":445:38:445:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":460:8:460:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":461:24:461:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":461:38:461:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":476:8:476:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":477:24:477:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":477:38:477:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":497:8:497:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":498:24:498:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":498:38:498:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":541:8:541:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":542:24:542:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":542:38:542:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":555:3:555:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":556:14:556:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":556:28:556:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":581:3:581:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":582:14:582:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_readchannelmi.v":582:28:582:36|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_reqcnt.v":17:8:17:21|Synthesizing module DDRCtrl_ReqCnt
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_reqcnt.v":82:4:82:9|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_reqcnt.v":91:23:91:25|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_rs_readchannelmi.v":19:8:19:31|Synthesizing module DDRCtrl_RS_ReadChannelmi
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_rs_readchannelmi.v":166:31:166:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_rs_readchannelmi.v":167:31:167:43|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_rs_readchannelmi.v":168:31:168:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_rs_readchannelmi.v":178:31:178:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_rs_readchannelmi.v":179:31:179:43|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_rs_readchannelmi.v":180:31:180:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_rs_readchannelmi.v":222:12:222:19|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_rs_readchannelmi.v":223:12:223:24|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_rs_readchannelmi.v":224:20:224:30|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_rs_readchannelmi.v":241:30:241:41|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_rs_readchannelmi.v":243:30:243:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\ddrctrl_rs_readchannelmi.v":245:30:245:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_lockctlrdmi.v":17:8:17:26|Synthesizing module default_LockCtlRdmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_lockctlrdmi.v":86:34:86:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":20:8:20:28|Synthesizing module default_ReadChannelmi
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":259:4:259:7|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":260:19:260:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":260:33:260:41|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":302:24:302:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":302:38:302:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":338:3:338:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":339:14:339:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":339:28:339:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":364:8:364:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":365:24:365:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":365:38:365:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":380:8:380:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":381:24:381:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":381:38:381:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":396:8:396:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":397:24:397:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":397:38:397:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":412:8:412:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":413:24:413:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":413:38:413:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":428:8:428:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":429:24:429:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":429:38:429:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":444:8:444:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":445:24:445:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":445:38:445:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":460:8:460:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":461:24:461:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":461:38:461:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":476:8:476:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":477:24:477:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":477:38:477:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":497:8:497:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":498:24:498:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":498:38:498:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":541:8:541:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":542:24:542:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":542:38:542:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":555:3:555:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":556:14:556:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":556:28:556:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":581:3:581:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":582:14:582:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_readchannelmi.v":582:28:582:36|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_reqcnt.v":17:8:17:21|Synthesizing module default_ReqCnt
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_reqcnt.v":82:4:82:9|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_reqcnt.v":91:23:91:25|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_rs_readchannelmi.v":19:8:19:31|Synthesizing module default_RS_ReadChannelmi
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_rs_readchannelmi.v":166:31:166:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_rs_readchannelmi.v":167:31:167:43|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_rs_readchannelmi.v":168:31:168:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_rs_readchannelmi.v":178:31:178:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_rs_readchannelmi.v":179:31:179:43|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_rs_readchannelmi.v":180:31:180:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_rs_readchannelmi.v":222:12:222:19|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_rs_readchannelmi.v":223:12:223:24|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_rs_readchannelmi.v":224:20:224:30|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_rs_readchannelmi.v":241:30:241:41|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_rs_readchannelmi.v":243:30:243:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\default_rs_readchannelmi.v":245:30:245:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_lockctlrdmi.v":17:8:17:26|Synthesizing module IntSRAM_LockCtlRdmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_lockctlrdmi.v":86:34:86:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":20:8:20:28|Synthesizing module IntSRAM_ReadChannelmi
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":259:4:259:7|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":260:19:260:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":260:33:260:41|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":302:24:302:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":302:38:302:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":338:3:338:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":339:14:339:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":339:28:339:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":364:8:364:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":365:24:365:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":365:38:365:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":380:8:380:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":381:24:381:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":381:38:381:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":396:8:396:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":397:24:397:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":397:38:397:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":412:8:412:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":413:24:413:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":413:38:413:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":428:8:428:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":429:24:429:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":429:38:429:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":444:8:444:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":445:24:445:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":445:38:445:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":460:8:460:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":461:24:461:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":461:38:461:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":476:8:476:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":477:24:477:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":477:38:477:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":497:8:497:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":498:24:498:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":498:38:498:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":541:8:541:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":542:24:542:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":542:38:542:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":555:3:555:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":556:14:556:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":556:28:556:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":581:3:581:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":582:14:582:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_readchannelmi.v":582:28:582:36|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_reqcnt.v":17:8:17:21|Synthesizing module IntSRAM_ReqCnt
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_reqcnt.v":91:23:91:25|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_rs_readchannelmi.v":19:8:19:31|Synthesizing module IntSRAM_RS_ReadChannelmi
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_rs_readchannelmi.v":166:31:166:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_rs_readchannelmi.v":167:31:167:43|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_rs_readchannelmi.v":168:31:168:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_rs_readchannelmi.v":178:31:178:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_rs_readchannelmi.v":179:31:179:43|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_rs_readchannelmi.v":180:31:180:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_rs_readchannelmi.v":222:12:222:19|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_rs_readchannelmi.v":223:12:223:24|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_rs_readchannelmi.v":224:20:224:30|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_rs_readchannelmi.v":241:30:241:41|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_rs_readchannelmi.v":243:30:243:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\intsram_rs_readchannelmi.v":245:30:245:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_arm_permitctl.v":18:8:18:25|Synthesizing module RDCH_ARM_PermitCtl
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_arm_permitctl.v":124:15:124:27|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_arm_permitctl.v":124:29:124:37|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_arm_permitctl.v":138:15:138:27|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_arm_permitctl.v":138:29:138:37|M
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_arm_permitctl.v":163:0:163:5|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_arm_permitctl.v":212:27:212:37|M
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_arm_permitctl.v":221:0:221:5|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_arm_permitctl.v":230:27:230:37|M
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_arm_permitctl.v":281:0:281:5|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_arm_permitctl.v":340:15:340:27|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_arm_permitctl.v":340:29:340:37|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_arm_permitctl.v":354:15:354:27|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_arm_permitctl.v":354:29:354:37|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_videoenc_permitctl.v":18:8:18:30|Synthesizing module RDCH_VideoEnC_PermitCtl
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_videoenc_permitctl.v":124:15:124:27|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_videoenc_permitctl.v":124:29:124:37|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_videoenc_permitctl.v":138:15:138:27|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_videoenc_permitctl.v":138:29:138:37|M
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_videoenc_permitctl.v":163:0:163:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_videoenc_permitctl.v":203:0:203:5|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_videoenc_permitctl.v":212:27:212:37|M
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_videoenc_permitctl.v":221:0:221:5|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_videoenc_permitctl.v":230:27:230:37|M
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_videoenc_permitctl.v":281:0:281:5|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_videoenc_permitctl.v":340:15:340:27|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_videoenc_permitctl.v":340:29:340:37|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_videoenc_permitctl.v":354:15:354:27|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\rdch_videoenc_permitctl.v":354:29:354:37|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\apb0_armimi2s_registered.v":20:7:20:30|Synthesizing module APB0_ARMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\apb0_rdmimi2s_registered.v":20:7:20:30|Synthesizing module APB0_RDMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\apb1_armimi2s_registered.v":20:7:20:30|Synthesizing module APB1_ARMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\apb1_rdmimi2s_registered.v":20:7:20:30|Synthesizing module APB1_RDMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\arm_arsim2si_registered.v":20:7:20:29|Synthesizing module ARM_ARSIm2si_registered
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\arm_arsim2si_registered.v":77:0:77:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\arm_rdsim2si_registered.v":20:7:20:29|Synthesizing module ARM_RDSIm2si_registered
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\arm_rdsim2si_registered.v":77:0:77:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\ddrctrl_armimi2s_registered.v":20:7:20:33|Synthesizing module DDRCtrl_ARMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\ddrctrl_rdmimi2s_registered.v":20:7:20:33|Synthesizing module DDRCtrl_RDMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\default_armimi2s_registered.v":20:7:20:33|Synthesizing module default_ARMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\default_rdmimi2s_registered.v":20:7:20:33|Synthesizing module default_RDMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\intsram_armimi2s_registered.v":20:7:20:33|Synthesizing module IntSRAM_ARMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\intsram_rdmimi2s_registered.v":20:7:20:33|Synthesizing module IntSRAM_RDMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\smc_armimi2s_registered.v":20:7:20:29|Synthesizing module SMC_ARMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\smc_rdmimi2s_registered.v":20:7:20:29|Synthesizing module SMC_RDMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\videoenc_arsim2si_registered.v":20:7:20:34|Synthesizing module VideoEnC_ARSIm2si_registered
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\videoenc_arsim2si_registered.v":77:0:77:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\videoenc_rdsim2si_registered.v":20:7:20:34|Synthesizing module VideoEnC_RDSIm2si_registered
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\registerslice\videoenc_rdsim2si_registered.v":77:0:77:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_lockctlrdmi.v":17:8:17:22|Synthesizing module SMC_LockCtlRdmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_lockctlrdmi.v":86:34:86:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":20:8:20:24|Synthesizing module SMC_ReadChannelmi
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":259:4:259:7|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":260:19:260:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":260:33:260:41|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":302:24:302:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":302:38:302:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":338:3:338:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":339:14:339:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":339:28:339:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":364:8:364:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":365:24:365:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":365:38:365:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":380:8:380:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":381:24:381:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":381:38:381:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":396:8:396:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":397:24:397:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":397:38:397:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":412:8:412:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":413:24:413:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":413:38:413:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":428:8:428:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":429:24:429:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":429:38:429:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":444:8:444:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":445:24:445:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":445:38:445:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":460:8:460:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":461:24:461:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":461:38:461:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":476:8:476:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":477:24:477:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":477:38:477:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":497:8:497:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":498:24:498:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":498:38:498:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":541:8:541:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":542:24:542:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":542:38:542:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":555:3:555:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":556:14:556:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":556:28:556:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":581:3:581:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":582:14:582:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_readchannelmi.v":582:28:582:36|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_reqcnt.v":17:8:17:17|Synthesizing module SMC_ReqCnt
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_reqcnt.v":91:23:91:25|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_rs_readchannelmi.v":19:8:19:27|Synthesizing module SMC_RS_ReadChannelmi
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_rs_readchannelmi.v":166:31:166:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_rs_readchannelmi.v":167:31:167:43|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_rs_readchannelmi.v":168:31:168:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_rs_readchannelmi.v":178:31:178:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_rs_readchannelmi.v":179:31:179:43|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_rs_readchannelmi.v":180:31:180:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_rs_readchannelmi.v":222:12:222:19|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_rs_readchannelmi.v":223:12:223:24|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_rs_readchannelmi.v":224:20:224:30|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_rs_readchannelmi.v":241:30:241:41|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_rs_readchannelmi.v":243:30:243:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\smc_rs_readchannelmi.v":245:30:245:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":18:8:18:18|Synthesizing module ReadChannel
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":338:13:338:22|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":353:13:353:22|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":368:13:368:22|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":383:13:383:22|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":398:13:398:22|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":413:13:413:22|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":638:14:638:31|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":653:14:653:31|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":668:14:668:31|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":683:14:683:31|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":698:14:698:31|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":713:14:713:31|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":728:14:728:31|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":743:14:743:31|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":758:14:758:31|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\top\readchannel.v":773:14:773:31|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":17:8:17:29|Synthesizing module VideoEnC_ReadChannelsi
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":260:27:260:38|M
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":294:28:294:38|M
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":295:28:295:37|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":347:19:347:30|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":356:8:356:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":357:19:357:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":357:33:357:41|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":405:8:405:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":406:20:406:32|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":406:34:406:42|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":472:24:472:34|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":487:4:487:7|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":488:19:488:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":488:33:488:41|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":519:3:519:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":520:14:520:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":520:28:520:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":561:8:561:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":562:24:562:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":562:38:562:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":580:8:580:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":581:24:581:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":581:38:581:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":599:8:599:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":600:24:600:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":600:38:600:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":615:8:615:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":616:24:616:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":616:38:616:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":631:8:631:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":632:24:632:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":632:38:632:46|M
@W: CL157 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":642:4:642:14|M
@W: MO111 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_readchannelsi.v":642:4:642:14|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_rs_readchannelsi.v":17:8:17:32|Synthesizing module VideoEnC_RS_ReadChannelsi
@W: CL157 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_rs_readchannelsi.v":240:29:240:40|M
@W: MO111 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_rs_readchannelsi.v":240:29:240:40|M
@W: CL157 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_rs_readchannelsi.v":242:30:242:42|M
@W: MO111 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_rs_readchannelsi.v":242:30:242:42|M
@W: CL157 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_rs_readchannelsi.v":244:29:244:40|M
@W: MO111 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_rs_readchannelsi.v":244:29:244:40|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_rs_readchannelsi.v":297:30:297:41|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_rs_readchannelsi.v":298:30:298:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\readchannel\videoenc_rs_readchannelsi.v":299:30:299:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":20:7:20:10|Synthesizing module SBUS
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":910:11:910:20|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":929:11:929:20|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":948:11:948:20|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":967:11:967:20|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":986:11:986:20|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1005:11:1005:20|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1028:12:1028:24|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1104:12:1104:23|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1108:12:1108:24|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1180:12:1180:23|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1184:12:1184:24|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1257:12:1257:23|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1260:12:1260:24|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1333:12:1333:23|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1336:12:1336:24|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1409:12:1409:23|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1412:12:1412:24|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1485:12:1485:23|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1488:12:1488:24|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1561:12:1561:23|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1564:12:1564:24|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1637:12:1637:23|M
@W: CL156 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1644:0:1644:16|M
@W: CL156 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\top\sbus.v":1938:0:1938:15|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_lockctlwrmi.v":17:8:17:23|Synthesizing module APB0_LockCtlWrmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_lockctlwrmi.v":86:34:86:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_reqinter.v":17:8:17:24|Synthesizing module APB0_ReqInterBuff
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_reqinter.v":145:27:145:33|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_reqinter.v":165:28:165:35|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_rs_writechannelmi.v":20:8:20:29|Synthesizing module APB0_RS_WriteChannelmi
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_rs_writechannelmi.v":180:31:180:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_rs_writechannelmi.v":181:31:181:43|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_rs_writechannelmi.v":182:31:182:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_rs_writechannelmi.v":187:27:187:37|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_rs_writechannelmi.v":239:30:239:41|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_rs_writechannelmi.v":241:30:241:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_rs_writechannelmi.v":243:30:243:41|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_rs_writechannelmi.v":252:30:252:40|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":21:8:21:26|Synthesizing module APB0_WriteChannelmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":211:28:211:39|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":214:28:214:37|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":215:28:215:38|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":225:29:225:39|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":273:4:273:7|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":274:19:274:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":274:33:274:41|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":310:24:310:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":310:38:310:46|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":331:30:331:41|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":348:3:348:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":349:14:349:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":349:28:349:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":371:8:371:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":372:24:372:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":372:38:372:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":385:8:385:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":386:24:386:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":386:38:386:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":401:8:401:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":402:24:402:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":402:38:402:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":415:8:415:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":416:24:416:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":416:38:416:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":429:8:429:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":430:24:430:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":430:38:430:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":443:8:443:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":444:24:444:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":444:38:444:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":458:8:458:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":459:24:459:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":459:38:459:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":472:8:472:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":473:24:473:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":473:38:473:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":487:8:487:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":488:24:488:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":488:38:488:46|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":508:29:508:39|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":544:3:544:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":545:14:545:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":545:28:545:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":564:8:564:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":565:23:565:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":578:8:578:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":579:23:579:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":592:8:592:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":593:23:593:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":606:8:606:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":607:23:607:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":620:8:620:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":621:23:621:31|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":634:27:634:37|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":641:8:641:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":642:23:642:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":653:3:653:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":654:14:654:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":654:28:654:36|M
@W: CL157 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":698:0:698:12|M
@W: MO111 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb0_writechannelmi.v":698:0:698:12|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_lockctlwrmi.v":17:8:17:23|Synthesizing module APB1_LockCtlWrmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_lockctlwrmi.v":86:34:86:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_reqinter.v":17:8:17:24|Synthesizing module APB1_ReqInterBuff
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_reqinter.v":145:27:145:33|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_reqinter.v":165:28:165:35|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_rs_writechannelmi.v":20:8:20:29|Synthesizing module APB1_RS_WriteChannelmi
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_rs_writechannelmi.v":180:31:180:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_rs_writechannelmi.v":181:31:181:43|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_rs_writechannelmi.v":182:31:182:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_rs_writechannelmi.v":187:27:187:37|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_rs_writechannelmi.v":239:30:239:41|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_rs_writechannelmi.v":241:30:241:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_rs_writechannelmi.v":243:30:243:41|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_rs_writechannelmi.v":252:30:252:40|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":21:8:21:26|Synthesizing module APB1_WriteChannelmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":211:28:211:39|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":214:28:214:37|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":215:28:215:38|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":225:29:225:39|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":273:4:273:7|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":274:19:274:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":274:33:274:41|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":310:24:310:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":310:38:310:46|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":331:30:331:41|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":348:3:348:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":349:14:349:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":349:28:349:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":371:8:371:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":372:24:372:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":372:38:372:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":385:8:385:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":386:24:386:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":386:38:386:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":401:8:401:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":402:24:402:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":402:38:402:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":415:8:415:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":416:24:416:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":416:38:416:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":429:8:429:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":430:24:430:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":430:38:430:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":443:8:443:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":444:24:444:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":444:38:444:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":458:8:458:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":459:24:459:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":459:38:459:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":472:8:472:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":473:24:473:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":473:38:473:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":487:8:487:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":488:24:488:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":488:38:488:46|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":508:29:508:39|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":544:3:544:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":545:14:545:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":545:28:545:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":564:8:564:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":565:23:565:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":578:8:578:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":579:23:579:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":592:8:592:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":593:23:593:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":606:8:606:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":607:23:607:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":620:8:620:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":621:23:621:31|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":634:27:634:37|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":641:8:641:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":642:23:642:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":653:3:653:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":654:14:654:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":654:28:654:36|M
@W: CL157 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":698:0:698:12|M
@W: MO111 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\apb1_writechannelmi.v":698:0:698:12|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_rs_writechannelsi.v":17:8:17:28|Synthesizing module ARM_RS_WriteChannelsi
@W: CL157 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_rs_writechannelsi.v":343:30:343:42|M
@W: MO111 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_rs_writechannelsi.v":343:30:343:42|M
@W: CL157 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_rs_writechannelsi.v":345:29:345:40|M
@W: MO111 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_rs_writechannelsi.v":345:29:345:40|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_rs_writechannelsi.v":403:30:403:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_rs_writechannelsi.v":404:30:404:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":17:8:17:25|Synthesizing module ARM_WriteChannelsi
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":416:28:416:35|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":417:23:417:32|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":418:24:418:33|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":521:8:521:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":522:19:522:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":522:33:522:41|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":598:8:598:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":599:23:599:35|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":599:37:599:45|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":691:8:691:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":692:19:692:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":692:33:692:41|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":767:8:767:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":768:19:768:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":768:33:768:41|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":844:8:844:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":845:23:845:35|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":845:37:845:45|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":884:4:884:7|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":885:19:885:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":885:33:885:41|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":920:3:920:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":921:14:921:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\arm_writechannelsi.v":921:28:921:36|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_lockctlwrmi.v":17:8:17:26|Synthesizing module DDRCtrl_LockCtlWrmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_lockctlwrmi.v":86:34:86:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_reqinter.v":17:8:17:27|Synthesizing module DDRCtrl_ReqInterBuff
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_reqinter.v":187:27:187:33|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_reqinter.v":207:28:207:35|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_rs_writechannelmi.v":20:8:20:32|Synthesizing module DDRCtrl_RS_WriteChannelmi
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_rs_writechannelmi.v":182:31:182:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_rs_writechannelmi.v":183:31:183:43|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_rs_writechannelmi.v":184:31:184:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_rs_writechannelmi.v":241:30:241:41|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_rs_writechannelmi.v":243:30:243:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_rs_writechannelmi.v":245:30:245:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":21:8:21:29|Synthesizing module DDRCtrl_WriteChannelmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":211:28:211:39|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":214:28:214:37|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":215:28:215:38|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":225:29:225:39|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":273:4:273:7|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":274:19:274:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":274:33:274:41|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":310:24:310:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":310:38:310:46|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":331:30:331:41|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":348:3:348:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":349:14:349:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":349:28:349:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":371:8:371:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":372:24:372:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":372:38:372:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":385:8:385:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":386:24:386:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":386:38:386:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":401:8:401:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":402:24:402:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":402:38:402:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":415:8:415:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":416:24:416:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":416:38:416:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":429:8:429:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":430:24:430:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":430:38:430:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":443:8:443:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":444:24:444:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":444:38:444:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":458:8:458:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":459:24:459:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":459:38:459:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":472:8:472:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":473:24:473:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":473:38:473:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":487:8:487:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":488:24:488:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":488:38:488:46|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":508:29:508:39|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":544:3:544:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":545:14:545:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":545:28:545:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":564:8:564:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":565:23:565:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":578:8:578:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":579:23:579:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":592:8:592:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":593:23:593:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":606:8:606:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":607:23:607:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":620:8:620:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":621:23:621:31|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":634:27:634:37|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":641:8:641:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":642:23:642:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":653:3:653:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":654:14:654:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":654:28:654:36|M
@W: CL157 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":698:0:698:12|M
@W: MO111 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\ddrctrl_writechannelmi.v":698:0:698:12|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_lockctlwrmi.v":17:8:17:26|Synthesizing module default_LockCtlWrmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_lockctlwrmi.v":86:34:86:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_reqinter.v":17:8:17:27|Synthesizing module default_ReqInterBuff
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_reqinter.v":187:27:187:33|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_reqinter.v":207:28:207:35|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_rs_writechannelmi.v":20:8:20:32|Synthesizing module default_RS_WriteChannelmi
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_rs_writechannelmi.v":182:31:182:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_rs_writechannelmi.v":183:31:183:43|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_rs_writechannelmi.v":184:31:184:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_rs_writechannelmi.v":241:30:241:41|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_rs_writechannelmi.v":243:30:243:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_rs_writechannelmi.v":245:30:245:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":21:8:21:29|Synthesizing module default_WriteChannelmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":211:28:211:39|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":214:28:214:37|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":215:28:215:38|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":225:29:225:39|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":273:4:273:7|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":274:19:274:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":274:33:274:41|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":310:24:310:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":310:38:310:46|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":331:30:331:41|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":348:3:348:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":349:14:349:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":349:28:349:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":371:8:371:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":372:24:372:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":372:38:372:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":385:8:385:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":386:24:386:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":386:38:386:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":401:8:401:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":402:24:402:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":402:38:402:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":415:8:415:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":416:24:416:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":416:38:416:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":429:8:429:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":430:24:430:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":430:38:430:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":443:8:443:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":444:24:444:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":444:38:444:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":458:8:458:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":459:24:459:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":459:38:459:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":472:8:472:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":473:24:473:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":473:38:473:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":487:8:487:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":488:24:488:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":488:38:488:46|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":508:29:508:39|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":544:3:544:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":545:14:545:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":545:28:545:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":564:8:564:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":565:23:565:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":578:8:578:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":579:23:579:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":592:8:592:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":593:23:593:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":606:8:606:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":607:23:607:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":620:8:620:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":621:23:621:31|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":634:27:634:37|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":641:8:641:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":642:23:642:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":653:3:653:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":654:14:654:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":654:28:654:36|M
@W: CL157 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":698:0:698:12|M
@W: MO111 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\default_writechannelmi.v":698:0:698:12|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_lockctlwrmi.v":17:8:17:26|Synthesizing module IntSRAM_LockCtlWrmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_lockctlwrmi.v":86:34:86:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_reqinter.v":17:8:17:27|Synthesizing module IntSRAM_ReqInterBuff
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_reqinter.v":151:27:151:33|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_reqinter.v":171:28:171:35|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_rs_writechannelmi.v":20:8:20:32|Synthesizing module IntSRAM_RS_WriteChannelmi
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_rs_writechannelmi.v":182:31:182:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_rs_writechannelmi.v":183:31:183:43|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_rs_writechannelmi.v":184:31:184:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_rs_writechannelmi.v":241:30:241:41|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_rs_writechannelmi.v":243:30:243:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_rs_writechannelmi.v":245:30:245:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":21:8:21:29|Synthesizing module IntSRAM_WriteChannelmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":211:28:211:39|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":214:28:214:37|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":215:28:215:38|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":225:29:225:39|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":273:4:273:7|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":274:19:274:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":274:33:274:41|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":310:24:310:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":310:38:310:46|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":331:30:331:41|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":348:3:348:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":349:14:349:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":349:28:349:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":371:8:371:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":372:24:372:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":372:38:372:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":385:8:385:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":386:24:386:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":386:38:386:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":401:8:401:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":402:24:402:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":402:38:402:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":415:8:415:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":416:24:416:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":416:38:416:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":429:8:429:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":430:24:430:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":430:38:430:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":443:8:443:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":444:24:444:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":444:38:444:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":458:8:458:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":459:24:459:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":459:38:459:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":472:8:472:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":473:24:473:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":473:38:473:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":487:8:487:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":488:24:488:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":488:38:488:46|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":508:29:508:39|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":544:3:544:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":545:14:545:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":545:28:545:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":564:8:564:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":565:23:565:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":578:8:578:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":579:23:579:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":592:8:592:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":593:23:593:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":606:8:606:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":607:23:607:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":620:8:620:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":621:23:621:31|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":634:27:634:37|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":641:8:641:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":642:23:642:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":653:3:653:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":654:14:654:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":654:28:654:36|M
@W: CL157 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":698:0:698:12|M
@W: MO111 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\intsram_writechannelmi.v":698:0:698:12|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\apb0_awmimi2s_registered.v":20:7:20:30|Synthesizing module APB0_AWMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\apb0_wdmimi2s_registered.v":20:7:20:30|Synthesizing module APB0_WDMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\apb0_wrmimi2s_registered.v":20:7:20:30|Synthesizing module APB0_WRMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\apb1_awmimi2s_registered.v":20:7:20:30|Synthesizing module APB1_AWMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\apb1_wdmimi2s_registered.v":20:7:20:30|Synthesizing module APB1_WDMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\apb1_wrmimi2s_registered.v":20:7:20:30|Synthesizing module APB1_WRMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\arm_awsim2si_registered.v":20:7:20:29|Synthesizing module ARM_AWSIm2si_registered
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\arm_awsim2si_registered.v":77:0:77:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\arm_wdsim2si_registered.v":20:7:20:29|Synthesizing module ARM_WDSIm2si_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\arm_wrsim2si_registered.v":20:7:20:29|Synthesizing module ARM_WRSIm2si_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\ddrctrl_awmimi2s_registered.v":20:7:20:33|Synthesizing module DDRCtrl_AWMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\ddrctrl_wdmimi2s_registered.v":20:7:20:33|Synthesizing module DDRCtrl_WDMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\ddrctrl_wrmimi2s_registered.v":20:7:20:33|Synthesizing module DDRCtrl_WRMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\default_awmimi2s_registered.v":20:7:20:33|Synthesizing module default_AWMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\default_wdmimi2s_registered.v":20:7:20:33|Synthesizing module default_WDMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\default_wrmimi2s_registered.v":20:7:20:33|Synthesizing module default_WRMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\intsram_awmimi2s_registered.v":20:7:20:33|Synthesizing module IntSRAM_AWMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\intsram_wdmimi2s_registered.v":20:7:20:33|Synthesizing module IntSRAM_WDMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\intsram_wrmimi2s_registered.v":20:7:20:33|Synthesizing module IntSRAM_WRMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\smc_awmimi2s_registered.v":20:7:20:29|Synthesizing module SMC_AWMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\smc_wdmimi2s_registered.v":20:7:20:29|Synthesizing module SMC_WDMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\registerslice\smc_wrmimi2s_registered.v":20:7:20:29|Synthesizing module SMC_WRMImi2s_registered
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_lockctlwrmi.v":17:8:17:22|Synthesizing module SMC_LockCtlWrmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_lockctlwrmi.v":86:34:86:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_reqinter.v":17:8:17:23|Synthesizing module SMC_ReqInterBuff
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_reqinter.v":151:27:151:33|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_reqinter.v":171:28:171:35|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_rs_writechannelmi.v":20:8:20:28|Synthesizing module SMC_RS_WriteChannelmi
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_rs_writechannelmi.v":182:31:182:42|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_rs_writechannelmi.v":183:31:183:43|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_rs_writechannelmi.v":184:31:184:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_rs_writechannelmi.v":241:30:241:41|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_rs_writechannelmi.v":243:30:243:42|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_rs_writechannelmi.v":245:30:245:41|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":21:8:21:25|Synthesizing module SMC_WriteChannelmi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":211:28:211:39|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":214:28:214:37|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":215:28:215:38|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":225:29:225:39|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":273:4:273:7|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":274:19:274:31|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":274:33:274:41|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":310:24:310:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":310:38:310:46|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":331:30:331:41|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":348:3:348:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":349:14:349:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":349:28:349:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":371:8:371:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":372:24:372:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":372:38:372:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":385:8:385:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":386:24:386:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":386:38:386:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":401:8:401:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":402:24:402:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":402:38:402:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":415:8:415:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":416:24:416:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":416:38:416:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":429:8:429:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":430:24:430:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":430:38:430:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":443:8:443:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":444:24:444:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":444:38:444:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":458:8:458:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":459:24:459:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":459:38:459:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":472:8:472:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":473:24:473:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":473:38:473:46|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":487:8:487:11|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":488:24:488:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":488:38:488:46|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":508:29:508:39|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":544:3:544:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":545:14:545:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":545:28:545:36|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":564:8:564:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":565:23:565:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":578:8:578:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":579:23:579:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":592:8:592:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":593:23:593:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":606:8:606:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":607:23:607:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":620:8:620:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":621:23:621:31|M
@W: CG134 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":634:27:634:37|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":641:8:641:11|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":642:23:642:31|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":653:3:653:6|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":654:14:654:26|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":654:28:654:36|M
@W: CL157 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":698:0:698:12|M
@W: MO111 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\smc_writechannelmi.v":698:0:698:12|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\top\writechannel.v":18:8:18:19|Synthesizing module WriteChannel
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\top\writechannel.v":672:15:672:32|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\top\writechannel.v":683:15:683:32|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\top\writechannel.v":693:15:693:32|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\top\writechannel.v":704:15:704:32|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\top\writechannel.v":714:15:714:32|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\top\writechannel.v":725:15:725:32|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\top\writechannel.v":735:15:735:32|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\top\writechannel.v":746:15:746:32|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\top\writechannel.v":756:15:756:32|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\top\writechannel.v":767:15:767:32|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\top\writechannel.v":777:15:777:32|M
@W: CG390 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\top\writechannel.v":788:15:788:32|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\wrch_arm_permitctl.v":18:8:18:25|Synthesizing module WRCH_ARM_PermitCtl
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\wrch_arm_permitctl.v":124:15:124:27|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\wrch_arm_permitctl.v":124:29:124:37|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\wrch_arm_permitctl.v":138:15:138:27|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\wrch_arm_permitctl.v":138:29:138:37|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\wrch_arm_permitctl.v":212:27:212:37|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\wrch_arm_permitctl.v":230:27:230:37|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\wrch_arm_permitctl.v":340:15:340:27|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\wrch_arm_permitctl.v":340:29:340:37|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\wrch_arm_permitctl.v":354:15:354:27|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axibus\writechannel\wrch_arm_permitctl.v":354:29:354:37|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\ahb2axibridge\ahb2axibridge.v":16:7:16:19|Synthesizing module AHB2AXIBridge
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\ahb2axibridge\ahb2axibridge.v":184:24:184:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\ahb2axibridge\ahb2axibridge.v":184:38:184:46|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\ahb2axibridge\ahb2axibridge.v":252:0:252:5|M
@W: CL112 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\ahb2axibridge\ahb2axibridge.v":252:0:252:5|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\ahb2axibridge\ahb2axibridge.v":367:25:367:37|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\ahb2axibridge\ahb2axibridge.v":367:39:367:47|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\ahb2axibridge\ahb2axibridge.v":383:25:383:37|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\ahb2axibridge\ahb2axibridge.v":383:39:383:47|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge.v":16:7:16:19|Synthesizing module AXI2APBBridge
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge.v":113:23:113:28|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge.v":118:23:118:25|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge.v":134:23:134:28|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge.v":207:24:207:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge.v":207:38:207:46|M
@W: CL112 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge.v":263:0:263:5|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge.v":278:14:278:26|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge.v":281:14:281:25|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge.v":304:0:304:5|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge.v":325:26:325:38|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge_simple.v":16:7:16:26|Synthesizing module AXI2APBBridge_Simple
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge_simple.v":96:23:96:28|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge_simple.v":101:23:101:25|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge_simple.v":117:23:117:28|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge_simple.v":171:24:171:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge_simple.v":171:38:171:46|M
@W: CL112 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge_simple.v":220:0:220:5|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge_simple.v":235:14:235:26|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge_simple.v":238:14:238:25|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge_simple.v":261:0:261:5|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\axi2apbbridge\axi2apbbridge_simple.v":282:26:282:38|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\defaultslave\defaultslave.v":16:7:16:18|Synthesizing module DefaultSlave
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\defaultslave\defaultslave.v":105:24:105:29|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\defaultslave\defaultslave.v":106:24:106:28|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\defaultslave\defaultslave.v":107:24:107:29|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\defaultslave\defaultslave.v":108:24:108:30|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\defaultslave\defaultslave.v":112:24:112:26|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\defaultslave\defaultslave.v":113:24:113:28|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\defaultslave\defaultslave.v":114:24:114:28|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\defaultslave\defaultslave.v":125:24:125:29|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\defaultslave\defaultslave.v":127:24:127:29|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\defaultslave\defaultslave.v":128:24:128:30|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\defaultslave\defaultslave.v":148:0:148:5|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\defaultslave\defaultslave.v":217:25:217:37|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\defaultslave\defaultslave.v":217:39:217:47|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\dsbridge\f2sslice_advanced.v":18:7:18:23|Synthesizing module F2SSlice_Advanced
@W: CL112 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\dsbridge\f2sslice_advanced.v":76:0:76:5|M
@W: CG296 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\dsbridge\f2sslice_advanced.v":107:9:107:56|M
@W: CG290 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\dsbridge\f2sslice_advanced.v":115:5:115:11|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\dsbridge\s2fslice.v":18:7:18:14|Synthesizing module S2FSlice
@W: CL112 :"d:\data\ntsc_pal\testplatform3\rtl\axiglue\dsbridge\s2fslice.v":75:0:75:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":4:7:4:11|Synthesizing module DDRAi
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":119:16:119:21|M
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":119:16:119:21|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":308:26:308:38|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":341:34:341:46|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":354:31:354:43|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":425:37:425:45|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":441:47:441:59|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":540:26:540:34|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":611:0:611:5|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":633:0:633:5|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":657:26:657:38|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":685:34:685:46|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":698:30:698:42|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":836:19:836:24|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":856:38:856:50|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":885:22:885:30|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":898:26:898:38|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":915:52:915:64|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":918:31:918:39|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":1008:12:1008:24|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrai.v":1018:12:1018:23|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrblq.v":4:7:4:12|Synthesizing module DDRBLQ
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrblq.v":19:0:19:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrblq.v":24:0:24:5|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrblq.v":48:40:48:52|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrblq.v":51:26:51:31|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrblq.v":70:32:70:43|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrblq.v":76:12:76:24|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrblq.v":90:12:90:23|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrbsm.v":4:7:4:12|Synthesizing module DDRBsm
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrbsm.v":53:15:53:19|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrbsm.v":54:15:54:19|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrbsm.v":55:15:55:19|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrbsm.v":56:12:56:17|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrbsm.v":60:12:60:22|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrbsm.v":64:14:64:24|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrbsm.v":65:16:65:22|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrbsm.v":115:0:115:5|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrbsm.v":166:0:166:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrcas.v":4:7:4:12|Synthesizing module DDRCas
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrcas.v":110:0:110:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":4:7:4:12|Synthesizing module DDRCtl
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":64:8:64:13|M
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":75:15:75:20|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":364:25:364:37|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":389:31:389:43|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":408:0:408:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":426:0:426:5|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":572:37:572:47|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":650:39:650:48|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":651:27:651:34|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":652:27:652:31|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":653:27:653:32|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":654:27:654:33|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":655:27:655:33|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":656:27:656:34|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":657:27:657:37|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":715:29:715:40|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":719:0:719:5|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1000:46:1000:53|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1007:46:1007:53|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1015:57:1015:64|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1016:57:1016:64|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1021:46:1021:53|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1023:36:1023:43|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1026:50:1026:57|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1112:0:1112:5|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1127:24:1127:36|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1141:0:1141:5|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1154:83:1154:89|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1155:24:1155:36|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1171:0:1171:5|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1188:24:1188:36|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1333:0:1333:5|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1478:12:1478:24|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrctl.v":1536:12:1536:23|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrras.v":7:7:7:12|Synthesizing module DDRRas
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrrds.v":19:7:19:12|Synthesizing module DDRRds
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrrds.v":86:0:86:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrrq.v":4:7:4:11|Synthesizing module DDRRQ
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrrq.v":9:25:9:28|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrrq.v":20:0:20:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrrq.v":25:0:25:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrrq.v":34:0:34:5|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrrq.v":37:40:37:52|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrrq.v":40:26:40:31|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrspi.v":20:7:20:12|Synthesizing module DDRSpi
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrspi.v":131:24:131:30|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrspi.v":171:24:171:30|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrspi.v":185:24:185:30|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrspi.v":186:24:186:30|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrspi.v":218:0:218:5|M
@W: CL112 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrspi.v":218:0:218:5|M
@W: CL112 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrspi.v":329:0:329:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrspi.v":396:0:396:5|M
@W: CL112 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrspi.v":396:0:396:5|M
@W: CL112 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrspi.v":481:0:481:5|M
@W: CL112 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrspi.v":575:0:575:5|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrspi.v":629:12:629:24|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrspi.v":653:12:653:23|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrtop.v":4:7:4:12|Synthesizing module DDRTop
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrtop.v":90:8:90:12|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrtop.v":193:7:193:12|M
@W: CL156 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrtop.v":279:7:279:12|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrwq.v":4:7:4:11|Synthesizing module DDRWQ
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrwq.v":20:0:20:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrwq.v":25:0:25:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrwq.v":34:0:34:5|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrwq.v":37:40:37:52|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\ddrctrl\ddrwq.v":40:26:40:31|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\etc\clockresetgen.v":17:7:17:19|Synthesizing module ClockResetGen
@W: CG293 :"d:\data\ntsc_pal\testplatform3\rtl\etc\clockresetgen.v":56:0:56:6|M
@W: CG439 :"d:\data\ntsc_pal\testplatform3\rtl\etc\clockresetgen.v":56:0:56:6|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\etc\clockresetgen.v":69:0:69:5|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\etc\clockresetgen.v":69:0:69:5|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":11:7:11:17|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":92:0:92:1|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":103:0:103:1|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":114:2:114:3|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":125:2:125:3|M
@W: CG296 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":137:0:137:6|M
@W: CD434 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":137:8:137:16|M
@N: MF138 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":139:3:139:4|M
@N: MO106 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":139:3:139:4|M
@W: CG290 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":139:9:139:13|M
@W: CG296 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":160:0:160:6|M
@W: CD434 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":160:8:160:16|M
@N: MF138 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":162:3:162:4|M
@N: MO106 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":162:3:162:4|M
@W: CG290 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":162:6:162:10|M
@W: CG296 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":182:0:182:6|M
@W: CD434 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":182:8:182:16|M
@N: MF138 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":184:3:184:4|M
@N: MO106 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":184:3:184:4|M
@W: CG290 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":184:6:184:10|M
@W: CG296 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":204:0:204:6|M
@W: CD434 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":204:8:204:16|M
@N: MF138 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":206:3:206:4|M
@N: MO106 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":206:3:206:4|M
@W: CG290 :"d:\data\ntsc_pal\testplatform3\rtl\etc\hc4094_7seg.vhd":206:6:206:10|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\gpio\gpio.v":16:7:16:10|Synthesizing module Gpio
@W: CL112 :"d:\data\ntsc_pal\testplatform3\rtl\gpio\gpio.v":80:0:80:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\btransctl.v":1:7:1:15|Synthesizing module BTransCtl
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\i2c\btransctl.v":19:0:19:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2c.v":13:7:13:9|Synthesizing module I2C
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2c.v":24:14:24:18|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2c.v":57:25:57:37|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2cbusdet.v":12:7:12:15|Synthesizing module I2cBusDet
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2cbusflt.v":1:7:1:15|Synthesizing module I2cBusFlt
@W: BN132 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2cbusflt.v":11:0:11:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2cclkdiv.v":1:7:1:15|Synthesizing module I2cClkDiv
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2cclkdiv.v":13:0:13:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2cclkdiv.v":36:0:36:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2ccore.v":2:7:2:13|Synthesizing module I2cCore
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2cctl.v":2:7:2:12|Synthesizing module I2cCtl
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2cioshft.v":1:7:1:15|Synthesizing module I2cIOShft
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2creg.v":3:7:3:12|Synthesizing module I2cReg
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2creg.v":141:33:141:37|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2creg.v":150:29:150:32|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2creg.v":158:29:158:32|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2creg.v":169:35:169:41|M
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2creg.v":195:4:195:7|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2creg.v":195:27:195:39|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2creg.v":195:41:195:49|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\i2creg.v":222:7:222:15|Synthesizing module AASDecode
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\sclctl.v":1:7:1:12|Synthesizing module SclCtl
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\smctl.v":32:7:32:11|Synthesizing module SMCtl
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\smctl.v":516:18:516:22|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\startctl.v":1:7:1:14|Synthesizing module StartCtl
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\i2c\startctl.v":15:0:15:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\i2c\stopctl.v":1:7:1:13|Synthesizing module StopCtl
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\i2c\stopctl.v":29:0:29:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\intsramctrl\intsramcontroller.v":16:7:16:23|Synthesizing module IntSRAMController
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\intsramctrl\intsramcontroller.v":93:24:93:29|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\intsramctrl\intsramcontroller.v":98:24:98:26|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\intsramctrl\intsramcontroller.v":114:24:114:29|M
@W: CL112 :"d:\data\ntsc_pal\testplatform3\rtl\intsramctrl\intsramcontroller.v":211:0:211:5|M
@W: CL170 :"d:\data\ntsc_pal\testplatform3\rtl\intsramctrl\intsramcontroller.v":211:0:211:5|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\intsramctrl\intsramcontroller.v":274:24:274:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\intsramctrl\intsramcontroller.v":274:38:274:46|M
@W: CL171 :"d:\data\ntsc_pal\testplatform3\rtl\intsramctrl\intsramcontroller.v":386:0:386:5|M
@W: CL112 :"d:\data\ntsc_pal\testplatform3\rtl\intsramctrl\intsramcontroller.v":431:0:431:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\intsramctrl\intsramcontroller.v":457:0:457:5|M
@W: CL170 :"d:\data\ntsc_pal\testplatform3\rtl\intsramctrl\intsramcontroller.v":510:0:510:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_apbregisterif.v":25:7:25:23|Synthesizing module mmc_APBRegisterIF
@W: CG286 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_apbregisterif.v":1216:1:1216:4|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_apbregisterif.v":1216:24:1216:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_apbregisterif.v":1216:38:1216:46|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_apbregisterif.v":1300:12:1300:24|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_apbregisterif.v":1365:12:1365:23|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_clksync.v":2:7:2:18|Synthesizing module mmc_PCLKSync
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_clksync.v":353:7:353:18|Synthesizing module mmc_MCLKSync
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_commandcontrol.v":20:7:20:24|Synthesizing module mmc_CommandControl
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_commandcontrol.v":182:0:182:5|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_commandcontrol.v":199:16:199:21|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_commandcontrol.v":597:7:597:14|Synthesizing module AUTORead
@W: BN132 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_commandcontrol.v":792:0:792:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_datacontrol.v":28:7:28:21|Synthesizing module mmc_DataControl
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_datacontrol.v":104:8:104:14|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_datacontrol.v":674:0:674:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_datacontrol.v":692:0:692:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_datacontrol.v":752:0:752:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_datacontrol.v":772:0:772:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_datacontrol.v":970:0:970:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_datacontrol.v":1880:0:1880:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_feedbacksync.v":2:7:2:22|Synthesizing module mmc_FeedBackSync
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_fifo.v":2:7:2:14|Synthesizing module mmc_FIFO
@N: CL134 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_fifo.v":88:0:88:5|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_fifo.v":90:36:90:51|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_fifo.v":163:7:163:17|Synthesizing module mmc_FIFOCtl
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_fifo.v":308:0:308:5|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_fifo.v":336:0:336:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_fifo.v":352:0:352:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_fifo.v":458:0:458:5|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_fifo.v":465:43:465:55|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_fifo.v":468:27:468:32|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_fifodmactr.v":4:7:4:22|Synthesizing module mmc_DataFifo_DMA
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_prescaler.v":18:7:18:19|Synthesizing module mmc_Prescaler
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_prescaler.v":122:0:122:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_regupd.v":7:7:7:16|Synthesizing module mmc_RegUpd
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmc_regupd.v":322:0:322:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\mmc\mmctop.v":17:7:17:12|Synthesizing module MMCTop
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\smc\axi_esmc_interface.v":16:7:16:24|Synthesizing module AXI_ESMC_interface
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\smc\axi_esmc_interface.v":94:23:94:28|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\smc\axi_esmc_interface.v":95:23:95:27|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\smc\axi_esmc_interface.v":96:23:96:28|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\smc\axi_esmc_interface.v":101:23:101:25|M
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\smc\axi_esmc_interface.v":115:23:115:28|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\smc\axi_esmc_interface.v":117:23:117:28|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\smc\axi_esmc_interface.v":167:24:167:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\smc\axi_esmc_interface.v":167:38:167:46|M
@W: CL112 :"d:\data\ntsc_pal\testplatform3\rtl\smc\axi_esmc_interface.v":224:0:224:5|M
@W: CL171 :"d:\data\ntsc_pal\testplatform3\rtl\smc\axi_esmc_interface.v":224:0:224:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\smc\axi_esmc_interface.v":263:0:263:5|M
@W: CL171 :"d:\data\ntsc_pal\testplatform3\rtl\smc\axi_esmc_interface.v":276:0:276:5|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\smc\axi_esmc_interface.v":284:26:284:38|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\smc\smc_reg.v":15:7:15:13|Synthesizing module SMC_REG
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\smc\smc_reg.v":42:16:42:21|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\smc\smc_reg.v":45:10:45:19|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\smc\smc_top.v":17:7:17:13|Synthesizing module SMC_TOP
@W: CS142 :"d:\data\ntsc_pal\testplatform3\rtl\smc\smc_top.v":64:1:64:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\smc\sram_ctrl.v":21:7:21:15|Synthesizing module SRAM_CTRL
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\smc\sram_ctrl.v":216:15:216:24|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\smc\sram_ctrl.v":234:16:234:25|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\smc\sram_ctrl.v":236:15:236:24|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\smc\sram_ctrl.v":369:22:369:27|M
@N: CG179 :"d:\data\ntsc_pal\testplatform3\rtl\smc\sram_ctrl.v":431:14:431:18|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheahb.vhd":28:7:28:14|M
@N: CD231 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheahb.vhd":94:16:94:17|M
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheahb.vhd":243:4:243:5|M
@N: CL236 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheahb.vhd":243:4:243:5|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachectl.vhd":23:7:23:14|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":28:7:28:13|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":34:4:34:7|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":38:4:38:6|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":40:4:40:8|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":42:4:42:7|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":54:4:54:9|M
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":54:4:54:9|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":55:4:55:8|M
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":55:4:55:8|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":79:4:79:10|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":84:4:84:9|M
@N: CD231 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":100:20:100:21|M
@N: CD231 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":110:20:110:21|M
@N: CD231 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":119:20:119:21|M
@N: CD231 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":125:20:125:21|M
@W: CD604 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":217:4:217:17|M
@W: CL171 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":632:4:632:5|M
@N: CL236 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":632:4:632:5|M
@W: BN132 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":666:4:666:5|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":666:4:666:5|M
@W: CL171 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":666:4:666:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":759:4:759:5|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":759:4:759:5|M
@N: CL236 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":759:4:759:5|M
@W: CL171 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":827:4:827:5|M
@N: CL236 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedc.vhd":827:4:827:5|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedpu.vhd":28:7:28:14|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachedpu.vhd":40:4:40:9|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":27:7:27:13|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":33:4:33:7|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":35:4:35:6|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":45:4:45:9|M
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":45:4:45:9|M
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":46:4:46:8|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":66:4:66:9|M
@N: CD231 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":82:20:82:21|M
@N: CD231 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":90:20:90:21|M
@N: CD231 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":97:20:97:21|M
@W: CD604 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":171:4:171:17|M
@W: CL171 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":460:4:460:5|M
@N: CL236 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":460:4:460:5|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":491:4:491:5|M
@W: CL171 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":491:4:491:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":553:4:553:5|M
@W: CL171 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":553:4:553:5|M
@N: CL236 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":553:4:553:5|M
@W: CL171 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":590:4:590:5|M
@N: CL236 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheic.vhd":590:4:590:5|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheipu.vhd":28:7:28:14|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cacheipu.vhd":40:4:40:9|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachemem.vhd":23:7:23:14|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachemem.vhd":26:4:26:9|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachemem.vhd":37:4:37:9|M
@W: CD604 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachepkg.vhd":85:4:85:17|M
@W: CD604 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachepkg.vhd":106:6:106:19|M
@W: CD604 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachepkg.vhd":114:6:114:19|M
@W: CD604 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachepkg.vhd":122:6:122:19|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachereg.vhd":28:7:28:14|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachewb.vhd":28:7:28:13|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachewb.vhd":43:4:43:9|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachewb.vhd":53:4:53:8|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachewb.vhd":300:4:300:5|M
@W: CL171 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\cachewb.vhd":300:4:300:5|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\sp128x22m4.vhd":25:7:25:16|M
@N: CL134 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\sp128x22m4.vhd":44:11:44:13|M
@W: BN132 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\sp128x22m4.vhd":49:4:49:5|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\sp128x23m4.vhd":25:7:25:16|M
@N: CL134 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\sp128x23m4.vhd":44:11:44:13|M
@W: BN132 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\sp128x23m4.vhd":49:4:49:5|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\sp512x32m4.vhd":25:7:25:16|M
@N: CL134 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\sp512x32m4.vhd":44:11:44:13|M
@W: BN132 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cache\sp512x32m4.vhd":49:4:49:5|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\alu.vhd":8:7:8:9|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\alu.vhd":9:13:9:19|M
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\alu.vhd":10:13:10:19|M
@W: CD638 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\alu.vhd":35:8:35:20|M
@W: CD638 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\alu.vhd":36:8:36:20|M
@W: CD638 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\alu.vhd":37:8:37:19|M
@W: CD638 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\alu.vhd":38:8:38:17|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\clz_unit.vhd":8:7:8:14|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\clz_unit.vhd":9:13:9:19|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\cond_check.vhd":7:7:7:16|M
@W: CD604 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\cond_check.vhd":121:2:121:15|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\cpsr_update.vhd":8:7:8:17|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":16:7:16:9|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":39:4:39:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":40:4:40:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":41:4:41:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":42:4:42:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":43:4:43:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":44:4:44:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":45:4:45:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":46:4:46:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":47:4:47:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":48:4:48:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":49:4:49:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":50:4:50:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":51:4:51:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":52:4:52:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":53:4:53:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":54:4:54:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":55:4:55:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":56:4:56:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":57:4:57:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":58:4:58:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":59:4:59:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":60:4:60:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":61:4:61:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":62:4:62:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":64:4:64:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":66:4:66:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":68:4:68:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":78:4:78:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":79:4:79:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":80:4:80:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":81:4:81:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":82:4:82:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":83:4:83:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":84:4:84:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":85:4:85:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":86:4:86:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":87:4:87:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":88:4:88:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":89:4:89:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":90:4:90:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":91:4:91:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":92:4:92:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":93:4:93:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":94:4:94:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":95:4:95:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":96:4:96:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":97:4:97:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":98:4:98:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":99:4:99:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":100:4:100:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":101:4:101:11|M
@W: BN115 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\csa.vhd":102:4:102:11|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\data_filter.vhd":8:7:8:17|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\data_filter.vhd":13:16:13:19|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\data_filter.vhd":14:17:14:19|M
@N: CD231 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\data_filter.vhd":30:17:30:18|M
@N: CL236 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\data_filter.vhd":39:1:39:2|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\dmem_ctrl.vhd":8:7:8:15|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\dmiu.vhd":8:7:8:10|M
@W: CD604 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\dmiu.vhd":61:4:61:17|M
@W: CD604 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\dmiu.vhd":75:4:75:17|M
@W: CD604 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\dmiu.vhd":86:4:86:17|M
@W: CD604 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\dmiu.vhd":95:4:95:17|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\dmou.vhd":8:7:8:10|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\dmou.vhd":10:14:10:19|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\fadd.vhd":16:7:16:10|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\ff1_32.vhd":8:7:8:12|M
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\ff1_32.vhd":27:1:27:2|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\ff1_4.vhd":8:7:8:11|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\ff4_32.vhd":8:7:8:12|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\ff_wb_ctrl.vhd":8:7:8:16|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\ff_x1_ctrl.vhd":8:7:8:16|M
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\ff_x1_ctrl.vhd":53:2:53:3|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\ff_x2_ctrl.vhd":8:7:8:16|M
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\ff_x2_ctrl.vhd":46:2:46:3|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\ff_x2b_ctrl.vhd":8:7:8:17|M
@W: BN116 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\ff_x2b_ctrl.vhd":42:2:42:3|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\forward_ctrl.vhd":8:7:8:18|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\forward_ctrl.vhd":11:13:11:23|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\forward_ctrl.vhd":26:13:26:23|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\forward_ctrl.vhd":29:13:29:19|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\forward_ctrl.vhd":30:13:30:19|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\greg.vhd":8:7:8:10|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\if_ctrl.vhd":8:7:8:13|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\inst_ctrl.vhd":8:7:8:15|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\inst_ctrl.vhd":10:16:10:19|M
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\inst_ctrl.vhd":10:16:10:19|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\inst_ctrl.vhd":20:13:20:25|M
@N: CD231 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\inst_ctrl.vhd":225:27:225:28|M
@N: CD231 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\inst_ctrl.vhd":226:29:226:30|M
@N: CL236 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\inst_ctrl.vhd":265:2:265:3|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\inv1.vhd":8:7:8:10|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\mbe.vhd":16:7:16:9|M
@W: CD604 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\mbe.vhd":42:12:42:27|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\mul.vhd":6:7:6:9|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\mul.vhd":9:4:9:10|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\mul.vhd":11:18:11:19|M
@W: CD638 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\mul.vhd":57:44:57:52|M
@W: CD638 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\mul.vhd":57:55:57:63|M
@W: CL171 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\mul.vhd":177:8:177:9|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\mux2_32.vhd":8:7:8:13|M
@W: CD604 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\mux2_32.vhd":30:2:30:15|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\mux2_4.vhd":8:7:8:12|M
@W: CD604 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\mux2_4.vhd":30:2:30:15|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\mux3_32.vhd":8:7:8:13|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\mux3_4.vhd":8:7:8:12|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\mux4_32.vhd":6:7:6:13|M
@W: CD604 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\mux4_32.vhd":34:2:34:15|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\op_filter.vhd":8:7:8:15|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\pass_wb_ctrl.vhd":8:7:8:18|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\pass_wb_data.vhd":8:7:8:18|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\psr.vhd":8:7:8:9|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\reg_conv.vhd":8:7:8:14|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\shift.vhd":8:7:8:11|M
@W: CL209 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\shift.vhd":13:16:13:19|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\stall_flush_ctrl.vhd":8:7:8:22|M
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\stall_flush_ctrl.vhd":28:13:28:19|M
@W: CL234 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\stall_flush_ctrl.vhd":29:13:29:19|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\stall_flush_ctrl.vhd":31:13:31:23|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\stall_flush_ctrl.vhd":32:14:32:19|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\stall_flush_ctrl.vhd":33:14:33:19|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\stall_flush_ctrl.vhd":34:13:34:19|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\stall_flush_ctrl.vhd":35:13:35:19|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\toyarm.vhd":8:7:8:12|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\wr_backup.vhd":8:7:8:15|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\core\wr_backup.vhd":14:15:14:19|M
@N: CD630 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\cpu.vhd":17:7:17:9|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\tarm_axi.v":16:7:16:14|Synthesizing module tarm_axi
@W: CL112 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\tarm_axi.v":134:0:134:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\tarm\tarm_axi_fastclk.v":17:7:17:22|Synthesizing module tarm_axi_fastclk
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\timer\timer_pwm.v":24:7:24:15|Synthesizing module timer_pwm
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\timer\timer_pwm.v":161:13:161:25|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\timer\timer_pwm.v":166:13:166:24|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\timer\timer_pwm.v":284:13:284:25|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\timer\timer_pwm.v":294:14:294:25|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\timer\timer_pwm.v":444:19:444:31|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\timer\timer_pwm.v":510:0:510:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\timer\timer_pwm.v":682:0:682:5|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\timer\timer_pwm.v":998:23:998:35|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\timer\timer_pwm.v":1072:15:1072:27|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":15:7:15:22|Synthesizing module TestPlatformCore
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":299:12:299:22|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":300:12:300:23|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":301:12:301:22|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":307:12:307:21|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":322:12:322:22|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":323:12:323:23|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":324:12:324:22|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":341:12:341:22|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":342:12:342:23|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":343:12:343:22|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":349:12:349:21|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":364:12:364:22|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":365:12:365:23|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":366:12:366:22|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":383:12:383:21|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":384:12:384:22|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":385:12:385:21|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":406:12:406:21|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":407:12:407:22|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":408:12:408:21|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":425:12:425:25|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":426:12:426:26|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":427:12:427:25|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":448:12:448:25|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":449:12:449:26|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":450:12:450:25|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":857:12:857:20|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":878:12:878:20|M
@W: CL156 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":959:46:959:49|M
@W: CL156 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":1156:53:1156:56|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":1215:12:1215:21|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":1224:12:1224:21|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":1233:12:1233:21|M
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":1242:12:1242:21|M
@W: CL156 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformcore.v":1275:19:1275:26|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformfpga.v":16:7:16:22|Synthesizing module TestPlatformFPGA
@W: CG360 :"d:\data\ntsc_pal\testplatform3\rtl\top\testplatformfpga.v":178:13:178:21|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uart.v":24:7:24:10|Synthesizing module Uart
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartapbif.v":25:7:25:15|Synthesizing module UartApbif
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartbaudcntr.v":25:7:25:18|Synthesizing module UartBaudCntr
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartbaudcntr.v":623:0:623:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartdatastp.v":24:7:24:17|Synthesizing module UartDataStp
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartdatastp.v":203:0:203:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartdma.v":25:7:25:13|Synthesizing module UartDMA
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartinterrupt.v":24:7:24:19|Synthesizing module UartInterrupt
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartirda.v":24:7:24:14|Synthesizing module UartIrDA
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartirda.v":353:0:353:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartirda.v":567:0:567:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartmodem.v":24:7:24:15|Synthesizing module UartModem
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartreceive.v":24:7:24:17|Synthesizing module UartReceive
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartregblock.v":24:7:24:18|Synthesizing module UartRegBlock
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartrxcntl.v":25:7:25:16|Synthesizing module UartRXCntl
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartrxcntl.v":653:0:653:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartrxcntl.v":661:0:661:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartrxfcntl.v":25:7:25:17|Synthesizing module UartRXFCntl
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartrxfcntl.v":364:0:364:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartrxfifo.v":25:7:25:16|Synthesizing module UartRXFIFO
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartrxparshft.v":25:7:25:19|Synthesizing module UartRXParShft
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartrxregfile.v":24:7:24:19|Synthesizing module UartRXRegFile
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartsynctopclk.v":25:7:25:20|Synthesizing module UartSynctoPCLK
@W: BN132 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartsynctopclk.v":353:0:353:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartsynctouclk.v":25:7:25:20|Synthesizing module UartSynctoUCLK
@W: BN132 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uartsynctouclk.v":529:0:529:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uarttest.v":23:7:23:14|Synthesizing module UartTest
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uarttxcntl.v":24:7:24:16|Synthesizing module UartTXCntl
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\uart\uarttxcntl.v":712:0:712:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\uart\uarttxcntl.v":721:0:721:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uarttxfcntl.v":26:7:26:17|Synthesizing module UartTXFCntl
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\uart\uarttxfcntl.v":412:0:412:5|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uarttxfifo.v":25:7:25:16|Synthesizing module UartTXFIFO
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\uart\uarttxregfile.v":25:7:25:19|Synthesizing module UartTXRegFile
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\vic\apb_vic.v":15:7:15:13|Synthesizing module APB_vic
@N: MF138 :"d:\data\ntsc_pal\testplatform3\rtl\vic\apb_vic.v":700:2:700:5|M
@N: MO106 :"d:\data\ntsc_pal\testplatform3\rtl\vic\apb_vic.v":700:2:700:5|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\vic\apb_vic.v":737:16:737:28|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\vic\apb_vic.v":740:16:740:27|M
@N: MF138 :"d:\data\ntsc_pal\testplatform3\rtl\vic\apb_vic.v":744:2:744:5|M
@N: MO106 :"d:\data\ntsc_pal\testplatform3\rtl\vic\apb_vic.v":744:2:744:5|M
@N: CG334 :"d:\data\ntsc_pal\testplatform3\rtl\vic\apb_vic.v":781:16:781:28|M
@N: CG333 :"d:\data\ntsc_pal\testplatform3\rtl\vic\apb_vic.v":784:16:784:27|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\vic\vic_master_arbiter.v":9:7:9:24|Synthesizing module vic_master_arbiter
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\vic\vic_master_arbiter.v":119:7:119:40|Synthesizing module vic_master_arbiter_priority_decode
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\vic\vic_master_arbiter.v":145:7:145:33|Synthesizing module vic_master_arbiter_4to1_mux
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\vic\vic_slave_arbiter.v":9:7:9:23|Synthesizing module vic_slave_arbiter
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\vic\vic_slave_arbiter.v":175:7:175:39|Synthesizing module vic_slave_arbiter_priority_decode
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\vic\vic_slave_arbiter.v":205:7:205:32|Synthesizing module vic_slave_arbiter_8to1_mux
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\multisram.v":1:7:1:15|Synthesizing module MULTISRAM
@N: CG440 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\multisram.v":22:18:22:20|M
@N: CL214 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\multisram.v":28:6:28:16|M
@N: CG364 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":30:7:30:24|Synthesizing module VideoEncoderTester
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":140:23:140:27|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":141:23:141:27|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":172:14:172:23|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":181:14:181:23|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":190:14:190:23|M
@W: CL159 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":199:14:199:23|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":291:15:291:27|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":325:24:325:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":325:38:325:46|M
@N: CG347 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":351:24:351:36|M
@N: CG346 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":351:38:351:46|M
@W: CL171 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":370:0:370:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":507:0:507:5|M
@W: CL170 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":507:0:507:5|M
@N: CL135 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":569:0:569:5|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":569:0:569:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":597:0:597:5|M
@N:  :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":615:0:615:5|M
@N: CL135 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":690:0:690:5|M
@W: CL169 :"d:\data\ntsc_pal\testplatform3\rtl\videoenctester\videoencodertester.v":690:0:690:5|M
