#!/bin/csh -fx

fm_shell -f LEC.tcl | tee /dev/tty >&! ./Ssp.log

#----========================================================================----
#-- Proper Sdf Generaion Fitted to TSMC 
#----========================================================================----
#./pt_postprocessor.pl -s ./Sdf/temp.sdf -o ./Sdf/MMCTop.noscan.sdf

#\rm -rf *.log ./Sdf/temp.sdf

exit
