library verilog;
use verilog.vl_types.all;
entity ARMD_RS_WriteChannelsi is
    generic(
        BUS_WID         : integer := 32;
        ADDR_WID        : integer := 32;
        MASTERID_WID    : integer := 1;
        SLAVEID_WID     : integer := 2;
        AWLEN_WID       : integer := 4;
        AWSIZE_WID      : integer := 3;
        AWBURST_WID     : integer := 2;
        AWLOCK_WID      : integer := 2;
        AWCACHE_WID     : integer := 4;
        AWPROT_WID      : integer := 3;
        WSTRB_WID       : integer := 4;
        BRESP_WID       : integer := 2;
        RRESP_WID       : integer := 2;
        ARLEN_WID       : integer := 4;
        ARBURST_WID     : integer := 2;
        ARLOCK_WID      : integer := 2;
        ARCACHE_WID     : integer := 4;
        ARPROT_WID      : integer := 3;
        MASTER_WID      : integer := 3;
        SLAVE_WID       : integer := 4;
        SLAVE_NUM       : integer := 8;
        MASTER_NUM      : integer := 5;
        SELMASTER_WID   : integer := 2;
        Wr_REQDEPTH_WID : integer := 1;
        Rd_REQDEPTH_WID : integer := 1;
        WrPermit_SLAVECNTWID: integer := 1;
        RdPermit_SLAVECNTWID: integer := 1;
        ARSIZE_WID      : integer := 3
    );
    port(
        SelMAP1         : in     vl_logic;
        ACLK            : in     vl_logic;
        ARESETn         : in     vl_logic;
        AWADDRm2si      : in     vl_logic_vector;
        AWLENm2si       : in     vl_logic_vector;
        AWSIZEm2si      : in     vl_logic_vector;
        AWBURSTm2si     : in     vl_logic_vector;
        AWLOCKm2si      : in     vl_logic_vector;
        AWVALIDm2si     : in     vl_logic;
        AWREADYsi2m     : out    vl_logic;
        WDATAm2si       : in     vl_logic_vector;
        WSTRBm2si       : in     vl_logic_vector;
        WLASTm2si       : in     vl_logic;
        WVALIDm2si      : in     vl_logic;
        WREADYsi2m      : out    vl_logic;
        BRESPsi2m       : out    vl_logic_vector;
        BVALIDsi2m      : out    vl_logic;
        BREADYm2si      : in     vl_logic;
        AWIDsi2mi0      : out    vl_logic_vector;
        AWADDRsi2mi0    : out    vl_logic_vector;
        AWLENsi2mi0     : out    vl_logic_vector;
        AWSIZEsi2mi0    : out    vl_logic_vector;
        AWBURSTsi2mi0   : out    vl_logic_vector;
        AWLOCKsi2mi0    : out    vl_logic_vector;
        AWCACHEsi2mi0   : out    vl_logic_vector;
        AWPROTsi2mi0    : out    vl_logic_vector;
        WIDsi2mi0       : out    vl_logic_vector;
        WDATAsi2mi0     : out    vl_logic_vector;
        WSTRBsi2mi0     : out    vl_logic_vector;
        AWIDsi2mi1      : out    vl_logic_vector;
        AWADDRsi2mi1    : out    vl_logic_vector;
        AWLENsi2mi1     : out    vl_logic_vector;
        AWSIZEsi2mi1    : out    vl_logic_vector;
        AWBURSTsi2mi1   : out    vl_logic_vector;
        AWLOCKsi2mi1    : out    vl_logic_vector;
        AWCACHEsi2mi1   : out    vl_logic_vector;
        AWPROTsi2mi1    : out    vl_logic_vector;
        WIDsi2mi1       : out    vl_logic_vector;
        WDATAsi2mi1     : out    vl_logic_vector;
        WSTRBsi2mi1     : out    vl_logic_vector;
        AWIDsi2mi2      : out    vl_logic_vector;
        AWADDRsi2mi2    : out    vl_logic_vector;
        AWLENsi2mi2     : out    vl_logic_vector;
        AWSIZEsi2mi2    : out    vl_logic_vector;
        AWBURSTsi2mi2   : out    vl_logic_vector;
        AWLOCKsi2mi2    : out    vl_logic_vector;
        AWCACHEsi2mi2   : out    vl_logic_vector;
        AWPROTsi2mi2    : out    vl_logic_vector;
        WIDsi2mi2       : out    vl_logic_vector;
        WDATAsi2mi2     : out    vl_logic_vector;
        WSTRBsi2mi2     : out    vl_logic_vector;
        AWIDsi2mi3      : out    vl_logic_vector;
        AWADDRsi2mi3    : out    vl_logic_vector;
        AWLENsi2mi3     : out    vl_logic_vector;
        AWSIZEsi2mi3    : out    vl_logic_vector;
        AWBURSTsi2mi3   : out    vl_logic_vector;
        AWLOCKsi2mi3    : out    vl_logic_vector;
        AWCACHEsi2mi3   : out    vl_logic_vector;
        AWPROTsi2mi3    : out    vl_logic_vector;
        WIDsi2mi3       : out    vl_logic_vector;
        WDATAsi2mi3     : out    vl_logic_vector;
        WSTRBsi2mi3     : out    vl_logic_vector;
        AWIDsi2mi4      : out    vl_logic_vector;
        AWADDRsi2mi4    : out    vl_logic_vector;
        AWLENsi2mi4     : out    vl_logic_vector;
        AWSIZEsi2mi4    : out    vl_logic_vector;
        AWBURSTsi2mi4   : out    vl_logic_vector;
        AWLOCKsi2mi4    : out    vl_logic_vector;
        AWCACHEsi2mi4   : out    vl_logic_vector;
        AWPROTsi2mi4    : out    vl_logic_vector;
        WIDsi2mi4       : out    vl_logic_vector;
        WDATAsi2mi4     : out    vl_logic_vector;
        WSTRBsi2mi4     : out    vl_logic_vector;
        AWIDsi2mi5      : out    vl_logic_vector;
        AWADDRsi2mi5    : out    vl_logic_vector;
        AWLENsi2mi5     : out    vl_logic_vector;
        AWSIZEsi2mi5    : out    vl_logic_vector;
        AWBURSTsi2mi5   : out    vl_logic_vector;
        AWLOCKsi2mi5    : out    vl_logic_vector;
        AWCACHEsi2mi5   : out    vl_logic_vector;
        AWPROTsi2mi5    : out    vl_logic_vector;
        WIDsi2mi5       : out    vl_logic_vector;
        WDATAsi2mi5     : out    vl_logic_vector;
        WSTRBsi2mi5     : out    vl_logic_vector;
        AWIDsi2mi6      : out    vl_logic_vector;
        AWADDRsi2mi6    : out    vl_logic_vector;
        AWLENsi2mi6     : out    vl_logic_vector;
        AWSIZEsi2mi6    : out    vl_logic_vector;
        AWBURSTsi2mi6   : out    vl_logic_vector;
        AWLOCKsi2mi6    : out    vl_logic_vector;
        AWCACHEsi2mi6   : out    vl_logic_vector;
        AWPROTsi2mi6    : out    vl_logic_vector;
        WIDsi2mi6       : out    vl_logic_vector;
        WDATAsi2mi6     : out    vl_logic_vector;
        WSTRBsi2mi6     : out    vl_logic_vector;
        AWIDsi2mi7      : out    vl_logic_vector;
        AWADDRsi2mi7    : out    vl_logic_vector;
        AWLENsi2mi7     : out    vl_logic_vector;
        AWSIZEsi2mi7    : out    vl_logic_vector;
        AWBURSTsi2mi7   : out    vl_logic_vector;
        AWLOCKsi2mi7    : out    vl_logic_vector;
        AWCACHEsi2mi7   : out    vl_logic_vector;
        AWPROTsi2mi7    : out    vl_logic_vector;
        WIDsi2mi7       : out    vl_logic_vector;
        WDATAsi2mi7     : out    vl_logic_vector;
        WSTRBsi2mi7     : out    vl_logic_vector;
        AWVALIDsi2mi    : out    vl_logic_vector;
        AWREADYmi2si    : in     vl_logic_vector;
        WLASTsi2mi      : out    vl_logic_vector;
        WVALIDsi2mi     : out    vl_logic_vector;
        WREADYmi2si     : in     vl_logic_vector;
        BIDmi02si       : in     vl_logic_vector;
        BRESPmi02si     : in     vl_logic_vector;
        BIDmi12si       : in     vl_logic_vector;
        BRESPmi12si     : in     vl_logic_vector;
        BIDmi22si       : in     vl_logic_vector;
        BRESPmi22si     : in     vl_logic_vector;
        BIDmi32si       : in     vl_logic_vector;
        BRESPmi32si     : in     vl_logic_vector;
        BIDmi42si       : in     vl_logic_vector;
        BRESPmi42si     : in     vl_logic_vector;
        BIDmi52si       : in     vl_logic_vector;
        BRESPmi52si     : in     vl_logic_vector;
        BIDmi62si       : in     vl_logic_vector;
        BRESPmi62si     : in     vl_logic_vector;
        BIDmi72si       : in     vl_logic_vector;
        BRESPmi72si     : in     vl_logic_vector;
        BVALIDmi2si     : in     vl_logic_vector;
        BREADYsi2mi     : out    vl_logic_vector
    );
end ARMD_RS_WriteChannelsi;
