#####################################################

#  Created by Design Compiler write_sdc on Thu Jun  8 14:49:26 2006

#####################################################
set sdc_version 1.4

create_clock -name "OscClk" -period 10 -waveform {0 5} [get_ports {ACLK}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[0]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[1]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[2]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[3]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[4]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[5]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[6]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[7]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[8]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[9]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[10]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[11]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[12]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[13]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[14]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[15]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[16]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[17]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[18]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[19]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[20]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[21]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[22]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[23]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[24]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[25]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[26]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[27]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[28]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[29]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[30]}]
set_input_delay 2 -clock "OscClk" [get_ports {MEMRDATA[31]}]
set_input_delay 2 -clock "OscClk" [get_ports {RREADY}]
set_input_delay 2 -clock "OscClk" [get_ports {ARVALID}]
set_input_delay 2 -clock "OscClk" [get_ports {ARBURST[0]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARBURST[1]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARSIZE[0]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARSIZE[1]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARSIZE[2]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARLEN[0]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARLEN[1]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARLEN[2]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARLEN[3]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[0]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[1]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[2]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[3]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[4]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[5]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[6]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[7]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[8]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[9]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[10]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[11]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[12]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[13]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[14]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[15]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[16]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[17]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[18]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[19]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[20]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[21]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[22]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[23]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[24]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[25]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[26]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[27]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[28]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[29]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[30]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARADDR[31]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARID[0]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARID[1]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARID[2]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARID[3]}]
set_input_delay 2 -clock "OscClk" [get_ports {BREADY}]
set_input_delay 2 -clock "OscClk" [get_ports {WVALID}]
set_input_delay 2 -clock "OscClk" [get_ports {WLAST}]
set_input_delay 2 -clock "OscClk" [get_ports {WSTRB[0]}]
set_input_delay 2 -clock "OscClk" [get_ports {WSTRB[1]}]
set_input_delay 2 -clock "OscClk" [get_ports {WSTRB[2]}]
set_input_delay 2 -clock "OscClk" [get_ports {WSTRB[3]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[0]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[1]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[2]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[3]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[4]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[5]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[6]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[7]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[8]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[9]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[10]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[11]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[12]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[13]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[14]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[15]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[16]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[17]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[18]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[19]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[20]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[21]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[22]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[23]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[24]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[25]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[26]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[27]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[28]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[29]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[30]}]
set_input_delay 2 -clock "OscClk" [get_ports {WDATA[31]}]
set_input_delay 2 -clock "OscClk" [get_ports {WID[0]}]
set_input_delay 2 -clock "OscClk" [get_ports {WID[1]}]
set_input_delay 2 -clock "OscClk" [get_ports {WID[2]}]
set_input_delay 2 -clock "OscClk" [get_ports {WID[3]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWVALID}]
set_input_delay 2 -clock "OscClk" [get_ports {AWBURST[0]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWBURST[1]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWSIZE[0]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWSIZE[1]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWSIZE[2]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWLEN[0]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWLEN[1]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWLEN[2]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWLEN[3]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[0]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[1]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[2]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[3]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[4]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[5]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[6]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[7]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[8]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[9]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[10]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[11]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[12]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[13]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[14]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[15]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[16]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[17]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[18]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[19]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[20]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[21]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[22]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[23]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[24]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[25]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[26]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[27]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[28]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[29]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[30]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWADDR[31]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWID[0]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWID[1]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWID[2]}]
set_input_delay 2 -clock "OscClk" [get_ports {AWID[3]}]
set_input_delay 2 -clock "OscClk" [get_ports {ARESETn}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[0]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[1]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[2]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[3]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[4]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[5]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[6]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[7]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[8]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[9]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[10]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[11]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[12]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[13]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[14]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[15]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[16]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[17]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[18]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[19]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[20]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[21]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[22]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[23]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[24]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[25]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[26]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[27]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[28]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[29]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[30]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWDATA[31]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWEn[0]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWEn[1]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWEn[2]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMWEn[3]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMCEn}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[0]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[1]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[2]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[3]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[4]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[5]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[6]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[7]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[8]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[9]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[10]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[11]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[12]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[13]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[14]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[15]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[16]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[17]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[18]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[19]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[20]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[21]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[22]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[23]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[24]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[25]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[26]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[27]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[28]}]
set_output_delay 3 -clock "OscClk" [get_ports {MEMADDR[29]}]
set_output_delay 3 -clock "OscClk" [get_ports {RVALID}]
set_output_delay 3 -clock "OscClk" [get_ports {RLAST}]
set_output_delay 3 -clock "OscClk" [get_ports {RRESP[0]}]
set_output_delay 3 -clock "OscClk" [get_ports {RRESP[1]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[0]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[1]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[2]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[3]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[4]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[5]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[6]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[7]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[8]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[9]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[10]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[11]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[12]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[13]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[14]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[15]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[16]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[17]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[18]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[19]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[20]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[21]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[22]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[23]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[24]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[25]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[26]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[27]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[28]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[29]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[30]}]
set_output_delay 3 -clock "OscClk" [get_ports {RDATA[31]}]
set_output_delay 3 -clock "OscClk" [get_ports {RID[0]}]
set_output_delay 3 -clock "OscClk" [get_ports {RID[1]}]
set_output_delay 3 -clock "OscClk" [get_ports {RID[2]}]
set_output_delay 3 -clock "OscClk" [get_ports {RID[3]}]
set_output_delay 3 -clock "OscClk" [get_ports {ARREADY}]
set_output_delay 3 -clock "OscClk" [get_ports {BVALID}]
set_output_delay 3 -clock "OscClk" [get_ports {BRESP[0]}]
set_output_delay 3 -clock "OscClk" [get_ports {BRESP[1]}]
set_output_delay 3 -clock "OscClk" [get_ports {BID[0]}]
set_output_delay 3 -clock "OscClk" [get_ports {BID[1]}]
set_output_delay 3 -clock "OscClk" [get_ports {BID[2]}]
set_output_delay 3 -clock "OscClk" [get_ports {BID[3]}]
set_output_delay 3 -clock "OscClk" [get_ports {WREADY}]
set_output_delay 3 -clock "OscClk" [get_ports {AWREADY}]
set_clock_transition -rise 0.4 [get_clocks {OscClk}]
set_clock_transition -fall 0.4 [get_clocks {OscClk}]
set_clock_uncertainty  1.9 -setup [get_clocks {OscClk}]
set_max_fanout 16 [current_design]
set_max_transition 1 [current_design]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ACLK}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARESETn}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWID[3]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWID[2]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWID[1]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWID[0]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[31]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[30]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[29]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[28]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[27]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[26]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[25]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[24]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[23]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[22]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[21]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[20]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[19]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[18]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[17]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[16]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[15]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[14]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[13]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[12]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[11]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[10]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[9]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[8]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[7]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[6]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[5]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[4]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[3]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[2]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[1]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWADDR[0]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWLEN[3]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWLEN[2]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWLEN[1]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWLEN[0]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWSIZE[2]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWSIZE[1]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWSIZE[0]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWBURST[1]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWBURST[0]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {AWVALID}]
set_load -pin_load 0.1 [get_ports {AWREADY}]
set_load -min -pin_load 0.1 [get_ports {AWREADY}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WID[3]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WID[2]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WID[1]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WID[0]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[31]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[30]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[29]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[28]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[27]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[26]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[25]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[24]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[23]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[22]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[21]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[20]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[19]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[18]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[17]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[16]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[15]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[14]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[13]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[12]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[11]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[10]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[9]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[8]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[7]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[6]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[5]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[4]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[3]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[2]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[1]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WDATA[0]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WSTRB[3]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WSTRB[2]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WSTRB[1]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WSTRB[0]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WLAST}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {WVALID}]
set_load -pin_load 0.1 [get_ports {WREADY}]
set_load -min -pin_load 0.1 [get_ports {WREADY}]
set_load -pin_load 0.1 [get_ports {BID[3]}]
set_load -min -pin_load 0.1 [get_ports {BID[3]}]
set_load -pin_load 0.1 [get_ports {BID[2]}]
set_load -min -pin_load 0.1 [get_ports {BID[2]}]
set_load -pin_load 0.1 [get_ports {BID[1]}]
set_load -min -pin_load 0.1 [get_ports {BID[1]}]
set_load -pin_load 0.1 [get_ports {BID[0]}]
set_load -min -pin_load 0.1 [get_ports {BID[0]}]
set_load -pin_load 0.1 [get_ports {BRESP[1]}]
set_load -min -pin_load 0.1 [get_ports {BRESP[1]}]
set_load -pin_load 0.1 [get_ports {BRESP[0]}]
set_load -min -pin_load 0.1 [get_ports {BRESP[0]}]
set_load -pin_load 0.1 [get_ports {BVALID}]
set_load -min -pin_load 0.1 [get_ports {BVALID}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {BREADY}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARID[3]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARID[2]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARID[1]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARID[0]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[31]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[30]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[29]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[28]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[27]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[26]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[25]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[24]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[23]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[22]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[21]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[20]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[19]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[18]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[17]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[16]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[15]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[14]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[13]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[12]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[11]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[10]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[9]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[8]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[7]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[6]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[5]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[4]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[3]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[2]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[1]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARADDR[0]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARLEN[3]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARLEN[2]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARLEN[1]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARLEN[0]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARSIZE[2]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARSIZE[1]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARSIZE[0]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARBURST[1]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARBURST[0]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {ARVALID}]
set_load -pin_load 0.1 [get_ports {ARREADY}]
set_load -min -pin_load 0.1 [get_ports {ARREADY}]
set_load -pin_load 0.1 [get_ports {RID[3]}]
set_load -min -pin_load 0.1 [get_ports {RID[3]}]
set_load -pin_load 0.1 [get_ports {RID[2]}]
set_load -min -pin_load 0.1 [get_ports {RID[2]}]
set_load -pin_load 0.1 [get_ports {RID[1]}]
set_load -min -pin_load 0.1 [get_ports {RID[1]}]
set_load -pin_load 0.1 [get_ports {RID[0]}]
set_load -min -pin_load 0.1 [get_ports {RID[0]}]
set_load -pin_load 0.1 [get_ports {RDATA[31]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[31]}]
set_load -pin_load 0.1 [get_ports {RDATA[30]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[30]}]
set_load -pin_load 0.1 [get_ports {RDATA[29]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[29]}]
set_load -pin_load 0.1 [get_ports {RDATA[28]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[28]}]
set_load -pin_load 0.1 [get_ports {RDATA[27]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[27]}]
set_load -pin_load 0.1 [get_ports {RDATA[26]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[26]}]
set_load -pin_load 0.1 [get_ports {RDATA[25]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[25]}]
set_load -pin_load 0.1 [get_ports {RDATA[24]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[24]}]
set_load -pin_load 0.1 [get_ports {RDATA[23]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[23]}]
set_load -pin_load 0.1 [get_ports {RDATA[22]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[22]}]
set_load -pin_load 0.1 [get_ports {RDATA[21]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[21]}]
set_load -pin_load 0.1 [get_ports {RDATA[20]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[20]}]
set_load -pin_load 0.1 [get_ports {RDATA[19]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[19]}]
set_load -pin_load 0.1 [get_ports {RDATA[18]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[18]}]
set_load -pin_load 0.1 [get_ports {RDATA[17]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[17]}]
set_load -pin_load 0.1 [get_ports {RDATA[16]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[16]}]
set_load -pin_load 0.1 [get_ports {RDATA[15]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[15]}]
set_load -pin_load 0.1 [get_ports {RDATA[14]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[14]}]
set_load -pin_load 0.1 [get_ports {RDATA[13]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[13]}]
set_load -pin_load 0.1 [get_ports {RDATA[12]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[12]}]
set_load -pin_load 0.1 [get_ports {RDATA[11]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[11]}]
set_load -pin_load 0.1 [get_ports {RDATA[10]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[10]}]
set_load -pin_load 0.1 [get_ports {RDATA[9]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[9]}]
set_load -pin_load 0.1 [get_ports {RDATA[8]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[8]}]
set_load -pin_load 0.1 [get_ports {RDATA[7]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[7]}]
set_load -pin_load 0.1 [get_ports {RDATA[6]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[6]}]
set_load -pin_load 0.1 [get_ports {RDATA[5]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[5]}]
set_load -pin_load 0.1 [get_ports {RDATA[4]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[4]}]
set_load -pin_load 0.1 [get_ports {RDATA[3]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[3]}]
set_load -pin_load 0.1 [get_ports {RDATA[2]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[2]}]
set_load -pin_load 0.1 [get_ports {RDATA[1]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[1]}]
set_load -pin_load 0.1 [get_ports {RDATA[0]}]
set_load -min -pin_load 0.1 [get_ports {RDATA[0]}]
set_load -pin_load 0.1 [get_ports {RRESP[1]}]
set_load -min -pin_load 0.1 [get_ports {RRESP[1]}]
set_load -pin_load 0.1 [get_ports {RRESP[0]}]
set_load -min -pin_load 0.1 [get_ports {RRESP[0]}]
set_load -pin_load 0.1 [get_ports {RLAST}]
set_load -min -pin_load 0.1 [get_ports {RLAST}]
set_load -pin_load 0.1 [get_ports {RVALID}]
set_load -min -pin_load 0.1 [get_ports {RVALID}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {RREADY}]
set_load -pin_load 0.1 [get_ports {MEMADDR[29]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[29]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[28]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[28]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[27]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[27]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[26]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[26]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[25]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[25]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[24]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[24]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[23]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[23]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[22]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[22]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[21]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[21]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[20]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[20]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[19]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[19]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[18]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[18]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[17]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[17]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[16]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[16]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[15]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[15]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[14]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[14]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[13]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[13]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[12]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[12]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[11]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[11]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[10]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[10]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[9]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[9]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[8]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[8]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[7]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[7]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[6]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[6]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[5]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[5]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[4]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[4]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[3]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[3]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[2]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[2]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[1]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[1]}]
set_load -pin_load 0.1 [get_ports {MEMADDR[0]}]
set_load -min -pin_load 0.1 [get_ports {MEMADDR[0]}]
set_load -pin_load 0.1 [get_ports {MEMCEn}]
set_load -min -pin_load 0.1 [get_ports {MEMCEn}]
set_load -pin_load 0.1 [get_ports {MEMWEn[3]}]
set_load -min -pin_load 0.1 [get_ports {MEMWEn[3]}]
set_load -pin_load 0.1 [get_ports {MEMWEn[2]}]
set_load -min -pin_load 0.1 [get_ports {MEMWEn[2]}]
set_load -pin_load 0.1 [get_ports {MEMWEn[1]}]
set_load -min -pin_load 0.1 [get_ports {MEMWEn[1]}]
set_load -pin_load 0.1 [get_ports {MEMWEn[0]}]
set_load -min -pin_load 0.1 [get_ports {MEMWEn[0]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[31]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[30]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[29]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[28]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[27]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[26]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[25]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[24]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[23]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[22]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[21]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[20]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[19]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[18]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[17]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[16]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[15]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[14]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[13]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[12]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[11]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[10]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[9]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[8]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[7]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[6]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[5]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[4]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[3]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[2]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[1]}]
set_driving_cell -lib_cell DFFX1 -pin Q [get_ports {MEMRDATA[0]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[31]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[31]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[30]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[30]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[29]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[29]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[28]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[28]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[27]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[27]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[26]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[26]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[25]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[25]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[24]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[24]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[23]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[23]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[22]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[22]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[21]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[21]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[20]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[20]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[19]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[19]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[18]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[18]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[17]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[17]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[16]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[16]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[15]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[15]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[14]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[14]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[13]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[13]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[12]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[12]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[11]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[11]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[10]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[10]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[9]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[9]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[8]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[8]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[7]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[7]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[6]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[6]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[5]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[5]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[4]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[4]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[3]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[3]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[2]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[2]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[1]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[1]}]
set_load -pin_load 0.1 [get_ports {MEMWDATA[0]}]
set_load -min -pin_load 0.1 [get_ports {MEMWDATA[0]}]
