#####################################################

#  Created by Design Compiler write_sdc on Tue Apr 17 13:50:15 2007

#####################################################
set sdc_version 1.4

create_clock -period 20 -waveform {0 10} [get_ports {PCLK}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWDATA[0]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[0]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWDATA[1]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[1]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWDATA[2]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[2]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWDATA[3]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[3]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWDATA[4]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[4]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWDATA[5]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[5]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWDATA[6]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[6]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWDATA[7]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[7]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWDATA[8]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[8]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWDATA[9]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[9]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWDATA[10]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[10]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWDATA[11]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[11]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWDATA[12]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[12]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWDATA[13]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[13]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWDATA[14]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[14]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWDATA[15]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWDATA[15]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PWRITE}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PWRITE}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PENABLE}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PENABLE}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PSEL}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PSEL}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PADDR[2]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PADDR[2]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PADDR[3]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PADDR[3]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PADDR[4]}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PADDR[4]}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PRESETn}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PRESETn}]
set_input_delay 14 -max -clock "PCLK" [get_ports {PCLK}]
set_input_delay 0 -min -clock "PCLK" [get_ports {PCLK}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[0]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[0]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[1]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[1]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[2]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[2]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[3]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[3]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[4]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[4]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[5]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[5]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[6]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[6]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[7]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[7]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[8]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[8]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[9]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[9]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[10]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[10]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[11]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[11]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[12]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[12]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[13]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[13]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[14]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[14]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[15]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[15]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[16]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[16]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[17]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[17]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[18]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[18]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[19]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[19]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[20]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[20]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[21]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[21]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[22]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[22]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[23]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[23]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[24]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[24]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[25]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[25]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[26]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[26]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[27]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[27]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[28]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[28]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[29]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[29]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[30]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[30]}]
set_output_delay 12 -max -clock "PCLK" [get_ports {PRDATA[31]}]
set_output_delay -0 -min -clock "PCLK" [get_ports {PRDATA[31]}]
set_clock_transition -rise 0 [get_clocks {PCLK}]
set_clock_transition -fall 0 [get_clocks {PCLK}]
set_clock_uncertainty  1.3 -setup [get_ports {PCLK}]
set_max_transition 2 [current_design]
set_input_transition -max 1 [get_ports {PCLK}]
set_load -pin_load 0 [get_ports {PCLK}]
set_input_transition -max 1 [get_ports {PRESETn}]
set_load -pin_load 0 [get_ports {PRESETn}]
set_disable_timing [get_ports {PRESETn}]
set_input_transition -max 1 [get_ports {PADDR[4]}]
set_input_transition -max 1 [get_ports {PADDR[3]}]
set_input_transition -max 1 [get_ports {PADDR[2]}]
set_input_transition -max 1 [get_ports {PSEL}]
set_input_transition -max 1 [get_ports {PENABLE}]
set_input_transition -max 1 [get_ports {PWRITE}]
set_input_transition -max 1 [get_ports {PWDATA[15]}]
set_input_transition -max 1 [get_ports {PWDATA[14]}]
set_input_transition -max 1 [get_ports {PWDATA[13]}]
set_input_transition -max 1 [get_ports {PWDATA[12]}]
set_input_transition -max 1 [get_ports {PWDATA[11]}]
set_input_transition -max 1 [get_ports {PWDATA[10]}]
set_input_transition -max 1 [get_ports {PWDATA[9]}]
set_input_transition -max 1 [get_ports {PWDATA[8]}]
set_input_transition -max 1 [get_ports {PWDATA[7]}]
set_input_transition -max 1 [get_ports {PWDATA[6]}]
set_input_transition -max 1 [get_ports {PWDATA[5]}]
set_input_transition -max 1 [get_ports {PWDATA[4]}]
set_input_transition -max 1 [get_ports {PWDATA[3]}]
set_input_transition -max 1 [get_ports {PWDATA[2]}]
set_input_transition -max 1 [get_ports {PWDATA[1]}]
set_input_transition -max 1 [get_ports {PWDATA[0]}]
set_load -pin_load 0.018316 [get_ports {SSPINTR}]
set_load -min -pin_load 0.018316 [get_ports {SSPINTR}]
set_input_transition -max 1 [get_ports {SSPRXD}]
set_input_transition -max 1 [get_ports {SSPFSSIN}]
set_input_transition -max 1 [get_ports {SSPCLKIN}]
set_load -pin_load 0.018316 [get_ports {SSPFSSOUT}]
set_load -min -pin_load 0.018316 [get_ports {SSPFSSOUT}]
set_load -pin_load 0.018316 [get_ports {SSPCLKOUT}]
set_load -min -pin_load 0.018316 [get_ports {SSPCLKOUT}]
set_load -pin_load 0.018316 [get_ports {SSPTXD}]
set_load -min -pin_load 0.018316 [get_ports {SSPTXD}]
set_load -pin_load 0.018316 [get_ports {nSSPOE}]
set_load -min -pin_load 0.018316 [get_ports {nSSPOE}]
set_load -pin_load 0.018316 [get_ports {nSSPCTLOE}]
set_load -min -pin_load 0.018316 [get_ports {nSSPCTLOE}]
set_load -pin_load 0.018316 [get_ports {PRDATA[31]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[31]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[30]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[30]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[29]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[29]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[28]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[28]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[27]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[27]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[26]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[26]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[25]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[25]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[24]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[24]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[23]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[23]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[22]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[22]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[21]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[21]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[20]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[20]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[19]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[19]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[18]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[18]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[17]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[17]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[16]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[16]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[15]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[15]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[14]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[14]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[13]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[13]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[12]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[12]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[11]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[11]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[10]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[10]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[9]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[9]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[8]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[8]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[7]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[7]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[6]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[6]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[5]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[5]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[4]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[4]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[3]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[3]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[2]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[2]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[1]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[1]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[0]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[0]}]
set_load -pin_load 0.018316 [get_ports {TxDMAReq}]
set_load -min -pin_load 0.018316 [get_ports {TxDMAReq}]
set_load -pin_load 0.018316 [get_ports {RxDMAReq}]
set_load -min -pin_load 0.018316 [get_ports {RxDMAReq}]
set_resistance 0 [get_nets {PCLK}]
set_resistance 0 [get_nets {PRESETn}]
