// ARM7TDMIr3.v
//
// Verilog implementation of ARM7TDMIr3, generated by ModelGen

// Elements of the code in this file are
// Copyright 1993, 94-98, 1999 ARM Ltd,
// All rights reserved.

`timescale 1 ps / 1 ps

// Inout shell

module ARM7TDMI_inout (A,
  ABE,
  ABORT,
  ALE,
  APE,
  BIGEND,
  BL,
  BREAKPT,
  BUSDIS,
  BUSEN,
  COMMRX,
  COMMTX,
  CPA,
  CPB,
  D_xmgxread,
  D,
  DBE,
  DBGACK,
  DBGEN,
  DBGRQ,
  DBGRQI,
  DIN,
  DOUT,
  DRIVEBS,
  ECLK,
  ECAPCLK,
  ECAPCLKBS,
  EXTERN0,
  EXTERN1,
  HIGHZ,
  ICAPCLKBS,
  IR,
  ISYNC,
  LOCK,
  MAS,
  MCLK,
  nCPI,
  nENIN,
  nENOUT,
  nENOUTI,
  nEXEC,
  nFIQ,
  nHIGHZ,
  nIRQ,
  nM,
  nMREQ,
  nOPC,
  nRESET,
  nRW,
  nTDOEN,
  nTRANS,
  nTRST,
  nWAIT,
  PCLKBS,
  RANGEOUT0,
  RANGEOUT1,
  RSTCLKBS,
  SCREG,
  SDINBS,
  SDOUTBS,
  SEQ,
  SHCLKBS,
  SHCLK2BS,
  TAPSM,
  TBE,
  TBIT,
  TCK,
  TCK1,
  TCK2,
  TDI,
  TDO,
  TMS,
  r0,
  r1,
  r2,
  r3,
  r4,
  r5,
  r6,
  r7,
  r8,
  r9,
  r10,
  r11,
  r12,
  r13,
  r14,
  r15,
  r8fiq,
  r9fiq,
  r10fiq,
  r11fiq,
  r12fiq,
  r13fiq,
  r14fiq,
  r13irq,
  r14irq,
  r13svc,
  r14svc,
  r13abt,
  r14abt,
  r13und,
  r14und,
  CPSR,
  SPSRfiq,
  SPSRirq,
  SPSRsvc,
  SPSRabt,
  SPSRund,
  icewp0addr,
  icewp0amask,
  icewp0data,
  icewp0dmask,
  icewp0ctl,
  icewp0cmask,
  icewp1addr,
  icewp1amask,
  icewp1data,
  icewp1dmask,
  icewp1ctl,
  icewp1cmask,
  icedbgctl,
  icedbgstatus,
  normal,
  scan,
  dclk,
  dbg,
  hghz,
  testBus,
  testDBus,
  enterDbg,
  leavingscan,
  leavingdclk,
  scan1Dbg,
  scan0Dbg,
  sc2updatedr,
  reads,
  mem,
  busen1,
  isync1,
  bl3,
  bl2,
  bl1,
  bl0,
  capture048,
  capture0148);

output [31:0] A;
input ABE;
input ABORT;
input ALE;
input APE;
input BIGEND;
input [3:0] BL;
input BREAKPT;
output BUSDIS;
input BUSEN;
output COMMRX;
output COMMTX;
input CPA;
input CPB;
input [31:0] D_xmgxread;
output [31:0] D;
input DBE;
output DBGACK;
input DBGEN;
input DBGRQ;
output DBGRQI;
input [31:0] DIN;
output [31:0] DOUT;
output DRIVEBS;
output ECLK;
output ECAPCLK;
output ECAPCLKBS;
input EXTERN0;
input EXTERN1;
output HIGHZ;
output ICAPCLKBS;
output [3:0] IR;
input ISYNC;
output LOCK;
output [1:0] MAS;
input MCLK;
output nCPI;
input nENIN;
output nENOUT;
output nENOUTI;
output nEXEC;
input nFIQ;
output nHIGHZ;
input nIRQ;
output [4:0] nM;
output nMREQ;
output nOPC;
input nRESET;
output nRW;
output nTDOEN;
output nTRANS;
input nTRST;
input nWAIT;
output PCLKBS;
output RANGEOUT0;
output RANGEOUT1;
output RSTCLKBS;
output [3:0] SCREG;
output SDINBS;
input SDOUTBS;
output SEQ;
output SHCLKBS;
output SHCLK2BS;
output [3:0] TAPSM;
input TBE;
output TBIT;
input TCK;
output TCK1;
output TCK2;
input TDI;
output TDO;
input TMS;
output [31:0] r0;
output [31:0] r1;
output [31:0] r2;
output [31:0] r3;
output [31:0] r4;
output [31:0] r5;
output [31:0] r6;
output [31:0] r7;
output [31:0] r8;
output [31:0] r9;
output [31:0] r10;
output [31:0] r11;
output [31:0] r12;
output [31:0] r13;
output [31:0] r14;
output [31:0] r15;
output [31:0] r8fiq;
output [31:0] r9fiq;
output [31:0] r10fiq;
output [31:0] r11fiq;
output [31:0] r12fiq;
output [31:0] r13fiq;
output [31:0] r14fiq;
output [31:0] r13irq;
output [31:0] r14irq;
output [31:0] r13svc;
output [31:0] r14svc;
output [31:0] r13abt;
output [31:0] r14abt;
output [31:0] r13und;
output [31:0] r14und;
output [31:0] CPSR;
output [31:0] SPSRfiq;
output [31:0] SPSRirq;
output [31:0] SPSRsvc;
output [31:0] SPSRabt;
output [31:0] SPSRund;
output [31:0] icewp0addr;
output [31:0] icewp0amask;
output [31:0] icewp0data;
output [31:0] icewp0dmask;
output [8:0] icewp0ctl;
output [7:0] icewp0cmask;
output [31:0] icewp1addr;
output [31:0] icewp1amask;
output [31:0] icewp1data;
output [31:0] icewp1dmask;
output [8:0] icewp1ctl;
output [7:0] icewp1cmask;
output [2:0] icedbgctl;
output [3:0] icedbgstatus;
output normal;
output scan;
output dclk;
output dbg;
output hghz;
output testBus;
output testDBus;
output enterDbg;
output leavingscan;
output leavingdclk;
output scan1Dbg;
output scan0Dbg;
output sc2updatedr;
output reads;
output mem;
output busen1;
output isync1;
output bl3;
output bl2;
output bl1;
output bl0;
output capture048;
output capture0148;

reg [31:0] A;
reg BUSDIS;
reg COMMRX;
reg COMMTX;
reg [31:0] D;
reg DBGACK;
reg DBGRQI;
reg [31:0] DOUT;
reg DRIVEBS;
reg ECLK;
reg ECAPCLK;
reg ECAPCLKBS;
reg HIGHZ;
reg ICAPCLKBS;
reg [3:0] IR;
reg LOCK;
reg [1:0] MAS;
reg nCPI;
reg nENOUT;
reg nENOUTI;
reg nEXEC;
reg nHIGHZ;
reg [4:0] nM;
reg nMREQ;
reg nOPC;
reg nRW;
reg nTDOEN;
reg nTRANS;
reg PCLKBS;
reg RANGEOUT0;
reg RANGEOUT1;
reg RSTCLKBS;
reg [3:0] SCREG;
reg SDINBS;
reg SEQ;
reg SHCLKBS;
reg SHCLK2BS;
reg [3:0] TAPSM;
reg TBIT;
reg TCK1;
reg TCK2;
reg TDO;
reg [31:0] r0;
reg [31:0] r1;
reg [31:0] r2;
reg [31:0] r3;
reg [31:0] r4;
reg [31:0] r5;
reg [31:0] r6;
reg [31:0] r7;
reg [31:0] r8;
reg [31:0] r9;
reg [31:0] r10;
reg [31:0] r11;
reg [31:0] r12;
reg [31:0] r13;
reg [31:0] r14;
reg [31:0] r15;
reg [31:0] r8fiq;
reg [31:0] r9fiq;
reg [31:0] r10fiq;
reg [31:0] r11fiq;
reg [31:0] r12fiq;
reg [31:0] r13fiq;
reg [31:0] r14fiq;
reg [31:0] r13irq;
reg [31:0] r14irq;
reg [31:0] r13svc;
reg [31:0] r14svc;
reg [31:0] r13abt;
reg [31:0] r14abt;
reg [31:0] r13und;
reg [31:0] r14und;
reg [31:0] CPSR;
reg [31:0] SPSRfiq;
reg [31:0] SPSRirq;
reg [31:0] SPSRsvc;
reg [31:0] SPSRabt;
reg [31:0] SPSRund;
reg [31:0] icewp0addr;
reg [31:0] icewp0amask;
reg [31:0] icewp0data;
reg [31:0] icewp0dmask;
reg [8:0] icewp0ctl;
reg [7:0] icewp0cmask;
reg [31:0] icewp1addr;
reg [31:0] icewp1amask;
reg [31:0] icewp1data;
reg [31:0] icewp1dmask;
reg [8:0] icewp1ctl;
reg [7:0] icewp1cmask;
reg [2:0] icedbgctl;
reg [3:0] icedbgstatus;
reg normal;
reg scan;
reg dclk;
reg dbg;
reg hghz;
reg testBus;
reg testDBus;
reg enterDbg;
reg leavingscan;
reg leavingdclk;
reg scan1Dbg;
reg scan0Dbg;
reg sc2updatedr;
reg reads;
reg mem;
reg busen1;
reg isync1;
reg bl3;
reg bl2;
reg bl1;
reg bl0;
reg capture048;
reg capture0148;
initial
  begin
    $mm("ARM7TDMIr3?rev=r3",A,
    ABE,
    ABORT,
    ALE,
    APE,
    BIGEND,
    BL,
    BREAKPT,
    BUSDIS,
    BUSEN,
    COMMRX,
    COMMTX,
    CPA,
    CPB,
    D_xmgxread,
    D,
    DBE,
    DBGACK,
    DBGEN,
    DBGRQ,
    DBGRQI,
    DIN,
    DOUT,
    DRIVEBS,
    ECLK,
    ECAPCLK,
    ECAPCLKBS,
    EXTERN0,
    EXTERN1,
    HIGHZ,
    ICAPCLKBS,
    IR,
    ISYNC,
    LOCK,
    MAS,
    MCLK,
    nCPI,
    nENIN,
    nENOUT,
    nENOUTI,
    nEXEC,
    nFIQ,
    nHIGHZ,
    nIRQ,
    nM,
    nMREQ,
    nOPC,
    nRESET,
    nRW,
    nTDOEN,
    nTRANS,
    nTRST,
    nWAIT,
    PCLKBS,
    RANGEOUT0,
    RANGEOUT1,
    RSTCLKBS,
    SCREG,
    SDINBS,
    SDOUTBS,
    SEQ,
    SHCLKBS,
    SHCLK2BS,
    TAPSM,
    TBE,
    TBIT,
    TCK,
    TCK1,
    TCK2,
    TDI,
    TDO,
    TMS,
    r0,
    r1,
    r2,
    r3,
    r4,
    r5,
    r6,
    r7,
    r8,
    r9,
    r10,
    r11,
    r12,
    r13,
    r14,
    r15,
    r8fiq,
    r9fiq,
    r10fiq,
    r11fiq,
    r12fiq,
    r13fiq,
    r14fiq,
    r13irq,
    r14irq,
    r13svc,
    r14svc,
    r13abt,
    r14abt,
    r13und,
    r14und,
    CPSR,
    SPSRfiq,
    SPSRirq,
    SPSRsvc,
    SPSRabt,
    SPSRund,
    icewp0addr,
    icewp0amask,
    icewp0data,
    icewp0dmask,
    icewp0ctl,
    icewp0cmask,
    icewp1addr,
    icewp1amask,
    icewp1data,
    icewp1dmask,
    icewp1ctl,
    icewp1cmask,
    icedbgctl,
    icedbgstatus,
    normal,
    scan,
    dclk,
    dbg,
    hghz,
    testBus,
    testDBus,
    enterDbg,
    leavingscan,
    leavingdclk,
    scan1Dbg,
    scan0Dbg,
    sc2updatedr,
    reads,
    mem,
    busen1,
    isync1,
    bl3,
    bl2,
    bl1,
    bl0,
    capture048,
    capture0148);
  end

endmodule

// Timing shell

module ARM7TDMI_timing (A,
  ABE,
  ABORT,
  ALE,
  APE,
  BIGEND,
  BL,
  BREAKPT,
  BUSDIS,
  BUSEN,
  COMMRX,
  COMMTX,
  CPA,
  CPB,
  D,
  DBE,
  DBGACK,
  DBGEN,
  DBGRQ,
  DBGRQI,
  DIN,
  DOUT,
  DRIVEBS,
  ECLK,
  ECAPCLK,
  ECAPCLKBS,
  EXTERN0,
  EXTERN1,
  HIGHZ,
  ICAPCLKBS,
  IR,
  ISYNC,
  LOCK,
  MAS,
  MCLK,
  nCPI,
  nENIN,
  nENOUT,
  nENOUTI,
  nEXEC,
  nFIQ,
  nHIGHZ,
  nIRQ,
  nM,
  nMREQ,
  nOPC,
  nRESET,
  nRW,
  nTDOEN,
  nTRANS,
  nTRST,
  nWAIT,
  PCLKBS,
  RANGEOUT0,
  RANGEOUT1,
  RSTCLKBS,
  SCREG,
  SDINBS,
  SDOUTBS,
  SEQ,
  SHCLKBS,
  SHCLK2BS,
  TAPSM,
  TBE,
  TBIT,
  TCK,
  TCK1,
  TCK2,
  TDI,
  TDO,
  TMS,
  r0,
  r1,
  r2,
  r3,
  r4,
  r5,
  r6,
  r7,
  r8,
  r9,
  r10,
  r11,
  r12,
  r13,
  r14,
  r15,
  r8fiq,
  r9fiq,
  r10fiq,
  r11fiq,
  r12fiq,
  r13fiq,
  r14fiq,
  r13irq,
  r14irq,
  r13svc,
  r14svc,
  r13abt,
  r14abt,
  r13und,
  r14und,
  CPSR,
  SPSRfiq,
  SPSRirq,
  SPSRsvc,
  SPSRabt,
  SPSRund,
  icewp0addr,
  icewp0amask,
  icewp0data,
  icewp0dmask,
  icewp0ctl,
  icewp0cmask,
  icewp1addr,
  icewp1amask,
  icewp1data,
  icewp1dmask,
  icewp1ctl,
  icewp1cmask,
  icedbgctl,
  icedbgstatus);

output [31:0] A;
input ABE;
input ABORT;
input ALE;
input APE;
input BIGEND;
input [3:0] BL;
input BREAKPT;
output BUSDIS;
input BUSEN;
output COMMRX;
output COMMTX;
input CPA;
input CPB;
inout [31:0] D;
input DBE;
output DBGACK;
input DBGEN;
input DBGRQ;
output DBGRQI;
input [31:0] DIN;
output [31:0] DOUT;
output DRIVEBS;
output ECLK;
output ECAPCLK;
output ECAPCLKBS;
input EXTERN0;
input EXTERN1;
output HIGHZ;
output ICAPCLKBS;
output [3:0] IR;
input ISYNC;
output LOCK;
output [1:0] MAS;
input MCLK;
output nCPI;
input nENIN;
output nENOUT;
output nENOUTI;
output nEXEC;
input nFIQ;
output nHIGHZ;
input nIRQ;
output [4:0] nM;
output nMREQ;
output nOPC;
input nRESET;
output nRW;
output nTDOEN;
output nTRANS;
input nTRST;
input nWAIT;
output PCLKBS;
output RANGEOUT0;
output RANGEOUT1;
output RSTCLKBS;
output [3:0] SCREG;
output SDINBS;
input SDOUTBS;
output SEQ;
output SHCLKBS;
output SHCLK2BS;
output [3:0] TAPSM;
input TBE;
output TBIT;
input TCK;
output TCK1;
output TCK2;
input TDI;
output TDO;
input TMS;
output [31:0] r0;
output [31:0] r1;
output [31:0] r2;
output [31:0] r3;
output [31:0] r4;
output [31:0] r5;
output [31:0] r6;
output [31:0] r7;
output [31:0] r8;
output [31:0] r9;
output [31:0] r10;
output [31:0] r11;
output [31:0] r12;
output [31:0] r13;
output [31:0] r14;
output [31:0] r15;
output [31:0] r8fiq;
output [31:0] r9fiq;
output [31:0] r10fiq;
output [31:0] r11fiq;
output [31:0] r12fiq;
output [31:0] r13fiq;
output [31:0] r14fiq;
output [31:0] r13irq;
output [31:0] r14irq;
output [31:0] r13svc;
output [31:0] r14svc;
output [31:0] r13abt;
output [31:0] r14abt;
output [31:0] r13und;
output [31:0] r14und;
output [31:0] CPSR;
output [31:0] SPSRfiq;
output [31:0] SPSRirq;
output [31:0] SPSRsvc;
output [31:0] SPSRabt;
output [31:0] SPSRund;
output [31:0] icewp0addr;
output [31:0] icewp0amask;
output [31:0] icewp0data;
output [31:0] icewp0dmask;
output [8:0] icewp0ctl;
output [7:0] icewp0cmask;
output [31:0] icewp1addr;
output [31:0] icewp1amask;
output [31:0] icewp1data;
output [31:0] icewp1dmask;
output [8:0] icewp1ctl;
output [7:0] icewp1cmask;
output [2:0] icedbgctl;
output [3:0] icedbgstatus;

// Connect up INOUTs:

wire [31:0] D_xmgxread;
assign D_xmgxread = D;

// Unused ports:

wire normal;
wire scan;
wire dclk;
wire dbg;
wire hghz;
wire testBus;
wire testDBus;
wire enterDbg;
wire leavingscan;
wire leavingdclk;
wire scan1Dbg;
wire scan0Dbg;
wire sc2updatedr;
wire reads;
wire mem;
wire busen1;
wire isync1;
wire bl3;
wire bl2;
wire bl1;
wire bl0;
wire capture048;
wire capture0148;

ARM7TDMI_inout theinout (A,
    ABE,
    ABORT,
    ALE,
    APE,
    BIGEND,
    BL,
    BREAKPT,
    BUSDIS,
    BUSEN,
    COMMRX,
    COMMTX,
    CPA,
    CPB,
    D_xmgxread,
    D,
    DBE,
    DBGACK,
    DBGEN,
    DBGRQ,
    DBGRQI,
    DIN,
    DOUT,
    DRIVEBS,
    ECLK,
    ECAPCLK,
    ECAPCLKBS,
    EXTERN0,
    EXTERN1,
    HIGHZ,
    ICAPCLKBS,
    IR,
    ISYNC,
    LOCK,
    MAS,
    MCLK,
    nCPI,
    nENIN,
    nENOUT,
    nENOUTI,
    nEXEC,
    nFIQ,
    nHIGHZ,
    nIRQ,
    nM,
    nMREQ,
    nOPC,
    nRESET,
    nRW,
    nTDOEN,
    nTRANS,
    nTRST,
    nWAIT,
    PCLKBS,
    RANGEOUT0,
    RANGEOUT1,
    RSTCLKBS,
    SCREG,
    SDINBS,
    SDOUTBS,
    SEQ,
    SHCLKBS,
    SHCLK2BS,
    TAPSM,
    TBE,
    TBIT,
    TCK,
    TCK1,
    TCK2,
    TDI,
    TDO,
    TMS,
    r0,
    r1,
    r2,
    r3,
    r4,
    r5,
    r6,
    r7,
    r8,
    r9,
    r10,
    r11,
    r12,
    r13,
    r14,
    r15,
    r8fiq,
    r9fiq,
    r10fiq,
    r11fiq,
    r12fiq,
    r13fiq,
    r14fiq,
    r13irq,
    r14irq,
    r13svc,
    r14svc,
    r13abt,
    r14abt,
    r13und,
    r14und,
    CPSR,
    SPSRfiq,
    SPSRirq,
    SPSRsvc,
    SPSRabt,
    SPSRund,
    icewp0addr,
    icewp0amask,
    icewp0data,
    icewp0dmask,
    icewp0ctl,
    icewp0cmask,
    icewp1addr,
    icewp1amask,
    icewp1data,
    icewp1dmask,
    icewp1ctl,
    icewp1cmask,
    icedbgctl,
    icedbgstatus,
    normal,
    scan,
    dclk,
    dbg,
    hghz,
    testBus,
    testDBus,
    enterDbg,
    leavingscan,
    leavingdclk,
    scan1Dbg,
    scan0Dbg,
    sc2updatedr,
    reads,
    mem,
    busen1,
    isync1,
    bl3,
    bl2,
    bl1,
    bl0,
    capture048,
    capture0148);

endmodule

// Debug shell

module ARM7TDMIr3 (A,
  ABE,
  ABORT,
  ALE,
  APE,
  BIGEND,
  BL,
  BREAKPT,
  BUSDIS,
  BUSEN,
  COMMRX,
  COMMTX,
  CPA,
  CPB,
  D,
  DBE,
  DBGACK,
  DBGEN,
  DBGRQ,
  DBGRQI,
  DIN,
  DOUT,
  DRIVEBS,
  ECLK,
  ECAPCLK,
  ECAPCLKBS,
  EXTERN0,
  EXTERN1,
  HIGHZ,
  ICAPCLKBS,
  IR,
  ISYNC,
  LOCK,
  MAS,
  MCLK,
  nCPI,
  nENIN,
  nENOUT,
  nENOUTI,
  nEXEC,
  nFIQ,
  nHIGHZ,
  nIRQ,
  nM,
  nMREQ,
  nOPC,
  nRESET,
  nRW,
  nTDOEN,
  nTRANS,
  nTRST,
  nWAIT,
  PCLKBS,
  RANGEOUT0,
  RANGEOUT1,
  RSTCLKBS,
  SCREG,
  SDINBS,
  SDOUTBS,
  SEQ,
  SHCLKBS,
  SHCLK2BS,
  TAPSM,
  TBE,
  TBIT,
  TCK,
  TCK1,
  TCK2,
  TDI,
  TDO,
  TMS);

output [31:0] A;
input ABE;
input ABORT;
input ALE;
input APE;
input BIGEND;
input [3:0] BL;
input BREAKPT;
output BUSDIS;
input BUSEN;
output COMMRX;
output COMMTX;
input CPA;
input CPB;
inout [31:0] D;
input DBE;
output DBGACK;
input DBGEN;
input DBGRQ;
output DBGRQI;
input [31:0] DIN;
output [31:0] DOUT;
output DRIVEBS;
output ECLK;
output ECAPCLK;
output ECAPCLKBS;
input EXTERN0;
input EXTERN1;
output HIGHZ;
output ICAPCLKBS;
output [3:0] IR;
input ISYNC;
output LOCK;
output [1:0] MAS;
input MCLK;
output nCPI;
input nENIN;
output nENOUT;
output nENOUTI;
output nEXEC;
input nFIQ;
output nHIGHZ;
input nIRQ;
output [4:0] nM;
output nMREQ;
output nOPC;
input nRESET;
output nRW;
output nTDOEN;
output nTRANS;
input nTRST;
input nWAIT;
output PCLKBS;
output RANGEOUT0;
output RANGEOUT1;
output RSTCLKBS;
output [3:0] SCREG;
output SDINBS;
input SDOUTBS;
output SEQ;
output SHCLKBS;
output SHCLK2BS;
output [3:0] TAPSM;
input TBE;
output TBIT;
input TCK;
output TCK1;
output TCK2;
input TDI;
output TDO;
input TMS;


// Unused ports:

wire [31:0] r0;
wire [31:0] r1;
wire [31:0] r2;
wire [31:0] r3;
wire [31:0] r4;
wire [31:0] r5;
wire [31:0] r6;
wire [31:0] r7;
wire [31:0] r8;
wire [31:0] r9;
wire [31:0] r10;
wire [31:0] r11;
wire [31:0] r12;
wire [31:0] r13;
wire [31:0] r14;
wire [31:0] r15;
wire [31:0] r8fiq;
wire [31:0] r9fiq;
wire [31:0] r10fiq;
wire [31:0] r11fiq;
wire [31:0] r12fiq;
wire [31:0] r13fiq;
wire [31:0] r14fiq;
wire [31:0] r13irq;
wire [31:0] r14irq;
wire [31:0] r13svc;
wire [31:0] r14svc;
wire [31:0] r13abt;
wire [31:0] r14abt;
wire [31:0] r13und;
wire [31:0] r14und;
wire [31:0] CPSR;
wire [31:0] SPSRfiq;
wire [31:0] SPSRirq;
wire [31:0] SPSRsvc;
wire [31:0] SPSRabt;
wire [31:0] SPSRund;
wire [31:0] icewp0addr;
wire [31:0] icewp0amask;
wire [31:0] icewp0data;
wire [31:0] icewp0dmask;
wire [8:0] icewp0ctl;
wire [7:0] icewp0cmask;
wire [31:0] icewp1addr;
wire [31:0] icewp1amask;
wire [31:0] icewp1data;
wire [31:0] icewp1dmask;
wire [8:0] icewp1ctl;
wire [7:0] icewp1cmask;
wire [2:0] icedbgctl;
wire [3:0] icedbgstatus;

parameter
  MG_LOGFILE_NAME = "",
  ARM7TDMI_TimingFile = "./ARM7TDMIr3.tdef",
  MG_ENABLE_BUILTIN_TIMING = 1;

ARM7TDMI_timing thetiming (A,
    ABE,
    ABORT,
    ALE,
    APE,
    BIGEND,
    BL,
    BREAKPT,
    BUSDIS,
    BUSEN,
    COMMRX,
    COMMTX,
    CPA,
    CPB,
    D,
    DBE,
    DBGACK,
    DBGEN,
    DBGRQ,
    DBGRQI,
    DIN,
    DOUT,
    DRIVEBS,
    ECLK,
    ECAPCLK,
    ECAPCLKBS,
    EXTERN0,
    EXTERN1,
    HIGHZ,
    ICAPCLKBS,
    IR,
    ISYNC,
    LOCK,
    MAS,
    MCLK,
    nCPI,
    nENIN,
    nENOUT,
    nENOUTI,
    nEXEC,
    nFIQ,
    nHIGHZ,
    nIRQ,
    nM,
    nMREQ,
    nOPC,
    nRESET,
    nRW,
    nTDOEN,
    nTRANS,
    nTRST,
    nWAIT,
    PCLKBS,
    RANGEOUT0,
    RANGEOUT1,
    RSTCLKBS,
    SCREG,
    SDINBS,
    SDOUTBS,
    SEQ,
    SHCLKBS,
    SHCLK2BS,
    TAPSM,
    TBE,
    TBIT,
    TCK,
    TCK1,
    TCK2,
    TDI,
    TDO,
    TMS,
    r0,
    r1,
    r2,
    r3,
    r4,
    r5,
    r6,
    r7,
    r8,
    r9,
    r10,
    r11,
    r12,
    r13,
    r14,
    r15,
    r8fiq,
    r9fiq,
    r10fiq,
    r11fiq,
    r12fiq,
    r13fiq,
    r14fiq,
    r13irq,
    r14irq,
    r13svc,
    r14svc,
    r13abt,
    r14abt,
    r13und,
    r14und,
    CPSR,
    SPSRfiq,
    SPSRirq,
    SPSRsvc,
    SPSRabt,
    SPSRund,
    icewp0addr,
    icewp0amask,
    icewp0data,
    icewp0dmask,
    icewp0ctl,
    icewp0cmask,
    icewp1addr,
    icewp1amask,
    icewp1data,
    icewp1dmask,
    icewp1ctl,
    icewp1cmask,
    icedbgctl,
    icedbgstatus);

endmodule

