            cp /user/jys/SoC_Design/ARM7TDMI/ARM7TDMI_serial/models/cadence_xl_verilog/ARM7TDMIr3.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/A7TDMI/verilog/rtl_source/A7TWrapCtrl.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/A7TDMI/verilog/rtl_source/A7TWrapTest.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/A7TDMI/verilog/rtl_source/A7WrapMaster.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/A7TDMI/verilog/rtl_source/A7WrapSM.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/A7TDMI/verilog/rtl_source/A7TWrap.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/A7TDMI/verilog/rtl_source/A7TDMI.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/Ahb2Ahb/verilog/rtl_source/Ahb2Lite.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/Ahb2Ahb/verilog/rtl_source/Ahb2Ahb.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/EASY_ARM7/verilog/rtl_source/EASY_ARM7.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/EgAPBSlave/verilog/rtl_source/EgAPBSlave.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/EgMaster/verilog/rtl_source/EgMasterCore.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/EgMaster/verilog/rtl_source/EgMaster.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/ElementsAHB/verilog/rtl_source/ArbSchm3.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/ElementsAHB/verilog/rtl_source/Arbiter3.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/ElementsAHB/verilog/rtl_source/MuxS2M.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/ElementsAHB/verilog/rtl_source/MuxM2S.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/ElementsAHB/verilog/rtl_source/DefaultSlave.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/ElementsAHB/verilog/rtl_source/Decoder.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/ElementsAPB/verilog/rtl_source/MuxP2B.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/ElementsAPB/verilog/rtl_source/APBif.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/ExternalMemory/verilog/rtl_source/ExtRAM.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/ExternalMemory/verilog/rtl_source/ExtROM.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/ExternalMemory/verilog/rtl_source/Memory.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/InternalMemory/verilog/rtl_source/IntMem.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/Interrupt/verilog/rtl_source/ICAhbifReg.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/Interrupt/verilog/rtl_source/ICPriority.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/Interrupt/verilog/rtl_source/ICSynctoHCLK.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/Interrupt/verilog/rtl_source/Interrupt.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/RemapPause/verilog/rtl_source/RemapPause.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/ResetCntl/verilog/rtl_source/ResetCntl.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/RetrySlave/verilog/rtl_source/RetrySlave.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/SMI/verilog/rtl_source/SmiCore.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/SMI/verilog/rtl_source/SmiDBI.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/SMI/verilog/rtl_source/TIC.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/SMI/verilog/rtl_source/SMI.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/Timers/verilog/rtl_source/*.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/Timers/verilog/rtl_source/TimersFrc.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/Timers/verilog/rtl_source/Timers.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/Tube/verilog/rtl_source/Tube.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/Watchdog/verilog/rtl_source/*.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/Watchdog/verilog/rtl_source/WdogFrc.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/Watchdog/verilog/rtl_source/Watchdog.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/gpio_pl061/verilog/rtl_source/GpioApbif.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/gpio_pl061/verilog/rtl_source/GpioAfm.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/gpio_pl061/verilog/rtl_source/GpioInt.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/gpio_pl061/verilog/rtl_source/GpioRevAnd.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/gpio_pl061/verilog/rtl_source/Gpio.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/TBEasy_ARM7/verilog/rtl_source/TBEasy_ARM7.v .
            cp /user/jys/PRE_ARM/Twin_ARM/ARM_ADK_REL1v1/design/global_ADK/verilog/*.v .
