library verilog;
use verilog.vl_types.all;
entity SEIP is
    port(
        WEMDO           : in     vl_logic_vector(7 downto 0);
        PIA             : in     vl_logic_vector(10 downto 0);
        PIDI            : in     vl_logic_vector(15 downto 0);
        EEMDO           : in     vl_logic_vector(15 downto 0);
        RXD             : in     vl_logic_vector(31 downto 0);
        WIMD            : in     vl_logic_vector(15 downto 0);
        TIMO            : in     vl_logic_vector(23 downto 0);
        EIMO            : in     vl_logic_vector(15 downto 0);
        TROMO           : in     vl_logic_vector(7 downto 0);
        SDI1            : in     vl_logic;
        TI4             : in     vl_logic;
        TXRDY           : in     vl_logic;
        MCK             : in     vl_logic;
        XRST            : in     vl_logic;
        TE              : in     vl_logic;
        TI0             : in     vl_logic;
        TI3             : in     vl_logic;
        TI2             : in     vl_logic;
        TI1             : in     vl_logic;
        RXWE            : in     vl_logic;
        SDI2            : in     vl_logic;
        XPOE            : in     vl_logic;
        XPWE            : in     vl_logic;
        PIDO            : out    vl_logic_vector(15 downto 0);
        WEMDI           : out    vl_logic_vector(7 downto 0);
        WEMA            : out    vl_logic_vector(23 downto 0);
        EEMA            : out    vl_logic_vector(15 downto 0);
        EEMDI           : out    vl_logic_vector(15 downto 0);
        TXD             : out    vl_logic_vector(31 downto 0);
        WIMA            : out    vl_logic_vector(8 downto 0);
        WIMDI           : out    vl_logic_vector(15 downto 0);
        TIMA            : out    vl_logic_vector(8 downto 0);
        TIMI            : out    vl_logic_vector(23 downto 0);
        TROMA           : out    vl_logic_vector(8 downto 0);
        EIMDI           : out    vl_logic_vector(15 downto 0);
        EIMA            : out    vl_logic_vector(7 downto 0);
        XEEMCE          : out    vl_logic;
        XEIMCE          : out    vl_logic;
        XTROMCE         : out    vl_logic;
        XTIMCE          : out    vl_logic;
        XWIMCE          : out    vl_logic;
        XEIMWE          : out    vl_logic;
        XTIMWE          : out    vl_logic;
        XWIMWE          : out    vl_logic;
        EXMBIH          : out    vl_logic;
        SCKO            : out    vl_logic;
        TO4             : out    vl_logic;
        ADMCK           : out    vl_logic;
        TO0             : out    vl_logic;
        PRDY            : out    vl_logic;
        TO1             : out    vl_logic;
        LRCKO           : out    vl_logic;
        TO3             : out    vl_logic;
        TO2             : out    vl_logic;
        SD2O            : out    vl_logic;
        SD1O            : out    vl_logic;
        TXSYNC          : out    vl_logic;
        TXRD            : out    vl_logic;
        RXSYNC          : out    vl_logic;
        RXRDY           : out    vl_logic;
        MLRCK           : out    vl_logic;
        MSCK            : out    vl_logic;
        XEEMWE          : out    vl_logic;
        XWEMWE          : out    vl_logic;
        XWEMOC          : out    vl_logic
    );
end SEIP;
