library verilog;
use verilog.vl_types.all;
entity ESPSQ is
    port(
        XRST            : in     vl_logic;
        TE              : in     vl_logic;
        TI              : in     vl_logic;
        MCK             : in     vl_logic;
        TSCST           : in     vl_logic;
        ESYNC           : in     vl_logic;
        ENP             : in     vl_logic;
        PMA             : in     vl_logic_vector(7 downto 0);
        RXESEN          : in     vl_logic;
        PCEBEN          : in     vl_logic;
        SURDEN          : in     vl_logic;
        EEMADCL         : out    vl_logic;
        EEMDS           : out    vl_logic;
        EEMDOLE         : out    vl_logic;
        EOBLE           : out    vl_logic;
        EEMALE          : out    vl_logic;
        XEEMWE          : out    vl_logic;
        ESCST           : out    vl_logic;
        EIMA            : out    vl_logic_vector(7 downto 0);
        \TO\            : out    vl_logic;
        EYLE            : out    vl_logic;
        EXLE            : out    vl_logic;
        EALE            : out    vl_logic;
        EBLE            : out    vl_logic;
        LFACLLE         : out    vl_logic;
        DTLE            : out    vl_logic;
        EQACCL          : out    vl_logic;
        TXLDLE          : out    vl_logic;
        TXRDLE          : out    vl_logic;
        ESSCL           : out    vl_logic;
        ESSCE           : out    vl_logic;
        EQACCE          : out    vl_logic;
        EOLE            : out    vl_logic;
        EQACLE          : out    vl_logic;
        ERLE            : out    vl_logic;
        ETLE            : out    vl_logic;
        EIMWE           : out    vl_logic;
        EROALE          : out    vl_logic;
        ETOEN           : out    vl_logic;
        EPSOEN          : out    vl_logic;
        EPOEN           : out    vl_logic;
        ET1EN           : out    vl_logic;
        ET0EN           : out    vl_logic;
        EXHEN           : out    vl_logic;
        EIMOEN          : out    vl_logic;
        MCHS            : out    vl_logic;
        ESSDEN          : out    vl_logic;
        SIEXS           : out    vl_logic;
        EXLRS           : out    vl_logic;
        EXTIEN          : out    vl_logic;
        ERS2            : out    vl_logic;
        ERS1            : out    vl_logic;
        EROEN           : out    vl_logic;
        EQACS0          : out    vl_logic;
        EQOEN           : out    vl_logic;
        ET5EN           : out    vl_logic;
        ET4EN           : out    vl_logic;
        ET3EN           : out    vl_logic;
        ET2EN           : out    vl_logic;
        EPAEN           : out    vl_logic;
        EAIVEN          : out    vl_logic;
        EOS1            : out    vl_logic;
        EOS0            : out    vl_logic;
        EOOEN           : out    vl_logic;
        ERLRS           : out    vl_logic;
        LFACLS          : out    vl_logic;
        EMSFEN          : out    vl_logic;
        DTEN            : out    vl_logic;
        EXEXEN          : out    vl_logic;
        PBSD4           : out    vl_logic;
        EPWEN           : out    vl_logic;
        EROMAS          : out    vl_logic;
        INC16           : out    vl_logic;
        ESLMTEN         : out    vl_logic;
        SAWPHEN         : out    vl_logic;
        SFTEN           : out    vl_logic;
        REPHEN          : out    vl_logic;
        ABSEN           : out    vl_logic;
        EPSFT2          : out    vl_logic;
        EPBSU           : out    vl_logic
    );
end ESPSQ;
