#-------------------------------------------------------------------------------
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from ARM Limited
#   (C) COPYRIGHT 1999 ARM Limited
#       ALL RIGHTS RESERVED
# The entire notice above must be reproduced on all authorised
# copies and copies may only be made to the extent permitted
# by a licensing agreement from ARM Limited.
#-------------------------------------------------------------------------------
# 
# Version and Release Control Information:
# 
# File Name              : makefile,v
# File Revision          : 1.2
# 
# Release Information    : PL160-REL1v1
# 
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Purpose : Standard VHDL Library Makefile  
#-------------------------------------------------------------------------------

MODULES = linedrv.vhd reg.vhd viregcyc_drivers.vhd  vregbank.vhd vio_driver.vhd

include ../modeltech/StdMakefile.mk

#------------------------------------- End -------------------------------------
