library verilog;
use verilog.vl_types.all;
entity dmacchannel is
    port(
        hclk            : in     vl_logic;
        hresetn         : in     vl_logic;
        masteraddressm1 : in     vl_logic_vector(31 downto 0);
        masteraddressm2 : in     vl_logic_vector(31 downto 0);
        chwrdatam1      : in     vl_logic_vector(31 downto 0);
        chwrdatam2      : in     vl_logic_vector(31 downto 0);
        busavlblm1      : in     vl_logic;
        busavlblm2      : in     vl_logic;
        dataerrorm1     : in     vl_logic;
        dataerrorm2     : in     vl_logic;
        xferabortedm1   : in     vl_logic;
        xferabortedm2   : in     vl_logic;
        reghwrite       : in     vl_logic;
        regaddress      : in     vl_logic_vector(4 downto 2);
        dmacchannelsel  : in     vl_logic;
        hwdata          : in     vl_logic_vector(31 downto 0);
        clrinttc        : in     vl_logic;
        clrinterr       : in     vl_logic;
        dmacbreqch      : in     vl_logic_vector(15 downto 0);
        dmaclbreqch     : in     vl_logic_vector(15 downto 0);
        dmacsreqch      : in     vl_logic_vector(15 downto 0);
        dmaclsreqch     : in     vl_logic_vector(15 downto 0);
        dmacen          : in     vl_logic;
        chgntm1         : in     vl_logic;
        chgntm2         : in     vl_logic;
        chhrdata        : out    vl_logic_vector(31 downto 0);
        channelen       : out    vl_logic;
        interrch        : out    vl_logic;
        inttcch         : out    vl_logic;
        rawinterrch     : out    vl_logic;
        rawinttcch      : out    vl_logic;
        clearreq        : out    vl_logic_vector(15 downto 0);
        sigtc           : out    vl_logic_vector(15 downto 0);
        errclrreq       : out    vl_logic_vector(15 downto 0);
        chlock          : out    vl_logic;
        chnumofxfersm1  : out    vl_logic_vector(4 downto 0);
        chreqm1         : out    vl_logic;
        chincrm1        : out    vl_logic;
        chaddrm1        : out    vl_logic_vector(31 downto 0);
        chprotm1        : out    vl_logic_vector(2 downto 0);
        chwidthm1       : out    vl_logic_vector(2 downto 0);
        chdirxnm1       : out    vl_logic;
        chxferabortm1   : out    vl_logic;
        chhwdatam1      : out    vl_logic_vector(31 downto 0);
        chnumofxfersm2  : out    vl_logic_vector(4 downto 0);
        chreqm2         : out    vl_logic;
        chincrm2        : out    vl_logic;
        chaddrm2        : out    vl_logic_vector(31 downto 0);
        chprotm2        : out    vl_logic_vector(2 downto 0);
        chwidthm2       : out    vl_logic_vector(2 downto 0);
        chdirxnm2       : out    vl_logic;
        chxferabortm2   : out    vl_logic;
        chhwdatam2      : out    vl_logic_vector(31 downto 0)
    );
end dmacchannel;
