@TM:1180075560
@N: BN191 :"":0:0:0:-1|Writing property annotation file D:\ETRI_UWB\2007524\synplify1\rev_2_identify\FPGA1.tap.
@N: BN225 :"":0:0:0:-1|Writing default property annotation file D:\ETRI_UWB\2007524\synplify1\rev_2_identify\FPGA1.map.
@N: FX164 :"":0:0:0:-1|The option to pack flops in the IOB has not been specified 
@W: FX350 :"":0:0:0:-1|xc_props attribute is obsolete and will not be supported in a future release.  Please use the attributes inside the xc_props string directly or generics/parameters if they are available 
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF258 :"":0:0:0:-1|Gated clock conversion disabled 
@N: MT195 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT197 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@N: MT206 :"":0:0:0:-1|Autoconstrain Mode is ON
@N: CG364 :"c:\program files\synplicity\fpga_862\lib\xilinx\unisim.v":141:7:141:19|Synthesizing module BSCAN_VIRTEX4
@N: CG364 :"c:\program files\synplicity\fpga_862\lib\xilinx\unisim.v":166:7:166:10|Synthesizing module BUFG
@N: CG364 :"c:\program files\synplicity\fpga_862\lib\xilinx\unisim.v":434:7:434:13|Synthesizing module DCM_ADV
@N: CG364 :"c:\program files\synplicity\fpga_862\lib\xilinx\unisim.v":9761:7:9761:11|Synthesizing module IBUFG
@TM:1180078675
@N: CG364 :"c:\program files\synplicity\fpga_862\lib\xilinx\unisim.v":17289:7:17289:18|Synthesizing module RAMB16_S9_S9
@N: CG364 :"c:\program files\synplicity\fpga_862\lib\xilinx\unisim.v":19202:7:19202:13|Synthesizing module SRLC16E
@N:  :"d:\etri_uwb\2007524\synplify1\rev_2_identify\identify.log":0:0:0:0|M
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\model\xilinx\mypll2x.v":23:7:23:13|Synthesizing module mypll2x
@W: FX222 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\model\xilinx\mypll2x.v":60:11:60:22|M
@N: CG334 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\model\xilinx\mypll2x.v":99:15:99:27|M
@N: CG333 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\model\xilinx\mypll2x.v":116:15:116:26|M
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\ismc\ismc_ahb.v":25:13:25:20|Synthesizing module ismc_ahb
@W: BN116 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\ismc\ismc_ahb.v":103:3:103:8|M
@W: CL170 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\ismc\ismc_ahb.v":103:3:103:8|M
@N: CG347 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\ismc\ismc_ahb.v":111:35:111:47|M
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\ismc\ssram32bit.v":17:7:17:16|Synthesizing module SSRAM32bit
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\ismc\ssram8bit.v":17:7:17:15|Synthesizing module SSRAM8bit
@N: CL134 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\ismc\ssram8bit.v":44:0:44:5|M
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\top\uwb_pci\fpga1.v":15:7:15:11|Synthesizing module FPGA1
@W: CL159 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\top\uwb_pci\fpga1.v":110:13:110:21|M
@W: CL159 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\top\uwb_pci\fpga1.v":111:8:111:19|M
@W: CL159 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\top\uwb_pci\fpga1.v":112:13:112:20|M
@W: CL234 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\top\uwb_pci\fpga1.v":115:13:115:20|M
@W: CL234 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\top\uwb_pci\fpga1.v":129:15:129:22|M
@W: CG360 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\top\uwb_pci\fpga1.v":176:6:176:12|M
@N:  :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\top\uwb_pci\fpga1.v":239:0:239:5|M
@N:  :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\top\uwb_pci\fpga1.v":245:0:245:5|M
@N:  :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\top\uwb_pci\fpga1.v":251:0:251:5|M
@W: CS149 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\top\uwb_pci\fpga1.v":286:16:286:23|M
@W: CS149 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\top\uwb_pci\fpga1.v":295:16:295:20|M
@W: CS149 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\top\uwb_pci\fpga1.v":329:19:329:26|M
@W: CS149 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\rtl\top\uwb_pci\fpga1.v":338:19:338:23|M
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":1:7:1:18|Synthesizing module b9_ORbIwXaEF
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":31:7:31:20|Synthesizing module jtag_interface
@W: MT246 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":86:16:86:25|M
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":100:7:100:26|Synthesizing module b16_Rcmi_qlx9_yHpm7y
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":151:7:151:16|Synthesizing module comm_block
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":216:7:216:16|Synthesizing module b7_V71OJqz
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":263:7:263:20|Synthesizing module b10_nYWNT9NwbL
@N: MF179 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":297:22:297:46|M
@N:  :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":301:2:301:7|M
@W: CL171 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":307:2:307:7|M
@W: CL189 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":307:2:307:7|M
@N: CG347 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":381:33:381:45|M
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":393:7:393:18|Synthesizing module b9_O2yyf_fG2
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":400:7:400:26|Synthesizing module b16_CRGcTCua_eH4_uXf
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":547:7:547:21|Synthesizing module b11_PSyil9s1fkT
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":2603:7:2603:16|Synthesizing module b7_PfFzrNY
@W: CL209 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":2619:16:2619:27|M
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":2661:7:2661:16|Synthesizing module b7_OCByLXC
@N: CG334 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":2728:14:2728:26|M
@N: CG333 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":2731:14:2731:25|M
@W: MO129 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":2736:2:2736:7|M
@N:  :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":2745:2:2745:7|M
@N: FX271 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":2753:2:2753:7|M
@N: FX271 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":2769:4:2769:7|M
@N: CG347 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":2769:42:2769:54|M
@N: CG347 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":2786:39:2786:51|M
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":2860:7:2860:22|Synthesizing module b12_OFWNT9_wMeEd
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":2914:7:2914:25|Synthesizing module GenericRAMram_block
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":2950:7:2950:23|Synthesizing module ramSliceram_block
@N: CG347 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":3119:37:3119:49|M
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":3140:7:3140:15|Synthesizing module ram_block
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":3432:7:3432:16|Synthesizing module b7_OFWNT9s
@N: CG334 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":3469:14:3469:26|M
@N: CG333 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":3472:14:3472:25|M
@N:  :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":3509:2:3509:7|M
@N:  :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":3524:2:3524:7|M
@N: FX271 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":3524:2:3524:7|M
@N: FX271 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":3524:2:3524:7|M
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":3681:7:3681:22|Synthesizing module b12_nvmFL_la1xyH
@N: CG347 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":3732:44:3732:56|M
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":3746:7:3746:16|Synthesizing module b7_PLF_6lN
@N: CG347 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":3786:42:3786:54|M
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":3800:7:3800:12|Synthesizing module b3_uKr
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":3885:7:3885:17|Synthesizing module b8_nR_ymqrG
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":3981:7:3981:12|Synthesizing module b3_12m
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":4091:7:4091:13|Synthesizing module ldic1_0
@N: CG364 :"d:\etri_uwb\2007524\synplify1\rev_2_identify\instr_sources\syn_dics.v":4206:7:4206:12|Synthesizing module iice_0
