#-------------------------------------------------------------------------------
#-  This confidential and proprietary software may be used only as
#-  authorised by a licensing agreement from ARM Limited
#-    (C) COPYRIGHT 1998 ARM Limited
#-        ALL RIGHTS RESERVED
#-  The entire notice above must be reproduced on all authorised
#-  copies and copies may only be made to the extent permitted
#-  by a licensing agreement from ARM Limited.
#-------------------------------------------------------------------------------
#-  
#-  Version and Release Control Information:
#-  
#-  File Name              : makefile,v
#-  File Revision          : 1.3
#-  
#-  Release Information    : PL050-REL1v1
#-  
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#- Purpose  : Standard VHDL Library Makefile  
#-------------------------------------------------------------------------------


MODULES = buscyc_drivers.vhd addrctl_driver.vhd penable_driver.vhd data_driver.vhd busline_drivers.vhd reset_driver.vhd

include ../modeltech/StdMakefile.mk

############################## End of file #####################################
