library verilog;
use verilog.vl_types.all;
entity APB0_RS_ReadChannelmi is
    generic(
        BUS_WID         : integer := 32;
        ADDR_WID        : integer := 32;
        MASTERID_WID    : integer := 1;
        SLAVEID_WID     : integer := 2;
        AWLEN_WID       : integer := 4;
        AWSIZE_WID      : integer := 3;
        AWBURST_WID     : integer := 2;
        AWLOCK_WID      : integer := 2;
        AWCACHE_WID     : integer := 4;
        AWPROT_WID      : integer := 3;
        WSTRB_WID       : integer := 4;
        BRESP_WID       : integer := 2;
        RRESP_WID       : integer := 2;
        ARLEN_WID       : integer := 4;
        ARBURST_WID     : integer := 2;
        ARLOCK_WID      : integer := 2;
        ARCACHE_WID     : integer := 4;
        ARPROT_WID      : integer := 3;
        MASTER_WID      : integer := 3;
        SLAVE_WID       : integer := 4;
        SLAVE_NUM       : integer := 8;
        MASTER_NUM      : integer := 5;
        SELMASTER_WID   : integer := 1;
        Wr_REQDEPTH_WID : integer := 1;
        Rd_REQDEPTH_WID : integer := 1;
        WrPermit_SLAVECNTWID: integer := 1;
        RdPermit_SLAVECNTWID: integer := 1;
        ARSIZE_WID      : integer := 3
    );
    port(
        ACLK            : in     vl_logic;
        ARESETn         : in     vl_logic;
        ARIDmi2s        : out    vl_logic_vector;
        ARADDRmi2s      : out    vl_logic_vector;
        ARLENmi2s       : out    vl_logic_vector;
        ARSIZEmi2s      : out    vl_logic_vector;
        ARBURSTmi2s     : out    vl_logic_vector;
        ARVALIDmi2s     : out    vl_logic;
        ARREADYs2mi     : in     vl_logic;
        RIDs2mi         : in     vl_logic_vector;
        RRESPs2mi       : in     vl_logic_vector;
        RDATAs2mi       : in     vl_logic_vector;
        RVALIDs2mi      : in     vl_logic;
        RLASTs2mi       : in     vl_logic;
        RREADYmi2s      : out    vl_logic;
        ARIDsi02mi      : in     vl_logic_vector;
        ARADDRsi02mi    : in     vl_logic_vector;
        ARLENsi02mi     : in     vl_logic_vector;
        ARSIZEsi02mi    : in     vl_logic_vector;
        ARBURSTsi02mi   : in     vl_logic_vector;
        ARLOCKsi02mi    : in     vl_logic_vector;
        ARCACHEsi02mi   : in     vl_logic_vector;
        ARPROTsi02mi    : in     vl_logic_vector;
        ARIDsi12mi      : in     vl_logic_vector;
        ARADDRsi12mi    : in     vl_logic_vector;
        ARLENsi12mi     : in     vl_logic_vector;
        ARSIZEsi12mi    : in     vl_logic_vector;
        ARBURSTsi12mi   : in     vl_logic_vector;
        ARLOCKsi12mi    : in     vl_logic_vector;
        ARCACHEsi12mi   : in     vl_logic_vector;
        ARPROTsi12mi    : in     vl_logic_vector;
        ARVALIDsi2mi    : in     vl_logic_vector;
        ARREADYmi2si    : out    vl_logic_vector;
        RIDmi2si0       : out    vl_logic_vector;
        RRESPmi2si0     : out    vl_logic_vector;
        RDATAmi2si0     : out    vl_logic_vector;
        RIDmi2si1       : out    vl_logic_vector;
        RRESPmi2si1     : out    vl_logic_vector;
        RDATAmi2si1     : out    vl_logic_vector;
        RVALIDmi2si     : out    vl_logic_vector;
        RLASTmi2si      : out    vl_logic_vector;
        RREADYsi2mi     : in     vl_logic_vector;
        Lock2Rdmi       : in     vl_logic;
        UnLock2Rdmi     : in     vl_logic;
        Lock2Wrmi       : out    vl_logic;
        UnLock2Wrmi     : out    vl_logic;
        AWVALID         : in     vl_logic;
        LockPort        : in     vl_logic_vector;
        ReadIntEmptyWrmi2Rdmi: in     vl_logic;
        DataCntEmptyRdmi2Wrmi: out    vl_logic;
        CtlDataRead2Lock: out    vl_logic_vector
    );
end APB0_RS_ReadChannelmi;
