library verilog;
use verilog.vl_types.all;
entity AxiPC is
    generic(
        DATA_WIDTH      : integer := 64;
        ID_WIDTH        : integer := 4;
        RID_WIDTH       : integer := 4;
        AWUSER_WIDTH    : integer := 32;
        WUSER_WIDTH     : integer := 32;
        BUSER_WIDTH     : integer := 32;
        ARUSER_WIDTH    : integer := 32;
        RUSER_WIDTH     : integer := 32;
        WDEPTH          : integer := 1;
        MAXRBURSTS      : integer := 64;
        MAXWBURSTS      : integer := 64;
        MAXWAITS        : integer := 3000;
        AXI_ERRM_ProofOptions: integer := 0;
        AXI_RECM_ProofOptions: integer := 0;
        AXI_AUXM_ProofOptions: integer := 0;
        AXI_ERRS_ProofOptions: integer := 0;
        AXI_RECS_ProofOptions: integer := 0;
        AXI_AUXS_ProofOptions: integer := 0;
        AXI_ERRL_ProofOptions: integer := 0;
        RecommendOn     : integer := 1;
        ADDRLO          : integer := 0;
        ADDRHI          : integer := 6
    );
    port(
        ACLK            : in     vl_logic;
        ARESETn         : in     vl_logic;
        AWID            : in     vl_logic_vector;
        AWADDR          : in     vl_logic_vector(31 downto 0);
        AWLEN           : in     vl_logic_vector(3 downto 0);
        AWSIZE          : in     vl_logic_vector(2 downto 0);
        AWBURST         : in     vl_logic_vector(1 downto 0);
        AWLOCK          : in     vl_logic_vector(1 downto 0);
        AWCACHE         : in     vl_logic_vector(3 downto 0);
        AWPROT          : in     vl_logic_vector(2 downto 0);
        AWUSER          : in     vl_logic_vector;
        AWVALID         : in     vl_logic;
        AWREADY         : in     vl_logic;
        WID             : in     vl_logic_vector;
        WLAST           : in     vl_logic;
        WDATA           : in     vl_logic_vector;
        WSTRB           : in     vl_logic_vector;
        WUSER           : in     vl_logic_vector;
        WVALID          : in     vl_logic;
        WREADY          : in     vl_logic;
        BID             : in     vl_logic_vector;
        BRESP           : in     vl_logic_vector(1 downto 0);
        BUSER           : in     vl_logic_vector;
        BVALID          : in     vl_logic;
        BREADY          : in     vl_logic;
        ARID            : in     vl_logic_vector;
        ARADDR          : in     vl_logic_vector(31 downto 0);
        ARLEN           : in     vl_logic_vector(3 downto 0);
        ARSIZE          : in     vl_logic_vector(2 downto 0);
        ARBURST         : in     vl_logic_vector(1 downto 0);
        ARLOCK          : in     vl_logic_vector(1 downto 0);
        ARCACHE         : in     vl_logic_vector(3 downto 0);
        ARPROT          : in     vl_logic_vector(2 downto 0);
        ARUSER          : in     vl_logic_vector;
        ARVALID         : in     vl_logic;
        ARREADY         : in     vl_logic;
        RID             : in     vl_logic_vector;
        RLAST           : in     vl_logic;
        RDATA           : in     vl_logic_vector;
        RRESP           : in     vl_logic_vector(1 downto 0);
        RUSER           : in     vl_logic_vector;
        RVALID          : in     vl_logic;
        RREADY          : in     vl_logic;
        CACTIVE         : in     vl_logic;
        CSYSREQ         : in     vl_logic;
        CSYSACK         : in     vl_logic
    );
end AxiPC;
