library verilog;
use verilog.vl_types.all;
entity dmacchsrcxfer is
    port(
        hclk            : in     vl_logic;
        hresetn         : in     vl_logic;
        dmacen          : in     vl_logic;
        busavlblm1      : in     vl_logic;
        busavlblm2      : in     vl_logic;
        dataerrorm1     : in     vl_logic;
        dataerrorm2     : in     vl_logic;
        xferabortedm1   : in     vl_logic;
        xferabortedm2   : in     vl_logic;
        srcstart        : in     vl_logic;
        flowcntl        : in     vl_logic_vector(2 downto 0);
        trfsizesrc      : in     vl_logic_vector(11 downto 0);
        sbsize          : in     vl_logic_vector(2 downto 0);
        swidth          : in     vl_logic_vector(2 downto 0);
        dwidth          : in     vl_logic_vector(2 downto 0);
        srcselect       : in     vl_logic;
        dstselect       : in     vl_logic;
        sourceen        : in     vl_logic;
        lliaddressub    : in     vl_logic_vector(31 downto 2);
        channelen       : in     vl_logic;
        dsterred        : in     vl_logic;
        chsrcbreq       : in     vl_logic;
        chsrcsreq       : in     vl_logic;
        chsrclbreq      : in     vl_logic;
        chsrclsreq      : in     vl_logic;
        chdstlbreq      : in     vl_logic;
        chdstlsreq      : in     vl_logic;
        fifoemptylevel  : in     vl_logic_vector(4 downto 0);
        setsrcaxsonmsk  : out    vl_logic;
        unsetsrcaxsonmsk: out    vl_logic;
        setsrce2lmsk    : out    vl_logic;
        seterrmsksrc    : out    vl_logic;
        errcycmasksrc   : out    vl_logic;
        abortreqsrcm1   : out    vl_logic;
        abortreqsrcm2   : out    vl_logic;
        dmactcsrc       : out    vl_logic;
        dmacclrsrc      : out    vl_logic;
        srcnumofxfers   : out    vl_logic_vector(4 downto 0);
        dectrfsizesrc   : out    vl_logic;
        srcaddrupdate   : out    vl_logic;
        srcdisable      : out    vl_logic;
        srcerr          : out    vl_logic;
        srcdmacstate    : out    vl_logic_vector(4 downto 0);
        setsrctcdone    : out    vl_logic;
        srcfactor       : out    vl_logic_vector(3 downto 0);
        fifowren        : out    vl_logic
    );
end dmacchsrcxfer;
