library verilog;
use verilog.vl_types.all;
entity SMI is
    port(
        nHCLK           : in     vl_logic;
        HCLK            : in     vl_logic;
        HRESETn         : in     vl_logic;
        HREADYIN        : in     vl_logic;
        HREADYINTIC     : in     vl_logic;
        HADDR           : in     vl_logic_vector(28 downto 0);
        HBURST          : in     vl_logic_vector(2 downto 0);
        HTRANS          : in     vl_logic_vector(1 downto 0);
        HWRITE          : in     vl_logic;
        HSIZE           : in     vl_logic_vector(2 downto 0);
        HWDATA          : in     vl_logic_vector(31 downto 0);
        HSELSMC         : in     vl_logic;
        HSELREG         : in     vl_logic;
        HRESPTIC        : in     vl_logic_vector(1 downto 0);
        HRDATATIC       : in     vl_logic_vector(31 downto 0);
        HGRANTTIC       : in     vl_logic;
        BIGENDIAN       : in     vl_logic;
        REMAP           : in     vl_logic;
        TICBUSGNTEBI    : in     vl_logic;
        SMBUSGNTEBI     : in     vl_logic;
        SCANENABLE      : in     vl_logic;
        SCANINHCLK      : in     vl_logic;
        SCANINnHCLK     : in     vl_logic;
        SMWAIT          : in     vl_logic;
        CANCELSMWAIT    : in     vl_logic;
        SMMWCS7         : in     vl_logic_vector(1 downto 0);
        SMDATAIN        : in     vl_logic_vector(31 downto 0);
        TESTREQA        : in     vl_logic;
        TESTREQB        : in     vl_logic;
        MCBUSREQ        : in     vl_logic;
        MCADDR          : in     vl_logic_vector(25 downto 0);
        MCDATAOUT       : in     vl_logic_vector(31 downto 0);
        MCDATAEN        : in     vl_logic_vector(3 downto 0);
        EXTBUSMUX       : in     vl_logic;
        HRDATA          : out    vl_logic_vector(31 downto 0);
        HREADYOUT       : out    vl_logic;
        HRESP           : out    vl_logic_vector(1 downto 0);
        HADDRTIC        : out    vl_logic_vector(31 downto 0);
        HTRANSTIC       : out    vl_logic_vector(1 downto 0);
        HWRITETIC       : out    vl_logic;
        HSIZETIC        : out    vl_logic_vector(2 downto 0);
        HBURSTTIC       : out    vl_logic_vector(2 downto 0);
        HPROTTIC        : out    vl_logic_vector(3 downto 0);
        HWDATATIC       : out    vl_logic_vector(31 downto 0);
        HBUSREQTIC      : out    vl_logic;
        HLOCKTIC        : out    vl_logic;
        TICBUSREQEBI    : out    vl_logic;
        SMBUSREQEBI     : out    vl_logic;
        SCANOUTnHCLK    : out    vl_logic;
        SCANOUTHCLK     : out    vl_logic;
        SMDATAOUT       : out    vl_logic_vector(31 downto 0);
        nSMDATAEN       : out    vl_logic_vector(3 downto 0);
        SMADDR          : out    vl_logic_vector(25 downto 0);
        SMCS            : out    vl_logic_vector(7 downto 0);
        nSMBLS          : out    vl_logic_vector(3 downto 0);
        nSMWEN          : out    vl_logic;
        nSMOEN          : out    vl_logic;
        TICREADEBI      : out    vl_logic;
        TBUSOUTEBI      : out    vl_logic_vector(31 downto 0);
        TESTACK         : out    vl_logic;
        MCBUSGNT        : out    vl_logic
    );
end SMI;
