#- --=========================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2001-2002 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- -----------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.2
#-
#- Release Information    : PrimeCell(TM)-PL220-r0p0-00ltd0
#-
#- -----------------------------------------------------------------------------
#- Purpose  :
#-            makefile for VHDL Trickbox files
#-
#- --=========================================================================--

MODULES =  EbiTrPackage.vhd \
           EbiTrRegBlk.vhd \
           EbiTrAhbif.vhd \
           EbiTrClkResGen.vhd \
           EbiTrArbtCtl.vhd \
           EbiTrMultBlk.vhd \
           EbiTrMirEbi.vhd \
           EbiTrReqIndctr.vhd \
           EbiTrComparator.vhd \
           EbiTrProChkr.vhd \
           EbiTrick.vhd

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk 

##################################### End ######################################
