/* Generated automatically by the program `gencodes'
   from the machine description file `md'.  */

#ifndef GCC_INSN_CODES_H
#define GCC_INSN_CODES_H

enum insn_code {
  CODE_FOR_return_internal = 0,
  CODE_FOR_sibcall_internal = 1,
  CODE_FOR_movsi_insn_big = 7,
  CODE_FOR_cmov = 8,
  CODE_FOR_movdi = 20,
  CODE_FOR_movdf = 21,
  CODE_FOR_movsf = 22,
  CODE_FOR_extendqisi2_sext = 23,
  CODE_FOR_extendqisi2_no_sext_mem = 24,
  CODE_FOR_extendhisi2_sext = 25,
  CODE_FOR_extendhisi2_no_sext_mem = 26,
  CODE_FOR_zero_extendqisi2 = 27,
  CODE_FOR_zero_extendhisi2 = 28,
  CODE_FOR_ashlsi3 = 29,
  CODE_FOR_ashrsi3 = 30,
  CODE_FOR_lshrsi3 = 31,
  CODE_FOR_rotrsi3 = 32,
  CODE_FOR_andsi3 = 33,
  CODE_FOR_iorsi3 = 34,
  CODE_FOR_xorsi3 = 35,
  CODE_FOR_one_cmplqi2 = 36,
  CODE_FOR_one_cmplsi2 = 37,
  CODE_FOR_negsi2 = 38,
  CODE_FOR_addsi3 = 39,
  CODE_FOR_subsi3 = 40,
  CODE_FOR_mulsi3 = 41,
  CODE_FOR_divsi3 = 42,
  CODE_FOR_udivsi3 = 43,
  CODE_FOR_jump_internal = 44,
  CODE_FOR_jump_aligned = 45,
  CODE_FOR_indirect_jump_internal = 46,
  CODE_FOR_indirect_jump_aligned = 47,
  CODE_FOR_call_internal = 48,
  CODE_FOR_call_aligned = 49,
  CODE_FOR_call_value_internal = 50,
  CODE_FOR_call_value_aligned = 51,
  CODE_FOR_call_value_indirect_internal = 52,
  CODE_FOR_call_value_indirect_aligned = 53,
  CODE_FOR_call_indirect_internal = 54,
  CODE_FOR_call_indirect_aligned = 55,
  CODE_FOR_tablejump_internal = 56,
  CODE_FOR_tablejump_aligned = 57,
  CODE_FOR_nop = 58,
  CODE_FOR_addsf3 = 59,
  CODE_FOR_adddf3 = 60,
  CODE_FOR_subsf3 = 61,
  CODE_FOR_subdf3 = 62,
  CODE_FOR_mulsf3 = 63,
  CODE_FOR_muldf3 = 64,
  CODE_FOR_divsf3 = 65,
  CODE_FOR_divdf3 = 66,
  CODE_FOR_prologue = 67,
  CODE_FOR_epilogue = 68,
  CODE_FOR_sibcall_epilogue = 69,
  CODE_FOR_sibcall = 70,
  CODE_FOR_sibcall_value = 71,
  CODE_FOR_movqi = 72,
  CODE_FOR_movhi = 73,
  CODE_FOR_movsi = 74,
  CODE_FOR_addsicc = 75,
  CODE_FOR_addhicc = 76,
  CODE_FOR_addqicc = 77,
  CODE_FOR_movsicc = 78,
  CODE_FOR_movhicc = 79,
  CODE_FOR_movqicc = 80,
  CODE_FOR_cmpsi = 81,
  CODE_FOR_beq = 82,
  CODE_FOR_bne = 83,
  CODE_FOR_bgt = 84,
  CODE_FOR_bgtu = 85,
  CODE_FOR_blt = 86,
  CODE_FOR_bltu = 87,
  CODE_FOR_bge = 88,
  CODE_FOR_bgeu = 89,
  CODE_FOR_ble = 90,
  CODE_FOR_bleu = 91,
  CODE_FOR_extendqisi2 = 92,
  CODE_FOR_extendqisi2_no_sext_reg = 93,
  CODE_FOR_extendhisi2 = 94,
  CODE_FOR_extendhisi2_no_sext_reg = 95,
  CODE_FOR_jump = 96,
  CODE_FOR_indirect_jump = 97,
  CODE_FOR_call = 98,
  CODE_FOR_call_value = 99,
  CODE_FOR_call_value_indirect = 100,
  CODE_FOR_call_indirect = 101,
  CODE_FOR_tablejump = 102,
  CODE_FOR_nothing
};

#endif /* GCC_INSN_CODES_H */
