library verilog;
use verilog.vl_types.all;
entity DmacEngine is
    port(
        ACLK            : in     vl_logic;
        ARESETn         : in     vl_logic;
        Start           : in     vl_logic;
        Ready           : out    vl_logic;
        ChControl       : in     vl_logic_vector(31 downto 0);
        ChSrcAddr       : in     vl_logic_vector(31 downto 0);
        ChDestAddr      : in     vl_logic_vector(31 downto 0);
        ChDescriptor    : in     vl_logic_vector(31 downto 0);
        ChControlWE     : out    vl_logic;
        ChSrcAddrWE     : out    vl_logic;
        ChDestAddrWE    : out    vl_logic;
        ChDescriptorWE  : out    vl_logic;
        ChControlWData  : out    vl_logic_vector(31 downto 0);
        ChSrcAddrWData  : out    vl_logic_vector(31 downto 0);
        ChDestAddrWData : out    vl_logic_vector(31 downto 0);
        ChDescriptorWData: out    vl_logic_vector(31 downto 0);
        ARVALID         : out    vl_logic;
        ARREADY         : in     vl_logic;
        ARADDR          : out    vl_logic_vector(31 downto 0);
        ARLEN           : out    vl_logic_vector(3 downto 0);
        ARSIZE          : out    vl_logic_vector(2 downto 0);
        ARBURST         : out    vl_logic_vector(1 downto 0);
        RDATA           : in     vl_logic_vector(31 downto 0);
        RRESP           : in     vl_logic_vector(1 downto 0);
        RLAST           : in     vl_logic;
        RVALID          : in     vl_logic;
        RREADY          : out    vl_logic;
        AWVALID         : out    vl_logic;
        AWREADY         : in     vl_logic;
        AWADDR          : out    vl_logic_vector(31 downto 0);
        AWLEN           : out    vl_logic_vector(3 downto 0);
        AWSIZE          : out    vl_logic_vector(2 downto 0);
        AWBURST         : out    vl_logic_vector(1 downto 0);
        WDATA           : out    vl_logic_vector(31 downto 0);
        WSTRB           : out    vl_logic_vector(3 downto 0);
        WLAST           : out    vl_logic;
        WVALID          : out    vl_logic;
        WREADY          : in     vl_logic;
        BRESP           : in     vl_logic_vector(1 downto 0);
        BVALID          : in     vl_logic;
        BREADY          : out    vl_logic;
        StartInterrupt  : out    vl_logic;
        EndInterrupt    : out    vl_logic;
        ErrorInterrupt  : out    vl_logic;
        StopInterrupt   : out    vl_logic
    );
end DmacEngine;
