#! /bin/sh
#- --=================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- ---------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : tif2bif.rca
#- File Revision          : 1.1
#-
#- Release Information    : PrimeCell(TM)-GLOBAL-REL1v7
#-
#- ---------------------------------------------------------------------
#- Purpose : 
#-           Script to generate .bif or .tif file
#-
#- --=================================================================--

sed 's/$RCSfile/RCSfile/g' $1.tif > $1.tmp1
sed 's/$Revision/Revision/g' $1.tmp1 > $1.tmp
sed 's/$State/State/g' $1.tmp > $1.bif
rm -f  $1.tmp1 $1.tmp

#- --=============================== End =============================--
