#-------------------------------------------------------------------------------
#-  This confidential and proprietary software may be used only as
#-  authorised by a licensing agreement from ARM Limited
#-    (C) COPYRIGHT 1998 ARM Limited
#-        ALL RIGHTS RESERVED
#-  The entire notice above must be reproduced on all authorised
#-  copies and copies may only be made to the extent permitted
#-  by a licensing agreement from ARM Limited.
#-------------------------------------------------------------------------------
#-  
#-  Version and Release Control Information:
#-  
#-  File Name              : makefile.rca
#-  File Revision          : 1.4
#-  
#-  Release Information    : PrimeCell(TM)-PL011-REL1v3
#-  
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#-  Purpose  : Standard VHDL Library Makefile
#-
#-------------------------------------------------------------------------------

MODULES = ../ticbox/Ticbox.vhd tbench.vhd

TEST_ENV = TICTALK

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

############################## End of file #####################################
