library verilog;
use verilog.vl_types.all;
entity SDRAi is
    generic(
        AW              : integer := 25;
        DW              : integer := 31;
        BW              : integer := 3;
        BL              : integer := 3;
        ID              : integer := 3;
        WQCD            : integer := 5;
        WQD             : integer := 63;
        RQCD            : integer := 5;
        RQD             : integer := 63;
        WBLQCD          : integer := 1;
        WBLQD           : integer := 3;
        RBLQCD          : integer := 1;
        RBLQD           : integer := 3;
        MDW             : integer := 31;
        DMW             : integer := 3;
        BAW             : integer := 1;
        RAW             : integer := 12;
        CAW             : integer := 10;
        TL              : integer := 4;
        RWW             : integer := 1;
        CD              : integer := 3;
        erc_powerup     : integer := 1;
        erc_epc         : integer := 2;
        erc_ar          : integer := 4;
        erc_mrs         : integer := 8;
        erc_idle        : integer := 16;
        erc_normal      : integer := 32;
        bc_null         : integer := 0;
        bc_mcas         : integer := 1;
        bc_mras         : integer := 2;
        bc_pc           : integer := 4;
        bc_sras         : integer := 8;
        bc_scas         : integer := 16;
        bc_epc          : integer := 32;
        ebc_null        : integer := 0;
        ebc_mcas        : integer := 1;
        ebc_mras        : integer := 2;
        ebc_pc          : integer := 4;
        ebc_sras        : integer := 8;
        ebc_scas        : integer := 16;
        ebc_epc         : integer := 32;
        ebc_bstop       : integer := 64;
        W_IDLE          : integer := 1;
        W_WDAT          : integer := 2;
        W_WACK          : integer := 4;
        W_WREQ          : integer := 8;
        W_WSPI          : integer := 16;
        R_IDLE          : integer := 1;
        R_RREQ          : integer := 2;
        R_RSPI          : integer := 4;
        R_DIDLE         : integer := 1;
        R_DREQ          : integer := 2
    );
    port(
        ARESETB         : in     vl_logic;
        PORESETB        : in     vl_logic;
        ACLK            : in     vl_logic;
        nACLK           : in     vl_logic;
        FCLK            : in     vl_logic;
        AWAddr          : in     vl_logic_vector;
        AWId            : in     vl_logic_vector;
        AWLen           : in     vl_logic_vector;
        AWValid         : in     vl_logic;
        AWReady         : out    vl_logic;
        AWBurst         : in     vl_logic_vector(1 downto 0);
        WLast           : in     vl_logic;
        WStrb           : in     vl_logic_vector;
        WData           : in     vl_logic_vector;
        WValid          : in     vl_logic;
        WReady          : out    vl_logic;
        WId             : in     vl_logic_vector;
        BResp           : out    vl_logic_vector(1 downto 0);
        BValid          : out    vl_logic;
        BReady          : in     vl_logic;
        BId             : out    vl_logic_vector;
        ARAddr          : in     vl_logic_vector;
        ARId            : in     vl_logic_vector;
        ARLen           : in     vl_logic_vector;
        ARValid         : in     vl_logic;
        ARReady         : out    vl_logic;
        ARBurst         : in     vl_logic_vector(1 downto 0);
        RData           : out    vl_logic_vector;
        RValid          : out    vl_logic;
        RReady          : in     vl_logic;
        RLast           : out    vl_logic;
        RId             : out    vl_logic_vector;
        RResp           : out    vl_logic_vector(1 downto 0);
        RQFull          : out    vl_logic;
        WQFull          : out    vl_logic;
        BA_STS          : in     vl_logic_vector(16 downto 0);
        BA_AA           : out    vl_logic_vector;
        BA_REQ          : out    vl_logic;
        BA_TT           : out    vl_logic_vector;
        BA_RW           : out    vl_logic;
        BA_ID           : out    vl_logic_vector;
        BA_PM           : out    vl_logic;
        SD_DQE          : out    vl_logic;
        SD_DQI          : in     vl_logic_vector;
        SD_DQO          : out    vl_logic_vector;
        SD_DQM          : out    vl_logic_vector
    );
end SDRAi;
