// ARM7TDMI.v shipped with DSM AT010-MS-26307-3A-00
//
// Verilog implementation of ARM7TDMI, generated by simwrap

// Elements of the code in this file are
// Copyright 1993-99, 2000-02 ARM Ltd,
// All rights reserved.

`timescale 1 ps / 1 ps

// Non blocking assign shell

module ARM7TDMI_nba (A_xmgxext,
  ABE,
  ABORT,
  ALE,
  APE,
  BIGEND,
  BL,
  BREAKPT,
  BUSDIS_xmgxext,
  BUSEN,
  COMMRX_xmgxext,
  COMMTX_xmgxext,
  CPA,
  CPB,
  D_xmgxread,
  D_xmgxext,
  DBE,
  DBGACK_xmgxext,
  DBGEN,
  DBGRQ,
  DBGRQI_xmgxext,
  DIN,
  DOUT_xmgxext,
  DRIVEBS_xmgxext,
  ECAPCLK_xmgxext,
  ECAPCLKBS_xmgxext,
  ECLK_xmgxext,
  EXTERN0,
  EXTERN1,
  HIGHZ_xmgxext,
  ICAPCLKBS_xmgxext,
  IR_xmgxext,
  ISYNC,
  LOCK_xmgxext,
  MAS_xmgxext,
  MCLK,
  nCPI_xmgxext,
  nENIN,
  nENOUT_xmgxext,
  nENOUTI_xmgxext,
  nEXEC_xmgxext,
  nFIQ,
  nHIGHZ_xmgxext,
  nIRQ,
  nM_xmgxext,
  nMREQ_xmgxext,
  nOPC_xmgxext,
  nRESET,
  nRW_xmgxext,
  nTDOEN_xmgxext,
  nTRANS_xmgxext,
  nTRST,
  nWAIT,
  PCLKBS_xmgxext,
  RANGEOUT0_xmgxext,
  RANGEOUT1_xmgxext,
  RSTCLKBS_xmgxext,
  SCREG_xmgxext,
  SDINBS_xmgxext,
  SDOUTBS,
  SEQ_xmgxext,
  SHCLK2BS_xmgxext,
  SHCLKBS_xmgxext,
  TAPSM_xmgxext,
  TBE,
  TBIT_xmgxext,
  TCK,
  TCK1_xmgxext,
  TCK2_xmgxext,
  TDI,
  TDO_xmgxext,
  TMS,
  r0,
  r1,
  r2,
  r3,
  r4,
  r5,
  r6,
  r7,
  r8,
  r9,
  r10,
  r11,
  r12,
  r13,
  r14,
  r15,
  r8fiq,
  r9fiq,
  r10fiq,
  r11fiq,
  r12fiq,
  r13fiq,
  r14fiq,
  r13irq,
  r14irq,
  r13svc,
  r14svc,
  r13abt,
  r14abt,
  r13und,
  r14und,
  cpsr,
  spsrfiq,
  spsrirq,
  spsrsvc,
  spsrabt,
  spsrund,
  icewp0addr,
  icewp0amask,
  icewp0data,
  icewp0dmask,
  icewp0ctl,
  icewp0cmask,
  icewp1addr,
  icewp1amask,
  icewp1data,
  icewp1dmask,
  icewp1ctl,
  icewp1cmask,
  icedbgctl,
  icedbgstatus,
  normal,
  scan,
  dclk,
  dbg,
  hghz,
  testBus,
  testDBus,
  enterDbg,
  leavingscan,
  leavingdclk,
  scan1Dbg,
  scan0Dbg,
  sc2updatedr,
  reads,
  mem,
  busen1,
  isync1,
  bl3,
  bl2,
  bl1,
  bl0,
  capture048,
  capture0148);

output [31:0] A_xmgxext;
input ABE;
input ABORT;
input ALE;
input APE;
input BIGEND;
input [3:0] BL;
input BREAKPT;
output BUSDIS_xmgxext;
input BUSEN;
output COMMRX_xmgxext;
output COMMTX_xmgxext;
input CPA;
input CPB;
input [31:0] D_xmgxread;
output [31:0] D_xmgxext;
input DBE;
output DBGACK_xmgxext;
input DBGEN;
input DBGRQ;
output DBGRQI_xmgxext;
input [31:0] DIN;
output [31:0] DOUT_xmgxext;
output DRIVEBS_xmgxext;
output ECAPCLK_xmgxext;
output ECAPCLKBS_xmgxext;
output ECLK_xmgxext;
input EXTERN0;
input EXTERN1;
output HIGHZ_xmgxext;
output ICAPCLKBS_xmgxext;
output [3:0] IR_xmgxext;
input ISYNC;
output LOCK_xmgxext;
output [1:0] MAS_xmgxext;
input MCLK;
output nCPI_xmgxext;
input nENIN;
output nENOUT_xmgxext;
output nENOUTI_xmgxext;
output nEXEC_xmgxext;
input nFIQ;
output nHIGHZ_xmgxext;
input nIRQ;
output [4:0] nM_xmgxext;
output nMREQ_xmgxext;
output nOPC_xmgxext;
input nRESET;
output nRW_xmgxext;
output nTDOEN_xmgxext;
output nTRANS_xmgxext;
input nTRST;
input nWAIT;
output PCLKBS_xmgxext;
output RANGEOUT0_xmgxext;
output RANGEOUT1_xmgxext;
output RSTCLKBS_xmgxext;
output [3:0] SCREG_xmgxext;
output SDINBS_xmgxext;
input SDOUTBS;
output SEQ_xmgxext;
output SHCLK2BS_xmgxext;
output SHCLKBS_xmgxext;
output [3:0] TAPSM_xmgxext;
input TBE;
output TBIT_xmgxext;
input TCK;
output TCK1_xmgxext;
output TCK2_xmgxext;
input TDI;
output TDO_xmgxext;
input TMS;
output [31:0] r0;
output [31:0] r1;
output [31:0] r2;
output [31:0] r3;
output [31:0] r4;
output [31:0] r5;
output [31:0] r6;
output [31:0] r7;
output [31:0] r8;
output [31:0] r9;
output [31:0] r10;
output [31:0] r11;
output [31:0] r12;
output [31:0] r13;
output [31:0] r14;
output [31:0] r15;
output [31:0] r8fiq;
output [31:0] r9fiq;
output [31:0] r10fiq;
output [31:0] r11fiq;
output [31:0] r12fiq;
output [31:0] r13fiq;
output [31:0] r14fiq;
output [31:0] r13irq;
output [31:0] r14irq;
output [31:0] r13svc;
output [31:0] r14svc;
output [31:0] r13abt;
output [31:0] r14abt;
output [31:0] r13und;
output [31:0] r14und;
output [31:0] cpsr;
output [31:0] spsrfiq;
output [31:0] spsrirq;
output [31:0] spsrsvc;
output [31:0] spsrabt;
output [31:0] spsrund;
output [31:0] icewp0addr;
output [31:0] icewp0amask;
output [31:0] icewp0data;
output [31:0] icewp0dmask;
output [8:0] icewp0ctl;
output [7:0] icewp0cmask;
output [31:0] icewp1addr;
output [31:0] icewp1amask;
output [31:0] icewp1data;
output [31:0] icewp1dmask;
output [8:0] icewp1ctl;
output [7:0] icewp1cmask;
output [2:0] icedbgctl;
output [4:0] icedbgstatus;
output normal;
output scan;
output dclk;
output dbg;
output hghz;
output testBus;
output testDBus;
output enterDbg;
output leavingscan;
output leavingdclk;
output scan1Dbg;
output scan0Dbg;
output sc2updatedr;
output reads;
output mem;
output busen1;
output isync1;
output bl3;
output bl2;
output bl1;
output bl0;
output capture048;
output capture0148;

reg [31:0] A_xmgxext;
reg [31:0] A;
reg BUSDIS_xmgxext;
reg BUSDIS;
reg COMMRX_xmgxext;
reg COMMRX;
reg COMMTX_xmgxext;
reg COMMTX;
reg [31:0] D_xmgxext;
reg [31:0] D;
reg DBGACK_xmgxext;
reg DBGACK;
reg DBGRQI_xmgxext;
reg DBGRQI;
reg [31:0] DOUT_xmgxext;
reg [31:0] DOUT;
reg DRIVEBS_xmgxext;
reg DRIVEBS;
reg ECAPCLK_xmgxext;
reg ECAPCLK;
reg ECAPCLKBS_xmgxext;
reg ECAPCLKBS;
reg ECLK_xmgxext;
reg ECLK;
reg HIGHZ_xmgxext;
reg HIGHZ;
reg ICAPCLKBS_xmgxext;
reg ICAPCLKBS;
reg [3:0] IR_xmgxext;
reg [3:0] IR;
reg LOCK_xmgxext;
reg LOCK;
reg [1:0] MAS_xmgxext;
reg [1:0] MAS;
reg nCPI_xmgxext;
reg nCPI;
reg nENOUT_xmgxext;
reg nENOUT;
reg nENOUTI_xmgxext;
reg nENOUTI;
reg nEXEC_xmgxext;
reg nEXEC;
reg nHIGHZ_xmgxext;
reg nHIGHZ;
reg [4:0] nM_xmgxext;
reg [4:0] nM;
reg nMREQ_xmgxext;
reg nMREQ;
reg nOPC_xmgxext;
reg nOPC;
reg nRW_xmgxext;
reg nRW;
reg nTDOEN_xmgxext;
reg nTDOEN;
reg nTRANS_xmgxext;
reg nTRANS;
reg PCLKBS_xmgxext;
reg PCLKBS;
reg RANGEOUT0_xmgxext;
reg RANGEOUT0;
reg RANGEOUT1_xmgxext;
reg RANGEOUT1;
reg RSTCLKBS_xmgxext;
reg RSTCLKBS;
reg [3:0] SCREG_xmgxext;
reg [3:0] SCREG;
reg SDINBS_xmgxext;
reg SDINBS;
reg SEQ_xmgxext;
reg SEQ;
reg SHCLK2BS_xmgxext;
reg SHCLK2BS;
reg SHCLKBS_xmgxext;
reg SHCLKBS;
reg [3:0] TAPSM_xmgxext;
reg [3:0] TAPSM;
reg TBIT_xmgxext;
reg TBIT;
reg TCK1_xmgxext;
reg TCK1;
reg TCK2_xmgxext;
reg TCK2;
reg TDO_xmgxext;
reg TDO;
reg [31:0] r0;
reg [31:0] r1;
reg [31:0] r2;
reg [31:0] r3;
reg [31:0] r4;
reg [31:0] r5;
reg [31:0] r6;
reg [31:0] r7;
reg [31:0] r8;
reg [31:0] r9;
reg [31:0] r10;
reg [31:0] r11;
reg [31:0] r12;
reg [31:0] r13;
reg [31:0] r14;
reg [31:0] r15;
reg [31:0] r8fiq;
reg [31:0] r9fiq;
reg [31:0] r10fiq;
reg [31:0] r11fiq;
reg [31:0] r12fiq;
reg [31:0] r13fiq;
reg [31:0] r14fiq;
reg [31:0] r13irq;
reg [31:0] r14irq;
reg [31:0] r13svc;
reg [31:0] r14svc;
reg [31:0] r13abt;
reg [31:0] r14abt;
reg [31:0] r13und;
reg [31:0] r14und;
reg [31:0] cpsr;
reg [31:0] spsrfiq;
reg [31:0] spsrirq;
reg [31:0] spsrsvc;
reg [31:0] spsrabt;
reg [31:0] spsrund;
reg [31:0] icewp0addr;
reg [31:0] icewp0amask;
reg [31:0] icewp0data;
reg [31:0] icewp0dmask;
reg [8:0] icewp0ctl;
reg [7:0] icewp0cmask;
reg [31:0] icewp1addr;
reg [31:0] icewp1amask;
reg [31:0] icewp1data;
reg [31:0] icewp1dmask;
reg [8:0] icewp1ctl;
reg [7:0] icewp1cmask;
reg [2:0] icedbgctl;
reg [4:0] icedbgstatus;
reg normal;
reg scan;
reg dclk;
reg dbg;
reg hghz;
reg testBus;
reg testDBus;
reg enterDbg;
reg leavingscan;
reg leavingdclk;
reg scan1Dbg;
reg scan0Dbg;
reg sc2updatedr;
reg reads;
reg mem;
reg busen1;
reg isync1;
reg bl3;
reg bl2;
reg bl1;
reg bl0;
reg capture048;
reg capture0148;
parameter
  whichlog = 0,
  JTAG_ID = 1057951503,
  MG_LOGFILE_NAME = "",
  MG_FORCED_DELAY = 0,
  MG_OBJECT = "$DIR_ARM7TDMI",
  MG_OMI_PATH = "",
  MG_MSG_TIME = 0,
  MG_MSG_INSTANCE = 0,
  MG_MSG_SEVERITY = "",
  MG_MSG_SUPPRESS = "",
  MG_MSG_V4_FORMAT = 0;

always @(A)
  A_xmgxext <= A;

always @(BUSDIS)
  BUSDIS_xmgxext <= BUSDIS;

always @(COMMRX)
  COMMRX_xmgxext <= COMMRX;

always @(COMMTX)
  COMMTX_xmgxext <= COMMTX;

always @(D)
  D_xmgxext <= D;

always @(DBGACK)
  DBGACK_xmgxext <= DBGACK;

always @(DBGRQI)
  DBGRQI_xmgxext <= DBGRQI;

always @(DOUT)
  DOUT_xmgxext <= DOUT;

always @(DRIVEBS)
  DRIVEBS_xmgxext <= DRIVEBS;

always @(ECAPCLK)
  ECAPCLK_xmgxext <= ECAPCLK;

always @(ECAPCLKBS)
  ECAPCLKBS_xmgxext <= ECAPCLKBS;

always @(ECLK)
  ECLK_xmgxext <= ECLK;

always @(HIGHZ)
  HIGHZ_xmgxext <= HIGHZ;

always @(ICAPCLKBS)
  ICAPCLKBS_xmgxext <= ICAPCLKBS;

always @(IR)
  IR_xmgxext <= IR;

always @(LOCK)
  LOCK_xmgxext <= LOCK;

always @(MAS)
  MAS_xmgxext <= MAS;

always @(nCPI)
  nCPI_xmgxext <= nCPI;

always @(nENOUT)
  nENOUT_xmgxext <= nENOUT;

always @(nENOUTI)
  nENOUTI_xmgxext <= nENOUTI;

always @(nEXEC)
  nEXEC_xmgxext <= nEXEC;

always @(nHIGHZ)
  nHIGHZ_xmgxext <= nHIGHZ;

always @(nM)
  nM_xmgxext <= nM;

always @(nMREQ)
  nMREQ_xmgxext <= nMREQ;

always @(nOPC)
  nOPC_xmgxext <= nOPC;

always @(nRW)
  nRW_xmgxext <= nRW;

always @(nTDOEN)
  nTDOEN_xmgxext <= nTDOEN;

always @(nTRANS)
  nTRANS_xmgxext <= nTRANS;

always @(PCLKBS)
  PCLKBS_xmgxext <= PCLKBS;

always @(RANGEOUT0)
  RANGEOUT0_xmgxext <= RANGEOUT0;

always @(RANGEOUT1)
  RANGEOUT1_xmgxext <= RANGEOUT1;

always @(RSTCLKBS)
  RSTCLKBS_xmgxext <= RSTCLKBS;

always @(SCREG)
  SCREG_xmgxext <= SCREG;

always @(SDINBS)
  SDINBS_xmgxext <= SDINBS;

always @(SEQ)
  SEQ_xmgxext <= SEQ;

always @(SHCLK2BS)
  SHCLK2BS_xmgxext <= SHCLK2BS;

always @(SHCLKBS)
  SHCLKBS_xmgxext <= SHCLKBS;

always @(TAPSM)
  TAPSM_xmgxext <= TAPSM;

always @(TBIT)
  TBIT_xmgxext <= TBIT;

always @(TCK1)
  TCK1_xmgxext <= TCK1;

always @(TCK2)
  TCK2_xmgxext <= TCK2;

always @(TDO)
  TDO_xmgxext <= TDO;

initial
  begin
    $mm("ARM7TDMI?locator=MG_OBJECT",A,
    ABE,
    ABORT,
    ALE,
    APE,
    BIGEND,
    BL,
    BREAKPT,
    BUSDIS,
    BUSEN,
    COMMRX,
    COMMTX,
    CPA,
    CPB,
    D_xmgxread,
    D,
    DBE,
    DBGACK,
    DBGEN,
    DBGRQ,
    DBGRQI,
    DIN,
    DOUT,
    DRIVEBS,
    ECAPCLK,
    ECAPCLKBS,
    ECLK,
    EXTERN0,
    EXTERN1,
    HIGHZ,
    ICAPCLKBS,
    IR,
    ISYNC,
    LOCK,
    MAS,
    MCLK,
    nCPI,
    nENIN,
    nENOUT,
    nENOUTI,
    nEXEC,
    nFIQ,
    nHIGHZ,
    nIRQ,
    nM,
    nMREQ,
    nOPC,
    nRESET,
    nRW,
    nTDOEN,
    nTRANS,
    nTRST,
    nWAIT,
    PCLKBS,
    RANGEOUT0,
    RANGEOUT1,
    RSTCLKBS,
    SCREG,
    SDINBS,
    SDOUTBS,
    SEQ,
    SHCLK2BS,
    SHCLKBS,
    TAPSM,
    TBE,
    TBIT,
    TCK,
    TCK1,
    TCK2,
    TDI,
    TDO,
    TMS,
    r0,
    r1,
    r2,
    r3,
    r4,
    r5,
    r6,
    r7,
    r8,
    r9,
    r10,
    r11,
    r12,
    r13,
    r14,
    r15,
    r8fiq,
    r9fiq,
    r10fiq,
    r11fiq,
    r12fiq,
    r13fiq,
    r14fiq,
    r13irq,
    r14irq,
    r13svc,
    r14svc,
    r13abt,
    r14abt,
    r13und,
    r14und,
    cpsr,
    spsrfiq,
    spsrirq,
    spsrsvc,
    spsrabt,
    spsrund,
    icewp0addr,
    icewp0amask,
    icewp0data,
    icewp0dmask,
    icewp0ctl,
    icewp0cmask,
    icewp1addr,
    icewp1amask,
    icewp1data,
    icewp1dmask,
    icewp1ctl,
    icewp1cmask,
    icedbgctl,
    icedbgstatus,
    normal,
    scan,
    dclk,
    dbg,
    hghz,
    testBus,
    testDBus,
    enterDbg,
    leavingscan,
    leavingdclk,
    scan1Dbg,
    scan0Dbg,
    sc2updatedr,
    reads,
    mem,
    busen1,
    isync1,
    bl3,
    bl2,
    bl1,
    bl0,
    capture048,
    capture0148);
  end

endmodule

// Inout shell

module ARM7TDMI_inout (A,
  ABE,
  ABORT,
  ALE,
  APE,
  BIGEND,
  BL,
  BREAKPT,
  BUSDIS,
  BUSEN,
  COMMRX,
  COMMTX,
  CPA,
  CPB,
  D_xmgxread,
  D,
  DBE,
  DBGACK,
  DBGEN,
  DBGRQ,
  DBGRQI,
  DIN,
  DOUT,
  DRIVEBS,
  ECAPCLK,
  ECAPCLKBS,
  ECLK,
  EXTERN0,
  EXTERN1,
  HIGHZ,
  ICAPCLKBS,
  IR,
  ISYNC,
  LOCK,
  MAS,
  MCLK,
  nCPI,
  nENIN,
  nENOUT,
  nENOUTI,
  nEXEC,
  nFIQ,
  nHIGHZ,
  nIRQ,
  nM,
  nMREQ,
  nOPC,
  nRESET,
  nRW,
  nTDOEN,
  nTRANS,
  nTRST,
  nWAIT,
  PCLKBS,
  RANGEOUT0,
  RANGEOUT1,
  RSTCLKBS,
  SCREG,
  SDINBS,
  SDOUTBS,
  SEQ,
  SHCLK2BS,
  SHCLKBS,
  TAPSM,
  TBE,
  TBIT,
  TCK,
  TCK1,
  TCK2,
  TDI,
  TDO,
  TMS,
  r0,
  r1,
  r2,
  r3,
  r4,
  r5,
  r6,
  r7,
  r8,
  r9,
  r10,
  r11,
  r12,
  r13,
  r14,
  r15,
  r8fiq,
  r9fiq,
  r10fiq,
  r11fiq,
  r12fiq,
  r13fiq,
  r14fiq,
  r13irq,
  r14irq,
  r13svc,
  r14svc,
  r13abt,
  r14abt,
  r13und,
  r14und,
  cpsr,
  spsrfiq,
  spsrirq,
  spsrsvc,
  spsrabt,
  spsrund,
  icewp0addr,
  icewp0amask,
  icewp0data,
  icewp0dmask,
  icewp0ctl,
  icewp0cmask,
  icewp1addr,
  icewp1amask,
  icewp1data,
  icewp1dmask,
  icewp1ctl,
  icewp1cmask,
  icedbgctl,
  icedbgstatus,
  normal,
  scan,
  dclk,
  dbg,
  hghz,
  testBus,
  testDBus,
  enterDbg,
  leavingscan,
  leavingdclk,
  scan1Dbg,
  scan0Dbg,
  sc2updatedr,
  reads,
  mem,
  busen1,
  isync1,
  bl3,
  bl2,
  bl1,
  bl0,
  capture048,
  capture0148);

output [31:0] A;
input ABE;
input ABORT;
input ALE;
input APE;
input BIGEND;
input [3:0] BL;
input BREAKPT;
output BUSDIS;
input BUSEN;
output COMMRX;
output COMMTX;
input CPA;
input CPB;
input [31:0] D_xmgxread;
output [31:0] D;
input DBE;
output DBGACK;
input DBGEN;
input DBGRQ;
output DBGRQI;
input [31:0] DIN;
output [31:0] DOUT;
output DRIVEBS;
output ECAPCLK;
output ECAPCLKBS;
output ECLK;
input EXTERN0;
input EXTERN1;
output HIGHZ;
output ICAPCLKBS;
output [3:0] IR;
input ISYNC;
output LOCK;
output [1:0] MAS;
input MCLK;
output nCPI;
input nENIN;
output nENOUT;
output nENOUTI;
output nEXEC;
input nFIQ;
output nHIGHZ;
input nIRQ;
output [4:0] nM;
output nMREQ;
output nOPC;
input nRESET;
output nRW;
output nTDOEN;
output nTRANS;
input nTRST;
input nWAIT;
output PCLKBS;
output RANGEOUT0;
output RANGEOUT1;
output RSTCLKBS;
output [3:0] SCREG;
output SDINBS;
input SDOUTBS;
output SEQ;
output SHCLK2BS;
output SHCLKBS;
output [3:0] TAPSM;
input TBE;
output TBIT;
input TCK;
output TCK1;
output TCK2;
input TDI;
output TDO;
input TMS;
output [31:0] r0;
output [31:0] r1;
output [31:0] r2;
output [31:0] r3;
output [31:0] r4;
output [31:0] r5;
output [31:0] r6;
output [31:0] r7;
output [31:0] r8;
output [31:0] r9;
output [31:0] r10;
output [31:0] r11;
output [31:0] r12;
output [31:0] r13;
output [31:0] r14;
output [31:0] r15;
output [31:0] r8fiq;
output [31:0] r9fiq;
output [31:0] r10fiq;
output [31:0] r11fiq;
output [31:0] r12fiq;
output [31:0] r13fiq;
output [31:0] r14fiq;
output [31:0] r13irq;
output [31:0] r14irq;
output [31:0] r13svc;
output [31:0] r14svc;
output [31:0] r13abt;
output [31:0] r14abt;
output [31:0] r13und;
output [31:0] r14und;
output [31:0] cpsr;
output [31:0] spsrfiq;
output [31:0] spsrirq;
output [31:0] spsrsvc;
output [31:0] spsrabt;
output [31:0] spsrund;
output [31:0] icewp0addr;
output [31:0] icewp0amask;
output [31:0] icewp0data;
output [31:0] icewp0dmask;
output [8:0] icewp0ctl;
output [7:0] icewp0cmask;
output [31:0] icewp1addr;
output [31:0] icewp1amask;
output [31:0] icewp1data;
output [31:0] icewp1dmask;
output [8:0] icewp1ctl;
output [7:0] icewp1cmask;
output [2:0] icedbgctl;
output [4:0] icedbgstatus;
output normal;
output scan;
output dclk;
output dbg;
output hghz;
output testBus;
output testDBus;
output enterDbg;
output leavingscan;
output leavingdclk;
output scan1Dbg;
output scan0Dbg;
output sc2updatedr;
output reads;
output mem;
output busen1;
output isync1;
output bl3;
output bl2;
output bl1;
output bl0;
output capture048;
output capture0148;

parameter
  whichlog = 0,
  JTAG_ID = 1057951503,
  MG_LOGFILE_NAME = "",
  MG_FORCED_DELAY = 0,
  MG_OBJECT = "$DIR_ARM7TDMI",
  MG_OMI_PATH = "",
  MG_MSG_TIME = 0,
  MG_MSG_INSTANCE = 0,
  MG_MSG_SEVERITY = "",
  MG_MSG_SUPPRESS = "",
  MG_MSG_V4_FORMAT = 0;

ARM7TDMI_nba thenba (A,
    ABE,
    ABORT,
    ALE,
    APE,
    BIGEND,
    BL,
    BREAKPT,
    BUSDIS,
    BUSEN,
    COMMRX,
    COMMTX,
    CPA,
    CPB,
    D_xmgxread,
    D,
    DBE,
    DBGACK,
    DBGEN,
    DBGRQ,
    DBGRQI,
    DIN,
    DOUT,
    DRIVEBS,
    ECAPCLK,
    ECAPCLKBS,
    ECLK,
    EXTERN0,
    EXTERN1,
    HIGHZ,
    ICAPCLKBS,
    IR,
    ISYNC,
    LOCK,
    MAS,
    MCLK,
    nCPI,
    nENIN,
    nENOUT,
    nENOUTI,
    nEXEC,
    nFIQ,
    nHIGHZ,
    nIRQ,
    nM,
    nMREQ,
    nOPC,
    nRESET,
    nRW,
    nTDOEN,
    nTRANS,
    nTRST,
    nWAIT,
    PCLKBS,
    RANGEOUT0,
    RANGEOUT1,
    RSTCLKBS,
    SCREG,
    SDINBS,
    SDOUTBS,
    SEQ,
    SHCLK2BS,
    SHCLKBS,
    TAPSM,
    TBE,
    TBIT,
    TCK,
    TCK1,
    TCK2,
    TDI,
    TDO,
    TMS,
    r0,
    r1,
    r2,
    r3,
    r4,
    r5,
    r6,
    r7,
    r8,
    r9,
    r10,
    r11,
    r12,
    r13,
    r14,
    r15,
    r8fiq,
    r9fiq,
    r10fiq,
    r11fiq,
    r12fiq,
    r13fiq,
    r14fiq,
    r13irq,
    r14irq,
    r13svc,
    r14svc,
    r13abt,
    r14abt,
    r13und,
    r14und,
    cpsr,
    spsrfiq,
    spsrirq,
    spsrsvc,
    spsrabt,
    spsrund,
    icewp0addr,
    icewp0amask,
    icewp0data,
    icewp0dmask,
    icewp0ctl,
    icewp0cmask,
    icewp1addr,
    icewp1amask,
    icewp1data,
    icewp1dmask,
    icewp1ctl,
    icewp1cmask,
    icedbgctl,
    icedbgstatus,
    normal,
    scan,
    dclk,
    dbg,
    hghz,
    testBus,
    testDBus,
    enterDbg,
    leavingscan,
    leavingdclk,
    scan1Dbg,
    scan0Dbg,
    sc2updatedr,
    reads,
    mem,
    busen1,
    isync1,
    bl3,
    bl2,
    bl1,
    bl0,
    capture048,
    capture0148);

defparam
  thenba.whichlog = whichlog,
  thenba.JTAG_ID = JTAG_ID,
  thenba.MG_LOGFILE_NAME = MG_LOGFILE_NAME,
  thenba.MG_FORCED_DELAY = MG_FORCED_DELAY,
  thenba.MG_OBJECT = MG_OBJECT,
  thenba.MG_OMI_PATH = MG_OMI_PATH,
  thenba.MG_MSG_TIME = MG_MSG_TIME,
  thenba.MG_MSG_INSTANCE = MG_MSG_INSTANCE,
  thenba.MG_MSG_SEVERITY = MG_MSG_SEVERITY,
  thenba.MG_MSG_SUPPRESS = MG_MSG_SUPPRESS,
  thenba.MG_MSG_V4_FORMAT = MG_MSG_V4_FORMAT;

endmodule

// Device shell

module ARM7TDMI (A,
  ABE,
  ABORT,
  ALE,
  APE,
  BIGEND,
  BL,
  BREAKPT,
  BUSDIS,
  BUSEN,
  COMMRX,
  COMMTX,
  CPA,
  CPB,
  D,
  DBE,
  DBGACK,
  DBGEN,
  DBGRQ,
  DBGRQI,
  DIN,
  DOUT,
  DRIVEBS,
  ECAPCLK,
  ECAPCLKBS,
  ECLK,
  EXTERN0,
  EXTERN1,
  HIGHZ,
  ICAPCLKBS,
  IR,
  ISYNC,
  LOCK,
  MAS,
  MCLK,
  nCPI,
  nENIN,
  nENOUT,
  nENOUTI,
  nEXEC,
  nFIQ,
  nHIGHZ,
  nIRQ,
  nM,
  nMREQ,
  nOPC,
  nRESET,
  nRW,
  nTDOEN,
  nTRANS,
  nTRST,
  nWAIT,
  PCLKBS,
  RANGEOUT0,
  RANGEOUT1,
  RSTCLKBS,
  SCREG,
  SDINBS,
  SDOUTBS,
  SEQ,
  SHCLK2BS,
  SHCLKBS,
  TAPSM,
  TBE,
  TBIT,
  TCK,
  TCK1,
  TCK2,
  TDI,
  TDO,
  TMS);

output [31:0] A;
input ABE;
input ABORT;
input ALE;
input APE;
input BIGEND;
input [3:0] BL;
input BREAKPT;
output BUSDIS;
input BUSEN;
output COMMRX;
output COMMTX;
input CPA;
input CPB;
inout [31:0] D;
input DBE;
output DBGACK;
input DBGEN;
input DBGRQ;
output DBGRQI;
input [31:0] DIN;
output [31:0] DOUT;
output DRIVEBS;
output ECAPCLK;
output ECAPCLKBS;
output ECLK;
input EXTERN0;
input EXTERN1;
output HIGHZ;
output ICAPCLKBS;
output [3:0] IR;
input ISYNC;
output LOCK;
output [1:0] MAS;
input MCLK;
output nCPI;
input nENIN;
output nENOUT;
output nENOUTI;
output nEXEC;
input nFIQ;
output nHIGHZ;
input nIRQ;
output [4:0] nM;
output nMREQ;
output nOPC;
input nRESET;
output nRW;
output nTDOEN;
output nTRANS;
input nTRST;
input nWAIT;
output PCLKBS;
output RANGEOUT0;
output RANGEOUT1;
output RSTCLKBS;
output [3:0] SCREG;
output SDINBS;
input SDOUTBS;
output SEQ;
output SHCLK2BS;
output SHCLKBS;
output [3:0] TAPSM;
input TBE;
output TBIT;
input TCK;
output TCK1;
output TCK2;
input TDI;
output TDO;
input TMS;

wire [31:0] r0;
wire [31:0] r1;
wire [31:0] r2;
wire [31:0] r3;
wire [31:0] r4;
wire [31:0] r5;
wire [31:0] r6;
wire [31:0] r7;
wire [31:0] r8;
wire [31:0] r9;
wire [31:0] r10;
wire [31:0] r11;
wire [31:0] r12;
wire [31:0] r13;
wire [31:0] r14;
wire [31:0] r15;
wire [31:0] r8fiq;
wire [31:0] r9fiq;
wire [31:0] r10fiq;
wire [31:0] r11fiq;
wire [31:0] r12fiq;
wire [31:0] r13fiq;
wire [31:0] r14fiq;
wire [31:0] r13irq;
wire [31:0] r14irq;
wire [31:0] r13svc;
wire [31:0] r14svc;
wire [31:0] r13abt;
wire [31:0] r14abt;
wire [31:0] r13und;
wire [31:0] r14und;
wire [31:0] cpsr;
wire [31:0] spsrfiq;
wire [31:0] spsrirq;
wire [31:0] spsrsvc;
wire [31:0] spsrabt;
wire [31:0] spsrund;
wire [31:0] icewp0addr;
wire [31:0] icewp0amask;
wire [31:0] icewp0data;
wire [31:0] icewp0dmask;
wire [8:0] icewp0ctl;
wire [7:0] icewp0cmask;
wire [31:0] icewp1addr;
wire [31:0] icewp1amask;
wire [31:0] icewp1data;
wire [31:0] icewp1dmask;
wire [8:0] icewp1ctl;
wire [7:0] icewp1cmask;
wire [2:0] icedbgctl;
wire [4:0] icedbgstatus;
wire normal;
wire scan;
wire dclk;
wire dbg;
wire hghz;
wire testBus;
wire testDBus;
wire enterDbg;
wire leavingscan;
wire leavingdclk;
wire scan1Dbg;
wire scan0Dbg;
wire sc2updatedr;
wire reads;
wire mem;
wire busen1;
wire isync1;
wire bl3;
wire bl2;
wire bl1;
wire bl0;
wire capture048;
wire capture0148;

parameter
  whichlog = 0,
  JTAG_ID = 1057951503,
  MG_LOGFILE_NAME = "",
  MG_FORCED_DELAY = 0,
  MG_OBJECT = "$DIR_ARM7TDMI",
  MG_OMI_PATH = "",
  MG_MSG_TIME = 0,
  MG_MSG_INSTANCE = 0,
  MG_MSG_SEVERITY = "",
  MG_MSG_SUPPRESS = "",
  MG_MSG_V4_FORMAT = 0;

ARM7TDMI_inout theinout (A,
    ABE,
    ABORT,
    ALE,
    APE,
    BIGEND,
    BL,
    BREAKPT,
    BUSDIS,
    BUSEN,
    COMMRX,
    COMMTX,
    CPA,
    CPB,
    D,
    D,
    DBE,
    DBGACK,
    DBGEN,
    DBGRQ,
    DBGRQI,
    DIN,
    DOUT,
    DRIVEBS,
    ECAPCLK,
    ECAPCLKBS,
    ECLK,
    EXTERN0,
    EXTERN1,
    HIGHZ,
    ICAPCLKBS,
    IR,
    ISYNC,
    LOCK,
    MAS,
    MCLK,
    nCPI,
    nENIN,
    nENOUT,
    nENOUTI,
    nEXEC,
    nFIQ,
    nHIGHZ,
    nIRQ,
    nM,
    nMREQ,
    nOPC,
    nRESET,
    nRW,
    nTDOEN,
    nTRANS,
    nTRST,
    nWAIT,
    PCLKBS,
    RANGEOUT0,
    RANGEOUT1,
    RSTCLKBS,
    SCREG,
    SDINBS,
    SDOUTBS,
    SEQ,
    SHCLK2BS,
    SHCLKBS,
    TAPSM,
    TBE,
    TBIT,
    TCK,
    TCK1,
    TCK2,
    TDI,
    TDO,
    TMS,
    r0,
    r1,
    r2,
    r3,
    r4,
    r5,
    r6,
    r7,
    r8,
    r9,
    r10,
    r11,
    r12,
    r13,
    r14,
    r15,
    r8fiq,
    r9fiq,
    r10fiq,
    r11fiq,
    r12fiq,
    r13fiq,
    r14fiq,
    r13irq,
    r14irq,
    r13svc,
    r14svc,
    r13abt,
    r14abt,
    r13und,
    r14und,
    cpsr,
    spsrfiq,
    spsrirq,
    spsrsvc,
    spsrabt,
    spsrund,
    icewp0addr,
    icewp0amask,
    icewp0data,
    icewp0dmask,
    icewp0ctl,
    icewp0cmask,
    icewp1addr,
    icewp1amask,
    icewp1data,
    icewp1dmask,
    icewp1ctl,
    icewp1cmask,
    icedbgctl,
    icedbgstatus,
    normal,
    scan,
    dclk,
    dbg,
    hghz,
    testBus,
    testDBus,
    enterDbg,
    leavingscan,
    leavingdclk,
    scan1Dbg,
    scan0Dbg,
    sc2updatedr,
    reads,
    mem,
    busen1,
    isync1,
    bl3,
    bl2,
    bl1,
    bl0,
    capture048,
    capture0148);

defparam
  theinout.whichlog = whichlog,
  theinout.JTAG_ID = JTAG_ID,
  theinout.MG_LOGFILE_NAME = MG_LOGFILE_NAME,
  theinout.MG_FORCED_DELAY = MG_FORCED_DELAY,
  theinout.MG_OBJECT = MG_OBJECT,
  theinout.MG_OMI_PATH = MG_OMI_PATH,
  theinout.MG_MSG_TIME = MG_MSG_TIME,
  theinout.MG_MSG_INSTANCE = MG_MSG_INSTANCE,
  theinout.MG_MSG_SEVERITY = MG_MSG_SEVERITY,
  theinout.MG_MSG_SUPPRESS = MG_MSG_SUPPRESS,
  theinout.MG_MSG_V4_FORMAT = MG_MSG_V4_FORMAT;

endmodule

