#-----------------------------------------------------------------------
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000-2001 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#-----------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile,v
#- File Revision          : 1.5
#-
#- Release Information    : ADK_REL1v1
#-
#-----------------------------------------------------------------------
#-  Purpose  :
#-             Standard Verilog Library Makefile
#-----------------------------------------------------------------------

MODULES = Vic.v \
          VicAhbifReg.v \
          VicRevAnd.v \
          VicPriority.v \
          VicSynctoHCLK.v \
          VicVectBank.v


PERIPH =  Interrupt


include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

########################## End of file #################################
