#- --=========================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2001-2002 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- -----------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.7
#-
#- Release Information    : PrimeCell(TM)-PL172-r2p3-00rel0
#-
#- -----------------------------------------------------------------------------
#- Purpose  :
#-            makefile for Verilog Trickbox files
#-
#- --=========================================================================--

MODULES =  MpmcTrParams.v \
           MpmcTrRegBlk.v \
           MpmcTrAhbif.v \
           MpmcTrClkResGen.v \
           MpmcTrProChkr.v \
           MpmcTrSnp.v \
           MpmcTrMemAhbifReg.v \
           MpmcTrMemArray.v \
           MpmcTrMemRdWrCtl.v \
           MpmcTrick.v \
           MpmcTrickMem.v

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk 

##################################### End ######################################
