#- --=========================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000-2001 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#- -----------------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.5
#-
#- Release Information    : PrimeCell(TM)-PL081-REL1v0
#-
#- -----------------------------------------------------------------------------
#- Purpose  :
#-            makefile for VHDL Trickbox files
#-
#- --=========================================================================--

MODULES =  DmacTrPackage.vhd \
           DmacTrIntArb.vhd \
           DmacTrAhbSlaveIf.vhd \
           DmacTrMasWrap.vhd \
           DmacTrAhbLite.vhd \
           DmacTrAhbMaster.vhd \
           DmacTrRouter.vhd \
           DmacTrChLogic.vhd \
           DmacTrBehaviour.vhd \
           DmacTrProChkr.vhd \
           DmacTrMem.vhd \
           DmacTrCounter.vhd \
           DmacTrPeriph.vhd \
           DmacTrGntGen.vhd \
           DmacTrick.vhd

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk 

##################################### End ######################################
