library verilog;
use verilog.vl_types.all;
entity epxa10 is
    generic(
        mg_logfile_name : string  := ""
    );
    port(
        clkref          : in     vl_logic;
        npor            : in     vl_logic;
        reserved        : in     vl_logic;
        debugen         : in     vl_logic;
        bootflash       : in     vl_logic;
        nconfig         : in     vl_logic;
        msel            : in     vl_logic_vector(1 downto 0);
        cen             : in     vl_logic;
        dclk            : in     vl_logic;
        cs              : in     vl_logic;
        csn             : in     vl_logic;
        rsn             : in     vl_logic;
        wsn             : in     vl_logic;
        datain          : in     vl_logic_vector(6 downto 0);
        exttck          : in     vl_logic;
        extntrst        : in     vl_logic;
        exttms          : in     vl_logic;
        ceon            : out    vl_logic;
        rdynbsy         : out    vl_logic;
        reset_in_n      : in     vl_logic;
        reset_out_n     : out    vl_logic;
        statusn         : inout  vl_logic;
        condone         : inout  vl_logic;
        datain7         : inout  vl_logic;
        exttdo          : inout  vl_logic;
        proctdi         : in     vl_logic;
        proctms         : in     vl_logic;
        proctck         : in     vl_logic;
        procntrst       : in     vl_logic;
        proctdo         : inout  vl_logic;
        jselect         : in     vl_logic;
        pldosc          : in     vl_logic;
        pldpor          : in     vl_logic;
        pldtdimux       : in     vl_logic;
        pldtdotap       : in     vl_logic;
        pldstatuson     : in     vl_logic;
        pldcondoneo     : in     vl_logic;
        pldceon         : in     vl_logic;
        pldcboscen      : in     vl_logic;
        pldrdynbsy      : in     vl_logic;
        pldcbendinit    : in     vl_logic;
        pldmsel         : out    vl_logic_vector(1 downto 0);
        pldconfign      : out    vl_logic;
        pldstatusin     : out    vl_logic;
        pldcondonei     : out    vl_logic;
        pldcen          : out    vl_logic;
        plddclk         : out    vl_logic;
        plddata         : out    vl_logic_vector(7 downto 0);
        pldoscen        : out    vl_logic;
        sdramdqin       : in     vl_logic_vector(31 downto 0);
        sdramdqsin      : in     vl_logic_vector(3 downto 0);
        sdramdqout      : out    vl_logic_vector(31 downto 0);
        sdramdqsout     : out    vl_logic_vector(3 downto 0);
        sdramdqm        : out    vl_logic_vector(3 downto 0);
        sdramaddr       : out    vl_logic_vector(14 downto 0);
        sdramclk        : out    vl_logic;
        sdramclkn       : out    vl_logic;
        sdramclke       : out    vl_logic;
        sdramwen        : out    vl_logic;
        sdramcasn       : out    vl_logic;
        sdramrasn       : out    vl_logic;
        sdramcsn        : out    vl_logic_vector(1 downto 0);
        sdramdqoe       : out    vl_logic_vector(3 downto 0);
        sdramdqsoe      : out    vl_logic_vector(3 downto 0);
        sdramioselect   : out    vl_logic;
        ebidqin         : in     vl_logic_vector(15 downto 0);
        ebiack          : in     vl_logic;
        ebidqout        : out    vl_logic_vector(15 downto 0);
        ebiaddr         : out    vl_logic_vector(24 downto 0);
        ebiwen          : out    vl_logic;
        ebioen          : out    vl_logic;
        ebibe           : out    vl_logic_vector(1 downto 0);
        ebics           : out    vl_logic_vector(3 downto 0);
        ebiclk          : out    vl_logic;
        ebidqoe         : out    vl_logic;
        ebiioselect     : out    vl_logic;
        intextn         : in     vl_logic;
        uartctsn        : in     vl_logic;
        uartdcdin       : in     vl_logic;
        uartdsrn        : in     vl_logic;
        uartrxd         : in     vl_logic;
        uartriin        : in     vl_logic;
        uarttxd         : out    vl_logic;
        uartrtsn        : out    vl_logic;
        uartdtrn        : out    vl_logic;
        uartrion        : out    vl_logic;
        uartdcdon       : out    vl_logic;
        uartdcdrioe     : out    vl_logic;
        uartioselect    : out    vl_logic;
        traceclk        : out    vl_logic;
        tracepipestat   : out    vl_logic_vector(2 downto 0);
        tracepkt        : out    vl_logic_vector(15 downto 0);
        tracesync       : out    vl_logic;
        traceioselect   : out    vl_logic;
        slavehclkpld    : in     vl_logic;
        slavehwrite     : in     vl_logic;
        slavehreadyi    : in     vl_logic;
        slavehselreg    : in     vl_logic;
        slavehsel       : in     vl_logic;
        slavehmastlock  : in     vl_logic;
        slavehtrans     : in     vl_logic_vector(1 downto 0);
        slavehsize      : in     vl_logic_vector(1 downto 0);
        slavehburst     : in     vl_logic_vector(2 downto 0);
        slavehaddr      : in     vl_logic_vector(31 downto 0);
        slavehwdata     : in     vl_logic_vector(31 downto 0);
        slavehreadyo    : out    vl_logic;
        slavehresp      : out    vl_logic_vector(1 downto 0);
        slavehrdata     : out    vl_logic_vector(31 downto 0);
        slavebuserrint  : out    vl_logic;
        masterhclkbridge: in     vl_logic;
        masterhready    : in     vl_logic;
        masterhgrant    : in     vl_logic;
        masterhresp     : in     vl_logic_vector(1 downto 0);
        masterhrdata    : in     vl_logic_vector(31 downto 0);
        masterhwrite    : out    vl_logic;
        masterhlock     : out    vl_logic;
        masterhbusreq   : out    vl_logic;
        masterhtrans    : out    vl_logic_vector(1 downto 0);
        masterhsize     : out    vl_logic_vector(1 downto 0);
        masterhburst    : out    vl_logic_vector(2 downto 0);
        masterhaddr     : out    vl_logic_vector(31 downto 0);
        masterhwdata    : out    vl_logic_vector(31 downto 0);
        clk0dp0         : in     vl_logic;
        clk1dp0         : in     vl_logic;
        clk0dp1         : in     vl_logic;
        clk1dp1         : in     vl_logic;
        r0a0            : in     vl_logic_vector(15 downto 0);
        r0a1            : in     vl_logic_vector(14 downto 0);
        r0ce0           : in     vl_logic;
        r0ce1           : in     vl_logic;
        r0rd            : in     vl_logic_vector(31 downto 0);
        r0rw0           : in     vl_logic;
        r0rw1           : in     vl_logic;
        r0rq            : out    vl_logic_vector(31 downto 0);
        lockreqdp0      : in     vl_logic;
        lockgrntdp0     : out    vl_logic;
        cramdp0         : in     vl_logic_vector(3 downto 0);
        r1a0            : in     vl_logic_vector(15 downto 0);
        r1a1            : in     vl_logic_vector(14 downto 0);
        r1ce0           : in     vl_logic;
        r1ce1           : in     vl_logic;
        r1rd            : in     vl_logic_vector(31 downto 0);
        r1rw0           : in     vl_logic;
        r1rw1           : in     vl_logic;
        r1rq            : out    vl_logic_vector(31 downto 0);
        lockreqdp1      : in     vl_logic;
        lockgrntdp1     : out    vl_logic;
        cramdp1         : in     vl_logic_vector(3 downto 0);
        highaddress     : in     vl_logic;
        dpcram          : in     vl_logic_vector(1 downto 0);
        intpld          : in     vl_logic_vector(5 downto 0);
        intuart         : out    vl_logic;
        inttimer0       : out    vl_logic;
        inttimer1       : out    vl_logic;
        intproc0        : out    vl_logic;
        intproc1        : out    vl_logic;
        debugrq         : in     vl_logic;
        debugext0       : in     vl_logic;
        debugext1       : in     vl_logic;
        debugiebrkpt    : in     vl_logic;
        debugdewpt      : in     vl_logic;
        debugextin      : in     vl_logic_vector(3 downto 0);
        debugack        : out    vl_logic;
        debugrng0       : out    vl_logic;
        debugrng1       : out    vl_logic;
        debugextout     : out    vl_logic_vector(3 downto 0);
        initialize      : in     vl_logic;
        shortreset      : in     vl_logic;
        clk_pll1        : in     vl_logic;
        clk_pll2        : in     vl_logic;
        pll_por         : out    vl_logic;
        pll_entest      : out    vl_logic;
        pll1_lock       : in     vl_logic;
        pll1_up         : in     vl_logic;
        pll1_down       : in     vl_logic;
        pll1_ctrl       : out    vl_logic_vector(14 downto 0);
        pll2_ctrl       : out    vl_logic_vector(14 downto 0);
        pll2_lock       : in     vl_logic;
        pll2_up         : in     vl_logic;
        pll2_down       : in     vl_logic;
        pll1_cnt        : out    vl_logic_vector(27 downto 0);
        pll2_cnt        : out    vl_logic_vector(27 downto 0)
    );
end epxa10;
