library verilog;
use verilog.vl_types.all;
entity writechannel is
    generic(
        bus_wid         : integer := 32;
        addr_wid        : integer := 32;
        masterid_wid    : integer := 4;
        slaveid_wid     : integer := 6;
        awlen_wid       : integer := 4;
        awsize_wid      : integer := 3;
        awburst_wid     : integer := 2;
        awlock_wid      : integer := 2;
        awcache_wid     : integer := 4;
        awprot_wid      : integer := 3;
        wstrb_wid       : integer := 4;
        bresp_wid       : integer := 2;
        rresp_wid       : integer := 2;
        arlen_wid       : integer := 4;
        arburst_wid     : integer := 2;
        arlock_wid      : integer := 2;
        arcache_wid     : integer := 4;
        arprot_wid      : integer := 3;
        master_wid      : integer := 3;
        slave_wid       : integer := 3;
        slave_num       : integer := 6;
        master_num      : integer := 4;
        selmaster_wid   : integer := 2;
        wr_reqdepth_wid : integer := 4;
        rd_reqdepth_wid : integer := 4;
        wrpermit_slavecntwid: integer := 3;
        rdpermit_slavecntwid: integer := 3;
        arsize_wid      : integer := 3;
        masterid0_wid   : integer := 4;
        masterid1_wid   : integer := 4;
        masterid2_wid   : integer := 4;
        masterid3_wid   : integer := 4;
        maxmasterid_wid : integer := 4;
        blankmasterid0_wid: integer := 0;
        blankmasterid1_wid: integer := 0;
        blankmasterid2_wid: integer := 0;
        blankmasterid3_wid: integer := 0;
        slaveid0_wid    : integer := 6;
        slaveid1_wid    : integer := 6;
        slaveid2_wid    : integer := 6;
        slaveid3_wid    : integer := 6;
        slaveid4_wid    : integer := 6;
        slaveid5_wid    : integer := 7;
        selmaster0_wid  : integer := 2;
        selmaster1_wid  : integer := 2;
        selmaster2_wid  : integer := 2;
        selmaster3_wid  : integer := 2;
        selmaster4_wid  : integer := 2;
        selmaster5_wid  : integer := 3;
        slave_masterid0_wid: integer := 4;
        slave_masterid1_wid: integer := 4;
        slave_masterid2_wid: integer := 4;
        slave_masterid3_wid: integer := 4;
        slave_masterid4_wid: integer := 4;
        slave_masterid5_wid: integer := 4
    );
    port(
        awidm02si0      : in     vl_logic_vector;
        awaddrm02si0    : in     vl_logic_vector;
        awlenm02si0     : in     vl_logic_vector;
        awsizem02si0    : in     vl_logic_vector;
        awburstm02si0   : in     vl_logic_vector;
        awlockm02si0    : in     vl_logic_vector;
        awcachem02si0   : in     vl_logic_vector;
        awprotm02si0    : in     vl_logic_vector;
        awvalidm02si0   : in     vl_logic;
        awreadysi02m0   : out    vl_logic;
        widm02si0       : in     vl_logic_vector;
        wdatam02si0     : in     vl_logic_vector;
        wstrbm02si0     : in     vl_logic_vector;
        wlastm02si0     : in     vl_logic;
        wvalidm02si0    : in     vl_logic;
        wreadysi02m0    : out    vl_logic;
        bidsi02m0       : out    vl_logic_vector;
        brespsi02m0     : out    vl_logic_vector;
        bvalidsi02m0    : out    vl_logic;
        breadym02si0    : in     vl_logic;
        awidm12si1      : in     vl_logic_vector;
        awaddrm12si1    : in     vl_logic_vector;
        awlenm12si1     : in     vl_logic_vector;
        awsizem12si1    : in     vl_logic_vector;
        awburstm12si1   : in     vl_logic_vector;
        awlockm12si1    : in     vl_logic_vector;
        awcachem12si1   : in     vl_logic_vector;
        awprotm12si1    : in     vl_logic_vector;
        awvalidm12si1   : in     vl_logic;
        awreadysi12m1   : out    vl_logic;
        widm12si1       : in     vl_logic_vector;
        wdatam12si1     : in     vl_logic_vector;
        wstrbm12si1     : in     vl_logic_vector;
        wlastm12si1     : in     vl_logic;
        wvalidm12si1    : in     vl_logic;
        wreadysi12m1    : out    vl_logic;
        bidsi12m1       : out    vl_logic_vector;
        brespsi12m1     : out    vl_logic_vector;
        bvalidsi12m1    : out    vl_logic;
        breadym12si1    : in     vl_logic;
        awidm22si2      : in     vl_logic_vector;
        awaddrm22si2    : in     vl_logic_vector;
        awlenm22si2     : in     vl_logic_vector;
        awsizem22si2    : in     vl_logic_vector;
        awburstm22si2   : in     vl_logic_vector;
        awlockm22si2    : in     vl_logic_vector;
        awcachem22si2   : in     vl_logic_vector;
        awprotm22si2    : in     vl_logic_vector;
        awvalidm22si2   : in     vl_logic;
        awreadysi22m2   : out    vl_logic;
        widm22si2       : in     vl_logic_vector;
        wdatam22si2     : in     vl_logic_vector;
        wstrbm22si2     : in     vl_logic_vector;
        wlastm22si2     : in     vl_logic;
        wvalidm22si2    : in     vl_logic;
        wreadysi22m2    : out    vl_logic;
        bidsi22m2       : out    vl_logic_vector;
        brespsi22m2     : out    vl_logic_vector;
        bvalidsi22m2    : out    vl_logic;
        breadym22si2    : in     vl_logic;
        awidm32si3      : in     vl_logic_vector;
        awaddrm32si3    : in     vl_logic_vector;
        awlenm32si3     : in     vl_logic_vector;
        awsizem32si3    : in     vl_logic_vector;
        awburstm32si3   : in     vl_logic_vector;
        awlockm32si3    : in     vl_logic_vector;
        awcachem32si3   : in     vl_logic_vector;
        awprotm32si3    : in     vl_logic_vector;
        awvalidm32si3   : in     vl_logic;
        awreadysi32m3   : out    vl_logic;
        widm32si3       : in     vl_logic_vector;
        wdatam32si3     : in     vl_logic_vector;
        wstrbm32si3     : in     vl_logic_vector;
        wlastm32si3     : in     vl_logic;
        wvalidm32si3    : in     vl_logic;
        wreadysi32m3    : out    vl_logic;
        bidsi32m3       : out    vl_logic_vector;
        brespsi32m3     : out    vl_logic_vector;
        bvalidsi32m3    : out    vl_logic;
        breadym32si3    : in     vl_logic;
        awidmi02s0      : out    vl_logic_vector;
        awaddrmi02s0    : out    vl_logic_vector;
        awlenmi02s0     : out    vl_logic_vector;
        awsizemi02s0    : out    vl_logic_vector;
        awburstmi02s0   : out    vl_logic_vector;
        awlockmi02s0    : out    vl_logic_vector;
        awcachemi02s0   : out    vl_logic_vector;
        awprotmi02s0    : out    vl_logic_vector;
        awvalidmi02s0   : out    vl_logic;
        awreadys02mi0   : in     vl_logic;
        widmi02s0       : out    vl_logic_vector;
        wdatami02s0     : out    vl_logic_vector;
        wstrbmi02s0     : out    vl_logic_vector;
        wlastmi02s0     : out    vl_logic;
        wvalidmi02s0    : out    vl_logic;
        wreadys02mi0    : in     vl_logic;
        bids02mi0       : in     vl_logic_vector;
        bresps02mi0     : in     vl_logic_vector;
        bvalids02mi0    : in     vl_logic;
        breadymi02s0    : out    vl_logic;
        awidmi12s1      : out    vl_logic_vector;
        awaddrmi12s1    : out    vl_logic_vector;
        awlenmi12s1     : out    vl_logic_vector;
        awsizemi12s1    : out    vl_logic_vector;
        awburstmi12s1   : out    vl_logic_vector;
        awlockmi12s1    : out    vl_logic_vector;
        awcachemi12s1   : out    vl_logic_vector;
        awprotmi12s1    : out    vl_logic_vector;
        awvalidmi12s1   : out    vl_logic;
        awreadys12mi1   : in     vl_logic;
        widmi12s1       : out    vl_logic_vector;
        wdatami12s1     : out    vl_logic_vector;
        wstrbmi12s1     : out    vl_logic_vector;
        wlastmi12s1     : out    vl_logic;
        wvalidmi12s1    : out    vl_logic;
        wreadys12mi1    : in     vl_logic;
        bids12mi1       : in     vl_logic_vector;
        bresps12mi1     : in     vl_logic_vector;
        bvalids12mi1    : in     vl_logic;
        breadymi12s1    : out    vl_logic;
        awidmi22s2      : out    vl_logic_vector;
        awaddrmi22s2    : out    vl_logic_vector;
        awlenmi22s2     : out    vl_logic_vector;
        awsizemi22s2    : out    vl_logic_vector;
        awburstmi22s2   : out    vl_logic_vector;
        awlockmi22s2    : out    vl_logic_vector;
        awcachemi22s2   : out    vl_logic_vector;
        awprotmi22s2    : out    vl_logic_vector;
        awvalidmi22s2   : out    vl_logic;
        awreadys22mi2   : in     vl_logic;
        widmi22s2       : out    vl_logic_vector;
        wdatami22s2     : out    vl_logic_vector;
        wstrbmi22s2     : out    vl_logic_vector;
        wlastmi22s2     : out    vl_logic;
        wvalidmi22s2    : out    vl_logic;
        wreadys22mi2    : in     vl_logic;
        bids22mi2       : in     vl_logic_vector;
        bresps22mi2     : in     vl_logic_vector;
        bvalids22mi2    : in     vl_logic;
        breadymi22s2    : out    vl_logic;
        awidmi32s3      : out    vl_logic_vector;
        awaddrmi32s3    : out    vl_logic_vector;
        awlenmi32s3     : out    vl_logic_vector;
        awsizemi32s3    : out    vl_logic_vector;
        awburstmi32s3   : out    vl_logic_vector;
        awlockmi32s3    : out    vl_logic_vector;
        awcachemi32s3   : out    vl_logic_vector;
        awprotmi32s3    : out    vl_logic_vector;
        awvalidmi32s3   : out    vl_logic;
        awreadys32mi3   : in     vl_logic;
        widmi32s3       : out    vl_logic_vector;
        wdatami32s3     : out    vl_logic_vector;
        wstrbmi32s3     : out    vl_logic_vector;
        wlastmi32s3     : out    vl_logic;
        wvalidmi32s3    : out    vl_logic;
        wreadys32mi3    : in     vl_logic;
        bids32mi3       : in     vl_logic_vector;
        bresps32mi3     : in     vl_logic_vector;
        bvalids32mi3    : in     vl_logic;
        breadymi32s3    : out    vl_logic;
        awidmi42s4      : out    vl_logic_vector;
        awaddrmi42s4    : out    vl_logic_vector;
        awlenmi42s4     : out    vl_logic_vector;
        awsizemi42s4    : out    vl_logic_vector;
        awburstmi42s4   : out    vl_logic_vector;
        awlockmi42s4    : out    vl_logic_vector;
        awcachemi42s4   : out    vl_logic_vector;
        awprotmi42s4    : out    vl_logic_vector;
        awvalidmi42s4   : out    vl_logic;
        awreadys42mi4   : in     vl_logic;
        widmi42s4       : out    vl_logic_vector;
        wdatami42s4     : out    vl_logic_vector;
        wstrbmi42s4     : out    vl_logic_vector;
        wlastmi42s4     : out    vl_logic;
        wvalidmi42s4    : out    vl_logic;
        wreadys42mi4    : in     vl_logic;
        bids42mi4       : in     vl_logic_vector;
        bresps42mi4     : in     vl_logic_vector;
        bvalids42mi4    : in     vl_logic;
        breadymi42s4    : out    vl_logic;
        awidmi52s5      : out    vl_logic_vector;
        awaddrmi52s5    : out    vl_logic_vector;
        awlenmi52s5     : out    vl_logic_vector;
        awsizemi52s5    : out    vl_logic_vector;
        awburstmi52s5   : out    vl_logic_vector;
        awlockmi52s5    : out    vl_logic_vector;
        awcachemi52s5   : out    vl_logic_vector;
        awprotmi52s5    : out    vl_logic_vector;
        awvalidmi52s5   : out    vl_logic;
        awreadys52mi5   : in     vl_logic;
        widmi52s5       : out    vl_logic_vector;
        wdatami52s5     : out    vl_logic_vector;
        wstrbmi52s5     : out    vl_logic_vector;
        wlastmi52s5     : out    vl_logic;
        wvalidmi52s5    : out    vl_logic;
        wreadys52mi5    : in     vl_logic;
        bids52mi5       : in     vl_logic_vector;
        bresps52mi5     : in     vl_logic_vector;
        bvalids52mi5    : in     vl_logic;
        breadymi52s5    : out    vl_logic;
        lock2wrmi0      : in     vl_logic;
        lock2wrmi1      : in     vl_logic;
        lock2wrmi2      : in     vl_logic;
        lock2wrmi3      : in     vl_logic;
        lock2wrmi4      : in     vl_logic;
        lock2wrmi5      : in     vl_logic;
        lock2rdmi0      : out    vl_logic;
        lock2rdmi1      : out    vl_logic;
        lock2rdmi2      : out    vl_logic;
        lock2rdmi3      : out    vl_logic;
        lock2rdmi4      : out    vl_logic;
        lock2rdmi5      : out    vl_logic;
        unlock2wrmi0    : in     vl_logic;
        unlock2wrmi1    : in     vl_logic;
        unlock2wrmi2    : in     vl_logic;
        unlock2wrmi3    : in     vl_logic;
        unlock2wrmi4    : in     vl_logic;
        unlock2wrmi5    : in     vl_logic;
        unlock2rdmi0    : out    vl_logic;
        unlock2rdmi1    : out    vl_logic;
        unlock2rdmi2    : out    vl_logic;
        unlock2rdmi3    : out    vl_logic;
        unlock2rdmi4    : out    vl_logic;
        unlock2rdmi5    : out    vl_logic;
        arvalidmi02s0   : in     vl_logic;
        arvalidmi12s1   : in     vl_logic;
        arvalidmi22s2   : in     vl_logic;
        arvalidmi32s3   : in     vl_logic;
        arvalidmi42s4   : in     vl_logic;
        arvalidmi52s5   : in     vl_logic;
        lockport2wrmi0  : in     vl_logic_vector;
        lockport2wrmi1  : in     vl_logic_vector;
        lockport2wrmi2  : in     vl_logic_vector;
        lockport2wrmi3  : in     vl_logic_vector;
        lockport2wrmi4  : in     vl_logic_vector;
        lockport2wrmi5  : in     vl_logic_vector;
        readintemptywrmi02rdmi0: out    vl_logic;
        readintemptywrmi12rdmi1: out    vl_logic;
        readintemptywrmi22rdmi2: out    vl_logic;
        readintemptywrmi32rdmi3: out    vl_logic;
        readintemptywrmi42rdmi4: out    vl_logic;
        readintemptywrmi52rdmi5: out    vl_logic;
        datacntemptyrdmi02wrmi0: in     vl_logic;
        datacntemptyrdmi12wrmi1: in     vl_logic;
        datacntemptyrdmi22wrmi2: in     vl_logic;
        datacntemptyrdmi32wrmi3: in     vl_logic;
        datacntemptyrdmi42wrmi4: in     vl_logic;
        datacntemptyrdmi52wrmi5: in     vl_logic;
        ctldatawrite2lock0: out    vl_logic_vector;
        ctldatawrite2lock1: out    vl_logic_vector;
        ctldatawrite2lock2: out    vl_logic_vector;
        ctldatawrite2lock3: out    vl_logic_vector;
        ctldatawrite2lock4: out    vl_logic_vector;
        ctldatawrite2lock5: out    vl_logic_vector;
        aclk            : in     vl_logic;
        aresetn         : in     vl_logic
    );
end writechannel;
