library verilog;
use verilog.vl_types.all;
entity DmReg is
    generic(
        AW              : integer := 29;
        DW              : integer := 31;
        IW              : integer := 1;
        BW              : integer := 3;
        XW              : integer := 10;
        YW              : integer := 10;
        CW              : integer := 9;
        GW              : integer := 10;
        VW              : integer := 10;
        CPlaneMaxBL     : integer := 8;
        GPlaneMaxBL     : integer := 8;
        VPlaneMaxBL     : integer := 8;
        CBLQCD          : integer := 1;
        CBLQD           : integer := 3;
        CBLQW           : integer := 3;
        GBLQCD          : integer := 2;
        GBLQD           : integer := 7;
        GBLQW           : integer := 3;
        VBLQCD          : integer := 1;
        VBLQD           : integer := 3;
        VBLQW           : integer := 3;
        DMCON           : integer := 0;
        DMSTS           : integer := 4;
        CCON            : integer := 16;
        CBLND           : integer := 20;
        CBMOD           : integer := 24;
        CBASE           : integer := 28;
        CADDR           : integer := 32;
        CPALM           : integer := 36;
        CADDR2          : integer := 40;
        CBLINK          : integer := 44;
        BGCOL           : integer := 48;
        GCON            : integer := 64;
        GBLND           : integer := 68;
        GBMOD           : integer := 72;
        GBASE           : integer := 76;
        GADDR           : integer := 80;
        GPALM           : integer := 84;
        GGAMMA00        : integer := 256;
        GGAMMA01        : integer := 260;
        GGAMMA02        : integer := 264;
        GGAMMA03        : integer := 268;
        GGAMMA04        : integer := 272;
        GGAMMA05        : integer := 276;
        GGAMMA06        : integer := 280;
        GGAMMA07        : integer := 284;
        GGAMMA08        : integer := 288;
        GGAMMA09        : integer := 292;
        GGAMMA0A        : integer := 296;
        GGAMMA0B        : integer := 300;
        GGAMMA0C        : integer := 304;
        GGAMMA0D        : integer := 308;
        GGAMMA0E        : integer := 312;
        GGAMMA0F        : integer := 316;
        GGAMMA10        : integer := 320;
        VCON            : integer := 96;
        VBLND           : integer := 100;
        VBMOD           : integer := 104;
        VBASE           : integer := 108;
        VADDR           : integer := 112;
        VADDR2          : integer := 116;
        SCON            : integer := 128;
        SSIZE           : integer := 132;
        SRATIO          : integer := 136;
        VGAMMA00        : integer := 512;
        VGAMMA01        : integer := 516;
        VGAMMA02        : integer := 520;
        VGAMMA03        : integer := 524;
        VGAMMA04        : integer := 528;
        VGAMMA05        : integer := 532;
        VGAMMA06        : integer := 536;
        VGAMMA07        : integer := 540;
        VGAMMA08        : integer := 544;
        VGAMMA09        : integer := 548;
        VGAMMA0A        : integer := 552;
        VGAMMA0B        : integer := 556;
        VGAMMA0C        : integer := 560;
        VGAMMA0D        : integer := 564;
        VGAMMA0E        : integer := 568;
        VGAMMA0F        : integer := 572;
        VGAMMA10        : integer := 576;
        LCDCON          : integer := 224;
        VIDCON          : integer := 228;
        HSYNC0          : integer := 240;
        HSYNC1          : integer := 244;
        VSYNC0          : integer := 248;
        VSYNC1          : integer := 252
    );
    port(
        ACLK            : in     vl_logic;
        ARESETn         : in     vl_logic;
        LCDCLK          : in     vl_logic;
        PCLK            : in     vl_logic;
        PRESETB         : in     vl_logic;
        PSEL            : in     vl_logic;
        PENABLE         : in     vl_logic;
        PADDR           : in     vl_logic_vector(9 downto 2);
        PWRITE          : in     vl_logic;
        PWDATA          : in     vl_logic_vector(31 downto 0);
        PRDATA          : out    vl_logic_vector(31 downto 0);
        CurFIFOUnderRun : in     vl_logic;
        GraFIFOUnderRun : in     vl_logic;
        VidFIFOUnderRun : in     vl_logic;
        MixFIFOUnderRun : in     vl_logic;
        CDMAOverRun     : in     vl_logic;
        GDMAOverRun     : in     vl_logic;
        VDMAOverRun     : in     vl_logic;
        DmInt           : out    vl_logic;
        FrameStart      : in     vl_logic;
        FrameEvenField  : in     vl_logic;
        CDMARAddr       : in     vl_logic_vector;
        GDMARAddr       : in     vl_logic_vector;
        VDMARAddr       : in     vl_logic_vector;
        LCDIPC          : out    vl_logic;
        LCDPDIV         : out    vl_logic_vector(2 downto 0);
        SWReset         : out    vl_logic;
        PrioritySel     : out    vl_logic;
        BPlaneDataIn    : out    vl_logic_vector(23 downto 0);
        CPlaneXPos      : out    vl_logic_vector;
        CPlaneYPos      : out    vl_logic_vector;
        GPlaneXPos      : out    vl_logic_vector;
        GPlaneYPos      : out    vl_logic_vector;
        VPlaneXPos      : out    vl_logic_vector;
        VPlaneYPos      : out    vl_logic_vector;
        CPlaneEn        : out    vl_logic;
        CPlaneChromaKeyEn: out    vl_logic;
        CPlaneChromaKey : out    vl_logic_vector(23 downto 0);
        CPlanePixFormat : out    vl_logic_vector(1 downto 0);
        CPlaneAlphaMode : out    vl_logic_vector(1 downto 0);
        CPlaneAlphaValue: out    vl_logic_vector(7 downto 0);
        CPlaneXRef      : out    vl_logic_vector;
        CPlaneXSize     : out    vl_logic_vector;
        CPlaneYSize     : out    vl_logic_vector;
        CPlaneStartAddr : out    vl_logic_vector;
        CPlaneStartAddr2: out    vl_logic_vector;
        CPlaneAddrSwEn  : out    vl_logic;
        CPlaneAddrSwVal : out    vl_logic_vector(5 downto 0);
        CPlanePalMemWrite: out    vl_logic;
        CPlanePalMemWrAddr: out    vl_logic_vector(7 downto 0);
        CPlanePalMemWrData: out    vl_logic_vector(23 downto 0);
        CPlanePalMemRead: out    vl_logic;
        CPlanePalMemRdData: in     vl_logic_vector(23 downto 0);
        GPlaneEn        : out    vl_logic;
        GPlaneChromaKeyEn: out    vl_logic;
        GPlaneChromaKey : out    vl_logic_vector(23 downto 0);
        GPlanePixFormat : out    vl_logic_vector(2 downto 0);
        GPlaneAlphaMode : out    vl_logic_vector(1 downto 0);
        GPlaneAlphaValue: out    vl_logic_vector(7 downto 0);
        GPlaneXRef      : out    vl_logic_vector;
        GPlaneXSize     : out    vl_logic_vector;
        GPlaneYSize     : out    vl_logic_vector;
        GPlaneStartAddr : out    vl_logic_vector;
        GPlaneGammaEn   : out    vl_logic;
        GPlanePalMemWrite: out    vl_logic;
        GPlanePalMemWrAddr: out    vl_logic_vector(7 downto 0);
        GPlanePalMemWrData: out    vl_logic_vector(23 downto 0);
        GPlanePalMemRead: out    vl_logic;
        GPlanePalMemRdData: in     vl_logic_vector(23 downto 0);
        GPlaneGamma10   : out    vl_logic_vector(23 downto 0);
        GPlaneGamma0F   : out    vl_logic_vector(23 downto 0);
        GPlaneGamma0E   : out    vl_logic_vector(23 downto 0);
        GPlaneGamma0D   : out    vl_logic_vector(23 downto 0);
        GPlaneGamma0C   : out    vl_logic_vector(23 downto 0);
        GPlaneGamma0B   : out    vl_logic_vector(23 downto 0);
        GPlaneGamma0A   : out    vl_logic_vector(23 downto 0);
        GPlaneGamma09   : out    vl_logic_vector(23 downto 0);
        GPlaneGamma08   : out    vl_logic_vector(23 downto 0);
        GPlaneGamma07   : out    vl_logic_vector(23 downto 0);
        GPlaneGamma06   : out    vl_logic_vector(23 downto 0);
        GPlaneGamma05   : out    vl_logic_vector(23 downto 0);
        GPlaneGamma04   : out    vl_logic_vector(23 downto 0);
        GPlaneGamma03   : out    vl_logic_vector(23 downto 0);
        GPlaneGamma02   : out    vl_logic_vector(23 downto 0);
        GPlaneGamma01   : out    vl_logic_vector(23 downto 0);
        GPlaneGamma00   : out    vl_logic_vector(23 downto 0);
        VPlaneEn        : out    vl_logic;
        VPlaneInterlaceEn: out    vl_logic;
        VPlaneN2PUpEn   : out    vl_logic;
        VPlaneChromaKeyEn: out    vl_logic;
        VPlaneChromaKey : out    vl_logic_vector(23 downto 0);
        VPlanePixFormat : out    vl_logic_vector(1 downto 0);
        VPlaneAlphaMode : out    vl_logic_vector(1 downto 0);
        VPlaneAlphaValue: out    vl_logic_vector(7 downto 0);
        VPlaneXRef      : out    vl_logic_vector;
        VPlaneXSize     : out    vl_logic_vector;
        VPlaneYSize     : out    vl_logic_vector;
        VPlaneStartAddr : out    vl_logic_vector;
        VPlaneStartAddr2: out    vl_logic_vector;
        VPlaneGammaEn   : out    vl_logic;
        VPlaneGamma10   : out    vl_logic_vector(23 downto 0);
        VPlaneGamma0F   : out    vl_logic_vector(23 downto 0);
        VPlaneGamma0E   : out    vl_logic_vector(23 downto 0);
        VPlaneGamma0D   : out    vl_logic_vector(23 downto 0);
        VPlaneGamma0C   : out    vl_logic_vector(23 downto 0);
        VPlaneGamma0B   : out    vl_logic_vector(23 downto 0);
        VPlaneGamma0A   : out    vl_logic_vector(23 downto 0);
        VPlaneGamma09   : out    vl_logic_vector(23 downto 0);
        VPlaneGamma08   : out    vl_logic_vector(23 downto 0);
        VPlaneGamma07   : out    vl_logic_vector(23 downto 0);
        VPlaneGamma06   : out    vl_logic_vector(23 downto 0);
        VPlaneGamma05   : out    vl_logic_vector(23 downto 0);
        VPlaneGamma04   : out    vl_logic_vector(23 downto 0);
        VPlaneGamma03   : out    vl_logic_vector(23 downto 0);
        VPlaneGamma02   : out    vl_logic_vector(23 downto 0);
        VPlaneGamma01   : out    vl_logic_vector(23 downto 0);
        VPlaneGamma00   : out    vl_logic_vector(23 downto 0);
        VideoSyncEnPCLK : out    vl_logic;
        LCDBPP          : out    vl_logic_vector(1 downto 0);
        LCDBGR          : out    vl_logic_vector(0 downto 0);
        LCDHFP          : out    vl_logic_vector(7 downto 0);
        LCDHBP          : out    vl_logic_vector(7 downto 0);
        LCDHSW          : out    vl_logic_vector(8 downto 0);
        LCDCPL          : out    vl_logic_vector;
        LCDVSW          : out    vl_logic_vector(5 downto 0);
        LCDVFP          : out    vl_logic_vector(7 downto 0);
        LCDVBP          : out    vl_logic_vector(7 downto 0);
        LCDLPS          : out    vl_logic_vector;
        LCDIVS          : out    vl_logic;
        LCDIHS          : out    vl_logic;
        LCDIEO          : out    vl_logic;
        LCDPwrEn        : out    vl_logic;
        LCDEn           : out    vl_logic
    );
end DmReg;
