 //+incdir+../Rtl/UART_PL011
 
 //`include "../Rtl/UART_PL011"
 `include "../Rtl/ARM7TDMIr3.v"
 `include "../Rtl/FileReadCore_DTS.v"
 `include "../Rtl/FileReader_DTS.v"
 `include "../Rtl/Reset_Controller.v"
 `include "../Rtl/New/Decoder.v"
 `include "../Rtl/New/Top_DTSDI002.v"
// `include "../Rtl/MuxP2B_DTS.v"
 `include "../Rtl/New/APBif.v"
 `include "../Rtl/New/APB_PowerManager.v"
 `include "../Rtl/AD_Conv10.v"
 `include "../Rtl/APB_ADC_Ctrl.v"
 `include "../Rtl/AD_Conv10.v"
// `include "../Rtl/APB_Timers_EAX0.v"
// `include "../Rtl/APB_Timers_EAX1.v"
// `include "../Rtl/APB_Timers_EAX2.v"
// `include "../Rtl/APB_Timers_EAX3.v"
// `include "../Rtl/APB_Timers_EAX4.v"
// `include "../Rtl/APB_Timers_EAX5.v"
// `include "../Rtl/APB_Timers_EAX6.v"
// `include "../Rtl/APB_Timers_EAX7.v"
// 
// `include "../Rtl/APB_Timers_PWM0_0.v"
// `include "../Rtl/APB_Timers_PWM0_1.v"
// `include "../Rtl/APB_Timers_PWM0_2.v"
// `include "../Rtl/APB_Timers_PWM0_3.v"
// `include "../Rtl/APB_Timers_PWM0_4.v"
// `include "../Rtl/APB_Timers_PWM0_5.v"
// `include "../Rtl/APB_Timers_PWM0_6.v"
// `include "../Rtl/APB_Timers_PWM0_7.v"
// 
// `include "../Rtl/APB_Timers_PWM1_0.v"
// `include "../Rtl/APB_Timers_PWM1_1.v"
// `include "../Rtl/APB_Timers_PWM1_2.v"
// `include "../Rtl/APB_Timers_PWM1_3.v"
// `include "../Rtl/APB_Timers_PWM1_4.v"
// `include "../Rtl/APB_Timers_PWM1_5.v"
// `include "../Rtl/APB_Timers_PWM1_6.v"
// `include "../Rtl/APB_Timers_PWM1_7.v"
// 
// `include "../Rtl/APB_Timers_PWM2_0.v"
// `include "../Rtl/APB_Timers_PWM2_1.v"
// `include "../Rtl/APB_Timers_PWM2_2.v"
// `include "../Rtl/APB_Timers_PWM2_3.v"
// `include "../Rtl/APB_Timers_PWM2_4.v"
// `include "../Rtl/APB_Timers_PWM2_5.v"
// `include "../Rtl/APB_Timers_PWM2_6.v"
// `include "../Rtl/APB_Timers_PWM2_7.v"
// 
// `include "../Rtl/APB_Timers_PWM3_0.v"
// `include "../Rtl/APB_Timers_PWM3_1.v"
// `include "../Rtl/APB_Timers_PWM3_2.v"
// `include "../Rtl/APB_Timers_PWM3_3.v"
// `include "../Rtl/APB_Timers_PWM3_4.v"
// `include "../Rtl/APB_Timers_PWM3_5.v"
// `include "../Rtl/APB_Timers_PWM3_6.v"
// `include "../Rtl/APB_Timers_PWM3_7.v"
 
 `include "../Rtl/New/APB_WDT.v"
 `include "../Rtl/APB_Gpio.v"
 `include "../Rtl/IO_PAD.v"
// `include "../Rtl/A7TWrapCtrl.v"
// `include "../Rtl/A7TWrapTest.v"
// `include "../Rtl/A7WrapMaster.v"
// `include "../Rtl/A7WrapSM.v"
// `include "../Rtl/A7TWrap.v"
// `include "../Rtl/A7TDMI.v"
// `include "../Rtl/Ahb2Lite.v"
// `include "../Rtl/EASY_ARM7.v"
// `include "../Rtl/EgAPBSlave.v"

 
// `include "../Rtl/EgMasterCore.v"
// `include "../Rtl/EgMaster.v"
// `include "../Rtl/ArbSchm3.v"
 `include "../Rtl/Arbiter3.v"
 `include "../Rtl/MuxS2M.v"
 `include "../Rtl/MuxM2S.v"
 `include "../Rtl/DefaultSlave.v"

 `include "../Rtl/MuxP2B.v"
 
 `include "../Rtl/ExtRAM.v"
 `include "../Rtl/ExtROM.v"
 `include "../Rtl/Memory.v"
 `include "../Rtl/IntMem.v"
// `include "../Rtl/ICAhbifReg.v"
// `include "../Rtl/ICPriority.v"
// `include "../Rtl/ICSynctoHCLK.v"
// `include "../Rtl/Interrupt.v"
// `include "../Rtl/RemapPause.v"

// `include "../Rtl/RetrySlave.v"
// `include "../Rtl/SmiCore.v"
// `include "../Rtl/SmiDBI.v"
// `include "../Rtl/TIC.v"
// `include "../Rtl/SMI.v"

// `include "../Rtl/TimersFrc.v"
// `include "../Rtl/Timers.v"

// `include "../Rtl/WdogFrc.v"
// `include "../Rtl/Watchdog.v"
// `include "../Rtl/GpioApbif.v"
// `include "../Rtl/GpioAfm.v"
// `include "../Rtl/GpioInt.v"
// `include "../Rtl/GpioRevAnd.v"
// `include "../Rtl/Gpio.v"

// `include "../Rtl/ClockInv.v"
// `include "../Rtl/ClockNand.v"
// `include "../Rtl/ClockOr.v"
// `include "../Rtl/LAT.v"
// `include "../Rtl/LATR.v"
// `include "../Rtl/LATS.v"
// `include "../Rtl/Lite2AHB.v"
// `include "../Rtl/RevAnd.v"
// `include "../Rtl/Tube.v"
 
 `include "TBFM_DTSDI002.v"
 //`include "TBROM_DTSDI002.v" 
