library verilog;
use verilog.vl_types.all;
entity TbSDR is
    generic(
        CKP1            : real    := 3.750000;
        SDLY            : integer := 2;
        DDLY            : integer := 3;
        DLY             : integer := 0;
        CDLY            : real    := 0.500000;
        AW              : integer := 25;
        DW              : integer := 31;
        BW              : integer := 3;
        BL              : integer := 3;
        ID              : integer := 3;
        WQCD            : integer := 5;
        WQD             : integer := 63;
        RQCD            : integer := 5;
        RQD             : integer := 63;
        WBLQCD          : integer := 1;
        WBLQD           : integer := 3;
        RBLQCD          : integer := 1;
        RBLQD           : integer := 3;
        MDW             : integer := 31;
        DMW             : integer := 3;
        BAW             : integer := 1;
        RAW             : integer := 12;
        CAW             : integer := 10;
        TL              : integer := 4;
        RWW             : integer := 1;
        CD              : integer := 3;
        erc_powerup     : integer := 1;
        erc_epc         : integer := 2;
        erc_ar          : integer := 4;
        erc_mrs         : integer := 8;
        erc_idle        : integer := 16;
        erc_normal      : integer := 32;
        bc_null         : integer := 0;
        bc_mcas         : integer := 1;
        bc_mras         : integer := 2;
        bc_pc           : integer := 4;
        bc_sras         : integer := 8;
        bc_scas         : integer := 16;
        bc_epc          : integer := 32;
        ebc_null        : integer := 0;
        ebc_mcas        : integer := 1;
        ebc_mras        : integer := 2;
        ebc_pc          : integer := 4;
        ebc_sras        : integer := 8;
        ebc_scas        : integer := 16;
        ebc_epc         : integer := 32;
        ebc_bstop       : integer := 64
    );
end TbSDR;
