library verilog;
use verilog.vl_types.all;
entity pci_chkpar64 is
    generic(
        oe_active       : integer := 0;
        vendor_id       : integer := 43981;
        device_id       : integer := 25702;
        class_id        : integer := 425984;
        rev_id          : integer := 16;
        bar0_present    : integer := 1;
        bar0_dwidth     : integer := 22;
        bar1_present    : integer := 1;
        bar1_dwidth     : integer := 8;
        bar2_present    : integer := 0;
        bar2_map        : integer := 0;
        bar2_dwidth     : integer := 28;
        bar3_present    : integer := 0;
        bar3_map        : integer := 0;
        bar3_dwidth     : integer := 28;
        bar4_present    : integer := 0;
        bar4_map        : integer := 0;
        bar4_dwidth     : integer := 28;
        bar5_present    : integer := 0;
        bar5_map        : integer := 0;
        bar5_dwidth     : integer := 28;
        ebar_present    : integer := 0;
        ebar_map        : integer := 0;
        ebar_dwidth     : integer := 17;
        subvendor_id    : integer := 4334;
        subdevice_id    : integer := 256;
        cis_ptr         : integer := 0;
        cap_ptr         : integer := 0;
        max_lat         : integer := 32;
        min_gnt         : integer := 4;
        int_pin         : integer := 1;
        int_line        : integer := 0;
        command_init    : integer := 0;
        status_init     : integer := 544;
        clsize_init     : integer := 0;
        lattimer_init   : integer := 0;
        intline_init    : integer := 0;
        iack_code       : integer := 0;
        scyc_code       : integer := 1;
        iord_code       : integer := 2;
        iowr_code       : integer := 3;
        res4_code       : integer := 4;
        res5_code       : integer := 5;
        mrd_code        : integer := 6;
        mwr_code        : integer := 7;
        res8_code       : integer := 8;
        res9_code       : integer := 9;
        cfgrd_code      : integer := 10;
        cfgwr_code      : integer := 11;
        mrm_code        : integer := 12;
        dual_code       : integer := 13;
        mrl_code        : integer := 14;
        mwi_code        : integer := 15
    );
    port(
        reset           : in     vl_logic;
        clk             : in     vl_logic;
        ad              : in     vl_logic_vector(63 downto 0);
        ben             : in     vl_logic_vector(7 downto 0);
        first_cyc       : in     vl_logic;
        irdynid         : in     vl_logic;
        trdynid         : in     vl_logic;
        pari            : in     vl_logic;
        par64i          : in     vl_logic;
        perrni          : in     vl_logic;
        ack64nid        : in     vl_logic;
        acc_wr          : in     vl_logic;
        perr_en         : in     vl_logic;
        serr_en         : in     vl_logic;
        target_act      : in     vl_logic;
        master_read     : in     vl_logic;
        master_act      : in     vl_logic;
        perrno_nxt      : out    vl_logic;
        serrno_nxt      : out    vl_logic;
        ot_perr_nxt     : out    vl_logic;
        set_mdperr      : out    vl_logic;
        sig_serr        : out    vl_logic;
        det_perr        : out    vl_logic
    );
end pci_chkpar64;
