library verilog;
use verilog.vl_types.all;
entity MuxP2B_DTS is
    generic(
        Vector_Bit      : integer := 49
    );
    port(
        PSELS0          : in     vl_logic;
        PSELS1          : in     vl_logic;
        PSELS2          : in     vl_logic;
        PSELS3          : in     vl_logic;
        PSELS4X0        : in     vl_logic;
        PSELS4X1        : in     vl_logic;
        PSELS4X2        : in     vl_logic;
        PSELS4X3        : in     vl_logic;
        PSELS4X4        : in     vl_logic;
        PSELS4X5        : in     vl_logic;
        PSELS4X6        : in     vl_logic;
        PSELS4X7        : in     vl_logic;
        PSELS5X0        : in     vl_logic;
        PSELS5X1        : in     vl_logic;
        PSELS5X2        : in     vl_logic;
        PSELS5X3        : in     vl_logic;
        PSELS5X4        : in     vl_logic;
        PSELS5X5        : in     vl_logic;
        PSELS5X6        : in     vl_logic;
        PSELS5X7        : in     vl_logic;
        PSELS6X0        : in     vl_logic;
        PSELS6X1        : in     vl_logic;
        PSELS6X2        : in     vl_logic;
        PSELS6X3        : in     vl_logic;
        PSELS6X4        : in     vl_logic;
        PSELS6X5        : in     vl_logic;
        PSELS6X6        : in     vl_logic;
        PSELS6X7        : in     vl_logic;
        PSELS7X0        : in     vl_logic;
        PSELS7X1        : in     vl_logic;
        PSELS7X2        : in     vl_logic;
        PSELS7X3        : in     vl_logic;
        PSELS7X4        : in     vl_logic;
        PSELS7X5        : in     vl_logic;
        PSELS7X6        : in     vl_logic;
        PSELS7X7        : in     vl_logic;
        PSELS8X0        : in     vl_logic;
        PSELS8X1        : in     vl_logic;
        PSELS8X2        : in     vl_logic;
        PSELS8X3        : in     vl_logic;
        PSELS8X4        : in     vl_logic;
        PSELS8X5        : in     vl_logic;
        PSELS8X6        : in     vl_logic;
        PSELS8X7        : in     vl_logic;
        PSELS9          : in     vl_logic;
        PSELS10         : in     vl_logic;
        PSELS11         : in     vl_logic;
        PSELS12         : in     vl_logic;
        PSELS13         : in     vl_logic;
        PRDATAS0        : in     vl_logic_vector(31 downto 0);
        PRDATAS1        : in     vl_logic_vector(31 downto 0);
        PRDATAS2        : in     vl_logic_vector(31 downto 0);
        PRDATAS3        : in     vl_logic_vector(31 downto 0);
        PRDATAS4X0      : in     vl_logic_vector(31 downto 0);
        PRDATAS4X1      : in     vl_logic_vector(31 downto 0);
        PRDATAS4X2      : in     vl_logic_vector(31 downto 0);
        PRDATAS4X3      : in     vl_logic_vector(31 downto 0);
        PRDATAS4X4      : in     vl_logic_vector(31 downto 0);
        PRDATAS4X5      : in     vl_logic_vector(31 downto 0);
        PRDATAS4X6      : in     vl_logic_vector(31 downto 0);
        PRDATAS4X7      : in     vl_logic_vector(31 downto 0);
        PRDATAS5X0      : in     vl_logic_vector(31 downto 0);
        PRDATAS5X1      : in     vl_logic_vector(31 downto 0);
        PRDATAS5X2      : in     vl_logic_vector(31 downto 0);
        PRDATAS5X3      : in     vl_logic_vector(31 downto 0);
        PRDATAS5X4      : in     vl_logic_vector(31 downto 0);
        PRDATAS5X5      : in     vl_logic_vector(31 downto 0);
        PRDATAS5X6      : in     vl_logic_vector(31 downto 0);
        PRDATAS5X7      : in     vl_logic_vector(31 downto 0);
        PRDATAS6X0      : in     vl_logic_vector(31 downto 0);
        PRDATAS6X1      : in     vl_logic_vector(31 downto 0);
        PRDATAS6X2      : in     vl_logic_vector(31 downto 0);
        PRDATAS6X3      : in     vl_logic_vector(31 downto 0);
        PRDATAS6X4      : in     vl_logic_vector(31 downto 0);
        PRDATAS6X5      : in     vl_logic_vector(31 downto 0);
        PRDATAS6X6      : in     vl_logic_vector(31 downto 0);
        PRDATAS6X7      : in     vl_logic_vector(31 downto 0);
        PRDATAS7X0      : in     vl_logic_vector(31 downto 0);
        PRDATAS7X1      : in     vl_logic_vector(31 downto 0);
        PRDATAS7X2      : in     vl_logic_vector(31 downto 0);
        PRDATAS7X3      : in     vl_logic_vector(31 downto 0);
        PRDATAS7X4      : in     vl_logic_vector(31 downto 0);
        PRDATAS7X5      : in     vl_logic_vector(31 downto 0);
        PRDATAS7X6      : in     vl_logic_vector(31 downto 0);
        PRDATAS7X7      : in     vl_logic_vector(31 downto 0);
        PRDATAS8X0      : in     vl_logic_vector(31 downto 0);
        PRDATAS8X1      : in     vl_logic_vector(31 downto 0);
        PRDATAS8X2      : in     vl_logic_vector(31 downto 0);
        PRDATAS8X3      : in     vl_logic_vector(31 downto 0);
        PRDATAS8X4      : in     vl_logic_vector(31 downto 0);
        PRDATAS8X5      : in     vl_logic_vector(31 downto 0);
        PRDATAS8X6      : in     vl_logic_vector(31 downto 0);
        PRDATAS8X7      : in     vl_logic_vector(31 downto 0);
        PRDATAS9        : in     vl_logic_vector(31 downto 0);
        PRDATAS10       : in     vl_logic_vector(31 downto 0);
        PRDATAS11       : in     vl_logic_vector(31 downto 0);
        PRDATAS12       : in     vl_logic_vector(31 downto 0);
        PRDATAS13       : in     vl_logic_vector(31 downto 0);
        PRDATA          : out    vl_logic_vector(31 downto 0)
    );
end MuxP2B_DTS;
