library verilog;
use verilog.vl_types.all;
entity pci_m64core is
    generic(
        oe_active       : integer := 0;
        vendor_id       : integer := 43981;
        device_id       : integer := 25702;
        class_id        : integer := 425984;
        rev_id          : integer := 16;
        bar0_present    : integer := 1;
        bar0_dwidth     : integer := 22;
        bar1_present    : integer := 1;
        bar1_dwidth     : integer := 8;
        bar2_present    : integer := 0;
        bar2_map        : integer := 0;
        bar2_dwidth     : integer := 28;
        bar3_present    : integer := 0;
        bar3_map        : integer := 0;
        bar3_dwidth     : integer := 28;
        bar4_present    : integer := 0;
        bar4_map        : integer := 0;
        bar4_dwidth     : integer := 28;
        bar5_present    : integer := 0;
        bar5_map        : integer := 0;
        bar5_dwidth     : integer := 28;
        ebar_present    : integer := 0;
        ebar_map        : integer := 0;
        ebar_dwidth     : integer := 17;
        subvendor_id    : integer := 4334;
        subdevice_id    : integer := 256;
        cis_ptr         : integer := 0;
        cap_ptr         : integer := 0;
        max_lat         : integer := 32;
        min_gnt         : integer := 4;
        int_pin         : integer := 1;
        int_line        : integer := 0;
        command_init    : integer := 0;
        status_init     : integer := 544;
        clsize_init     : integer := 0;
        lattimer_init   : integer := 0;
        intline_init    : integer := 0;
        iack_code       : integer := 0;
        scyc_code       : integer := 1;
        iord_code       : integer := 2;
        iowr_code       : integer := 3;
        res4_code       : integer := 4;
        res5_code       : integer := 5;
        mrd_code        : integer := 6;
        mwr_code        : integer := 7;
        res8_code       : integer := 8;
        res9_code       : integer := 9;
        cfgrd_code      : integer := 10;
        cfgwr_code      : integer := 11;
        mrm_code        : integer := 12;
        dual_code       : integer := 13;
        mrl_code        : integer := 14;
        mwi_code        : integer := 15
    );
    port(
        clkpci          : in     vl_logic;
        rstpcin         : in     vl_logic;
        adi             : in     vl_logic_vector(63 downto 0);
        cbei            : in     vl_logic_vector(7 downto 0);
        pari            : in     vl_logic;
        par64i          : in     vl_logic;
        idseli          : in     vl_logic;
        gntni           : in     vl_logic;
        frameni         : in     vl_logic;
        req64ni         : in     vl_logic;
        irdyni          : in     vl_logic;
        devselni        : in     vl_logic;
        ack64ni         : in     vl_logic;
        trdyni          : in     vl_logic;
        stopni          : in     vl_logic;
        perrni          : in     vl_logic;
        reqno           : out    vl_logic;
        frameno         : out    vl_logic;
        req64no         : out    vl_logic;
        irdyno          : out    vl_logic;
        devselno        : out    vl_logic;
        ack64no         : out    vl_logic;
        trdyno          : out    vl_logic;
        stopno          : out    vl_logic;
        ot_frame        : out    vl_logic;
        ot_req64        : out    vl_logic;
        ot_irdy         : out    vl_logic;
        ot_devsel       : out    vl_logic;
        ot_ack64        : out    vl_logic;
        ot_trdy         : out    vl_logic;
        ot_stop         : out    vl_logic;
        intano          : out    vl_logic;
        paro            : out    vl_logic;
        par64o          : out    vl_logic;
        perrno          : out    vl_logic;
        serrno          : out    vl_logic;
        ot_perr         : out    vl_logic;
        ot_par          : out    vl_logic;
        ot_par64        : out    vl_logic;
        ado             : out    vl_logic_vector(63 downto 0);
        ot_ad           : out    vl_logic_vector(63 downto 0);
        cbeo            : out    vl_logic_vector(7 downto 0);
        ot_cbe          : out    vl_logic_vector(7 downto 0);
        app_ado         : in     vl_logic_vector(63 downto 0);
        app_intn        : in     vl_logic;
        t_drdy          : in     vl_logic_vector(6 downto 0);
        t_abort         : in     vl_logic;
        t_term          : in     vl_logic;
        m_cbe           : in     vl_logic_vector(7 downto 0);
        m_areq          : in     vl_logic;
        m_areq64        : in     vl_logic;
        m_crw           : in     vl_logic;
        m_drdy          : in     vl_logic;
        m_lastd         : in     vl_logic;
        app_rst         : out    vl_logic;
        app_adr         : out    vl_logic_vector(31 downto 0);
        app_adi         : out    vl_logic_vector(63 downto 0);
        t_barhit        : out    vl_logic_vector(5 downto 0);
        t_ebarhit       : out    vl_logic;
        t_ben           : out    vl_logic_vector(7 downto 0);
        t_cmd           : out    vl_logic_vector(3 downto 0);
        t_rd            : out    vl_logic;
        t_wr            : out    vl_logic;
        t_we            : out    vl_logic;
        t_nextd         : out    vl_logic;
        t_adr_valid     : out    vl_logic;
        t_width64       : out    vl_logic;
        m_aack          : out    vl_logic;
        m_aack64        : out    vl_logic;
        m_otcmd         : out    vl_logic;
        m_otdata        : out    vl_logic;
        m_nextd         : out    vl_logic;
        m_wrejd         : out    vl_logic;
        m_mabort        : out    vl_logic;
        m_tabort        : out    vl_logic;
        m_tretry        : out    vl_logic;
        m_tdisc         : out    vl_logic;
        pcr_cmd         : out    vl_logic_vector(15 downto 0);
        pcr_stat        : out    vl_logic_vector(15 downto 0);
        pcr_cachesize   : out    vl_logic_vector(7 downto 0);
        pci_framenid    : out    vl_logic;
        pci_req64nid    : out    vl_logic;
        pci_irdynid     : out    vl_logic;
        pci_devselnid   : out    vl_logic;
        pci_ack64nid    : out    vl_logic;
        pci_trdynid     : out    vl_logic;
        pci_stopnid     : out    vl_logic
    );
end pci_m64core;
