@TM:1140828262
@N: FX164 :"":0:0:0:-1|The option to pack flops in the IOB has not been specified 
@N: MT195 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT197 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@N: MT204 :"":0:0:0:-1|Autoconstrain Mode is ON
@TM:1140834260
@N:  :"d:\data\timer_pwm\rtl\timer_pwm.v":22:7:22:15|Synthesizing module timer_pwm
@TM:1141977142
@W: CL159 :"d:\data\timer_pwm\rtl\timer_pwm.v":69:16:69:25|M
@W: CL159 :"d:\data\timer_pwm\rtl\timer_pwm.v":70:16:70:25|M
@W:  :"d:\data\timer_pwm\rtl\timer_pwm.v":71:16:71:26|M
@W: CL157 :"d:\data\timer_pwm\rtl\timer_pwm.v":71:16:71:26|M
@W: MO111 :"d:\data\timer_pwm\rtl\timer_pwm.v":71:16:71:26|M
@N:  :"d:\data\timer_pwm\rtl\timer_pwm.v":167:13:167:25|M
@N:  :"d:\data\timer_pwm\rtl\timer_pwm.v":172:13:172:24|M
@N:  :"d:\data\timer_pwm\rtl\timer_pwm.v":292:13:292:25|M
@N:  :"d:\data\timer_pwm\rtl\timer_pwm.v":302:14:302:25|M
@N: FX235 :"d:\data\timer_pwm\rtl\timer_pwm.v":320:0:320:5|M
@N: FX235 :"d:\data\timer_pwm\rtl\timer_pwm.v":356:2:356:7|M
@N:  :"d:\data\timer_pwm\rtl\timer_pwm.v":493:0:493:5|M
@N: MF179 :"d:\data\timer_pwm\rtl\timer_pwm.v":504:11:504:29|M
@N:  :"d:\data\timer_pwm\rtl\timer_pwm.v":667:0:667:5|M
@N: FX235 :"d:\data\timer_pwm\rtl\timer_pwm.v":667:0:667:5|M
@N: MF179 :"d:\data\timer_pwm\rtl\timer_pwm.v":707:17:707:41|M
@N: MF179 :"d:\data\timer_pwm\rtl\timer_pwm.v":713:17:713:34|M
