library verilog;
use verilog.vl_types.all;
entity target64_model is
    generic(
        enable64        : integer := 1;
        dec_speed       : integer := 1;
        vect_filename   : string  := "VECT_FILENAME";
        log_filename    : string  := "LOG_FILENAME";
        size            : integer := 4096;
        addr_width      : integer := 32;
        data_width      : integer := 64;
        cbe_width       : integer := 8;
        passed          : integer := 0;
        failed          : integer := 1;
        n_a             : integer := 2;
        vid             : integer := 0;
        vid_be          : integer := 12;
        did             : integer := 0;
        did_be          : integer := 3;
        cmdr            : integer := 4;
        cmdr_be         : integer := 12;
        statr           : integer := 4;
        statr_be        : integer := 3;
        lattimer        : integer := 12;
        bar0            : integer := 16;
        bar1            : integer := 20;
        bar2            : integer := 24;
        bar3            : integer := 28;
        bar4            : integer := 32;
        bar5            : integer := 36;
        cispr           : integer := 40;
        cap             : integer := 44;
        cap_be          : integer := 14;
        ebar            : integer := 48;
        subvid          : integer := 52;
        subvid_be       : integer := 12;
        subdid          : integer := 52;
        subdid_be       : integer := 3;
        maxlat          : integer := 60;
        maxlat_be       : integer := 7;
        mingnt          : integer := 60;
        mingnt_be       : integer := 11;
        intpin          : integer := 60;
        intpin_be       : integer := 13;
        intline         : integer := 60;
        intline_be      : integer := 14;
        iack_code       : integer := 0;
        scyc_code       : integer := 1;
        iord_code       : integer := 2;
        iowr_code       : integer := 3;
        res4_code       : integer := 4;
        res5_code       : integer := 5;
        mrd_code        : integer := 6;
        mwr_code        : integer := 7;
        res8_code       : integer := 8;
        res9_code       : integer := 9;
        cfgrd_code      : integer := 10;
        cfgwr_code      : integer := 11;
        mrm_code        : integer := 12;
        dual_code       : integer := 13;
        mrl_code        : integer := 14;
        mwi_code        : integer := 15;
        retry_clk_limit : integer := 334;
        bus_log_filemane: string  := "bus_monitor.log";
        tp1_err_msg1    : string  := " ERROR: TP1 rule violation - ";
        tp1_err_msg2    : string  := " not driven high before being tri-stated";
        tp2_err_msg     : string  := " ERROR: TP2 rule violation - PERR# reported without it has claimed the cycle and completed a data phase";
        tp5_err_msg     : string  := " ERROR: TP5 rule violation - TRDY# was deasserted without completed a data phase";
        tp6_err_msg     : string  := " ERROR: TP6 rule violation - DEVSEL# was deasserted while TRDY# asserted without completed a data phase";
        tp7_err_msg     : string  := " ERROR: TP7 rule violation - STOP# was changed while TRDY# asserted without completed a data phase";
        tp8_err_msg     : string  := " ERROR: TP8 rule violation - STOP# was changed without completed a data phase";
        tp9_err_msg     : string  := " ERROR: TP9 rule violation - TRDY# was changed while STOP# asserted without completed a data phase";
        tp10_err_msg    : string  := " ERROR: TP10 rule violation - DEVSEL# was changed while STOP# asserted without completed a data phase";
        tp11_err_msg    : string  := " ERROR: TP11 rule violation - data changed before both IRDY# and TRDY# are asserted";
        tp12_err_msg    : string  := " ERROR: TP12 rule violation - data not valid when TRDY# asserted on a read cycle";
        tp17a_err_msg   : string  := " ERROR: TP17 rule violation - AD lines are not driven to stable values during address phase";
        tp17d_err_msg   : string  := " ERROR: TP17 rule violation - AD lines are not driven to stable values during data phase";
        tp19_err_msg    : string  := " ERROR: TP19 rule violation - TRDY# asserted during turnaround cycle on a read";
        tp20_err_msg1   : string  := " ERROR: TP20 rule violation - ";
        tp20_err_msg2   : string  := " not driven high after the last data phase";
        tp22_err_msg    : string  := " ERROR: TP22 rule violation - STOP# not deasserted the cycle immediately following FRAME# being dessaerted";
        tp23_err_msg    : string  := " ERROR: TP23 rule violation - STOP# deasserted before FRAME# is negated";
        tp24_err_msg    : string  := " ERROR: TP24 rule violation - TRDY# not deasserted before signaling target-abort";
        tp25_err_msg    : string  := " ERROR: TP25 rule violation - STOP# deasserted and the transaction still continues ";
        tp26_err_msg    : string  := " ERROR: TP26 rule violation - initial data phase not completed within 16 clocks";
        tp28_err_msg    : string  := " ERROR: TP28 rule violation - DEVSEL# not asserted before any other response";
        tp29_err_msg    : string  := " ERROR: TP29 rule violation - DEVSEL# deasserted before the last data phase";
        tp30_err_msg    : string  := " ERROR: TP30 rule violation - target responded to special cycles";
        tp31_err_msg    : string  := " ERROR: TP31 rule violation - PAR not driven within one clock of AD being driven";
        tp32_err_msg    : string  := " ERROR: TP32 rule violation - parity error";
        tp34_err_msg    : string  := " ERROR: TP32 rule violation - write transaction not finished after 334 clock cycles after retry";
        fast            : integer := 0;
        medium          : integer := 1;
        slow            : integer := 2;
        sub             : integer := 3;
        t_continue      : integer := 0;
        t_abort         : integer := 1;
        t_retry         : integer := 2;
        t_disc_w_data   : integer := 3;
        t_disc_wo_data  : integer := 4;
        master_end      : integer := 5;
        cto_dly         : integer := 6;
        targetresponselimit: integer := 5;
        targetinitiallatency: integer := 16;
        targetsubseqlatency: integer := 8;
        master_end_tmaster_terminate: integer := 0;
        master_abort    : integer := 1;
        t_abort_tmaster_terminate: integer := 2;
        t_retry_tmaster_terminate: integer := 3;
        t_disc_w_data_tmaster_terminate: integer := 4;
        t_disc_wo_data_tmaster_terminate: integer := 5;
        read            : integer := 0;
        write           : integer := 1;
        bar2_map        : integer := 0;
        bar3_map        : integer := 0;
        bar4_map        : integer := 0;
        bar5_map        : integer := 0;
        ebar_map        : integer := 0;
        bar1_present    : integer := 1;
        bar2_present    : integer := 0;
        bar3_present    : integer := 0;
        bar4_present    : integer := 0;
        bar5_present    : integer := 0;
        ebar_present    : integer := 0;
        device_no       : integer := 0;
        lat_timer       : integer := 32;
        cache_size      : integer := 16;
        int_line        : integer := 10;
        arbit_master_no : integer := 2;
        arbit_target_no : integer := 2;
        arbit_latency_limit: integer := 0;
        uut_dma_txcnt   : integer := 32;
        uut_dma_ahbaddr : integer := 32;
        void_space      : integer := 268435456;
        target1_enable64: integer := 1;
        target1_size    : integer := 4096;
        target1_vector_filename: string  := "t64_t1.vec";
        target1_log_filename: string  := "t64_t1.log";
        target2_enable64: integer := 1;
        target2_size    : integer := 4096;
        target2_vector_filename: string  := "t64_t2.vec";
        target2_log_filename: string  := "t64_t2.log";
        target_vec_lines: integer := 11;
        ram_vec_lines   : integer := 16;
        clk_period      : integer := 15;
        cto_delay       : integer := 6;
        trdy_dly        : integer := 1;
        tm_idle         : integer := 0;
        tm_cmd          : integer := 1;
        tm_data         : integer := 2;
        tm_turnar       : integer := 3
    );
    port(
        rstn            : in     vl_logic;
        clk             : in     vl_logic;
        adio            : inout  vl_logic_vector(63 downto 0);
        cbe             : in     vl_logic_vector(7 downto 0);
        par             : inout  vl_logic;
        par64           : inout  vl_logic;
        idsel           : in     vl_logic;
        framen          : in     vl_logic;
        req64n          : in     vl_logic;
        irdyn           : in     vl_logic;
        trdyn           : out    vl_logic;
        devseln         : out    vl_logic;
        ack64n          : out    vl_logic;
        stopn           : out    vl_logic;
        perrn           : inout  vl_logic;
        serrn           : inout  vl_logic;
        params_enabled  : in     vl_logic;
        end_sim         : in     vl_logic
    );
end target64_model;
