library verilog;
use verilog.vl_types.all;
entity DDRSpi is
    generic(
        AW              : integer := 24;
        DW              : integer := 31;
        BW              : integer := 3;
        BL              : integer := 1;
        ID              : integer := 4;
        BBL             : integer := 3;
        WQCD            : integer := 4;
        WQD             : integer := 31;
        RQCD            : integer := 5;
        RQD             : integer := 63;
        WBLQCD          : integer := 2;
        WBLQD           : integer := 7;
        BBLQCD          : integer := 1;
        BBLQD           : integer := 3;
        RBLQCD          : integer := 3;
        RBLQD           : integer := 15;
        MDW             : integer := 15;
        DMW             : integer := 1;
        BAW             : integer := 1;
        RAW             : integer := 12;
        CAW             : integer := 10;
        RWW             : integer := 1;
        CD              : integer := 4;
        erc_powerup     : integer := 1;
        erc_epc         : integer := 2;
        erc_ar          : integer := 4;
        erc_mrs         : integer := 8;
        erc_idle        : integer := 16;
        erc_normal      : integer := 32;
        bc_null         : integer := 0;
        bc_mcas         : integer := 1;
        bc_mras         : integer := 2;
        bc_pc           : integer := 4;
        bc_sras         : integer := 8;
        bc_scas         : integer := 16;
        bc_epc          : integer := 32;
        ebc_null        : integer := 0;
        ebc_mcas        : integer := 1;
        ebc_mras        : integer := 2;
        ebc_pc          : integer := 4;
        ebc_sras        : integer := 8;
        ebc_scas        : integer := 16;
        ebc_epc         : integer := 32;
        ebc_bstop       : integer := 64
    );
    port(
        ACLK            : in     vl_logic;
        ARESETn         : in     vl_logic;
        AWID_M          : in     vl_logic_vector;
        AWADDR_M        : in     vl_logic_vector(31 downto 0);
        AWLEN_M         : in     vl_logic_vector(3 downto 0);
        AWBURST_M       : in     vl_logic_vector(1 downto 0);
        AWVALID_M       : in     vl_logic;
        AWREADY_M       : out    vl_logic;
        WID_M           : in     vl_logic_vector;
        WDATA_M         : in     vl_logic_vector(31 downto 0);
        WSTRB_M         : in     vl_logic_vector(3 downto 0);
        WLAST_M         : in     vl_logic;
        WVALID_M        : in     vl_logic;
        WREADY_M        : out    vl_logic;
        BID_M           : out    vl_logic_vector;
        BRESP_M         : out    vl_logic_vector(1 downto 0);
        BVALID_M        : out    vl_logic;
        BREADY_M        : in     vl_logic;
        ARID_M          : in     vl_logic_vector;
        ARADDR_M        : in     vl_logic_vector(31 downto 0);
        ARLEN_M         : in     vl_logic_vector(3 downto 0);
        ARBURST_M       : in     vl_logic_vector(1 downto 0);
        ARVALID_M       : in     vl_logic;
        ARREADY_M       : out    vl_logic;
        RID_M           : out    vl_logic_vector;
        RDATA_M         : out    vl_logic_vector(31 downto 0);
        RRESP_M         : out    vl_logic_vector(1 downto 0);
        RLAST_M         : out    vl_logic;
        RVALID_M        : out    vl_logic;
        RREADY_M        : in     vl_logic;
        AWID_S          : out    vl_logic_vector;
        AWADDR_S        : out    vl_logic_vector(31 downto 0);
        AWLEN_S         : out    vl_logic_vector(3 downto 0);
        AWBURST_S       : out    vl_logic_vector(1 downto 0);
        AWVALID_S       : out    vl_logic;
        AWREADY_S       : in     vl_logic;
        WID_S           : out    vl_logic_vector;
        WDATA_S         : out    vl_logic_vector(31 downto 0);
        WSTRB_S         : out    vl_logic_vector(3 downto 0);
        WLAST_S         : out    vl_logic;
        WVALID_S        : out    vl_logic;
        WREADY_S        : in     vl_logic;
        BID_S           : in     vl_logic_vector;
        BRESP_S         : in     vl_logic_vector(1 downto 0);
        BVALID_S        : in     vl_logic;
        BREADY_S        : out    vl_logic;
        ARID_S          : out    vl_logic_vector;
        ARADDR_S        : out    vl_logic_vector(31 downto 0);
        ARLEN_S         : out    vl_logic_vector(3 downto 0);
        ARBURST_S       : out    vl_logic_vector(1 downto 0);
        ARVALID_S       : out    vl_logic;
        ARREADY_S       : in     vl_logic;
        RID_S           : in     vl_logic_vector;
        RDATA_S         : in     vl_logic_vector(31 downto 0);
        RRESP_S         : in     vl_logic_vector(1 downto 0);
        RLAST_S         : in     vl_logic;
        RVALID_S        : in     vl_logic;
        RREADY_S        : out    vl_logic
    );
end DDRSpi;
