library verilog;
use verilog.vl_types.all;
entity readchannel is
    generic(
        bus_wid         : integer := 32;
        addr_wid        : integer := 32;
        id_wid          : integer := 4;
        awlen_wid       : integer := 4;
        awsize_wid      : integer := 3;
        awburst_wid     : integer := 2;
        awlock_wid      : integer := 2;
        awcache_wid     : integer := 4;
        awprot_wid      : integer := 3;
        wstrb_wid       : integer := 4;
        bresp_wid       : integer := 2;
        rresp_wid       : integer := 2;
        arlen_wid       : integer := 4;
        arsize_wid      : integer := 3;
        arburst_wid     : integer := 2;
        arlock_wid      : integer := 2;
        arcache_wid     : integer := 4;
        arprot_wid      : integer := 3;
        master_wid      : integer := 4;
        slave_wid       : integer := 3;
        slave_num       : integer := 6;
        master_num      : integer := 4;
        slavecntwid     : integer := 5;
        reqdepth_wid    : integer := 2
    );
    port(
        aclk            : in     vl_logic;
        aresetn         : in     vl_logic;
        aridm02si0      : in     vl_logic_vector;
        araddrm02si0    : in     vl_logic_vector;
        arlenm02si0     : in     vl_logic_vector;
        arsizem02si0    : in     vl_logic_vector;
        arburstm02si0   : in     vl_logic_vector;
        arlockm02si0    : in     vl_logic_vector;
        arcachem02si0   : in     vl_logic_vector;
        arprotm02si0    : in     vl_logic_vector;
        arvalidm02si0   : in     vl_logic;
        arreadysi02m0   : out    vl_logic;
        ridsi02m0       : out    vl_logic_vector;
        rrespsi02m0     : out    vl_logic_vector;
        rdatasi02m0     : out    vl_logic_vector;
        rlastsi02m0     : out    vl_logic;
        rvalidsi02m0    : out    vl_logic;
        rreadym02si0    : in     vl_logic;
        aridm12si1      : in     vl_logic_vector;
        araddrm12si1    : in     vl_logic_vector;
        arlenm12si1     : in     vl_logic_vector;
        arsizem12si1    : in     vl_logic_vector;
        arburstm12si1   : in     vl_logic_vector;
        arlockm12si1    : in     vl_logic_vector;
        arcachem12si1   : in     vl_logic_vector;
        arprotm12si1    : in     vl_logic_vector;
        arvalidm12si1   : in     vl_logic;
        arreadysi12m1   : out    vl_logic;
        ridsi12m1       : out    vl_logic_vector;
        rrespsi12m1     : out    vl_logic_vector;
        rdatasi12m1     : out    vl_logic_vector;
        rlastsi12m1     : out    vl_logic;
        rvalidsi12m1    : out    vl_logic;
        rreadym12si1    : in     vl_logic;
        aridm22si2      : in     vl_logic_vector;
        araddrm22si2    : in     vl_logic_vector;
        arlenm22si2     : in     vl_logic_vector;
        arsizem22si2    : in     vl_logic_vector;
        arburstm22si2   : in     vl_logic_vector;
        arlockm22si2    : in     vl_logic_vector;
        arcachem22si2   : in     vl_logic_vector;
        arprotm22si2    : in     vl_logic_vector;
        arvalidm22si2   : in     vl_logic;
        arreadysi22m2   : out    vl_logic;
        ridsi22m2       : out    vl_logic_vector;
        rrespsi22m2     : out    vl_logic_vector;
        rdatasi22m2     : out    vl_logic_vector;
        rlastsi22m2     : out    vl_logic;
        rvalidsi22m2    : out    vl_logic;
        rreadym22si2    : in     vl_logic;
        aridm32si3      : in     vl_logic_vector;
        araddrm32si3    : in     vl_logic_vector;
        arlenm32si3     : in     vl_logic_vector;
        arsizem32si3    : in     vl_logic_vector;
        arburstm32si3   : in     vl_logic_vector;
        arlockm32si3    : in     vl_logic_vector;
        arcachem32si3   : in     vl_logic_vector;
        arprotm32si3    : in     vl_logic_vector;
        arvalidm32si3   : in     vl_logic;
        arreadysi32m3   : out    vl_logic;
        ridsi32m3       : out    vl_logic_vector;
        rrespsi32m3     : out    vl_logic_vector;
        rdatasi32m3     : out    vl_logic_vector;
        rlastsi32m3     : out    vl_logic;
        rvalidsi32m3    : out    vl_logic;
        rreadym32si3    : in     vl_logic;
        aridmi02s0      : out    vl_logic_vector;
        araddrmi02s0    : out    vl_logic_vector;
        arlenmi02s0     : out    vl_logic_vector;
        arsizemi02s0    : out    vl_logic_vector;
        arburstmi02s0   : out    vl_logic_vector;
        arlockmi02s0    : out    vl_logic_vector;
        arcachemi02s0   : out    vl_logic_vector;
        arprotmi02s0    : out    vl_logic_vector;
        arvalidmi02s0   : out    vl_logic;
        arreadys02mi0   : in     vl_logic;
        rids02mi0       : in     vl_logic_vector;
        rresps02mi0     : in     vl_logic_vector;
        rdatas02mi0     : in     vl_logic_vector;
        rlasts02mi0     : in     vl_logic;
        rvalids02mi0    : in     vl_logic;
        rreadymi02s0    : out    vl_logic;
        aridmi12s1      : out    vl_logic_vector;
        araddrmi12s1    : out    vl_logic_vector;
        arlenmi12s1     : out    vl_logic_vector;
        arsizemi12s1    : out    vl_logic_vector;
        arburstmi12s1   : out    vl_logic_vector;
        arlockmi12s1    : out    vl_logic_vector;
        arcachemi12s1   : out    vl_logic_vector;
        arprotmi12s1    : out    vl_logic_vector;
        arvalidmi12s1   : out    vl_logic;
        arreadys12mi1   : in     vl_logic;
        rids12mi1       : in     vl_logic_vector;
        rresps12mi1     : in     vl_logic_vector;
        rdatas12mi1     : in     vl_logic_vector;
        rlasts12mi1     : in     vl_logic;
        rvalids12mi1    : in     vl_logic;
        rreadymi12s1    : out    vl_logic;
        aridmi22s2      : out    vl_logic_vector;
        araddrmi22s2    : out    vl_logic_vector;
        arlenmi22s2     : out    vl_logic_vector;
        arsizemi22s2    : out    vl_logic_vector;
        arburstmi22s2   : out    vl_logic_vector;
        arlockmi22s2    : out    vl_logic_vector;
        arcachemi22s2   : out    vl_logic_vector;
        arprotmi22s2    : out    vl_logic_vector;
        arvalidmi22s2   : out    vl_logic;
        arreadys22mi2   : in     vl_logic;
        rids22mi2       : in     vl_logic_vector;
        rresps22mi2     : in     vl_logic_vector;
        rdatas22mi2     : in     vl_logic_vector;
        rlasts22mi2     : in     vl_logic;
        rvalids22mi2    : in     vl_logic;
        rreadymi22s2    : out    vl_logic;
        aridmi32s3      : out    vl_logic_vector;
        araddrmi32s3    : out    vl_logic_vector;
        arlenmi32s3     : out    vl_logic_vector;
        arsizemi32s3    : out    vl_logic_vector;
        arburstmi32s3   : out    vl_logic_vector;
        arlockmi32s3    : out    vl_logic_vector;
        arcachemi32s3   : out    vl_logic_vector;
        arprotmi32s3    : out    vl_logic_vector;
        arvalidmi32s3   : out    vl_logic;
        arreadys32mi3   : in     vl_logic;
        rids32mi3       : in     vl_logic_vector;
        rresps32mi3     : in     vl_logic_vector;
        rdatas32mi3     : in     vl_logic_vector;
        rlasts32mi3     : in     vl_logic;
        rvalids32mi3    : in     vl_logic;
        rreadymi32s3    : out    vl_logic;
        aridmi42s4      : out    vl_logic_vector;
        araddrmi42s4    : out    vl_logic_vector;
        arlenmi42s4     : out    vl_logic_vector;
        arsizemi42s4    : out    vl_logic_vector;
        arburstmi42s4   : out    vl_logic_vector;
        arlockmi42s4    : out    vl_logic_vector;
        arcachemi42s4   : out    vl_logic_vector;
        arprotmi42s4    : out    vl_logic_vector;
        arvalidmi42s4   : out    vl_logic;
        arreadys42mi4   : in     vl_logic;
        rids42mi4       : in     vl_logic_vector;
        rresps42mi4     : in     vl_logic_vector;
        rdatas42mi4     : in     vl_logic_vector;
        rlasts42mi4     : in     vl_logic;
        rvalids42mi4    : in     vl_logic;
        rreadymi42s4    : out    vl_logic;
        aridmi52s5      : out    vl_logic_vector;
        araddrmi52s5    : out    vl_logic_vector;
        arlenmi52s5     : out    vl_logic_vector;
        arsizemi52s5    : out    vl_logic_vector;
        arburstmi52s5   : out    vl_logic_vector;
        arlockmi52s5    : out    vl_logic_vector;
        arcachemi52s5   : out    vl_logic_vector;
        arprotmi52s5    : out    vl_logic_vector;
        arvalidmi52s5   : out    vl_logic;
        arreadys52mi5   : in     vl_logic;
        rids52mi5       : in     vl_logic_vector;
        rresps52mi5     : in     vl_logic_vector;
        rdatas52mi5     : in     vl_logic_vector;
        rlasts52mi5     : in     vl_logic;
        rvalids52mi5    : in     vl_logic;
        rreadymi52s5    : out    vl_logic;
        lock2rdmi0      : in     vl_logic;
        lock2rdmi1      : in     vl_logic;
        lock2rdmi2      : in     vl_logic;
        lock2rdmi3      : in     vl_logic;
        lock2rdmi4      : in     vl_logic;
        lock2rdmi5      : in     vl_logic;
        lock2wrmi0      : out    vl_logic;
        lock2wrmi1      : out    vl_logic;
        lock2wrmi2      : out    vl_logic;
        lock2wrmi3      : out    vl_logic;
        lock2wrmi4      : out    vl_logic;
        lock2wrmi5      : out    vl_logic;
        unlock2rdmi0    : in     vl_logic;
        unlock2rdmi1    : in     vl_logic;
        unlock2rdmi2    : in     vl_logic;
        unlock2rdmi3    : in     vl_logic;
        unlock2rdmi4    : in     vl_logic;
        unlock2rdmi5    : in     vl_logic;
        unlock2wrmi0    : out    vl_logic;
        unlock2wrmi1    : out    vl_logic;
        unlock2wrmi2    : out    vl_logic;
        unlock2wrmi3    : out    vl_logic;
        unlock2wrmi4    : out    vl_logic;
        unlock2wrmi5    : out    vl_logic;
        awvalidmi02s0   : in     vl_logic;
        awvalidmi12s1   : in     vl_logic;
        awvalidmi22s2   : in     vl_logic;
        awvalidmi32s3   : in     vl_logic;
        awvalidmi42s4   : in     vl_logic;
        awvalidmi52s5   : in     vl_logic;
        lockport2rdmi0  : in     vl_logic_vector;
        lockport2rdmi1  : in     vl_logic_vector;
        lockport2rdmi2  : in     vl_logic_vector;
        lockport2rdmi3  : in     vl_logic_vector;
        lockport2rdmi4  : in     vl_logic_vector;
        lockport2rdmi5  : in     vl_logic_vector;
        readintemptywrmi02rdmi0: in     vl_logic;
        readintemptywrmi12rdmi1: in     vl_logic;
        readintemptywrmi22rdmi2: in     vl_logic;
        readintemptywrmi32rdmi3: in     vl_logic;
        readintemptywrmi42rdmi4: in     vl_logic;
        readintemptywrmi52rdmi5: in     vl_logic;
        datacntemptyrdmi02wrmi0: out    vl_logic;
        datacntemptyrdmi12wrmi1: out    vl_logic;
        datacntemptyrdmi22wrmi2: out    vl_logic;
        datacntemptyrdmi32wrmi3: out    vl_logic;
        datacntemptyrdmi42wrmi4: out    vl_logic;
        datacntemptyrdmi52wrmi5: out    vl_logic;
        ctldataread2lock0: out    vl_logic_vector;
        ctldataread2lock1: out    vl_logic_vector;
        ctldataread2lock2: out    vl_logic_vector;
        ctldataread2lock3: out    vl_logic_vector;
        ctldataread2lock4: out    vl_logic_vector;
        ctldataread2lock5: out    vl_logic_vector
    );
end readchannel;
