database -open waves -into waves.shm -default
probe -create -shm pcim64ahbw_tb.UUT.clk_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.rstn_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.reqn_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.gntn_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.idsel_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.framen_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.req64n_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.irdyn_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.devseln_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.ack64n_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.trdyn_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.stopn_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.ad_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.cbe_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.par_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.par64_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.perrn_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.serrn_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.intan_p -waveform
probe -create -shm pcim64ahbw_tb.UUT.hclk -waveform
probe -create -shm pcim64ahbw_tb.UUT.hresetn -waveform
probe -create -shm pcim64ahbw_tb.UUT.mhbusreq -waveform
probe -create -shm pcim64ahbw_tb.UUT.mhgrant -waveform
probe -create -shm pcim64ahbw_tb.UUT.mhtrans -waveform
probe -create -shm pcim64ahbw_tb.UUT.mhwrite -waveform
probe -create -shm pcim64ahbw_tb.UUT.mhburst -waveform
probe -create -shm pcim64ahbw_tb.UUT.mhsize -waveform
probe -create -shm pcim64ahbw_tb.UUT.mhprot -waveform
probe -create -shm pcim64ahbw_tb.UUT.mhlock -waveform
probe -create -shm pcim64ahbw_tb.UUT.mhready -waveform
probe -create -shm pcim64ahbw_tb.UUT.mhresp -waveform
probe -create -shm pcim64ahbw_tb.UUT.mhaddr -waveform
probe -create -shm pcim64ahbw_tb.UUT.mhwdata -waveform
probe -create -shm pcim64ahbw_tb.UUT.mhrdata -waveform
