#- --=================================================================--
#- This confidential and proprietary software may be used only as
#- authorised by a licensing agreement from ARM Limited
#-   (C) COPYRIGHT 2000 ARM Limited
#-       ALL RIGHTS RESERVED
#- The entire notice above must be reproduced on all authorised
#- copies and copies may only be made to the extent permitted
#- by a licensing agreement from ARM Limited.
#-
#-----------------------------------------------------------------------
#- Version and Release Control Information:
#-
#- File Name              : makefile.rca
#- File Revision          : 1.3
#-
#- Release Information    : PrimeCell(TM)-PL041-REL1v0
#-
#-----------------------------------------------------------------------
#-  Purpose  :
#-             Standard Verilog Library Makefile
#-
#- --=================================================================--

MODULES = AaciParams.v \
	AaciRevAnd.v \
	AaciFrmGen.v \
	AaciSlot0Gen.v \
	AaciFrmDec.v \
	AaciTxCntl.v \
	AaciRxCntl.v \
	AaciTmgCntl.v \
	AaciApbifReg.v \
	AaciTxFCntl.v  \
	AaciDMATxFCntl.v  \
	AaciRxFCntl.v \
	AaciDMARxFCntl.v \
	AaciTxRegFile.v \
	AaciRxRegFile.v \
	AaciTxChannel.v \
	AaciDMATChannel.v \
	AaciRxChannel.v \
	AaciDMARChannel.v \
	AaciIntrGen.v \
	AaciBtoPSync.v \
	AaciPtoBSync.v \
	Aaci.v

include $(GLOBAL)/$(SIMULATOR)/RtlMakefile.mk

############################## End #####################################
