library verilog;
use verilog.vl_types.all;
entity pcim64ahb is
    port(
        clkpci          : in     vl_logic;
        rstpcin         : in     vl_logic;
        adi             : in     vl_logic_vector(63 downto 0);
        cbei            : in     vl_logic_vector(7 downto 0);
        pari            : in     vl_logic;
        par64i          : in     vl_logic;
        idseli          : in     vl_logic;
        gntni           : in     vl_logic;
        frameni         : in     vl_logic;
        req64ni         : in     vl_logic;
        irdyni          : in     vl_logic;
        devselni        : in     vl_logic;
        ack64ni         : in     vl_logic;
        trdyni          : in     vl_logic;
        stopni          : in     vl_logic;
        perrni          : in     vl_logic;
        reqno           : out    vl_logic;
        frameno         : out    vl_logic;
        req64no         : out    vl_logic;
        irdyno          : out    vl_logic;
        devselno        : out    vl_logic;
        ack64no         : out    vl_logic;
        trdyno          : out    vl_logic;
        stopno          : out    vl_logic;
        ot_frame        : out    vl_logic;
        ot_req64        : out    vl_logic;
        ot_irdy         : out    vl_logic;
        ot_devsel       : out    vl_logic;
        ot_ack64        : out    vl_logic;
        ot_trdy         : out    vl_logic;
        ot_stop         : out    vl_logic;
        intano          : out    vl_logic;
        paro            : out    vl_logic;
        par64o          : out    vl_logic;
        perrno          : out    vl_logic;
        serrno          : out    vl_logic;
        ot_perr         : out    vl_logic;
        ot_par          : out    vl_logic;
        ot_par64        : out    vl_logic;
        ado             : out    vl_logic_vector(63 downto 0);
        ot_ad           : out    vl_logic_vector(63 downto 0);
        cbeo            : out    vl_logic_vector(7 downto 0);
        ot_cbe          : out    vl_logic_vector(7 downto 0);
        hclk            : in     vl_logic;
        hresetn         : in     vl_logic;
        mhaddr          : out    vl_logic_vector(31 downto 0);
        mhbusreq        : out    vl_logic;
        mhlock          : out    vl_logic;
        mhgrant         : in     vl_logic;
        mhwrite         : out    vl_logic;
        mhtrans         : out    vl_logic_vector(1 downto 0);
        mhsize          : out    vl_logic_vector(2 downto 0);
        mhprot          : out    vl_logic_vector(3 downto 0);
        mhburst         : out    vl_logic_vector(2 downto 0);
        mhready         : in     vl_logic;
        mhresp          : in     vl_logic_vector(1 downto 0);
        mhrdata         : in     vl_logic_vector(31 downto 0);
        mhwdata         : out    vl_logic_vector(31 downto 0);
        shsel           : in     vl_logic;
        shwrite         : in     vl_logic;
        shtrans         : in     vl_logic_vector(1 downto 0);
        shsize          : in     vl_logic_vector(2 downto 0);
        shburst         : in     vl_logic_vector(2 downto 0);
        shaddr          : in     vl_logic_vector(31 downto 0);
        shready         : out    vl_logic;
        shresp          : out    vl_logic_vector(1 downto 0);
        shrdata         : out    vl_logic_vector(31 downto 0);
        shwdata         : in     vl_logic_vector(31 downto 0);
        hint            : out    vl_logic
    );
end pcim64ahb;
