library verilog;
use verilog.vl_types.all;
entity SMCtl is
    port(
        CLK             : in     vl_logic;
        NRST            : in     vl_logic;
        ClkEnab         : in     vl_logic;
        SoftReset       : in     vl_logic;
        Enab            : in     vl_logic;
        IFLG            : in     vl_logic;
        STA             : in     vl_logic;
        STP             : in     vl_logic;
        AAK             : in     vl_logic;
        ReadData0       : in     vl_logic;
        Ack             : in     vl_logic;
        BusBusy         : in     vl_logic;
        StartDet        : in     vl_logic;
        StopDet         : in     vl_logic;
        ArbLost         : in     vl_logic;
        Slave7Det       : in     vl_logic;
        Slave101Det     : in     vl_logic;
        Slave102Det     : in     vl_logic;
        GenCallDet      : in     vl_logic;
        ExtAddrDet      : in     vl_logic;
        StartComp       : in     vl_logic;
        TFerComp        : in     vl_logic;
        ClearSTP        : in     vl_logic;
        TFerData        : in     vl_logic;
        TFerAck         : in     vl_logic;
        SampAddr        : in     vl_logic;
        Status          : out    vl_logic_vector(7 downto 3);
        SRLoad          : out    vl_logic;
        SendStart       : out    vl_logic;
        StartTFer       : out    vl_logic;
        SendStop        : out    vl_logic;
        SendAck         : out    vl_logic;
        TxData          : out    vl_logic;
        NoIFLG          : out    vl_logic;
        ArbDataEnab     : out    vl_logic;
        ArbAckEnab      : out    vl_logic;
        BusClkEnab      : out    vl_logic;
        ErrCond1        : out    vl_logic;
        ErrCond2        : out    vl_logic;
        GoToIdle        : out    vl_logic;
        ReleaseBus      : out    vl_logic;
        MastMode        : out    vl_logic;
        flagrs          : out    vl_logic
    );
end SMCtl;
