#####################################################

#  Created by Design Compiler write_sdc on Mon Jan 15 13:57:48 2007

#####################################################
set sdc_version 1.4

create_clock -period 10 -waveform {0 5} [get_ports {MCK}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[0]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[0]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[1]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[1]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[2]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[2]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[3]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[3]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[4]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[4]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[5]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[5]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[6]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[6]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[7]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[7]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[8]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[8]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[9]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[9]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[10]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[10]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[11]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[11]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[12]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[12]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[13]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[13]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[14]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[14]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[15]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[15]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[16]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[16]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[17]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[17]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[18]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[18]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[19]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[19]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[20]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[20]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[21]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[21]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[22]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[22]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[23]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[23]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[24]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[24]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[25]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[25]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[26]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[26]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[27]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[27]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[28]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[28]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[29]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[29]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[30]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[30]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWDATA[31]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWDATA[31]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PWRITE}]
set_input_delay 0 -min -clock "MCK" [get_ports {PWRITE}]
set_input_delay 6 -max -clock "MCK" [get_ports {PADDR[2]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PADDR[2]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PADDR[3]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PADDR[3]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PADDR[4]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PADDR[4]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PADDR[5]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PADDR[5]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PADDR[6]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PADDR[6]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PADDR[7]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PADDR[7]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PADDR[8]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PADDR[8]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PADDR[9]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PADDR[9]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PADDR[10]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PADDR[10]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PADDR[11]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PADDR[11]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PADDR[12]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PADDR[12]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PADDR[13]}]
set_input_delay 0 -min -clock "MCK" [get_ports {PADDR[13]}]
set_input_delay 6 -max -clock "MCK" [get_ports {PENABLE}]
set_input_delay 0 -min -clock "MCK" [get_ports {PENABLE}]
set_input_delay 6 -max -clock "MCK" [get_ports {PSEL}]
set_input_delay 0 -min -clock "MCK" [get_ports {PSEL}]
set_input_delay 5 -max -rise -clock "MCK" [get_ports {XRST}]
set_input_delay 0.5 -min -rise -clock "MCK" [get_ports {XRST}]
set_output_delay 8 -max -clock "MCK" [get_ports {PREADY}]
set_output_delay -0 -min -clock "MCK" [get_ports {PREADY}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[0]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[0]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[1]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[1]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[2]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[2]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[3]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[3]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[4]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[4]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[5]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[5]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[6]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[6]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[7]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[7]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[8]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[8]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[9]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[9]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[10]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[10]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[11]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[11]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[12]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[12]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[13]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[13]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[14]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[14]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[15]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[15]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[16]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[16]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[17]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[17]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[18]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[18]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[19]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[19]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[20]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[20]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[21]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[21]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[22]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[22]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[23]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[23]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[24]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[24]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[25]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[25]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[26]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[26]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[27]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[27]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[28]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[28]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[29]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[29]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[30]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[30]}]
set_output_delay 8 -max -clock "MCK" [get_ports {PRDATA[31]}]
set_output_delay -0 -min -clock "MCK" [get_ports {PRDATA[31]}]
set_clock_transition -rise 0 [get_clocks {MCK}]
set_clock_transition -fall 0 [get_clocks {MCK}]
set_clock_uncertainty  0.8 -setup [get_ports {MCK}]
set_max_transition 2 [current_design]
set_input_transition -max 1 [get_ports {MCK}]
set_load -pin_load 0 [get_ports {MCK}]
set_input_transition -max 1 [get_ports {XRST}]
set_load -pin_load 0 [get_ports {XRST}]
set_disable_timing [get_ports {XRST}]
set_input_transition -max 1 [get_ports {TE}]
set_input_transition -max 1 [get_ports {TI0}]
set_input_transition -max 1 [get_ports {TI1}]
set_input_transition -max 1 [get_ports {TI2}]
set_input_transition -max 1 [get_ports {TI3}]
set_input_transition -max 1 [get_ports {TI4}]
set_load -pin_load 0.018316 [get_ports {TO0}]
set_load -min -pin_load 0.018316 [get_ports {TO0}]
set_load -pin_load 0.018316 [get_ports {TO1}]
set_load -min -pin_load 0.018316 [get_ports {TO1}]
set_load -pin_load 0.018316 [get_ports {TO2}]
set_load -min -pin_load 0.018316 [get_ports {TO2}]
set_load -pin_load 0.018316 [get_ports {TO3}]
set_load -min -pin_load 0.018316 [get_ports {TO3}]
set_load -pin_load 0.018316 [get_ports {TO4}]
set_load -min -pin_load 0.018316 [get_ports {TO4}]
set_input_transition -max 1 [get_ports {PSEL}]
set_input_transition -max 1 [get_ports {PENABLE}]
set_input_transition -max 1 [get_ports {PADDR[13]}]
set_input_transition -max 1 [get_ports {PADDR[12]}]
set_input_transition -max 1 [get_ports {PADDR[11]}]
set_input_transition -max 1 [get_ports {PADDR[10]}]
set_input_transition -max 1 [get_ports {PADDR[9]}]
set_input_transition -max 1 [get_ports {PADDR[8]}]
set_input_transition -max 1 [get_ports {PADDR[7]}]
set_input_transition -max 1 [get_ports {PADDR[6]}]
set_input_transition -max 1 [get_ports {PADDR[5]}]
set_input_transition -max 1 [get_ports {PADDR[4]}]
set_input_transition -max 1 [get_ports {PADDR[3]}]
set_input_transition -max 1 [get_ports {PADDR[2]}]
set_input_transition -max 1 [get_ports {PWRITE}]
set_input_transition -max 1 [get_ports {PWDATA[31]}]
set_input_transition -max 1 [get_ports {PWDATA[30]}]
set_input_transition -max 1 [get_ports {PWDATA[29]}]
set_input_transition -max 1 [get_ports {PWDATA[28]}]
set_input_transition -max 1 [get_ports {PWDATA[27]}]
set_input_transition -max 1 [get_ports {PWDATA[26]}]
set_input_transition -max 1 [get_ports {PWDATA[25]}]
set_input_transition -max 1 [get_ports {PWDATA[24]}]
set_input_transition -max 1 [get_ports {PWDATA[23]}]
set_input_transition -max 1 [get_ports {PWDATA[22]}]
set_input_transition -max 1 [get_ports {PWDATA[21]}]
set_input_transition -max 1 [get_ports {PWDATA[20]}]
set_input_transition -max 1 [get_ports {PWDATA[19]}]
set_input_transition -max 1 [get_ports {PWDATA[18]}]
set_input_transition -max 1 [get_ports {PWDATA[17]}]
set_input_transition -max 1 [get_ports {PWDATA[16]}]
set_input_transition -max 1 [get_ports {PWDATA[15]}]
set_input_transition -max 1 [get_ports {PWDATA[14]}]
set_input_transition -max 1 [get_ports {PWDATA[13]}]
set_input_transition -max 1 [get_ports {PWDATA[12]}]
set_input_transition -max 1 [get_ports {PWDATA[11]}]
set_input_transition -max 1 [get_ports {PWDATA[10]}]
set_input_transition -max 1 [get_ports {PWDATA[9]}]
set_input_transition -max 1 [get_ports {PWDATA[8]}]
set_input_transition -max 1 [get_ports {PWDATA[7]}]
set_input_transition -max 1 [get_ports {PWDATA[6]}]
set_input_transition -max 1 [get_ports {PWDATA[5]}]
set_input_transition -max 1 [get_ports {PWDATA[4]}]
set_input_transition -max 1 [get_ports {PWDATA[3]}]
set_input_transition -max 1 [get_ports {PWDATA[2]}]
set_input_transition -max 1 [get_ports {PWDATA[1]}]
set_input_transition -max 1 [get_ports {PWDATA[0]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[31]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[31]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[30]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[30]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[29]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[29]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[28]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[28]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[27]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[27]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[26]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[26]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[25]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[25]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[24]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[24]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[23]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[23]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[22]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[22]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[21]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[21]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[20]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[20]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[19]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[19]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[18]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[18]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[17]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[17]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[16]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[16]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[15]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[15]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[14]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[14]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[13]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[13]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[12]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[12]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[11]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[11]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[10]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[10]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[9]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[9]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[8]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[8]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[7]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[7]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[6]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[6]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[5]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[5]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[4]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[4]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[3]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[3]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[2]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[2]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[1]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[1]}]
set_load -pin_load 0.018316 [get_ports {PRDATA[0]}]
set_load -min -pin_load 0.018316 [get_ports {PRDATA[0]}]
set_load -pin_load 0.018316 [get_ports {PREADY}]
set_load -min -pin_load 0.018316 [get_ports {PREADY}]
set_load -pin_load 0.018316 [get_ports {EEMA_M[15]}]
set_load -min -pin_load 0.018316 [get_ports {EEMA_M[15]}]
set_load -pin_load 0.018316 [get_ports {EEMA_M[14]}]
set_load -min -pin_load 0.018316 [get_ports {EEMA_M[14]}]
set_load -pin_load 0.018316 [get_ports {EEMA_M[13]}]
set_load -min -pin_load 0.018316 [get_ports {EEMA_M[13]}]
set_load -pin_load 0.018316 [get_ports {EEMA_M[12]}]
set_load -min -pin_load 0.018316 [get_ports {EEMA_M[12]}]
set_load -pin_load 0.018316 [get_ports {EEMA_M[11]}]
set_load -min -pin_load 0.018316 [get_ports {EEMA_M[11]}]
set_load -pin_load 0.018316 [get_ports {EEMA_M[10]}]
set_load -min -pin_load 0.018316 [get_ports {EEMA_M[10]}]
set_load -pin_load 0.018316 [get_ports {EEMA_M[9]}]
set_load -min -pin_load 0.018316 [get_ports {EEMA_M[9]}]
set_load -pin_load 0.018316 [get_ports {EEMA_M[8]}]
set_load -min -pin_load 0.018316 [get_ports {EEMA_M[8]}]
set_load -pin_load 0.018316 [get_ports {EEMA_M[7]}]
set_load -min -pin_load 0.018316 [get_ports {EEMA_M[7]}]
set_load -pin_load 0.018316 [get_ports {EEMA_M[6]}]
set_load -min -pin_load 0.018316 [get_ports {EEMA_M[6]}]
set_load -pin_load 0.018316 [get_ports {EEMA_M[5]}]
set_load -min -pin_load 0.018316 [get_ports {EEMA_M[5]}]
set_load -pin_load 0.018316 [get_ports {EEMA_M[4]}]
set_load -min -pin_load 0.018316 [get_ports {EEMA_M[4]}]
set_load -pin_load 0.018316 [get_ports {EEMA_M[3]}]
set_load -min -pin_load 0.018316 [get_ports {EEMA_M[3]}]
set_load -pin_load 0.018316 [get_ports {EEMA_M[2]}]
set_load -min -pin_load 0.018316 [get_ports {EEMA_M[2]}]
set_load -pin_load 0.018316 [get_ports {EEMA_M[1]}]
set_load -min -pin_load 0.018316 [get_ports {EEMA_M[1]}]
set_load -pin_load 0.018316 [get_ports {EEMA_M[0]}]
set_load -min -pin_load 0.018316 [get_ports {EEMA_M[0]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[31]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[31]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[30]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[30]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[29]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[29]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[28]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[28]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[27]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[27]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[26]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[26]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[25]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[25]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[24]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[24]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[23]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[23]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[22]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[22]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[21]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[21]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[20]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[20]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[19]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[19]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[18]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[18]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[17]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[17]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[16]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[16]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[15]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[15]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[14]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[14]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[13]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[13]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[12]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[12]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[11]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[11]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[10]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[10]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[9]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[9]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[8]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[8]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[7]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[7]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[6]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[6]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[5]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[5]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[4]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[4]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[3]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[3]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[2]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[2]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[1]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[1]}]
set_load -pin_load 0.018316 [get_ports {EEMDI_M[0]}]
set_load -min -pin_load 0.018316 [get_ports {EEMDI_M[0]}]
set_input_transition -max 1 [get_ports {EEMDO_M[31]}]
set_input_transition -max 1 [get_ports {EEMDO_M[30]}]
set_input_transition -max 1 [get_ports {EEMDO_M[29]}]
set_input_transition -max 1 [get_ports {EEMDO_M[28]}]
set_input_transition -max 1 [get_ports {EEMDO_M[27]}]
set_input_transition -max 1 [get_ports {EEMDO_M[26]}]
set_input_transition -max 1 [get_ports {EEMDO_M[25]}]
set_input_transition -max 1 [get_ports {EEMDO_M[24]}]
set_input_transition -max 1 [get_ports {EEMDO_M[23]}]
set_input_transition -max 1 [get_ports {EEMDO_M[22]}]
set_input_transition -max 1 [get_ports {EEMDO_M[21]}]
set_input_transition -max 1 [get_ports {EEMDO_M[20]}]
set_input_transition -max 1 [get_ports {EEMDO_M[19]}]
set_input_transition -max 1 [get_ports {EEMDO_M[18]}]
set_input_transition -max 1 [get_ports {EEMDO_M[17]}]
set_input_transition -max 1 [get_ports {EEMDO_M[16]}]
set_input_transition -max 1 [get_ports {EEMDO_M[15]}]
set_input_transition -max 1 [get_ports {EEMDO_M[14]}]
set_input_transition -max 1 [get_ports {EEMDO_M[13]}]
set_input_transition -max 1 [get_ports {EEMDO_M[12]}]
set_input_transition -max 1 [get_ports {EEMDO_M[11]}]
set_input_transition -max 1 [get_ports {EEMDO_M[10]}]
set_input_transition -max 1 [get_ports {EEMDO_M[9]}]
set_input_transition -max 1 [get_ports {EEMDO_M[8]}]
set_input_transition -max 1 [get_ports {EEMDO_M[7]}]
set_input_transition -max 1 [get_ports {EEMDO_M[6]}]
set_input_transition -max 1 [get_ports {EEMDO_M[5]}]
set_input_transition -max 1 [get_ports {EEMDO_M[4]}]
set_input_transition -max 1 [get_ports {EEMDO_M[3]}]
set_input_transition -max 1 [get_ports {EEMDO_M[2]}]
set_input_transition -max 1 [get_ports {EEMDO_M[1]}]
set_input_transition -max 1 [get_ports {EEMDO_M[0]}]
set_load -pin_load 0.018316 [get_ports {XEEMWE_M[3]}]
set_load -min -pin_load 0.018316 [get_ports {XEEMWE_M[3]}]
set_load -pin_load 0.018316 [get_ports {XEEMWE_M[2]}]
set_load -min -pin_load 0.018316 [get_ports {XEEMWE_M[2]}]
set_load -pin_load 0.018316 [get_ports {XEEMWE_M[1]}]
set_load -min -pin_load 0.018316 [get_ports {XEEMWE_M[1]}]
set_load -pin_load 0.018316 [get_ports {XEEMWE_M[0]}]
set_load -min -pin_load 0.018316 [get_ports {XEEMWE_M[0]}]
set_load -pin_load 0.018316 [get_ports {RxDmaRequest}]
set_load -min -pin_load 0.018316 [get_ports {RxDmaRequest}]
set_load -pin_load 0.018316 [get_ports {TxDmaRequest}]
set_load -min -pin_load 0.018316 [get_ports {TxDmaRequest}]
set_load -pin_load 0.018316 [get_ports {SEIPInt}]
set_load -min -pin_load 0.018316 [get_ports {SEIPInt}]
set_load -pin_load 0.018316 [get_ports {EXMBIH}]
set_load -min -pin_load 0.018316 [get_ports {EXMBIH}]
set_load -pin_load 0.018316 [get_ports {WEMDI[7]}]
set_load -min -pin_load 0.018316 [get_ports {WEMDI[7]}]
set_load -pin_load 0.018316 [get_ports {WEMDI[6]}]
set_load -min -pin_load 0.018316 [get_ports {WEMDI[6]}]
set_load -pin_load 0.018316 [get_ports {WEMDI[5]}]
set_load -min -pin_load 0.018316 [get_ports {WEMDI[5]}]
set_load -pin_load 0.018316 [get_ports {WEMDI[4]}]
set_load -min -pin_load 0.018316 [get_ports {WEMDI[4]}]
set_load -pin_load 0.018316 [get_ports {WEMDI[3]}]
set_load -min -pin_load 0.018316 [get_ports {WEMDI[3]}]
set_load -pin_load 0.018316 [get_ports {WEMDI[2]}]
set_load -min -pin_load 0.018316 [get_ports {WEMDI[2]}]
set_load -pin_load 0.018316 [get_ports {WEMDI[1]}]
set_load -min -pin_load 0.018316 [get_ports {WEMDI[1]}]
set_load -pin_load 0.018316 [get_ports {WEMDI[0]}]
set_load -min -pin_load 0.018316 [get_ports {WEMDI[0]}]
set_input_transition -max 1 [get_ports {WEMDO[7]}]
set_input_transition -max 1 [get_ports {WEMDO[6]}]
set_input_transition -max 1 [get_ports {WEMDO[5]}]
set_input_transition -max 1 [get_ports {WEMDO[4]}]
set_input_transition -max 1 [get_ports {WEMDO[3]}]
set_input_transition -max 1 [get_ports {WEMDO[2]}]
set_input_transition -max 1 [get_ports {WEMDO[1]}]
set_input_transition -max 1 [get_ports {WEMDO[0]}]
set_load -pin_load 0.018316 [get_ports {WEMA[23]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[23]}]
set_load -pin_load 0.018316 [get_ports {WEMA[22]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[22]}]
set_load -pin_load 0.018316 [get_ports {WEMA[21]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[21]}]
set_load -pin_load 0.018316 [get_ports {WEMA[20]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[20]}]
set_load -pin_load 0.018316 [get_ports {WEMA[19]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[19]}]
set_load -pin_load 0.018316 [get_ports {WEMA[18]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[18]}]
set_load -pin_load 0.018316 [get_ports {WEMA[17]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[17]}]
set_load -pin_load 0.018316 [get_ports {WEMA[16]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[16]}]
set_load -pin_load 0.018316 [get_ports {WEMA[15]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[15]}]
set_load -pin_load 0.018316 [get_ports {WEMA[14]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[14]}]
set_load -pin_load 0.018316 [get_ports {WEMA[13]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[13]}]
set_load -pin_load 0.018316 [get_ports {WEMA[12]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[12]}]
set_load -pin_load 0.018316 [get_ports {WEMA[11]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[11]}]
set_load -pin_load 0.018316 [get_ports {WEMA[10]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[10]}]
set_load -pin_load 0.018316 [get_ports {WEMA[9]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[9]}]
set_load -pin_load 0.018316 [get_ports {WEMA[8]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[8]}]
set_load -pin_load 0.018316 [get_ports {WEMA[7]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[7]}]
set_load -pin_load 0.018316 [get_ports {WEMA[6]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[6]}]
set_load -pin_load 0.018316 [get_ports {WEMA[5]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[5]}]
set_load -pin_load 0.018316 [get_ports {WEMA[4]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[4]}]
set_load -pin_load 0.018316 [get_ports {WEMA[3]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[3]}]
set_load -pin_load 0.018316 [get_ports {WEMA[2]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[2]}]
set_load -pin_load 0.018316 [get_ports {WEMA[1]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[1]}]
set_load -pin_load 0.018316 [get_ports {WEMA[0]}]
set_load -min -pin_load 0.018316 [get_ports {WEMA[0]}]
set_load -pin_load 0.018316 [get_ports {XWEMOC}]
set_load -min -pin_load 0.018316 [get_ports {XWEMOC}]
set_load -pin_load 0.018316 [get_ports {XWEMWE}]
set_load -min -pin_load 0.018316 [get_ports {XWEMWE}]
set_input_transition -max 1 [get_ports {SDI1}]
set_input_transition -max 1 [get_ports {SDI2}]
set_load -pin_load 0.018316 [get_ports {SCKO}]
set_load -min -pin_load 0.018316 [get_ports {SCKO}]
set_load -pin_load 0.018316 [get_ports {ADMCK}]
set_load -min -pin_load 0.018316 [get_ports {ADMCK}]
set_load -pin_load 0.018316 [get_ports {LRCKO}]
set_load -min -pin_load 0.018316 [get_ports {LRCKO}]
set_load -pin_load 0.018316 [get_ports {SD2O}]
set_load -min -pin_load 0.018316 [get_ports {SD2O}]
set_load -pin_load 0.018316 [get_ports {SD1O}]
set_load -min -pin_load 0.018316 [get_ports {SD1O}]
set_load -pin_load 0.018316 [get_ports {MLRCK}]
set_load -min -pin_load 0.018316 [get_ports {MLRCK}]
set_load -pin_load 0.018316 [get_ports {MSCK}]
set_load -min -pin_load 0.018316 [get_ports {MSCK}]
set_resistance 0 [get_nets {MCK}]
set_resistance 0 [get_nets {XRST}]
