library verilog;
use verilog.vl_types.all;
entity DmTop is
    generic(
        AW              : integer := 29;
        DW              : integer := 31;
        IW              : integer := 1;
        BW              : integer := 3;
        XW              : integer := 10;
        YW              : integer := 10;
        CW              : integer := 9;
        GW              : integer := 10;
        VW              : integer := 10;
        CPlaneMaxBL     : integer := 8;
        GPlaneMaxBL     : integer := 8;
        VPlaneMaxBL     : integer := 8;
        CBLQCD          : integer := 1;
        CBLQD           : integer := 3;
        CBLQW           : integer := 3;
        GBLQCD          : integer := 2;
        GBLQD           : integer := 7;
        GBLQW           : integer := 3;
        VBLQCD          : integer := 1;
        VBLQD           : integer := 3;
        VBLQW           : integer := 3;
        DMCON           : integer := 0;
        DMSTS           : integer := 4;
        CCON            : integer := 16;
        CBLND           : integer := 20;
        CBMOD           : integer := 24;
        CBASE           : integer := 28;
        CADDR           : integer := 32;
        CPALM           : integer := 36;
        CADDR2          : integer := 40;
        CBLINK          : integer := 44;
        BGCOL           : integer := 48;
        GCON            : integer := 64;
        GBLND           : integer := 68;
        GBMOD           : integer := 72;
        GBASE           : integer := 76;
        GADDR           : integer := 80;
        GPALM           : integer := 84;
        GGAMMA00        : integer := 256;
        GGAMMA01        : integer := 260;
        GGAMMA02        : integer := 264;
        GGAMMA03        : integer := 268;
        GGAMMA04        : integer := 272;
        GGAMMA05        : integer := 276;
        GGAMMA06        : integer := 280;
        GGAMMA07        : integer := 284;
        GGAMMA08        : integer := 288;
        GGAMMA09        : integer := 292;
        GGAMMA0A        : integer := 296;
        GGAMMA0B        : integer := 300;
        GGAMMA0C        : integer := 304;
        GGAMMA0D        : integer := 308;
        GGAMMA0E        : integer := 312;
        GGAMMA0F        : integer := 316;
        GGAMMA10        : integer := 320;
        VCON            : integer := 96;
        VBLND           : integer := 100;
        VBMOD           : integer := 104;
        VBASE           : integer := 108;
        VADDR           : integer := 112;
        VADDR2          : integer := 116;
        SCON            : integer := 128;
        SSIZE           : integer := 132;
        SRATIO          : integer := 136;
        VGAMMA00        : integer := 512;
        VGAMMA01        : integer := 516;
        VGAMMA02        : integer := 520;
        VGAMMA03        : integer := 524;
        VGAMMA04        : integer := 528;
        VGAMMA05        : integer := 532;
        VGAMMA06        : integer := 536;
        VGAMMA07        : integer := 540;
        VGAMMA08        : integer := 544;
        VGAMMA09        : integer := 548;
        VGAMMA0A        : integer := 552;
        VGAMMA0B        : integer := 556;
        VGAMMA0C        : integer := 560;
        VGAMMA0D        : integer := 564;
        VGAMMA0E        : integer := 568;
        VGAMMA0F        : integer := 572;
        VGAMMA10        : integer := 576;
        LCDCON          : integer := 224;
        VIDCON          : integer := 228;
        HSYNC0          : integer := 240;
        HSYNC1          : integer := 244;
        VSYNC0          : integer := 248;
        VSYNC1          : integer := 252
    );
    port(
        ACLK            : in     vl_logic;
        ARESETn         : in     vl_logic;
        ARID            : out    vl_logic_vector;
        ARADDR          : out    vl_logic_vector(31 downto 0);
        ARLEN           : out    vl_logic_vector(3 downto 0);
        ARSIZE          : out    vl_logic_vector(2 downto 0);
        ARBURST         : out    vl_logic_vector(1 downto 0);
        ARLOCK          : out    vl_logic_vector(1 downto 0);
        ARCACHE         : out    vl_logic_vector(3 downto 0);
        ARPROT          : out    vl_logic_vector(2 downto 0);
        ARVALID         : out    vl_logic;
        ARREADY         : in     vl_logic;
        RID             : in     vl_logic_vector;
        RDATA           : in     vl_logic_vector;
        RRESP           : in     vl_logic_vector(1 downto 0);
        RLAST           : in     vl_logic;
        RVALID          : in     vl_logic;
        RREADY          : out    vl_logic;
        PCLK            : in     vl_logic;
        PRESETB         : in     vl_logic;
        PSEL            : in     vl_logic;
        PENABLE         : in     vl_logic;
        PADDR           : in     vl_logic_vector(9 downto 2);
        PWRITE          : in     vl_logic;
        PWDATA          : in     vl_logic_vector(31 downto 0);
        PRDATA          : out    vl_logic_vector(31 downto 0);
        LCDCLK          : in     vl_logic;
        LCDCLKo         : out    vl_logic;
        LCDHSync        : out    vl_logic;
        LCDVSync        : out    vl_logic;
        LCDDataEn       : out    vl_logic;
        LCDData         : out    vl_logic_vector(23 downto 0);
        LCDPDIV         : out    vl_logic_vector(2 downto 0);
        VideoSyncEnPCLK : out    vl_logic;
        DmInt           : out    vl_logic
    );
end DmTop;
