// ARM946E_88.v shipped with DSM LF000-MS-27602-1.01rel0
//
// Verilog implementation of ARM946E_88, generated by ModelGen

// Elements of the code in this file are
// Copyright 1993, 94-99, 2000 ARM Ltd,
// All rights reserved.

`timescale 1 ps / 1 ps

// Inout shell

module ARM946E_88_inout (HBUSREQ,
  HLOCK,
  HADDR,
  HTRANS,
  HWRITE,
  HSIZE,
  HBURST,
  HPROT,
  HWDATA,
  CPINSTR,
  CPDOUT,
  CPPASS,
  CPLATECANCEL,
  CPTBIT,
  nCPMREQ,
  nCPTRANS,
  CPCLKEN,
  COMMRX,
  COMMTX,
  DBGACK,
  DBGRQI,
  DBGINSTREXEC,
  DBGRNG,
  DBGTDO,
  DBGIR,
  DBGSCREG,
  DBGTAPSM,
  DBGnTDOEN,
  DBGSDIN,
  BIGENDOUT,
  ETMBIGEND,
  ETMHIVECS,
  ETMIA,
  ETMInMREQ,
  ETMISEQ,
  ETMITBIT,
  ETMIABORT,
  ETMDA,
  ETMDMAS,
  ETMDMORE,
  ETMDnMREQ,
  ETMDnRW,
  ETMDSEQ,
  ETMRDATA,
  ETMDABORT,
  ETMCHSD,
  ETMCHSE,
  ETMnWAIT,
  ETMID31To25,
  ETMID15To11,
  ETMWDATA,
  ETMLATECANCEL,
  ETMPASS,
  ETMDBGACK,
  ETMINSTREXEC,
  ETMRNGOUT,
  ETMPROCID,
  ETMPROCIDWR,
  ETMINSTRVALID,
  GateTheCLK,
  ITCMWData,
  ITCMWEn,
  ITCMEn,
  ITCMAdrs,
  DTCMWData,
  DTCMWEn,
  DTCMEn,
  DTCMAdrs,
  SCANOUT1,
  SCANOUT2,
  SCANOUT3,
  SCANOUT4,
  HRESETn,
  HCLKEN,
  CLK,
  HGRANT,
  HRDATA,
  HREADY,
  HRESP,
  CPDIN,
  CHSDE,
  CHSEX,
  DBGEN,
  EDBGRQ,
  DBGEXT,
  DBGIEBKPT,
  DBGDEWPT,
  DBGnTRST,
  DBGTCKEN,
  DBGTDI,
  DBGTMS,
  DBGSDOUT,
  nFIQ,
  nIRQ,
  VINITHI,
  INITRAM,
  TAPID,
  DCacheSize,
  ICacheSize,
  ETMEN,
  SCANEN,
  TESTMODE,
  SCANIN1,
  SCANIN2,
  SCANIN3,
  SCANIN4,
  ETMFIFOFULL,
  UnGatedCLK,
  ITCMRData,
  DTCMRData,
  PhyDTCMSize,
  PhyITCMSize,
  cpsr,
  spsrfiq,
  spsrirq,
  spsrsvc,
  spsrabt,
  spsrund,
  r0,
  r1,
  r2,
  r3,
  r4,
  r5,
  r6,
  r7,
  r8,
  r9,
  r10,
  r11,
  r12,
  r13,
  r14,
  r15,
  r13irq,
  r14irq,
  r13svc,
  r14svc,
  r13abt,
  r14abt,
  r13und,
  r14und,
  r8fiq,
  r9fiq,
  r10fiq,
  r11fiq,
  r12fiq,
  r13fiq,
  r14fiq);

output HBUSREQ;
output HLOCK;
output [31:0] HADDR;
output [1:0] HTRANS;
output HWRITE;
output [2:0] HSIZE;
output [2:0] HBURST;
output [3:0] HPROT;
output [31:0] HWDATA;
output [31:0] CPINSTR;
output [31:0] CPDOUT;
output CPPASS;
output CPLATECANCEL;
output CPTBIT;
output nCPMREQ;
output nCPTRANS;
output CPCLKEN;
output COMMRX;
output COMMTX;
output DBGACK;
output DBGRQI;
output DBGINSTREXEC;
output [1:0] DBGRNG;
output DBGTDO;
output [3:0] DBGIR;
output [4:0] DBGSCREG;
output [3:0] DBGTAPSM;
output DBGnTDOEN;
output DBGSDIN;
output BIGENDOUT;
output ETMBIGEND;
output ETMHIVECS;
output [31:1] ETMIA;
output ETMInMREQ;
output ETMISEQ;
output ETMITBIT;
output ETMIABORT;
output [31:0] ETMDA;
output [1:0] ETMDMAS;
output ETMDMORE;
output ETMDnMREQ;
output ETMDnRW;
output ETMDSEQ;
output [31:0] ETMRDATA;
output ETMDABORT;
output [1:0] ETMCHSD;
output [1:0] ETMCHSE;
output ETMnWAIT;
output [31:25] ETMID31To25;
output [15:11] ETMID15To11;
output [31:0] ETMWDATA;
output ETMLATECANCEL;
output ETMPASS;
output ETMDBGACK;
output ETMINSTREXEC;
output [1:0] ETMRNGOUT;
output [31:0] ETMPROCID;
output ETMPROCIDWR;
output ETMINSTRVALID;
output GateTheCLK;
output [31:0] ITCMWData;
output [3:0] ITCMWEn;
output ITCMEn;
output [17:0] ITCMAdrs;
output [31:0] DTCMWData;
output [3:0] DTCMWEn;
output DTCMEn;
output [17:0] DTCMAdrs;
output SCANOUT1;
output SCANOUT2;
output SCANOUT3;
output SCANOUT4;
input HRESETn;
input HCLKEN;
input CLK;
input HGRANT;
input [31:0] HRDATA;
input HREADY;
input [1:0] HRESP;
input [31:0] CPDIN;
input [1:0] CHSDE;
input [1:0] CHSEX;
input DBGEN;
input EDBGRQ;
input [1:0] DBGEXT;
input DBGIEBKPT;
input DBGDEWPT;
input DBGnTRST;
input DBGTCKEN;
input DBGTDI;
input DBGTMS;
input DBGSDOUT;
input nFIQ;
input nIRQ;
input VINITHI;
input INITRAM;
input [31:0] TAPID;
input [3:0] DCacheSize;
input [3:0] ICacheSize;
input ETMEN;
input SCANEN;
input TESTMODE;
input SCANIN1;
input SCANIN2;
input SCANIN3;
input SCANIN4;
input ETMFIFOFULL;
input UnGatedCLK;
input [31:0] ITCMRData;
input [31:0] DTCMRData;
input [3:0] PhyDTCMSize;
input [3:0] PhyITCMSize;
output [11:0] cpsr;
output [11:0] spsrfiq;
output [11:0] spsrirq;
output [11:0] spsrsvc;
output [11:0] spsrabt;
output [11:0] spsrund;
output [31:0] r0;
output [31:0] r1;
output [31:0] r2;
output [31:0] r3;
output [31:0] r4;
output [31:0] r5;
output [31:0] r6;
output [31:0] r7;
output [31:0] r8;
output [31:0] r9;
output [31:0] r10;
output [31:0] r11;
output [31:0] r12;
output [31:0] r13;
output [31:0] r14;
output [31:0] r15;
output [31:0] r13irq;
output [31:0] r14irq;
output [31:0] r13svc;
output [31:0] r14svc;
output [31:0] r13abt;
output [31:0] r14abt;
output [31:0] r13und;
output [31:0] r14und;
output [31:0] r8fiq;
output [31:0] r9fiq;
output [31:0] r10fiq;
output [31:0] r11fiq;
output [31:0] r12fiq;
output [31:0] r13fiq;
output [31:0] r14fiq;

reg HBUSREQ;
reg HLOCK;
reg [31:0] HADDR;
reg [1:0] HTRANS;
reg HWRITE;
reg [2:0] HSIZE;
reg [2:0] HBURST;
reg [3:0] HPROT;
reg [31:0] HWDATA;
reg [31:0] CPINSTR;
reg [31:0] CPDOUT;
reg CPPASS;
reg CPLATECANCEL;
reg CPTBIT;
reg nCPMREQ;
reg nCPTRANS;
reg CPCLKEN;
reg COMMRX;
reg COMMTX;
reg DBGACK;
reg DBGRQI;
reg DBGINSTREXEC;
reg [1:0] DBGRNG;
reg DBGTDO;
reg [3:0] DBGIR;
reg [4:0] DBGSCREG;
reg [3:0] DBGTAPSM;
reg DBGnTDOEN;
reg DBGSDIN;
reg BIGENDOUT;
reg ETMBIGEND;
reg ETMHIVECS;
reg [31:1] ETMIA;
reg ETMInMREQ;
reg ETMISEQ;
reg ETMITBIT;
reg ETMIABORT;
reg [31:0] ETMDA;
reg [1:0] ETMDMAS;
reg ETMDMORE;
reg ETMDnMREQ;
reg ETMDnRW;
reg ETMDSEQ;
reg [31:0] ETMRDATA;
reg ETMDABORT;
reg [1:0] ETMCHSD;
reg [1:0] ETMCHSE;
reg ETMnWAIT;
reg [31:25] ETMID31To25;
reg [15:11] ETMID15To11;
reg [31:0] ETMWDATA;
reg ETMLATECANCEL;
reg ETMPASS;
reg ETMDBGACK;
reg ETMINSTREXEC;
reg [1:0] ETMRNGOUT;
reg [31:0] ETMPROCID;
reg ETMPROCIDWR;
reg ETMINSTRVALID;
reg GateTheCLK;
reg [31:0] ITCMWData;
reg [3:0] ITCMWEn;
reg ITCMEn;
reg [17:0] ITCMAdrs;
reg [31:0] DTCMWData;
reg [3:0] DTCMWEn;
reg DTCMEn;
reg [17:0] DTCMAdrs;
reg SCANOUT1;
reg SCANOUT2;
reg SCANOUT3;
reg SCANOUT4;
reg [11:0] cpsr;
reg [11:0] spsrfiq;
reg [11:0] spsrirq;
reg [11:0] spsrsvc;
reg [11:0] spsrabt;
reg [11:0] spsrund;
reg [31:0] r0;
reg [31:0] r1;
reg [31:0] r2;
reg [31:0] r3;
reg [31:0] r4;
reg [31:0] r5;
reg [31:0] r6;
reg [31:0] r7;
reg [31:0] r8;
reg [31:0] r9;
reg [31:0] r10;
reg [31:0] r11;
reg [31:0] r12;
reg [31:0] r13;
reg [31:0] r14;
reg [31:0] r15;
reg [31:0] r13irq;
reg [31:0] r14irq;
reg [31:0] r13svc;
reg [31:0] r14svc;
reg [31:0] r13abt;
reg [31:0] r14abt;
reg [31:0] r13und;
reg [31:0] r14und;
reg [31:0] r8fiq;
reg [31:0] r9fiq;
reg [31:0] r10fiq;
reg [31:0] r11fiq;
reg [31:0] r12fiq;
reg [31:0] r13fiq;
reg [31:0] r14fiq;
initial
  begin
    $mm("ARM946E_88?rev=r1",HBUSREQ,
    HLOCK,
    HADDR,
    HTRANS,
    HWRITE,
    HSIZE,
    HBURST,
    HPROT,
    HWDATA,
    CPINSTR,
    CPDOUT,
    CPPASS,
    CPLATECANCEL,
    CPTBIT,
    nCPMREQ,
    nCPTRANS,
    CPCLKEN,
    COMMRX,
    COMMTX,
    DBGACK,
    DBGRQI,
    DBGINSTREXEC,
    DBGRNG,
    DBGTDO,
    DBGIR,
    DBGSCREG,
    DBGTAPSM,
    DBGnTDOEN,
    DBGSDIN,
    BIGENDOUT,
    ETMBIGEND,
    ETMHIVECS,
    ETMIA,
    ETMInMREQ,
    ETMISEQ,
    ETMITBIT,
    ETMIABORT,
    ETMDA,
    ETMDMAS,
    ETMDMORE,
    ETMDnMREQ,
    ETMDnRW,
    ETMDSEQ,
    ETMRDATA,
    ETMDABORT,
    ETMCHSD,
    ETMCHSE,
    ETMnWAIT,
    ETMID31To25,
    ETMID15To11,
    ETMWDATA,
    ETMLATECANCEL,
    ETMPASS,
    ETMDBGACK,
    ETMINSTREXEC,
    ETMRNGOUT,
    ETMPROCID,
    ETMPROCIDWR,
    ETMINSTRVALID,
    GateTheCLK,
    ITCMWData,
    ITCMWEn,
    ITCMEn,
    ITCMAdrs,
    DTCMWData,
    DTCMWEn,
    DTCMEn,
    DTCMAdrs,
    SCANOUT1,
    SCANOUT2,
    SCANOUT3,
    SCANOUT4,
    HRESETn,
    HCLKEN,
    CLK,
    HGRANT,
    HRDATA,
    HREADY,
    HRESP,
    CPDIN,
    CHSDE,
    CHSEX,
    DBGEN,
    EDBGRQ,
    DBGEXT,
    DBGIEBKPT,
    DBGDEWPT,
    DBGnTRST,
    DBGTCKEN,
    DBGTDI,
    DBGTMS,
    DBGSDOUT,
    nFIQ,
    nIRQ,
    VINITHI,
    INITRAM,
    TAPID,
    DCacheSize,
    ICacheSize,
    ETMEN,
    SCANEN,
    TESTMODE,
    SCANIN1,
    SCANIN2,
    SCANIN3,
    SCANIN4,
    ETMFIFOFULL,
    UnGatedCLK,
    ITCMRData,
    DTCMRData,
    PhyDTCMSize,
    PhyITCMSize,
    cpsr,
    spsrfiq,
    spsrirq,
    spsrsvc,
    spsrabt,
    spsrund,
    r0,
    r1,
    r2,
    r3,
    r4,
    r5,
    r6,
    r7,
    r8,
    r9,
    r10,
    r11,
    r12,
    r13,
    r14,
    r15,
    r13irq,
    r14irq,
    r13svc,
    r14svc,
    r13abt,
    r14abt,
    r13und,
    r14und,
    r8fiq,
    r9fiq,
    r10fiq,
    r11fiq,
    r12fiq,
    r13fiq,
    r14fiq);
  end

endmodule

// Timing shell

module ARM946E_88_timing (HBUSREQ,
  HLOCK,
  HADDR,
  HTRANS,
  HWRITE,
  HSIZE,
  HBURST,
  HPROT,
  HWDATA,
  CPINSTR,
  CPDOUT,
  CPPASS,
  CPLATECANCEL,
  CPTBIT,
  nCPMREQ,
  nCPTRANS,
  CPCLKEN,
  COMMRX,
  COMMTX,
  DBGACK,
  DBGRQI,
  DBGINSTREXEC,
  DBGRNG,
  DBGTDO,
  DBGIR,
  DBGSCREG,
  DBGTAPSM,
  DBGnTDOEN,
  DBGSDIN,
  BIGENDOUT,
  ETMBIGEND,
  ETMHIVECS,
  ETMIA,
  ETMInMREQ,
  ETMISEQ,
  ETMITBIT,
  ETMIABORT,
  ETMDA,
  ETMDMAS,
  ETMDMORE,
  ETMDnMREQ,
  ETMDnRW,
  ETMDSEQ,
  ETMRDATA,
  ETMDABORT,
  ETMCHSD,
  ETMCHSE,
  ETMnWAIT,
  ETMID31To25,
  ETMID15To11,
  ETMWDATA,
  ETMLATECANCEL,
  ETMPASS,
  ETMDBGACK,
  ETMINSTREXEC,
  ETMRNGOUT,
  ETMPROCID,
  ETMPROCIDWR,
  ETMINSTRVALID,
  GateTheCLK,
  ITCMWData,
  ITCMWEn,
  ITCMEn,
  ITCMAdrs,
  DTCMWData,
  DTCMWEn,
  DTCMEn,
  DTCMAdrs,
  SCANOUT1,
  SCANOUT2,
  SCANOUT3,
  SCANOUT4,
  HRESETn,
  HCLKEN,
  CLK,
  HGRANT,
  HRDATA,
  HREADY,
  HRESP,
  CPDIN,
  CHSDE,
  CHSEX,
  DBGEN,
  EDBGRQ,
  DBGEXT,
  DBGIEBKPT,
  DBGDEWPT,
  DBGnTRST,
  DBGTCKEN,
  DBGTDI,
  DBGTMS,
  DBGSDOUT,
  nFIQ,
  nIRQ,
  VINITHI,
  INITRAM,
  TAPID,
  DCacheSize,
  ICacheSize,
  ETMEN,
  SCANEN,
  TESTMODE,
  SCANIN1,
  SCANIN2,
  SCANIN3,
  SCANIN4,
  ETMFIFOFULL,
  UnGatedCLK,
  ITCMRData,
  DTCMRData,
  PhyDTCMSize,
  PhyITCMSize,
  cpsr,
  spsrfiq,
  spsrirq,
  spsrsvc,
  spsrabt,
  spsrund,
  r0,
  r1,
  r2,
  r3,
  r4,
  r5,
  r6,
  r7,
  r8,
  r9,
  r10,
  r11,
  r12,
  r13,
  r14,
  r15,
  r13irq,
  r14irq,
  r13svc,
  r14svc,
  r13abt,
  r14abt,
  r13und,
  r14und,
  r8fiq,
  r9fiq,
  r10fiq,
  r11fiq,
  r12fiq,
  r13fiq,
  r14fiq);

output HBUSREQ;
output HLOCK;
output [31:0] HADDR;
output [1:0] HTRANS;
output HWRITE;
output [2:0] HSIZE;
output [2:0] HBURST;
output [3:0] HPROT;
output [31:0] HWDATA;
output [31:0] CPINSTR;
output [31:0] CPDOUT;
output CPPASS;
output CPLATECANCEL;
output CPTBIT;
output nCPMREQ;
output nCPTRANS;
output CPCLKEN;
output COMMRX;
output COMMTX;
output DBGACK;
output DBGRQI;
output DBGINSTREXEC;
output [1:0] DBGRNG;
output DBGTDO;
output [3:0] DBGIR;
output [4:0] DBGSCREG;
output [3:0] DBGTAPSM;
output DBGnTDOEN;
output DBGSDIN;
output BIGENDOUT;
output ETMBIGEND;
output ETMHIVECS;
output [31:1] ETMIA;
output ETMInMREQ;
output ETMISEQ;
output ETMITBIT;
output ETMIABORT;
output [31:0] ETMDA;
output [1:0] ETMDMAS;
output ETMDMORE;
output ETMDnMREQ;
output ETMDnRW;
output ETMDSEQ;
output [31:0] ETMRDATA;
output ETMDABORT;
output [1:0] ETMCHSD;
output [1:0] ETMCHSE;
output ETMnWAIT;
output [31:25] ETMID31To25;
output [15:11] ETMID15To11;
output [31:0] ETMWDATA;
output ETMLATECANCEL;
output ETMPASS;
output ETMDBGACK;
output ETMINSTREXEC;
output [1:0] ETMRNGOUT;
output [31:0] ETMPROCID;
output ETMPROCIDWR;
output ETMINSTRVALID;
output GateTheCLK;
output [31:0] ITCMWData;
output [3:0] ITCMWEn;
output ITCMEn;
output [17:0] ITCMAdrs;
output [31:0] DTCMWData;
output [3:0] DTCMWEn;
output DTCMEn;
output [17:0] DTCMAdrs;
output SCANOUT1;
output SCANOUT2;
output SCANOUT3;
output SCANOUT4;
input HRESETn;
input HCLKEN;
input CLK;
input HGRANT;
input [31:0] HRDATA;
input HREADY;
input [1:0] HRESP;
input [31:0] CPDIN;
input [1:0] CHSDE;
input [1:0] CHSEX;
input DBGEN;
input EDBGRQ;
input [1:0] DBGEXT;
input DBGIEBKPT;
input DBGDEWPT;
input DBGnTRST;
input DBGTCKEN;
input DBGTDI;
input DBGTMS;
input DBGSDOUT;
input nFIQ;
input nIRQ;
input VINITHI;
input INITRAM;
input [31:0] TAPID;
input [3:0] DCacheSize;
input [3:0] ICacheSize;
input ETMEN;
input SCANEN;
input TESTMODE;
input SCANIN1;
input SCANIN2;
input SCANIN3;
input SCANIN4;
input ETMFIFOFULL;
input UnGatedCLK;
input [31:0] ITCMRData;
input [31:0] DTCMRData;
input [3:0] PhyDTCMSize;
input [3:0] PhyITCMSize;
output [11:0] cpsr;
output [11:0] spsrfiq;
output [11:0] spsrirq;
output [11:0] spsrsvc;
output [11:0] spsrabt;
output [11:0] spsrund;
output [31:0] r0;
output [31:0] r1;
output [31:0] r2;
output [31:0] r3;
output [31:0] r4;
output [31:0] r5;
output [31:0] r6;
output [31:0] r7;
output [31:0] r8;
output [31:0] r9;
output [31:0] r10;
output [31:0] r11;
output [31:0] r12;
output [31:0] r13;
output [31:0] r14;
output [31:0] r15;
output [31:0] r13irq;
output [31:0] r14irq;
output [31:0] r13svc;
output [31:0] r14svc;
output [31:0] r13abt;
output [31:0] r14abt;
output [31:0] r13und;
output [31:0] r14und;
output [31:0] r8fiq;
output [31:0] r9fiq;
output [31:0] r10fiq;
output [31:0] r11fiq;
output [31:0] r12fiq;
output [31:0] r13fiq;
output [31:0] r14fiq;


ARM946E_88_inout theinout (HBUSREQ,
    HLOCK,
    HADDR,
    HTRANS,
    HWRITE,
    HSIZE,
    HBURST,
    HPROT,
    HWDATA,
    CPINSTR,
    CPDOUT,
    CPPASS,
    CPLATECANCEL,
    CPTBIT,
    nCPMREQ,
    nCPTRANS,
    CPCLKEN,
    COMMRX,
    COMMTX,
    DBGACK,
    DBGRQI,
    DBGINSTREXEC,
    DBGRNG,
    DBGTDO,
    DBGIR,
    DBGSCREG,
    DBGTAPSM,
    DBGnTDOEN,
    DBGSDIN,
    BIGENDOUT,
    ETMBIGEND,
    ETMHIVECS,
    ETMIA,
    ETMInMREQ,
    ETMISEQ,
    ETMITBIT,
    ETMIABORT,
    ETMDA,
    ETMDMAS,
    ETMDMORE,
    ETMDnMREQ,
    ETMDnRW,
    ETMDSEQ,
    ETMRDATA,
    ETMDABORT,
    ETMCHSD,
    ETMCHSE,
    ETMnWAIT,
    ETMID31To25,
    ETMID15To11,
    ETMWDATA,
    ETMLATECANCEL,
    ETMPASS,
    ETMDBGACK,
    ETMINSTREXEC,
    ETMRNGOUT,
    ETMPROCID,
    ETMPROCIDWR,
    ETMINSTRVALID,
    GateTheCLK,
    ITCMWData,
    ITCMWEn,
    ITCMEn,
    ITCMAdrs,
    DTCMWData,
    DTCMWEn,
    DTCMEn,
    DTCMAdrs,
    SCANOUT1,
    SCANOUT2,
    SCANOUT3,
    SCANOUT4,
    HRESETn,
    HCLKEN,
    CLK,
    HGRANT,
    HRDATA,
    HREADY,
    HRESP,
    CPDIN,
    CHSDE,
    CHSEX,
    DBGEN,
    EDBGRQ,
    DBGEXT,
    DBGIEBKPT,
    DBGDEWPT,
    DBGnTRST,
    DBGTCKEN,
    DBGTDI,
    DBGTMS,
    DBGSDOUT,
    nFIQ,
    nIRQ,
    VINITHI,
    INITRAM,
    TAPID,
    DCacheSize,
    ICacheSize,
    ETMEN,
    SCANEN,
    TESTMODE,
    SCANIN1,
    SCANIN2,
    SCANIN3,
    SCANIN4,
    ETMFIFOFULL,
    UnGatedCLK,
    ITCMRData,
    DTCMRData,
    PhyDTCMSize,
    PhyITCMSize,
    cpsr,
    spsrfiq,
    spsrirq,
    spsrsvc,
    spsrabt,
    spsrund,
    r0,
    r1,
    r2,
    r3,
    r4,
    r5,
    r6,
    r7,
    r8,
    r9,
    r10,
    r11,
    r12,
    r13,
    r14,
    r15,
    r13irq,
    r14irq,
    r13svc,
    r14svc,
    r13abt,
    r14abt,
    r13und,
    r14und,
    r8fiq,
    r9fiq,
    r10fiq,
    r11fiq,
    r12fiq,
    r13fiq,
    r14fiq);

endmodule

// Debug shell

module ARM946E_88 (HBUSREQ,
  HLOCK,
  HADDR,
  HTRANS,
  HWRITE,
  HSIZE,
  HBURST,
  HPROT,
  HWDATA,
  CPINSTR,
  CPDOUT,
  CPPASS,
  CPLATECANCEL,
  CPTBIT,
  nCPMREQ,
  nCPTRANS,
  CPCLKEN,
  COMMRX,
  COMMTX,
  DBGACK,
  DBGRQI,
  DBGINSTREXEC,
  DBGRNG,
  DBGTDO,
  DBGIR,
  DBGSCREG,
  DBGTAPSM,
  DBGnTDOEN,
  DBGSDIN,
  BIGENDOUT,
  ETMBIGEND,
  ETMHIVECS,
  ETMIA,
  ETMInMREQ,
  ETMISEQ,
  ETMITBIT,
  ETMIABORT,
  ETMDA,
  ETMDMAS,
  ETMDMORE,
  ETMDnMREQ,
  ETMDnRW,
  ETMDSEQ,
  ETMRDATA,
  ETMDABORT,
  ETMCHSD,
  ETMCHSE,
  ETMnWAIT,
  ETMID31To25,
  ETMID15To11,
  ETMWDATA,
  ETMLATECANCEL,
  ETMPASS,
  ETMDBGACK,
  ETMINSTREXEC,
  ETMRNGOUT,
  ETMPROCID,
  ETMPROCIDWR,
  ETMINSTRVALID,
  GateTheCLK,
  ITCMWData,
  ITCMWEn,
  ITCMEn,
  ITCMAdrs,
  DTCMWData,
  DTCMWEn,
  DTCMEn,
  DTCMAdrs,
  SCANOUT1,
  SCANOUT2,
  SCANOUT3,
  SCANOUT4,
  HRESETn,
  HCLKEN,
  CLK,
  HGRANT,
  HRDATA,
  HREADY,
  HRESP,
  CPDIN,
  CHSDE,
  CHSEX,
  DBGEN,
  EDBGRQ,
  DBGEXT,
  DBGIEBKPT,
  DBGDEWPT,
  DBGnTRST,
  DBGTCKEN,
  DBGTDI,
  DBGTMS,
  DBGSDOUT,
  nFIQ,
  nIRQ,
  VINITHI,
  INITRAM,
  TAPID,
  DCacheSize,
  ICacheSize,
  ETMEN,
  SCANEN,
  TESTMODE,
  SCANIN1,
  SCANIN2,
  SCANIN3,
  SCANIN4,
  ETMFIFOFULL,
  UnGatedCLK,
  ITCMRData,
  DTCMRData,
  PhyDTCMSize,
  PhyITCMSize);

output HBUSREQ;
output HLOCK;
output [31:0] HADDR;
output [1:0] HTRANS;
output HWRITE;
output [2:0] HSIZE;
output [2:0] HBURST;
output [3:0] HPROT;
output [31:0] HWDATA;
output [31:0] CPINSTR;
output [31:0] CPDOUT;
output CPPASS;
output CPLATECANCEL;
output CPTBIT;
output nCPMREQ;
output nCPTRANS;
output CPCLKEN;
output COMMRX;
output COMMTX;
output DBGACK;
output DBGRQI;
output DBGINSTREXEC;
output [1:0] DBGRNG;
output DBGTDO;
output [3:0] DBGIR;
output [4:0] DBGSCREG;
output [3:0] DBGTAPSM;
output DBGnTDOEN;
output DBGSDIN;
output BIGENDOUT;
output ETMBIGEND;
output ETMHIVECS;
output [31:1] ETMIA;
output ETMInMREQ;
output ETMISEQ;
output ETMITBIT;
output ETMIABORT;
output [31:0] ETMDA;
output [1:0] ETMDMAS;
output ETMDMORE;
output ETMDnMREQ;
output ETMDnRW;
output ETMDSEQ;
output [31:0] ETMRDATA;
output ETMDABORT;
output [1:0] ETMCHSD;
output [1:0] ETMCHSE;
output ETMnWAIT;
output [31:25] ETMID31To25;
output [15:11] ETMID15To11;
output [31:0] ETMWDATA;
output ETMLATECANCEL;
output ETMPASS;
output ETMDBGACK;
output ETMINSTREXEC;
output [1:0] ETMRNGOUT;
output [31:0] ETMPROCID;
output ETMPROCIDWR;
output ETMINSTRVALID;
output GateTheCLK;
output [31:0] ITCMWData;
output [3:0] ITCMWEn;
output ITCMEn;
output [17:0] ITCMAdrs;
output [31:0] DTCMWData;
output [3:0] DTCMWEn;
output DTCMEn;
output [17:0] DTCMAdrs;
output SCANOUT1;
output SCANOUT2;
output SCANOUT3;
output SCANOUT4;
input HRESETn;
input HCLKEN;
input CLK;
input HGRANT;
input [31:0] HRDATA;
input HREADY;
input [1:0] HRESP;
input [31:0] CPDIN;
input [1:0] CHSDE;
input [1:0] CHSEX;
input DBGEN;
input EDBGRQ;
input [1:0] DBGEXT;
input DBGIEBKPT;
input DBGDEWPT;
input DBGnTRST;
input DBGTCKEN;
input DBGTDI;
input DBGTMS;
input DBGSDOUT;
input nFIQ;
input nIRQ;
input VINITHI;
input INITRAM;
input [31:0] TAPID;
input [3:0] DCacheSize;
input [3:0] ICacheSize;
input ETMEN;
input SCANEN;
input TESTMODE;
input SCANIN1;
input SCANIN2;
input SCANIN3;
input SCANIN4;
input ETMFIFOFULL;
input UnGatedCLK;
input [31:0] ITCMRData;
input [31:0] DTCMRData;
input [3:0] PhyDTCMSize;
input [3:0] PhyITCMSize;


// Unused ports:

wire [11:0] cpsr;
wire [11:0] spsrfiq;
wire [11:0] spsrirq;
wire [11:0] spsrsvc;
wire [11:0] spsrabt;
wire [11:0] spsrund;
wire [31:0] r0;
wire [31:0] r1;
wire [31:0] r2;
wire [31:0] r3;
wire [31:0] r4;
wire [31:0] r5;
wire [31:0] r6;
wire [31:0] r7;
wire [31:0] r8;
wire [31:0] r9;
wire [31:0] r10;
wire [31:0] r11;
wire [31:0] r12;
wire [31:0] r13;
wire [31:0] r14;
wire [31:0] r15;
wire [31:0] r13irq;
wire [31:0] r14irq;
wire [31:0] r13svc;
wire [31:0] r14svc;
wire [31:0] r13abt;
wire [31:0] r14abt;
wire [31:0] r13und;
wire [31:0] r14und;
wire [31:0] r8fiq;
wire [31:0] r9fiq;
wire [31:0] r10fiq;
wire [31:0] r11fiq;
wire [31:0] r12fiq;
wire [31:0] r13fiq;
wire [31:0] r14fiq;

parameter
  ID = 0,
  ICACHE_SIZE = 8192,
  DCACHE_SIZE = 8192,
  MG_LOGFILE_NAME = "",
  MG_BUILTIN_TIMING_MESSAGES = 1,
  ARM946E_88_TimingFile = "./ARM946E_88.tdef",
  MG_ENABLE_BUILTIN_TIMING = 1,
  MG_FORCED_DELAY = 0;

ARM946E_88_timing thetiming (HBUSREQ,
    HLOCK,
    HADDR,
    HTRANS,
    HWRITE,
    HSIZE,
    HBURST,
    HPROT,
    HWDATA,
    CPINSTR,
    CPDOUT,
    CPPASS,
    CPLATECANCEL,
    CPTBIT,
    nCPMREQ,
    nCPTRANS,
    CPCLKEN,
    COMMRX,
    COMMTX,
    DBGACK,
    DBGRQI,
    DBGINSTREXEC,
    DBGRNG,
    DBGTDO,
    DBGIR,
    DBGSCREG,
    DBGTAPSM,
    DBGnTDOEN,
    DBGSDIN,
    BIGENDOUT,
    ETMBIGEND,
    ETMHIVECS,
    ETMIA,
    ETMInMREQ,
    ETMISEQ,
    ETMITBIT,
    ETMIABORT,
    ETMDA,
    ETMDMAS,
    ETMDMORE,
    ETMDnMREQ,
    ETMDnRW,
    ETMDSEQ,
    ETMRDATA,
    ETMDABORT,
    ETMCHSD,
    ETMCHSE,
    ETMnWAIT,
    ETMID31To25,
    ETMID15To11,
    ETMWDATA,
    ETMLATECANCEL,
    ETMPASS,
    ETMDBGACK,
    ETMINSTREXEC,
    ETMRNGOUT,
    ETMPROCID,
    ETMPROCIDWR,
    ETMINSTRVALID,
    GateTheCLK,
    ITCMWData,
    ITCMWEn,
    ITCMEn,
    ITCMAdrs,
    DTCMWData,
    DTCMWEn,
    DTCMEn,
    DTCMAdrs,
    SCANOUT1,
    SCANOUT2,
    SCANOUT3,
    SCANOUT4,
    HRESETn,
    HCLKEN,
    CLK,
    HGRANT,
    HRDATA,
    HREADY,
    HRESP,
    CPDIN,
    CHSDE,
    CHSEX,
    DBGEN,
    EDBGRQ,
    DBGEXT,
    DBGIEBKPT,
    DBGDEWPT,
    DBGnTRST,
    DBGTCKEN,
    DBGTDI,
    DBGTMS,
    DBGSDOUT,
    nFIQ,
    nIRQ,
    VINITHI,
    INITRAM,
    TAPID,
    DCacheSize,
    ICacheSize,
    ETMEN,
    SCANEN,
    TESTMODE,
    SCANIN1,
    SCANIN2,
    SCANIN3,
    SCANIN4,
    ETMFIFOFULL,
    UnGatedCLK,
    ITCMRData,
    DTCMRData,
    PhyDTCMSize,
    PhyITCMSize,
    cpsr,
    spsrfiq,
    spsrirq,
    spsrsvc,
    spsrabt,
    spsrund,
    r0,
    r1,
    r2,
    r3,
    r4,
    r5,
    r6,
    r7,
    r8,
    r9,
    r10,
    r11,
    r12,
    r13,
    r14,
    r15,
    r13irq,
    r14irq,
    r13svc,
    r14svc,
    r13abt,
    r14abt,
    r13und,
    r14und,
    r8fiq,
    r9fiq,
    r10fiq,
    r11fiq,
    r12fiq,
    r13fiq,
    r14fiq);

endmodule

