library verilog;
use verilog.vl_types.all;
entity tbspi is
    generic(
        spicon          : integer := 0;
        spipre          : integer := 4;
        spista          : integer := 8;
        spiintdma       : integer := 12;
        spiintsta       : integer := 16;
        spitxdat        : integer := 20;
        spirxdat        : integer := 24;
        spihidden       : integer := 28;
        enable          : integer := 8;
        masterslave     : integer := 4;
        cpha            : integer := 2;
        cpol            : integer := 1;
        prescalval      : integer := 255;
        divval          : integer := 65280;
        txfifofull      : integer := 32;
        txfifoempty     : integer := 16;
        rxfifofull      : integer := 8;
        rxfifoempty     : integer := 4;
        busy            : integer := 2;
        error           : integer := 1;
        txfifoint       : integer := 8192;
        rxfifoint       : integer := 4096;
        rxtimeoutint    : integer := 2048;
        rxoverrunint    : integer := 1024;
        txdmaenable     : integer := 512;
        txdmalevel      : integer := 480;
        rxdmaenable     : integer := 16;
        rxdmalevel      : integer := 15;
        rtic            : integer := 32;
        roric           : integer := 16;
        txfifointsta    : integer := 8;
        rxfifointsta    : integer := 4;
        rxtimeoutintsta : integer := 2;
        rxoverrunintsta : integer := 1;
        txdat           : integer := 65535;
        rxdat           : integer := 65535;
        datasize        : integer := 240;
        datasize8       : integer := 112;
        mode            : integer := 12;
        slaveouten      : integer := 2;
        lbm             : integer := 1;
        ckp             : integer := 5;
        dly             : integer := 10
    );
end tbspi;
